### PR TITLE
Kokkos morse

### PR DESCRIPTION
**Pull request by Pakketeretet2**
This PR contains a KOKKOS-enabled pair_style for the Morse potential. The modification of allocate to virtual in pair_morse.h seems to be necessary to prevent a segfault at the moment Pair::init_one is called.

I hope this is better. I think I mixed up the new and old master in the tutorial I found. :]

### CODE REVIEW

**Comment by akohlmey** [comment]
@Pakketeretet2 would you mind including the necessary changes to the documentation?

**Comment by akohlmey** [comment]
@stanmoore1 i see that most kokkos styles put a check on `copymode` into the destructor of the base class, but i don't see it here (and in a select few other styles). Is this a thing that, like the `-DLAMMPS_BIGBIG` should be done consistently to avoid hard to find issues in the future?

related to that, `pair.h` has a `set_copymode()` function, but nothing seems to be using it, but rather sets the `copymode` variable directly. we should either use it consistently or get rid of it.

**Comment by Pakketeretet2** [comment]
Sure, I forgot about it, will add the changes tomorrow.

**Comment by stanmoore1** [comment]
@Pakketeretet2 The documentation would be just adding one thing: Add "pair_style morse/kk" to the list of pair styles at the top of /doc/src/pair_morse.txt

**Comment by stanmoore1** [comment]
@Pakketeretet2 One small tweak, can you move the contributing author acknowledgment to the .cpp file instead of the .h file for consistency with other pair styles in LAMMPS? For an example, you can take a look at pair_eam_kokkos.cpp. I tested this on OpenMP and GPU and as far as I can tell it works great, thanks for porting this.

@akohlmey Simple pair styles like LJ and morse fit into the `pair_kokkos.h` framework that @crtrott setup, which uses the `cleanup_copy()` function instead of setting `copymode`. Ideally we should make everything consistent, but this does work correctly without `copymode`.

**Comment by stanmoore1** [comment]
@akohlmey Also I will remove the `set_copymode()` function, thanks.

**Comment by stanmoore1** [comment]
@Pakketeretet2 Thanks, I am assigning this to @sjplimp for inclusion into Master.

**Pull request merged**
