### PR TITLE
Makefile for Arch Linux

### PR DESCRIPTION
**Pull request by Pakketeretet2**
This is part of the GitHub Tutorial. I added my custom Arch Linux Makefile to the repository.

### CODE REVIEW

**Comment by Pakketeretet2** [comment]
As additional modification I added a PairStyle for a linearly smoothed Morse potential.

**Comment by akohlmey** [comment]
Can you please explain what in your makefile is required for Arch Linux that is not in Makefile.mpi.

Also, in order to have your modified morse pair style included, can you please add documentation for it, e.g. by including extra text and a suitable formula (including latex source) to doc/pair_morse.txt.

thanks, axel.

**Comment by Pakketeretet2** [comment]
About the Makefiles: There is not a lot of difference. I added fftw3, ffmpg, libpng, libjpeg and voro++ variables so that make checks the default installation paths for those. However, I now found out that the default MPI-Makefile also works fine on Arch, so I don't think there is much need to add it. I will add documentation to the pair_style now.

**Comment by akohlmey** [comment]
i've selectively merged the pair style and moved it to the USER-MISC package, where such contributions usually end up, and updated the docs accordingly. i had to redo the formula, since steve always wants the tex source, too.  will forward the changes to steve tomorrow. closing this pull request now.

**Comment by Pakketeretet2** [comment]
Alright, cheers.

**Pull request closed without merging**
