### PR TITLE
Add trim option to skip neighbor list build styles

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

The neighbor list `skip` styles can add new neighbor lists. When neighbor "trimming" is enabled this can lead to the creation of several extra lists. This PR extends skip styles to use trimming to be more efficient. This also fixes a potential bug in the neighbor list sorting by cutoff required for trimming.

**Related Issue(s)**

This PR conflicts with https://github.com/lammps/lammps/pull/3430, but hopefully the changes are trivial. If https://github.com/lammps/lammps/pull/3430 is merged before this PR, I will update.

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
To illustrate the issue, the old code builds 12 neighbor lists and several are not used:
```
  12 neighbor lists, perpetual/occasional/extra = 12 0 0
  (1) pair oxdna2/hbond, perpetual, trim from (4)
      attributes: half, newton on, cut 8.783775457904158
      pair build: trim
      stencil: none
      bin: none
  (2) pair oxdna2/xstk, perpetual, trim from (6)
      attributes: half, newton on, cut 8.7
      pair build: trim
      stencil: none
      bin: none
  (3) pair oxdna2/coaxstk, perpetual, trim from (2)
      attributes: half, newton on, cut 8.622222222222222
      pair build: trim
      stencil: none
      bin: none
  (4) pair oxdna2/dh, perpetual, skip from (10)
      attributes: half, newton on
      pair build: skip
      stencil: none
      bin: none
  (5) pair lj/cut, perpetual, skip from (11)
      attributes: half, newton on, cut 9.1225
      pair build: skip
      stencil: none
      bin: none
  (6) pair oxdna2/excv, perpetual, trim from (1)
      attributes: half, newton on, cut 8.711879214356259
      pair build: trim
      stencil: none
      bin: none
  (7) neighbor class addition, perpetual, trim from (11)
      attributes: half, newton on, cut 8.783775457904158
      pair build: trim
      stencil: none
      bin: none
  (8) neighbor class addition, perpetual, trim from (7)
      attributes: half, newton on, cut 8.7
      pair build: trim
      stencil: none
      bin: none
  (9) neighbor class addition, perpetual, trim from (8)
      attributes: half, newton on, cut 8.622222222222222
      pair build: trim
      stencil: none
      bin: none
  (10) neighbor class addition, perpetual
      attributes: half, newton on
      pair build: half/bin/newton
      stencil: half/bin/3d
      bin: standard
  (11) neighbor class addition, perpetual, trim from (10)
      attributes: half, newton on, cut 9.1225
      pair build: trim
      stencil: none
      bin: none
  (12) neighbor class addition, perpetual, trim from (7)
      attributes: half, newton on, cut 8.711879214356259
      pair build: trim
      stencil: none
      bin: none
```

while the new code builds only 7 lists:
```
  7 neighbor lists, perpetual/occasional/extra = 7 0 0
  (1) pair oxdna2/hbond, perpetual, trim from (4)
      attributes: half, newton on, cut 8.783775457904158
      pair build: trim
      stencil: none
      bin: none
  (2) pair oxdna2/xstk, perpetual, trim from (6)
      attributes: half, newton on, cut 8.7
      pair build: trim
      stencil: none
      bin: none
  (3) pair oxdna2/coaxstk, perpetual, trim from (2)
      attributes: half, newton on, cut 8.622222222222222
      pair build: trim
      stencil: none
      bin: none
  (4) pair oxdna2/dh, perpetual, skip from (7)
      attributes: half, newton on
      pair build: skip
      stencil: none
      bin: none
  (5) pair lj/cut, perpetual, skip trim from (7)
      attributes: half, newton on, cut 9.1225
      pair build: skip/trim
      stencil: none
      bin: none
  (6) pair oxdna2/excv, perpetual, trim from (1)
      attributes: half, newton on, cut 8.711879214356259
      pair build: trim
      stencil: none
      bin: none
  (7) neighbor class addition, perpetual
      attributes: half, newton on
      pair build: half/bin/newton
      stencil: half/bin/3d
      bin: standard
```

**Comment by stanmoore1** [comment]
Kokkos regression tests passed on GPU and CPU. @akohlmey is there an easy way to debug the failing unit tests?

**Review by sjplimp — APPROVED** [review]

**Comment by akohlmey** [comment]
> Kokkos regression tests passed on GPU and CPU. @akohlmey is there an easy way to debug the failing unit tests?

You can follow the links to, e.g.: https://ci.lammps.org/job/dev/job/pull_requests/job/fedora/job/unit_tests/job/cmake_serial_kokkos_smallbig_shared/2538/testReport/junit/projectroot.unittest/force-styles/AtomicPairStyle_hybrid_eam/

Which shows that the OPENMP tests fail for hybrid with lj/cut and eam with either a segfault or an error. Those have the following pair style/coeff settings.

```
pair_style: hybrid lj/cut 8.0 eam/fs
pair_coeff: ! |
  1 * lj/cut 0.01014 3.0
  * * eam/fs AlFe_mm.eam.fs NULL Al
```

```
pair_style: hybrid lj/cut 8.0 eam
pair_coeff: ! |
  1 * lj/cut 0.01014 3.0
  2 2 eam Ni_u3.eam
```

**Comment by akohlmey** [comment]
@stanmoore1 Here is an explicit  reproducer based on the in.eam benchmark:
```
# bulk Cu lattice

variable        x index 1
variable        y index 1
variable        z index 1

variable        xx equal 20*$x
variable        yy equal 20*$y
variable        zz equal 20*$z

units           metal
atom_style      atomic

lattice         fcc 3.615
region          box block 0 ${xx} 0 ${yy} 0 ${zz}
create_box      2 box
create_atoms    1 box

mass 2 1.0

pair_style      hybrid eam lj/cut 10.0
pair_coeff      * * lj/cut 0.0 1.0
pair_coeff      1 1 eam Cu_u3.eam

velocity        all create 1600.0 376847 loop geom

neighbor        1.0 bin
neigh_modify    every 1 delay 5 check yes

fix             1 all nve

timestep        0.005
thermo          50

run             100
```

Which results in:
```
$ ./lmp -in in.eam -sf omp
LAMMPS (3 Aug 2023 - Development - patch_2Aug2023-818-g5c813d2bac)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
using multi-threaded neighbor list subroutines
Lattice spacing in x,y,z = 3.615 3.615 3.615
Created orthogonal box = (0 0 0) to (72.3 72.3 72.3)
  1 by 1 by 1 MPI processor grid
Created 32000 atoms
  using lattice units in orthogonal box = (0 0 0) to (72.3 72.3 72.3)
  create_atoms CPU = 0.002 seconds
Reading eam potential file Cu_u3.eam with DATE: 2007-06-11
Hybrid pair style last /omp style lj/cut
Last active /omp style is pair_style lj/cut
ERROR: Requested neighbor pair method does not exist (src/neighbor.cpp:943)
Last command: run             100
```

**Comment by akohlmey** [comment]
@stanmoore1 I have a change to the unit test source, that should make it easier to see the error message from the CI log files. If you want, we can try it on this PR and see if that is going to help, or I can keep it for later (and port it to other tests).

**Comment by akohlmey** [comment]
The output of the failing tests will become something like this:
```
284: Test command: /home/akohlmey/compile/lammps/build-gui/test_pair_style "/home/akohlmey/compile/lammps/unittest/force-styles/tests/atomic-pair-hybrid-eam_fs.yaml"
284: Working Directory: /home/akohlmey/compile/lammps/build-gui/unittest/force-styles
284: Environment variables: 
284:  PYTHONPATH=/home/akohlmey/compile/lammps/unittest/force-styles/tests:
284:  PYTHONUNBUFFERED=1
284:  PYTHONDONTWRITEBYTECODE=1
284:  OMP_PROC_BIND=false
284:  LAMMPS_POTENTIALS=/home/akohlmey/compile/lammps/potentials
284:  LD_LIBRARY_PATH=/home/akohlmey/compile/lammps/build-gui:/home/akohlmey/.local/lib:/usr/lib64/mpich/lib
284: Test timeout computed to be: 1500
284: [==========] Running 8 tests from 1 test suite.
284: [----------] Global test environment set-up.
284: [----------] 8 tests from PairStyle
284: [ RUN      ] PairStyle.plain
284: [       OK ] PairStyle.plain (258 ms)
284: [ RUN      ] PairStyle.omp
284: LAMMPS Error: ERROR: Requested neighbor pair method does not exist (src/neighbor.cpp:943)
284: 
2/2 Test #284: AtomicPairStyle:hybrid-eam_fs ....***Failed    0.71 sec

0% tests passed, 2 tests failed out of 2
```

**Comment by stanmoore1** [comment]
@akohlmey thanks that was helpful, I missed the OPENMP and INTEL skip styles, will update soon. I also restructured the commits in this PR to separate out the bug fixes: 718cfc4562150ad87dc1def13003f0060ce8de39 and 6f366b8c74a4eb2aa3ddd7718f6ffa4666e2dd62 need to be ported to https://github.com/lammps/lammps/pull/3933 while other commits should not be ported as they have the possibility of introducing a new bug.

**Comment by stanmoore1** [comment]
> LAMMPS Error: ERROR: Requested neighbor pair method does not exist (src/neighbor.cpp:943)

@akohlmey I really like this enhancement!

**Comment by akohlmey** [comment]
> > LAMMPS Error: ERROR: Requested neighbor pair method does not exist (src/neighbor.cpp:943)
> 
> @akohlmey I really like this enhancement!

It is included it in PR #3976 now.

**Comment by stanmoore1** [comment]
Regression tests passed again. I also ran OPENMP and INTEL packages on a test case. This is ready to merge from my POV.

**Pull request merged**
