### PR TITLE
Kokkos accelerated variant for adp pair style

### LINKED ISSUE #2405: [Feature Request] Add GPU support for pair style adp
**Summary**

Request for adding GPU support to pair style adp potential

**Detailed Description**

ADP potentials is a generalization of EAM potentials. They have an additional terms of dipole and quadrupole moments. Is the implementation of “adp/gpu” acceleration and GPU support for pair style adp planned for the future?

Thank you.

### PR DESCRIPTION
**Pull request by vladgl**
**Summary**

Implementation of the adp/kk accelerated variant of the angular dependent potential model.

**Related Issues**

Implements and thus closes #2405 

**Author(s)**

Vladislav Galigerov @vladgl vladgl3@yandex.ru (Higher School of Economics, Russia)
Vsevolod Nikolskiy @Vsevak thevsevak@gmail.com (Higher School of Economics, Russia)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

There are no changes in this pull request that will break backward compatibility for inputs.

**Implementation Notes**

Additionally, copymode flag check was added in PairADP destructor to avoid segmentation fault, as it is necessary when classes are used as functors by Kokkos. Also, file2array and array2spline methods were made virtual.

Correctness was approved by comparing dump information on 1000 steps for positions, forces and energies with an existing MANYBODY/pair_adp implementation (checks were made for serial, omp and cuda backends).

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@vladgl @Vsevak thanks for your contribution. I've done some minor cosmetic updates and merged in the latest development sources from upstream.

When I test locally, there is a problem with the included unit tests. The computed stress with `pair_modify nofdotr` does not match which means that something is amiss with the tallying of the per-atom / global stress. I run the local test using KOKKOS OpenMP, but it likely would apply to the GPU backends as well (we don't have support for running tests with those yet).

```
$ ctest -R adp -V
UpdateCTestConfiguration  from :/home/akohlmey/compile/lammps/build-test/DartConfiguration.tcl
Parse Config file:/home/akohlmey/compile/lammps/build-test/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/akohlmey/compile/lammps/build-test/DartConfiguration.tcl
Parse Config file:/home/akohlmey/compile/lammps/build-test/DartConfiguration.tcl
Test project /home/akohlmey/compile/lammps/build-test
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 218
    Start 218: AtomicPairStyle:adp

218: Test command: /home/akohlmey/compile/lammps/build-test/test_pair_style "/home/akohlmey/compile/lammps/unittest/force-styles/tests/atomic-pair-adp.yaml"
218: Environment variables: 
218:  PYTHONPATH=/home/akohlmey/compile/lammps/unittest/force-styles/tests:
218:  PYTHONUNBUFFERED=1
218:  OMP_PROC_BIND=false
218:  LAMMPS_POTENTIALS=/home/akohlmey/compile/lammps/potentials
218:  LD_LIBRARY_PATH=/home/akohlmey/compile/lammps/build-test:/home/akohlmey/.local/lib:/usr/lib64/mpich/lib
218: Test timeout computed to be: 1500
218: [==========] Running 8 tests from 1 test suite.
218: [----------] Global test environment set-up.
218: [----------] 8 tests from PairStyle
218: [ RUN      ] PairStyle.plain
218: [       OK ] PairStyle.plain (269 ms)
218: [ RUN      ] PairStyle.omp
218: [       OK ] PairStyle.omp (108 ms)
218: [ RUN      ] PairStyle.kokkos_omp
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:43: Failure
218: Expected: (err) <= (epsilon)
218:   Actual: 0.068581014854455252 vs 2.4999999999999998e-11
218: Google Test trace:
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:41: EXPECT_STRESS: nofdotr_stress
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:44: Failure
218: Expected: (err) <= (epsilon)
218:   Actual: 0.027127444881897365 vs 2.4999999999999998e-11
218: Google Test trace:
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:41: EXPECT_STRESS: nofdotr_stress
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:45: Failure
218: Expected: (err) <= (epsilon)
218:   Actual: 0.059467874393049319 vs 2.4999999999999998e-11
218: Google Test trace:
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:41: EXPECT_STRESS: nofdotr_stress
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:46: Failure
218: Expected: (err) <= (epsilon)
218:   Actual: 0.03339372267269259 vs 2.4999999999999998e-11
218: Google Test trace:
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:41: EXPECT_STRESS: nofdotr_stress
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:47: Failure
218: Expected: (err) <= (epsilon)
218:   Actual: 0.44850515300529609 vs 2.4999999999999998e-11
218: Google Test trace:
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:41: EXPECT_STRESS: nofdotr_stress
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:48: Failure
218: Expected: (err) <= (epsilon)
218:   Actual: 0.035511227429342741 vs 2.4999999999999998e-11
218: Google Test trace:
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_main.cpp:41: EXPECT_STRESS: nofdotr_stress
218: [  FAILED  ] PairStyle.kokkos_omp (114 ms)
218: [ RUN      ] PairStyle.gpu
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_pair_style.cpp:744: Skipped
218: 
218: [  SKIPPED ] PairStyle.gpu (0 ms)
218: [ RUN      ] PairStyle.intel
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_pair_style.cpp:839: Skipped
218: 
218: [  SKIPPED ] PairStyle.intel (0 ms)
218: [ RUN      ] PairStyle.opt
218: One or more prerequisite styles with /opt suffix
218: are not available in this LAMMPS configuration:
218: pair_style adp
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_pair_style.cpp:947: Skipped
218: 
218: [  SKIPPED ] PairStyle.opt (0 ms)
218: [ RUN      ] PairStyle.single
218: Single method not available for pair style adp
218: /home/akohlmey/compile/lammps/unittest/force-styles/test_pair_style.cpp:1058: Skipped
218: 
218: [  SKIPPED ] PairStyle.single (55 ms)
218: [ RUN      ] PairStyle.extract
218: [       OK ] PairStyle.extract (102 ms)
218: [----------] 8 tests from PairStyle (652 ms total)
218: 
218: [----------] Global test environment tear-down
218: [==========] 8 tests from 1 test suite ran. (652 ms total)
218: [  PASSED  ] 3 tests.
218: [  SKIPPED ] 4 tests, listed below:
218: [  SKIPPED ] PairStyle.gpu
218: [  SKIPPED ] PairStyle.intel
218: [  SKIPPED ] PairStyle.opt
218: [  SKIPPED ] PairStyle.single
218: [  FAILED  ] 1 test, listed below:
218: [  FAILED  ] PairStyle.kokkos_omp
218: 
218:  1 FAILED TEST
1/1 Test #218: AtomicPairStyle:adp ..............***Failed    0.68 sec
```

**Comment by vladgl** [comment]
@akohlmey thank you for reply. Issue was in virial computation, I have fixed it in #[4ef8ca0](https://github.com/lammps/lammps/pull/3247/commits/4ef8ca091d33e1575f22dcd48f5e6013f1838e74).
Now this test pass:


UpdateCTestConfiguration  from :/home/pullo/lammps/build-test/DartConfiguration.tcl
Parse Config file:/home/pullo/lammps/build-test/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/pullo/lammps/build-test/DartConfiguration.tcl
Parse Config file:/home/pullo/lammps/build-test/DartConfiguration.tcl
Test project /home/pullo/lammps/build-test
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 196
    Start 196: AtomicPairStyle:adp

196: Test command: /home/pullo/lammps/build-test/test_pair_style "/home/pullo/lammps/unittest/force-styles/tests/atomic-pair-adp.yaml"
196: Environment variables:
196:  PYTHONPATH=/home/pullo/lammps/unittest/force-styles/tests:
196:  PYTHONUNBUFFERED=1
196:  OMP_PROC_BIND=false
196:  LAMMPS_POTENTIALS=/home/pullo/lammps/potentials
196:  LD_LIBRARY_PATH=/home/pullo/lammps/build-test:
196: Test timeout computed to be: 1500
196: [==========] Running 8 tests from 1 test suite.
196: [----------] Global test environment set-up.
196: [----------] 8 tests from PairStyle
196: [ RUN      ] PairStyle.plain
196: [       OK ] PairStyle.plain (344 ms)
196: [ RUN      ] PairStyle.omp
196: /home/pullo/lammps/unittest/force-styles/test_pair_style.cpp:499: Skipped
196:
196: [  SKIPPED ] PairStyle.omp (0 ms)
196: [ RUN      ] PairStyle.kokkos_omp
196: [       OK ] PairStyle.kokkos_omp (137 ms)
196: [ RUN      ] PairStyle.gpu
196: /home/pullo/lammps/unittest/force-styles/test_pair_style.cpp:744: Skipped
196:
196: [  SKIPPED ] PairStyle.gpu (0 ms)
196: [ RUN      ] PairStyle.intel
196: /home/pullo/lammps/unittest/force-styles/test_pair_style.cpp:839: Skipped
196:
196: [  SKIPPED ] PairStyle.intel (0 ms)
196: [ RUN      ] PairStyle.opt
196: /home/pullo/lammps/unittest/force-styles/test_pair_style.cpp:927: Skipped
196:
196: [  SKIPPED ] PairStyle.opt (0 ms)
196: [ RUN      ] PairStyle.single
196: One or more prerequisite styles are not available in this LAMMPS configuration:
196: pair_style adp
196: atom_style full
196: /home/pullo/lammps/unittest/force-styles/test_pair_style.cpp:1036: Skipped
196:
196: [  SKIPPED ] PairStyle.single (1 ms)
196: [ RUN      ] PairStyle.extract
196: [       OK ] PairStyle.extract (125 ms)
196: [----------] 8 tests from PairStyle (609 ms total)
196:
196: [----------] Global test environment tear-down
196: [==========] 8 tests from 1 test suite ran. (609 ms total)
196: [  PASSED  ] 3 tests.
196: [  SKIPPED ] 5 tests, listed below:
196: [  SKIPPED ] PairStyle.omp
196: [  SKIPPED ] PairStyle.gpu
196: [  SKIPPED ] PairStyle.intel
196: [  SKIPPED ] PairStyle.opt
196: [  SKIPPED ] PairStyle.single
1/1 Test #196: AtomicPairStyle:adp ..............   Passed    1.01 sec

The following tests passed:
        AtomicPairStyle:adp

**Comment by sjplimp** [comment]
@akohlmey Stan should decide on this one

**Review by stanmoore1 — APPROVED** [review]

**Comment by vladgl** [comment]
@akohlmey Thanks for your review. 
There are one input script and potential file for pair adp in bench/POTENTIALS.

**Comment by stanmoore1** [comment]
@vladgl I messed up my run--here is the real profile, it looks great:

```
==157791== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   42.33%  125.69ms        98  1.2825ms  1.1510ms  1.3595ms  _ZN6Kokkos4Impl36cuda_parallel_launch_constant_memoryINS0_11ParallelForIN9LAMMPS_NS13PairADPKokkosINS_4CudaEEENS_11RangePolicyIJS5_NS3_17TagPairADPKernelCILi2ELi0ELi0EEEEEES5_EEEEvv
                   35.65%  105.87ms       101  1.0483ms  515.35us  1.1223ms  _ZN6Kokkos4Impl36cuda_parallel_launch_constant_memoryINS0_11ParallelForIN9LAMMPS_NS13PairADPKokkosINS_4CudaEEENS_11RangePolicyIJS5_NS3_17TagPairADPKernelAILi2ELi0EEEEEES5_EEEEvv
                    7.30%  21.690ms      4904  4.4220us  1.6630us  43.040us  [CUDA memcpy DtoH]
                    4.16%  12.368ms      3154  3.9210us  1.2800us  60.160us  [CUDA memcpy HtoD]
```

**Pull request merged**
