### PR TITLE
Bond/react custom group

### PR DESCRIPTION
**Pull request by jrgissing**
## Purpose

allow bond/react to act on user-defined groups, even when using stabilization option

## Author(s)

JG

## Backward Compatibility

no

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@jrgissing I don't like the behavior for existing groups. A fix should not change a group it hasn't created. Why can't you just use the existing static group as parent group and create a new dynamic group using that name with '_REACT' appended?

**Comment by jrgissing** [comment]
@akohlmey that was also my initial instinct. my concern is, that way, the group is less intuitive to reference later, and also breaks backward compatibility

**Comment by akohlmey** [comment]
@jrgissing i consider consistency across the code much more important that backward compatibility of a new feature. I am a big fan of the principle of least surprise and having a fix change/recreate a group with different settings is a big surprise and very unexpected when looking at the rest of LAMMPS.

**Comment by jrgissing** [comment]
agreed, thanks for catching this. will update this weekend

**Pull request merged**
