### PR TITLE
types in gather_atoms updated from 0 and 1 to LAMMPS_INT and LAMMPS_D…

### PR DESCRIPTION
**Pull request by liviabp**
…OUBLE to be consistent with library.cpp

**Summary**

gather_atoms in lammps.py failed to extract information as type==1 no longer meant double

**Related Issue(s)**

Within library.cpp, the changes 0--> LAMMPS_INT and 1-->LAMMPS_DOUBLE had been done for gather atoms only, and not in e.g. gather_atoms_concat or in scatter_atoms, causing some inconsistency in the code. Shouldn't this be addressed, especially that LAMMPS_DOUBLE=2 ? 

**Author(s)**

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by rbberger** [comment]
@liviabp Thanks for pointing out the inconsistency. Indeed the change in `lammps_gather_atoms` seems to have been done by mistake. Because the gather/scatter methods were using different "magic numbers", they shouldn't have been touched at all for the last release to ensure backwards compatibility. Oh well...

@akohlmey I traced this back to 68b533d1b8c33a8d0ec3bb603acb0b313a54fb46. Looks like a line of a newer version sneaked in. How do you want to proceed? Undo that change for now and then have a separate PR for changing the gather functions as intended?

**Comment by akohlmey** [comment]
> @akohlmey I traced this back to [68b533d](https://github.com/lammps/lammps/commit/68b533d1b8c33a8d0ec3bb603acb0b313a54fb46). Looks like a line of a newer version sneaked in. How do you want to proceed? Undo that change for now and then have a separate PR for changing the gather functions as intended?

Your call. Mid term `lammps_gather_atoms()` and its variants can probably be eliminated, since we have more generic functionality to do the same, but also work on computes and fixes.

**Comment by rbberger** [comment]
Ok, changing `lammps_gather_atoms` back to using 0 and 1 for now. That's the less intrusive change. No point in breaking compatibility for something that might even go away.

**Comment by liviabp** [comment]
Many thanks for checking and clarifying!

**Pull request closed without merging**
