### PR TITLE
Generalized DPD pair styles: dpd/ext and dpd/ext/tstat

### PR DESCRIPTION
**Pull request by msvbd**
**Summary**

This package implements a generalised force field for dissipative particle dynamics (DPD). The extension divides contributions
of dissipative and random forces into parallel and perpendicular parts. See the doc pages for "pair_style dpdext" and "pair_style dpdext/tstat".

**Author(s)**

Martin Svoboda (ICPF, UJEP) - svobod.martin@gmail.com
Karel Sindelka (ICPF) - sindelka@icpf.cas.cz 
Martin Lisal (ICPF, UJEP) - lisal@icpf.cas.cz

**Licensing**

By submitting this pull request, I agree that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Implementation Notes**

We have extended existing files: pair_dpd.h, pair_dpd_tstat.h, pair_dpd.cpp, pair_dpd_tstat.cpp, etc.
Implementation was verified by tests which two of them are part of included examples.

**Post Submission Checklist**

- [X] The feature or features in this pull request is complete
- [X] Licensing information is complete
- [X] Corresponding author information is complete
- [X] The source code follows the LAMMPS formatting guidelines
- [X] Suitable new documentation files and/or updates to the existing docs are included
- [X] The added/updated documentation is integrated and tested with the documentation build system
- [X] The feature has been verified to work with the conventional build system
- [X] The feature has been verified to work with the CMake based build system

- [X] A package specific README file has been included or updated
- [X] One or more example input decks are included

**Further Information, Files, and Links**
More about method:
Groot and Warren, J Chem Phys, 107, 4423-35 (1997).
Junghans, Praprotnik and Kremer, Soft Matter 4, 156, 1119-1128 (2008).

### CODE REVIEW

**Comment by akohlmey** [comment]
@msvbd Thank you for your submission before I take a closer look at the code, we have a few requests for "cosmetic" changes.
This kind of contribution does not justify creating a separate package, so please move it to the USER-MISC package. In a few weeks we will be reorganizing packages and redistributing styles and then we'll likely be moving this to a more suitable, new package. So not having the extra package makes things easier.
Second, please change the style names to "dpd/ext" and "dpd/ext/tstat" and change the source file names accordingly ("pair_dpd_ext.cpp", "pair_dpd_ext.h", "pair_dpd_ext_tstat.cpp", "pair_dpd_ext_tstat.h") and also the example folder(s) should be moved to "examples/USER/misc/dpd_ext". In the headers, please use LMP_PAIR_DPD_EXT_H and LMP_PAIR_DPD_EXT_TSTAT_H as include guards. Please check that all file permissions are rw-r--r-- (= 0644) and that all files have unix line endings when you commit on a Linux/Unix machine and that all files have a newline at the end (some platforms will fail to compile or read the last line of input otherwise).
Also, the documentation for the added styles needs to be linked in the Commands_pair.rst and pair_style.rst files and while you are at it check that it translates cleanly with html and pdf and passes the spell check. That all will make it easier for us to process and include your contribution.

**Comment by sjplimp** [comment]
Thanks for contributing this new pair style.  I concur with all of Axel's requested changes (we discussed them).  Then it should be ready to merge.

**Comment by msvbd** [comment]
@akohlmey Thanks for the commands. I have made some changes and checks.
- [x] Change directory to USER-MISC
- [x] Change name to dpd/ext" and "dpd/ext/tstat
- [x] Move examples to examples/USER/misc/dpd_ext
- [x] chmod 0644
- [x] unix line endings -> I have used dos2unix
- [x] Add link to Commands_pair.rst and pair_style.rst
- [x] /doc -> make pdf & make html -> no warnings no errors

**Comment by akohlmey** [comment]
@msvbd thanks for the updates. I've had to make a few more cosmetic changes and updated the branch to upstream.
@sjplimp this is ready for you to have a final look at.

**Comment by msvbd** [comment]
Thanks for the updates. It is new to me. So is my part finished now? Thanks and have a nice day

**Comment by akohlmey** [comment]
> Thanks for the updates. It is new to me. So is my part finished now? Thanks and have a nice day

Yes. This is waiting for @sjplimp to review and approve or request changes.

**Review by sjplimp — APPROVED** [review]
thanks for contributing these 2 new pair styles!

**Pull request merged**
