### PR TITLE
plugged memory leaks in ml-rann package. Resolves [2811]

### LINKED ISSUE #2811: [BUG] Memory leaks in USER-RANN package
**Summary**

There are multiple memory leaks reported when running the USER-RANN example or with valgrind's memcheck tool `valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes <path/to/>lmp -in in.rann` (please note https://docs.lammps.org/Errors_debug.html#using-valgrind-to-get-a-stack-trace and https://github.com/lammps/lammps/tree/master/tools/valgrind ) or enabling memory checking during unit testing
with `ctest -T memcheck -R ManybodyPairStyle:rann` (please note https://docs.lammps.org/Build_development.html#code-coverage-and-unit-testing).

**LAMMPS Version and Platform**

Pull request branch from PR #2810

```
OS: Linux "Fedora 34 (Thirty Four)" 5.12.11-300.fc34.x86_64 on x86_64

Compiler: GNU C++ 11.1.1 20210531 (Red Hat 11.1.1-3) with OpenMP 4.5
C++ standard: C++11
MPI v3.1: MPICH Version:        3.4.1
MPICH Release date:     Fri Jan 22 14:17:48 CST 2021
MPICH ABI:      13:10:1

Accelerator configuration:

USER-OMP package API: OpenMP
USER-OMP package precision: double

GPU present: no

Active compile time flags:

-DLAMMPS_GZIP
-DLAMMPS_PNG
-DLAMMPS_JPEG
-DLAMMPS_FFMPEG
-DLAMMPS_EXCEPTIONS
-DLAMMPS_SMALLBIG
sizeof(smallint): 32-bit
sizeof(imageint): 32-bit
sizeof(tagint):   32-bit
sizeof(bigint):   64-bit
```

**Expected Behavior**

No memory leak reports except those due to OpenMP or MPI (can be suppressed by using the suppressions in tools/valgrind)

**Actual Behavior**

Memory leak reports in the attached files.

**Steps to Reproduce**

- Compile LAMMPS with CMake using (at least) `-DENABLE_TESTING=on` and `-DPKG_USER-RANN=on` 
- Run `valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes </path/to>/lmp -in in.rann` in examples/USER/rann folder. Output: [rann-valgrind.txt](https://github.com/lammps/lammps/files/6696171/rann-valgrind.txt)

- Run `ctest -T memcheck -R  ManybodyPairStyle:rann` in build folder. Output: [MemoryChecker.266.txt](https://github.com/lammps/lammps/files/6696170/MemoryChecker.266.txt)

### PR DESCRIPTION
**Pull request by kipbarrett**
**Summary**

Plugged memory leaks in rann package/

**Related Issue(s)**

resolves #2811

**Author(s)**

Christopher Barrett, barrett@me.msstate.edu

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues.

**Implementation Notes**

Valgrind still reports a leak of 16 bytes from alpha_k initialized in rann_fingerprint_bondscreened.cpp line 42. I'm not sure why since it is deleted in line 55.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

[valgrind.output.txt](https://github.com/lammps/lammps/files/6833678/valgrind.output.txt)

### CODE REVIEW

**Comment by akohlmey** [comment]
Sorry, but this only resolves part of issue #2811. When I run:
```
cmake -S cmake -B build-rann -DENABLE_TESTING=on -C cmake/presets/basic.cmake -D PKG_ML-RANN=on -DBUILD_SHARED_LIBS=on -DLAMMPS_EXCEPTIONS=on
cmake --build build-rann
ctest --test-dir build-rann -T memcheck -R rann
```
This still has significant memory leaks. 
[CTestMemcheck.txt](https://github.com/lammps/lammps/files/6833962/CTestMemcheck.txt)

**Comment by akohlmey** [comment]
> Valgrind still reports a leak of 16 bytes from alpha_k initialized in rann_fingerprint_bondscreened.cpp line 42. I'm not sure why since it is deleted in line 55.

That leak was easily found and fixed. There is another allocation in the corresponding `init()` functions that is missing the `delete[]`.
That reduces the number of memory leaks somewhat, but not by a lot. I am updating the output file.
[CTestMemcheck.txt](https://github.com/lammps/lammps/files/6833999/CTestMemcheck.txt)

As I was mentioning already in the issue, the safest way to go about this is to initialize *all* pointers for allocations to `nullptr` in the constructor and then *always* do a delete before a new (or equivalent). This helps to resolve cases that beyond a simple input with just one `pair_style` and one `pair_coeff` command. Both commands are valid to be used in the same input multiple times and you need to keep in mind that when you have a second `pair_style` command for the same pair style, then the style is not recreated (i.e. the destructor/constructor are *not* run) but only the `settings()` function is re-run. For pair styles that read their settings from a parameter file, there are often significant memory leaks, if you use the `pair_coeff` command multiple times (e.g. with different files). The unit tests expose many of these scenarios and thus have been extremely helpful in spotting memory leaks that do not occur with simple input decks.

**Comment by kipbarrett** [comment]
Ok. I wasn't able to get ctest running before because the syntax has changed. I didn't realize the valgrind command would not catch everything. Thanks for the suggestions. I'll get on these soon.

**Comment by akohlmey** [comment]
BTW: just noticed these warnings:

```
/home/akohlmey/compile/lammps/src/ML-RANN/pair_rann.cpp: In member function ‘void LAMMPS_NS::PairRANN::read_file(char*)’:
/home/akohlmey/compile/lammps/src/ML-RANN/pair_rann.cpp:289:8: warning: variable length array ‘linetemp’ is used [-Wvla]
  289 |   char linetemp[longline];
      |        ^~~~~~~~
/home/akohlmey/compile/lammps/src/ML-RANN/pair_rann.cpp: In member function ‘void LAMMPS_NS::PairRANN::read_fingerprints(std::vector<std::__cxx11::basic_string<char> >, std::vector<std::__cxx11::basic_string<char> >, char*, int)’:
/home/akohlmey/compile/lammps/src/ML-RANN/pair_rann.cpp:402:7: warning: variable length array ‘atomtypes’ is used [-Wvla]
  402 |   int atomtypes[nwords-1];
      |       ^~~~~~~~~
/home/akohlmey/compile/lammps/src/ML-RANN/pair_rann.cpp: In member function ‘void LAMMPS_NS::PairRANN::read_fingerprint_constants(std::vector<std::__cxx11::basic_string<char> >, std::vector<std::__cxx11::basic_string<char> >, char*, int)’:
/home/akohlmey/compile/lammps/src/ML-RANN/pair_rann.cpp:435:7: warning: variable length array ‘atomtypes’ is used [-Wvla]
  435 |   int atomtypes[n_body_type];
      |       ^~~~~~~~~
/home/akohlmey/compile/lammps/src/ML-RANN/pair_rann.cpp: In member function ‘void LAMMPS_NS::PairRANN::read_weight(std::vector<std::__cxx11::basic_string<char> >, std::vector<std::__cxx11::basic_string<char> >, FILE*, char*, int*)’:
/home/akohlmey/compile/lammps/src/ML-RANN/pair_rann.cpp:516:8: warning: variable length array ‘linetemp’ is used [-Wvla]
  516 |   char linetemp [longline];
      |        ^~~~~~~~
/home/akohlmey/compile/lammps/src/ML-RANN/pair_rann.cpp: In member function ‘void LAMMPS_NS::PairRANN::read_screening(std::vector<std::__cxx11::basic_string<char> >, std::vector<std::__cxx11::basic_string<char> >, char*, int)’:
/home/akohlmey/compile/lammps/src/ML-RANN/pair_rann.cpp:595:7: warning: variable length array ‘atomtypes’ is used [-Wvla]
  595 |   int atomtypes[n_body_type];
      |       ^~~~~~~~~
```

When using a variable to dimension an array in C++ it must be a compile time constant. This code construct is only correct in C99 and Fortran (and many of the C standardization folks consider allowing it a mistake by now).

**Comment by kipbarrett** [comment]
I wasn't able to use delete exactly as you suggest because I have 2d and 3d arrays with all variable dimensions. I did initialize everything with null pointers and then put a deallocation at the beginning of the coeff command. That seems to have satisfied the units test.

I think I've caught all the warnings for variable length arrays too.
[MemoryChecker.253.log](https://github.com/lammps/lammps/files/6843061/MemoryChecker.253.log)

**Comment by akohlmey** [comment]
just recompiled the PR branch in a new build folder and saw some more warnings. I guess these files didn't get recompiled in the previous build folder when I updated the checkout.

```
[512/926] Building CXX object CMakeFiles/lammps.dir/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp.o
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp: In member function ‘void LAMMPS_NS::RANN::Fingerprint_bond::do3bodyfeatureset_singleneighborloop(double*, double*, double*, double*, int, int, double*, double*, double*, int*, int, int*)’:
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:318:10: warning: variable length array ‘expr’ is used [-Wvla]
  318 |   double expr[jnum][kmax+12];
      |          ^~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:318:10: warning: variable length array ‘expr’ is used [-Wvla]
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:378:10: warning: variable length array ‘Bb’ is used [-Wvla]
  378 |   double Bb[mb];
      |          ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:420:16: warning: variable length array ‘Bg’ is used [-Wvla]
  420 |         double Bg[mb];
      |                ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp: In member function ‘void LAMMPS_NS::RANN::Fingerprint_bond::do3bodyfeatureset_doubleneighborloop(double*, double*, double*, double*, int, int, double*, double*, double*, int*, int, int*)’:
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:573:10: warning: variable length array ‘expr’ is used [-Wvla]
  573 |   double expr[jnum][kmax];
      |          ^~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:573:10: warning: variable length array ‘expr’ is used [-Wvla]
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:574:10: warning: variable length array ‘y’ is used [-Wvla]
  574 |   double y[jnum][3];
      |          ^
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:575:10: warning: variable length array ‘ri’ is used [-Wvla]
  575 |   double ri[jnum];
      |          ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:576:10: warning: variable length array ‘dfc’ is used [-Wvla]
  576 |   double dfc[jnum];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:579:10: warning: variable length array ‘c41’ is used [-Wvla]
  579 |   double c41[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:580:10: warning: variable length array ‘c51’ is used [-Wvla]
  580 |   double c51[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:581:10: warning: variable length array ‘c61’ is used [-Wvla]
  581 |   double c61[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bond.cpp:582:10: warning: variable length array ‘ct’ is used [-Wvla]
  582 |   double ct[kmax];
      |          ^~
[513/926] Building CXX object CMakeFiles/lammps.dir/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp.o
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp: In member function ‘void LAMMPS_NS::RANN::Fingerprint_bondscreened::do3bodyfeatureset_singleneighborloop(double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, bool*, int, int, double*, double*, double*, int*, int, int*)’:
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:319:10: warning: variable length array ‘expr’ is used [-Wvla]
  319 |   double expr[jnum][kmax+12];
      |          ^~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:319:10: warning: variable length array ‘expr’ is used [-Wvla]
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:381:10: warning: variable length array ‘Bb’ is used [-Wvla]
  381 |   double Bb[mb];
      |          ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:385:10: warning: variable length array ‘dBbx1’ is used [-Wvla]
  385 |   double dBbx1[mb];
      |          ^~~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:386:10: warning: variable length array ‘dBby1’ is used [-Wvla]
  386 |   double dBby1[mb];
      |          ^~~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:387:10: warning: variable length array ‘dBbz1’ is used [-Wvla]
  387 |   double dBbz1[mb];
      |          ^~~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:430:16: warning: variable length array ‘Bg’ is used [-Wvla]
  430 |         double Bg[mb];
      |                ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp: In member function ‘void LAMMPS_NS::RANN::Fingerprint_bondscreened::do3bodyfeatureset_doubleneighborloop(double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, bool*, int, int, double*, double*, double*, int*, int, int*)’:
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:615:10: warning: variable length array ‘expr’ is used [-Wvla]
  615 |   double expr[jnum][kmax];
      |          ^~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:615:10: warning: variable length array ‘expr’ is used [-Wvla]
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:616:10: warning: variable length array ‘y’ is used [-Wvla]
  616 |   double y[jnum][3];
      |          ^
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:617:10: warning: variable length array ‘ri’ is used [-Wvla]
  617 |   double ri[jnum];
      |          ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:618:10: warning: variable length array ‘dfc’ is used [-Wvla]
  618 |   double dfc[jnum];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:621:10: warning: variable length array ‘Bijk’ is used [-Wvla]
  621 |   double Bijk[kb][mb];
      |          ^~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:621:10: warning: variable length array ‘Bijk’ is used [-Wvla]
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:622:10: warning: variable length array ‘c41’ is used [-Wvla]
  622 |   double c41[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:623:10: warning: variable length array ‘c51’ is used [-Wvla]
  623 |   double c51[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:624:10: warning: variable length array ‘c61’ is used [-Wvla]
  624 |   double c61[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreened.cpp:625:10: warning: variable length array ‘ct’ is used [-Wvla]
  625 |   double ct[kmax];
      |          ^~
[514/926] Building CXX object CMakeFiles/lammps.dir/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp.o
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp: In member function ‘void LAMMPS_NS::RANN::Fingerprint_bondscreenedspin::do3bodyfeatureset_singleneighborloop(double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, bool*, int, int, double*, double*, double*, int*, int, int*)’:
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:321:10: warning: variable length array ‘expr’ is used [-Wvla]
  321 |   double expr[jnum][kmax+12];
      |          ^~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:321:10: warning: variable length array ‘expr’ is used [-Wvla]
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:384:10: warning: variable length array ‘Bb’ is used [-Wvla]
  384 |   double Bb[mb];
      |          ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:385:10: warning: variable length array ‘Bbs’ is used [-Wvla]
  385 |   double Bbs[mb];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:433:16: warning: variable length array ‘Bg’ is used [-Wvla]
  433 |         double Bg[mb];
      |                ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:434:16: warning: variable length array ‘Bgs’ is used [-Wvla]
  434 |         double Bgs[mb];
      |                ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp: In member function ‘void LAMMPS_NS::RANN::Fingerprint_bondscreenedspin::do3bodyfeatureset_doubleneighborloop(double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, bool*, int, int, double*, double*, double*, int*, int, int*)’:
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:642:10: warning: variable length array ‘expr’ is used [-Wvla]
  642 |   double expr[jnum][kmax];
      |          ^~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:642:10: warning: variable length array ‘expr’ is used [-Wvla]
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:643:10: warning: variable length array ‘y’ is used [-Wvla]
  643 |   double y[jnum][3];
      |          ^
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:644:10: warning: variable length array ‘ri’ is used [-Wvla]
  644 |   double ri[jnum];
      |          ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:645:10: warning: variable length array ‘dfc’ is used [-Wvla]
  645 |   double dfc[jnum];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:648:10: warning: variable length array ‘Bijk’ is used [-Wvla]
  648 |   double Bijk[kb][mb];
      |          ^~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:648:10: warning: variable length array ‘Bijk’ is used [-Wvla]
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:649:10: warning: variable length array ‘c41’ is used [-Wvla]
  649 |   double c41[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:650:10: warning: variable length array ‘c51’ is used [-Wvla]
  650 |   double c51[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:651:10: warning: variable length array ‘c61’ is used [-Wvla]
  651 |   double c61[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondscreenedspin.cpp:652:10: warning: variable length array ‘ct’ is used [-Wvla]
  652 |   double ct[kmax];
      |          ^~
[516/926] Building CXX object CMakeFiles/lammps.dir/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp.o
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp: In member function ‘void LAMMPS_NS::RANN::Fingerprint_bondspin::do3bodyfeatureset_singleneighborloop(double*, double*, double*, double*, double*, double*, double*, int, int, double*, double*, double*, int*, int, int*)’:
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:318:10: warning: variable length array ‘expr’ is used [-Wvla]
  318 |   double expr[jnum][kmax+12];
      |          ^~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:318:10: warning: variable length array ‘expr’ is used [-Wvla]
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:379:10: warning: variable length array ‘Bb’ is used [-Wvla]
  379 |   double Bb[mb];
      |          ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:380:10: warning: variable length array ‘Bbs’ is used [-Wvla]
  380 |   double Bbs[mb];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:427:16: warning: variable length array ‘Bg’ is used [-Wvla]
  427 |         double Bg[mb];
      |                ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:428:16: warning: variable length array ‘Bgs’ is used [-Wvla]
  428 |         double Bgs[mb];
      |                ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp: In member function ‘void LAMMPS_NS::RANN::Fingerprint_bondspin::do3bodyfeatureset_doubleneighborloop(double*, double*, double*, double*, double*, double*, double*, int, int, double*, double*, double*, int*, int, int*)’:
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:613:10: warning: variable length array ‘expr’ is used [-Wvla]
  613 |   double expr[jnum][kmax];
      |          ^~~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:613:10: warning: variable length array ‘expr’ is used [-Wvla]
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:614:10: warning: variable length array ‘y’ is used [-Wvla]
  614 |   double y[jnum][3];
      |          ^
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:615:10: warning: variable length array ‘ri’ is used [-Wvla]
  615 |   double ri[jnum];
      |          ^~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:616:10: warning: variable length array ‘dfc’ is used [-Wvla]
  616 |   double dfc[jnum];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:619:10: warning: variable length array ‘c41’ is used [-Wvla]
  619 |   double c41[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:620:10: warning: variable length array ‘c51’ is used [-Wvla]
  620 |   double c51[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:621:10: warning: variable length array ‘c61’ is used [-Wvla]
  621 |   double c61[kmax];
      |          ^~~
/home/akohlmey/compile/lammps-progguide/src/ML-RANN/rann_fingerprint_bondspin.cpp:622:10: warning: variable length array ‘ct’ is used [-Wvla]
  622 |   double ct[kmax];
      |          ^~
```

**Comment by akohlmey** [comment]
@kipbarrett I can confirm that the memory leaks are now closed for the available tests.

**Comment by kipbarrett** [comment]
@akohlmey I'm having some trouble removing the rest of the variable length arrays without compromising performance. I don't really want to change up the inheritance to be able to use the memory class from inside fingerprints. Creating 2d arrays with the new keyword is not great for speed, so I'll probably end up vectorizing everything. In fact, nothing on the heap is as fast as the VLAs. Am I allowed to use the alloca function? I'd welcome any suggestions for the best way to do this.

**Comment by akohlmey** [comment]
> @akohlmey I'm having some trouble removing the rest of the variable length arrays without compromising performance. I don't really want to change up the inheritance to be able to use the memory class from inside fingerprints. Creating 2d arrays with the new keyword is not great for speed, so I'll probably end up vectorizing everything. In fact, nothing on the heap is as fast as the VLAs. Am I allowed to use the alloca function? I'd welcome any suggestions for the best way to do this.

What are the typical and min/max dimensions of those arrays? Please note that on many HPC machines, the size of the stack is very limited, often to 8MB and can not always be extended. So if those are small, say not much more than 100, then you could use a compile time constant maximum size and then just check whether those overflow and then abort with a suitable error message to change the corresponding constant (and a warning that one may have to increase the stack size).

You do not have to change the inheritance, instead you can just pass the LAMMPS class as an argument and then you can use `lmp->memory` from inside your derived class. See `utils::expand_args()` which is not derived from any class, for example.

Finally, it is rather straightforward to get the same 2d memory allocation pattern from the memory class also with new/delete. Example:
```
a=10;
b=10l
double **array = new double*[a];
array[0] = new double[a*b];
for (int i = 1; i < a; ++i) array[i] = array[0] + i*b;
```
Which is then deleted with:
```
delete[] array[0];
delete[] array;
```
Those two steps could be added as inline functions in a common header files.
Both new/delete and the memory class use the same memory allocator on the backend.

There is nothing in LAMMPS currently using `alloca()`, so I would want to avoid that. But mainly I would be concerned about excessive stack usage. Please note that the *use* of variable length arrays in C/C++ is causing a performance penalty and significant complications in the compiler implementation (and thus an increased likelihood of compiler bugs).
https://stackoverflow.com/questions/1887097/why-arent-variable-length-arrays-part-of-the-c-standard/21519062#21519062

My main concern is that it while most C++ compiler implementations currently accept this code (unless one explicitly requires strict C++ standard compliance), it could happen at any time that compiler vendors decide that they want to stop supporting this. There have been multiple precedents. The last I remember was during the change from GCC 3.x to GCC 4.x where strict pointer aliasing compliance was suddenly assumed (and on average 10% performance gained) and it took a significant effort to fix the code in LAMMPS that was not compliant. Not to mention the time it took to explain the reason why code that worked on one machine suddenly caused lots of segmentation faults on another (with a newer compiler).

**Comment by akohlmey** [comment]
@sjplimp since this PR resolves the most pressing issue of memory leakage, we can merge this now and I'll create a new issue for handling non-standard C++ features. Those tend to pop up in different contributions occasionally as well, so we are considering to make this a compile time error in the integration testing, so that it will be detected before it is merged (but for that we need to get rid of all cases in the existing code base, of course). However, this is not going to happen until after the next stable release.

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
