### PR TITLE
Prevent geometric grow of memory in CommBrick

### LINKED ISSUE #1528: [BUG] Possible bug in comm_brick calling grow_send
**Summary**

In the following lines of code:
https://github.com/lammps/lammps/blob/bb11344424a468254c320e3cfa0cf263a1005630/src/comm_brick.cpp#L610-L614
grow_send is called if there is any change in bufextra. If there happens to be frequent change in maxexchange_fix, which happens when FixNeighHistory is instantiated and the number of neighbours is constantly increasing, it triggers grow_send that will multiply maxsend with BUFFACTOR. That might lead to an unintended overflow of maxsend integer variable. Just as a reference CommTiled takes a different approach and just calls memory->grow:
https://github.com/lammps/lammps/blob/bb11344424a468254c320e3cfa0cf263a1005630/src/comm_tiled.cpp#L654-L655

**LAMMPS Version and Platform**

Master branch, independent of platform.

**Expected Behavior**

The variable maxsend shouldn't be modified in this case. We either need to modify grow_send to account for cases where bufextra is increased, or just call memory->grow directly as in CommTiled.

**Actual Behavior**

The function grow_send is called and maxsend is increased.

**Steps to Reproduce**

This is really hard to reproduce. It was only spotted because our application have a lot of instatiation of atoms which triggers a constant change in the numbers of partners in FixNeighHistory and a constant modification of maxexchange_fix in CommBrick. I am unable to provide a simulation case with the present modules. I hope that the problem become obvious by a quick code review.

**Further Information, Files, and Links**

No further information.

### PR DESCRIPTION
**Pull request by valleymouth**
**Summary**

Prevent geometric grow of memory in CommBrick.

**Related Issues**

Fixes #1528.

**Author(s)**

Denis Taniguchi (denis.taniguchi@gmail.com)
Newcastle University

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No backward compatibility issues.

**Implementation Notes**

Changed call to grow_send to a direct call to memory->grow. Checked with granregion examples.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

None.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@valleymouth have you confirmed that this indeed fixes #1528?

**Comment by valleymouth** [comment]
@stanmoore1 I just realised that it is important to keep the call to grow_send because of Kokkos. So a cleaver solution is to call grow_send((maxsend+bufextra)/BUFFACTOR+1,1).

**Comment by Adrian-Diaz** [comment]
The more formal solution would probably be to alter grow send if it is to be abstracted to this degree. Using a flag to determine whether or not to multiply by BUFFACTOR. Involving float division by 1.5 for an integer size (that should be carefully tailored to avoid segfault) is risky. Another option is to just redefine BUFFACTOR as an actual variable and set it to 1 at the time of the maxexchange checks and grow; I doubt anyone will miss the overhead associated with buffactor=1 and then setting it back to 1.5.

**Comment by valleymouth** [comment]
I have tested it with examples/pour/in.pour which also triggers an increase in bufextra. The master branch ends up with maxsend having a size of 345123 and with my latest commit it grows to only 3591.
@Adrian-Diaz I haven't noticed your last comment on this issue and I ended up using the "clever size" approach. If you consider that this is a bad choice I am happy to change it to the additional flag approach. It seams to me that that would be a relatively local change since the only class that inherits form CommBrick is CommKokkos. I would love to hear @stanmoore1 and @akohlmey opinion on this.

**Comment by akohlmey** [comment]
#1556 provides a more generic solution to the issue at hand than this PR. so this one will be closed automatically when the other is completed, passes all tests, and then gets merged to master.

**Pull request closed without merging**
