### PR TITLE
Change random number generator for stochastic wall fixes

### PR DESCRIPTION
**Pull request by toquydong**
**Summary**

Change random generator (from RandomMars to RandomPark) for stochastic wall model to avoid numerical instability.

**Related Issues**

In long run, we observe numerical issues with the random mars generator. In several long run simulations, after 40E6 timestep for example, the program is halted with error "Non-numeric atom coords - simulation unstable". After replacing with random park generator, the program does not encounter the above issues.

**Author(s)**

Quy-Dong To. Université Paris Est Marne la Vallée.

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

The changes are compatible.

**Implementation Notes**

Changes were made in random_park.cpp, random_park.h to include distributions required for stochastic wall. In fix_wall_reflect_stochastic.cpp, fix_wall_reflect_stochastic.h, the randompark is used instead randommars.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

### CODE REVIEW

**Comment by sjplimp** [comment]
The Marsaglia RN generator (random_mars) is actually a much better generator than Park.
Much longer period, better in parallel, carefully studied properties, etc.  Do you have evidence that bad random #s are somehow causing your simulation to go unstable?  How many procs are you running on, how many RNs is each proc using?  There could be many other reasons for a simulation to blow up.  If it's just a rare occurrence, then the fact the behavior changes when you switch the generator is not conclusive.  Does it also happen/not-happen if you change the seed?  Also, how are you using the Park generator in parallel?

**Comment by sjplimp** [comment]
I now see this line in your changed code:
random = new RanPark(lmp,seedfix + comm->me);

For RanMars that is a good way to get independent RN streams on different procs.
It's designed to be used that way.  For seeds that differ by even 1, the
streams are completely independent.

For Park, that's actually a bad way to use it in parallel.  Your RN streams
on different procs are likely correlated.

**Comment by toquydong** [comment]
It depends on the number of processor. If I use 1 proc, the simulation time can be longer. For many procs (8 procs), the simulation terminates earlier. I attach the results with randmars in the zip files.
[Out.zip](https://github.com/lammps/lammps/files/4494665/Out.zip)

**Comment by toquydong** [comment]
It is possible that the gaussian based on mars generator can generate high speed value that leads to numerical instability?

**Comment by sjplimp** [comment]
If Gaussian RNs in the tail of the distribution is the problem, then that's not a problem with the Marsaglia generator.  That's possibly a problem with the procedure that converts the RNs to a Gaussian distribution.  Even that is unlikely.  If the stochastic wall method has a numerical problem with Gaussian RNs at the extreme tails, then it should check them, not use them, and request another Gaussian RN.  I.e. throw away the tails.  I can't think of a good reason why Mars vs Park would make a difference for this particular issue.

**Comment by akohlmey** [comment]
@toquydong I have to agree with @sjplimp and can confirm that the computing of the gaussian distribution is correct. I have tested this thoroughly in a yet unpublished branch which implements an alternate and faster algorithm to obtain the gaussian distribution (the calls to `exp()` can be time consuming when a lot of random numbers are used).

**Comment by toquydong** [comment]
Thanks for the messages. I am now checking the code to find where the problem is.

**Comment by toquydong** [comment]
Hello,
After doing many tests and checks, I can not find the mentioned numerical error. I believes that the above issue is due to the tail of the distribution. Such event is very rare.
Quy Dong

**Comment by akohlmey** [comment]
> Hello,
> After doing many tests and checks, I can not find the mentioned numerical error. I believe that the above issue is due to the tail of the distribution. Such event is very rare.
> I agree that there is no need to change to random park.
> Quy Dong

OK, then we should close this pull request and instead you may want to look into adding a feature that allows to clamp the distribution, i.e. get a new random number, if the value is too large.

**Comment by toquydong** [comment]
OK. We should close this thread. I will investigate the problem further before proposing any changes.

**Pull request closed without merging**
