### PR TITLE
reset_mol_ids command

### PR DESCRIPTION
**Pull request by jrgissing**
**Summary**

resets molecule ids (in the spirit of reset_ids)
for example, enables correctly identifying the atoms that belong to a given molecule, after fix bond/react changes system topology

**Related Issues**

none

**Author(s)**

JG

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

yes

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
hmmm... couldn't you achieve the same thing through compute fragment/atom and then set?
that would give you additional options and flexibility, as you can compute/apply it to only a group of atoms and assign offsets by using an atom style variable or do other manipulation of the data.

**Comment by jrgissing** [comment]
that's true. however, i still think a 'command' will be simple and useful in this case. also, i am getting large speedups (64x for 200K atom on 20 procs, polymerized nylon system)

**Comment by akohlmey** [comment]
assigning to @sjplimp for evaluation of whether this is something we want as a global command or just as part of the USER-REACTION package. What I like about the route via `compute fragment/atom` is the additional flexibility. Unlike for `reset_ids` which needs to be a global command as it requires rewriting the topology, molecule ids are just labels and not always aligned with molecules, but can also be used to partition the system differently. When  updating those, people may only want to update them for a subset of atoms, and for that you would have to limit it to groups and define a starting value.

**Comment by sjplimp** [comment]
@jrgissing Hi Jake - looking over this code.  It's pretty complex, so I have a few Qs.
a) separate from re-numbering, does this do the same thing as compute fragment/atom,
     I.e. assign the same ID to all atoms in the same molecule?
b) I think you are saying this is 200x faster than that compute - can you explain why
    in an algorithmic sense?  i.e. what is this doing that is different
c) including the re-numbering, will this work scalably, e.g. for 10000 procs and billions
     of molecules?  The gather_molIDs() method with the "send to root" comment
     looks troubling (but maybe I just don't understand what it is doing)

**Comment by jrgissing** [comment]
Hi Steve,
> a) separate from re-numbering, does this do the same thing as compute fragment/atom,
> I.e. assign the same ID to all atoms in the same molecule?

yes (though perhaps several more lines (variable, set, output, and run commands) are required for the compute fragment/atom result to be assigned to molecule IDs)

> b) I think you are saying this is 200x faster than that compute - can you explain why
> in an algorithmic sense? i.e. what is this doing that is different

as I understand, fragment/atom does a full forward and reverse communication on every iteration, where each iteration updates every atom's ID to the minimum of its first neighbors. So, if you happen to have atom with ID 1 at one end of a chain with 10,000 backbone atoms, that's 10,000 iterations in this worst case scenario (and the best case is still half that).

reset_mol_ids in current form is the other extreme. Each processor first assigns locally-consistent (and globally-unique) IDs to all local and part-ghost molecules. Now, we are interested in deduplicating the part-ghost IDs that are actually the same molecule. Each processor is informed of equivalent IDs to each part-ghost molecule, and currently all these equivalences are sent to root for dedup.

> c) including the re-numbering, will this work scalably, e.g. for 10000 procs and billions
> of molecules? The gather_molIDs() method with the "send to root" comment
> looks troubling (but maybe I just don't understand what it is doing)

The scaling issue would be memory requirement at root, which is O(# of part-ghost molecules per proc * # procs * # equivalent IDs) , where # equivalent IDs is at most 8 (at corner of processor domain). So, many small molecules in a large system would cause issues.

However, I think that it would be fairly straightforward to treat small molecules confined to one border as a special case, and send only large-molecule IDs to root for dedup.

**Comment by sjplimp** [comment]
@jrgissing Thanks for the info, Jake.  Fragment/atom does do comm every iteration,
but an iteration assigns new IDs to all the atoms on the proc (if anything changed
at the proc boundary).  So your 10000 backbone example should
only happen if the atoms were each on different procs (i.e. 10000 procs).
So I'm puzzled by how fragment/atom can be slow.
Do you have a test case which shows a big performance difference between
reset_mol_ids and fragment/atom?  Maybe with a big data file, but
hopefully simple scripts to do the test?  Better yet, a way to auto-generate
the data file at different sizes, mol counts, etc?

**Comment by jrgissing** [comment]
please find (zipped) data file and input attached. for timings, I compared ComputeFragmentAtom::compute_peratom with ResetMolIDs::command

perhaps, one chain switches many times between processors, which would cause many iterations of fragment/atom (technically possible even with just two procs)

[final_poly99_in.txt](https://github.com/lammps/lammps/files/4807411/final_poly99_in.txt)

[final_poly99.zip](https://github.com/lammps/lammps/files/4807410/final_poly99.zip)

**Comment by sjplimp** [comment]
Thanks for the files - I will take a look.  Conceptual Q.  I'm trying to recall why
fragment/atom uses the (half vs full, depends on newton) bond list to walk the molecule
instead of the (full) special list (1st neighs).  It could be b/c of the various ways that
bonds can be broken/added in LAMMPS.  Does fix bond/react keep both data structs up-to-date whenever a bond is added/broken?

**Comment by jrgissing** [comment]
yes, bond/react updates both the bond list and the special list

**Comment by jrgissing** [comment]
completely refactored so that memory does not scale with number of processors. Now, each molecule is walked one at a time, instead of sending all equivalent molIDs to root. This also resulted in slightly simpler code, though about 4x slower than the original reset_mol_ids (200K atom on 20 procs, polymerized nylon system)

**Comment by akohlmey** [comment]
@jrgissing FYI, you need to merge in or rebase on the master branch from upstream for this to pass testing.

**Pull request closed without merging**
