### PR TITLE
Added third order, added documentation, took out extraneous lines, ad…

### PR DESCRIPTION
**Pull request by charlessievers**
…ded documentation figures.

**Summary**

_Removed unnecessary lines from dynamical_matrix.cpp
Added third order force constant tensor calculator, it also uses finite difference to calculate.
Updated documentation for dynamical_matrix to help users understand the output and options.
Added documentation for third_order._

**Related Issues**

_No related issues._

**Author(s)**

_Name: Charles Sievers
University: UC Davis
Department: Chemistry
Lab: Donadio Lab
Email: charliesievers@cox.net._

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

_Should not break backward compatibility._

**Implementation Notes**

_Third order tensors were compared against a long standing in house third order tensor calculator._

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@charlessievers i have updated the code base to the current master to avoid any problems with integration tests. i also renamed the "ballistico" keyword to be consistent with the "dynamical_matrix" command. it is difficult to justify those in the first place, but to have them named differently in both commands is just confusing to people. i leave it to you to decide, if you want to reflect the change in the implementation as well (not needed, but would be cleaner).

**Comment by charlessievers** [comment]
> @charlessievers i have updated the code base to the current master to avoid any problems with integration tests. i also renamed the "ballistico" keyword to be consistent with the "dynamical_matrix" command. it is difficult to justify those in the first place, but to have them named differently in both commands is just confusing to people. i leave it to you to decide, if you want to reflect the change in the implementation as well (not needed, but would be cleaner).

Thank you @akohlmey for the edits. I totally understand, I will settle for eskm.

**Comment by charlessievers** [comment]
@akohlmey would you be interested in me creating an option to access the dynamical matrix and third order tensor through the library interface? I understand that this would involve storing large slots of memory, but I think it would be useful for small to medium sized systems.

**Comment by akohlmey** [comment]
> @akohlmey would you be interested in me creating an option to access the dynamical matrix and third order tensor through the library interface? I understand that this would involve storing large slots of memory, but I think it would be useful for small to medium sized systems.

the tricky thing about this would be the question of what would allocate and free(!) the memory. since these are commands, their classes go out of scope after completion and thus there will be nothing that would know how to free the allocated memory. what might work could be to store the information to a (vector style) variable or a fix similar to fix store/state. that would make accessing it easy and the memory can be freed when the variable is deleted or the fix unfixed or the LAMMPS class instance deleted.

thus i think it might be sufficient to have example code that would read the generated file(s) into python and then post-process the data. if this file would be written to a ramdisk (e.g. /tmp on most linux machines), processing it could be rather fast.

**Comment by charlessievers** [comment]
> the tricky thing about this would be the question of what would allocate and free(!) the memory. since these are commands, their classes go out of scope after completion and thus there will be nothing that would know how to free the allocated memory. what might work could be to store the information to a (vector style) variable or a fix similar to fix store/state. that would make accessing it easy and the memory can be freed when the variable is deleted or the fix unfixed or the LAMMPS class instance deleted.
I see, that makes sense. I may look into this for my next update.

**Comment by charlessievers** [comment]
> thus i think it might be sufficient to have example code that would read the generated file(s) into python and then post-process the data. if this file would be written to a ramdisk (e.g. /tmp on most linux machines), processing it could be rather fast.

I am not sure what you mean by example code. Are you referring to an example python scripts with ASE that I forgot to include in this PR?

**Comment by akohlmey** [comment]
> > thus i think it might be sufficient to have example code that would read the generated file(s) into python and then post-process the data. if this file would be written to a ramdisk (e.g. /tmp on most linux machines), processing it could be rather fast.
> 
> I am not sure what you mean by example code. Are you referring to an example python scripts with ASE that I forgot to include in this PR?

i don't mean the entire script, especially not the ASE part, but i vaguely recall that there was some post processing part that would read in the dynamical matrix from the file and do some numpy matrix operations on it.

**Comment by charlessievers** [comment]
> i don't mean the entire script, especially not the ASE part, but i vaguely recall that there was some post processing part that would read in the dynamical matrix from the file and do some numpy matrix operations on it.

I can add a script to read in the dynamical matrix and use it into this pull request (If you think it would enhance the PR).

**Comment by akohlmey** [comment]
> > i don't mean the entire script, especially not the ASE part, but i vaguely recall that there was some post processing part that would read in the dynamical matrix from the file and do some numpy matrix operations on it.
> 
> I can add a script to read in the dynamical matrix and use it into this pull request (If you think it would enhance the PR).

yes, i do.

**Comment by akohlmey** [comment]
> looks good - thanks @charlessievers

@sjplimp does this mean you meant to approve this PR or that you want to wait for somebody else, e.g.  @athomps to approve?

**Comment by sjplimp** [comment]
I approve - @athomps  Aidan may want to look at it as well

**Pull request merged**
