### PR TITLE
library: add comm->procgrid to extract_global

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

Adds access to procgrid via the library interface

**Related Issue(s)**

**Author(s)**

@rbberger 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by sjplimp** [comment]
@rbberger @akohlmey This looks fine.  However, note that procgrid[3] is only defined in comm.h for a logical 3d grid of procs (layout UNIFORM or NONUNIFORM).  It is not defined for a TILED layout, e.g. when using RCB via balance or fix balance.  So I am not sure if the lib interface should error check for that or return something different, e.g. mysplit[3][2] ??

**Comment by rbberger** [comment]
@sjplimp we have other parts of the library interface that are accessible but make no sense to access in certain cases. E.g. when we have triclinic boxes some values are not defined. There are some other comm quantities as well that might be worth exposing, but this was the minimal change I needed for a collaborator, so I started this PR.

**Comment by sjplimp** [comment]
So in all those cases, why don't we either print a warning (or trigger an error), or return something like a null ptr so the caller can check it.  If we return procgrid when the values are unset, that seems like a bad idea.  Ditto for anything similar for orthogonal vs triclinic.

**Comment by rbberger** [comment]
Added the necessary check for layout to the new `proc_grid` global. Otherwise, it'll return a `nullptr`.

**Comment by akohlmey** [comment]
@rbberger is there a specific reason the keyword is "proc_grid" instead of the name of the class member "procgrid"?

**Comment by rbberger** [comment]
Was following the naming scheme of other globals, that don't necessarily exactly match the underlying variables.

**Comment by akohlmey** [comment]
> Was following the naming scheme of other globals, that don't necessarily exactly match the underlying variables.

Hmm... In most cases they *do* match and most of the time when there is an underscore it is added to represent a dereference, e.g. 'respa_levels' for `respa->nlevels'.

Not that I am opposing it, but I prefer to have these match the variable name as much as possible since that is easier to remember.

**Comment by akohlmey** [comment]
FWIW, I've also added some more flags from the Comm class so that one can check without having to deal with None.

**Comment by rbberger** [comment]
Fine by me either way.

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
