### PR TITLE
Correct some inconsistencies

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This PR correct a few inconsistencies due to recent changes in the core of LAMMPS.

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

The following changes are include:
- consistently use `ev_init()` instead of `ev_setup()` plus explicit variable initialization in pair styles
- update input examples and log files where `fix_modify energy yes` has been replaced with using the "econserve" thermo keyword.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by akohlmey** [comment]
@stanmoore1 I think this should cover it (for now). I have checked all inputs following the standard naming conventions where the input file starts with "in.". I think for the next stable release we should do a complete overhaul of the examples (some changes will be needed for the package rename anyway) and re-run the logs for all, update them to match the conventions and then also update the regression test inputs based on the examples with recently added/changed examples.

**Review by sjplimp — APPROVED** [review]
good catches on ev_init() vs ev_setup()

**Comment by stanmoore1** [comment]
@akohlmey OK I'm still seeing segfaults in my Jenkins tests, I'm going to merge this PR into my test branch and see if that helps.

**Comment by akohlmey** [comment]
> @akohlmey OK I'm still seeing segfaults in my Jenkins tests, I'm going to merge this PR into my test branch and see if that helps.

which test? based on an example? or something else?

**Comment by stanmoore1** [comment]
I'm seeing a crash in one of the electrostatics tests, and `examples/USER/diffraction` is still failing. I can't reproduce the issue on my Linux box though, still digging.

**Comment by stanmoore1** [comment]
@akohlmey there is a memory issue due to recent changes in MSM, see attached reproducer.


[in.msm.txt](https://github.com/lammps/lammps/files/5953222/in.msm.txt)

**Comment by stanmoore1** [comment]
```
MSM initialization ...
WARNING: Adjusting Coulombic cutoff for MSM, new cutoff = 55.969857 (../msm.cpp:1085)
*** Error in `/lammps_master/src/lmp_mpi': free(): invalid pointer: 0x00007f0e12c527b8 ***
```

**Comment by stanmoore1** [comment]
```
==10670== Conditional jump or move depends on uninitialised value(s)
==10670==    at 0x516863: LAMMPS_NS::Memory::sfree(void*) (memory.cpp:114)
==10670==    by 0x9073B8: destroy<double> (memory.h:79)
==10670==    by 0x9073B8: LAMMPS_NS::MSM::allocate() (msm.cpp:660)
==10670==    by 0x91882E: LAMMPS_NS::MSM::setup() (msm.cpp:400)
==10670==    by 0x91A017: LAMMPS_NS::MSM::init() (msm.cpp:198)
==10670==    by 0x61D382: LAMMPS_NS::Force::init() (force.cpp:190)
==10670==    by 0x55A565: LAMMPS_NS::LAMMPS::init() (lammps.cpp:850)
==10670==    by 0x62A8B0: LAMMPS_NS::Run::command(int, char**) (run.cpp:177)
==10670==    by 0x412C65: void LAMMPS_NS::Input::command_creator<LAMMPS_NS::Run>(LAMMPS_NS::LAMMPS*, int, char**) (input.cpp:809)
==10670==    by 0x4107DF: LAMMPS_NS::Input::execute_command() (input.cpp:792)
==10670==    by 0x41126C: LAMMPS_NS::Input::file() (input.cpp:271)
==10670==    by 0x405645: main (main.cpp:64)
==10670== 
```

**Comment by akohlmey** [comment]
@stanmoore1 thanks for the valgrind output. somehow it didn't show for my compile. but that is pointing to something that looks like it needed to be done, anyway. not sure it cures the issue at hand, but it will be an improvement nevertheless.

**Comment by stanmoore1** [comment]
@akohlmey Yes that fixes the MSM issue, thanks. I'm running the other tests now.

**Comment by stanmoore1** [comment]
@akohlmey I think we are good now. I was wrong about `examples/USER/diffraction`, it is passing.

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
