### PR TITLE
Character based types

### PR DESCRIPTION
**Pull request by jrgissing**
## Purpose

toward an option for character-based atom, bond, etc. types in data and molecule files. notably, this results in truly general molecule templates

_The plan_
- [ ] Add option to remember comments in data files (in coeff sections) 
- [ ] Add support for restart files
- [ ] Let these character-based types override numeric types (e.g. when multiple read_datas)
- [ ] Add support for molecule templates

## Author(s)

Jacob Gissinger

## Backward Compatibility

yes

## Implementation Notes

designed to be minimally invasive when reading data/molecule files. however, required many (mostly formulaic) changes when printing. ~8 user packages could also be updated to support this.
no support for restart files attempted

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included (not yet)
- [x] One or more example input decks are included (a temporary one)
- [x] The source code follows the LAMMPS formatting guidelines (i think so)

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@jrgissing this is a valiant effort, but i think there is very little hope that this gets added in the way it is currently shaping up. this is something where there should be a discussion beforehand where it is settled what kind of scenarios should be supported and how (from the user perspective, independent of the implementation). the best way to get such an effort with rather fundamental changes started is to arrange for a discussion with the core LAMMPS developers, especially @sjplimp at a LAMMPS workshop.

As an aside, we already have an informal "standard" to encode type names into data files, by adding them as comments in addition to the numerical types. This is used by multiple external tools. So i would start from that file format, which is fully backward compatible and treat the atom type names as an additional (diagnostic) property, which could then also be used selectively to match against string types. I also don't understand why you need to do all the complex changes here. The type names should be a global array/hash that is replicated across all MPI ranks, so internally only the numbers are used. no need to change the communication routines. As member of the atom class, there is no need to change the write_data APIs. 

For use of character based types instead of numbers, i would propose a variable function so that one can do an immediate variable in the input file to use character based types instead of numbers, but LAMMPS will just see the numbers. please note, that character based types cannot cleanly handle wildcards for ranges, as it is not known in which order they are stored and mapped to numerical types.

For data files, there could be a flag to read data indicating whether the numerical or the character based type should be preferred and so on. ...and this is just what comes to my mind right now. i am certain @sjplimp has his own ideas, considerations and requirements. so unless you don't mind redoing a lot of work, i personally would recommend to have a discussion with the LAMMPS core developers first before you continue.

**Comment by jewettaij** [comment]
Hi Jacob.  There have been some fascinating proposals recently.  It sounds like you want to improve the functionality for looking up bonded interaction parameters whenever new bonds are formed.  Is this correct?
    Given that modern force fields have anywhere from 40-1000 atom types, there are so many possible combinations permutations for the 4 atom types in a dihedral (for example), it is impractical to list them all.  (I'm pretty sure you realize this.)  So force fields like OPLSAA and COMPASS use "equivalence tables" to effectively reduce the number of atom types we have to consider.  This is an alternative to using strings and wildcards which might be useful.  The atom types can remain as integers.
    As an example, in OPLSAA, atoms of type 86, 87, 88, 169, 266, 280, 281, 325, 325, 340, 342, 458, 459, 649, 900, 901, and 902 all belong to the "47" "equivalence" group.  Atoms in this group are carbon atoms which behave identically when participating in bonded interactions.  In OPLSAA there are 906 atom types, but only about 100 "equivalence groups".  Effectively the number of atom types from 906 to ~100 makes it feasible to actually list all possible combinations of them in a reasonable length file.
    I have several force field files (OPLSAA, COMPASS, AMBER GAFF) which are in this format (or in a format which can easily be converted to this format), which I can send you.
    Over here at Scripps, my collaborators and I are working variant of fox bond/create which I might need some help with, in case you would like to collaborate.
    Either way, I think what you are doing is fantastic.
    Let me know if there is any way I can help.

**Comment by jewettaij** [comment]
(However I admit, it is certainly much easier for a human to read files with atom-type strings.  So I am not arguing against what you are doing at all.)

**Comment by jrgissing** [comment]
@akohlmey this PR actually sounds like (a first iteration of) what you are describing. it does not modify communication routines, only those which write atom, bond etc. types to files. i believe this is required to write the character-based types (instead of the internally-used numeric types) to a data file after the simulation. the 'variable function' is implemented as a character array, whose index corresponds to the number that lammps sees. the 'character types flag' is currently triggered if an atom type starts with a character, but i agree it should be a flag to the read_data command in case e.g. you wish to mix character and numeric types

@jewettaij yes, i think that is essentially the goal, i.e. my primary motivation is to greatly simplify the process of matching up types between multiple data files and/or molecule templates, as well as the option to add more permanent transparency to data files, etc. Your point about equivalences is interesting, but could really apply to either character or numeric types, so i think is technically unrelated to this PR. i agree that character-based types makes the most obvious sense for atom and bond types, and is progressively less general/more difficult to standardize, but this is in line with force field files themselves

**Comment by jrgissing** [comment]
i doubt that the need for advanced tools such as moltemplate will be eliminated any time soon, but great to hear you think this PR could be useful

**Comment by jewettaij** [comment]
My apologies.  I hope I did not muddy the waters.  When I commented on this PR, I misunderstood what Jacob is trying to do.  I assumed he wanted to use these strings to be able to write a new fix which can lookup force field parameters whenever a bond is formed or broken.  So the example I provided used a combination of different force fields with overlapping atom types to make a case for using atom-type strings instead of integers.  But that's not what fix bond/react does.  With fix bond/react, the user manually specifies the new angles, dihedrals and impropers when a bond is formed.  So my example was a confusing non-sequitur.

That said, using strings to represent (atom, bond, ...) types helps with Jacob's problem too, and might have dividends down the road enabling new fixes and features we haven't thought of yet.

**Comment by akohlmey** [comment]
@jrgissing this has been sitting here for a long time without updates. are you still working on it?

at the moment, i don't see a convincing argument to make this kind of change in this way, since we already have an established, alternate way to store string information (for atom types and more) as comments into data files.
since the strings *will* have to be converted to numbers internally at some point, i would prefer an implementation, where you can state on reading, whether you want to read string based info, or number based info (or even make it a global flag), but on writing, you write out both (so it would theoretically be possible to continue without the text labels) in the established format.

**Comment by jrgissing** [comment]
okay, this can be refactored. to reiterate, in data files, you'd like it to read alphanumeric types from comments (instead of replacing numeric types in their traditional column locations), and have it triggered by a keyword to read_data. 

regarding molecule templates, I would vote to retain this PRs current method (directly replacing numeric types)

**Comment by akohlmey** [comment]
please see my comment at pull request #1252

**Pull request closed without merging**
