### PR TITLE
Compute snap

### PR DESCRIPTION
**Pull request by athomps**
**Summary**

Added a new compute that generates a global array of SNAP bispectrum quantities that are
needed to train SNAP potentials. 

**Related Issues**

None

**Author(s)**

Aidan Thompson

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This is a new feature, the old computes sna/atom, snad/atom and snav/atom still work as before.

**Implementation Notes**

It works in parallel and gives the same results on any processor count.  I added documentation to the existing compute_sna_atom.html doc page. I added an example in examples/snap/in.snap.compute that demonstrates all the computes, showing equivalences, for a minimal system with two atom types.  I was not able to get Sphinx to compile the html on my computer, so there might be some formatting issues. 

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@athomps This needs to add the `compute snap` command to `doc/txt/compute.txt` and `doc/txt/Command_compute.txt` and their RST counterparts in `doc/src`. Please note, if PR #1786 gets merged first, `doc/txt/Command_compute.txt` will be gone and `doc/src/Command_compute.rst` will be different (simpler) in how a new compute is added.

**Comment by akohlmey** [comment]
@athomps, also there is a typo in the `compute sna/atom` doc file, where it says "refence" instead of "reference"
https://ci.lammps.org/job/lammps/job/pull-requests/job/build-docs-pr/1363/warnings3Result/

**Comment by athomps** [comment]
Addressed issued identified by @akohlmey

**Comment by athomps** [comment]
I don't know how to resolve this conflict without making a new PR.

**Comment by akohlmey** [comment]
> I don't know how to resolve this conflict without making a new PR.

Merge conflict should be resolved now.

**Comment by akohlmey** [comment]
@rbberger there is something off with the triggering of jenkins tests for this PR. Can you please have a look?

**Comment by athomps** [comment]
Thanks!

**Comment by akohlmey** [comment]
@rbberger i suggest to merge this PR before your changes to the command tables.

**Pull request merged**
