### PR TITLE
Have extra/XXX/per/atom set by keyword to the read_data command

### PR DESCRIPTION
**Pull request by jewettaij**
This pull request adds keywords for `extra/XXX/per/atom` settings to the `read_data` command that make it consistent with `create_box`. This also better supports the case where data files are read during a run, that were created previously from `write_data`, which will not output 'extra XXX per atom' in the header.
To maintain backward compatibility with existing data files, the `extra XXX per atom` lines are still parsed and applied as before, if the keywords are not given. In case the setting is requested in both, data file header and input file keyword, the larger of the two is chosen. Documentation updates are included.

Originally, this pull request suggested to change `write_data`, but the change to `read_data` seems more compelling and removes an inconsistency. Below is the original comment:

Lately, I've been running simulations using fix bond/create (as well as fix bond/break, and several related fixes which I am working on), all of which require "extra bonds per atom".  Currently, this information is not included in the data files created by write_data, so I made a small change to write_data.cpp.  Cheers -andrew

### CODE REVIEW

**Comment by akohlmey** [comment]
Not sure, if this is the best way to go. I never liked the need to modify data files much. Wouldn't it be more consistent, if we lifted the settings out of the data file, and make them keywords to the `read_data` command? that would make it consistent with `create_box`, too. `read_data` already has keywords for extra types.

**Comment by jewettaij** [comment]
I did not realize it was possible to set these parameters by adding keywords to the "read_data" command.  Cool.  In the future, I'll run my simulations that way.  But if we want to encourage other people to this, then we should change the documentation at http://lammps.sandia.gov/doc/Section_errors.html
Specifically
"New bond exceeded bonds per atom in create_bonds
    See the read_data command for info on setting the “extra bond per atom” header value to allow for additional bonds to be formed."
    I suspect most people learn about the need to define extra bond per atom settings from this error message.  Perhaps we should change the documentation here to say:
   "See the read_data command for info on setting the "extra/bond/per/atom" keyword to allow for additional bonds to be formed"
   (There are several other error messages similar to this which would also need to be modified.)  If we can change this documentation, I'd be happy to leave write_data.cpp alone.  Generally, I agree with you.  I prefer to leave extraneous settings out of the data file.  Let's see if we can make it less confusing for the user.
   Cheers
-andrew

**Comment by jewettaij** [comment]
Should I post a message about the documentation on the list?  (Thanks for doing all this, by the way.)

**Comment by akohlmey** [comment]
@jewettaij you misread my comment. this option does not exist (yet). the reason, why this is currently somewhat inconsistent, is how things have developed historically. The change to data files was first, but with create_box, you don't have a file, so it had to be a keyword.

**Comment by jewettaij** [comment]
Oops.  Yeah, I just realized that.  If you're willing to add that feature to read_data.cpp, that's great.  Otherwise, I'm happy to make this change, and update "doc/src/Section_errors.txt" too.  Sound good?

**Comment by akohlmey** [comment]
If you are willing to make the changes, please go ahead. I would suggest to retain support for reading the "extra <something per atom" in the data files for backward compatibility, but remove it from the documentation and give precedence to the keywords (or make them additive; whatever is more convenient to implement). I can review the changes and, if needed, add tweaks to it.

**Comment by jewettaij** [comment]
In progress.  I'll test it and send a new pull request soon.

**Comment by akohlmey** [comment]
@jewettaij here is one more hint for handling github and git more smoothly:
don't do development on `master`. instead create a branch, push it and submit this as pull request.
this way you can work on different "topics" concurrently and don't have to deal with divergence and merge conflict issues. whenever you submit a pull request from master, it has **all** commits in there, including merge commits and other stuff, that you may not want in a pull request.
The github tutorial in the manual is quite nicely showing and explaining all the steps.

**Comment by jewettaij** [comment]
Okay.  I reverted to the previous version of write_data.cpp, and updated read_data.cpp, and updated read_data.txt and Section_errors.txt.  (Tested the changes using this command:
"read_data system.data extra/bond/per/atom 10 extra/angle/per/atom 20 extra/special/per/atom 100")

**Comment by jewettaij** [comment]
(For my next pull request, I'll create a new branch.  It would have eliminated the need to use "git revert" in this case.)

**Comment by akohlmey** [comment]
@jewettaij FYI, just pushed some changes, that makes the handling of "extra XXX per atom" flags in the data file header safer. It now takes the MAX() of value set by the keyword and in the file. With your version a value given in the file would always override the keyword, which could result in unexpected behavior.

**Comment by jewettaij** [comment]
Did not think of that.  Sounds good.  Thanks for catching it.

**Comment by jewettaij** [comment]
I have another pull request I'd like to make, but I'm afraid of making changes to my local repository which is out of sync with your changes.  (Perhaps this is a good example why I should have created a separate branch before creating the pull request.)  I don't want to rush you, but please merge this pull request if everything looks okay.  (That way I can sync my fork with lammps/lammps, make some changes, and submit my next pull request.  I appreciate your patience while I learn how to use git.)  If you want me to test your changes and get back to you, I'm happy to do that.

**Comment by akohlmey** [comment]
merges are done by steve only. and steve is not available until july 4th.
in the mean time, you can do the following steps in your repository (assuming you have deposited an ssh key on github, otherwise you have to use the equivalent https:// syntax) to have a new clean reference from the current master of the LAMMPS project.
```bash
# add a remote that is tracking only the master branch of the official lammps repo
git remote add -t master lammps git@github.com:lammps/lammps.git
# fetch relevant remote data into the local git repo
git fetch lammps
# create a local branch 'lammps-master' that tracks the upstream master branch (never do development on this branch. only do "git pull" to update it)
git checkout -t lammps/master -b lammps-master
# now create a new local feature branch 'new-devel' for your new development that starts from 'lammps-master' as branching off point
git checkout -b new-devel lammps-master
# hack away and when you are done push the feature branch to your own repo (and set up automatic push/pull)
git push -u origin new-devel
```
i am doing the the equivalent procedure, but reversed, when i add changes to a branch for a pull request.

**Comment by sjplimp** [comment]
I'm confused by the doc pages.  Are we saying all these optional lines
no longer work in the data file (deprecated?), or they still work for now,
but will be deprecated in the future, so better to use only input script
options?

Is there any downside to removing all these "extra" settings from data files?
Maybe users want to hard-code the extra setting in the data file,
so they never have to worry about it again?  Can't recall the motivation
we originally had for doing it this way ...

**Comment by akohlmey** [comment]
@sjplimp according to wiktionary "deprecated" means: 'said of a construct in a computing language considered old, and planned to be phased out, but still available for use'

so it will remain available for the time being, but is not recommended for future use. the way i see it, we will phase it out very slowly, i.e. have the current state for a year or two, then remove the documentation for the header lines in the data file and then a couple years later remove the support for parsing them.

i don't see much of a downside. i think we're promoting consistency and reducing dependencies between data file and input file. i think, it is conceptually not a good strategy to have to modify a data file because you are adding a create_atoms command with a new atom type or want to read a second data file. it feels more natural to simply add/modify a keyword to the first read_data command.

people typically will have to do some tweaking on the input regardless of what you put in the data file. as far as i recall the history, the flags in the header were added first, when support for reading multiple data files was added. then it became apparent, that similar provisions were needed for create_box, but there is no file being read, so those had to become keywords. and then the extra/XXX/types keywords were added to read data. i think, if it had been obvious what this would evolve into, you probably would have gone all-keywords on this right away (for consistency).

with the "take the max of the two settings if both header flag and keyword are given" strategy people should be safe from surprises. i don't feel strong about removing the header flag parsing. i would be fine, if we just don't mention it anymore in the docs after some suitable time.

**Comment by sjplimp** [comment]
got it - thanks

Steve

**Comment by jewettaij** [comment]
Thanks Axel and Steve for dealing with this, and for the help using git!
(Alas, my other pull request is taking longer than I thought it would.
I'll send it in a few days.)
-Andrew

**Pull request merged**
