### PR TITLE
Port changes in #3280 to Kokkos

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Port changes in #3280 to Kokkos
Also fix a small bug in Kokkos ReaxFF

**Related Issue(s)**

#3280 

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
Kokkos regression tests passed.

**Comment by stanmoore1** [comment]
I'm seeing what looks like a bug in the pressure computation for the Kokkos version using the test case in #3280.

**Comment by stanmoore1** [comment]
Still debugging the pressure difference, getting closer...

**Comment by stanmoore1** [comment]
Found the bug--I think it should be pretty rare. When it compared equal tags it had bad behavior in one spot.

**Comment by athomps** [comment]
interesting. This tag check does not seem to exist in the non-kokkos code. A similar check exists in `fix_qeq_reax.cpp`, perhaps the some code pattern should be used in both places?

**Comment by stanmoore1** [comment]
@athomps I copied that check from Stillinger-Weber. The non-Kokkos code does `if (j < i) continue` instead. If I recall correctly, using atom tags allows better load balancing when running on multiple procs. They both turn a full neigh list into a half neigh list with newton off, i.e. skip half the owned-owned interactions and duplicate the owned-ghost interactions on both procs.

**Comment by stanmoore1** [comment]
The fix qeq/reax version adds this check as well `if (j < atom->nlocal)`, which turns a full neigh list into a half neigh list with newton _on_.

**Review by athomps — APPROVED** [review]
I approve.

**Pull request merged**
