### PR TITLE
Misc Improvements to GPU Package

### PR DESCRIPTION
**Pull request by wmbrownIntel**
**Summary**

Some small misc optimizations for the GPU package
- Optimizations for molecular systems
-   Improved kernel performance and greater CPU overlap
- Reduced GPU to CPU communications for discrete devices
- Switch classic Intel makefiles to use LLVM-based compilers (much shorter build times)
- Prefetch optimizations supported for OpenCL
- Optimized data repack for quaternions

**Related Issue(s)**

**Author(s)**

Mike Brown (Intel)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

- Three files are modified outside of GPU package: neighbor.h, neighbor.cpp, and doc/src/package.rst
- neighbor changes are protected by LMP_GPU macro and allow build_topology() to be called from GPU package instead to better overlap CPU/GPU
- Doc file has a single line change to add runtime prefetch configuration option for OpenCL
- Prefetch is only implemented for OpenCL; not in higher-level CUDA APIs
- Changed back some types for GPU casting; these should only be hit if GPU_CAST is defined (still experimental)
- Single line bug fix in lib/gpu/geryon/nvd_device.h for a non-default preprocessor option

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@wmbrownIntel these changes seem to break with Nvidia OpenCL and CUDA as well as on my desktop at home with Intel CPU/GPU . There are a whole bunch of test failures: 
https://ci.lammps.org/job/dev/job/pull_requests/job/gpu_unit_tests/285/

**Comment by akohlmey** [comment]
@wmbrownIntel  this is now passing the tests with Nvidia CUDA and OpenCL, but it fails on my home machine with Intel OpenCL and UHD graphics. Below is a typical error from compiling with -DGPU_DEBUG=on  and -DGPU_PREC=double and then running the unit tests. I tried with other precisions and it seems the issue is a fundamental one.
```
89: 
89: ----------------------------------------------------------
89:  UCL Error: Error compiling OpenCL Program (-2) ...
89: ----------------------------------------------------------
89: 
89: error: __builtin_IB_lsc_prefetch_global_uint: LSC not supported on this platform
89: in kernel: 'k_beck'
89: error: backend compiler failed build.
89: 
89: error: __builtin_IB_lsc_prefetch_global_uint: LSC not supported on this platform
89: in kernel: 'k_beck_fast'
89: error: backend compiler failed build.
89: 
89: ----------------------------------------------------------
```

**Comment by ndtrung81** [comment]
@wmbrownIntel thanks very much for the improvements and bug fixes. I hope the issues with the Intel OpenCL builds on UHD graphics would be resolved soon.

**Comment by wmbrownIntel** [comment]
The failures are for the prefetch intrinsics; didn't expect this on intel gpus. ...but I have added a fail safe to detect any failures with prefetch and fall back. Thanks.

**Comment by akohlmey** [comment]
@wmbrownIntel @ndtrung81 this now passes the unit tests on my Intel CPU/GPU box at home in double and mixed precision. So this is now good to go from my POV.

I have removed the ifdefs and duplicate code in the neighbor list code. I think this is such a small and localized change that it can always be present and thus simplify the code.

**Review by athomps — APPROVED** [review]
I approve.

**Pull request merged**
