### PR TITLE
bond/react: efficient competing reactions

### PR DESCRIPTION
**Pull request by jrgissing**
## Purpose

more efficient treatment of competing reactions

## Author(s)

JG

## Backward Compatibility

yes

## Implementation Notes

adds an extract to comm_brick to get local sendlist atoms. similar implementation for comm_tiled would require that comm_tiled has same format as comm_brick (e.g. private vs protected variables)

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by rbberger** [comment]
testing won’t run until conflicts are resolved

**Comment by akohlmey** [comment]
@sjplimp this touches the `Comm` class, so I won't even look at it before you approve of the changes.

**Comment by sjplimp** [comment]
@jrgissing if this means fix bond/react will only work with comm style brick, then it
needs to check if tiled is enabled and throw an error - otherwise the changes to Comm are minor additions

**Comment by jrgissing** [comment]
@sjplimp yes, currently it checks and simply reverts to a less efficient mode if tiled is enabled

**Comment by akohlmey** [comment]
@sjplimp this is now waiting for your approval, as it touches the Comm class, which you "own".

**Pull request merged**
