### PR TITLE
Update Kokkos library in LAMMPS to v3.2

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Update Kokkos library in LAMMPS to v3.2

**Related Issues**

None

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

**To-do:**

- [x] Kokkos regression testing
- [x] Performance regression testing
- [x] Update docs

### CODE REVIEW

**Comment by junghans** [comment]
@stanmoore1 I added some cmake updates.

**Comment by stanmoore1** [comment]
@junghans I forgot about that, thanks!

**Comment by stanmoore1** [comment]
With these changes I can now compile all of Kokkos LAMMPS with the HIP backend, using the version of Kokkos bundled with LAMMPS. However, there are still runtime issues. @arghdos

**Comment by akohlmey** [comment]
@stanmoore1 here is one thing from the lammps-users mailing list, that may be worth checking while you are on the compatibility "warpath" (part of the information was only sent to me even though I asked the person to respond to the list).
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaGetDeviceCount( & m_cudaDevCount ) error( cudaErrorInsufficientDriver): CUDA driver version is insufficient for CUDA runtime version /app/lammps/lammps-3Mar20_kokkos/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:204
```
This was done with CUDA 10.2 and apparently the machine is using the forward compatibility feature of recent CUDA toolkits, since it is running GPU accelerated calculations with the GPU package.

**Comment by stanmoore1** [comment]
@akohlmey OK do you have more details that you can email me?

**Comment by akohlmey** [comment]
> @akohlmey OK do you have more details that you can email me?

nope. that is all I have. I recall that there was some discussion on the kokkos slack, that the test for the cuda version may be off.

**Comment by stanmoore1** [comment]
I replied to the mail list thread. I have no idea how to reproduce the issue.

**Comment by akohlmey** [comment]
> I replied to the mail list thread. I have no idea how to reproduce the issue.

you would have a machine with CUDA 10.1 and the corresponding driver and then also install CUDA 10.2, but do not update the driver. in the old days that would be refused, but with the forward compatibility in newer drivers that can work. @rbberger has been using this on our machine learning servers to provide CUDA 10.2 without us having to update the driver. he can explain this better than me. i suspect that Kokkos might stumble over that. that is the only explanation that would be consistent with the information that I have.

**Comment by stanmoore1** [comment]
OK I'll take this info back to Kokkos slack.

**Comment by stanmoore1** [comment]
I talked to the Kokkos developers. They said that:

- The Kokkos 3.2 release (in this PR) does take into account the new forward compatibility feature of the driver
- The `cudaErrorInsufficientDriver` is not Kokkos complaining, it is actually the CUDA runtime reporting an error, which is then routed to the user by Kokkos. So this is a system error check, not Kokkos.

**Pull request merged**
