### PR TITLE
smeared charges for DPD

### PR DESCRIPTION
**Pull request by evoyiatzis**
**Summary**

It provides a new pair_style for short- & long-range smeared charges suitable for DPD simulations (known as "slater-type" charges). The mathematical description is given in J. Chem. Phys. 146, 124904 (2017); doi: 10.1063/1.4978809 Eq. (17)-(18).  

**Related Issues**

No related issue

**Author(s)**

Evangelos Voyiatzis (Royal DSM) email: evoyiatzis@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

It does not  break backward compatibility 

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [X] Licensing information is complete
- [X] Corresponding author information is complete
- [X] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [X] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@evoyiatzis this is missing documentation.
@sjplimp should this be moved to USER-MISC?

**Comment by evoyiatzis** [comment]
Is it ok to add a short description at pair_coul.rst instead of creating a separate rst file?

**Comment by sjplimp** [comment]
@evoyiatzis @akohlmey yes, I think it should be moved to USER-MISC.  Should the name of the pair style include dpd, or it more generic than that?

**Comment by evoyiatzis** [comment]
@sjplimp I think it is more general. it can be used with any soft-core potential to avoid artificial ion-pairing (which occurs with "usual" point charges). The "standard" DPD models are the most common ones. My way of using this potential is by combining it with the soft-core pair potentials via the pair_style hybrid/overlay command.
@akohlmey Is it ok to add a short description at pair_coul.rst instead of creating a separate rst file?

**Comment by akohlmey** [comment]
> @sjplimp I think it is more general. it can be used with any soft-core potential to avoid artificial ion-pairing (which occurs with "usual" point charges). The "standard" DPD models are the most common ones. My way of using this potential is by combining it with the soft-core pair potentials via the pair_style hybrid/overlay command.

would this be on top of pair style coul/cut/soft or coul/long/soft or instead of.

> @akohlmey Is it ok to add a short description at pair_coul.rst instead of creating a separate rst file?

For my personal taste the pair_coul.rst file is already overloaded, therefore hard to read, and thus should be broken into 2 or 3 separate files (similarly pair_lj.rst and a few others). This could be started right now with this change or later. Since this is more a policy decision than a technical issue, @sjplimp has the last word on that.

**Comment by sjplimp** [comment]
I'm not opposed to splitting the lj and coul doc pages.  So long as there
is one master page at the top which has links to the new subset pages.

**Comment by akohlmey** [comment]
> I'm not opposed to splitting the lj and coul doc pages. So long as there
> is one master page at the top which has links to the new subset pages.

We can do this at a later point. I should take a note and make some restructuring of the manual a talking point of our next in-person meeting. It'll be easier to figure out what you have in mind.

**Comment by akohlmey** [comment]
> @akohlmey Is it ok to add a short description at pair_coul.rst instead of creating a separate rst file?

yes (for now. we'll work out how to split that later), but you should wait until PR #1888 is merged to master and then update to it, as there are many changes to the documentation formatting and in particular we now embed all math with `:math:` or `..  math::` directives instead of relying on images rendered from external latex files. due to on-the-fly rendering with MathJax you can also embed LaTeX style expressions into the text.

**Comment by evoyiatzis** [comment]
@akohlmey I will have a look at the content of pair_coul_diel.rst and try to create a separate rst file for these two pair styles once you have merged PR 1888. No need to clutter even more the pair_coul.rst.

**Pull request merged**
