### PR TITLE
Add citation information to GitHub

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

Adds a `CITATION.cff` file to add citation information to GitHub. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Related Issue(s)**

**Author(s)**

@rbberger 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by rbberger** [comment]
@lammps/core  Noticed this feature today in https://github.com/spack/spack/ (right side below "About", "Cite this repository"). Might be useful for LAMMPS as well.

**Comment by akohlmey** [comment]
It think this file should be added to .gitattributes as export-ignore.
For the repository, wouldn't it be more consistent to mention the Zenodo DOI?

**Comment by rbberger** [comment]
That's really up to you. I've just added a boilerplate of what I think was the recommended citation. If you want people to cite the Zenodo DOIs instead, that can be done too. The format supports adding the regular `software` citation and a `preferred-citation`. Here is the full spec: https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md. There is also a tool to validate the file:
```
python3 -m pip install --user cffconvert
cffconvert --validate
```

**Comment by akohlmey** [comment]
@rbberger I'll leave the decision about whether to merge this and which citation(s) to include to @sjplimp and @athomps

**Comment by athomps** [comment]
This seems like a good idea.  I vote for maximum inclusion i.e. `software` citation, `preferred-citation`, and if possible also a citation to the 1995 paper.

**Comment by rbberger** [comment]
@athomps I've added what I think is necessary for the software citation part. I also added the ORCIDs for three of us I found on Zenodo.

**Review by athomps — APPROVED** [review]
I approve.

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
