### PR TITLE
GPU version of pair_style lj/smooth

### PR DESCRIPTION
**Pull request by gugmelik**
**Summary**

This pull request adds gpu acceleration for pair style lj/smooth.

**Related Issue(s)**

**Author(s)**
Gurgen Melikyan under supervision of Vsevolod Nikolskiy and Vladimir Stegailov (HSE University)
 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This PR does not break backward compatibility.

**Implementation Notes**

This new GPU pair style is based on the example of the pair style lj/cut/gpu. We have checked carefully that lj/smooth/gpu provides exactly the same results as lj/smooth up to the rounding off errors (if DOUBLE-DOUBLE precision is used on GPU).

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@gugmelik FYI, we just merged some improvements and corrections to the GPU package into upstream. The unittests will now also run on a GPU with CUDA and OpenCL if compiled accordingly.

**Comment by akohlmey** [comment]
@sjplimp FYI, this PR has clang-format applied to the new .h and .cpp files in "src/GPU"

**Comment by akohlmey** [comment]
@gugmelik Just updated your submission to the latest upstream code, made a few cosmetic changes, fixed a few minor issues with the docs, and applied our new clang-format. This looks good and passes the GPU unit tests with CUDA and OpenCL. Unless somebody else finds some problem, this will be included in the next patch release.

Thanks a lot for your contribution to LAMMPS.

**Review by ndtrung81 — APPROVED** [review]
@gugmelik Thanks for your contribution!

**Review by sjplimp — APPROVED** [review]

**Comment by sjplimp** [comment]
@ndtrung81 What do you think of this new clang formatting?

**Comment by gugmelik** [comment]
Thank you!🙂

**Comment by ndtrung81** [comment]
@sjplimp The formatting looks pretty good to me.

**Pull request merged**
