### PR TITLE
Iss1572clean: Clean fix for error handling, clarify data requirements for fix bocs input

### LINKED ISSUE #1572: [BUG] Fix error handling, clarify data requirements for fix bocs input
**Summary**

While working on #1109, I discovered a small problem with validation and error handling for the spline-basis input file that contains pressure corrections as a function of volume. This led to a discussion with the original authors (@mdelsyer and Dunn) and an initial agreement on a) how to fix the defect and b) on implementing, in both the code and the documentation, a clarification of the requirements for the input data. 

Since the clarification could change external behavior for some input data files, I'm recording this as a separate issue and asking the original authors to give a formal OK to my description of the new expected behavior below.

**LAMMPS Version and Platform**

Version: LAMMPS (18 Jun 2019) -- tested with code from master branch as of this afternoon
Platform: Ubuntu on Windows but problem behavior should be completely platform independent

**Expected Behavior**

1) Change the documentation to read: 
_The volumes in the file must be uniformly spaced._

2) Add validation code to ensure spline input volume values are uniformly spaced.

3) Any problem with the input values (missing, corrupt, or non-uniform) should be treated as an error and halt processing

4) An example set of inputs for a spline basis analysis, including a sample volume/pressure-correction file should be supplied.

**Actual Behavior**

The fix bocs documentation is fairly precise about the format required for the volume/pressure-correction data:
_With either spline method, the only argument that needs to follow it is the name of a file that contains the desired pressure correction as a function of volume. The file should be formatted so each line has:
Volume_i, PressureCorrection_i
Note both the COMMA and the SPACE separating the volume’s value and its corresponding pressure correction._
However, the only example data for this fix is for the analytic basis and so no volume/pressure-correction file is supplied.

But the doc is somewhat ambiguous about an additional requirement for the volume values:
_The volumes in the file should be uniformly spaced._
The authors now agree that their intention was that the code would work with a uniform distribution of splines and that the volume values must be uniformly spaced. 

Meanwhile, in the code, missing or corrupt values in the input file are handled with warning messages and simply omitted from the working data. This would result in fewer splines than intended and a non-uniform distribution of values.

**Steps to Reproduce**

I will create a small set of input files that trigger the new fatal error so I can test it. Right now you could at least see the warning generated if you simply add a blank line or omit on of the two values on a line in the input file.

**Further Information, Files, and Links**

### PR DESCRIPTION
**Pull request by eagunn**
**Summary**

Changed the code in the read_F_table function to conform to the "expected behavior" description in #1572. Adopted a best-of-both-worlds approach, though, and processed the whole input file all the way through, emitting a message for each problem found, before issuing a final error message to stop processing. 

Changed the doc to clarify the requirement for uniform volume spacing in the input file. This PR replaces #1578 which did not have one clean commit message and contained test files that belong in the lammps-testing project.

**Related Issues**

Closes #1572 

This change makes a tiny down-payment on #1109, plugging the smallest of the memory leaks by using a local variable rather than calloc'ing for an error message string.

**Author(s)**

E. Anne Gunn, Sheridan College (NWCCD)
agunn@sherprog.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Bad volume/pressure-correction data lines now generate error messages while the file is processed rather than causing problems/failures at some point downstream. Behavior should be unchanged for valid input files.

**Implementation Notes**

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

Test files that demonstrate the new error handling behavior will be checked into the lammps-testing repo as soon as I can get them reorganized and renamed to meet the conventions of that project.

### CODE REVIEW

**Comment by eagunn** [comment]
@rbberger I did a `merge --squash` of my original iss1572 branch into this one, to reduce the commits for my code changes to one. But I still see several merge pull requests in addition to my actual change, due to synch my repo's master branch with the lammps master. If there is a way to avoid those extra commits in the future, please advise.

**Comment by rbberger** [comment]
@eagunn If this is just about getting 0bda6e8c293acbe99a3069537199c0524f6761f2 merged in this PR, what you could do is:
```bash
# make sure "iss1572clean" is checked out
git checkout iss1572clean

# get latest upstream and merge it into branch
git remote add upstream git@github.com:lammps/lammps.git
git fetch upstream

# merge upstream/master into your branch
git merge upstream/master

# rebase based on upstream/master
git rebase upstream/master

# at the end of this your commits will be based on the
# latest upstream/master commit and all the merges should be gone

# finally force push to this branch
git push -f
```

**Comment by akohlmey** [comment]
rebased and force pushed it to update to current master for imminent merge

**Comment by eagunn** [comment]
@rbberger Thank you for the detailed instructions. I've never seen that path walked before. I'll use it on my next PR.
@akohlmey Thanks for the cleanup so the PR could get accepted.

**Pull request merged**
