### PR TITLE
KIM package corrections and refactoring

### PR DESCRIPTION
**Pull request by yafshar**
**Summary**
- Fixing a minor bug (`write_log_cite` interface)
- Enhancement (removing the `kim.log` on the start of a new simulation)
- Clean up the code (replace tabs with white spaces & correct the format according to the LAMMPS standard)
- Replacing the macro `SNUM`
  Following the [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines), avoid macros if you can (ES.30-33).

**Related Issues**
- Fixing a minor bug
   Fix the `write_log_cite` interface by correcting the data type. The `model_name` variable is a `char *` and not a `string`.
- Enhancement
  The `kim.log` was not created on each run which would result in a large file after multiple runs (the `KIM-API` appends the logging information to this file on each run.)

**Author(s)**

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@ellio167 @yafshar i did some additional refactoring and using the utils::split_words() convenience function and added an overloaded convenience variant for Variable::set() that just takes a single std::string as argument. updates a few APIs in the variable class (taken from a different branch not yet set up as a pull request). i hope you agree that this helps to simplify the code and make it more readable. please test it carefully, since we don't have many KIM tests in our regression test library (only the examples, and i am not certain whether they are currently even run, since we only very recently added the pre-compiled kim-api package to our test container images).

There is probably more than can be done to simplify and clean up the code. In general, we are trying to get rid of strtok() (and also std::stringstream, if possible). for parsing of files, you may also consider using the classes in tokenizer.h/tokenizer.cpp.
utils::split_words() is ok for a single line of text, but it is rather inefficient for larger texts.

for generating more complex strings, it may be more effective and/or more readable to use fmt::format() with automatic conversion through '{}' instead of concatenating strings and converting numbers with std::to_string().

**Comment by akohlmey** [comment]
@ellio167 since you mentioned trying your hand at unit testing, there are now some more example tests in unittest/commands and it would be a good opportunity to add tests it for the KIM package commands. If we had a decent test coverage of those commands, the refactoring that I just did would be much less risky as the tests could indicate when things break.

**Comment by akohlmey** [comment]
for your convenience, I have added a template for a kim command tester tool with a couple of minmal tests.

**Comment by yafshar** [comment]
> for your convenience, I have added a template for a kim command tester tool with a couple of minmal tests.

@akohlmey sounds great. Thanks for initiating that we will complete the unit test for different `kim_commands`.

**Comment by akohlmey** [comment]
@yafshar I have updated the PR branch with a corrected utils::split_words() function, expanded its unit tests and applied the quotes to the variable set command in kim_property.cpp. This will actually improve the code in utils to be consistent with regular LAMMPS input parsing. We'll have to see if there is any breakage with our detailed regression tests, but if there is, that just means there is code that I need to fix. 
When adding unit tests, please make sure you construct them so that they don't fail for cases where the KIM package is not installed, there is no internet connection, or the kim-property module is not installed, and instead skip the test. We don't want reports of tests failing because prerequisites are missing. The template is rather minimal, so you need to look around for what other tester codes do, how to achieve this. This built in testing is a work in progress and still evolving (although it is stabilizing for what it does). Please note that are test for the explicit use of the kim pair style and specifically its reporting of energies and forces is already in the unittest/force-styles/ tree, so you can focus on syntax and behavior of the commands themselves.

**Comment by yafshar** [comment]
> @yafshar I have updated the PR branch with a corrected utils::split_words() function, expanded its unit tests and applied the quotes to the variable set command in kim_property.cpp. This will actually improve the code in utils to be consistent with regular LAMMPS input parsing. We'll have to see if there is any breakage with our detailed regression tests, but if there is, that just means there is code that I need to fix.
> When adding unit tests, please make sure you construct them so that they don't fail for cases where the KIM package is not installed, there is no internet connection, or the kim-property module is not installed, and instead skip the test. We don't want reports of tests failing because prerequisites are missing. The template is rather minimal, so you need to look around for what other tester codes do, how to achieve this. This built in testing is a work in progress and still evolving (although it is stabilizing for what it does). Please note that are test for the explicit use of the kim pair style and specifically its reporting of energies and forces is already in the unittest/force-styles/ tree, so you can focus on syntax and behavior of the commands themselves.

@akohlmey the problem is fixed now. I will test and make sure when adding components for the tests to not fail for cases where the KIM package is not installed or there is no internet connection.

**Comment by akohlmey** [comment]
FYI, we plan to release a new patch on Tuesday and I would like to have this pull request included, so please push any corrections, additional updates and improvements by Monday. More changes can be submitted later as a separate pull request.

**Comment by akohlmey** [comment]
@yafshar @ellio167 please let me know, if you plan to push more changes to the PR or whether I can check it one more time and then, if it passes, merge?

**Comment by yafshar** [comment]
> @yafshar @ellio167 please let me know, if you plan to push more changes to the PR or whether I can check it one more time and then, if it passes, merge?

@akohlmey I am adding more tests, but it is not ready yet. We have more updates that we plan to do in a separate PR later. So please go ahead.

**Pull request merged**
