### PR TITLE
Optimized implementation of FIRE

### PR DESCRIPTION
**Pull request by jguenole**
#work_in_progress

## Purpose

In Bitzek's group (FAU Erlangen-Nuernberg, Germany) we were wondering why we observe a different behavior of FIRE in LAMMPS versus the implementation in IMD (https://github.com/itapmd/imd). 
After carefully comparing the two implementations, we realized that IMD included several optimizations that are not included in LAMMPS.

Attached you’ll find two examples to show the improved performance of our new implementation. Our intention is to publish a study of the impact of algorithmic implementation details on the efficiency and to provide an optimized FIRE implementation for LAMMPS.

newfireimplementation_sivacancies
newfireimplementation_mgalloy

## Author(s)

Julien Guénolé, RWTH Aachen University
Erik Bitzek, FAU Erlangen-Nuernberg

## Backward Compatibility

None.

## Implementation Notes

For compatibility reason, it is currently named adaptglok (min_style adaptglok). A lot of parameters can be adjusted by using the min_modify command.

A simple box relaxation scheme (iso, aniso, x, y, z) has been implemented by using min_modify. However, the compution of the pressure seems wrong in some cases (when the box dimensions change significantly) and needs corrections.

@sjplimp, @athomps: for now, our new implementation uses the different class "adaptglok". Regarding backwards compatibility / reproducibility, would it be preferable to replace the current FIRE by this new version, or just switch from one to the other by options within min_modify? 
We feel that actually our overworked implementation of FIRE is closer to original FIRE-“spirit”, and would therefore like to keep the name FIRE for the new implementation.

As shown in the attached flow charts, there are two main differences between the actual (class MinFire) and new implementation (class MinAdaptGlok) of Fire:
- modification of the integration scheme
- the half-step-back in the pseudo-dynamic integration scheme, when v.f <= 0

[2017-07_Fire-Adaptglok-Lammps_v1.pdf](https://github.com/lammps/lammps/files/2282388/2017-07_Fire-Adaptglok-Lammps_v1.pdf)

## Usage
Minimal:
`min_style adaptglok`
`minimize 0.0 1e-8 20000 20000`

With box relaxation:
`min_style adaptglok`
`min_modify relaxbox aniso relaxbox_mod 1e6`
`minimize 0.0 1e-8 20000 20000`

Personalized:
`min_style adaptglok`
`min_modify dmax 0.02 delaystep 20 dtgrow 1.1 dtshrink 0.5 alpha0 0.25 alphashrink 0.99 tmax 10.0 tmin 0.01 integrator verlet halfstepback yes initialdelay yes vdfmax 2000 relaxbox y relaxbox_mod 1e7 relaxbox_rate 0.2 ptol 0.01`
`minimize 0.0 1e-8 20000 20000`

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] Correct the relaxbox option.
- [ ] The features in this pull request are complete
- [ ] Cleanup the  #code.
- [ ] Choose the final name of this implementation (replace current Fire or a new minimizer?)
- [ ] Refine the updated documentation files
- [ ] One or more example input decks are included
- [ ] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

A preprint will be available on Arxiv in 1-2 weeks.

### CODE REVIEW

**Comment by sjplimp** [comment]
@jguenole Taking my first look at this, will look at the code next.  Just a couple conceptual
comments/Qs.  I think it would be fine to make this version the new min_style fire,
i.e. remove the current one.  I assume there is no functionality the old one has, that
the new one does not?  Nor problems where the old one give better convergence?
I suggest waiting until the last step to rename this one, remove the old one.  So you
can compare both methods.  Re: box relax.  Is there no way to make the new fire work
with fix box/relax, like other min styles do?  Or if your box relax is doing something
better, to add its ideas to fix box/relax, either as options or replacements?

**Comment by jguenole** [comment]
@sjplimp Sorry for the delay, I was away for the week...

There is indeed no functionality the old FIRE has, that are not provided by the new one. Actually, the behavior of the old one could be entirely reproduce by a specific set of parameters with min_modify. For backward compatibility and reproducibility, that could be mentioned in the documentation.

Regarding the fix box/relax, I initially tried to make it working with this new fire... but without success. My attempts were however pretty limited, as I do not exactly understand why it cannot works with "damped dynamics min style".
So, to have something working, the implementation I made of box relaxation is very-rudimentary, much simpler than box/relax. But I discovered recently that my piece of code to relax the box is actually bugged: when the dimensions of the box are modified too much (ie initial pressure far from 0), the pressure is not computed correctly after some iterations. I'll work on it in the next days...

**Comment by sjplimp** [comment]
@jguenole Sounds good - I like the idea of explaining in the doc page how to reproduce the old FIRE results. Re: box/relax, what you are calling a "bug" might be the same issue that the other minimizers have, as explained on the fix box/relax doc page.  Namely that objective function is only well-posed if the reference box size/shape and reference pressure has not changed much. So often you need to restart the minimizer (i.e. invoke minimize multiple times) or use the nreset option to continually reset the reference box size/shape.  Another issue might be how the kinetic term in the pressure is computed to compare to the target press.  For CG (etc) the velocities never change so the kinetic term is constant. But for damped dynamics the kinetic term could be fluctuating in an odd way?

**Comment by jguenole** [comment]
@sjplimp Ah yes, indeed that appears very similar to the behavior of box/relax. I tested with this new fore, and a successive second minimization with the new fire effectively minimize the pressure properly.

What bother me in the case of the "issue" of this pull request, is that the pressure printed by "thermo" is actually wrong when the box changes too much. E.g the pressure at the end of the minimization is printed close to 0, but a simple run 0 just after it will print a (correct) pressure largely different. As you suggested, the kinetic term of the pressure might be a reason. I'll go though the code to try spotting any logical / misunderstanding.

**Comment by jguenole** [comment]
I re-wrote the method that relax the box, by getting inspiration from the change_box command. 
When the simulation box size changes too much, PBC are lost. It can be corrected by increasing the skin value (command neighbor).
I assume it is a problem in generating the neighbor list, since it is independent of the number of CPU.

**Comment by akohlmey** [comment]
> I re-wrote the method that relax the box, by getting inspiration from the change_box command.
> When the simulation box size changes too much, PBC are lost. It can be corrected by increasing the skin value (command neighbor).
> I assume it is a problem in generating the neighbor list, since it is independent of the number of CPU.

More likely, this is due to the communication cutoff (which implicitly depends on the neighborlist skin. its default is: largest pair cutoff plus neighbor skin). Whenever the system changes shape significantly, you are running into danger of losing atoms, since LAMMPS will only communicate atoms between neighboring domains, so the desired atoms have to be withing the ghost atom range, which is set by the communication cutoff. If there is an empirical way to determine a required communication cutoff, you could test for that, or otherwise limit the amount of a box change, so that it doesn't require communicating atoms beyond that cutoff. In the documentation, it would be better to recommend changing the communication cutoff, as it has less performance impact, than changing the neighbor skin.

**Comment by jguenole** [comment]
> More likely, this is due to the communication cutoff (which implicitly depends on the neighborlist skin. its default is: largest pair cutoff plus neighbor skin). Whenever the system changes shape significantly, you are running into danger of losing atoms, since LAMMPS will only communicate atoms between neighboring domains, so the desired atoms have to be withing the ghost atom range, which is set by the communication cutoff. If there is an empirical way to determine a required communication cutoff, you could test for that, or otherwise limit the amount of a box change, so that it doesn't require communicating atoms beyond that cutoff. In the documentation, it would be better to recommend changing the communication cutoff, as it has less performance impact, than changing the neighbor skin.

Thanks for the indication! 
I just tested and indeed, choosing specific larger values for the communication cutoff effectively allow box relaxation for large displacement. 
A good value seems however to be the results of a subtle relation between system size, number of core, etc. I'll look at it further...

**Comment by sjplimp** [comment]
@jguenole Hi - I will try to look this over again, more carefully, the week after
the Tgiving break.  Sorry for the delay.

**Comment by akohlmey** [comment]
postponing until after the workshop.

**Comment by jguenole** [comment]
The document associated with these changes (called FIRE2.0 in it) is finally online: https://arxiv.org/abs/1908.02038 

In the mean time (https://github.com/lammps/lammps/pull/1052/commits/c2e400910652defcff31ebc4559ae053db58d97a), I removed the option for minimizing the pressure of the simulation. It was largely bugged. So now, it basically works as the current FIRE, but better.

I could suggest two ways:
- Replace the current implementation of FIRE, and mention in the documentation the parameters of `min_modify` to reproduce the behavior of the first version of FIRE. Getting the _exact_ same behavior as FIRE might not be guaranty since the code is largely re-written.
- Create two additional `min_style` (`fire1`, `fire2`). `fire1` correspond to the current FIRE, and `fire2` to the new implementation. `fire` would be an alias of `fire2`. In this way, full backward compatibility is ensured, and any user that would like to use again the first FIRE (for reproducibility checks as an example) could use the exact same code.

When you will have chosen how to proceed, I will modify the files and update the documentation accordingly.

**Comment by jguenole** [comment]
I updated the code to follow the last advances (no leapfrog integration scheme anymore). The current unsuccessful check and conflict are trivial to resolve when it will be decided how to merge it (see previous message).

Regarding the integration of this piece of code, I realize that it could also be done by means of a user package USER-FIRE2. That will make these changes less invasive and maybe ease the integration within the Lammps project?

**Comment by jguenole** [comment]
I renamed the min_style "fire2" instead of "adaptglok".
I strongly simplified the documentation, hiding most of the non-critical parameters.

If you feel that this pull request should not make it into the main code, I could try to convert it into a "fix", but I'm not certain that it is possible to reproduce the identical behavior.

**Comment by rbberger** [comment]
@sjplimp @athomps I fixed the merge conflicts due to the documentation changes. Now it's ready for merge. Let us know what you want to do with this PR.

**Comment by sjplimp** [comment]
@rberger @athomps I will try to look at the latest on this one next week.

**Comment by sjplimp** [comment]
@jguenole This all looks great.  Sorry again for the long delay in getting this added to LAMMPS.  My bad!  Here are a few final suggestions.  @akohlmey may have opinions as well.

(1) I think the existing fire should be renamed fire/old.  And the new fire2 be renamed fire.  So that the new, more robust, more optimized one is what users will typically use.  The old one can be retained for some period of time.  Above you mentioned the new fire could reproduce old fire with appropriate settings?  Is that explained in the doc pages?  If not, might be useful to add.  I didn't see it.

(2) On the min_style doc page, explain the features both fire/old and new fire have.  I.e. what is the FIRE minimizer.  Then a short paragraph highlighting the new, better features of the new fire.  And saying fire/old is the original fire in LAMMPS, still there for backward compatibility.  That might also be the place to explain how new fire can reproduce old fire if you do x,y,z.

(3) Top of min_fire2.cpp - check that the attribution to you as authors is correct.

(4) Something relatilvely new in the minimizer options is that the norm keyword has a new max option.  The doc page makes it sound like new fire does not recognize the norm keyword  (any of its options).  Is that correct?  If so, maybe explain how new fire handles thatt differently?

(5) For users it might be nice to have a new examples dir, which exercises a few of the minimizers on a simple problem or two.  Say examples/fire.  Or add some scripts to examples/min.  These should be small problems that run for less than a minute (or faster) on a single core.  They could illustrate the syntax and relative convergence performance of a few of the styles.

Thanks again for contributing this to LAMMPS - very nice work!

**Comment by sjplimp** [comment]
@jguenole Actually I think it is the "inf" setting that is new for the "norm" keyword for min_modify.

**Comment by sjplimp** [comment]
@jguenole Not seeing my small edits in this PR though I pushed them.  Possibly it is showing up as a pull request in your repo.

**Comment by akohlmey** [comment]
> @jguenole Not seeing my small edits in this PR though I pushed them. Possibly it is showing up as a pull request in your repo.

@sjplimp you may need to refresh the page. both commits show up for me.

**Comment by jguenole** [comment]
@sjplimp thanks for all your feedback! 
> (1-3,5) That sounds indeed nice to replace it. I will rework the files name accordingly. I will also rework the documentation as you suggested, and include some small examples. 
> (4)  yes, started to work on the implementation long before the inclusion of the "norm" option. I will have a look at it.

**Comment by sjplimp** [comment]
@jguenole Great.  If you can make these changes by end of Jan, it should become part of the next LAMMPS stable release (mid-Feb).

**Comment by jguenole** [comment]
@sjplimp hopefully all the corrections are done!
- fire renamed fire/old
- fire2 renamed fire
- Note in the documentation to reproduce fire/old with fire
- fire now consider all the "norm" options
- rework of the documentation, with some details on the difference between fire and fire/old
- examples (folder fire) directly inspired from "min" and "neb" that show how to use fire, avec the differences with cg, quickmin and fire/old.

In the next days, I will continue to check whether I forgot some typo or wrong wording somewhere.

**Comment by akohlmey** [comment]
FYI, I just updated this branch to latest master and fixed a few whitespace and format issues in the updated manual pages

**Pull request merged**
