### PR TITLE
Non-linear ACE potential for MD simulations of hydrocarbons

### PR DESCRIPTION
**Pull request by jtwillman**
**Summary**

Non-linear ACE potential for MD simulations of hydrocarbons (CH_Willman_JCP2024.yace), as detailed in Journal of Chemical Physics (https://doi.org/10.1063/5.0213560) has been added to lammps/potential folder along with potential declaration file (CH_Willman_JCP2024.pot.mod)

**Related Issue(s)**

**Author(s)**
Jonathan T. Willman* <willman@lanl.gov>, Romain Perriot, Christopher Ticknor

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**
N/A

**Implementation Notes**
N/A

**Post Submission Checklist**

- [X ] The feature or features in this pull request is complete
- [ X] Licensing information is complete
- [X ] Corresponding author information is complete
- [ X] The source code follows the LAMMPS formatting guidelines
- [ X] Suitable new documentation files and/or updates to the existing docs are included
- [X ] The added/updated documentation is integrated and tested with the documentation build system
- [X ] The feature has been verified to work with the conventional build system
- [ X] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**
https://doi.org/10.1063/5.0213560

### CODE REVIEW

**Comment by akohlmey** [comment]
@jtwillman Thanks for your submission. Is this in support of any upcoming feature in LAMMPS?
If no, wouldn't it be better to submit it here: https://www.ctcms.nist.gov/potentials/

**Comment by jtwillman** [comment]
Hi Axel,

We have recently had a paper accepted to JCP, where we state that the potential will be available on the lammps github page. This is a non-linear ace potential specifically to be used with lammps. Last year I submitted the potential files for a carbon quadratic snap potential (C_SNAP_2021.10.15.quadratic.coeff and C_SNAP_2021.10.15.quadratic.param) and was following the same protocal here.

Thanks,
Jonathan Willman

From: Axel Kohlmeyer ***@***.***>
Reply-To: lammps/lammps ***@***.***>
Date: Monday, August 12, 2024 at 12:59 PM
To: lammps/lammps ***@***.***>
Cc: "Willman, Jonathan Tyler" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [lammps/lammps] Non-linear ACE potential for MD simulations of hydrocarbons (PR #4272)


@jtwillman<https://urldefense.com/v3/__https:/github.com/jtwillman__;!!Bt8fGhp8LhKGRg!Cfqj_oXkOoQcUsGEt-y5J2x-PHbfYGG47J50MF63qpy6orHn7U4JndAnyDkUFC5HTB8J-GOq41dJaeRCwqWHdUaV$> Thanks for your submission. Is this in support of any upcoming feature in LAMMPS?
If no, wouldn't it be better to submit it here: https://www.ctcms.nist.gov/potentials/<https://urldefense.com/v3/__https:/www.ctcms.nist.gov/potentials/__;!!Bt8fGhp8LhKGRg!Cfqj_oXkOoQcUsGEt-y5J2x-PHbfYGG47J50MF63qpy6orHn7U4JndAnyDkUFC5HTB8J-GOq41dJaeRCwtZ_8AfT$>

**Comment by akohlmey** [comment]
> We have recently had a paper accepted to JCP, where we state that the potential will be available on the lammps github page. This is a non-linear ace potential specifically to be used with lammps. Last year I submitted the potential files for a carbon quadratic snap potential (C_SNAP_2021.10.15.quadratic.coeff and C_SNAP_2021.10.15.quadratic.param) and was following the same protocal here.

I have to discuss this with @athomps who is currently on vacation. But please note that the potentials folder in the LAMMPS distribution is not *meant* to be a repository for all kinds of potentials that people have derived. There is a bit of lenience toward SNAP, since that is a feature integral to LAMMPS so what supports SNAP is looked up favorably.

Making potentials available in ready-to-use form is really what the NIST data base website is for.

**Comment by jtwillman** [comment]
Many thanks Axel,

Apologies for not checking if this would be OK first, I was unaware there was a preference for SNAP potentials. I will wait for Aidan’s response. Also, thanks for mentioning the NIST database which we had not considered. We will make sure to submit the potential there as well.

Regards,
Jonathan Willman

From: Axel Kohlmeyer ***@***.***>
Reply-To: lammps/lammps ***@***.***>
Date: Monday, August 12, 2024 at 2:33 PM
To: lammps/lammps ***@***.***>
Cc: "Willman, Jonathan Tyler" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [lammps/lammps] Non-linear ACE potential for MD simulations of hydrocarbons (PR #4272)


We have recently had a paper accepted to JCP, where we state that the potential will be available on the lammps github page. This is a non-linear ace potential specifically to be used with lammps. Last year I submitted the potential files for a carbon quadratic snap potential (C_SNAP_2021.10.15.quadratic.coeff and C_SNAP_2021.10.15.quadratic.param) and was following the same protocal here.

I have to discuss this with @athomps<https://urldefense.com/v3/__https:/github.com/athomps__;!!Bt8fGhp8LhKGRg!C9bPcEd57c6hpJXOAD-18V5YVxoZ5ls0i43NaEW_WHlntEvxibHB-Aj-xUtJNBIoNig6cOs3NF7jBRCAXlHwhE-2$> who is currently on vacation. But please note that the potentials folder in the LAMMPS distribution is not meant to be a repository for all kinds of potentials that people have derived. There is a bit of lenience toward SNAP, since that is a feature integral to LAMMPS so what supports SNAP is looked up favorably.

Making potentials available in ready-to-use form is really what the NIST data base website is for.

**Comment by athomps** [comment]
I agree with @akohlmey that the primary purpose of the `potentials` directory is to provide interatomic potential files needed to demonstrate particular code features e.g. pair styles that have a corresponding usage example in the `examples` dir.  In the case of 'examples/snap' we got a bit carried away in the past :-). But new SNAP potentials not associated with a major new code feature are now posted to the NIST repo rather than LAMMPS e.g. https://www.ctcms.nist.gov/potentials/system/C-W-Zr/

**Pull request closed without merging**
