### PR TITLE
USER-DPD Bugfix: reset_dt() is not called when I thought it should be called.

### PR DESCRIPTION
**Pull request by timattox**
Move the calculation of dtsqrt inside FixShardlow::initial_integrate() where it is needed.

This corrects a serious bug discovered with a new ARL-internal USER-DPD test case.

### CODE REVIEW

**Comment by timattox** [comment]
Woops, hold off a second, I have one more minor change for this pull request,

**Comment by timattox** [comment]
This now passes all my test cases.

**Comment by akohlmey** [comment]
ok. @timattox do you have time for a little experiment? are you able to assign the PR to steve? that would tell him, that the PR is ready to be merged. ...and then try to (temporarily) unassign him. In case the same situation happens, and i am not able to react quickly. Unassigning steve would be the signal to wait with merging it.

**Comment by timattox** [comment]
I don't see any "active" controls on this webpage for assigning the PR to steve or to add labels, etc., so I don't think I have enough privileges to do so.

**Comment by akohlmey** [comment]
Thanks a lot for confirming.

**Pull request merged**
