### PR TITLE
Small Kokkos changes

### LINKED ISSUE #3927: [BUG] Kokkos does not work with property/atom rmass
**Summary**

<!--Please provide a clear and concise description of what the bug is.-->

When running with peoperty/atom rmass with Kokkos,  an illegal memory access error was raised.

Our purpose is to run lammps with per-atom mass using `peoperty/atom rmass` command to run [hydrogen mass repartitioning](http://ambermd.org/tutorials/basic/tutorial12/index.php) for proteins, in this way we could use a larger timestep. However, an error was raised when running with kokkos. The regular verision without kokkos works great.


**LAMMPS Version and Platform**

Large-scale Atomic/Molecular Massively Parallel Simulator - 28 Mar 2023 - Development
Git info (HEAD / patch_28Mar2023-121-gff5b4e971d)

**Expected Behavior**

Run normally when using kokkos with rmass

**Actual Behavior**

Error message
```
$ mpirun -np 1 /blue/apps/lammps-ani/external/lammps/build/lmp_mpi -k on g 1 -sf kk -i run.in.hmr.npt
Setting up Verlet run ...
  Unit style    : real
  Current step  : 0
  Time step     : 2
WARNING: Fixes cannot yet send exchange data in Kokkos communication, switching to classic exchange/border communication (src/KOKKOS/comm_kokkos.cpp:651)
cudaStreamSynchronize(stream) error( cudaErrorIllegalAddress): an illegal memory access was encountered /blue/apps/lammps-ani/external/lammps/lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:172
Backtrace:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Kokkos::Impl::save_stacktrace() [0x14d8403620f5]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Kokkos::Impl::traceback_callstack(std::ostream&) [0x14d840358b0a]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Kokkos::Impl::host_abort(char const*) [0x14d840358b3b]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Kokkos::Impl::cuda_internal_error_abort(cudaError, char const*, char const*, int) [0x14d840368567]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Kokkos::Impl::cuda_stream_synchronize(CUstream_st*, Kokkos::Impl::CudaInternal const*, std::string const&) [0x14d84036888d]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Kokkos::Impl::ParallelReduce<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>, Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> >, Kokkos::InvalidType, Kokkos::Cuda>::execute() [0x14d83a4d7f9c]
                                                                                                                                                                                                                                                                                                                                                                                             Kokkos::Impl::ParallelReduceAdaptor<Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> >, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::execute_impl(std::string const&, Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> > const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda> const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP&) [0x14d83a4d6889]
std::enable_if<!(Kokkos::Impl::ParallelReduceAdaptor<Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> >, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::is_array_reduction&&std::is_pointer<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::value), void>::type Kokkos::Impl::ParallelReduceAdaptor<Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> >, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::execute<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>(std::string const&, Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> > const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda> const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP&) [0x14d83a4d574f]
                                                  std::enable_if<Kokkos::is_execution_policy<Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> > >::value&&(!((Kokkos::is_view<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::value||Kokkos::is_reducer<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::value)||std::is_pointer<LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>::value)), void>::type Kokkos::parallel_reduce<Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> >, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP>(Kokkos::RangePolicy<Kokkos::Cuda, LAMMPS_NS::TagComputeTempScalar<1> > const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda> const&, LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::s_CTEMP&) [0x14d83a4d48c0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       LAMMPS_NS::ComputeTempKokkos<Kokkos::Cuda>::compute_scalar() [0x14d83a4d2eb2]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   LAMMPS_NS::FixNHKokkos<Kokkos::Cuda>::setup(int) [0x14d83a14ba56]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                LAMMPS_NS::ModifyKokkos::setup(int) [0x14d83a205c87]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                LAMMPS_NS::VerletKokkos::setup(int) [0x14d83a7a649d]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               LAMMPS_NS::Run::command(int, char**) [0x14d839800977]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                LAMMPS_NS::Input::execute_command() [0x14d8395bb7e3]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           LAMMPS_NS::Input::file() [0x14d8395b8195]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [0x40128b]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  __libc_start_main [0x14d83635fd85]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [0x40115e]
```

The full error message is attached: [error_message.txt](https://github.com/lammps/lammps/files/12786243/error_message.txt)

**Steps to Reproduce**

<!--Describe the steps required to (quickly) reproduce the issue. You can attach (small) files to the section below or add URLs where to download an archive with all necessary files. Please try to create an input set that is as minimal and small as possible and reproduces the bug as quickly as possible. **NOTE:** the less effort and time it takes to reproduce your reported bug, the more likely it becomes, that somebody will look into it and fix the problem.-->

[00-water-force_field-kokkos_rmass_debug_minimal.zip](https://github.com/lammps/lammps/files/12786248/00-water-force_field-kokkos_rmass_debug_minimal.zip)

A minimal reproducible example is attached, to run them, build lammps with kokkos and gpu
```bash
# 1. no rmass, no kokkos ✅
mpirun -np 1 lmp_mpi -i run.in.npt
# 2. no rmass, with kokkos ✅
mpirun -np 1 lmp_mpi -k on g 1 -sf kk -i run.in.npt
# 3. with rmass, no kokkos ✅
mpirun -np 1 lmp_mpi -i run.in.hmr.npt
# 4. with rmass, with kokkos ❌
mpirun -np 1 lmp_mpi -k on g 1 -sf kk -i run.in.hmr.npt
```

**Further Information, Files, and Links**

<!--Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications-->

### LINKED ISSUE #3929: [BUG] Dynamic groups do not update when run with KOKKOS.
**Summary**

Dynamic groups do not update when run with KOKKOS.

**LAMMPS Version and Platform**

LAMMPS (2 Aug 2023 - Development - patch_2Aug2023-439-g49f08e6231)

**Expected Behavior**

the attached input produces 3 dump files. As the temperature increases, atoms cease to be in the FCC configuration and are thus removed from the group fccg. These atoms are then no longer printed in the dump file.

**Actual Behavior**

When run with the KOKKOS package, the group fccg is not updated and thus all atoms are printed in every dump file at every time step. 

Variables and computes are updating properly, as can be seen in the dump files.

**Steps to Reproduce**

Correct behavior:
<lmp> -in render.txt
Then examine contents of dump-fcc.2000.lammpstraj
Incorrect behavior
<lmp> -in render.txt -k on g 1 -sf kk (Or whatever accelerator you are using)
Then examine contents of dump-fcc.2000.lammpstraj

[render.txt](https://github.com/lammps/lammps/files/12792483/render.txt)

### LINKED ISSUE #3935: [Feature Request] Add support for LLNL's FLUX scheduler
**Summary**

LLNL's Flux scheduler currently fails to run with LAMMPS due to lack of correctly defined MPI environment variables here:
https://github.com/lammps/lammps/blob/49f08e6231169d3f76aced42f4135ae6d3c24c49/src/KOKKOS/kokkos.cpp#L140-L181C27

Run command: 
```
flux run -N1 -n4 -c8 -g1 \
  ${INSTALL_DIR}/lmp \
  -k on g 4 -sf kk -pk kokkos cuda/aware on neigh full comm device neigh/qeq full newton on -v x 8 -v y 8 -v z 8 -v steps 600 -in in.lj -nocite -log log.lammps
```

Error message:
```
Error: Could not determine local MPI rank for multiple GPUs with Kokkos because MPI library not recognized (src/KOKKOS/kokkos.cpp:180)
```

**Detailed Description**

Maybe need to add implementation details for FLUX which should be something like:
```
      if ((str = getenv("FLUX_TASK_LOCAL_ID"))) {
        if (ngpus > 0) {
          int local_rank = atoi(str);
          device = local_rank % ngpus;
          if (device >= skip_gpu) device++;
          set_flag = 1;
        }
      }
```
See: https://github.com/flux-framework/flux-core/issues/669

Although, when I added this to `/src/KOKKOS/kokkos.cpp` and rebuilt, I'm getting errors:
```
ERROR: Requested GPU with id '1' but only 1GPU(s) available! Raised by Kokkos::initialize().
ERROR: Requested GPU with id '2' but only 1GPU(s) available! Raised by Kokkos::initialize().
ERROR: Requested GPU with id '3' but only 1GPU(s) available! Raised by Kokkos::initialize().
```
So, I believe it is not capturing an env variable (like ${FLUX_LOCAL_RANKS}) and just defaulting to a single visible device for all ranks.

**Further Information, Files, and Links**

N/A

### LINKED ISSUE #3936: [BUG] hybrid/overlay with KOKKOS overwrites atom forces, rather than sums them
**Summary**

When calling hybrid/overlay with KOKKOS package, the second potential replaces atom forces rather then adds to them.

**LAMMPS Version and Platform**

LAMMPS (2 Aug 2023 - Development - patch_2Aug2023-540-gc0ace4aa4b)'

Note: This bug is NOT present in LAMMPS (28 Mar 2023 - Development)

**Expected Behavior**

When running the attached input we expect to see forces being applied by the LJ potential which has a 20 angstrom cutoff.

**Actual Behavior**

When running the attached input with KOKKOS we see all forces are zero, because they have been overwritten by the extremely small cutoff zbl potential.

**Steps to Reproduce**

lmp -in test-hybrid.txt -k on g 1 -sf kk (or whatever KOKKOS accelerator you are using)
examine forces in dump.0.lammpstraj, they should be zero

lmp -in test-hybrid.txt 
examine forces in dump.0.lammpstraj, they should be non-zero

**Further Information, Files, and Links**

[test-hybrid.txt](https://github.com/lammps/lammps/files/12861195/test-hybrid.txt)

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

- Add support for FLUX scheduler/runtime
- Fix harmless compiler warnings
- Add missing code for dynamic groups
- Fix issue with Kokkos `fix property/atom`
- Add error check in Kokkos PACE for unsupported radial basis style
- Fix bug with Kokkos `pair hybrid/overlay` + full neighbor list where forces were zeroed out erroneously

**Related Issue(s)**

Fixes #3927
Fixes #3929 
Fixes #3935
Fixes #3936

**Author(s)**

Stan Moore

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
Running this through full Kokkos regression testing.

**Comment by stanmoore1** [comment]
This PR is waiting on https://github.com/ICAMS/lammps-user-pace/pull/19 so the regression tests will run.

**Comment by stanmoore1** [comment]
All Kokkos regression tests passed.

**Comment by akohlmey** [comment]
@stanmoore1 would you mind re-running your tests?
I noticed an opportunity to use the new accessor API for fixes in the changes (and then two more cases), but the property/atom one is a bit of a fragile change (I already noticed and addressed one bug while writing this message).

**Comment by stanmoore1** [comment]
Will do.

**Comment by akohlmey** [comment]
> Will do.

Thanks a lot.

**Comment by stanmoore1** [comment]
@akohlmey the tests passed again

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
