### PR TITLE
cmake: sort package in header

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
LGTM! 

But why do we need to sort both? Isn't `installed_packages` what gets printed?

**Comment by rbberger** [comment]
@junghans try out `lmp -h` ;-)

**Comment by akohlmey** [comment]
@junghans you are missing the point. this is about *styles* not packages.

**Comment by junghans** [comment]
@akohlmey, @rbberger clarified that to me, thanks!

**Comment by junghans** [comment]
Anyhow, ready to merge!

**Pull request merged**
