### PR TITLE
Doc pdf g clavier

### PR DESCRIPTION
**Pull request by Bibobu**
**Summary**

Review of the pdf between p400 and 672. I went a bit above p400 in order to start at the Tools section, might overlap with @rbberger work.

Some Comments:
- Some tables are ugly. In  the pdf, see for example `lammps_extract_global` in the C API part. Centering them would help maybe? This would require going through the whole library.cpp file. I don't know if this is necessary.
- There is a weird pdf formatting issue on p625 in the FORTRAN API format (see fix_external_set_energy_global subroutine). I did not find how to fix it.

In both cases the html version if fine. Nothing more catches my eye through simple visual inspection. (I did not go through  the details of all the error and warning message and trusted the text there and focused on the format.)

**Related Issue(s)**

Issue #4274

**Author(s)**

Germain Clavier (germain.clavier@unicaen.fr)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@Bibobu I will pull your branch into my pull request since I already have a bunch of additional changes in there. I've looked into the table issue and it seems it can be mostly addressed by setting explicit column widths.

The Fortran issue seem just a linewrap combined with missing text. Not something we're looking into now. But I'll have some library interface revisions pending and then I'll have to port them to Fortran, too, and that will be the time to review the docs again.

Here is a revised version of the PDF manual with your changes included (fresh of the CI server).
https://ci.lammps.org/job/dev/job/pull_requests/job/build_docs/10346/artifact/lammps/doc/Manual.pdf

**Comment by Bibobu** [comment]
Then I shall close the PR. Thanks.

**Comment by akohlmey** [comment]
> Then I shall close the PR. Thanks.

Technically, this is not needed. GitHub rechecks whether a PR has conflicts after every merge. If it detects that it has no more changes relative to the target branch or all commits are in the branch history, it will automatically close the PR when the other PR is merged.

**Comment by Bibobu** [comment]
Oh thanks again. I didn’t know that.

**Pull request closed without merging**
