### PR TITLE
USER-NC-DUMP package

### PR DESCRIPTION
**Pull request by akohlmey**
This PR incorporates the NetCDF based nc and nc/mpiio dump styles into LAMMPS as USER-NC-DUMP package. Settings for the NetCDF library are in lib/netcdf (and could be reused for other styles using NetCDF). The settings use the automatic configuration via the nc-config tool included in a typical netcdf install. It also autodetects whether nc/mpiio is included (through a define and ifdeffing the entire code).

This PR has been updated to the latest development code and also according to suggestions from Lars in the comments below. I've added the improved autodetect and made both NetCDF variants optional. I also added README with examples explaining how to manually configure NetCDF support. It is done in such a way, so that the same folder can be used by other features, that want to use NetCDF for portable file i/o.

### CODE REVIEW

**Comment by akohlmey** [comment]
@pastewka please review if there is any problem integrating your netcdf dump into LAMMPS like this, especially if the automatic detection of parallel netcdf and inclusion of dump style nc/mpiio works as intended. Thanks, Axel.

**Comment by pastewka** [comment]
Will look into this but may take a couple of day.

**Comment by pastewka** [comment]
Hi Axel,

I noticed the following issues:

- lib/netcdf/README is referred to in USER-NC-DUMP/README but is missing. Should I create one? What should it contain?
- nc-dump is not in PACKUSER variable of the top-level Makefile. Does it need to be?
- As far as I understand "nc-config --has-pnetcdf" checks if standard NetCDF has been compiled with parallel support on top of parallel-netcdf. (I have to admit I have never seen this option before.) dump nc/mpiio uses parallel-netcdf directly. Unfortunately, parallel-netcdf does not come with *-config file. The best way to check whether parallel netcdf exists is to check whether there is an executable "ncmpidump" somewhere in the path. Some systems (e.g. BlueGene) don't have standard NetCDF but just parallel NetCDF, so I would detect that as well.

My suggestion is to change Makefile.lammps:

```
netcdf_SYSINC =
netcdf_SYSLIB =
netcdf_SYSPATH =

ifneq ($(shell which nc-config),)

netcdf_SYSINC += -DLMP_HAS_NETCDF $(shell nc-config --cflags)
netcdf_SYSLIB += $(shell nc-config --libs)
netcdf_SYSPATH =

endif

ifneq ($(shell which ncmpidump),)

netcdf_SYSINC += -DLMP_HAS_PNETCDF -I$(shell which ncmpidump | sed 's,bin/ncmpidump,include,')
netcdf_SYSLIB += -L$(shell which ncmpidump | sed 's,bin/ncmpidump,lib,')
netcdf_SYSPATH +=

endif
```

(and also wrap dump_nc.cpp into and #ifdef LMP_HAS_NETCDF). Detection of parallel-netcdf include and library paths is a bit ugly but should work on most systems.

- Lars

**Comment by pastewka** [comment]
Sorry, small correction to Makefile.lammps:

```
netcdf_SYSINC =
netcdf_SYSLIB =
netcdf_SYSPATH =

ifneq ($(shell which nc-config),)

netcdf_SYSINC += -DLMP_HAS_NETCDF $(shell nc-config --cflags)
netcdf_SYSLIB += $(shell nc-config --libs)
netcdf_SYSPATH =

endif

ifneq ($(shell which ncmpidump),)

netcdf_SYSINC += -DLMP_HAS_PNETCDF -I$(shell which ncmpidump | sed 's,bin/ncmpidump,include,')
netcdf_SYSLIB += -L$(shell which ncmpidump | sed 's,bin/ncmpidump,lib,') -lpnetcdf
netcdf_SYSPATH +=

endif
```

**Comment by akohlmey** [comment]
@pastewka thanks for your comments and suggestions. i've updated the pull request accordingly.

**Comment by pastewka** [comment]
There is a small typo in Makefile.lammps in the line starting with `PNETCDF_PATH=`: `($` -> `$(`

Also bottom row of `netcdf_* =` instructions should be `+=` not `=`, i.e. `netcdf_SYSINC += -DLMP_HAS_PNETCDF -I$(PNETCDF_PATH)/include`, otherwise NetCDF module is not compiled if parallel NetCDF is present. (Now this could be a feature, but I would rather detect both independently.)

**Comment by pastewka** [comment]
I can confirm this works on a BlueGene/Q and standard Intel cluster. Please merge to master. I'll deprecate the repository at [https://github.com/Atomistica/lammps-netcdf](https://github.com/Atomistica/lammps-netcdf) and point to this as the main development branch.

**Pull request merged**
