### PR TITLE
Address minor issues indicated by compiler warnings and static code analysis

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request fixes a few minor issues (dead code, redundant computation, inconsistent of array sizes on stack)  in recent changes that were indicated by compiler warnings and static code analysis with coverity scan.

**Related Issue(s)**

The issues were introduced by PRs #2514, #2557, and #2558

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Review by athomps — CHANGES_REQUESTED** [review]
Changes to pair_tersoff.cpp are incorrect for SHIFT_FLAG.  I agree that there is redundant computation here, but it is not simple to remove it.

**Comment by akohlmey** [comment]
> Changes to pair_tersoff.cpp are incorrect for SHIFT_FLAG. I agree that there is redundant computation here, but it is not simple to remove it.

yup. I see this from the unit tests failing. will have to think about it some more.

**Comment by athomps** [comment]
I took a look at computing and saving all pair quantities at the start and reusing, which would be fairly straightforward, except that for ik contribution to threebody, ik cutoff is typed on ijk triplet.*  After confirming that this is a real requirement, not just laziness on my part, I quit.  One way to do it would be to store pair quantities for all pairs within maximal cutoff i.e. max(R_I1J,...,R_INJ), where I, J are types/elements of atom i and j, lying in range (1,N).

*In practice usually typed on ik pair, but sometimes ij pair

**Comment by akohlmey** [comment]
> > Changes to pair_tersoff.cpp are incorrect for SHIFT_FLAG. I agree that there is redundant computation here, but it is not simple to remove it.
> 
> yup. I see this from the unit tests failing. will have to think about it some more.

at the very least I can remove the dead code from the twobody interaction, sprinkle in a few more consts and move the "shift_flag" variable into templated arguments in the USER-OMP versions of tersoff/mod and tersoff/mod/c.

My main mistake was to overlook the square root. that'll much cost more than recomputing rsq anyway.

**Comment by akohlmey** [comment]
@athomps unit tests are passing again.

**Review by athomps — APPROVED** [review]

**Pull request merged**
