### PR TITLE
USER-EES package

### PR DESCRIPTION
**Pull request by aershadinia**
Source files, Documentations and some examples of "fix wall/ees" and "fix wall/region/ees" are added. 
These code is meant to calculate the interaction between ellipsoidal particles and a semi-finite wall introduced by Babadi and Ejtehadi.

### CODE REVIEW

**Comment by akohlmey** [comment]
I haven't been able to test the code, but i have one question and one request.

do the fixes check, whether all particles in the fix group are actual ellipsoids and have the bonus field allocated?

these files don't look as if they warrant a whole package. better to add them to the USER-MISC package and move/adjust examples and documentation accordingly.

**Comment by akohlmey** [comment]
there has been no activity here for almost 3 months. thus i am closing this for inactivity. please file a new pull request, if you are still interested to contribute your code.

**Comment by aershadinia** [comment]
Yes. I was bz during this semester. I am gonna do it just next week after
semester ends.

**Comment by aershadinia** [comment]
Hi. I moved my code from src/USER-EES to src/MISC directory. I am going to add another pull req.

**Pull request closed without merging**
