### PR TITLE
Require C++11 and CMake 3.10

### LINKED ISSUE #1659: C++11 in LAMMPS
## Summary

There is an ongoing discussion among the developers of LAMMPS about when the right time is to allow C++11 compliant code in the core of LAMMPS. Currently it is only required by some packages such as KOKKOS. But we are increasingly seeing code that needs to be changed or rejected because of the C++98 requirement.

Many compilers already default to C++14, so I would argue that by now it should be safe to move forward in allowing C++11 code in all of LAMMPS. One argument against this is usually that  there are sites with older OS versions/GCC versions that enforce the use of the system compiler. It would be beneficial to collect which supercomputing sites / clusters fall into this category and what their EOL (end-of-life) is.

If you have any comments, ideas or feedback about this topic please comment below.

## Proposal to assess impact
After the last LAMMPS workshop in Albuquerque (August 2019) the following was dicussed as a possible test for seeing the impact to the user base. We could include a small piece of code that will not change the behavior, but print out an error if a non-C++11 compliant compiler is used.  Users that run into this error can easily disable it by defining `LAMMPS_CXX98` or switching to a C++11 compliant compiler. They should be encouraged to report here or at the mailing list so we can collect their feedback.
```
#ifndef LAMMPS_CXX98
#if __cplusplus <= 199711L
  #error LAMMPS is planning to transition to C++11. Do disable this error please use a C++11 compliant compiler or define LAMMPS_CXX98 in your makefile
#endif
#endif
```

## Target Platforms
| OS |  g++ Version | g++ default | clang++ Version | clang++ default |
| --- | ---- | --- | --- | ---|
| Ubuntu 18.04 LTS   | 7.4.0 | C++14    | 6.0.0 | C++14 |
| Ubuntu 19.04   | 9.2.1 | C++14    | 8.0.0 | C++14 |
| CentOS 7 (EL7)    | 4.8.5 | **C++98** (C++11 supported with `-std=c++11`)   | 3.4.2 | **C++98** (C++11 supported with `-std=c++11`) |
| CentOS 8 (EL8)    | ? | ? | ? | ? |
| Fedora 29     | 8.3.1 | C++14    | 7.0.1 | C++14 |
| Fedora 30     | 9.2.1 | C++14    | 8.0.0 | C++14 |
| Fedora 31     | 9.2.1 | C++14    | 9.0.0 | C++14 |

### Testing default C++ compiler standard
```
g++ -dM -E -x c++  /dev/null | grep -F __cplusplus
```

## References:
 - https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B11_features

### LINKED ISSUE #1729: [Feature Request] Update minimum CMake version required to 3.10
**Summary**

After the next stable release we should set the minimum CMake version require to 3.10.

**Detailed Description**

Compatibility with CMake 2.8.12 causes increasing difficulties and requires hacks and workaround. See the discussion for pull request #1723 for the reasoning why version 3.10 was picked and why the negative impact should be rather limited.

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This adds tests and documents the new requirements for C++ compiler and CMake.

**Related Issues**

Closes #1659 
Closes #1729 

**Author(s)**

Axel Kohlmeyer (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This deliberately breaks compatibility with old compilers and CMake versions

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by junghans** [comment]
With cmake-3.10 we can also get rid of `LAMMPS_LINK_LIBS` and `LMP_SOURCES` as one can simply create the library/executable target at the beginning of the CMake file with e.g. `add_excutable(lmp)` (no source files) and then add source files with `target_sources(lmp foo.cpp)`, similar for linking with `target_link_libraries(lmp foo::foo)`.

**Comment by akohlmey** [comment]
> With cmake-3.10 we can also get rid of `LAMMPS_LINK_LIBS` and `LMP_SOURCES` as one can simply create the library/executable target at the beginning of the CMake file with e.g. `add_excutable(lmp)` (no source files) and then add source files with `target_sources(lmp foo.cpp)`, similar for linking with `target_link_libraries(lmp foo::foo)`.

Feel free to submit a pull request with those changes. Either to this branch or to master.

**Comment by junghans** [comment]
`Modules/Testing.cmake` makes use of a cmake-3.11 feature, so we might want make that the minimum.

**Comment by akohlmey** [comment]
> `Modules/Testing.cmake` makes use of a cmake-3.11 feature, so we might want make that the minimum.

No. #1723 has the reasoning why 3.10 was chosen. lammps-testing is still an ad hoc package and not something that we should encourage non-expert users to use. I think including it in the CMake configuration at this stage is not a good idea.

**Pull request merged**
