### PR TITLE
Port Recent SNAP changes to Kokkos

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Port the changes to the SNAP potential in #1507 to Kokkos. Also removed redundant computation of `ulist` in `compute_duarray()`. Gives about 1.6x speedup on a V100 GPU. 

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@athomps they are still used as temporary variables in `compute_uarray()` but we could just get rid of them.

**Comment by athomps** [comment]
Yes, I think it would be good to get rid of them entirely.

**Comment by stanmoore1** [comment]
@athomps OK will do.

**Comment by stanmoore1** [comment]
@athomps I got rid of `ulist_r` and `ulist_i` entirely.

**Pull request merged**
