### PR TITLE
Iss1572: Fix error handling, clarify data requirements for fix bocs input

### PR DESCRIPTION
**Pull request by eagunn**
**Summary**

Changed the code in the read_F_table function to conform to the "expected behavior" description in #1572. Adopted a best-of-both-worlds approach, though, and processed the whole input file all the way through, emitting a message for each problem found, before issuing a final error message to stop processing. 

**Related Issues**

This change makes a tiny down-payment on #1109, plugging the smallest of the memory leaks by using a local variable rather than calloc'ing for an error message string.

**Author(s)**

E. Anne Gunn, Sheridan College (NWCCD)
agunn@sherprog.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Bad volume/pressure-correction data lines now generate error messages while the file is processed rather than causing problems/failures at some point downstream. Behavior should be unchanged for truly valid input files.

**Implementation Notes**

I've added a folder under the source code for this user fix that contains a sample input file and some samples of error data. I'm hoping this is allowed. It increases the source tree by a certain number of files but gives the core developers for this feature and others a way to communicate about expected and new behavior.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

New error handling behavior can be observed using lmp input file: 
src/USER-BOCS/tests/cubic_spline_file_set/cgheptane.badFvData.lmp
and the data file it points to:
src/USER-BOCS/tests/cubic_spline_file_set/delta_Fv_badbad.dat

### CODE REVIEW

**Comment by eagunn** [comment]
I believe this pull request should be reviewed by @mdelyser before it is merged.

**Comment by mdelyser** [comment]
I looked through the changes in the code and documentation made by @eagunn and have no problem with them being committed.

**Comment by akohlmey** [comment]
@eagunn please do not put test inputs into the examples folder. we do have a lammps-testing project which is still in its infancy and will likely get more attention after the workshop in mid-august.

**Comment by rbberger** [comment]
@eagunn having these test cases in the `src` folder is not typical. Instead, I propose you create a PR for [lammps-testing](https://github.com/lammps/lammps-testing). Please create a folder `tests/packages/USER-BOCS` and add a folder per test case. The naming convention for inputs is `in.testA`, `in.testB`, `in.testC`, etc. See https://github.com/lammps/lammps-testing/tree/master/tests/examples/indent as inspiration.

We're currently not testing for error messages and these tests will not be part of any automatic regression test, but I generally like the idea and it's something we can add in the future. So this would be the right place for these files.

As for this PR, if you can, please rebase this branch to remove the unnecessary commits and clean up the history.

**Comment by eagunn** [comment]
@akohlmey @rbberger Messages received. 

I'll pull the test code out of this PR and prep a separate PR for the test project when I get a chance. And, yes, I can/will rebase to simplify commit history. 

Thanks for taking a look.

**Comment by eagunn** [comment]
I'm closing this PR in favor of the simpler #1603 which I think resolves the objections raised above.

**Pull request closed without merging**
