### PR TITLE
Thermo_modify format ranges

### PR DESCRIPTION
**Pull request by hammondkd**
**Summary**

I made minor modifications to `thermo.cpp` so that the ``thermo_modify format`` command now accepts ranges. For example,
```
thermo_style custom step temp press etotal c_1[1*20]
thermo_modify format 5* "%5f"
```
will output the first 20 elements of compute ID `1` (this is existing functionality), but the "5*" (equivalent in this case to "5*24") format ID in ``thermo_modify`` will now cause fields 5 through 24 to have "%8f" as their format specifier. This makes it easier to format multiple very similar columns without reformatting all floats that way: previously, the user would have to specify either all floats at once, then override the ones that the user wanted to be different, or specify the 20 that the user wanted to be different in different "format" lines.

**Author(s)**

Karl Hammmond, University of Missouri
hammondkd at missouri.edu
@hammondkd

**Licensing**

By submitting this pull request, I agree that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This should not affect backward compatibility (and I performed a few checks to ensure that it does not).

**Implementation Notes**

This existing utility functions to check formatting (is_integer and is_type). The is_type function currently does not check whether the range given constitutes a valid type, it just checks that it's a valid integer range specifier; if this functionality ever changes, this routine would need to be modified.

This has been checked that existing functionality isn't disrupted (as far as I can tell). I did not write a separate unit test to check this new feature, but there isn't one dedicated to ``thermo_modify format`` that I see anyway (and if there is one, I'll add a quick test for this feature). There *are* documentation updates included.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by hammondkd** [comment]
Just to make sure this gets documented somewhere: my original implementation used `not`, `and`, and `or` in thermo.cpp, but the Windows build didn't work. I changed them to `!`, `&&`, and `||` instead and it worked. I'm pretty sure that's not supposed to happen (i.e., the C++ standard calls them synonyms, or so I thought), but there it is all the same.

**Review by sjplimp — APPROVED** [review]

**Comment by akohlmey** [comment]
@hammondkd support for negative ranges (`-2*6` *not* `-2*-6`) could be added with something like the following:
```
      } else if (utils::strmatch(arg[iarg + 1], "^-?\\d*\\*\\d*$")) {
        int nlo, nhi, neg=0;
        if (arg[iarg][0] == '-') neg = 1;
        utils::bounds(FLERR, arg[iarg + 1] + neg, 1, nfield_initial, nlo, nhi, error);
        if (neg) {
          nlo = -nlo;
          nhi = -nhi;
        }
        int icol = -1;
        [...]
```

**Comment by sjplimp** [comment]
> @hammondkd support for negative ranges (`-2*6` _not_ `-2*-6`) could be added with something like the following:
>       } else if (utils::strmatch(arg[iarg + 1], "^-?\\d*\\*\\d*$")) {
>         int nlo, nhi, neg=0;
>         if (arg[iarg][0] == '-') neg = 1;
>         utils::bounds(FLERR, arg[iarg + 1] + neg, 1, nfield_initial, nlo, nhi, error);
>         if (neg) {
>           nlo = -nlo;
>           nhi = -nhi;
>         }
>         int icol = -1;
>         [...]

Did this get added to the merge?  I'm hoping not.

**Comment by akohlmey** [comment]
> Did this get added to the merge? I'm hoping not.

no.

**Pull request merged**
