### PR TITLE
cmake: fix linkage against external latte

### PR DESCRIPTION
**Pull request by junghans**
**Summary**

This feature got broken in cmake refactor.

**Related Issues**

#1956 

**Author(s)**

@junghans 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

**Implementation Notes**

CMake only

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

Found in https://github.com/lanl/LATTE/pull/113

### CODE REVIEW

**Comment by akohlmey** [comment]
FYI all those comments in the pull request template still show up in the slack messages

**Comment by junghans** [comment]
But I saved 2 mins not having to delete them ;-)

**Comment by junghans** [comment]
Retrigger jenkins

**Comment by akohlmey** [comment]
deleted by accident, sorry. @junghans it would be better if you submit pull requests with branches from your own LAMMPS fork instead of creating a branch in the lammps repo. That way the chance of this happening again would be reduced to zero. Branches in the LAMMPS repo are primarily intended to be used for features that multiple core developers collaborate on.

**Comment by junghans** [comment]
Sorry, that was by accident, just remove my write permission that sound help.

**Comment by akohlmey** [comment]
> Sorry, that was by accident, just remove my write permission that sound help.

I don't really want to do that, since It is too convenient to have this feature in case there is a need to work on a branch with multiple people before there is a pull request. It happened to me a few times, too, but after watching it for a while, it became a habit to push feature branches into the lammps repo. I've helped myself by renaming the remotes, so there is no more "origin".

**Comment by junghans** [comment]
I use the web interface for tiny changes that doesn't create forks. Anyhow will try to be more careful in the future.

Can you merge this PR into #2023?

**Comment by akohlmey** [comment]
> I use the web interface for tiny changes that doesn't create forks. Anyhow will try to be more careful in the future.
> 
> Can you merge this PR into #2023?

sure. #2027, too?

**Comment by junghans** [comment]
> > I use the web interface for tiny changes that doesn't create forks. Anyhow will try to be more careful in the future.
> > Can you merge this PR into #2023?
> 
> sure. #2027, too?

Let's have one of the plumed developers review it first.

**Pull request closed without merging**
