### PR TITLE
Standardize fix contributions to energy and virial, remove THERMO_ENERGY mask

### LINKED ISSUE #2528: Review use of THERMO_ENERGY in Fix::setmask() and methods of computing of the conserved quantity in MD
There are some inconsistencies and unusual behavior due to choices made a long time ago, that need to be reviewed and possibly some changes made.  For details, please see the discussion on PR #2515 

Please also note the inconsistency discussed in Issue #2537 

Further discussion results and proposed changes should be documented here.

### LINKED ISSUE #2537: [BUG]  fix modify energy has no effect on fix orient/eco
**Summary**

Grain growth can be studied by modifying the per atom potential energy of differently oriented grains using the `fix orient/eco`. The energy change cannot be include in the thermodynamic output as expected from the `fix_modify energy` as described in the documentation.

**LAMMPS Version and Platform**

- LAMMPS version 29 Oct 2020
- Ubuntu 18.04
- serial as well as mpi versions have been tried
- compiled including the MISC package

**Expected Behavior**

The `fix orient/eco` adds or substracts potential energy to crystalline grains provided the cyrstallographic orientation. This can initiate grain growth based on a gradient in potential energy if differently oriented grains are present in a simulation cell. Per default, the energy contribution of the fix should not be included in the potential energy that is output to thermo or per-atom potential energy. According to the documentation this behavior can be changed using the `fix_modify energy`. The new potential energy should then be the sum of the normal pair potential contribution and the contribution from the `fix orient/eco`.

We have applied this fix to simple examples such as Cu (see files attached) but also systems that show less mobile grain boundaries. In the latter case larger driving forces can be applied and the below described problem becomes more obvious. To make statements about the potential energy we have used careful post-processing that includes temporal and spatial averaging of per atom energies to track the excess provided by the fix.

**Actual Behavior**

The grains are properly recognized by the fix (can be seen by the fix orient eco output) and grain growth works (see dump). However, the per-atom potential energy does not change if the `fix_modify energy` is set to either yes or no.

**Steps to Reproduce**

The files attached can be run with LAMMPS and produce the described output. Comment/uncomment the line regarding the `fix_modify energy` to observe the problem. Per atom energies can be temperorally and spatially averaged for the grains using some post-processing tool. We used Ovito (ovito.org)

**Further Information, Files, and Links**

[Cu_u6.txt](https://github.com/lammps/lammps/files/5725505/Cu_u6.txt)
[equilibrated_300K.txt](https://github.com/lammps/lammps/files/5725510/equilibrated_300K.txt)
[grain.txt](https://github.com/lammps/lammps/files/5725521/grain.txt)
[input.txt](https://github.com/lammps/lammps/files/5725522/input.txt)

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

As title says, make fix contributions to energy/virial, both global and peratom more standard.
Remove THERMO_ENERGY mask, replace with energy_global_flag or ecouple_flag, depending on whether
the fix adds potential energy or accumulates thermostatting reservoir energy.  Also added energy_peratom_flag and virial_global_flag and virial_peratom_flag.

**Related Issue(s)**

Should address and thus closes #2537 and also closes #2528

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by sjplimp** [comment]
I think I've made the changes needed in KOKKOS and OMP packages.  Want to see if all regression tests pass.  Still TODO: make fix documentation consistent with how fix_modify energy/virial options are set.  Also add some programmer documention for this change to the manual.

**Review by athomps — APPROVED** [review]
Looks a lot cleaner.

**Comment by akohlmey** [comment]
> I think I've made the changes needed in KOKKOS and OMP packages. Want to see if all regression tests pass. Still TODO: make fix documentation consistent with how fix_modify energy/virial options are set. Also add some programmer documention for this change to the manual.

Compiling KOKKOS is still failing with:
```
CMakeFiles/lammps.dir/mnt/lammps/workspace/dev/pull_requests/compilation_tests/lammps/src/KOKKOS/modify_kokkos.cpp.o
/mnt/lammps/workspace/dev/pull_requests/compilation_tests/lammps/src/KOKKOS/modify_kokkos.cpp(361): error: identifier "n_thermo_energy" is undefined
    for (int i = 0; i < n_thermo_energy; i++) {
                        ^

/mnt/lammps/workspace/dev/pull_requests/compilation_tests/lammps/src/KOKKOS/modify_kokkos.cpp(362): error: identifier "list_thermo_energy" is undefined
      atomKK->sync(fix[list_thermo_energy[i]]->execution_space,
                       ^
```

**Comment by sjplimp** [comment]
@stanmoore1 I removed one function from modify_kokkos.cpp and added 3 others.  The first 2 are hopefully correct, but you should check.  But the energy_atom() function is a placeholder with the CPU code commented out.

**Comment by stanmoore1** [comment]
@sjplimp thanks I'll take a look.

**Comment by julient31** [comment]
Hey Steve @sjplimp !
I looked at the changes in fix langevin/spin and fix precession/spin and that looks fine to me. Actually it looks much cleaner ^^. 
Thanks a lot!

**Comment by sjplimp** [comment]
@akohlmey In going thru the doc page and code settings, one thing I noticed is that fix colvars and fix plumed differ in their default setting for fix_modify energy yes/no.  Plumed includes its energy contribution, Colvars does not (by default).  We can switch that to be the same if you think it makes better sense.  The list of fixes that set the flag to yes by default are: external, latte, cmap, client/md, plumed.

**Comment by sjplimp** [comment]
@julient31 thanks for checking

**Comment by giacomofiorin** [comment]
> @akohlmey In going thru the doc page and code settings, one thing I noticed is that fix colvars and fix plumed differ in their default setting for fix_modify energy yes/no. Plumed includes its energy contribution, Colvars does not (by default). We can switch that to be the same if you think it makes better sense. The list of fixes that set the flag to yes by default are: external, latte, cmap, client/md, plumed.

@sjplimp That is okay. I was planning on addressing that in a separate PR, possibly also enabling virial contributions from Colvars. This PR is making things a bit clearer.

**Comment by sjplimp** [comment]
Removed the work-in-progress label, since I've now finished all code changes and doc page updates for this PR. Included a new subsection of the Developer_notes.rst page.  It would be good if @akohlmey looked at it.  Also need some input from @stanmoore1 if there any further Kokkos changes needed.  Otherwise I think it is ready for full regression testing, and then release.

**Comment by akohlmey** [comment]
@sjplimp there are still issues compiling everything.
```
lammps/src/USER-QTB/fix_qbmsst.cpp:1067:24: error: ‘econserve’ was not declared in this scope
 1067 |   etot = epot + ekin + econserve;
```

**Comment by akohlmey** [comment]
@sjplimp this now compiles for me.
@stanmoore1 I've had to make some changes to KOKKOS to prevent compile and link failures due to incorrect scoping of added/modified functions. please check. It also looks as if it may still need some work in those parts.

**Comment by akohlmey** [comment]
updated to current master and addressed whitespace issues

**Comment by akohlmey** [comment]
it looks like run and regression tests are failing because their inputs contain fix_modify energy yes and this now fails for some fixes.

**Comment by stanmoore1** [comment]
>@stanmoore1 I've had to make some changes to KOKKOS to prevent compile and link failures due to incorrect scoping of added/modified functions. please check. It also looks as if it may still need some work in those parts.

Yes I will take a look.

**Comment by stanmoore1** [comment]
I'm looking at the Kokkos issues now. @sjplimp @akohlmey there are some merge conflicts, can you take a look at those?

**Comment by akohlmey** [comment]
> I'm looking at the Kokkos issues now. @sjplimp @akohlmey there are some merge conflicts, can you take a look at those?

will sort this out ASAP. must be due to some cleanups to address some (mostly unimportant) issues reported by static code analysis. same as with compiler warnings, you first have to do some invasive changes to silence all the unimportant warnings so you can better see the ones that matter.

**Comment by stanmoore1** [comment]
When I try to see which Jenkins tests failed, I get:

```
Page not found (404)
Jenkins could not find the page you were looking for. Check the URL for errors or press the back button.
```

Is that just because it has been too long and the test results were deleted, or a broken link?

**Comment by akohlmey** [comment]
> When I try to see which Jenkins tests failed, I get:
> 
> ```
> Page not found (404)
> Jenkins could not find the page you were looking for. Check the URL for errors or press the back button.
> ```
> 
> Is that just because it has been too long and the test results were deleted, or a broken link?

I don't have a problem. Which tests in particular are you referring to?
The last failed test runs were: https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Frun_tests/detail/run_tests/163/pipeline
and 
https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Fregression_tests/detail/regression_tests/145/pipeline

You can click on the sub-runs and then on "triggered builds" and then on "Tests" with the number of failed tests.
Those are all inputs from the lammps-testing repo, which means they likely need to be adapted to follow changes in the input syntax and conventions.

As for changes needed for KOKKOS, I suggest you look at what is changed in the KOKKOS package code.
Now that I've updated the branch to current master, it should be easier to compare (against master).

**Comment by stanmoore1** [comment]
Yeah the link works now, not sure what changed. I'm seeing some segfaults in the regression tests, even without Kokkos.

**Comment by akohlmey** [comment]
> Yeah the link works now, not sure what changed. I'm seeing some segfaults in the regression tests, even without Kokkos.

am retriggering those to get up-to-date output after master was merged.

**Comment by stanmoore1** [comment]
I reviewed the Kokkos changes. There are 3 tests failing, but I'm pretty sure it isn't related to Kokkos.

**Comment by akohlmey** [comment]
> I reviewed the Kokkos changes. There are 3 tests failing, but I'm pretty sure it isn't related to Kokkos.

Found a bug in compute stress/atom. That might be the culprit.

**Comment by stanmoore1** [comment]
>Found a bug in compute stress/atom. That might be the culprit.

OK I'm running the regression tests again.

**Comment by akohlmey** [comment]
> > Found a bug in compute stress/atom. That might be the culprit.
> 
> OK I'm running the regression tests again.

please also note that I had to modify the inputs and reset three regression tests based on example inputs: hugoniostat, msst, and threebody.

**Comment by stanmoore1** [comment]
Good to know, thanks.

**Comment by akohlmey** [comment]
> Good to know, thanks.

Regression tests on ci.lammps.org now pass with the 3 updated inputs and gold standard logs. This looks ready to go in. There was an extra test run triggered by accident. So I'll have to wait another half hour before I can merge and then update PR #2586 for some final checks over night.

**Review by akohlmey — APPROVED** [review]

**Comment by stanmoore1** [comment]
@akohlmey Looks like the `examples/USER/qtb/alpha_quartz_qbmsst/in.alpha_quartz_qbmsst` example is failing:

```
ERROR: Illegal fix_modify command (../fix.cpp:155)
test alpha_quartz_qbmsst FAILED
```

Maybe we need to grep the examples?

**Comment by akohlmey** [comment]
> @akohlmey Looks like the `examples/USER/qtb/alpha_quartz_qbmsst/in.alpha_quartz_qbmsst` example is failing:
> 
> ```
> ERROR: Illegal fix_modify command (../fix.cpp:155)
> test alpha_quartz_qbmsst FAILED
> ```
> 
> Maybe we need to grep the examples?

Doing it right now. Found some other, unrelated inconsistencies while reviewing PR #2590, so I already have a branch collecting such kinds of changes.

**Pull request merged**
