### PR TITLE
Kokkos EAM tweaks for V100

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

A few code tweaks to give better performance of Kokkos EAM on V100 GPUs.

**Related Issue(s)**

None.

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by rbberger** [comment]
@stanmoore1 I'll soon start merging new things into master. Is there anything else I should be aware of coming this way?

**Comment by stanmoore1** [comment]
I have one more tweak from @weinbe2, but today is super busy for me, so should get it in the next few days.

**Comment by rbberger** [comment]
@stanmoore1 let me know if we can merge this into the next patch release (end of November) or you want to keep it open longer.

**Comment by stanmoore1** [comment]
@rbberger I'm putting this PR and #2497 through Kokkos regression testing, then it will be ready to merge.

**Comment by stanmoore1** [comment]
Kokkos regression tests passed, ready for merge.

**Review by rbberger — APPROVED** [review]

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
