### PR TITLE
Refactoring of AtomVec class

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

Refactoring of atom styles with goal of making it as simple as possible for a  developer
to add a new atom style.  An added bonus is there should now be zero overhead for using
a hybrid atom style.  So creating new styles that just augment existing styles is simple
and has no performance impact.

**Related Issues**

N/A

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Styles that have been refactored should work identically as before.

**Implementation Notes**

The basic idea is that the AtomVec child classes (atom style classes) only specify
lists of peratom variables that need to be communicated in various categories.
The parent AtomVec class now loops over those lists and packs/unpacks them
into communication buffers in a more generic manner than previously.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
So far all the atom styles in src and the standard packages have been refactored.
With the exception of those that have Bonus data structs (including body), and
hybrid, and the Kokkos atom styles.  The USER package atom styles are also
not yet refactored.

But this is enough for other developers to view/test the refactored styles to see what
you think.  Some simple benchmark testing did not show significant changes in 
performance.  More benchmarking should be done.  Note that only
the methods that are invoked within timestepping are important for performance.
I.e. (un)pack_comm, (un)pack_reverse, (un)pack_border, (un)pack_exchange.

@stanmoore1 Will this work for Kokkos?  Will it produce more kernel launches
due to each extra per-atom vector/array being packed in its own loop over atoms?
If so, maybe the Kokkos version of a method like pack_comm() should still
use one loop over atoms and embed the loop over extra fields inside it.

@ndtrung81 What does this refactoring mean for the GPU package?

**Comment by sjplimp** [comment]
Refactored the atom styles with bonus data, still need to test them.  Also a few USER package
atom styles.  Several USER ones still to go.  Style hybrid is the biggest remaining one.

**Comment by ndtrung81** [comment]
@sjplimp The refactoring do not affect the GPU package up to this point.

**Comment by Adrian-Diaz** [comment]
Took a quick look, was wondering if it would still work if the atomvec children were still allowed to inherit the parent routines in order to keep existing atomvecs operational until changed. Was also wondering how one could perform an operation on the data being communicated beforehand such as adding dx for pbc. Small thing, noticed the comment heading for init_method in atomvec.cpp was a copy of the following destructor's own comment heading.

**Comment by sjplimp** [comment]
@ndtrung81 Thanks - so you are saying the GPU package does not use any of the AtomVec methods, e.g. for comm during timestepping: forward, reverse, border, exchange?

**Comment by sjplimp** [comment]
@Adrian-Diaz All the existing child styles will be replaced before this is released.  The parent AtomVec::pack_comm() method now does the PBC operations.  There are also some hook methods added for create_atom, data_atom, etc to let a child class initialize per-atom fields in non-standard ways.  Re: comment on init(), good catch -  will change that.  Thanks for looking this over.

**Comment by ndtrung81** [comment]
@sjplimp Right, the /gpu pair styles and pppm/gpu do not use any AtomVec methods for comm.

**Comment by sjplimp** [comment]
@akohlmey This is nearly done.  Still need to work on USER-AWPMD atom style and the replicate command.  I've done regression testing on nearly all the other atom styles.

**Comment by sjplimp** [comment]
This is done, except for KOKKOS and changing some doc pages.  Performance
seems equivalent to previous version.

@akohlmey @athomps @rbberger @stanmoore1 If you can take a look and see
if you like it.  It should reduce the complexity of atom styles for developers quite a bit.

**Comment by stanmoore1** [comment]
My plan is to get the KOKKOS package to compile/run using the old atom-vec format as a first step. Porting the KOKKOS package to the new atom-vec format will happen at a later time.

**Comment by sjplimp** [comment]
@rbberger I think I fixed the bug with reading velocities from the data file in the python example.  Nothing to do with python, just with the format of how the Velocities section of the data file was written earlier in the test script.

**Comment by rbberger** [comment]
@sjplimp yes, both test cases are now working.

**Comment by sjplimp** [comment]
@akohlmey To resolve these conflicts should I do a local merge of current master into
this PR branch?  Then push the result back to GHub?
This push was the new doc pages.  So reading them would be a good start
for you to see what the changes are.  I think it is dramatically simpler now
for someone to write a new atom style.

These are the only undone tasks I think are left on this PR.  For some
of them I likely need to be back in the office:

a) check that this works with fix property/atom q or mol (custom is OK)
b) spin style: needed to rearrange the atom lines in the data file, so that
     all 4 values stored in sp[4] are consecutive.  Julian T may have to change
     his data files
c) Noticed the AWPMD Install.py file is not creating a Makefile.lammps.
    @akohlmey can you check this - not sure if this is also an issue with CMake
d) 2 changes I want to do to the src code in USER-SPH
     change variable "e" (too generic) to "e_sph", and rename atom_style mess
     (also too generic) to atom_style sph
e) when running tests on every atom style, I needed to make a few changes
     to scripts in the example dirs - I need to include that in the PR

**Comment by stanmoore1** [comment]
I took a look at this for Kokkos. The `atom_vec_hybrid_kokkos` style needs some work because many of the "hybrid" methods were deleted.

**Comment by sjplimp** [comment]
@akohlmey I have now done everthing I mentioned in my March 18 comment above.  All that is left is @stanmoore1  to work on the Kokkos issue (talked to him today).  And any further regression testing you want to do on example scripts, etc.  Otherwise ready to release.

**Comment by stanmoore1** [comment]
Kokkos package compiles, starting regression tests now.

**Comment by stanmoore1** [comment]
@sjplimp I'm seeing a compile error:

```
16:01:20 ../atom_vec_meso.cpp: In constructor ‘LAMMPS_NS::AtomVecMeso::AtomVecMeso(LAMMPS_NS::LAMMPS*)’:
16:01:20 ../atom_vec_meso.cpp:45:9: error: ‘class LAMMPS_NS::Atom’ has no member named ‘e_flag’; did you mean ‘q_flag’?
16:01:20    atom->e_flag = 1;
16:01:20          ^~~~~~
16:01:20 ../atom_vec_meso.cpp: In member function ‘virtual void LAMMPS_NS::AtomVecMeso::grow(int)’:
16:01:20 ../atom_vec_meso.cpp:75:26: error: ‘class LAMMPS_NS::Atom’ has no member named ‘e’
16:01:20    e = memory->grow(atom->e, nmax, "atom:e");
16:01:20                           ^
16:01:20 ../atom_vec_meso.cpp:76:27: error: ‘class LAMMPS_NS::Atom’ has no member named ‘de’
16:01:20    de = memory->grow(atom->de, nmax*comm->nthreads, "atom:de");
16:01:20                            ^~
16:01:20 ../atom_vec_meso.cpp: In member function ‘void LAMMPS_NS::AtomVecMeso::grow_reset()’:
16:01:20 ../atom_vec_meso.cpp:99:13: error: ‘class LAMMPS_NS::Atom’ has no member named ‘e’
16:01:20    e = atom->e;
16:01:20              ^
16:01:20 ../atom_vec_meso.cpp:100:14: error: ‘class LAMMPS_NS::Atom’ has no member named ‘de’
16:01:20    de = atom->de;
16:01:20               ^~
```

**Comment by sjplimp** [comment]
@stanmoore1 Is that file in src/USER-SPH?  If so, it no longer exists.
It was re-named atom_vec_sph.cpp and e and de were renamed to espy and de_sph.
@akohlmey This reminds me I do still need to make some edits to the USER-SPH
examples input scripts to reflect this.

**Comment by stanmoore1** [comment]
OK thanks, I'll purge my build.

**Comment by akohlmey** [comment]
> @stanmoore1 Is that file in src/USER-SPH? If so, it no longer exists.
> It was re-named atom_vec_sph.cpp and e and de were renamed to espy and de_sph.
> @akohlmey This reminds me I do still need to make some edits to the USER-SPH
> examples input scripts to reflect this.

@sjplimp if you renamed/moved files, you need to add them to `src/Purge.list` and also update `src/.gitignore`. Been a while since we did any of that, I guess.

**Comment by stanmoore1** [comment]
I'm seeing 1 test for vanilla LAMMPS fail, but it is an old test no longer in the examples so I'm going to update it and see if it still fails. Also several Kokkos tests failing, looks like it is related to charge systems, will need to dig deeper.

**Comment by stanmoore1** [comment]
@sjplimp I'm seeing a segfault in both of the inputs in `examples/USER/lb/polymer`:

```
#1  0x00000000005516c9 in LAMMPS_NS::AtomVecHybrid::process_args(int, char**)
    () at ../atom_vec_hybrid.cpp:217
#2  0x000000000052e7df in LAMMPS_NS::Atom::create_avec(char const*, int, char**, int) () at ../atom.cpp:701
#3  0x000000000040bc4e in LAMMPS_NS::Input::atom_style() ()
    at ../input.cpp:1421
#4  0x0000000000408915 in LAMMPS_NS::Input::execute_command() ()
    at ../input.cpp:801
#5  0x0000000000406919 in LAMMPS_NS::Input::file() () at ../input.cpp:229
#6  0x00000000004050f4 in main ()
```

**Comment by stanmoore1** [comment]
Here is Valgrind:

```
==1914== Invalid read of size 1
==1914==    at 0x4A0A231: strstr (mc_replace_strmem.c:1367)
==1914==    by 0x5516C8: LAMMPS_NS::AtomVecHybrid::process_args(int, char**) (atom_vec_hybrid.cpp:217)
==1914==    by 0x52E7DE: LAMMPS_NS::Atom::create_avec(char const*, int, char**, int) (atom.cpp:701)
==1914==    by 0x40BC4D: LAMMPS_NS::Input::atom_style() (input.cpp:1421)
==1914==    by 0x408914: LAMMPS_NS::Input::execute_command() (input.cpp:801)
==1914==    by 0x406918: LAMMPS_NS::Input::file() (input.cpp:229)
==1914==    by 0x4050F3: main (main.cpp:65)
==1914==  Address 0x1 is not stack'd, malloc'd or (recently) free'd
==1914== 
==1914== 
==1914== Process terminating with default action of signal 11 (SIGSEGV)
==1914==  Access not within mapped region at address 0x1
==1914==    at 0x4A0A231: strstr (mc_replace_strmem.c:1367)
==1914==    by 0x5516C8: LAMMPS_NS::AtomVecHybrid::process_args(int, char**) (atom_vec_hybrid.cpp:217)
==1914==    by 0x52E7DE: LAMMPS_NS::Atom::create_avec(char const*, int, char**, int) (atom.cpp:701)
==1914==    by 0x40BC4D: LAMMPS_NS::Input::atom_style() (input.cpp:1421)
==1914==    by 0x408914: LAMMPS_NS::Input::execute_command() (input.cpp:801)
==1914==    by 0x406918: LAMMPS_NS::Input::file() (input.cpp:229)
==1914==    by 0x4050F3: main (main.cpp:65)
```

**Comment by stanmoore1** [comment]
The Kokkos failing tests are coming from this change: https://github.com/lammps/lammps/pull/1788/files#diff-8aa6aef318bc37bda5aaf422631ed7faL718. If I add this back in then Kokkos runs:

```patch
diff --git a/src/special.cpp b/src/special.cpp
index f859f4f..4fb7f40 100644
--- a/src/special.cpp
+++ b/src/special.cpp
@@ -715,6 +715,7 @@ void Special::combine()
     memory->create(atom->special,atom->nmax,atom->maxspecial,"atom:special");
   }
 
+  atom->avec->grow_pointers();
   tagint **special = atom->special;
 
   // ----------------------------------------------------
```

@sjplimp is there a reason this call was removed? Should I commit this change or do something different for Kokkos?

**Comment by sjplimp** [comment]
@stanmoore1 I will look into these issues.  The LB polymer script is odd.
It says:
atom_vec hybrid molecular
Just one sub-style which should maybe be an error.
Without hybrid it runs until it reads
the data file, then gives a formatting error.

**Comment by stanmoore1** [comment]
@sjplimp I think I fixed the Kokkos issue. I'm running the regression tests again.

**Comment by sjplimp** [comment]
@stamoor I just pushed a bug fix for the issue with the LB polymer script.  Now appears to start running correctly.  It does show valgrind errors, but the same ones are also present in current master.  So I think this has nothing to do with the new AtomVec classes.  Re: special.cpp, are you saying this is a Kokkos-only problem?  No issue in CPU version?  What is the test script you are running for that?

**Comment by sjplimp** [comment]
@stanmoore1 See the previous comment if you didn't get an email on it

**Comment by stanmoore1** [comment]
>Re: special.cpp, are you saying this is a Kokkos-only problem? No issue in CPU version? What is the test script you are running for that?

This is a Kokkos-only problem. I moved the `grow_pointers` call up a little into a Kokkos-only part of the code. I'm using the `rhodo` benchmark to test.

**Comment by sjplimp** [comment]
@stanmoore1 ok - I like that solution - I don't think the CPU version of the AtomVec classes needs the grow_pointers() call

**Comment by stanmoore1** [comment]
@sjplimp all the vanilla LAMMPS regression tests are passing now. I'm working on Kokkos.

**Comment by stanmoore1** [comment]
Good news is all the regression tests are passing, for both vanilla and Kokkos OpenMP & CUDA. I want to make a small tweak to the code, then it will be ready to merge.

**Comment by stanmoore1** [comment]
All regression tests are passing on my end.

**Pull request merged**
