### PR TITLE
Update Kokkos version in LAMMPS to 3.7.1

### LINKED ISSUE #3584: [BUG] Can't build CUDA KOKKOS with CUDA 12 and cmake
**Summary**

Trying to use cmake for LAMMPS compilation with KOKKOS fails if CUDA 12 is installed.

**LAMMPS Version and Platform**

Current develop

**Expected Behavior**

Cmake should correctly prepare files for compilation.

**Actual Behavior**

An error appears:
`nvcc fatal   : Value 'sm_35' is not defined for option 'gpu-architecture'`

Followed by errors from the cmake itself:

```
CMake Error at /tmp/lammps/lib/kokkos/cmake/kokkos_compiler_id.cmake:12 (STRING):
  STRING sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  /tmp/lammps/lib/kokkos/cmake/kokkos_compiler_id.cmake:53 (kokkos_internal_have_compiler_nvcc)
  /tmp/lammps/lib/kokkos/cmake/kokkos_tribits.cmake:215 (INCLUDE)
  /tmp/lammps/lib/kokkos/CMakeLists.txt:188 (KOKKOS_SETUP_BUILD_ENVIRONMENT)


-- SERIAL backend is being turned on to ensure there is at least one Host space. To change this, you must enable another host execution space and configure with -DKokkos_ENABLE_SERIAL=OFF or change CMakeCache.txt
-- Using -std=c++14 for C++14 standard as feature
CMake Error at /tmp/lammps/lib/kokkos/cmake/kokkos_test_cxx_std.cmake:132 (MESSAGE):
  Invalid compiler for CUDA.  The compiler must be nvcc_wrapper or Clang or
  NVC++ or use kokkos_launch_compiler, but compiler ID was GNU
Call Stack (most recent call first):
  /tmp/lammps/lib/kokkos/cmake/kokkos_tribits.cmake:242 (INCLUDE)
  /tmp/lammps/lib/kokkos/CMakeLists.txt:188 (KOKKOS_SETUP_BUILD_ENVIRONMENT
```

**Steps to Reproduce**

Install CUDA 12.0, and run following lines:
```
git clone https://github.com/lammps/lammps
cd lammps
mkdir build
cd build
cmake -D PKG_KOKKOS=yes -D Kokkos_ENABLE_CUDA=yes ../cmake
```

The issue also appears if a GPU architecture is specified, e.g. `-D Kokkos_ARCH_AMPERE86=yes` is added.

**Further Information, Files, and Links**

The issue arises from the `nvcc_wrapper` script which uses `sm_35` as a default architecture and it was removed in CUDA 12:
https://github.com/lammps/lammps/blob/f84b64bc869003320ccc3b83e8cfe428d9b87f0f/lib/kokkos/bin/nvcc_wrapper#L15-L16

This problem is solved if the line with `sm_35` is commented and the next one uncommented, but I think it should documented somewhere.

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

- Update Kokkos version bundled with LAMMPS to v3.7.01
- Backport Kokkos PR #5624 to Kokkos version in LAMMPS to correct occupancy calculations for Kokkos CUDA, see https://github.com/kokkos/kokkos/pull/5624 for a more detailed description. This may hurt performance a little in some cases, need to check.
- Fix init arguments and some join stuff for Kokkos 4

Closes #3568
Closes #3584

**Related Issue(s)**

#3568, #3584

**Author(s)**

Stan Moore (SNL), Christian Trott (SNL) Axel Kohlmeyer (Temple U), and Kokkos developers, thanks to @weinbe2 for helping backport Kokkos changes

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
Running internal regression tests now. Also need to check performance.

**Comment by stanmoore1** [comment]
Internal regression tests passed. Checking performance now.

**Comment by akohlmey** [comment]
@stanmoore1 it looks like the pending CI test was completed but the report somehow was not sent or received by GitHub. I'll try to re-trigger it. Otherwise I would just merge in current upstream and trigger a complete new rebuild and test cycle.

**Comment by stanmoore1** [comment]
I'm still testing performance. Everything looks good so far, except I see a ~6% regression for ReaxFF with CUDA 11.2.0.

**Comment by stanmoore1** [comment]
I tested performance for V100 and A100. Everything looks good except ReaxFF on V100.

**Comment by stanmoore1** [comment]
I also spot checked a couple potentials on MI250X and it looks good.

**Comment by stanmoore1** [comment]
We have a potential fix for the ReaxFF regression, but need a little more testing.

**Comment by stanmoore1** [comment]
The ReaxFF regression should be fixed by https://github.com/kokkos/kokkos/pull/5739, need to back port those changes.

**Comment by stanmoore1** [comment]
Rerunning regression tests. Also need to do a quick check of performance.

**Comment by stanmoore1** [comment]
Regression tests passed and performance looks good. This is ready to merge from my POV.

**Comment by akohlmey** [comment]
> Regression tests passed and performance looks good. This is ready to merge from my POV.

Excellent!! Thank you so much for your effort!

**Review by athomps — APPROVED** [review]
I approve.

**Pull request merged**
