### PR TITLE
Add atom_map hash option for Kokkos package

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Add `atom_map` "hash" option for Kokkos package. Previously only the "array" option was supported by the Kokkos package.

**Related Issue(s)**

None.

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
Running this PR through Kokkos regression testing now.

**Comment by stanmoore1** [comment]
@akohlmey I'm seeing a collision, not sure how to fix this:

```
09:43:00 In file included from ../fix_reaxc_species_kokkos.cpp:22:0:
09:43:00 ../reaxc_defs.h:38:18: error: expected identifier before numeric constant
09:43:00  #define SUCCESS  1
09:43:00                   ^
09:43:00 ../../lib/kokkos/containers/src/Kokkos_UnorderedMap.hpp:88:5: note: in expansion of macro ‘SUCCESS’
09:43:00      SUCCESS          = 1u << 31,
```

**Comment by stanmoore1** [comment]
Can we rename the ReaxFF `SUCCESS` variable, or move it into a namespace?

**Comment by akohlmey** [comment]
> Looks like this is fixed in #2708.

yes. please note that you cannot put a pre-processor define into a namespace. so it would have to be renamed.
#2708 rebuilds the common reaxff headers to have only the required parts on only expose to the rest of LAMMPS which needs to be and thus removing all kinds of defines, declarations and settings that were not used.

**Comment by stanmoore1** [comment]
What is the ETA for #2708 being merged?

**Comment by stanmoore1** [comment]
@akohlmey I mean: should I go ahead and rename the ReaxFF SUCCESS variable in this PR, or will #2708 be merged soon and I wait?

**Comment by akohlmey** [comment]
> What is the ETA for #2708 being merged?

Need to discuss that with @athomps 
The plan is to have it included in the upcoming stable release. But currently it depends on resolving the issues in #2736 first and then port them over to #2708. Contingency plan would be to postpone those changes and place tests and warnings into the code when the results are questionable, i.e. with fdotr is explicitly disabled

**Comment by athomps** [comment]
I just looked at #2736.  That is a lot of pair styles affected!  For this discussion, I thought we had fully resolved the problem with reax/c, but perhaps not reax/c/omp.  In any event, resolving reax/c/omp issue will take some effort.   Therefore, I recommend going ahead with the existing improvements (either just renaming SUCCESS, or else broader changes), and addressing #2736 later.

**Comment by stanmoore1** [comment]
The unit test failure looks unrelated to the changes in this PR, @akohlmey or @rbberger can you take a look?

**Comment by stanmoore1** [comment]
```
CMake Error at Modules/Packages/USER-PACE.cmake:8 (file):
  file DOWNLOAD HASH mismatch

    for file: [/data/builder/workspace/dev/pull_requests/ubuntu/unit_tests/cmake_mpi_openmp_smallsmall_shared/build/libpace.tar.gz]
      expected hash: [4db54962fbd6adcf8c18d46e1798ceb5]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

Call Stack (most recent call first):
  CMakeLists.txt:356 (include)


You have called ADD_LIBRARY for library pace without any source files. This typically indicates a problem with your CMakeLists.txt file
```

**Comment by akohlmey** [comment]
> I just looked at #2736. That is a lot of pair styles affected! For this discussion, I thought we had fully resolved the problem with reax/c, but perhaps not reax/c/omp. In any event, resolving reax/c/omp issue will take some effort. Therefore, I recommend going ahead with the existing improvements (either just renaming SUCCESS, or else broader changes), and addressing #2736 later.

@athomps To be able to merge #2708 I will have to roll back some of your changes as they are addressing what #2736 is supposed to resolve in a more general way.

**Comment by stanmoore1** [comment]
All Kokkos regression tests passed, except voronoi is crashing on GPU.

**Comment by athomps** [comment]
That's fine.

**Comment by stanmoore1** [comment]
The crash for voronoi exposed an issue in the code, will need to refactor a bit

**Comment by stanmoore1** [comment]
@akohlmey @rbberger any ideas on the failed Intel compilation test? I can't reproduce this on my local box with Intel 19.0.5 and all the other compilers (e.g. GCC) in the test suite are happy too.

```
Scanning dependencies of target lmp
[100%] Building CXX object CMakeFiles/lmp.dir/mnt/lammps/workspace/dev/pull_requests/compilation_tests/lammps/src/main.cpp.o
[100%] Linking CXX executable lmp
liblammps.so.0: undefined reference to `LAMMPS_NS::AtomKokkos::map_set()'
liblammps.so.0: undefined reference to `LAMMPS_NS::AtomKokkos::map_init(int)'
liblammps.so.0: undefined reference to `LAMMPS_NS::AtomKokkos::map_delete()'
```

**Comment by akohlmey** [comment]
> @akohlmey @rbberger any ideas on the failed Intel compilation test? I can't reproduce this on my local box with Intel 19.0.5 and all the other compilers (e.g. GCC) in the test suite are happy too.
> 
> ```
> Scanning dependencies of target lmp
> [100%] Building CXX object CMakeFiles/lmp.dir/mnt/lammps/workspace/dev/pull_requests/compilation_tests/lammps/src/main.cpp.o
> [100%] Linking CXX executable lmp
> liblammps.so.0: undefined reference to `LAMMPS_NS::AtomKokkos::map_set()'
> liblammps.so.0: undefined reference to `LAMMPS_NS::AtomKokkos::map_init(int)'
> liblammps.so.0: undefined reference to `LAMMPS_NS::AtomKokkos::map_delete()'
> ```

Could it be that those are called from a constructor or destructor without explicit scoping? i.e. you are calling `map_set()` or `map_init()` or `map_delete()`, but since the virtual function tables are not always fully functioning, the linker may get confused.
If that is the case, replacing `map_init()` with `AtomKokkos::map_init()` may do the trick.

When you make a class polymorph (i.e. add the virtual keyword to member functions), you should probably also declare the destructor as virtual so that the destructors in the class hierarchy are run in reverse order.

**Comment by stanmoore1** [comment]
OK I'll take a look. What version of the Intel compiler is used for PR testing?

**Comment by akohlmey** [comment]
> OK I'll take a look. What version of the Intel compiler is used for PR testing?

According to the CMake output in the Jenkins console log it is the following.

For the "intel_oneapi" compilation it is (on ubuntu 20.04)
```
-- The CXX compiler identification is Intel 20.2.2.20210228
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/compiler/2021.2.0/linux/bin/intel64/icpc - skipped
```

For the "intel" compilation it is (on ubuntu 20.04)
```
-- The CXX compiler identification is Intel 19.1.2.20200623
-- Check for working CXX compiler: /opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64/icpc
-- Check for working CXX compiler: /opt/intel/compilers_and_libraries_2020.2.254/linux/bin/intel64/icpc - works
```

**Comment by akohlmey** [comment]
@stanmoore1 as it turns out, the linker failure has nothing to do with the Intel compilers, but is due to using CMake **and** building a static LAMMPS library. It won't show with the conventional build system, as the newly added file is copied automatically. For CMake certain files, that are not "style" classes matching a base class, need to be listed explicitly in `cmake/Modules/Packages/KOKKOS.cmake`. The missing object file only produces and error at link time when linking statically. With a shared library the relocation is by default deferred to when the program is actually run. That it shows with the two Intel compiler based compilation tests is a coincidence. FWIW, I could reproduce the linker error locally on a Fedora 34 machine with `cmake -S cmake -C cmake/presets/intel.cmake -C cmake/presets/kokkos-openmp.cmake -B build-kokkos && cmake --build build-kokkos` where CMake reports the C++ compiler as:
```
-- C++ Compiler:     /home/akohlmey/intel/oneapi/compiler/2021.2.0/linux/bin/intel64/icpc
      Type:          Intel
      Version:       2021.2.0.20210228
      C++ Flags:     -restrict -Wall -Wextra -g -O2 -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=4;LAMMPS_JPEG;LAMMPS_PNG;LAMMPS_GZIP;LAMMPS_FFMPEG;LMP_KOKKOS
      Options:       -xHost
```

Just pushed the changes that make the compilation pass for me. Not sure if the failure of the unit tests has the same cause.

**Comment by akohlmey** [comment]
@rbberger the unit test runs fail with
```
INFO: [CTest-Version 3.x (default)] - 1 test report file(s) were found with the pattern 'build/Testing/**/Test.xml' relative to '/home/builder/workspace/dev/pull_requests/ubuntu/unit_tests/cmake_mpi_openmp_smallbig_shared' for the testing framework 'CTest-Version 3.x (default)'.
[Cobertura] Cobertura coverage report found.

[Pipeline] sh (Download and verify CodeCov)
+ /home/builder/workspace/dev/pull_requests/unit_tests/lammps-testing/scripts/common/download_codecov.sh
codecov: FAILED
shasum: WARNING: 1 computed checksum did NOT match
codecov: FAILED
shasum: WARNING: 1 computed checksum did NOT match
codecov: FAILED
shasum: WARNING: 1 computed checksum did NOT match
```
any idea what could be causing this? Unit tests themselves are passing.

**Comment by akohlmey** [comment]
> any idea what could be causing this? Unit tests themselves are passing.

This seems to be an issue with codecov itself. They just released version 1.0.4. However, the (generic) download has the wrong version number in the downloaded script. If I manually download the specific version from the 1.0.4 tag based branch I get a file that differs only in version. Thus with the generic download it checks against the wrong checksums (from version 1.0.3).

```
$ diff -u codecov codecov.1 
--- codecov	2021-07-10 11:55:30.489907735 -0400
+++ codecov.1	2021-07-10 11:57:13.822488665 -0400
@@ -5,7 +5,7 @@
 
 set -e +o pipefail
 
-VERSION="1.0.3"
+VERSION="1.0.4"
 
 codecov_flags=( )
 url="https://codecov.io"

```

**Comment by stanmoore1** [comment]
Thanks @akohlmey

**Comment by stanmoore1** [comment]
This now passes my local testing for GPU and CPU. I'm running the full Kokkos regression tests once more just to be safe.

**Comment by akohlmey** [comment]
> What is the ETA for #2708 being merged?

FYI, PR #2736 is now completed and merged and I have just updated #2708 and cleaned up the merge conflicts. Tomorrow I will start testing and reviewing which changes are still pending for this one. In the course of completing PR #2736 I've also implemented the infrastructure to replace the non-threaded virial tally calls in the OPENMP version of REAXFF. So I just need a bit of luck tomorrow... :smile:

**Comment by stanmoore1** [comment]
> > What is the ETA for #2708 being merged?
> 
> FYI, PR #2736 is now completed and merged and I have just updated #2708 and cleaned up the merge conflicts. Tomorrow I will start testing and reviewing which changes are still pending for this one. In the course of completing PR #2736 I've also implemented the infrastructure to replace the non-threaded virial tally calls in the OPENMP version of REAXFF. So I just need a bit of luck tomorrow... 😄

Sounds good, thanks

**Comment by stanmoore1** [comment]
Regression tests passed, ready for merge.

**Comment by akohlmey** [comment]
@sjplimp can you please have a look at this PR. This is next in line to be merged, but since it changes some core classes, I don't want to merge it without your OK.

**Comment by stanmoore1** [comment]
>since it changes some core classes, I don't want to merge it without your OK.

The changes to core are all trivial, like adding the `virtual` keyword...

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
