### PR TITLE
Voigt documentation

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

Clarify in code comments and a couple command doc pages when Voigt ordering or non Voigt ordering (virials)
is used.  This is for symmetric virial and pressure tensors.

**Related Issue(s)**

N/A

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey Changes to src code are simply comments.

**Review by stanmoore1 — APPROVED** [review]

**Review by akohlmey — APPROVED** [review]

**Comment by akohlmey** [comment]
> @akohlmey Changes to src code are simply comments.

yup. but it needed updating the false positives list for the spell checking of the manual.

**Review by athomps — APPROVED** [review]
This is a good change.  False assumptions about the ordering is definitely a source of insidious errors.  To make it even more clear, I suggested changing ever occurrence of `xx,yy,zz,xy,xz,yz`, etc. to `xx,yy,zz,xy,xz,yz (non-Voigt)`

**Comment by sjplimp** [comment]
Aidan's suggestion is a good one - do I need now to make a 2nd PR for that?

**Comment by akohlmey** [comment]
> Aidan's suggestion is a good one - do I need now to make a 2nd PR for that?

yup. just merged this 5 mins ago after having to work around some storage issue on our CI servers. sorry.

**Pull request merged**
