### PR TITLE
extract/scale for pair/snap

### PR DESCRIPTION
**Pull request by tomswinburne**
**Summary**

Added extract() function and scale matrix to pair/snap, following pair/eam/fs. 

**Author(s)**

TD Swinburne, CNRS, swinburne@cinam.univ-mrs.fr

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

full

**Implementation Notes**

none
**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**
n/a

### CODE REVIEW

**Comment by akohlmey** [comment]
@tomswinburne thanks for your submission.
I'll leave it to @athomps to check if your changes are correct, since he "owns" this part of the LAMMPS code.

I have a bunch of formal issues. You selected a bunch of checkmarks in the submission template that are not correct:
- there is no documentation added. Pair styles compatible with fix adapt (and the parameters that can be adapted) are listed in the fix adapt and fix adapt/fep documentation page in a table.
- there is no unit test added or updated (supported extract parameters should be listed)
- there is no example provided (not required for this kind of change unless you have a very instructive and special example)
- there are whitespace changes (empty lines or spaces added/removed) that are unrelated to the functionality added and should thus be reverted. If desired I can flag them individually.

**Review by athomps — COMMENTED** [review]
I agree with all of Axel's comments. I welcome a simple fast-running demo/test added to ./examples/snap.

**Comment by tomswinburne** [comment]
Dear Axel, Aidan,

Thanks for the quick reply and apologies for the imprecision. I'll address
these changes and resubmit.

Best

Tom

**Comment by akohlmey** [comment]
@tomswinburne please note that you are a "victim" of the package reorganization that we had planned for a while. Since merging with upstream to resolve the merge conflicts can be complicated under the current circumstances, I suggest you make copies of your modified files, reset your master branch, then start a new feature branch(!) from there and re-add the modified files. Please note that it is best practice to not do any development on the "master" branch but only on feature branches so it is easy to keep "master" in sync with  upstream through fast-forward merges and thus avoid diverging commit histories.

**Comment by tomswinburne** [comment]
Dear Axel,

Thanks for the heads up, given how small my proposed changes are this will be easy to start a new feature branch as you describe on my fork. I’ll get this underway asap

**Pull request closed without merging**
