### PR TITLE
Update Kokkos library to v2.03.13

### PR DESCRIPTION
**Pull request by stanmoore1**
Update Kokkos library to v2.03.13

### CODE REVIEW

**Comment by stanmoore1** [comment]
Internal Kokkos regression tests passed.

**Comment by stanmoore1** [comment]
@akohlmey should I wait until after the stable release to assign to @sjplimp?

**Comment by rbberger** [comment]
@stanmoore1 if you ask that question, please assign axel to it. otherwise steve just merges it and we can't stop it anymore.

**Comment by akohlmey** [comment]
@stanmoore1 am still working on cleaning up the docs and some related things. Due to removing Make.py and replacing most of its functionality with the Install.py files in lib, there are several inconsistencies, that i believe should be resolved for a stable release. unfortunately, there have been too many distractions on my side at the moment, so progress is slow. I.e. the stable release will have to wait until after the LAMMPS workshop. This is not what i had hoped for, but considering that most LAMMPS users will use stable releases these days, it is the reasonable choice.

**Comment by stanmoore1** [comment]
@akohlmey This PR is ready to merge--can you assign to @sjplimp when ready? Thanks

**Comment by akohlmey** [comment]
@stanmoore1 does this fix any significant known bugs? or asked differently do your prefer it to be included in the stable release or not? if not, i would suggest we wait until after the stable release, which won't happen until next week due to the ongoing workshop. i don't want to make any changes to the core code, but peripheral changes should be OK (like richard's python fixes, and a few tweaks/consistency changes to docs and (secondary) installation scripts. KOKKOS is somewhere in between, so i won't fight it, if you have a good argument for including this PR.

**Comment by stanmoore1** [comment]
@akohlmey this update isn't critical and can wait until next week

**Pull request merged**
