### PR TITLE
Pair entropy fingerprint

### PR DESCRIPTION
**Pull request by PabloPiaggi**
## Purpose

This pull request includes a new compute style that implements a fingerprint to distinguish liquid and solid-like environments. The fingerprint is described in [this article](https://aip.scitation.org/doi/full/10.1063/1.4998408) and is based on a two-body approximation for the entropy of fluids, we therefore call it "pair entropy fingerprint". One of the advantages of this parameter over others is that no a priori information about the solid structure is required.

## Author(s)

Pablo M. Piaggi
Ecole Polytechnique Fédérale de Lausanne (EPFL)
Switzerland

## Implementation Notes

The fingerprint is implemented using the equations described in the article cited above. I tested the correctness of this implementation by comparing the results with another implementation. The normalization of g(r) was verified. 

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

The relevant files are:
- src/USER-MISC/compute_pair_entropy_atom.cpp
- src/USER-MISC/compute_pair_entropy_atom.h
- examples/USER/misc/pair_entropy/*
- doc/src/compute_pair_entropy_atom.txt

Link to the publication
https://aip.scitation.org/doi/full/10.1063/1.4998408

### CODE REVIEW

**Comment by akohlmey** [comment]
Thanks for your contribution to LAMMPS. I renamed the files to be consistent with the style name and added a few entries to integrate your contribution into the document builds and README file.

**Comment by sjplimp** [comment]
This all looks great.  Thanks Pablo for adding this new functionality.
My only quibble is the naming of several of the files.  In order to keep
them consistent with the rest of LAMMPS.  Pair is an overloaded term
for LAMMPS.  So I suggest:

name of command:  compute entropy/atom
source files: compute_entropy_atom.cpp/h
name of class in source files: ComputeEntropyAtom
name of eq files: compute_entropy_atom.tex/jpg
name of example dir: examples/USER/misc/entropy or entropy_atom

Unless you think that there may be future variants
of this which are not pairwise and require their
own command (as opposed to an option added to 
the existing command).  In which case:

name of command: compute entropy/pair/atom
likewise for other names

**Comment by akohlmey** [comment]
i suspect @sjplimp may not have studied the logged changes here carefully enough and thus may have drawn conclusions that are not consistent with the state of affairs. i am quite comfortable with the current name of the compute style `pentropy/atom`. i would consider a name like `entropy/pair/atom` more misleading.

**Comment by sjplimp** [comment]
Thanks for the feedback.  Regardless of the command name, all the
other things I listed need to be consistent with the command name.
I think we should go with compute entropy/atom.  The majority of
compute names are simple words (sometimes shorter abbrevs).
This compute calcs per-atom entropy.  Its limitations (liquids) and its method
(pairwise) should be explained in its doc page.  If we have future
contributions that compute entropy in other ways, then we usually
go the route of compute entropy/alternate/atom.  Just like there
are many variants of compute temp.  Thanks.

**Comment by PabloPiaggi** [comment]
I changed the name of the compute style to entropy/atom and updated all the files that were affected by this change. Perhaps @akohlmey and @sjplimp can confirm that they agree with the changes? Thank you.

**Comment by sjplimp** [comment]
Looks great  - thanks for morphing it to the new name.

**Pull request merged**
