### PR TITLE
Implementing short neighbor lists for three-body gpu styles

### LINKED ISSUE #543: Implement short neighborlists on manybody potentials in GPU package
In CPU and KOKKOS versions of vashishta, sw and tersoff, we use short neighbor lists that only contains neighbors within cutoff. This is especially useful in vashishta where 3-body forces usually have much smaller cutoff. 

The GPU package is nice since it supports single/mixed precision and works in Atomify, so I'm interested in porting this feature into the GPU package as well. I'm not so familiar with how it actually does neighbor list building etc, so if anyone knows how to do this easily, feel free to do it :D If not I'll probably try to understand how it's done.

### PR DESCRIPTION
**Pull request by ndtrung81**
## Purpose

This PR closes #543,  adding support for short neighbor lists for kernels in 3-body /gpu styles (sw, tersoff* and vashista), in a similar fashion to what has been done for their CPU-only counterparts. When the neighbor list is built on the device (neigh yes), performance could be improved remarkably.

## Author(s)

Trung D. Nguyen (Northwestern University)
(with thanks for the motivation by, and discussion with, Anders Hafreager @andeplane)

## Backward Compatibility

The changes in the PR do not break backward compatibility.

## Implementation Notes

In cases where the neighbor list is built on the device (neigh yes) or on the host with the number of threads per atom equal 1 (tpa 1), the 3-body gpu styles build a short neighbor list from the existing neighbor list data at every time step. This short neighbor list is then used for 3-body kernels (three_center, three_end and three_end_vatom).

In the case where the neighbor list is built on the CPU and tpa > 1 (e.g. in pair hybrid), the code falls back to the current implementation, so the PR would not affect the performance in this case.

The PR has been tested for all the cases mentioned for sw/gpu, tersoff/gpu, tersoff/mod/gpu, tersoff/zbl/gpu and vashista/gpu.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by andeplane** [comment]
I'll take a look tomorrow.

One comment: since the regular neighbor list includes neighbors within r<rCut+rShell, we should also build a shortlist for 2-body kernels that only contains pairs within rCut. Or what do you think?

**Comment by ndtrung81** [comment]
For sw and tersoff potentials, I have implemented the short list for the 2-body kernel, which happens to be identical to that for the 3-body kernels. For vashista, as you pointed out, these two short lists are different (by using cutshortsq = cutmax*cutmax and cutshotsq = r0max*r0max, respectively). I can give it a try but it may take me a while, and I don't expect much further speedup overall because the timing for the 2-body kernel is quite small compared to the 3-body kernels anyway.

**Comment by andeplane** [comment]
Ok I see. I suggest something like doubling size of neighbor list so that dev_short_nbor[3bodymax] is number of 2body neighbors and their indices are found at dev_short_nbor[3bodymax+n_stride].

Or just have another array so we have `dev_short_nbor_3body` and `dev_short_nbor_2body`. I tested the latter and got 5-10% increase for SiC, a nice to have at least. For SiC, 2-body cutoff is 7.9, 3-body is 2.9 so the 2-body kernels get higher share of computing time than SiO2 with 5.5 vs 2.6. I'll do more testing later. We can skip this for now and add later.

I'll look through it today :)

**Comment by akohlmey** [comment]
@ndtrung81 if you are ready with this, please assign it to me, so that we can process this PR as soon as the stable release is done.

**Comment by ndtrung81** [comment]
@akohlmey Yes, the PR is ready for me and I have assigned it to you. Thanks!

**Pull request merged**
