### PR TITLE
Add error if using multiple threads with Kokkos Serial backend

### LINKED ISSUE #3132: [BUG] Kokkos unit test LammpsClass  / LAMMPS_kokkos.InitMembers fails
**Summary**

This install is for a HPC cluster. Lammps is compiled with unit tests and unit tests are run for validation. 
Using Intel compiler, several unit test fail. Reverting to gcc, still one test fails with the KOKKOS module. 

The unit test checks for an  output line starting with  "Kokkos::OpenMP::", but the  only actual KOKKOS output line starts with "KOKKOS mode is enabled".

==================================
running the test and partial output: 

lammps-patch_7Jan2022-83-gd51017ff50/build_serial/unittest/cplusplus/test_lammps_class
[...]
[----------] 1 test from LAMMPS_kokkos
[ RUN      ] LAMMPS_kokkos.InitMembers
/dev/shm/mqj37/chem/lammps/patch_7Jan2022-83-gd51017ff50-nd/src/lammps-patch_7Jan2022-83-gd51017ff50/unittest/cplusplus/test_lammps_class.cpp:270: Failure
Value of: output
Expected: starts with "Kokkos::OpenMP::"
  Actual: ""
[  FAILED  ] LAMMPS_kokkos.InitMembers (1 ms)
[...]

==================================
So expected output is "Kokkos::OpenMP::"
Actual output:

$ echo | ../../lmp_serial      "-k"     "on"   "t"    "2"     "-sf"  "kk"
LAMMPS (7 Jan 2022)
KOKKOS mode is enabled (src/lammps-patch_7Jan2022-83-gd51017ff50/src/KOKKOS/kokkos.cpp:105)
  will use up to 0 GPU(s) per node
  using 2 OpenMP thread(s) per MPI task

==================================

**LAMMPS Version and Platform**
* lammps-patch_7Jan2022-83-gd51017ff50
* Rocky Linux 
* cmake command/flags:
cmake -DCMAKE_INSTALL_PREFIX=<somedir> -D ENABLE_TESTING=on -DPKG_KOKKOS=yes -DPKG_OPENMP=yes  -DPKG_MPIIO=no -D LAMMPS_MACHINE=serial -DPKG_MPI=no -DBUILD_MPI=off ../cmake

Variants tested with -DPKG_OPENMP=yes  and without and with -DMKL and without.

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Add error if using multiple threads with Kokkos Serial backend
Also updates the LammpsClass unit test to automatically adapt to whether a threaded backend is available or not.

**Related Issue(s)**

Closes #3132 

**Author(s)**

Stan Moore (SNL), suggested by Richard Berger (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
I tested this and it works.

**Review by rbberger — APPROVED** [review]

**Review by athomps — APPROVED** [review]

**Comment by rbberger** [comment]
@stanmoore1 it seems to be possible to compile LAMMPS with both Serial and OpenMP enabled. In that case, this error triggers as well.

**Comment by stanmoore1** [comment]
OK I'll tweak the check

**Comment by stanmoore1** [comment]
@rbberger I think I fixed the issue

**Pull request merged**
