### PR TITLE
Group dynamic property: inherit atoms

### PR DESCRIPTION
**Pull request by jrgissing**
## Purpose

If the group ID already exists, add the specified atoms to a 'dynamic-property group,' as promised by docs

## Author(s)

JG

## Backward Compatibility

yes

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@jrgissing Assuming that i do understand correctly, what you are trying to do here, i have to say, that i don't agree with the logic you are trying to employ. it is quite confusing to me. the logic for dynamic groups is simple: whenever the defining property is (re-)evaluated, all atoms in the parent group conforming to that property are included and all not are removed, which means a complete reset. The behavior you want, can be implemented e.g. by changing the expression used to define the group. When defining a dynamic group with the name of a previous static group, this should not matter, or - for clarity - should be flagged as an error.
@sjplimp what do you think?

**Comment by jrgissing** [comment]
@akohlmey the behavior I'm trying to get at is: allow users to custom initialize a per-atom property group. for example, if they wanted bond/react to only act on all molecules that have an atom in a specific region, this would allow them to define that group

**Comment by jrgissing** [comment]
leaning toward allowing for customized dynamic-property-groups internally, i.e. without needing this modification. @akohlmey I agree that 'When defining a dynamic group with the name of a previous static group, this should not matter.' will close this PR soon

**Comment by sjplimp** [comment]
@jrgissing @akohlmey Just looking at this now.  Not clear on a few things.
a) I agree with Axel that the current dynamic group rule is simple: re-eval,
is a complete reset of the dynamic group, no history involved.
b) Jake said "as promised by docs" in original PR, not clear what you
are referring to - are you saying (a) violates something on the doc page?
c) are there useful use cases for a dynamic group where (a) is insufficient?
I think you said: define a group where all molecules with any atom in a region
are the group.  Don't think that can currently be done.  How are you saying
it could be done?

**Comment by sjplimp** [comment]
@jrgissing @akohlmey One more Q - possibly this is the confusion on my previous comment (b).
The group doc page for dynamic groups says this:
"The per-atom property is evaluated and atoms whose
values are 0.0 are removed from the dynamic group, otherwise they
are added to the group."
I think that's wrong, since there is nothing to eval for a atom property
(it's just a stored value for each atom)
and "add" is confusing in this context.  Should it just be:
"Atoms whose per-atom property value is 0.0 are removed
from the dynamic group."
Am I forgetting some way that per-atom properties can themselves
be dynamic?

**Comment by jrgissing** [comment]
b) i think the docs are technically correct. basically, i was finding "If the group ID already exists, the group command adds the specified atoms to the group" to be slightly misleading for dynamic property groups

c) In my case, it will be most user-friendly to convert the inputted group under-the-hood to a properly initialized dynamic group [technically, in an input script, you could also define an arbitrary group, set a 'gmask' variable, initialize a per-atom property with that variable, then define the dynamic property group]

'One more Q' - i think the original doc page is more correct, because at least one fix does dynamically update per-atom properties (and therefore both add and remove atoms from groups). however, we might reiterate there that they still must be in the parent group to be added

**Pull request closed without merging**
