### PR TITLE
Intel GPU updates: kspace & cmake

### PR DESCRIPTION
**Pull request by cjknight**
**Summary**

This adds support for offloading FFTs on Intel GPUs via oneMKL when using the SYCL backend of Kokkos. Makefiles for Aurora are included and support was also added for cmake. 

This fixes a bug in fix shake/kk where forces weren't correctly synced on host at start of simulation and incorrect forces written to dump files. 

Changes for cmake are definitely a case of "It works for me." as I did not test against latest public oneAPI on a standalone node with Intel GPUs. 

One thing that was a bit strange was I had to modify KOKKOS.cmake to even get MKL FFTs to be used in a cpu build using the OpenMP backend. The cmake output did indicate MKL would be used, but I found KISS FFTs being used instead (i.e. -DFFT_KOKKOS_MKL was not being used as expected during compilation+linking). Could easily be an issue with how I was using cmake, but thought I was following the docs...

cpu :: Kokkos/OpenMP
```
cmake -C ../cmake/presets/kokkos-openmp.cmake -DPKG_MOLECULE=on -DPKG_RIGID=on -DPKG_KSPACE=on -DPKG_ML-SNAP=on -DFFT=MKL -DFFT_KOKKOS=MKL -DFFT_SINGLE=on ../cmake
```

gpu :: Kokkos/SYCL
```
cmake -C ../cmake/presets/kokkos-sycl.cmake -DPKG_MOLECULE=on -DPKG_RIGID=on -DPKG_KSPACE=on -DPKG_ML-SNAP=on -DFFT=MKL -DFFT_KOKKOS=MKL_GPU -DFFT_SINGLE=on ../cmake
```

gpu :: GPU/OpenCL
```
cmake -C ../cmake/presets/oneapi.cmake -DPKG_MOLECULE=on -DPKG_RIGID=on -DPKG_KSPACE=on -DPKG_ML-SNAP=on -DFFT=MKL -DFFT_SINGLE=on -DPKG_GPU=on -DGPU_API=opencl ../cmake
```

**Related Issue(s)**

Enables build LAMMPS with KSPACE & KOKKOS packages on Intel GPUs using the SYCL backend.

**Author(s)**

Chris Knight (ANL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Nothing should break. If changes relating to -DFFT_KOKKOS_MKL are correct, then small differences might appear with MKL now being used instead of KISS.

**Implementation Notes**

Several builds were validated on Aurora@ALCF comparing energies and forces for a few input decks for 10s of steps: in.lj, in.rhodo, and one snap workload.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by stanmoore1** [comment]
@cjknight thanks for working on this, it looks good overall. I tweaked the change to FixShake to be more general. I think the only thing this lacks is a documentation update.

**Comment by cjknight** [comment]
1st pass on updating docs included.

**Review by stanmoore1 — APPROVED** [review]

**Comment by stanmoore1** [comment]
@akohlmey The changes to `verlet_kokkos.cpp` in 26af887 is a bugfix that needs to go into the next stable.

**Comment by akohlmey** [comment]
> @akohlmey The changes to `verlet_kokkos.cpp` in [26af887](https://github.com/lammps/lammps/commit/26af8878c932aeaa24310118213a459a732e2e4a) is a bugfix that needs to go into the next stable.

Got it in  87f022576d21424ea3016b8bc5285b13cbf72075 Thanks.

**Comment by akohlmey** [comment]
@stanmoore1 @cjknight I've updated the pull request to resolve the conflicts caused by merging Richard Berger's pull request #4294. Please have a look and confirm that I didn't mess anything up. Thanks.

**Comment by cjknight** [comment]
Looks good to me! Fresh builds compiled+ran without issue.

**Comment by rarensu** [comment]
I had to tell cmake that it should look for a fortran compiler named ifort. otherwise it kept finding f95 which doesn't understand intel sycl link options; instantly fails the compile a basic program test.

**Comment by akohlmey** [comment]
> I had to tell cmake that it should look for a fortran compiler named ifort. otherwise it kept finding f95 which doesn't understand intel sycl link options; instantly fails the compile a basic program test. 

Using -D CMAKE_Fortran_COMPILER="" should also work. Nothing inside LAMMPS uses Fortran, only a few tools. Disabling the Fortran compiler will skip building those.

**Pull request merged**
