### PR TITLE
Implementation of inner/middle/outer compute methods for lj/class2

### PR DESCRIPTION
**Pull request by evoyiatzis**
Implementation of inner/middle/outer functions in style lj/class2 to enable integration with respa

**Summary**

Implementing the inner/middle/outer functions for style lj/class2

**Related Issues**

Not related to any issue

**Author(s)**

Evangelos Voyiatzis - Royal DSM, evoyiatzis@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No backward compatibility issue

**Implementation Notes**

The implementation is based on the inner/middle/outer functions of style lj/cut
A short MD NVE run was made using the in.einstein.2d file (in examples/VISCOSITY) with lj/class2 style instead of lj/cut & run_style verlet and run_style respa with all inner/middle/outer enabled. The energy of the system was conserved.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by evoyiatzis** [comment]
I have used dos2unix to fix the line ending issue. Is it ok now?

**Comment by akohlmey** [comment]
> I have used dos2unix to fix the line ending issue. Is it ok now?

no, only one of the files is corrected.

**Comment by akohlmey** [comment]
> > I have used dos2unix to fix the line ending issue. Is it ok now?
> 
> no, only one of the files is corrected.

nevermind, i went ahead and fixed it myself.

**Comment by evoyiatzis** [comment]
Thanks for taking care and fixing it - sorry for my delay in taking proper action.

**Comment by sjplimp** [comment]
@evoyiatzis thanks for submitting this

**Pull request merged**
