### PR TITLE
Change documentation to use RST directly

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

Adding the auto-generated RST files to version control is the first step of moving the documentation to RST-only. `make rst` will regenerate the RST files based on the txt files. Once the migration is complete the conversion tools will be retired.

**Related Issues**

#1533 

**Author(s)**

@rbberger (Temple University)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

HTML docs are now built directly from the RST files that are part of this repo. There is no temporary directory in `/tmp` anymore.

**Implementation Notes**

The documentation build and its files are directly written into the doc folder. Files that are not supposed to be checked in are in `.gitignore`

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by eagunn** [comment]
@rbberger I'm back online and expect to be able to contribute a few to several hours a week to lammps this semester. Please let me know how I can help with this PR and, in particular, if you think you'll want to use anything directly from #1533 or or I should just close it.

**Comment by akohlmey** [comment]
@rbberger as discussed in person, I would like to merge this PR next, so that we finally begin the transition to writing documentation directly in RST. We should leave the conversion toolchain around until after the next stable release. but we should already remove the support for the legacy documentation via txt2html and htmldoc. Could you please update this PR to the state of the current master?

**Comment by rbberger** [comment]
@akohlmey done.

**Comment by eagunn** [comment]
@rbberger Glad to see you are making progress on this big, long-term change. I'm finding that in-semester teaching duties are giving me no time to help. But I will have a month, from mid-December to mid-January without day-to-day content and grading duties. If there's anything I can do to help during that interim period, I'd be happy to give it a go. Would still like to find a role to contribute over the long run.

**Pull request merged**
