### PR TITLE
Collected small changes

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

Various small changes and bug fixes

**Related Issue(s)**

- The change to the "ramp()" function was motivated by this discussion: https://matsci.org/t/expand-compress-region/43458/
- The change to the GPU library is based on the report here: https://matsci.org/t/problem-building-lammps-with-intel-icps/43380

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

The following changes are implemented:
- replace "auto" with explicit data type in the GPU lib since some Intel compiler versions seem to sometimes not able to deduce the type
- fix cut-n-paste error in `dump_modify` error message and improve the error message
- enable `dump_modify colname` support for `dump local` that was somehow forgotten
- allow the "ramp(x,y)" function to be used in between runs (it will return the value of x in this case), also avoid division by zero when used with "run 0"
- the variable functions vdisplace(), swiggle(), and cwiggle() may not be used with fix dt/reset since they assume a constant dt
- fix copy-n-paste bug in swiggle() variable function.
- silence warnings about integer overflows from CodeQL

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp this is PR is not complete, but please have a look at the changes to the variable code and the ramp() functions and add your comments (please also look at the use case). I am particularly interested why there was a hard error (but only in one of the three places where the function is programmed, why so?) when the behavior that I chose with this PR seems quite reasonable (at least to me).

**Comment by sjplimp** [comment]
@akohlmey Similar betwee-run error for ramp is generated by vdisplace, swiggle, cwiggle

**Comment by sjplimp** [comment]
@akohlmey Also, just noticed this typo:
This line appears in an swiggle code chunk, when it should be SWIGGLE
if (tree) newtree->type = CWIGGLE;

**Comment by akohlmey** [comment]
> @akohlmey Also, just noticed this typo: This line appears in an swiggle code chunk, when it should be SWIGGLE if (tree) newtree->type = CWIGGLE;

This is now fixed (and the fix cherry-picked into the maintenance branch for the stable version)

**Comment by akohlmey** [comment]
> @akohlmey Similar betwee-run error for ramp is generated by vdisplace, swiggle, cwiggle

@sjplimp I had a close look at those and there is a significant difference: they all take the increment as an argument while ramp() has to compute it. With that it seems to me that it would be better to leave them unchanged after removing the check for being in between runs. But what I **did** notice is that these three functions assume that *dt* is constant. So I added a check that disallows using them when fix dt/reset is in use.

**Comment by sjplimp** [comment]
@akohlmey yes, removing the error check so they can be invoked between runs is what I was hoping

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
