### PR TITLE
CG-DNA unit test and performance enhancement

### PR DESCRIPTION
**Pull request by ohenrich**
**Summary**

The local reference frame of each atom is now pre-calculated only once per time step within the pair style pair_oxdna_excv, then stored and accessed by all bond and pair styles through the force->pair->extract method. Previously all bond and pair styles calculated the local reference frame separately from the quaternion data. The new logic leads to a speed-up of around 20%.

We added a unit test for atom_style oxdna, which checks, among other settings, that the ID of each bond partner in 5'-direction (id5p) is correctly assigned when reading the bond information from the data file. We introduced also the generation of log files in the ad hoc regression test functionality in the example directory.

**Author(s)**

Oliver Henrich
Department of Physics
University of Strathclyde
Glasgow, UK

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Backward compatibility is fully retained.

**Implementation Notes**

The implementation of the pre-calculated local reference frame uses the fact that as per pair_style command sequence in the input file (pair_style hybrid/overlay oxdna2/excv oxdna2/stk oxdna2/hbond oxdna2/xstk oxdna2/coaxstk oxdna2/dh for oxDNA2) the excluded volume interaction is invoked before any other pair and bonded interaction.

**Post Submission Checklist**

[x] The feature or features in this pull request is complete
[x] Licensing information is complete
[x] Corresponding author information is complete
[x] The source code follows the LAMMPS formatting guidelines
[x] Suitable new documentation files and/or updates to the existing docs are included
[x] The added/updated documentation is integrated and tested with the documentation build system
[x] The feature has been verified to work with the conventional build system
[x] The feature has been verified to work with the CMake based build system
[x] Suitable tests have been added to the unittest tree.
[x] A package specific README file has been included or updated
[x] One or more example input decks are included

### CODE REVIEW

**Comment by ohenrich** [comment]
I see somewhere there is a regression testing facility. Could you please tell me more about it. Moreover, could you please check in the new unit test for the atom_style oxdna if I overlooked anything that should be also included in the test.

**Comment by akohlmey** [comment]
> I see somewhere there is a regression testing facility. Could you please tell me more about it.

The corresponding scripts and inputs are in https://github.com/lammps/lammps-testing/
Most of those are adapted inputs from the examples tree. It is currently in a strange state, though: it is missing quite a few examples that are available because those have not been carried over; at the same time we would like to integrate this somehow into the examples tree, so that it would be easier to maintain.

There are two kinds of tests: 1) test if a run can complete with serial, MPI, or OpenMP active, 2) run with MPI can compare a processed log file to reproduce a gold standard file. Either test run can be started manually by adding labels to the PR (because they are rather time consuming and are running on limited hardware here at Temple, we cannot run them for every push to a PR) or all of them (and GPU test and Power CPU via emulator) by adding the ready_for_merge label.

**Comment by ohenrich** [comment]
Unit tests failed. No idea why. They ran fine on my system.

**Comment by akohlmey** [comment]
> Unit tests failed. No idea why. They ran fine on my system.

The added test code was not valgrind clean. It was accessing "empty" data and thus would return random data.
Those are easy to spot with:
```
valgrind  ./unittest/formats/test_atom_styles -v 2>out
```
and then from examining "out". On my (Fedora 35) machine I would get when running the test (w/o valgrind):
```
     2 = max # of 1-4 neighbors
     4 = max # of special neighbors
  special bonds CPU = 0.004 seconds
pair_style hybrid/overlay oxdna2/excv oxdna2/stk oxdna2/hbond oxdna2/xstk oxdna2/coaxstk oxdna2/dh
pair_coeff * * oxdna2/excv 2.0 0.7 0.675 2.0 0.515 0.5 2.0 0.33 0.32
pair_coeff * * oxdna2/stk seqdep 0.1 1.3523 2.6717 6.0 0.4 0.9 0.32 0.75 1.3 0 0.8 0.9 0 0.95 0.9 0 0.95 2.0 0.65 2.0 0.65
pair_coeff * * oxdna2/hbond seqdep 0.0 8.0 0.4 0.75 0.34 0.7 1.5 0 0.7 1.5 0 0.7 1.5 0 0.7 0.46 3.141592653589793 0.7 4.0 1.5707963267948966 0.45 4.0 1.5707963267948966 0.45
pair_coeff 1 4 oxdna2/hbond seqdep 1.0678 8.0 0.4 0.75 0.34 0.7 1.5 0 0.7 1.5 0 0.7 1.5 0 0.7 0.46 3.141592653589793 0.7 4.0 1.5707963267948966 0.45 4.0 1.5707963267948966 0.45
pair_coeff 2 3 oxdna2/hbond seqdep 1.0678 8.0 0.4 0.75 0.34 0.7 1.5 0 0.7 1.5 0 0.7 1.5 0 0.7 0.46 3.141592653589793 0.7 4.0 1.5707963267948966 0.45 4.0 1.5707963267948966 0.45
pair_coeff * * oxdna2/xstk 47.5 0.575 0.675 0.495 0.655 2.25 0.791592653589793 0.58 1.7 1.0 0.68 1.7 1.0 0.68 1.5 0 0.65 1.7 0.875 0.68 1.7 0.875 0.68
pair_coeff * * oxdna2/coaxstk 58.5 0.4 0.6 0.22 0.58 2.0 2.891592653589793 0.65 1.3 0 0.8 0.9 0 0.95 0.9 0 0.95 40.0 3.116592653589793
pair_coeff * * oxdna2/dh 0.1 0.2 0.815
/home/akohlmey/compile/lammps/unittest/formats/test_atom_styles.cpp:5223: Failure
Expected equality of these values:
  bond_type[lmp->atom->map(5)][0]
    Which is: 64273
  0
Total wall time: 0:00:01
[  FAILED  ] AtomStyleTest.oxdna (1129 ms)
[----------] 16 tests from AtomStyleTest (12359 ms total)

[----------] Global test environment tear-down
[==========] 16 tests from 1 test suite ran. (12420 ms total)
[  PASSED  ] 15 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AtomStyleTest.oxdna

 1 FAILED TEST
```
I suspect other machines may just segfault because of the dereferencing of uninitialized pointers.

**Review by rbberger — APPROVED** [review]

**Pull request merged**
