### PR TITLE
Update Kokkos library bundled in LAMMPS to v4.2

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Update Kokkos library bundled in LAMMPS to v4.2

**Related Issue(s)**

None

**Author(s)**

Stan Moore (SNL), Kokkos developers

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by rbberger** [comment]
Doc pages need an update due to new AMD naming convention. 

https://docs.lammps.org/Build_extras.html#available-architecture-settings

AMD_GFX906, AMD_GFX908, AMD_GFX90A, AMD_GFX1030 and AMD_GFX942

**Comment by stanmoore1** [comment]
One regression test failing on the GPU, need to debug.

On V100, this gives a small ~3 or 4% performance regression for small Lennard-Jones (1k atoms), but a ~9% speedup for the chain benchmark. Everything else is roughly the same.

**Comment by stanmoore1** [comment]
The failing regression test is not a bug in LAMMPS or Kokkos, but rather an issue with the MPI library/CUDA version on the test machine. It is failing in the MPI destructor, but only occasionally. I need to get a newer MPI but for now I consider all the tests passed.
```
--------------------------------------------------------------------------
The call to cuIpcCloseMemHandle failed. This is a warning and the program
will continue to run.
  cuIpcCloseMemHandle return value:   1
  address: 0x7fec55b74400
Check the cuda.h file for what the return value means. Perhaps a reboot
of the node will clear the problem.
--------------------------------------------------------------------------
[srgpu01:43554] *** Process received signal ***
[srgpu01:43554] Signal: Segmentation fault (11)
[srgpu01:43554] Signal code: Address not mapped (1)
[srgpu01:43554] Failing at address: 0x10

(gdb) where
#0  0x00007f8b819ef361 in opal_free_list_destruct ()
   from /projects/sems/install/rhel7-x86_64/sems/tpl/cuda_openmpi/4.0.2/gcc/8.3.0/cuda/11.1/base/lib/libopen-pal.so.40
#1  0x00007f8b779ee5d1 in mca_rcache_rgpusm_finalize ()
   from /projects/sems/install/rhel7-x86_64/sems/tpl/cuda_openmpi/4.0.2/gcc/8.3.0/cuda/11.1/base/lib/openmpi/mca_rcache_rgpusm.so
#2  0x00007f8b81a8d9af in mca_rcache_base_module_destroy ()
   from /projects/sems/install/rhel7-x86_64/sems/tpl/cuda_openmpi/4.0.2/gcc/8.3.0/cuda/11.1/base/lib/libopen-pal.so.40
#3  0x00007f8b762d8959 in mca_btl_smcuda_del_procs ()
   from /projects/sems/install/rhel7-x86_64/sems/tpl/cuda_openmpi/4.0.2/gcc/8.3.0/cuda/11.1/base/lib/openmpi/mca_btl_smcuda.so
#4  0x00007f8b775e4c3e in mca_bml_r2_del_procs ()
   from /projects/sems/install/rhel7-x86_64/sems/tpl/cuda_openmpi/4.0.2/gcc/8.3.0/cuda/11.1/base/lib/openmpi/mca_bml_r2.so
#5  0x00007f8b8307c5b7 in ompi_mpi_finalize ()
   from /projects/sems/install/rhel7-x86_64/sems/tpl/cuda_openmpi/4.0.2/gcc/8.3.0/cuda/11.1/base/lib/libmpi.so.40
#6  0x0000000000477dd6 in main () at ../main.cpp:100
#7  0x00007f8b81faa555 in __libc_start_main () from /lib64/libc.so.6
#8  0x00000000004aadce in _start ()
```

**Comment by stanmoore1** [comment]
One other known issue is that Kokkos v4.2 breaks CUDA 11.2 on Summit and Sierra/Lassen (Power9 + V100) when running on multiple GPUs with GPU-aware MPI. Using CUDA 11.1 is OK though. Turning off `cudaMallocAsync` fixes the crash, e.g. `Kokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC:BOOL=OFF`

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
