### PR TITLE
Improve PairReaxFFKokkos neigh list algorithm

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Reduce the number of resizes needed for `PairReaxFFKokkos::PairReaxBuildListsHalf` by continuing to count if space is exceeded.

**Related Issue(s)**

None

**Author(s)**

Stan Moore (SNL), with helpful discussions from Evan Weinberg (NVIDIA)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
@akohlmey this is ready to merge from my point of view.

**Comment by akohlmey** [comment]
> @akohlmey this is ready to merge from my point of view.

yes, I only removed the label because having it present will trigger the extended regression and unit tests on every comment or other change to the PR (not just pushes). this way I can merge it right away after having one more approval without having to wait at least half an hour.

while on the subject on merging, can you please check out PR #2233? your change request is still blocking it.

**Comment by stanmoore1** [comment]
OK thanks for the clarification, I will review #2233.

**Review by athomps — APPROVED** [review]
I approve.

**Pull request merged**
