### PR TITLE
core-shell version of pair_style lj/class2/coul/long

### PR DESCRIPTION
**Pull request by evoyiatzis**
**Summary**

It is an implementation of a core-shell version of pair_style lj/class2/coul/long

**Related Issues**

No related issue

**Author(s)**

Evangelos Voyiatzis (NovaMechanics Ltd) email: evoyiatzis@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

It maintains backward compatibility 

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by evoyiatzis** [comment]
@akohlmey Thanks for cleaning up the code and for the feature request #1990

**Comment by sjplimp** [comment]
@akohlmey There should also be a new entries for this on the list-of-pair-styles pages?

**Comment by akohlmey** [comment]
> @akohlmey There should also be a new entries for this on the list-of-pair-styles pages?

yes. `make -C doc style_check` confirms. BTW: we still have an undocumented compute from USER-SMD

**Comment by akohlmey** [comment]
@evoyiatzis have you tested this with `run_style respa`? There seems to be some inconsistency between the `compute()` and `compute_inner/middle/outer()` functions in the ewald adjustments.
Did you just inherit this from `lj/cut/coul/long/cs`?

It looks to me that it would be safer to disable r-RESPA support here and in all other core-shell styles with long-range coulomb until that is confirmed to be correct. I can do this in a separate pull request.

**Comment by evoyiatzis** [comment]
I have tested it only with the verlet run_style (in the original paper of the force field the authors used also the verlet).
About the implementation: I have not modified the settings of the Ewald summation - they should be the same with lj/cut/coul/long/cs. Should I set the respa_enable = 0 ?

**Comment by akohlmey** [comment]
> I have tested it only with the verlet run_style (in the original paper of the force field the authors used also the verlet).
> About the implementation: I have not modified the settings of the Ewald summation - they should be the same with lj/cut/coul/long/cs. Should I set the respa_enable = 0 ?

you could do a test with:
```
run_style       respa 3 1 1 dihedral 1 inner 1 4.5 5.0 middle 2 7.0 8.0 outer 3 kspace 3
```
and the differences should be very small. here are example outputs for a molecular system w/o shake at 0.25fs time step (with shake the difference is larger).
Verlet:
```
---------------- Step        0 ----- CPU =      0.0000 (sec) ----------------
TotEng   =     -5454.7635 KinEng   =      1134.9186 Temp     =       190.0857 
PotEng   =     -6589.6821 E_bond   =        16.5572 E_angle  =        36.3727 
E_dihed  =        15.5190 E_impro  =         1.9426 E_vdwl   =       792.4496 
E_coul   =     26455.4040 E_long   =    -33907.9271 Press    =     19137.6141 
---------------- Step       50 ----- CPU =      0.4060 (sec) ----------------
TotEng   =     -5451.8936 KinEng   =      1469.2983 Temp     =       246.0904 
PotEng   =     -6921.1919 E_bond   =       176.6171 E_angle  =       414.7149 
E_dihed  =        18.7401 E_impro  =         2.2861 E_vdwl   =       813.6197 
E_coul   =     25560.2676 E_long   =    -33907.4375 Press    =       -67.0848 
```
r-RESPA:
```
---------------- Step        0 ----- CPU =      0.0000 (sec) ----------------
TotEng   =     -5454.7635 KinEng   =      1134.9186 Temp     =       190.0857 
PotEng   =     -6589.6821 E_bond   =        16.5572 E_angle  =        36.3727 
E_dihed  =        15.5190 E_impro  =         1.9426 E_vdwl   =       792.4496 
E_coul   =     26455.4040 E_long   =    -33907.9271 Press    =     19137.6141 
---------------- Step       50 ----- CPU =      0.7221 (sec) ----------------
TotEng   =     -5451.8938 KinEng   =      1469.2979 Temp     =       246.0904 
PotEng   =     -6921.1917 E_bond   =       176.6170 E_angle  =       414.7148 
E_dihed  =        18.7401 E_impro  =         2.2861 E_vdwl   =       813.6197 
E_coul   =     25560.2680 E_long   =    -33907.4375 Press    =       -67.0812 
```

**Comment by akohlmey** [comment]
> About the implementation: I have not modified the settings of the Ewald summation - they should be the same with lj/cut/coul/long/cs. Should I set the respa_enable = 0 ?

if this needs changing, then probably throughout the various /cs pair styles.

**Pull request merged**
