### PR TITLE
Physically informed neural network (PINN) pairstyle submission

### PR DESCRIPTION
**Pull request by jfh3**
**Summary**

The physically Informed Neural Network (PINN) model has been added. An example PINN potential for Al is included (see potentials/Al_2020.pinn), an example LAMMPS script (see examples/USER/pinn/), as well as an .rst file with a full explanation of the model which compiles with the LAMMPS documentation. 

The package requires no external libraries and can be built with the current stable version of LAMMPS with no modification to any makefile using the following commands. 

make clean-all 
make yes-USER-PINN
make mpi

**Related Issue(s)**

**Author(s)**

Author: Ganga P Purja Pun, George Mason University, Fairfax, Virginia.
Email: gangapurjapun@gmail.com

Additional point of contact: 
James Hickman (NIST) (james.hickman@nist.gov) 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Not tested for backward compatibility.

**Implementation Notes**

This implementation does not affect any other features in LAMMPS; The code also requires NO external libraries and can be compiled "out of the box".

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

For more information, please refer to Phys Rev Mat 4, 113807 (2020).
https://journals.aps.org/prmaterials/abstract/10.1103/PhysRevMaterials.4.113807

### CODE REVIEW

**Comment by akohlmey** [comment]
@jfh3 if you have any questions about the comments to previous incarnations of this pull request or need help with implementing the requested changes, please let us know.
Please note that we currently have multiple pull requests with neural network based pair styles pending and ideally we want to do the final review and processing of all of them for the same patch release so responses may be slow at times while we focus on ongoing refactoring work in the code base.

**Comment by jfh3** [comment]
> @jfh3 if you have any questions about the comments to previous incarnations of this pull request or need help with implementing the requested changes, please let us know.
> Please note that we currently have multiple pull requests with neural network based pair styles pending and ideally we want to do the final review and processing of all of them for the same patch release so responses may be slow at times while we focus on ongoing refactoring work in the code base.

**Comment by athomps** [comment]
@jfh3 To what extend does the output from USER-PINN match the results from the non-LAMMPS code. More specifically, is the output of examples/USER/pinn consistent with the potentials published for Ta and Al in the papers listed in the header files.

**Comment by jfh3** [comment]
> @jfh3 To what extend does the output from USER-PINN match the results from the non-LAMMPS code. More specifically, is the output of examples/USER/pinn consistent with the potentials published for Ta and Al in the papers listed in the header files.

@athomps As far as I understand, the results should be identical. To test this, I ran 2500 step NVE runs using the non-LAMMPS code (PGMC from NASA) and compared the output to LAMMPS. The thermodynamic information (T, PE, KE, and pressure) appeared to be identical at each timestep (for both the Pt potential and the Al potential). The PGMC coded uses a different thermostat algorithm than LAMMPS so it is only possible to compare point-to-point in NVE. I hope this answers your question, if not, then let me know and I can try to look into it further.

**Comment by athomps** [comment]
That's a good test of the two codes.  Can you say anything about verification of the Al and Ta examples, both of which are supposed to reproduce published results?

**Comment by jfh3** [comment]
> That's a good test of the two codes. Can you say anything about verification of the Al and Ta examples, both of which are supposed to reproduce published results?

@athomps  I'm so sorry, I made a typo! I meant to say "Al and Ta" not "Al and Pt". The Al and Ta potentials uploaded to LAMMPS are the potentials from the papers. The results in the papers were primarily generated using PGMC, however, since the codes reproduce each other, the respective results should be reproducible in LAMMPS using the provided potentials files.

**Comment by akohlmey** [comment]
Pull request will be reopened/resubmitted after improvements discussed offline have been applied

**Pull request closed without merging**
