### PR TITLE
Collected small changes and fixes

### LINKED ISSUE #4045: LAMMPS-GPU Benchmark-Cuda driver error 4 in call at file ‘geryon/nvd_device.h
**Summary**
Got error about Cuda driver

mpirun --allow-run-as-root -n 32 lmp -sf gpu -pk gpu 2  -restart2data lmp.restart remap lmp_final.data

image

**LAMMPS Version and Platform**

 LAMMPS version 20230802.1 and 20230802.2

**Details**

Noted:
* I got this error when run LAMMPS version 20230802.1 and 20230802.2 with cuda
* But when run LAMMPS version 20230802.1 and 20230802.2 with opencl then no error appears , The program runs smoothly but performance will be decrease by about 20%
* When I run LAMMPS version 20220623.4 with cuda the error not appears

Compare LAMMPS version 20230802 is different from LAMMPS version 20220602 in file lib/gpu/geryon/nvd_device.h. Some function added in this file

-Version 20230802
```

void UCL_Device::clear() {
  if (_device > -1) {
    for (int i = 1; i < num_queues(); i++) 
        pop_command_queue();

#if GERYON_NVD_PRIMARY_CONTEXT
    CU_SAFE_CALL_NS(cuCtxSetCurrent(_old_context));
    CU_SAFE_CALL_NS(cuDevicePrimaryCtxRelease(_cu_device));
#else
    cuCtxDestroy(_context);
#endif
    _device = -1;
}
```

-Version 20220623

```
void UCL_Device::clear() {
  if (_device > -1) {
    for (int i = 1; i < num_queues(); i++) 
        pop_command_queue();

  cuCtxDestroy(_context);

  _device = -1;
}
```

Currently I' m using Spack to build LAMMPS

`spack graph lammps@20230802.1%aocc@4.1.0+cuda cuda_arch=90 fftw_precision=single target=zen4 +extra-dump +granular +kspace +manybody +meam +molecule +opt +replica +rigid +openmp +openmp-package  ^amdfftw %aocc@4.1.0 ^ucx@1.15.0 %aocc@4.1.0 +xpmem+verbs+ud+rc+mlx5_dv+cuda cuda_arch=80 ^openmpi@4.1.5  %aocc@4.1.0 +cuda cuda_arch=80 fabrics=ucx
`

### LINKED ISSUE #4055: [BUG] MPI errors when running NEB with multiple cores per replica
**Summary**

Running NEB with multiple cores per replica, such as 
`mpirun -np 8 lmp -partition 4x2 -in in.neb.sivac` leads to a few different MPI-related crashes.

**LAMMPS Version and Platform**

LAMMPS (2 Aug 2023) - Update 2 running on Ubuntu 20.04.6 LTS compiled with Open-MPI 4.0.3 including the MANYBODY and REPLICA package

**Expected Behavior**

The free-end NEB `end` commands should (ideally) all allow for multiple cores per replica to be run. At the moment, we are limited to a single core per replica for `end last/efirst` and `end last/efirst/middle`.

**Actual Behavior**

When running NEB with multiple cores per replica, e.g.,

`mpirun -np 8 lmp -partition 4x2 -in in.neb.sivac`

LAMMPS will return an error if no `verbosity` argument is provided to the `neb` command:

```
 *** An error occurred in MPI_Allgather
 *** reported by process [2652307457,4]
 *** on communicator MPI COMMUNICATOR 4 SPLIT FROM 0
 *** MPI_ERR_TRUNCATE: message truncated
 *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
 ***    and potentially your MPI job)
```

This issue is immediately fixed by adding any `verbosity` argument to the `neb` command.

Separately, when trying to use free-end NEB (particularly only `end last/efirst` and `end last/efirst/middle`) with multiple cores per replica will return a different MPI error:

```
 *** An error occurred in MPI_Bcast
 *** reported by process [2639265793,2]
 *** on communicator MPI_COMM_WORLD
 *** MPI_ERR_COMM: invalid communicator
 *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
 ***    and potentially your MPI job)
```

which completely prevents the use of multiple cores per replica for more complicated free-end NEB calculations. Note that this issue does not occur for `end first` or `end last`. This has been an constant issue on multiple platforms and installations.

**Steps to Reproduce**

After a clean install of LAMMPS (2 Aug 2023) - Update 2 including the MANYBODY and REPLICA package, you can run the `example/neb` case `in.neb.sivac` with the correct partition command to replicate these issues.

**Further Information, Files, and Links**

It seems that the behavior for the first error is fixed by just adding the `verbosity` keyword to the `neb` command, although it is not clear to me as to why. There is only a single MPI_Allgather that a NEB script running with the `default` print_mode should encounter which is on line 642 of `neb.cpp`.

The second error seems to be fixed by changing the communicator in line 302 of `fix_neb.cpp` from:

     if (me == 0) MPI_Bcast(&vIni, 1, MPI_DOUBLE, 0, rootworld);

to:

     if (me == 0) MPI_Bcast(&vIni, 1, MPI_DOUBLE, 0, uworld);

although this is my first time poking around the LAMMPS source code so I don't know if this is the correct/desired fix.

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request combines multiple small changes and bug fixes

**Related Issue(s)**

Fixes #4045 
Fixes #4055 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

The following individual changes are included:
- fix bug in fix style neb which was not always creating the rootworld communicator when needed
- fix bug in neb command where the print verbosity was not initialized
- remove dead code and silence compiler warnings in recently added GPU package code
- avoid the device error reported in issue #4045 (fix from @ndtrung81)
- update MDI library to version 1.4.26 which fixes some minor issues and one bug detected by coverity scan
- convert defines for numeric constants into `static constexpr` statements
- initialize static character buffers to empty strings
- modernize APIs used to look up computes and fixes
- replace references and checks for (no longer existing) fix ave/spatial with correct alternatives
- improve error messages
- remove dead code and unused keywords
- whitespace cleanup in the gpu library

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Review by jtclemm — APPROVED** [review]

**Comment by akohlmey** [comment]
@ndtrung81 can you please check out the changes to the GPU package library files and the GPU package sources.

**Comment by akohlmey** [comment]
@sjplimp the important changes for you to look at would be to neb.cpp, fix_neb.cpp (logic fixes for issue #4055) and compute_temp_sphere.cpp, compute_heat_flux.cpp, compute_stress_atom.cpp (replace `Modify::find_compute()` with `Modify::get_compute_by_id()`, and modify.h, dump.h, dump.cpp related to the "refresh" keyword and access to Modify internals.

**Comment by akohlmey** [comment]
@stanmoore1 the important changes for you to look at would be the changes to the pppm styles and KOKKOS package files.

**Review by ndtrung81 — APPROVED** [review]

**Review by sjplimp — COMMENTED** [review]
NEB changes look fine - thanks

**Pull request merged**
