### PR TITLE
Use preprocessor macros support compilers with strict OpenMP 4.x semantics

### PR DESCRIPTION
**Pull request by ExpHP**
**Summary**

- Use macros to support OpenMP in GCC 9.x.
- Reenable OpenMP by default for GCC 9.x in cmake builds.

This replaces the script `hack_openmp_for_pgi_gcc9.sh`, which required manual intervention and modifies the source tree.

**Author(s)**

Michael Lamparski, diagonaldevice@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This change is backwards compatible.

**Implementation Notes**

A python script was used to perform commit dbb4d0413283.  This will be posted in a following comment.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [ ] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated

**Further Information, Files, and Links**

See https://github.com/lammps/lammps/issues/1482

### CODE REVIEW

**Comment by akohlmey** [comment]
@ExpHP Do you have any suggestions for how to make this work without having to use C++11 features? Otherwise, we have to close this PR.

**Comment by ExpHP** [comment]
Not really, no.

**Comment by junghans** [comment]
Also see #1659

**Comment by junghans** [comment]
Now as we are on C++11, can we have another at this PR?

**Comment by ExpHP** [comment]
Since the automated changes in the second commit are almost certainly out of date by now, I'll rebase this on top of master and regenerate them.

**Comment by akohlmey** [comment]
this now needs to be updated for the latest cmake related changes.

**Comment by akohlmey** [comment]
@ExpHP I have submitted a pull request into your fork that has some updates and corrections that need to be included before we can merge this pull request into LAMMPS. It looks otherwise OK and has been tested successfully with a variety of compilers and versions.

**Pull request merged**
