### PR TITLE
new reset_mol_ids command

### LINKED ISSUE #2224: [BUG] reset_ids segfaulting with "sort yes"
**Summary**

rest_ids leads to a segfault when using the "sort yes" option.

**LAMMPS Version and Platform**

LAMMPS (30 Jun 2020)
Linux Ubuntu (18.04), compiled with cmake  (3.13.2) and Gnu Compiler (7.5.0)

**Expected Behavior**

Reset atom IDs for the system, including all the global IDs stored for bond, angle, dihedral, improper topology data. This will create a set of IDs that are numbered contiguously from 1 to N for a N atoms system. If the sort keyword is used with a setting of yes, then the assignment of new atom IDs will be the same no matter how many processors LAMMPS is running on. This is done by first doing a spatial sort of all the atoms into bins and sorting them within each bin. Because the set of bins is independent of the number of processors, this enables a consistent assignment of new IDs to each atom.

**Actual Behavior**

segfault if option "sort yes"

**Steps to Reproduce**
##############################################
# LAMMPS atomistic input script
units           real
#units		metal
atom_style      full

# Interaction potential definition
pair_style      lj/cut/coul/cut 5
#pair_style	 airebo 2.5 1 0

region          box block 0 20   0 5   0 5
create_box      1 box
create_atoms    1 single 2 2.5 2.5
create_atoms    1 single 4 2.5 2.5
create_atoms    1 single 6 2.5 2.5
create_atoms    1 single 8 2.5 2.5

mass            * 12.0
pair_coeff      * * 0.05400 4.01000
#pair_coeff	* * /opt/lammps_git_master/potentials/CH.airebo	C

reset_ids       sort yes
############################

**Further Information, Files, and Links**

without "sort yes" or setting "sort no" lammps is not segfaulting
[lammps_reset_ids.zip](https://github.com/lammps/lammps/files/4902745/lammps_reset_ids.zip)

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

New `reset_mol_ids` command, which uses compute fragment/atom and compute chunk/atom to perform a walk of the bonds within each current molecule and then relabel the molecule IDs contiguously from 1 to N.

**Related Issues**

This supersedes and thus closes #2104
Fixes #2224 

**Author(s)**

Steve Plimpton (SNL), Jake Gissinger (U Colorado), Axel Kohlmeyer (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This optimizes the compute fragment/atom command.  By using the special bonds list to walk the bond topology.  This means it can no longer be used when bonds have been broken by the `bond_style quartic` command, since it doesn't update the special bonds list.  It's possible this can be re-enabled at some point.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey Please check on how I used the fmt and string classes in reset_mol_ids.cpp.  Not sure I did it properly.

**Comment by sjplimp** [comment]
@jrgissing If you want to use this as a periodic option in other commands, like fix bond/react, that could be done by making reset_mol_ids be structured like the write_restart class.  Where it can be both a stand-alone command and invoked periodically by the Output class.  I suggest you do that after this PR is merged.

**Comment by akohlmey** [comment]
@sjplimp this is now updated to the latest master and I've added a (baseline) unittest tool for it (will try to make it a habit for most if not all of these kinds of additions). This also fixes a bug in `reset_ids` that was exposed by the tester tool.

**Comment by sjplimp** [comment]
@akohlmey Added the offset keyword (see the doc page).  Please retry your test cases now.  Also did you want
to change reset_ids --> reset_atom_ids?

**Comment by akohlmey** [comment]
> @akohlmey Added the offset keyword (see the doc page). Please retry your test cases now. Also did you want
> to change reset_ids --> reset_atom_ids?

I was thinking about it. It would be a logical step to improve consistency, and if we want to do it, it better be now while the command is relatively new. For a transition period we could stay backward compatible, by silently accepting `reset_ids` by just having two command style macros in the header,and then in a year or two drop it. Docs and files would be renamed right away.

**Comment by sjplimp** [comment]
@akohlmey Keeping both old/new command names for some period of time is fine also.
But in this case I think it's also fine to just make the change.  B/c it's probably not a 
widely used command.

**Comment by akohlmey** [comment]
> @akohlmey Keeping both old/new command names for some period of time is fine also.
> But in this case I think it's also fine to just make the change. B/c it's probably not a
> widely used command.

your call.

**Comment by akohlmey** [comment]
@sjplimp this has now all features working the way I would expect them to work. Also tests are implemented and pass (for now). Not 100% happy with the implementation, but I didn't see a simpler way. To make single atoms have a molecule ID of 0 turned out to be a bit more complex than expected, as there are multiple issues to deal with. Please have a look and perhaps update the docs a bit more or make some updates/tweaks where you feel they could be applied.

I better stop now before I get an idea for an even crazier change which requires even more work to implement it.

**Comment by akohlmey** [comment]
@jrgissing @sjplimp this has now a completed tester (100% code coverage) and has everything that I would be looking for in this kind of command (and a bit more).

**Comment by akohlmey** [comment]
> [compute_fragment_atom.zip](https://github.com/lammps/lammps/files/4907686/compute_fragment_atom.zip)
> compute fragment/atom seems to be faster when you first communicate specials, so that they include info for ghosts, as e.g. done in #2104 (again testing on 200K nylon example)

@sjplimp can you check this out? we could either merge the PR as is and then potentially have another PR with the performance optimization or just wait until you checked it out and either added it or not.

**Comment by sjplimp** [comment]
@akohlmey Let's just merge this.  I'll look at the @jrgissing optimization
later.

**Pull request merged**
