### PR TITLE
Fixes issue from Feb 2021 GPU package update for tersoff styles using multiple types

### PR DESCRIPTION
**Pull request by wmbrownIntel**
**Author(s)**

Mike Brown (Intel)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No.

**Implementation Notes**

Only modifies tersoff files in GPU library directory

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@ndtrung81 with this change nearly all pair styles that have a /gpu version pass the unit test runs with double, mixed, and single precision (there is are (global) empirical factors that scale the precision requirements from the YAML files accordingly). The test runs are done with neighbor lists on the CPU and on the GPU. CUDPP and MPS are disabled.
The following tests are still skipped for the GPU package:
- all styles with long-range coulomb tabulation (I understand the GPU styles don't need/use it, so only the inputs without are checked)
- the dpd variants (different random number streams between GPU and CPU, so they cannot match)
- hybrid pair styles (have not tried your PR since it is still listed as Draft)
- lj/charmm/coul/charmm (see the discussion thread at PR #2308)
- tersoff and variants that use the optional "shift" keyword (that feature was implemented recently and has not been ported to the GPU package or USER-INTEL or KOKKOS)

**Comment by akohlmey** [comment]
With commit bb7931c it is now possible to also run the pair style test for lj/charmm/coul/charmm on the GPU.

**Comment by ndtrung81** [comment]
@wmbrownIntel thank you very much for resolving the issues with tersoff*/gpu and lj/charmm/coul/charmm/gpu.
@akohlmey thanks for sending the reproducer for the issue in lj/charmm/coul/charmm/gpu, and for the updates with the gpu unit tests. I will update the draft PR with neighbor builds with pair hybrid with these latest changes, and try to wrap it up soon.

**Comment by akohlmey** [comment]
@ndtrung81 @sjplimp  I would like to merge this PR ASAP. Any objections, concerns?

**Review by ndtrung81 — APPROVED** [review]

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
