### PR TITLE
Collected small fixes and updates

### LINKED ISSUE #3920: [BUG] Fix_Plumed documentation example contains typo
**Summary**

In the documentation for the plumed fix, the example in https://docs.lammps.org/fix_plumed.html#examples seems to be slightly incorrect. Instead of `fix pl all plumed all plumed plumedfile plumed.dat outfile p.log`, the example should instead be `fix pl all plumed plumedfile plumed.dat outfile p.log`
My guess is that `all plumed` was accidentally copy-pasted twice when the documentation was being written.

The source code for this documentation is located at: https://github.com/lammps/lammps/blame/develop/doc/src/fix_plumed.rst

**LAMMPS Version and Platform**

This bug is affecting the most recent version of the LAMMPS online manual, https://docs.lammps.org/fix_plumed.html
Based on the commit history for fix_plumed.rst, it looks like this typo in the example has existed for quite a while.

**Expected Behavior**

As described in the manual, the syntax should be `fix ID group-ID plumed keyword value ...`
https://docs.lammps.org/fix_plumed.html

Thank you for looking into this small issue.

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request combines multiple small fixes and updates that don't warrant pull requests on their own.

**Related Issue(s)**

See this discussion for the REBO neighbor list change: https://matsci.org/t/lammps-exiting-without-error-and-without-results/50684
Fixes #3920 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

The following individual changes are included:
- workaround for an issue with neighbor list trimming when using REBO pair styles as a hybrid sub-style. With trimming, the neighbor list entries for ghost atoms are not initialized.
- updates for building tools and removal of references to tools that have been removed
- updates for LAMMPS shell to adjust lists of possible completions to the current state of LAMMPS
- ignore reading `atom->map_user` from binary restart files so atom_modify map will be honored when reading restarts.
- various updates and corrections for the documentation

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [x] A package specific README file has been included or updated

### CODE REVIEW

**Comment by akohlmey** [comment]
@stanmoore1 please have a look at the change to pair_airebo.cpp. It seems the neighbor list trimming is removing neighbors too aggressively for building the REBO lists. Those seem to be missing the data for neighbors of ghost atoms.
Changing the default works around the issue, but does not really resolve it.

**Comment by stanmoore1** [comment]
@akohlmey do you have a reproducer for the REBO case?

**Comment by akohlmey** [comment]
> @akohlmey do you have a reproducer for the REBO case?

Please check out the post in the MatSci forum that is mentioned above.

**Comment by stanmoore1** [comment]
@akohlmey can you update this compute to the new name:
https://github.com/lammps/lammps/blob/develop/src/KOKKOS/Install.sh#L99-L100

**Comment by akohlmey** [comment]
> @akohlmey can you update this compute to the new name: https://github.com/lammps/lammps/blob/develop/src/KOKKOS/Install.sh#L99-L100

done

**Comment by stanmoore1** [comment]
Thank you!

**Review by sjplimp — APPROVED** [review]

**Comment by akohlmey** [comment]
> @akohlmey do you have a reproducer for the REBO case?

@stanmoore1 looks like the same issue also happens to pair style extep as reported in issue #3940. The common denominator seems to be the request of a neighbor list with neighbors for ghost atoms.

**Comment by stanmoore1** [comment]
@akohlmey the trim list issues should be fixed by #3941, can you revert the workaround you put in?

**Comment by akohlmey** [comment]
> @akohlmey the trim list issues should be fixed by #3941, can you revert the workaround you put in?

Will check it out. ;-)

**Pull request merged**
