### PR TITLE
implementation of an "ellipsoidal" region option

### PR DESCRIPTION
**Pull request by evoyiatzis**
Based on the code of the region_sphere and the code described in https://www.geometrictools.com/Documentation/DistancePointEllipseEllipsoid.pdf, an option for axis-aligned ellipsoidal regions has been implemented

**Summary**

**Related Issue(s)**

**Author(s)**

Evangelos Voyiatzis @ NovaMechanics Ltd (evoyiatzis@gmail.com)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by evoyiatzis** [comment]
It is not clear to me what the value of the radius of the contact structure should be

**Comment by sjplimp** [comment]
@evoyiatzis Evangelos - thanks for contributing this new region to LAMMPS.  I made some edits to the doc page, just cosmetic changes to the source files.  Am I correct that although the ellipsoid is defined as axis-aligned if can be rotated by the "rotate" keyword, either statically or dynamically?  I think that should be the case.  Also it might be nice to add an example script to the examples/friction dir that replaced the hemispherical asperities with half-ellipsoids.  To demonstrate how this works.

**Comment by sjplimp** [comment]
Also, just checking, are we free to distribute the Boost code in region_ellipsoid.cpp with LAMMPS ?

**Comment by evoyiatzis** [comment]
> @evoyiatzis Evangelos - thanks for contributing this new region to LAMMPS. I made some edits to the doc page, just cosmetic changes to the source files. Am I correct that although the ellipsoid is defined as axis-aligned if can be rotated by the "rotate" keyword, either statically or dynamically? I think that should be the case. Also it might be nice to add an example script to the examples/friction dir that replaced the hemispherical asperities with half-ellipsoids. To demonstrate how this works.

Thanks for the review and the edits you made. Indeed, when the region is created initially it is strictly axis-aligned. The functionality of the "rotate" keyword comes from the Region::rotate (it is the function for the rotation of the particles belonging to region).  To my understanding "rotate" is applicable to all derived region styles. I have verified that with a simple test script.

**Comment by evoyiatzis** [comment]
> Also, just checking, are we free to distribute the Boost code in region_ellipsoid.cpp with LAMMPS ?

The full text of the license is here https://www.boost.org/LICENSE_1_0.txt
I am not an expert - my gut feeling is that you are free to distribute the code under the boost license.

**Comment by akohlmey** [comment]
> > Also, just checking, are we free to distribute the Boost code in region_ellipsoid.cpp with LAMMPS ?
> 
> The full text of the license is here https://www.boost.org/LICENSE_1_0.txt I am not an expert - my gut feeling is that you are free to distribute the code under the boost license.

https://en.wikipedia.org/wiki/Boost_(C%2B%2B_libraries)#License

**Comment by akohlmey** [comment]
@evoyiatzis please update to the latest upstream code from the devel branch and apply the following commands in the src folder:
```
make fix-whitespace
make fix-permissions
make fix-homepage
make fix-errordocs
```
and apply any resulting changes.

**Comment by akohlmey** [comment]
Please also note our updated suggestions for error messages: https://docs.lammps.org/latest/Modify_style.html#error-or-warning-messages-and-explanations-preferred

**Comment by akohlmey** [comment]
> Please also note our updated suggestions for error messages: https://docs.lammps.org/latest/Modify_style.html#error-or-warning-messages-and-explanations-preferred

No more need. I just updated the code myself.

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
