### PR TITLE
cmake: add DOWNLOAD_MSCG option

### PR DESCRIPTION
**Pull request by junghans**
Thanks to @tdlafage

@akohlmey you might want to use mscg-1.7.3.1 in the Makefile for MSCG as well.

### CODE REVIEW

**Comment by junghans** [comment]
@akohlmey @sjplimp is there are reason why we include the actual code of linalg and not just download it via a `Install.py`?

**Comment by akohlmey** [comment]
@junghans lib/linalg predates the Install.py scripts by many years. it also predates the simplified build procedure that BLAS/LAPACK offer now and it was added at a time, where the subset of BLAS/LAPACK required was **much** smaller.

**Comment by junghans** [comment]
@akohlmey maybe we should change it then (not in this PR though).

**Comment by junghans** [comment]
Assigned to @akohlmey to make use of mscg-1.7.3.1 in its `Install.py`.

Make linalg a real external library should be done in a later PR.

**Pull request merged**
