### PR TITLE
Update GPU CMake and Makefile scripts for ROCm v3.5

### PR DESCRIPTION
**Pull request by Vsevak**
**Summary**

This PR updates CMake and Makefile scripts (#1863) for the GPU module to be working with current AMD ROCm version 3.5.
Also, this PR includes a small memory management fix for lj/cut/tip4p/long pair style (#1776).

**Author(s)**

Vsevolod Nikolskiy (thevsevak@gmail.com, @Vsevak)
International Laboratory for Supercomputer Atomistic Modelling and Multi-scale Analysis
HSE University, Moscow, Russia

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

~~This update will probably break the building with previous versions of AMD ROCm, which are now deprecated.~~
I try to keep the compatibility with the deprecated compiler, *but* I didn't test it since I don't have such a platform right now.

**Implementation Notes**

I changed the compiler keys to be compatible with the current HIP-Clang compiler instead of the deprecated ones. CMake and Makefile have been tested on a machine with ROCm v3.5 and AMD GPUs.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by arghdos** [comment]
Looks better than mine did :)

**Comment by Vsevak** [comment]
@arghdos Thanks!

**Comment by rbberger** [comment]
I will test it now. I lost a lot of time trying to get the ROCm container to work again. Turns out that doing `apt-get upgrade` inside of the `rocm/dev-ubuntu-18.04:3.5` container breaks the build system due to bad symlinks (`/opt/rocm/` not being updated).

**Comment by arghdos** [comment]
>Turns out that doing apt-get upgrade inside of the rocm/dev-ubuntu-18.04:3.5 container breaks the build system due to bad symlinks (/opt/rocm/ not being updated).

Ugh... sorry about that, the 3.5.1 update has been causing issues on upgrade :/.
Typically what I do is to overwrite the rocm source with a fixed build, such that it won't upgrade ROCm until I tell it to.  E.g., for 3.5.0, you can use:

`echo 'deb [arch=amd64] http://repo.radeon.com/rocm/apt/3.5/ xenial main' | sudo tee /etc/apt/sources.list.d/rocm.list`

(the full list is here: http://repo.radeon.com/rocm/apt/)

Or if you're doing a docker-build, you can use something like:

```
FROM ubuntu:18.04

# Register the ROCM package repository, and install rocm-dev package
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl libnuma-dev gnupg \
  && curl -sL http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | apt-key add - \
  && printf "deb [arch=amd64] http://repo.radeon.com/rocm/apt/3.5/ xenial main" | tee /etc/apt/sources.list.d/rocm.list \
  && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  sudo \
  libelf1 \
  rocm-dev \
  build-essential && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
```
(adapted from here: https://hub.docker.com/r/rocm/dev-ubuntu-18.04)

**Comment by rbberger** [comment]
Had more issues, filed them here: https://github.com/RadeonOpenCompute/ROCm/issues/1167. Ended up creating a clean image based on `ubuntu:18.04`.

**Comment by arghdos** [comment]
Thanks, I sent a ping to the maintainer of the docker images as well.

**Comment by rbberger** [comment]
Ok, so I'll keep the AMD ROCm container based on vanilla ubuntu 18.04 for now, since building it from scratch seems to be the safer option. Reason: `apt upgrade` on the `rocm/dev-ubuntu-18.04` containers currently produces broken setups, since symlinks aren't updated and dependencies aren't reinstalled. If the release of 3.5.2 (or whatever follows) is done the same way as 3.5.0 -> 3.5.1 the container would break again.

Anyway, the `GPU_API=HIP` version now compiles again in the container, so I'll approve this PR.

As much as I would like to, I can't do any run tests because my development system (Arch, Linux 5.7.5-arch1-1, Navi 10, Radeon 5700 XT) isn't really supported. This is the main source of why it's hard for us to really look into this ourselves.

**Comment by ndtrung81** [comment]
@Vsevak @rbberger thanks very much for your work!

**Pull request merged**
