### PR TITLE
cmake: Add -restrict for Intel compilers

### PR DESCRIPTION
**Pull request by wesbarnett**
Some packages (USER-OMP, OPT, and USER-INTEL) require the -restrict flag when using the Intel compiler.

## Purpose

Adds an if statement in the CMakeLists.txt to see if the user is using the Intel compiler and adds the `-restrict` flag if so.

## Author(s)

James W. Barnett, Department of Chemical Engineering, Columbia University

## Backward Compatibility

Nothing breaks.

## Implementation Notes

I ran cmake with different compilers and packages to see that the flag was added (or not added) correctly.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by wesbarnett** [comment]
I actually don't know if other packages require the `-restrict` flag. These are the three I found documented, but I may have missed others.

**Comment by akohlmey** [comment]
@wesbarnett regardless of whether packages require it or not. it is safe to _always_ use the `-restrict` flag when compiling with the intel compilers. FWIW, the documentation of the `USER-INTEL` package has some useful information to get the most out of the intel compilers and has recommendations for different version. please note, that there is a pending update in PR #674 with more info.

**Comment by wesbarnett** [comment]
Hey @akohlmey, thanks. Are you suggesting some of those flags be added in this PR?

**Comment by akohlmey** [comment]
@wesbarnett,

> Are you suggesting some of those flags be added in this PR

i am not a cmake scripting expert. if there are ways to determine which set of flags are supported by the compiler version at hand and which kind of hardware you are compiling for, there may be a benefit. but i think that is something best left to individual users. with the cmake x11 or text mode gui, these flags can be easily set manually. the major difference here is that -restrict is required for intel compilers, the rest are optional and can result in better performance (or not).

**Comment by wesbarnett** [comment]
Cf. #616.

**Pull request merged**
