### PR TITLE
new stress/mop and stress/mop/profile computes for USER-MISC 

### PR DESCRIPTION
**Pull request by RomainVermorel**
## Purpose

This pull request provides the stress/mop and stress.mop/profile compute styles. These are LAMMPS compute styles that calculate components of the local stress tensor using the method of planes as described in the paper by Todd et al. (B. D. Todd, Denis J. Evans, and Peter J. Daivis: "Pressure tensor for inhomogeneous fluids", Phys. Rev. E 52, 1627 (1995)).

## Author(s)

The persons who created these files are Laurent Joly at University of Lyon 1 and Romain Vermorel at University of Pau and Pays de l'Adour.

Laurent Joly
Institut Lumière Matière
Université Lyon 1 et CNRS
43 boulevard du 11 novembre 1918
69622 Villeurbanne Cedex
e-mail: laurent.joly@univ-lyon1.fr

Romain Vermorel
Laboratory of Complex Fluids and their Reservoirs (LFCR)
Université de Pau et des Pays de l'Adour
Avenue de l'Université 
64012 Pau
e-mail: romain.vermorel@univ-pau.fr

## Backward Compatibility

No changes in the pull request break backward compatibility.

## Implementation Notes

We verified the computations of the local stress tensor by comparing our results to some simple configurations for which abundant data is found in the literature (bulk Lennard-Jones fluid, Lennard-Jones fluid confined in a slit pore, etc). We benchmarked the code in serial and parallel, for various boundary conditions and spatial decomposition between processors. 

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x ] The feature or features in this pull request is complete
- [ x] Suitable new documentation files and/or updates to the existing docs are included
- [ x] One or more example input decks are included
- [ x] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by akohlmey** [comment]
@RomainVermorel thanks for your contribution. I've made a bunch of cosmetic changes to follow the LAMMPS style conventions and moved files from the source folder into the examples and doc tree. I've also merged to two mostly identical doc pages into one describing both commands. Please see my review message for and issue that needs fixing or explaining and a suggestion for more clarity.

**Comment by akohlmey** [comment]
@RomainVermorel please note, that you didn't "rename" but just added new files. I had to do a significant amount of cleaning up, removing obsoleted files and changing doc entries. I have been doing this, since this is your first contribution. In the future, please make a better effort and particularly consider following the  github tutorial in the LAMMPS manual more closely. Starting with not doing development in the "master" branch, but using a feature branch (after your code is merged, it is probably best to start over cleanly and drop your LAMMPS fork and make a new one, but don't do that yet).

As for the renaming of the package, this is a question to be answered by our mastermind @sjplimp 
My personal perspective is, that renaming the package to something more generic implies, that you also volunteer to maintain this package. A possible alternative would be to move your contribution to the USER-MISC package.

As for differences between single and multi-processor, i see them for *all* generated files. Please check out the files uploaded to the pull request on github in the `mop-results.tar.gz` tarball.
[mop-results.tar.gz](https://github.com/lammps/lammps/files/2351228/mop-results.tar.gz)

**Comment by akohlmey** [comment]
moved the styles of USER-MISC. @rbberger it is all yours now

**Comment by RomainVermorel** [comment]
@akohlmey sorry for the inconvenience caused, I am new to GitHub... I must have overlooked the part of the tutorial on the feature branch. Next time I will pay more attention.

I suppose the differences between serial and parallel runs resulted from the initialization of the system in the example input script. We indeed used some random procedures for deleting some atoms and creating initial velocities, which led to different results depending on the number of processors. 

We have prepared a new example input script and a data file to make sure the initial conditions are the same, irrespective of the number of processors. This simulation provides the same output data with single and multi-processors. Please check out these new input scripts in the attached file and let me know if it solves the issue.  

[mop_example_20180906.tar.gz](https://github.com/lammps/lammps/files/2356446/mop_example_20180906.tar.gz)

**Pull request merged**
