### PR TITLE
Nose-Hoover simulations with fixed volume and flexible cell shape

### PR DESCRIPTION
**Pull request by stevenvdb**
**Summary**

This PR enhances LAMMPS with the (N, V, **sigma**<sub>a</sub>=0, T) ensemble, in which the cell volume and the deviatoric stress are controlled, but the cell shape and the isotropic pressure are unconstrained. The theoretical background was developed by [Rogge et al.](https://pubs.acs.org/doi/10.1021/acs.jctc.5b00748)

**Author(s)**

Steven Vandenbrande, Center for Molecular Modeling, Ghent University

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This PR should not break backward compatibility

**Implementation Notes**

This ensemble can be considered a variant of the Nose-Hoover style NPT ensemble that is implemented in LAMMPS. The only difference is that the momentum tensor associated with the barostat particles (the _omega_dot_ array in fix_nh.cpp), should be kept traceless. This is why simulations within this ensemble are requested using a command very similar to the existing _npt_ command, but with the keyword _fixvolume yes_.

An example is included in the _examples/USER/yaff/mil53al_pressure_profile_ directory. It was checked that the volume was indeed constant during simulations, and that the average isotropic pressures correspond to published results.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [x] One or more example input decks are included

### CODE REVIEW

**Comment by stevenvdb** [comment]
@athomps Those are some good points. I forgot to take the change in degrees of freedom (pdof in the code) into account. It indeed turns out that the conserved quantity is not conserved. I will need some time to look into this and report back here when it's all fixed and tested properly.

**Comment by akohlmey** [comment]
@stevenvdb can you please comment on the status of this PR? Is this ready to be re-reviewed?

Please also note, that there may be more changes required to classes that are derived from `FixNH` (e.g. for extended particles or for KOKKOS) or in case we merge the changes from #1026

**Comment by akohlmey** [comment]
@athomps @stevenvdb this is waiting now for 3 months on some feedback about whether this pull request is ready for inclusion or if there are still steps missing.

...and - as I already mentioned - all changes to fix_nh.cpp have to either be propagated to the various derived classes or tests added, that error out when flags are set that are not supported and will have no effect in those derived classes.
I can help to resolve the merge conflict on the documentation and update the PR to the latest master (in order to make it compatible with the ongoing transition of the documentation sources from .txt to .rst).

**Comment by athomps** [comment]
@stevenvdb indicated on June 26 that this feature does not conserve the conserved quantity.  While this is probably due to some small difference between the implementation and the theory, and it may not affect results in typical use cases, it does not make sense to add this feature if it is known to be incorrect.

**Pull request closed without merging**
