### PR TITLE
MathSpecial::fm_exp: fix return value on ppc64

### PR DESCRIPTION
**Pull request by junghans**
Found on OpenSuse

### CODE REVIEW

**Comment by martok** [comment]
The version ported from MEAM was relying on dead code elimination for the second return statement, the code after 15a960056 is indeed bad.
But I would prefer something more compact, like this:
```
double MathSpecial::fm_exp(double x)
{
#if defined(__BYTE_ORDER__) && (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)
    return exp2_x86(FM_DOUBLE_LOG2OFE * x);
#else
    return ::exp(x);
#endif
}
```

**Comment by junghans** [comment]
@martok: Done

**Comment by akohlmey** [comment]
@junghans done where?

**Comment by martok** [comment]
@akohlmey Forced push, apparently doesn't get re-sorted chronologically.

**Comment by junghans** [comment]
Patch added to version 
20180316 in OpenSuse: https ://build.opensuse.org/request/show/592170

**Pull request merged**
