### PR TITLE
Misc minor patches/features in BPM/Granular packages

### PR DESCRIPTION
**Pull request by jtclemm**
**Summary**

This PR includes several minor patches or requested features to the BPM and GRANULAR packages including:

1. Adding option to normalize forces in BPM bond styles by reference lengths
2. Adding missing factor of 1/r in the BondBPMRotational->single() method (reported on Matsci)
3. Unifying the syntax for BPM bond styles
4. Adding flag to prevent 2x mixing of coefficients in pair granular (reported on Matsci)
5. Fixing various typos in doc pages

**Related Issue(s)**

Matsci forum topics
https://matsci.org/t/using-bpm-to-simulate-beam/48584/5
https://matsci.org/t/about-mixing-of-coefficients-of-pair-style-granular/48694/7

**Author(s)**

Joel Clemmer (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Input scripts for BPM bond styles and granular pair styles with mixing coefficients may need to be updated.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

NA

### CODE REVIEW

**Review by stanmoore1 — APPROVED** [review]
I approve

**Comment by jtclemm** [comment]
Thanks Stan for the review.

The iffiest part of this PR is the revised coefficient mixing in pair granular, which Dan can confirm whether or not is correct.

**Comment by akohlmey** [comment]
> The iffiest part of this PR is the revised coefficient mixing in pair granular, which Dan can confirm whether or not is correct.

So in other words, this should not be merged until @dsbolin has confirmed or requests changes?

**Comment by akohlmey** [comment]
@jtclemm please note that there is a merge conflict with `src/GRANULAR/gran_sub_mod_normal.h`

**Comment by jtclemm** [comment]
> So in other words, this should not be merged until @dsbolin has confirmed or requests changes?

Yes, Dan should review the PR before it is merged.

**Review by dsbolin — APPROVED** [review]
Looks good to me. Thanks @jtclemm !

**Pull request merged**
