### PR TITLE
fix_bond_create_updated

### PR DESCRIPTION
**Pull request by aminaramoon**
Here is a pull request for fix_bond_create with added features.

This update allows users to dynamically allocate angle, bond, or dihedral types during cross-linking, opposed to the previous code that would allow only for a static type of coordinates.

This update is fully backward compatible, with minimal changes to the main class.

### CODE REVIEW

**Comment by aminaramoon** [comment]
Please let me know if you've checked the codes, or you need to modify it ? thanks

**Comment by akohlmey** [comment]
We've been busy all week with the LAMMPS tutorial at Temple. https://sites.google.com/site/templesummermd/
The code looks now like it is worth checking it out and testing it. It will have to wait until next week, though. I've been briefly talking to Tim Sirk, who wrote a significant chunk of fix bond/create and who apparently has programmed an extension to fix bond/create which can do similar things, but is more general. So we'll have to figure out, how to sort this out cleanly.

**Comment by aminaramoon** [comment]
great! Thanks

**Comment by aminaramoon** [comment]
Also my code code "type_detector" will be used to create chains, and macromolecules in a new class caleed "create_chains" that I will submit sometimes next week.

**Comment by akohlmey** [comment]
What I can see after looking at the patch more closely is the following:
- it still doesn't follow the common source code formatting style (2 blanks per level of indentation, no tabs). several other formatting choices are different from adjacent code as well
- there seems to be memory leaks, when short int arrays are allocated with new
- fix_bond_create.h should not include type_detector.h. instead a forward declaration should be used and type_detector.h only included in the .cpp file. type_detector.h includes other include files (why does it include pointers.h?), which would pollute the name space even more.
- there are typos in the added documentation and in added code (e.g. varialbe, tokentize)
- TypeDetector class should use an enumerator and the corresponding symbolic constants instead of numbers to indicate bonds/angles/dihedrals/impropers.
- the TypeDetector class should be placed into the LAMMPS_NS namespace
- type_detector.h should only include header files it requires, that seem to be only vector and stdlib.h

**Comment by aminaramoon** [comment]
I will fix them and push the shortly.
Thanks

**Comment by aminaramoon** [comment]
I have fixed the forward declaration issues, cleaned up the imports, added enum for bond, angle, and dihedral and fixed the potential memory leak issue.
corrections to doc and code have been made to resolve typos and grammatical mistakes.

**Comment by akohlmey** [comment]
Thanks for being so patient and helping with getting the code into a good shape and consistent with the rest of LAMMPS. This is much appreciated. I will take it from here. There are a few minor improvements, that i have in mind, that are easier for me to check out, rather than trying to explain in a comment box.

**Comment by aminaramoon** [comment]
thanks you as well. I understand your concern for keeping the code in the consistent shape and format.

**Comment by akohlmey** [comment]
unfortunately, the changes have grown beyond my initial expectations. there are some logical inconsistencies, several memory leaks, leftover whitespace and indentation issues, lack of testing in some cases and overly complex code in other places.

**Comment by aminaramoon** [comment]
Can you name them here, so I can fix them asap and send them to you. also if you have a guideline for formatting codes, jus send me the link, I will reformat the code and send it to you.

Thanks.

**Comment by akohlmey** [comment]
i've already made the changes. i've created a pull request in your github fork so you can review them. Mind you, i have not yet tested them.

**Comment by aminaramoon** [comment]
I will check them now.

**Comment by aminaramoon** [comment]
So, I did check the codes, the type_dector_refactor commit seems to be fine, except one harmless bug which I will fix. The fix_bond_create.cpp reformatting has a couple of inconsistencies with the new type_detector class and also memory management issues in the classes where local_types are deleted. They need to be deleted at the end of the method to avoid null argument exception error. Do you want me to fix them or should I list them here !

**Comment by aminaramoon** [comment]
Or since there are only a few places that need change, I can leave comments where it is needed.

**Comment by akohlmey** [comment]
whatever you prefer. you can add comments in the source or you can merge my pull request, make the changes and update the pull request here.

**Comment by aminaramoon** [comment]
It is not possible for me to merge it. All the checks failed. any suggestion ?

**Comment by aminaramoon** [comment]
I resolved the memory corruption problem that was caused by deleting the int array in make angle, dihedral and improper.

made small changes to type detector, and solved a small harmless bug.

fix_bond_create.cpp is not consistent with the new type_detector
formatting should be correct.

I compiled and tested the code with 400 processors. it does run just fine, with no problem.

**Comment by akohlmey** [comment]
This is mostly useless, since you didn't first merge the missing commit to fix bond/create that i submitted as a pull request to your github fork. Also, if the change you made in order to solve a memory corruption, that part of the corresponding part of the code in your TypeDetector class is very badly designed and not acceptable.

**Comment by aminaramoon** [comment]
I did merge all the commits as far as I remember, I don't know what part is missing. Any suggestion ?!

The memory corruption was happening in fix_create_bond.cpp class, not in type_detector. It was happening in the part that you added "delete[] ang_type" inside the loops, but it had to be called outside of the loop to remove the array for cases that the condition for entering the loop is not satisfied.

**Comment by akohlmey** [comment]
The pull request is still listed as unmerged and due to your recent changes, it can no longer be merged cleanly. https://github.com/aminaramoon/lammps-1/pull/2

I still see that some of my changes are missing and code that i kicked out for being redundant. Like the completely useless XXXXdynflag variables. all they provide is the information whether the XXX_detector pointers are NULL or not. You can test for that directly.

**Comment by aminaramoon** [comment]
I think when I merged it last night, the codes were divergent and it just created a merge commit and detached it from HEAD. 

Do you want me to resolve the conflicts ? 

from the memory corruption, it doesn't happen in type_detector class, it was happening when the array was deleted inside the fix_bond_create. I can comment the type_detector class for more clarification.

**Comment by aminaramoon** [comment]
I resolved the conflict in the missing commit, merged it, and fixed a couple of small bugs, compiled and ran it.

Please let me know if you need something.

**Pull request merged**
