### PR TITLE
cmake: added ccache support

### PR DESCRIPTION
**Pull request by junghans**
## Purpose

Make the use of `ccache` easy.

## Author(s)

@junghans

## Backward Compatibility

Yes

## Implementation Notes

Nothing special

## Post Submission Checklist

- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

https://ccache.samba.org/performance.html

To test this:
```
cmake -DENABLE_CCACHE=ON ../cmake
ccache -z
time make
ccache -s
make clean
time make
ccache -s
```

### CODE REVIEW

**Comment by akohlmey** [comment]
I don't understand the need for this. Can you please elaborate which specific use cases this covers? From my understanding, when ccache is properly installed, it is automatically active. Been using it for **years** and it seems to be working fine with CMake out of the box, too.
```
[akohlmey@silence examples]$ which gcc
/usr/lib64/ccache/gcc
[akohlmey@silence examples]$ which clang
/usr/lib64/ccache/clang
```
The symlinks point to supported compilers and everything is transparent and "just works(tm)" on my desktop:
```
-- <<< Build configuration >>>
   Build type       RelWithDebInfo
   Install path     /home/akohlmey/.local
   Compilers and Flags:
   C++ Compiler     /usr/lib64/ccache/c++
       Type         GNU
       Version      8.2.1
   C++ Flags         -O2 -g
   Defines          LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;FFT_FFTW;LMP_PYTHON;LAMMPS_JPEG;LAMMPS_PNG;LAMMPS_GZIP;LAMMPS_FFMPEG
-- Fortran Compiler /usr/bin/gfortran
           Type     GNU
           Version  8.2.1
   Fortran Flags     -O2 -g -DNDEBUG
-- C Compiler /usr/lib64/ccache/cc
     Type     GNU
     Version  8.2.1
     C Flags   -O2 -g -DNDEBUG
-- Static libraries  
-- Link libraries: /usr/lib64/mpich/lib/libmpicxx.so;/usr/lib64/mpich/lib/libmpi.so;/usr/lib64/libfftw3.so;/usr/lib64/libpython2.7.so;/usr/lib64/libjpeg.so;/usr/lib64/libpng.so;/usr/lib64/libz.so;/usr/lib64/libvoro++.so;m;meam;poems;gfortran;gcc_s;gcc;quadmath;c
-- Using mpi with headers in /usr/include/mpich-x86_64 and /usr/lib64/mpich/lib/libmpicxx.so;/usr/lib64/mpich/lib/libmpi.so
-- Using FFTW3 as FFT
-- Configuring done
-- Generating done
-- Build files have been written to: /home/akohlmey/compile/lammps/build
```

**Comment by junghans** [comment]
That is how I have been using it, too, but it seems on a bunch of systems `/usr/lib64/ccache` or equivalent doesn't get added to the `PATH` automatically, so this PR avoids the need to create the symlinks or change the `PATH` variable.

**Comment by giacomofiorin** [comment]
@junghans In my opinion, it is a more frequent scenario that a system is simply missing `ccache` (e.g. an HPC cluster not administered by @akohlmey and @rbberger).  In that case, a user would install it on their home folder, and need to add its installation path in `PATH` anyway.

**Comment by akohlmey** [comment]
@junghans if i weigh who would benefit (very, very few people, as ccache only speeds up **re-**compilation and thus is of primary benefit to only few developers, that e.g. frequently switch between branches **and** have not ccache set up in the typical way) against the fact, that any code we add we need to test and maintain, i think the benefit is too small to justify the inclusion of this.

**Comment by junghans** [comment]
Your call guys! I know how to make `ccache` work either way, however some cluster at LANL and LLNL have a `ccache` module. The module add `ccache` to the `PATH`, but doesn't provide a folder with symlinks. Plus if there are 40 different compilers keeping such a folder up-to-date would just be a pain.

**Comment by junghans** [comment]
Oh, and at least on my older fedora system installing `ccache` doesn’t automatically add the folder with the compiler syslinks to your `PATH`.

Anyhow, I feel <10 lines of CMake isn’t a huge burden if it helps a couple of developers!

**Comment by akohlmey** [comment]
It is not a question of the number of lines of code, but the fact that this is an option orthogonal to most other options, and thus significantly increases the number of permutations of feature combinations, that need to be tested, and that for a minimal benefit of a very specific use case, that could also be achieved through other means. I might be thinking differently, if we had more people actively contributing to (release) testing of LAMMPS. Thus I am inclined to drop this unless some other core LAMMPS developer supports including this feature.

**Comment by junghans** [comment]
@lammps/core any opinions?

**Comment by stanmoore1** [comment]
I'm not a CMake expert, so I don't have an opinion, sorry.

**Comment by junghans** [comment]
Sorry, but isn't the same argument true for a lot of options we have like e.g. all the `ENABLE_SANITIZE` options - if you need those flags just add them to CMAKE_CXX_FLAGS to the cmake command line.

Don't get me wrong, I have been using ccache for years and most of my systems have it setup, but it never caught on with other users due to the fact that if I have to tell people to make a folder with a bunch of symlinks and add that to their PATH or to use some obscure CMake variable, which isn't even documented on the CMake's website that is just one bridge too far for most users.

That all said, I have no hard feeling, if we don't merge this, but it would at least make life a bit easier for users at LANL.

**Comment by junghans** [comment]
@giacomofiorin Sure, it is just that we don't have those folder with symlinks and nor will they be added in the foreseeable future. Honestly, I am not a big fan of adding random craft either, but the `ccache` usage got a nice uptake when gromacs added something similar (even though more [advanced](https://github.com/gromacs/gromacs/commit/04190c78b16e6ebafc9d8487189d3dfe7f5f4600)).

**Comment by junghans** [comment]
Votes are in, let's not merge this!

**Pull request closed without merging**
