### PR TITLE
Discrete element models for the BODY package

### PR DESCRIPTION
**Pull request by ndtrung81**
## Purpose

This PR contains the implementation of the discrete element models (DEM) for polygons and polyhedra following the models proposed by Langston and coworkers (Fraige et al., Particuology 2008, 6, 455-466, and Wang et al., Granular Matter 2011, 13, 1-12). In these DEM, the polygons and polyhedra are rounded at their vertices and edges by a specified diameter. The interaction between any pair of polygons and polyhedra is determined from a multiple contact model, as described in the mentioned references. The models (including the new atom styles, pair styles and related fixes) are part of the BODY package.

## Author(s)

Trung Nguyen (Vietnam Academy of Science and Technology, now at Northwestern) - through discussion with, and suggestion by, Steve Plimpton.

## Backward Compatibility

N/A

## Implementation Notes

The current models do not take into account the contact history for friction forces as done in the mentioned references.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by sjplimp** [comment]
HI Trung - I made some small modifications to many of the files.  In the doc files,
see my NOTE comments and Qs.  Also, all the example files ran except
the pour3d example on 4 procs (it ran on 1 proc).  It crashed on step 0.

**Comment by sjplimp** [comment]
@ndtrung81 I cleaned up your latest doc changes (removed my TRUNG comments)
and changed the name of the old pair_style body to body/nparticle (now that
there are several variants).  I think this is ready to go, so am assigning to @akohlmey

**Comment by akohlmey** [comment]
@sjplimp this needs some more work in the documentation. there are two issues:
- redundant references to citations (sphinx website processing requires them to be unique across all files)
- you did not update doc/src/lammps.book when renaming the existing body style (and the docs for it).

from the jenkins output at https://ci.lammps.org/job/lammps/job/pull-requests/job/build-docs-pr/1397/console
```
The HTML pages are in html.
############################################
Fraige
 - src/body.txt:450
 - src/pair_body_rounded_polygon.txt:132
Wang
 - src/body.txt:454
 - src/kspace_style.txt:353
 - src/pair_body_rounded_polyhedron.txt:126
Found 2 anchor label errors.
############################################
```
and
```
Converting write_data.txt ...
Converting write_dump.txt ...
Converting write_restart.txt ...
ERR005: Unable to find "pair_body.html"...
PAGES: 2260

                                                                               
BYTES: 16709078
Makefile:110: recipe for target 'pdf' failed
make: *** [pdf] Error 1
```

**Comment by sjplimp** [comment]
doc changes done @akohlmey

**Pull request merged**
