### PR TITLE
NWChem

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

Interface between LAMMPS and NWChem QM code.  For either ab initio MD or QM/MM.  A new NWCHEM package
with a fix nwchem command wraps the NWChem DFT library.

This is conceptually similar to the LATTE package and fix latte command.  Except that here, LAMMPS computes a Coulomb potential which is passed to NWChem, enabling QM/MM coupling.

Many things still to do for this work-in-progress PR:

(a) enable building with NWChem lib
(b) parallel operation of LAMMPS
(c) treatment of simulation box boundary conditions
(d) molecular systems with weighted Coulombic interactions
(e) test scripts and example dir.

**Related Issue(s)**

N/A

**Author(s)**

Steve and Eric Bylaska (PNNL, NWChem developer)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp since part of the changes of this PR are now in upstream, you should probably merge with the current develop branch, specifically since you were missing a few changes.

**Comment by akohlmey** [comment]
@sjplimp this hasn't seen updates for half a year. In general, we close stalled pull requests and ask to resubmit when ready (again). At the very least, this should be updated to the current upstream code base.

**Comment by sjplimp** [comment]
@akohlmey merged with current master, here has been debugging and testing in my local branch in more recent months, don't want to archive it yet

**Comment by akohlmey** [comment]
@sjplimp is this going to become obsolete by PR #3628?

**Comment by sjplimp** [comment]
yes, that is correct - you can delete it
I hope today or tomorrow to finish the new one so that it is ready to
review/merge.

Steve

**Pull request closed without merging**
