### PR TITLE
Add non-volatile version of join function to DomainKokkos

### PR DESCRIPTION
**Pull request by arghdos**
**Summary**

Adds non-volatile overload to fix build error w/ Kokkos commit (067c2593b58e1d9204d097432e221cfd524d7978)

**Related Issue(s)**

N/A

**Author(s)**

Nicholas Curtis

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

I am not 100% sure -- was there a time where Kokkos only had a volatile overload? If so, that might break.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by arghdos** [comment]
@stanmoore1 -- this passes my validation tests for LJ/EAM/Tersoff/ReaxFF&SNAP, but I am not 100% confident on what this functor is doing.

**Comment by stanmoore1** [comment]
@arghdos this fails to compile with the Intel compiler, I think we have to wait until we update the Kokkos version in LAMMPS too. :(

**Comment by stanmoore1** [comment]
This will be fixed in Kokkos instead, see https://github.com/kokkos/kokkos/pull/4951.

**Comment by arghdos** [comment]
FWIW, we might still want to have a non-volatile overload for join (hopefully that will make the Intel compiler happy)

**Comment by stanmoore1** [comment]
@arghdos I agree, will do.

**Review by stanmoore1 — APPROVED** [review]

**Comment by PhilMiller** [comment]
Once kokkos#4951 is merged, you'll ideally want to just want to change the parameters to your `join()` to not be `volatile` qualified. That should potentially offer better performance.

I don't know the code's policy/practices in terms of forward/backward Kokkos compatibility, though. Having both overloads will maintain operation with Kokkos 3.6 as well as `develop` (post 4951)

**Comment by stanmoore1** [comment]
@PhilMiller thanks for the info. We'll plan to remove the `volatile` when the version of Kokkos bundled with with LAMMPS includes 4951 (probably Kokkos v3.7).

**Pull request merged**
