### PR TITLE
Certificate Verification

### PR DESCRIPTION
**Pull request by yafshar**
if SSL report an error ("certificate verify failed") during the
handshake and thus refuses further communication with that server,
you can specify your own CA cert path by setting the environment
variable CURL_CA_BUNDLE to the path of your choice.

**Summary**

enhancement.

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by yafshar** [comment]
@ellio167 I added an extra certificate verification, following the [curl protocol docs](https://curl.haxx.se/docs/sslcerts.html).

**Comment by ellio167** [comment]
@yafshar Thanks for working on this.  I think it would make more sense to just check for the `CURL_CA_BUNDLE` env variable in `kim_query.cpp` directly.  Involving the cmake build process seems unnecessary.

**Comment by yafshar** [comment]
@ellio167 I agree with your suggestion and removed the CMake changes. But I used the c++ `std::getenv` to set the environment variable. Do you agree with this or would rather to use the macro version?

**Comment by ellio167** [comment]
This looks good to me.

**Comment by rbberger** [comment]
@ellio167 @yafshar I'm missing some sort of documentation about `LMP_NO_SSL_CHECK` and `CURL_CA_BUNDLE`. It also doesn't seem to be present in the CMake file.

**Comment by ellio167** [comment]
@rbberger Agree that we should add doc for `CURL_CA_BUNDLE`.  However, `LMP_NO_SSL_CHECK` (and for that matter  `LMP_DEBUG_CURL`) were added by @akohlmey back in 741a7fe630d5e445163115c897db5aba74455f7f

So, I'm not sure what should be done with those...  Do you suggest that  both of these be added as [Package-Specific Configuration Options](https://github.com/lammps/lammps/blob/master/cmake/README.md#package-specific-configuration-options)?

**Comment by rbberger** [comment]
Sorry, I didn't know this was from @akohlmey . Ok, we'll look into documenting `LMP_NO_SSL_CHECK` and ` LMP_DEBUG_CURL`. Since those are compile-time options they should be added to the build docs and the CMake build (https://lammps.sandia.gov/doc/Build_extras.html#kim).

However, this `CURL_CA_BUNDLE` environment variable seems to be a runtime option, so I suppose this should go into a documentation page in the Manual where the usage of KIM models is explained.

**Comment by yafshar** [comment]
@ellio167 @rbberger @akohlmey I do not know if there is a specific reason @akohlmey put   `LMP_NO_SSL_CHECK` and `LMP_DEBUG_CURL` like that. But I can update those and add the documentation as well.

**Comment by yafshar** [comment]
@rbberger I did all the changes and added the document to the `Build_extras.txt` file. Should I also add it to the `rst` file as well?

**Comment by rbberger** [comment]
@yafshar Yes, please recreate the RST file(s) (`make -C doc rst`). FYI, we're migrating away from the txt format. Future changes should be done in the RST file only. Once the txt file is no longer up-to-date, we remove it completely to avoid accidentally overriding changes.

**Comment by yafshar** [comment]
@rbberger @ellio167 I added the changes and updated the CMAKE, txt and rst files as well.

**Comment by ellio167** [comment]
Looks good to me.  Thanks @yafshar

**Comment by rbberger** [comment]
@yafshar one last change. Please mark the CMake options as advanced, so they are hidden by default.
I would push myself but you seem to have restricted either your repo or this PR (check allow push by maintainers)
```
diff --git a/cmake/Modules/Packages/KIM.cmake b/cmake/Modules/Packages/KIM.cmake
index eda8ffe82..a75e24809 100644
--- a/cmake/Modules/Packages/KIM.cmake
+++ b/cmake/Modules/Packages/KIM.cmake
@@ -6,10 +6,12 @@ if(PKG_KIM)
     list(APPEND LAMMPS_LINK_LIBS ${CURL_LIBRARIES})
     add_definitions(-DLMP_KIM_CURL)
     set(LMP_DEBUG_CURL OFF CACHE STRING "Set libcurl verbose mode on/off. If on, it displays a lot of verbose information about its operations.")
+    mark_as_advanced(LMP_DEBUG_CURL)
     if(LMP_DEBUG_CURL)
       add_definitions(-DLMP_DEBUG_CURL)
     endif()
     set(LMP_NO_SSL_CHECK OFF CACHE STRING "Tell libcurl to not verify the peer. If on, the connection succeeds regardless of the names in the certificate. Insecure - Use with caution!")
+    mark_as_advanced(LMP_NO_SSL_CHECK)
     if(LMP_NO_SSL_CHECK)
       add_definitions(-DLMP_NO_SSL_CHECK)
     endif()

```

**Comment by yafshar** [comment]
@rbberger Allow edits from maintainers is on? is there anything else I should do

**Comment by rbberger** [comment]
@yafshar weird. It might be because you forked from someone else, not from lammps/lammps. In any case, something on your repo is blocking me from pushing. You could add me as a contributor to your local repo's settings or just push the small change yourself.

**Comment by rbberger** [comment]
@yafshar Ok, done. Found my mistake. Once the tests complete I'll merge this. Thanks.

**Pull request merged**
