### PR TITLE
Restore non-dpd atom style support in USER-DPD.

### PR DESCRIPTION
**Pull request by timattox**

### CODE REVIEW

**Comment by akohlmey** [comment]
tim, i am seeing that a colleague of yours (Chris Stone) seems to have been sending patches to Steve before I have been able to send him what you have submitted here via pull requests. Can you please agree on one consistent way of submitting patches to LAMMPS. The scheme of sending stuff to both Steve and me is likely to create problems (to put it mildly).

**Comment by timattox** [comment]
Axel,
Yeah, I tried to head that off, but apparently my colleague didn't
understand my request to wait until my changes
flowed all the way through.  Sorry for the mixup.
I guess I'll go back to sending my USER-DPD stuff directly to Steve so this
doesn't happen again.

Anything I can do right now to help clean up the current mess?


On Tue, Jun 28, 2016 at 12:32 PM, Axel Kohlmeyer <notifications@github.com>
wrote:

> tim, i am seeing that a colleague of yours (Chris Stone) seems to have
> been sending patches to Steve before I have been able to send him what you
> have submitted here via pull requests. Can you please agree on one
> consistent way of submitting patches to LAMMPS. The scheme of sending stuff
> to both Steve and me is likely to create problems (to put it mildly).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lammps/lammps/pull/105#issuecomment-229105251>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AJJbgR8tKgRb7AqFuL41yf7K4m_5VNMkks5qQUyTgaJpZM4I849l>
> .
>



-- 
Tim Mattox, Ph.D. - tmattox@gmail.com

**Comment by akohlmey** [comment]
from my perspective, it would be better to always go through github. sending stuff to steve and have him do the right thing can be very tricky sometimes. even after so many years, i don't always get it right, or he does unpredictable things that create problems. when processing submissions through github, we have already integration tests that go far beyond what steve is checking (if does check things at all, with user packages he is often assuming the people sending him stuff did all the careful updating and testing necessary), so issues can be detected much sooner.

**Comment by timattox** [comment]
Okay Axel, I'll try to get everyone on our side to use github (that would be my preference too).  BTW - The code change in question was created by Chris Stone, but it was submitted by Jim Larentzos to Steve.  I think Chris and I can handle the github workflow directly once Jim is done with his current set of changes.

**Comment by akohlmey** [comment]
I think i've managed to restore everything to a reasonable state. Please check out the latest lammps-icms branch. The most confusing thing was, that the updated files steve was given undid several bugfixes and plugs for memory leaks that were already present in upstream and not just in lammps-icms. in addition i've replaced the ::fastpowi() hack with the better implementation in MathSpecial::powint() and made the code use the FLERR macro correctly. Still need to run checks with valgrind's memcheck, though.

**Comment by timattox** [comment]
Axel, that was worse than I thought, clearly one of my colleagues had an out-of-date repository.  I'll work with them to make sure they are up to date with your bugfixes and memory leak fixes.  I've run a few tests, and what is now in lammps-icms looks good to me, but I have to check on a few differences in DPD-RX reaction values I saw in a few local tests.  Likely my reference output is out of date for those tests.  Either way, your fixes should be sent back to Steve so his svn repo has them.  If there are regressions we see in our local testing, we'll fix them on our end and submit updates through github pull requests.  Thanks for your effort to clean this up!  Very appreciated, and sorry for the added work!

**Pull request merged**
