### PR TITLE
added manifold_spine_two to manifold_factory

### PR DESCRIPTION
**Pull request by Pakketeretet2**
I forgot to add the new manifold to the factory.

### CODE REVIEW

**Comment by akohlmey** [comment]
is there any documentation for this new feature yet?

**Comment by Pakketeretet2** [comment]
Ah, good point, forgot about it, will add it.

**Comment by Pakketeretet2** [comment]
Oh, oops, I think the push also included changes in all the generated HTML files. Is there a simple way to prevent that?

**Comment by akohlmey** [comment]
```
mpic++ -fopenmp -O3 -fomit-frame-pointer -march=core2 -ffast-math -mpc64 -g -fstrict-aliasing -Wall -Wextra -W -Wno-unused-parameter -Wno-maybe-uninitialized -Wno-sign-compare  -DLAMMPS_GZIP -DLAMMPS_MEMALIGN=64 -DLAMMPS_JPEG -DLAMMPS_PNG -DLAMMPS_FFMPEG -I../../lib/meam -DLMP_USER_INTEL -DLMP_MPIIO -I../../lib/poems -I../../lib/voronoi/src -I../../lib/smd -I../../lib/h5md/include -DLMP_USER_OMP -I../../lib/colvars -I../../lib/awpmd/ivutils/include -I../../lib/awpmd/systems/interact -DLMP_PYTHON  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1 -DFFT_FFTW3   -I/usr/include/vtk     -I/usr/include/python2.7 -I/usr/include/python2.7   -c ../manifold_factory.cpp
../manifold_factory.cpp:45:37: fatal error: manifold_spherocylinder.h: No such file or directory
compilation terminated.
Makefile:111: recipe for target 'manifold_factory.o' failed
make[1]: *** [manifold_factory.o] Error 1
make[1]: Leaving directory '/home/akohlmey/compile/lammps-icms/src/Obj_openmpi-omp'
Makefile:130: recipe for target 'openmpi-omp' failed
make: *** [openmpi-omp] Error 2
```

**Comment by Pakketeretet2** [comment]
Yeah, sorry, I am screwing things up again. Just close this, I will remake the branches in a proper way.

**Comment by akohlmey** [comment]
just fixed it.

**Comment by Pakketeretet2** [comment]
Oh. Alright, then I just reopen and comment? I guess some edits that were supposed to go in one branch ended up in the other.

**Comment by akohlmey** [comment]
i excluded all the unwanted changes from the pull and corrected the includes.
check out the updated lammps-icms branch from commit 2ae9572b5aa5f1169104e57b6802b41807e4ca87

**Pull request closed without merging**
