### PR TITLE
add exactly N particles to available lattice points

### PR DESCRIPTION
**Pull request by jrgissing**
a couple other modifications which helped setting up and testing simulations for bond/react

## Purpose

add exactly N particles to available lattice points

## Author(s)

Jacob Gissinger

## Backward Compatibility

Backwards Compatible

## Implementation Notes

tested on multiple systems, region types, using mol option

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Parallelized, tested in parallel

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by jrgissing** [comment]
added 'insert' keyword. see doc page for explanation, here is example command:

create_atoms 1 box insert 100 8411551

**Comment by akohlmey** [comment]
Thanks for submitting these changes. I'll take a closer look in a few days.

**Comment by jrgissing** [comment]
updated with a much faster (in parallel), slightly simpler and 'more completely random' way to do this

**Comment by akohlmey** [comment]
@jrgissing finally getting around to catching up on old pull requests during our concerted "github spring cleaning". will have to make some tests and check, whether your changes are affected by some strong scaling improvements that are still pending. if you don't mind, i would like to rebase your changes to the current master after some more of the pending pull requests are merged. i may even wait until we have the next patch release out. the rebase will make it easier to test, but it will require a forced push into your branch, or i would have to open a new branch in my repo and file a new pull request.

haven't looked at the code, yet, but i most certainly would want to change the name of the added keyword. i would go for something more descriptive like 'maxadd', or 'randnpos'.

**Comment by jrgissing** [comment]
sure, I've also been trying to rebase every so often

**Comment by akohlmey** [comment]
@jrgissing please note, that the doc-build test has detected a spelling error.

**Comment by jrgissing** [comment]
okay, i'm done

**Comment by sjplimp** [comment]
I looked this over - it's an interesting idea.  I don't think the idea scales.  If I understand,
proc 0 needs to allocate space for all the lattice points (in the entire system), and loop
over all of them.  Here are a few ways people will try to use this, say on 1000 procs.
(a) define a lattice with 10B (billion) sites and populate it with 1B atoms.
(b) define a lattice with 1B sites and populate it 99% so there are 1% vacancies.
(c) same as (b) but with 10B sites.  create_atoms would do this without the randnpos keyword.
All of these will blow out memory or take forever to run.
Also there are no overflow checks for 32-bit ints that I could see.  You definetely need
64-bit ints for some values.  Also you can't
use int foo[N]; or int *foo = new int[N]; when N is huge.  You have to use memory->create()
to catch an out-of-memory error with a good error message.

I have an alternate suggestion for how to do this, that
I think will be more scalable in memory and run time.  I'll email it directly
to @jrgissing and @akohlmey.

**Comment by akohlmey** [comment]
> I have an alternate suggestion for how to do this, that
> I think will be more scalable in memory and run time. I'll email it directly
> to @jrgissing and @akohlmey.

@sjplimp so are you saying that this pull request should be closed?

**Comment by sjplimp** [comment]
no, I think some version of this is a good idea - this is a good placeholder
until we have a version we all agree on.

**Comment by rbberger** [comment]
@sjplimp please let us know how you want to proceed with this PR.

**Comment by sjplimp** [comment]
@rberger It's been a while, let me look at the current version. Jake and I went back and forth a few times on ways to do this scalably.

**Comment by sjplimp** [comment]
@jrgissing Just pushed the changes we talked about.  The new options for create_atoms are subset and ratio.  The new options for set type are type/ratio and type/subset.  There was already a type/fraction keyword for set, so Axel and I decided to use ratio and subset consistently between the 2 commands.  If you think this all looks good, and works as expected, we should be ready to merge.

**Comment by jrgissing** [comment]
this looks good to me

**Pull request merged**
