### PR TITLE
added several features to the NEB

### PR DESCRIPTION
**Pull request by EmileMaras**
#The main new features are the following : 
   - new nudging force which is more efficient at keeping the replicas equispaced (Note that the "original" nudging forces can still be used)
   - possibility to add a perpendicular spring force which can be useful to prevent the path from becoming too kinky
   - free end neb
   - verbose option 

see the neb.txt and fix_neb.txt file for more informations

### CODE REVIEW

**Comment by akohlmey** [comment]
thanks for your submission. i have not had much time to look at it, but there are two issues that stand out easily, that need to be addressed. please understand that because these are changes to the core code, some of our requests may seem a bit nitpicky and more focused on style than on science. we aim to maintain a consistent style in the code, that helps maintainers and also users in the long run. here are a few of these nitpicks:
- you have added keywords/flags that are written in CamelCase and some of them are almost full sentences. we prefer all lowercase and short keywords and flags. this is not done 100% in the existing code and docs, but any change/update is an opportunity to improve the situation and consistency
- when comparing side by side, i see that your changes revert some of the recent maintenance changes, e.g. spelling fixes, adjustments to remove duplicate links in the docs (all links have to have globally unique tags)
- it also looks like you removed or significantly shortened some paragraphs in the docs. can you please check, whether those were added/extended after you forked off your development code (and thus should be re-added) or whether these are incorrect and must remain removed.
- there is unrelated garbage at the beginning of the fix_neb doc file
- don't use (imprecise and inconsistent) local constants; include the math_const.h header and use constants in MathConst namespace, if available, e.g. for pi, pi/2, 2pi and so on.
- try to keep lines within 80 characters width.
- do not use tabs, indentation width is 2 characters
- steve prefers compact if and loop statements: brace on the same line as the condition. only use braces for multi-line blocks, place single line block on the next line unless it is very short. example:
```c++
if (condition) {
  val = something;
  val += something_else;
} else val = nothing;
```
- don't add (trailing) whitespace as that artificially introduces differences to the code without any changes.

thanks again for your contribution. please try to apply as much of the suggested changes as seems reasonable to you (none of the "rules" i listed are strict rules), commit them to your branch and then push them to github to update the PR (see the LAMMPS github tutorial for some discussion of the review and merge process on github) and add comments here, if you have questions or disagree with any suggestion.

**Comment by EmileMaras** [comment]
Hi Alex,

I made the changes you asked for.
Some parts of the documentation were removed on purpose because they either became irrelevant or were inaccurate.

I hope that now everything is fine.

**Comment by akohlmey** [comment]
Sadly, things are not fine. While reformatting, you have messed up some other parts.
I've updated the doc files to have proper formatting and fixed inconsistency issues.

i've also updated the source code for consistent formatting and removed dead code, silenced compiler warnings, plugged a few memory leaks and also rolled a bunch of 8 MPI_Allreduce() into a single call.

there are still CamelCaseVariableNamesThatAreAlmostWholeSentences, e.g. in fix neb:
```c++
  double kspring,kspringPerp,EIniIni,EFinalIni;
  bool StandardNEB,NEBLongRange,PerpSpring,FreeEndIni,FreeEndFinal;
  bool FreeEndFinalWithRespToEIni,FinalAndInterWithRespToEIni;
```
Worst problem is that the modified code cannot reproduce the results of the examples provided in the `examples/neb` folder.

**Comment by akohlmey** [comment]
I've been wondering about the discrepancy of the reference input. could it be, that by default, there is now a different algorithm in place? then this needs to be documented. i don't recall seeing anything related to that, but i didn't check very thoroughly and focused on the formal issues. Also, we need to change the example inputs accordingly and/or provide alternate example input demonstrating the new/altered/improved features. please let me know.

**Comment by EmileMaras** [comment]
Thanks for the editing. 
You are right, the new default implementation of the NEB is different from the old version since I modified the nudging forces. The new default version is more efficient for maintaining the replicas equispaced. Beyond that, both versions should give very similar results. You can get back to the old version by using the keyword neigh :+1: 
fix		2 nebatoms neb 1.0 neigh 

I did check quickly on one example and I got exactly the same results as before.


However I do not get the same results with the last version that I commited and with the current version (i.e. after your modifications) when using the default nudging forces.  Can you think of any change you implemented that could change the behaviour of the code?
 I hope to get some time tomorrow to check this.

Regarding the different options for the NEB, I think that everything is explained in the documentation. But let me know if you feel that something is not clear or is missing.

You are right, I should also take some time to modify and add some examples. I do not really like that the current examples just 4 images so I will add more images in the current examples and I should at least add one example for the free end neb.

**Comment by akohlmey** [comment]
The original code had some memory issues, which may or may not have led to memory corruption. E.g. i would get significantly different results with different number of MPI ranks per replica. The only major code change was the collating of the 8 MPI_Allreduce calls into one. i will manually review this chunk of code again for potential errors (easy enough to have a cut-n-paste error in these).

Please note that the choice of <=4 replica is motivated by being able to run these inputs also as regressions tests, where we are limited to a small number of MPI ranks. I would suggest to add some explanation to the README file that explains that the suggested number of replica are merely to quickly verify the correct functioning of the NEB facility under a variety of parallelization conditions.

**Comment by akohlmey** [comment]
Here are my observations:
of the `in.neb.hop1` input, when comparing your original commit 640edbc1d40e6571d25b02d9f4e892d95a9c4008 and while adding the flag to fix neb, i cannot fully reproduce the original log files. the columns GradV0 and GradV1 diverge significantly a few others less so, most are within typical numerical error range. i don't see any difference between that version and the current tree. when comparing the original commit and the HEAD revision on the NEB-Change branch, i also get very different results.

i've double checked the MPI_Allreduce() change and i don't see any problems there. The cause is likely somewhere else.

**Comment by akohlmey** [comment]
OK, i think i found one of the issues. It was my mistake. When reformatting the initialization of the booleans in the fix neb constructor, i incorrectly changed the default setting for `NEBLongRange` from `true` to false`.
Correcting this also exposed a bug in the code to free the custom communictor in the fix neb destructor.
There are a few more small changes for improved consistency with other LAMMPS source code and to avoid data corruption. Will push the changes to your branch now. Please check.

**Comment by EmileMaras** [comment]
Yes I did not commit properly. it should now be ok.

**Comment by akohlmey** [comment]
OK, so where do we stand on this pull request overall?
Do you plan to make additional changes?
Does the code now reproduce all results that should be reproduced in your opinion?

**Comment by EmileMaras** [comment]
Everything seems to work as expected and I do not plan to make any additional change anytime soon.
So I think that we are all set to go.

**Comment by athomps** [comment]
Hi Emile, these are nice extensions to the NEB capability in LAMMPS.  I did not look at the code, as it sounds like it has been carefully reviewed by Axel. Instead I just reviewed the additions to the doc page.  Here are some suggestions that will help to minimize confusion for current and future NEB users:

1. The keywords idealpos and neigh seem to be mutually exclusive, although this is not explicitly stated (could one use both?).  I suggest instead that you use keyword/value syntax, which is more LAMMPSian e.g. spring_style neigh|idealpos. Even better would be spring_style neb|string, since I think the two styles are associated with the NEB (Jonsson) and String (E) methods, respectively. 
2. Switch the default behavior to be the same as the old code (spring_style neb) and document that in the Default section of the doc page.
3. Verify that default input script reproduces old output log.5Oct16.neb.hop1.g++.4 etc.

I think everything else is fine as is, although here are a few more suggestions:

0. See doc/src/fix_langevin.txt for a good example of how to document a fix with many options. 
1. Add the bullet "zero or more keyword/value pairs may be appended" before the last bullet.
2. Change freeend flag to freend_style none|ini|final|finaleini|final2eini
3. State that freend_style default is none in Default section
4. It seems like the force expressions used for finaleini and final2eine contain a stiffness constant in front of (E-Etarget) that is implicitly set to 1.0 / angstrom.  This should be specified by the user, perhaps with a sensible default.

**Comment by EmileMaras** [comment]
I made most of the changes you suggested. 
I did not use the values NEB and string for the parallel nudging force because the neb and string method do more than just this. 
I did put back the default behaviour to be the same as the old code. I have to say that I was hesitating to do so.  The advantage is that if people run the same input file as before they will get exactly the same results. However the idealpos value should give better results in at least most cases. So I am not so sure. I let you chose.

I have check and the examples give the same results as before (at least when they should : I put the nudg_style to idealpos in some examples so the results are different but I checked that when removing it I get the same results as before).

**Comment by athomps** [comment]
Thanks for making the changes. I think this is almost ready for release. I will go ahead and assign it to Steve.  You should review the doc page one more time. I think there are some remnants of the old text still hanging around (some text describing the use of "flag").

**Comment by sjplimp** [comment]
Hi Emile - I'm reading the doc page and code for the alterations to NEB.  Thanks
for submitting these improvements.  I don't fully understand the "freeend" options
for adding additional forces to the first/last replica.  Shouldn't there be an
option to do add forces to the both the first/last replicas?  The way the doc
and code are now, it seems like you must choose one or the other.  Should syntax like
this be allowed:

fix 1 all neb 1.0 freeend first freeend last

to allow both end replicas to be perturbed?

Steve

**Pull request merged**
