### PR TITLE
Small enhancements to the mdi/qm fix

### PR DESCRIPTION
**Pull request by taylor-a-barnes**
**Summary**

This PR adds a few small enhancements to the `mdi/qm` fix.  Most notably, it adds support for QM engines that are only capable of running gas-phase calculations, and thus do not support the `>CELL` MDI command.  In addition, it requests the energy from the QM engine in a way that is more general with respect to the capabilities of various QM engines.

**Author(s)**

Name: Taylor Barnes
Affiliation: MolSSI

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

These changes should not affect backwards compatibility.

**Implementation Notes**

This has been confirmed to function properly with the QCEngine MDI engine and the GAMESS MDI engine, which did not support the `>CELL` MDI command.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Review by akohlmey — COMMENTED** [review]
@taylor-a-barnes @sjplimp
I have two questions:
- Do these changes require updates to the documentation or example scripts?
- Since those changes are to fix mdi/qm, how about fix mdi/qmmm?

**Comment by akohlmey** [comment]
Please also note that either clang-format should be applied or a `// clang-format off` comment added to either the top of the file or `// clang-format off` , `// clang-format on` added to blocks that should be protected from clang-format processing.

**Comment by taylor-a-barnes** [comment]
@akohlmey Thanks for the comments.  You're correct, the same changes were also needed in mdi/qmmm fix.  I've added the changes to mdi/qmmm in the latest commits.

In terms of documentation, there isn't really anything different a LAMMPS user would need to do, but it is probably worth letting users know that if a QM code doesn't support periodic boundary conditions, the mdi/qm (or mdi/qmmm) calculation needs to run with non-periodic boundary conditions.  I've added this warning to the documentation for the fixes.

I've also run the mdi/qm and mdi/qmmm files through clang-format.  The resulting formatting changes weren't isolated to my changes.  @sjplimp: you might want to confirm that the reformatting didn't affect your contributions to the code in adverse ways.

**Comment by akohlmey** [comment]
@sjplimp FYI, this PR is assigned to you so you can double check the changes and make updates to the examples, if needed. If you don't want the clang-format changes, we can roll that back, but then a "// clang-format no" needs to be placed at the top of the .cpp file.

**Review by sjplimp — APPROVED** [review]
@taylor-a-barnes Thanks for making these additions.  Made a few minor changes for clarity (for me) in the comments, and pushed them.  This is ready to merge from my perspective.

**Comment by sjplimp** [comment]
@taylor-a-barnes Also, I had a note for fix mdi/qmmm about support being added to MDI for these 3 new commands:
>LATTICE_ELEMENTS, >LATTICE_FORCES, >POTENTIAL_AT_NUCLEI -- is that still your plan?  The NWChem and PySCF  Python wrappers in examples/QUANTUM are using them.

**Pull request merged**
