### PR TITLE
Refactor kim commands

### PR DESCRIPTION
**Pull request by yafshar**
**Summary**

This PR includes,

- Refactor `kim commands` to a single command with sub-commands following it for different options
   - Update the `kim init` command. Now it sets the skin and timestep default values as 2.0 Angstroms and 1.0
femtosecond for every unit system for kim models
   - Update the `kim query` command. Now, the `kim query` works with the `model` argument and can also be used with no `kim init` call requirement.
   - Update the `kim param` command and make it independent of `kim init` call at the start
   - Update the `kim command` doc and references to it
   - Update the `kim command` examples and log files with new command interface
   - Update the `kim command` unit tests and add extra test cases for better coverage
- Extend the `kim query` command, to get all available models meeting certain requirements. To query for KIM models the query function is `get_available_models`
- Fix some mistakes in the code and clean up the interface

**Related Issue(s)**

**Author(s)**

Yaser Afshar (UMN)
Ryan S. Elliott (UMN)
Ellad Tadmor (UMN)
Axel Kohlmeyer, (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This PR is **not backward compatible**. It includes refactoring the `kim commands` to a single command with sub-commands following it for different options, which will fail if used with old input files.

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@yafshar I have added the removed commands as aliases to the "Deprecated" command style, so that people that use LAMMPS input with the old format get a more meaningful error message like below.
I have also updated it to the current master to avoid reporting changes in the GitHub web interface that are already included.

```
$ ./lmp
LAMMPS (10 Feb 2021)
kim_init

'kim_<command>' has been renamed to 'kim <command>'

ERROR: This command is no longer available (src/deprecated.cpp:43)
Last command: kim_init
```

**Comment by yafshar** [comment]
> @yafshar I have added the removed commands as aliases to the "Deprecated" command style, so that people that use LAMMPS input with the old format get a more meaningful error message like below.
> I have also updated it to the current master to avoid reporting changes in the GitHub web interface that are already included.
> 
> ```
> $ ./lmp
> LAMMPS (10 Feb 2021)
> kim_init
> 
> 'kim_<command>' has been renamed to 'kim <command>'
> 
> ERROR: This command is no longer available (src/deprecated.cpp:43)
> Last command: kim_init
> ```

@akohlmey thanks, this is better and more expressive

**Comment by akohlmey** [comment]
@tadmor @yafshar @ellio167 the citation reporting for KIM models somewhat clashes with the conventions we have established.
The first line of the string handed to `citeme->add()` should be a one line summary mentioning what needs to be cited including a DOI or a URL. E.g. for the KIM API as such it could be: `KIM API: https://openkim.org/kim-api/` or `OpenKIM API: https://doi.org/10.25950/ff8f563a`
Right now it only prints `@Comment`.

It is also a discussion with @sjplimp what exactly should be printed and added.
So the `kim` command should cite the OpenKIM API, and then individual models should cite just the model.
So far in the discussion with @sjplimp the general trend was to limit what is cited in the default/terse output to just the minimum (applied here it would mean that there would be only the most relevant publication for the KIM API added) and then refer to additional publications in the documentation. However, I don't think this has anticipated citing potentials or KIM models.

**Comment by sjplimp** [comment]
I thought we did discuss this previously.  For the brief output, one line for KIM.  Add one line for each potential used (assuming there is a citation for it, presumably no citation for LJ).  For verbose, it's the same, just verbose versions of each citation.

**Comment by ellio167** [comment]
We had been focused on the refactoring of the commands and adding the`get_available_models` support for Steve.

We'll take a quick look at this to see if we can do it right away.  If it will take a little longer, we'll request that this PR be processed and we'll do the citation updates soon in a second PR.

**Comment by akohlmey** [comment]
> We had been focused on the refactoring of the commands and adding the`get_available_models` support for Steve.
> 
> We'll take a quick look at this to see if we can do it right away. If it will take a little longer, we'll request that this PR be processed and we'll do the citation updates soon in a second PR.

I can merge as soon as the PR is approved by @sjplimp

**Review by sjplimp — APPROVED** [review]

**Comment by akohlmey** [comment]
> We had been focused on the refactoring of the commands and adding the`get_available_models` support for Steve.
> 
> We'll take a quick look at this to see if we can do it right away. If it will take a little longer, we'll request that this PR be processed and we'll do the citation updates soon in a second PR.

Ok, I'll take it will need some more time. So will be merging this now.

**Pull request merged**
