### PR TITLE
user-crslnk added

### PR DESCRIPTION
**Pull request by aminaramoon**
Here is a pull request for a feature branch to add to USER-CRSLNK

### CODE REVIEW

**Comment by akohlmey** [comment]
This code cannot be accepted in its current form. Your package directory has modified versions of files that are either in the baseline or in other packages. That is not allowed, as this makes it impossible to uninstall your package correctly.

So we'll have to look into your changes in two (or three) steps.
- modifications to baseline (input, variable) those need to be compatible with no package installed and while code in USER packages is generally rather easily accepted, these changes will be put under very close scrutiny and thoroughly reviewed. expect requests for changes or alternate approaches
- modification to files from other packages. this will also have to be fully backward compatible and work correctly *without* your package installed.
- add your new compute. since this is only one command, it would then rather find its home in the USER-MISC package. at that point, we'll have to sort out dependencies.

so before updating your pull request. please consider and resolve these issues. i don't see much of a chance to have your contribution merged otherwise.

**Comment by aminaramoon** [comment]
The install.sh file in the package will backup files in the root folder when it installs them, and it copies them back when uninstalling. I have checked both installing and uninstalling, and it works just fine.
The second case is also fully backward compatible and works with the same syntax as well as updated command.

**Comment by akohlmey** [comment]
no. using backup files is not acceptable. keep in mind that there are regularly changes to the baseline files and then your add-on versions will be out-of-sync and stop working.

**Comment by akohlmey** [comment]
using backup files also collide with the source code management system.

**Comment by aminaramoon** [comment]
So what is your suggestion ?
Is there anything that I can do to facilitate the process ? I am sure that input file, and variable files are compatibles as I have just added new commands.

**Comment by akohlmey** [comment]
i already described the process. until you submit pull requests with each set of changes separately (changes to baseline code, changes to files from other packages, adding your new compute), in a way that i (and more importantly steve plimpton) can review them individually and without too much effort on our side, i will not even look at them. if you are not happy with this process, you can try e-mailing your code to steve directly.

**Comment by aminaramoon** [comment]
Okay, thanks a lot. I will close this pull request, and create new ones with the changes explained separately. Only one last question, the changes in the baseline files are meant to be used for the file in the other class (fix_bond_create). isn't it cause a problem in reviewing process ?

**Comment by akohlmey** [comment]
the changes to baseline files have to stand on their own and have to make sense. steve will not allow changes to them, that can be achieved differently.

there may have to be changes to those added features and modifications, so while you may post a second PR with the next stage of changes, you will need to update it with whatever makes it into the baseline code.

oh, and "crslnk" is a horrible name. why not "crosslink" or "xlink" (if you absolutely must save a few characters)?

**Comment by rbberger** [comment]
When you're working on baseline files, such as `variable.cpp`, also consider the following: it's a file with 5000 lines of code. You might have changed only a few lines to extend it in a way which allows your extension to work. However that change is obscured because you reformatted the entire file. So it becomes very difficult for anyone else to review the change and give you feedback. In short:

* don't reformat core files or parts of the code you don't change
* don't create a duplicate of core files in a USER package
* use 2 space indentations, as expected by Steve

PS: you don't have to close the PR, just push the update when you're ready.

**Pull request closed without merging**
