### PR TITLE
Added fix_gaussflow

### PR DESCRIPTION
**Pull request by sstrong99**
This file implements Gaussian dynamics (GD), which is a method to do nonequilibrium molecular dynamics simulations of steady-state flow. See http://dx.doi.org/10.1021/acs.jpclett.6b00748. It is simple to implement and derives rigorously from Gauss's principle of least constraint.

### CODE REVIEW

**Comment by akohlmey** [comment]
Thanks for your contribution. If you don't mind, I'd like to make a few suggestions, that will make it easier to merge and distribute:

- Your contribution would fit best into the USER-MISC package, which means the .h and .cpp file need to be moved and the src/USER-MISC/README file updated. Correspondingly, the input example(s) should be located in examples/USER/gaussflow and the documentation source should reference the USER-MISC package as other styles in this package do.
- Naming conventions for styles is to use all lowercase, so the fix should be called either gaussflow or flow/gauss or gauss/flow (my personal preference would be the second option)
- LAMMPS source code style uses 2 character indentation per level, no tabs, and no trailing whitespace and a newline at the end of a file. This is not a strict requirement, but would be highly appreciated.

FYI, no need to close the pull request. just update your local branch with the changes and push into the same branch on github used for the pull request and it will be automatically updated.

Thanks again for contributing to LAMMPS.

**Comment by sstrong99** [comment]
Ok, I think I addressed those issues. Let me know if there is anything else.

**Comment by sstrong99** [comment]
Thanks. If you don't mind, could you let me know what the minor issue was? I noticed that the checks failed, but it compiled fine on my machine. What was I missing?

**Comment by akohlmey** [comment]
You had removed one include statement too many. Please see commit: 9f1759481b3c25d07202cf7a3f0325d7c88fe526

**Pull request merged**
