### PR TITLE
Added optimized vashishta potential.

### PR DESCRIPTION
**Pull request by andeplane**
Replacing the pull request here:
https://github.com/lammps/lammps/pull/139

since I used lammps-icms branch in that pull request.

### CODE REVIEW

**Comment by akohlmey** [comment]
using the lammps-icms branch is the better choice, since all changes get merged into this branch before i send them to steve.

**Comment by andeplane** [comment]
Well, but since pull requests are per-branch I might work on two different pull requests over time. They should stay separate until merged?

Note that the pull request uses lammps-icms on lammps/lammps, but in my fork it doesn't:
andeplane  wants to merge 5 commits into lammps:lammps-icms from _andeplane:optimized_vashishta._

**Comment by akohlmey** [comment]
A pull request is nothing more than telling somebody that one of your branches is ready to be merged into a remote "official" branch. You should not file a pull request until you are convinced the changes are ready and update it only when asked to do so. You can keep and work on as many local branches as you wish. You can also merge from their corresponding upstream in the process as many times as you need or want. A branch for a pull request can be an hour old or a year old. It doesn't make much of a difference. It will help merging, if it is up-to-date with the baseline, though.

**Comment by andeplane** [comment]
If this passes testing it is ready to be merged.

**Comment by akohlmey** [comment]
Haven't had time to check yet, as this requires some more work and care to test. Been slowly grinding through accumulated changes and doing double duty with duplicating pull requests in my own fork, for practicing git with Steve (not mentioning many, many e-mails discussing details of the process).

**Comment by akohlmey** [comment]
I've given the tabulation code a careful review and tested it with valgrind, too. Some changes were needed. The original implementation was needlessly complex would allocate ntypes*ntypes tables, while nelements*nelements is sufficient (we always have: ntypes > nelements, and sometimes ntypes >> nelements). Also did some cleanup and added memory accounting info (since tables can be large).

**Comment by akohlmey** [comment]
FYI,
steve went a different way with integrating your changes and converted it to a separate pair style with a /table suffix. Since that takes the number of tabulation points as argument (similar to pair style table), the whole pair_modify thing and concerns about consistency with coul/long styles doesn't apply anymore. His proposed code is currently in the following branch (we are currently test driving using git in my repository and i've been feeding steve selected pull requests with increasing complexity)
https://github.com/akohlmey/lammps/tree/vashishta-tabulation
https://github.com/akohlmey/lammps/pull/13

If you would like to make any additional changes, you could submit a pull request relative to that branch in my repository or simply tell me. I'll add vashishta/table/omp, do some checks myself and then hand it over to steve.

**Pull request merged**
