### PR TITLE
Adding intel variant of snap pair style.

### PR DESCRIPTION
**Pull request by wmbrownIntel**
**Summary**

This adds an intel package variant of the snap pair style that is optimized for AVX-512. In my tests, it can be over 4X faster than the existing variants on CPUs.

**Related Issue(s)**

**Author(s)**

Mike Brown, Intel

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

This is implemented somewhat differently than other intel variants due to the unique bottlenecks and loop structure. First, it is only available if it is built with an Intel compiler for a CPU supporting AVX-512 (due to use of math library vector intrinsics). Second, it is currently only double precision, regardless of the Intel package precision mode selected. These notes are added to the snap doc page. While there is still performance on the table here, I need to set this aside for a bit. But as is, there are great speed ups and I believe it to be "production ready".

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by stanmoore1** [comment]
@wmbrownIntel it looks like the changes to snap doc page didn't get included? Also it looks like this doesn't support OpenMP threading yet either, just SIMD?

**Comment by wmbrownIntel** [comment]
> @wmbrownIntel it looks like the changes to snap doc page didn't get included? Also it looks like this doesn't support OpenMP threading yet either, just SIMD?

Thanks. I just committed the missing doc page changes and added that only a single OpenMP thread will be used. It is relatively straight forward to add OpenMP support here, but I don't believe it will currently be advantageous since we mostly use that for SMT (that will not benefit the current bottlenecks).

**Comment by athomps** [comment]
This is a nice addition that will provide speed up for people running MD with SNAP potentials on CPUs.  It would be nice if these optimizations could also be ported to `compute_snap.cpp`, so that the same speedup can be obtained in training SNAP potentials.

**Review by sjplimp — APPROVED** [review]
@wmbrownIntel Very nice Mike.  And impressive speed-up!

**Pull request merged**
