### PR TITLE
Add Kokkos support for fix shake and forward comm on Device for fixes

### LINKED ISSUE #1849: [Feature Request] KOKKOS - fix rattle / shake
**Summary**

Porting fix rattle / shake to kokkos package

**Detailed Description**

As we perform calculations of big systems with a lot of water on a GPU cluster using the Kokkos package we would ask to port the fix shake and/or rattle to the Kokkos package. Is it planned in the future? Thank you in advance!

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Add Kokkos support for fix shake and support for packing/unpacking forward comm for fixes, threaded on Device. Not all Kokkos fixes support device forward comm; currently only fix shake and fix qeq/reax do, while the other fixes pack/unpack on host.

**Related Issue(s)**

Closes #1849, #2454

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
Running this through Kokkos regression testing.

**Comment by stanmoore1** [comment]
All Kokkos regression tests are passing for this PR except `deposit/in.deposit.molecule.shake` on the GPU.

**Comment by stanmoore1** [comment]
I have one more issue I need to look into, should be ready in a few days.

**Comment by stanmoore1** [comment]
Kokkos regression tests passed.

**Comment by rbberger** [comment]
@sjplimp please approve to proceed with the merge.

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
