### PR TITLE
Adding scale parameter to pair/snap for fix/adapt

### PR DESCRIPTION
**Pull request by tomswinburne**
**Summary**

Added extract() function and scale matrix to pair/snap, following pair/eam/fs. (again...)

**Author(s)**

TD Swinburne, CNRS, swinburne@cinam.univ-mrs.fr

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Implementation Notes**

Due to the way alloy interactions are handled in SNAP, we only specify diagonal values of scale matrix (scale the coefficients of type i). This ensures potential forces are the negative gradient of the potential energy. 

I have tried to address Axel's points-

- there is no documentation added. Pair styles compatible with fix adapt (and the parameters that can be adapted) are listed in the fix adapt and fix adapt/fep documentation page in a table. 
This is done.

- there is no unit test added or updated (supported extract parameters should be listed) 
I am not sure how to find and modify the appropriate unittest for this case.

- there is no example provided (not required for this kind of change unless you have a very instructive and special example)
I have added a toy example in examples/snap, using hybrid/overlay and fix/adapt to mix linear and quadratic SNAP potentials.

- there are whitespace changes (empty lines or spaces added/removed) that are unrelated to the functionality added and should thus be reverted. If desired I can flag them individually. 
This has been resolved (I think)

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by akohlmey** [comment]
@tomswinburne I've added the modification to the unit tests for SNAP, but you still have the merge conflict due to the renaming of the packages in the upstream version. From the commit history it doesn't look like you followed the procedure I suggested.

**Comment by tomswinburne** [comment]
@akohlmey my master branch is even with lammps:master, and the following works without complaint-
```bash
git checkout -b master_copy
git merge snap-scale
```
with output
```
Auto-merging doc/src/fix_adapt_fep.rst
Merge made by the 'recursive' strategy.
 doc/src/fix_adapt.rst                             |  2 ++
 doc/src/fix_adapt_fep.rst                         |  4 +++-
 examples/snap/Ni_Zuo_JPCA2020.quadratic.snapcoeff |  1 +
 examples/snap/Ni_Zuo_JPCA2020.quadratic.snapparam |  1 +
 examples/snap/Ni_Zuo_JPCA2020.snapcoeff           |  1 +
 examples/snap/Ni_Zuo_JPCA2020.snapparam           |  1 +
 examples/snap/in.snap.scale.Ni_Zuo_JCPA2020       | 53 +++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/ML-SNAP/pair_snap.cpp                         | 32 ++++++++++++++++++++++++--------
 src/ML-SNAP/pair_snap.h                           |  2 ++
 9 files changed, 88 insertions(+), 9 deletions(-)
 create mode 120000 examples/snap/Ni_Zuo_JPCA2020.quadratic.snapcoeff
 create mode 120000 examples/snap/Ni_Zuo_JPCA2020.quadratic.snapparam
 create mode 120000 examples/snap/Ni_Zuo_JPCA2020.snapcoeff
 create mode 120000 examples/snap/Ni_Zuo_JPCA2020.snapparam
 create mode 100644 examples/snap/in.snap.scale.Ni_Zuo_JCPA2020
```

**Comment by tomswinburne** [comment]
@akohlmey I think I have resolved this now. I think I was behind the most recent major renaming. Apologies.

**Comment by akohlmey** [comment]
@athomps does this look OK to you now? It passes our unit tests and tests valgrind clean.

**Review by athomps — APPROVED** [review]
I approve.

**Pull request merged**
