### PR TITLE
Inner cutoff switching function for SNAP descriptors and potentials

### PR DESCRIPTION
**Pull request by athomps**
**Summary**

Added a keyword switchinnerflag to various SNAP-related commands that smoothly turns off SNAP descriptors
at short separation distances

**Related Issue(s)**

None

**Author(s)**

Aidan Thompson, SNL

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Some of the existing code was refactored, and text output for examples has shifted somewhat, but numerical output should be unaffected.

**Implementation Notes**

Support for the new feature was implemented consistently across all the existing SNAP-related commands, although the definition of the number of elements and the order of those elements is subtly different for different commands. This is documented.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@athomps @charlessievers does any of you have pending changes to this pull request?
I would like to grab it and replace uses of `strtok()` with calling the Tokenizer/ValueTokenizer classes instead.
But I don't want to mess up anything that you are still working on and thus would rather wait until you are done.
Please let me know.

**Comment by athomps** [comment]
@akohlmey Have at it!

**Comment by akohlmey** [comment]
> @akohlmey Have at it!

Done

**Comment by stanmoore1** [comment]
@athomps does this need to be ported to Kokkos?

**Comment by athomps** [comment]
Eventually, yes.

**Comment by athomps** [comment]
Looks good to me. @charlessievers could you take a look at this and submit a review?

**Review by charlessievers — APPROVED** [review]
An inner cutoff will help when fitting multiple elements that have different sizes.
In addition, the reduction of parameters into duidrj looks great.
Also, I ran the changes with all fitsnap bispectrum examples in a linux environment and no errors occurred.

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
