### PR TITLE
Fixes issues found via Static Code Analysis

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

* Fixes memory leak when using `shell putenv`
* Fixes small memory leak in Jacobi template class
* Use correct data layout when creating `verlet/lrt/intel` integrate style
* Fix function parameter dimensions for a few spin/dipole styles
* Fix a small memory leak with hybrid pair styles in compute pressure
* Use `utils::sfread()` instead of `fread()` in a few recently added styles
* Remove some dead code and fix a few logic issues
* Fixes a bug in fix propel/self to correctly access bonus data for hybrid atom styles.

**Related Issue(s)**

Fixes bug reported at the bottom of #1818 

**Author(s)**

Richard Berger (Temple University) @rbberger 
Axel Kohlmeyer (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@rbberger I have added any changes that I found worth doing based on the coverity and scan-build output. A whole lot of warnings could be dropped by wrapping fmt::format() in the Error class into try/catch, but since we are using wildcard formats, chances of exceptions are extremely slim and without the code reads better.

**Comment by rbberger** [comment]
@akohlmey ok. Please mark them as "Fix Submitted" next time.

**Review by sjplimp — APPROVED** [review]

**Review by gokulup009 — COMMENTED** [review]
I am getting " 'utils’ has not been declared" error when running "make mpi" .i don't have much knowledge of cpp. please help me  to declare this 'utils.

**Comment by akohlmey** [comment]
> I am getting " 'utils’ has not been declared" error when running "make mpi" .i don't have much knowledge of cpp. please help me to declare this 'utils.

This is not the right place to discuss such issues given your inexperience in C++ software development and how to use a website like this in a meaningful way. Please post your inquiry to the lammps-users mailing list instead. Please see https://lammps.sandia.gov/mail.html 
When posting to the mailing list you need to provide more details and relevant information to reproduce what you are doing. Thus please study and follow the guidelines posted here: https://lammps.sandia.gov/guidelines.html

**Pull request merged**
