### PR TITLE
GPU package has a hard cufft dependency when GPU_API=CUDA

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

CMake change was missing to add linking to cuFFT in the GPU package when using CUDA.

**Related Issue(s)**

**Author(s)**

@rbberger 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
This must be bogus.
If you look through the code in lib/gpu, only the amoeba support files reference cuFFT and in the .cpp file all code related to cufft is disabled. So how should there be a dependency?

There must be some part where this was done incompletely, possibly in the header.

**Comment by stanmoore1** [comment]
Right, the GPU package does not support FFTs on the GPU, it is all done on the host CPU.

**Comment by rbberger** [comment]
The header does the include and fails compilation. If the cpp parts are disabled, probably the header should also follow suit.

**Comment by akohlmey** [comment]
should be fixed in https://github.com/lammps/lammps/pull/4111/commits/a13d53dd65a435df205a727f77efe752c1f8c986

**Pull request closed without merging**
