### PR TITLE
Cmake flag check

### PR DESCRIPTION
**Pull request by junghans**
**Summary**

Discussion  in https://github.com/lammps/lammps/issues/2084#issuecomment-646868760, but with the `ENABLE_SANITIZER` option added, the original issue isn't valid anymore as there is a better way to enable the address sanitizer.

**Related Issues**

#2084 

**Author(s)**

@junghans 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

yesish

**Implementation Notes**

CMake only

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
this test only works for flags that are only required at compile time (and only applies them to compilation). it fails for flags that have to be provided at compile *and* link time. that is why the sanitizer flags failed it and (why the CMake script code to enable them is so messy to support CMake 3.10 to 3.12. there may be others (compilers have *far* too many flags). it also fails for flags like "--flag key=value". so there are just too many things that can go wrong either way, so i consider not checking the preferred choice.

**Comment by junghans** [comment]
Hmm, how about just checking our defaults then? (`-march=native` is a compiler flag only.)

Also if the user injects a flag that needs to added to link line as well, isn't our mechanism already broken. The flag will get injected unchecked and later lead to an error at the link stage.

**Comment by akohlmey** [comment]
applying the flag at link time is fixable (see the ENABLE_SANITIZER code). it is the test itself that is broken. i am currently not in the mood to spend more time dealing with cmake issues anymore (already spent far too much time with it in the last few weeks, including a substantial amount of time to understand and try out different ways to fix this test). i have other things on my mind and my TODO list that have a much more significant impact to LAMMPS users and that are supposed to get done or be significantly more complete for the next stable release. this and other cmake related issues can wait until we are close to the next stable release and do portability and other testing, also for unusual configurations and platforms. i am closing this now, we can look at this again in 6-8 weeks.

**Comment by Z-H-Sun** [comment]
> Hmm, how about just checking our defaults then? (`-march=native` is a compiler flag only.)
> 
> Also if the user injects a flag that needs to added to link line as well, isn't our mechanism already broken. The flag will get injected unchecked and later lead to an error at the link stage.

I was met with similar issues on powerpc. I think the proposal above is actually feasible. How about checking the machine architecture instead of checking the flag? I found a simple workaround: mfem/mfem#216 , mfem/mfem@cbb74a9.

Simply put, if `uname -m` returns x86*, `CMAKE_TUNE_FLAGS` := `-march=native`; else if returning ppc*, `CMAKE_TUNE_FLAGS` := `-mcpu=native -mtune=native`; else `CMAKE_TUNE_FLAGS` := ""

**Comment by junghans** [comment]
Ok, this is the variant, where it only injects `-march=native` into the defaults when the compiler supports it that should help for issues like #2232 as well.

@Z-H-Sun, sorry I don't implement the `-mtune` part.

**Comment by Z-H-Sun** [comment]
> Ok, this is the variant, where it only injects `-march=native` into the defaults when the compiler supports it that should help for issues like #2232 as well.
> 
> @Z-H-Sun, sorry I don't implement the `-mtune` part.

No worries. One can always opt to specify it in the `CMAKE_TUNE_DEFAULT` flag if they like. What I feel necessary is that the default CMake configuration is supposed to work regardless of the machine type--that is why I do not like the solution in d6ca98c

**Comment by junghans** [comment]
> What I feel necessary is that the default CMake configuration is supposed to work regardless of the machine type--that is why I do not like the solution in [d6ca98c](https://github.com/lammps/lammps/commit/d6ca98cb440e6b863090a53a76d05caa0a2e4cf8)

Yeah this MR sound do that now.

**Comment by akohlmey** [comment]
this change is now obsolete

**Pull request closed without merging**
