### PR TITLE
USER-DPD: Whitespace cleanup to pair_dpd_fdt_energy.cpp

### PR DESCRIPTION
**Pull request by timattox**
Axel, I seem to recall you had some script(s) to automate this sort of whitepsace normalization.  Can you share them?

### CODE REVIEW

**Comment by akohlmey** [comment]
Tim,

here is a simple one line sed command that i use most of the time for trailing blanks:
```
sed -i -e 's/ \+$//' <files to be stripped>
```

If you want to automate the process, you can add a `pre-commit` hook script to the `.git/hooks` folder. that could look like this (note, this removes space and tab characters, it may be worth adding ^M as well, if you have changes contributed by people that send text files, which often have the ^Ms added):
```sh
#!/bin/bash
#
# This hook will do some automatic checks and updates before a commit.
################################################################################
# Task 1: remove all trailing whitespace in the files about to be committed.

for f in $(git status --porcelain | sed -n -e 's/^M \+\(.*\.\(cpp\|h\|C\)\)/\1/p')
do \
  sed -i -e 's/ \+$//' -e 's/	\+$//' $f
  git add $f
done

exit 0
```

**Comment by timattox** [comment]
Thanks for the script.  I fixed up the rest of the whitespace problems in USER-DPD, AFAIK,
and added a whitespace check in my pre-commit hook script.

**Comment by stanmoore1** [comment]
The issue I fixed were tabs which I converted to spaces. Any scripts for that?

**Comment by akohlmey** [comment]
Tabs are trickier than spaces, since people may set tabs to represent 2, 4 or 8 blanks.
If i run across a file with many tabs, i usually load it into emacs, run untabify on the buffer and then re-indent the buffer. Over the years i've figured cc-mode settings that resemble steve's preferences rather closely. But this is a bit too complex to copy this here.

It might be worth exploring, if we can work out a way to have GNU indent ( https://www.gnu.org/software/indent/ ) reproduce steve's preferences so closely, that he would agree to having it applied automatically to all files before committing and thus keeping formatting consistent automatically.

**Comment by timattox** [comment]
stan, for tab indentation conversion, I used "expand -i". Not elegant, since it has no option to work "in place", but it was quick, once I identified which files had tabs using "grep -P '\t'".  Looks like a ton of files in LAMMPS/src have tabs still... but hey, I can at least keep USER-DPD "clean". :-)

**Comment by stanmoore1** [comment]
Good to know, thanks.

**Pull request merged**
