### PR TITLE
Log pizza updates

### LINKED ISSUE #3151: Log parsing and plotting in python 2
**Summary**

I am new to lammps and went to use the log parsing/plotting tools, specifically the files logplot.py and log2txt.py in lammps/tools/python/. Most of these tools are written in python 2 and some are called in a way that doesn't work on linux systems. I have a few commits that fix this, and I wanted to ask if I should open a PR for those.

**LAMMPS Version and Platform**

I'm on commit 7ea26161 and running this on Fedora 35.

**Details**

I have 3 commits that I can submit as a PR but I first wanted to run them by you to make sure they are all reasonable. This is what's included:
1. The scripts are in python 2, so they need upgrading. They also have some confusing variable names (`list` and `map`), so I have fixed those, too. However, I have upgraded only logplot.py and log2txt.py. Is it okay to submit an upgrade to just some of the scripts in this folder?
2. logplot.py calls python using `#!/usr/bin/env python -i`, which I can't get to work in linux, so I removed the -i so that it can run (non-interactively) in linux. Is that okay?
3. log2txt.py also creates a file of unnamed columns. In all use cases I can think of, it's preferable to also include column names so that humans or plotting software can more easily read it later. I would also propose to write out column names, but if you don't think that's a generally useful change, I can keep that in my own version.

### PR DESCRIPTION
**Pull request by aliehlen**
**Summary**

This updates the files logplot.py and log2txt.py in lammps/tools/python/. Most of these tools are written in python 2 and some are called in a way that doesn't work on linux systems. To address this, these three commits do the following:
1. The scripts are in python 2, so they need upgrading. They also have some confusing variable names (`list` and `map`), so I have fixed those, too. However, I have upgraded only logplot.py and log2txt.py. Is it okay to submit an upgrade to just some of the scripts in this folder?
2. logplot.py calls python using `#!/usr/bin/env python -i`, which I can't get to work in linux, so I removed the -i so that it can run (non-interactively) in linux. Is that okay?
3. log2txt.py also creates a file of unnamed columns. In all use cases I can think of, it's preferable to also include column names so that humans or plotting software can more easily read it later. I would also propose to write out column names, but if you don't think that's a generally useful change, I can keep that in my own version.  

**Related Issue(s)**

closes #3151 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes, I think that this might break compatibility with python 2. 

**Implementation Notes**

Other than upgrading to python 3, this change behavior in 2 ways:
- logplot.py does not run in interactive mode
- log2txt.py will create a log file with column names (previous behavior was that no column names were included)

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by akohlmey** [comment]
@aliehlen thanks for the submission. I have made a couple of minor changes to retain compatibility with python 2.
I think this is good to be included, but let's wait for the verdict of @sjplimp, who wrote this code originally.

**Comment by sjplimp** [comment]
@aliehlen Thanks for doing these updates for Py 3.  The code changes look basically fine.  @akohlmey Are you saying these changes now work for both Py2 and Py3.
That would be ideal if possible. 
Re: original 3 Qs:
(1) fine to only update some files
(2) The reason to launch logplot.py with -i, is that it displays a plot, which will immediately disappear if the script exits.  Maybe there is some more portable way to do this in the first line of the script?   But I think that functionality is important to preserve
(3) For log2txt.py I agree column header info is nice.  Is there a portable way to do this that can be read by all common plotting tools?  If not, I suggest doing it the way you think is best, but make it an option.  E.g. add an optional -h switch to the log2txt.py syntax (before the log.lammps arg) which also outputs the col headers.

**Comment by sjplimp** [comment]
@allehlen - note there is also a lammps/pizza repo which has log.py in it - not sure if it is identical to the log.py in the lammps/tools repo - but it would be nice to have these Py 3 updates in it as well

**Comment by akohlmey** [comment]
>  @akohlmey Are you saying these changes now work for both Py2 and Py3. That would be ideal if possible.
yes.

>  (2) The reason to launch logplot.py with -i, is that it displays a plot, which will immediately disappear if the script exits. Maybe there is some more portable way to do this in the first line of the script?

It does not disappear for me. but there is a way around it, too: 
just call [`code.interact()`](https://docs.python.org/3/library/code.html) at the end of the script.
I tested it successfully with Python3 and Python2.7.

**Comment by akohlmey** [comment]
@aliehlen are you going to add (some of) the suggested changes to this pull request? Please let us know.

**Comment by aliehlen** [comment]
@akohlmey Yes, sorry about that. I can do these, though it will be later this week or early next week, if that's okay.

**Comment by akohlmey** [comment]
> @akohlmey Yes, sorry about that. I can do these, though it will be later this week or early next week, if that's okay.

No problem. We just need to know if a person will update a pull request of if we have to do it ourselves. I want to avoid that multiple people start working on this but also that this pull request sits there and waits for people to complete it.

**Comment by aliehlen** [comment]
That makes sense!

**Comment by aliehlen** [comment]
Okay, I have added an optional switch -n to turn on the writing of column names. (The argparse packages uses -h to display a help message, so I had to pick a different letter.) I'll look to see if it's easy to apply these changes to log.py in the lammps/pizza repo now, but that will be a separate thing, but I think this was the only missing action item for this PR.

**Comment by akohlmey** [comment]
@sjplimp does this address all your concerns?

**Review by sjplimp — APPROVED** [review]
looks good - thanks to both of you for the changes

**Pull request merged**
