### PR TITLE
Tubular potential force field package for carbon nanotubes

### LINKED ISSUE #2150: Reminder: document that pair style mesocnt is part of the USER-MESONT package
**Summary**

We are starting to unbundle large files from the LAMMPS distribution and download them instead from download.lammps.org during configuration/installation of a package. First target is pair style mesocnt, which has been moved to the folder for the upcoming USER-MESONT package (PR #1873). Once that PR is merged the documentation needs to be updated to mention pair style mesocnt as well.

### PR DESCRIPTION
**Pull request by iafoss**
**Summary**

This pull request incorporates the tubular potential model (TPM) force field into LAMMPS. This force field is designed for mesoscopic simulations of interacting flexible carbon nanotubes (CNTs) and is based on representation of nanotubes as chains of stretchable cylindrical segments. Further details about this force field can be found in the references listed below and in doc files submitted with this pull request.

This pull request includes the following:

1. TPM nanotube Fortran library (mesont) developed by Alexey N. Volkov, the author of TMP force field, and used to produce results listed in the references below. This library implements basic level functions describing stretching, bending, and intertube components of the force field. Harmonic bending [1] and anharmonic bending-buckling [2] potentials, as well as segment-segment and segment-chain intertube interaction approximations [3,4] are included.

2. USER-MESONT LAMMPS package incorporating mesont Fortran library into the LAMMPS framework:

- mesont/tpm pair style implementing TPM mesoscopic force field. It includes generation of bonds, rearrangement of nanotube nodes into contiguous chains, generation of a list of neighboring chains (to support both segment-chain and segment-segment approximations of intertube interaction), and calls of corresponding mesont Fortran library functions.

- mesont atomic style designed to work with tubular representation of CNTs and use it together with TPM force field.

- mesont/Es, mesont/Eb, mesont/Et, mesont/B, mesont/Es_tot, mesont/Eb_tot, mesont/Et_tot computes to evaluate different components (stretching, bending, intertube) of the potential energy and buckling state. 

3. Potential tables parameterized for single wall CNTs with (10,10) chirality.

4. Two examples of input for simulation of a single CNT bundle and relaxation of a thin CNT film.

5. Tools:

-  TMDPotGen, the code for generation of TMP potential tables for single-walled CNTs with a given chirality (m,n).

- TMDGen, the code designed to generate initial samples composed of straight and dispersed nanotubes of given chirality and length at a given material density. The files are saved in the format compatible with mesont atomic style provided with this pull request.

- dump2vtk, the code for conversion of output from NT simulations written in *.dump format into VTK that can be visualized as a set of tubes (rather than a set of NT nodes) in Paraview or other packages (see images below).

6. Documentation describing the features provided with the pull request.

**Author(s)**

Maxim V. Shugaev, University of Virginia, mvs9t@virginia.edu
Alexey N. Volkov, University of Alabama, avolkov1@ua.edu
Leonid V. Zhigilei, University of Virginia, lz2n@virginia.edu

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues

**Implementation Notes**

A brief description of the implementation details is provided above, in the summary section, and a paper with additional implementation and verification details will be published soon. The correctness of the implementation is verified in the following tests. (1) Energy conservation in NVE simulation of CNT film relaxation performed for segment-segment and segment-chain approximations with harmonic bending potential. (2) Direct comparison of the energy evolution (with separate consideration of bending, buckling, and intertube interaction) and structures predicted by the current LAMMPS implementation and the original Fortran code developed by Alexey N. Volkov and used for the work reported in the references listed below. The simulations are performed for both harmonic bending and anharmonic bending-buckling potentials under NVE and NVT conditions. Both serial and parallel codes were verified in these sets of simulations. (3) Large parallel simulation of film relaxation (see the movie below).

The code is developed in a way to minimize its impact on other components of LAMMPS. In particular, this pull request only requires including several variables to atom.h and the corresponding code for their initiation in atom.cpp. Other additions are localized within the developed package, and no other components of LAMMPS are affected.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

[1] L. V. Zhigilei, C. Wei, and D. Srivastava, Mesoscopic model for dynamic simulations of carbon nanotubes, Phys. Rev. B 71, 165417, 2005.
[2] A. N. Volkov and L. V. Zhigilei, Structural stability of carbon nanotube films: The role of bending buckling, ACS Nano 4, 6187-6195, 2010.
[3] A. N. Volkov, K. R. Simov, and L. V. Zhigilei, Mesoscopic model for simulation of CNT-based materials, Proceedings of the ASME International Mechanical Engineering Congress and Exposition (IMECE2008), ASME paper IMECE2008-68021, 2008.
[4] A. N. Volkov and L. V. Zhigilei, Mesoscopic interaction potential for carbon nanotubes of arbitrary length and orientation, J. Phys. Chem. C 114, 5513-5531, 2010.
[5] B. K. Wittmaack, A. H. Banna, A. N. Volkov, L. V. Zhigilei, Mesoscopic modeling of structural self-organization of carbon nanotubes into vertically aligned networks of nanotube bundles, Carbon 130, 69-86, 2018.
[6] B. K. Wittmaack, A. N. Volkov, L. V. Zhigilei, Mesoscopic modeling of the uniaxial compression and recovery of vertically aligned carbon nanotube forests, Compos. Sci. Technol. 166, 66-85, 2018.
[7] B. K. Wittmaack, A. N. Volkov, L. V. Zhigilei, Phase transformation as the mechanism of mechanical deformation of vertically aligned carbon nanotube arrays: Insights from mesoscopic modeling, Carbon 143, 587-597, 2019.
[8] A. N. Volkov and L. V. Zhigilei, Scaling laws and mesoscopic modeling of thermal conductivity in carbon nanotube materials, Phys. Rev. Lett. 104, 215902, 2010.
[9] A. N. Volkov, T. Shiga, D. Nicholson, J. Shiomi, and L. V. Zhigilei, Effect of bending buckling of carbon nanotubes on thermal conductivity of carbon nanotube materials, J. Appl. Phys. 111, 053501, 2012.
[10] A. N. Volkov and L. V. Zhigilei, Heat conduction in carbon nanotube materials: Strong effect of intrinsic thermal conductivity of carbon nanotubes, Appl. Phys. Lett. 101, 043113, 2012.
[11] W. M. Jacobs, D. A. Nicholson, H. Zemer, A. N. Volkov, and L. V. Zhigilei, Acoustic energy dissipation and thermalization in carbon nanotubes: Atomistic modeling and mesoscopic description, Phys. Rev. B 86, 165414, 2012.
[12] A. N. Volkov and A. H. Banna, Mesoscopic computational model of covalent cross-links and mechanisms of load transfer in cross-linked carbon nanotube films with continuous networks of bundles, Comp. Mater. Sci. 176, 109410, 2020.

A representative image of a thin CNT film after relaxation colored based on the potential energy. The plot illustrates tube buckling (dark red regions) and formation of bundles (blue regions).
TB 0200

Relaxation of a thick CNT film composed of 8000 200 nm tubes, which corresponds to 1.6M CNT segments in total.
plot1

Schematic illustration of implementation details:
CNT

Closes #2150

### CODE REVIEW

**Comment by akohlmey** [comment]
@iafoss thanks for your submission. please note, that we are currently in a "stabilization phase" leading up to a stable release and during that we will not consider contributions like this for merging. So it will take a few weeks until we can look at this seriously. Also I will have to discuss with @sjplimp a few things about the naming of the user package and the styles to be more specific and consistent with other packages. From a cursory look, there will also be suggestions for some technical issues, e.g. the C/C++ to Fortran interfacing, compatibility with units settings and some other technical details as well as suggestions for cosmetic changes to the code and its documentation.

**Comment by iafoss** [comment]
@akohlmey , Thank you for your quick response. Let me know about modifications I need to make when you have time to carefully look into my pull request.

**Comment by iafoss** [comment]
@akohlmey , Do you have any updates on this request?

**Comment by akohlmey** [comment]
We are still working on the stable release. Will get back to you in a few
days.

--
Dr. Axel Kohlmeyer akohlmey@gmail.com http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste, Italy

**Comment by akohlmey** [comment]
FYI we recently had a discussion among the LAMMPS core developers and we have decided to merge PR #1788 before this one (or any other pull request with new atom styles). This will mean a bit more work for you to adapt, but on the other hand, it should make it simpler to write an atom style.

**Comment by akohlmey** [comment]
FYI, PR #1788 is now about to be merged after the last few minor issues are resolved. As mentioned before, this will result in additional work as it will likely result in a merge conflict.

**Comment by akohlmey** [comment]
@junghans would you mind giving a helping hand to the folks submitting this in making the CMake related changes consistent with the rest of LAMMPS?
I am currently too busy with other work (and less experienced, too).

**Comment by junghans** [comment]
> @junghans would you mind giving a helping hand to the folks submitting this in making the CMake related changes consistent with the rest of LAMMPS?
> I am currently too busy with other work (and less experienced, too).

Sure, doesn't look too far off, I think the package still needs to be added to the files in `cmake/presets/`.

**Comment by akohlmey** [comment]
@sjplimp this seems to be ready for merging now. I've updated the docs and did some other maintenance related work and tested its compilation and running the examples.
We could update the custom AtomVecMesont class to use the new scheme, but it seems to work as it is.

**Pull request merged**
