### PR TITLE
Add a quick and full regression test as GitHub Actions

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request adds two new workflows that run a quick and a full regression test as GitHub actions.
It also includes changes to the script(s) in the tools/regression-test folder to support this.

**Related Issue(s)**

N/A

**Author(s)**

Trung Nguyen, U Chicago
Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

This adds two workflows for running regression tests using the scripts in tools/regression-tests: 1) a full regression test running all example inputs and comparing the output against the references, 2) a quick regression test that tries to determine which commands or styles were changed in the pull request branch and then runs only those example inputs that include those commands. The full regression test should be triggered *after* a merge to "develop" the quick regression test on every push to a pull request that wants to be merged with develop.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included

### CODE REVIEW

**Comment by akohlmey** [comment]
@ndtrung81 Quick test is now under 10min thanks to ccache and limiting the number of tests to 100 or less.

BTW: according to GitHub documentation, we have 4 CPU cores per instance and the matrix job seem to run on separate instances. So we could install MPI into the full test instance and run with 4 MPI tasks.

I've decided to integrate the git based input finder in a similar fashion than your --analyze flag. I've added some docs, but some more may be needed. Perhaps more in the form of a Howto tutorial showing how to run different tests.

I'm done with my modifications so far and am handing it back to you. If you have question, please ping me on Slack.

**Comment by ndtrung81** [comment]
@akohlmey at the end of the test, it now shows, for instance, with `--example-folders="examples/rigid;examples/melt" `:
```
Summary:
  Total number of input scripts: 19
  - Skipped  : 0
  - Failed   : 1
  - Completed: 18
    - numerical tests passed: 11

Output:
  - Failed inputs and reasons     : failure.yaml
  - Status of the tested inputs   : progress.yaml
  - Running log with screen output: run.log
  - Testing result in JUnit XML   : output.xml
```

1) The failed inputs in `failure.yaml` would look like
```
in.rigid.gravity: { folder: examples/rigid, status: "completed, numerical checks skipped due to missing the reference log file", walltime: 1.0 }
in.rigid.nve: { folder: examples/rigid, status: "completed, 3 rel thermo checks failed", walltime: 0.0 }
in.rigid.nve.early: { folder: examples/rigid, status: "completed, 3 rel thermo checks failed", walltime: 0.0 }
in.rigid.poems: { folder: examples/rigid, status: "completed, 3 rel thermo checks failed", walltime: 2.0 }
in.rigid.poems2: { folder: examples/rigid, status: "completed, 3 rel thermo checks failed", walltime: 2.0 }
in.rigid.poems4: { folder: examples/rigid, status: "completed, 3 rel thermo checks failed", walltime: 2.0 }
in.rigid.poems5: { folder: examples/rigid, status: "completed, 3 rel thermo checks failed", walltime: 2.0 }
in.rigid.tnr: { folder: examples/rigid, status: "completed, 22 rel thermo checks failed", walltime: 13.0 }
```
Do you think we need to add more info to `failure.yaml`? 

2) The output file `progress.yaml` contains the testing outcome of all the tested inputs, with the wall time. I need to define a (nonzero) reference time, to normalize the walltimes. As we may randomly pick the inputs to run, the reference wall time should be outside of the randomly picked set, say, from running `bench/in.lj`.

3) The `run.log` contains the screen output of all the runs. We can also run with `--verbose` to have more details of the failed numerical checks and reason for error (already shown in `run.log`).

**Comment by akohlmey** [comment]
@ndtrung81 I've reverted back to serial runs. It is faster. I've also recorded a full run to get the reference data and modified the quick run to skip long or failing inputs, which makes it quite a bit faster.
This is ready as far as I am concerned.

**Review by rbberger — APPROVED** [review]

**Comment by junghans** [comment]
As discussed at the dev meeting, to cancel duplicated pending jobs one could use [concurrency groups](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency), in VOTCA we use:
```
concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}
```

**Pull request merged**
