### PR TITLE
Molecule template: molecule-IDs and fragments

### PR DESCRIPTION
**Pull request by jrgissing**
**Summary**

Add option to assign molecule IDs to molecule-template atoms, for when more than one molecule per file
also, add fragments option to molecule templates

**Related Issues**

none

**Author(s)**

JG

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

_Please state whether any changes in the pull request will break backward compatibility for inputs, and - if yes - explain what has been changed and why_

**Implementation Notes**

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@jrgissing can you explain a bit what the group feature is supposed to be used for. It does not seem to be used right now.

**Comment by jrgissing** [comment]
my use case is for reaction constraints for bond/react, to enable substituting a template-atom-ID argument with a group name. for example, to enforce an angle between side groups

**Comment by akohlmey** [comment]
> my use case is for reaction constraints for bond/react, to enable substituting a template-atom-ID argument with a group name. for example, to enforce an angle between side groups

Thanks for the explanation. I am concerned, that people will confuse this with the group command and expect molecules to be added to a given group or something similar. People often don't fully read documentation and make up something that seems reasonable to them  (and then get upset that the feature does do what they assumed it did).

How about changing the name to "fragment" instead of "group" (also in the code for clarity) to reduce the chance of a misinterpretation?
And a reference in the "molecule" documentation that this feature is meant for use with fix bond/react? If other uses come up later, this can be suitably augmented.

**Comment by jrgissing** [comment]
this is a good idea. (though perhaps i'll add a more specific reference to bond/react in an upcoming PR?)

**Comment by akohlmey** [comment]
@jrgissing this has a merge conflict now, probably due to some recent documentation cleanup. Do you want me to attempt sorting this out, or do you prefer doing it yourself? I assume this is now otherwise complete and ready for merge?

**Comment by jrgissing** [comment]
i can take a crack at it. yes, this is ready otherwise

**Pull request merged**
