### PR TITLE
Add user crslnk

### PR DESCRIPTION
**Pull request by aminaramoon**
Here is a pull request for feature branch to add a package "user-crslnk"

This package will enable users to assign correct types of bonds, angle, and dihedral (improper& proper) during bond creating as a function of types of atoms that are involved in the angle, bond or dihedral.

### CODE REVIEW

**Comment by aminaramoon** [comment]
comment

**Comment by aminaramoon** [comment]
I don't understand why the checks fails, anything I need to check to solve the problem ?

thanks

**Comment by aminaramoon** [comment]
I don't understand why the checks fails, anything I need to check to solve the problem ?

thanks

**Comment by rbberger** [comment]
Your commit c5430f46f7ebd4741f02d871251fb0a3677c918f changed the Makefile too much. See the logs in Jenkins (click "Details"): https://ci.lammps.org/job/lammps/job/pull-requests/job/serial-pr/35/console.

It seems like whatever you did causes it to try to compile with USER-INTEL. Take the latest version of the original Makefile and only add your user package. Don't try to change the defaults.

**Pull request closed without merging**
