### PR TITLE
Add support for neural network (nn) models to MLIAP package to compute energies and forces without going through Python

### PR DESCRIPTION
**Pull request by pedroantoniosantosf**
**Summary**

In this pull request, the changes were introduced in order to implement the neural networks `nn` model to the MLIAP package, with energies and forces calculated by an MLIAP without python. We included the mliap_model_nn.cpp/h files, as well as added 2 new examples in the ./examples/mliap/ folder using this new model. In order to include this new model, we also updated the documentation and the package specific README file.

Users can generate the model files from the third-party packages. For example, to train the `nn` model with the SNAP descriptors, you can check the examples in [PyXtal\_FF](https://github.com/qzhu2017/PyXtal_FF).

**Related Issue(s)**

None

**Author(s)**

Pedro Antonio Santos Florez, University of Nevada - Las Vegas (UNLV)
pedroantoniosantosf@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

 

N/A

**Implementation Notes**

## New Files Included

1. `mliap_model_nn.h`. 

Similar to the other model headers and here we define the activation functions (sigmoid, tanh, relu) and some new variables.

2. `mliap_model_nn.cpp`. 

Here we define the function to compute gradient, returning the atomic energy and dEdx. 

We also define a new `read_coeffs` function in order to read the NN parameters, according to the following structure:

```
# Neural networks parameters generated in PyXtal_FF 

# total_species nparams 
1 71 

# NET ndescriptors nlayers activation_func for layer 1, number of nodes for layer 1, ..., ..., ...., 
NET 30 3 tanh 2 tanh 2 linear 1 

# Scale0 
    98.5564567301067      0.1817576370006     -5.0513436999162      0.0453581866073     -4.4382278670569 
    -2.6985391112026     -4.9445068940273      7.8840372041149    -12.8729456412560     ...
# Scale1 
   783.0204659783215     33.6453931227955      7.9068346594951     32.2509031640463      5.6624925894670 
     5.6511565657016      8.2175114613285    108.9434600935519     16.3162547782998      ...

# Coefficients
  -0.0172776832190    0.1634820888796    0.0840977526000    0.1499173817443   -0.0789708467690 
  -0.1759660760033    0.0580901781048    0.0554623755914    0.0316677454411    ...
```

* The total parameters `nparams` corresponds to the number of coefficients, including the weights and bias values.
* The `nlayers` parameter represents the number of layers (including the hidden layers and the output layer) in the neural network. 
* The `scale0` include the minimum values and `scale1` the values of (max - min), in order to normalize the descriptors.

## Files Modified

1. `pair_mliap.cpp`. 

Here we modified the file to include the model nn.

```
#include "mliap_model_nn.h"

```

```
       } else if (strcmp(arg[iarg+1],"nn") == 0) {
         if (iarg+3 > narg) error->all(FLERR,"Illegal pair_style mliap command");
         model = new MLIAPModelNN(lmp,arg[iarg+2]);
         iarg += 3;
```

2. `mliap_data.cpp`.

Removed incorrect and useless early-exit

## How to apply the NN model in LAMMPS:

1. Reinstalled the `MLIAP package` in the `lammps/src/` folder. If you do not have the `SNA package` installed, install it first. For example:
```
make yes-mliap
make yes-snap
make yes mpi
```

2. Now, the Lammps input can support
```
pair_style mliap model nn Cu.nn.mliap.model descriptor sna Cu.snap.mliap.descriptor
```

4. Two examples for NN code can be referred in `./examples/mliap/` folder: `in.mliap.nn.Cu` and `in.mliap.nn.Ta06A`.

## Correctness was verified

* The correctness was verified comparing with results of our python package [PyXtal\_FF](https://github.com/qzhu2017/PyXtal_FF)
* The results of the examples in `./examples/mliap/` folder prior to our alterations do not change.
*  Aidan Thompson helped us to check the code and fix some issues.

No other LAMMPS features are affected by this update.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by athomps** [comment]
@pedroantoniosantosf It looks like you have included files that have not changed, and also files that do not belong in LAMMPS, probably because you did `git add mliap/*` or something similar, not a good idea.  Please remove the files that should not be included, especially `compute*.dat, *v2, *.pyz` and probably a few others.

**Comment by athomps** [comment]
@pedroantoniosantosf The files listed above seem to be the only hitchhikers. Also ./src/MLIAP/mliap_model_python_couple.pyx should stay i.e. only remove `compute*.dat, *v2`

**Review by rbberger — CHANGES_REQUESTED** [review]
CMake assumes the *.pyx files are in `src/MLIAP`, not `src/PYTHON`. It should stay in `src/MLIAP`.

https://github.com/lammps/lammps/blob/42035ef99fc156372281a13334b1775708278eaa/cmake/Modules/Packages/MLIAP.cmake#L28

**Comment by akohlmey** [comment]
> CMake assumes the *.pyx files are in `src/MLIAP`, not `src/PYTHON`. It should stay in `src/MLIAP`.
> 
> https://github.com/lammps/lammps/blob/42035ef99fc156372281a13334b1775708278eaa/cmake/Modules/Packages/MLIAP.cmake#L28

that was my bad. should be corrected now.

**Comment by akohlmey** [comment]
@athomps I noticed some inconsistent and sometimes confusing names for certain class members and temporary variables in the MLIAPData class. Since we have this PR already open and touching parts of that file, there would be an opportunity to have this sorted out right away. If you agree, we need to discuss what to change and where.

**Review by rbberger — APPROVED** [review]

**Comment by athomps** [comment]
> @athomps I noticed some inconsistent and sometimes confusing names for certain class members and temporary variables in the MLIAPData class. Since we have this PR already open and touching parts of that file, there would be an opportunity to have this sorted out right away. If you agree, we need to discuss what to change and where.

Yes, let's discuss and make these changes.

**Comment by akohlmey** [comment]
> Yes, let's discuss and make these changes.

ok, here we are:
- `MLIAPData::natoms_array` is a copy of `Atom::natoms`. That means it should be either a `bigint` or check for overflow. I have already added the check assuming that there are currently no desired to run MLIAP models on very large systems. But it would be cleaner to also call it `MLIAPData::natoms` or `MLIAPData::natoms_all`. The former name is already taken however, but read on.
- `MLIAPData::natoms` is essentially a copy of `list->inum`, but inum is probably not as good a name to export. How about `nlatoms` or `nlistatoms` or `numatoms`? When `natoms` is used inside the class functions, it can be difficult to realize that this is a copy of `list->inum` and not a copy of `atom->natoms`.
- The value of `list->inum` is cached in multiple different variable names, many times that is just used once or twice, so there is little need. Since `list->inum` is also stored in `MLIAPData::natoms` it could be using either the new name of that, or just locally stored in an `int inum` or not cached at all, if it is not used inside a loop or so.
- In many places in LAMMPS the sum of `atom->nlocal` and `atom->nghost` is stored in `nall`.

**Comment by athomps** [comment]
@akohlmey These are good suggestions. I have done the following:
- Changed `ntotal` to `nall` in `compute_mliap.cpp` and `mliap_data.cpp`
- Changed `MLIAPData::natoms` to `nlistatoms` and `natoms_max` to `nlistatoms_max`
- Changed `int MLIAPData::natoms_array` to `int MLIAPData::natoms`, kept `MAXSMALLINT` check
- Changed `list->inum` to `MLIAPData::nlistatoms`

**Comment by akohlmey** [comment]
> @akohlmey These are good suggestions. I have done the following:
> 
> * Changed `ntotal` to `nall` in `compute_mliap.cpp` and `mliap_data.cpp`
> * Changed `MLIAPData::natoms` to `nlistatoms` and `natoms_max` to `nlistatoms_max`
> * Changed `int MLIAPData::natoms_array` to `int MLIAPData::natoms`, kept `MAXSMALLINT` check
> * Changed `list->inum` to `MLIAPData::nlistatoms`

thanks. looks good. that will make it easier to review the next time. I appreciate it.
I suspect the overflow check should not be for `natoms > MAXSMALLINT` but for `ndims_force * natoms > MAXSMALLINT`. That is assuming I read the code correctly and how data is collected.

**Review by athomps — APPROVED** [review]
Looks good.  Thank you @pedroantoniosantosf

**Comment by pedroantoniosantosf** [comment]
> Looks good. Thank you @pedroantoniosantosf

Thank you also for all the assistance @athomps.

**Pull request merged**
