### PR TITLE
Update Kokkos library in LAMMPS to v3.7.0

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Update Kokkos library in LAMMPS to v3.7.0

**Related Issue(s)**

None

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by akohlmey** [comment]
@stanmoore1 please make certain you update to the latest upstream develop branch. It contains multiple fixes for issues that went undetected due to differences in package selections.

**Comment by stanmoore1** [comment]
Performance on NVIDIA looks good, testing AMD now.

**Comment by stanmoore1** [comment]
All Kokkos regression tests passed for this PR.

**Comment by stanmoore1** [comment]
AMD GPU performance looks fine too.

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
