### PR TITLE
Preserve molecule templates when using "replicate"

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

The replicate command works by creating a new instance of an Atom class and then populates it with correspondingly replicated copies of atoms and associated data from the original class and finally swaps the two and deletes the old one. Since the list molecule templates is stored as a member of the Atom class, it needs to be transferred in the process. Otherwise those "molecules" are 'lost' and the command will thus not work when using atom style "template".

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Previously molecule templates would have to recreated by re-issuing molecule commands after using "replicate". This is no longer necessary and re-issuing molecule commands for the same molecules will raise an error.

**Implementation Notes**

Since the list of molecules is independent of the number of atoms, the list of molecules is simply transferred.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by rbberger** [comment]
@akohlmey the testcases are getting unreadable. Please add some comments or use helper functions to document these endless lists of assertions please. Otherwise you'll be the only person able to read and maintain them.

**Comment by akohlmey** [comment]
> @akohlmey the testcases are getting unreadable. Please add some comments or use helper functions to document these endless lists of assertions. Otherwise you'll be the only person able to read and maintain them.

This is not as easy to do as you may think. The principle is quite simple: there are a whole lot of settings and arrays associated with an atom style and this first checks that everything is reset properly to zero/non-zero for a given style and then it creates/reads/deletes some atoms and verifies the associated data is set/unset as needed. To keep the lists from growing even longer, only selected properties are checked on subsequent tests. Since this is all depended on what data is associated with an atom style, I have yet to find a way to make this more readable. The best way to make sense of these tests is to look at them while also looking at the Atom and AtomVec classes. That is what I do.

**Comment by rbberger** [comment]
@akohlmey cleaned this up a bit and found an issue in the avec template class. Have another idea of getting rid of the assert/expects for the vectors, but that is for another day.

**Comment by akohlmey** [comment]
@rbberger @sjplimp can we merge this now? I would like to start working on adding support for "molfrac" to "create_atoms" so that it can handle templates with multiple molecules. but before starting with that I need to have the components in those two PRs merged so I won't have to do work twice and won't have to resolve merge conflicts. thanks.

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
