### PR TITLE
Fix and compute styles for calculating viscosity with periodic perturbation method

### PR DESCRIPTION
**Pull request by z-gong**
**Summary**

This is a new fix and a new compute for calculating viscosity with periodic perturbation method to be added to the USER-MISC package.

**Author(s)**

Zheng Gong, École normale supérieure de Lyon, z.gong@outlook.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No backward compatibility is broken.

**Implementation Notes**

The added fix accelerate/cos will apply a cosine acceleration in x-direction based on the z coordinates of atoms, which will generate a velocity gradient in the system. The added compute viscosity/cos will compute the generated velocity amplitude, from which the viscosity can be obtained. The compute viscosity/cos also counts for the collective velocity bias so that the temperature is correctly maintained by the thermostat.

The added function will not affect any existing functionality.

The correctness of implementation is validated by comparing the calculated viscosity of SPCE water with the results calculated with GROMACS, which also supports this method.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

The method is described in this paper
https://aip.scitation.org/doi/10.1063/1.1421362

### CODE REVIEW

**Comment by akohlmey** [comment]
@z-gong thanks for your contribution. yes, this being a small and contained contribution, adding it to USER-MISC would be preferred to making it a separate package. If there would be more related styles added at a later point, it would always be possible to move it to a separate package then.

Please note, that your branch is based on an older version of the master branch and has merge conflicts due to changes in master that were added since. so in addition to changing from your custom package to USER-MISC, you also need to merge in the head of upstream master branch and resolve any merge conflicts before this branch can be merged.

**Comment by z-gong** [comment]
@akohlmey Thank you for taking time reviewing the commits. I've moved the files to USER-MISC package and updated the docs accordingly.

**Comment by akohlmey** [comment]
> @akohlmey Thank you for taking time reviewing the commits. I've moved the files to USER-MISC package and updated the docs accordingly.

i haven't looked at the code itself yet. only checked out the comments on the github pull request page and the status of the integration testing. The real review will come later when there is more time.

**Comment by akohlmey** [comment]
@z-gong I have updated your branch to the latest master as of now. I've also resolved some minor issues with the formatting of your documentation page and make it consistent with other similar pages.
Since your method is a method to compute viscosity, you should add a quick summary of it to the Howto_viscosity.rst file and perhaps mention when it is preferred to use. In addition it would be very helpful, if you could add an input for the same system to the `examples/VISCOSITY` folder and a short section to the README file so that people can compare the results. Thanks.

**Comment by z-gong** [comment]
I've updated the How-to viscosity page. In order to follow the formula in the paper and be consistent with the implementation in GROMACS, the velocity gradient is in the z-direction. Therefore, I cannot set up an example on a 2D system. So I kept the example for SPC/E model and added a description in the README about the data extraction and the expected result.

**Comment by akohlmey** [comment]
@z-gong thanks for the update. I've made a few more cosmetic changes and updated the branch to the current master. I've also added a note to the docs about the restriction to 3d simulations and included a test in the `fix accelerate/cos` constructor.

that should make it sufficient to get it included. now we need an approval from one more LAMMPS developer to merge it.

**Comment by akohlmey** [comment]
@sjplimp @athomps can you please have a look at this? I would like to merge this for the next patch release.

**Pull request merged**
