### PR TITLE
Restricted squared cosine angle and dihedral potentials

### PR DESCRIPTION
**Pull request by evoyiatzis**
**Summary**

Implements the restricted squared cosine potentials for angle and dihedral terms as discussed in J. Chem. Theory Comput., 9 [8] 3282-3292 (2013). These terms are part of the MARTINI force field. The goal is to avoid singularities of coarse grain force fields when the angle is close to 180 degrees. It is part of [GROMACS ](https://manual.gromacs.org/current/reference-manual/functions/bonded-interactions.html#restricted-bending-potential) and I was missing this functionality in LAMMPS.

**Related Issue(s)**

None

**Author(s)**

E. Voyiatzis email - evoyiatzis@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

It will not break backward compatibility

**Implementation Notes**

The code has been manually tested and debug. Note that the GROMACS manual is not providing the correct formulas (a factor of -0.5 is missing in the original paper as well as the current online manual - it has been confirmed by the respective maintainers) 

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [ ] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@evoyiatzis I've added unit test inputs for the new styles and the dihedral one fails when newton is off, i.e. the forces are significantly different from those with newton on. Can you please check it out?

**Comment by evoyiatzis** [comment]
@akohlmey i will have a look. Thanks for spending time on the PR during the Easter period

**Comment by akohlmey** [comment]
@evoyiatzis could you figure out why I was seeing differences between newton on and off with the dihedral style?

**Comment by evoyiatzis** [comment]
No @akohlmey I have not. I hope to look into this during this weekend though

**Comment by akohlmey** [comment]
@evoyiatzis I've been trying to come up with a standalone input to reproduce the unit test failure and in the process have found out that the (randomly picked) dihedral_coeff settings for the unit test lead to too large forces which made them subject to floating-point truncation errors when summing the forces. Reducing the force constant for all dihedral types to more sane values with somewhat smaller forces recovers the test .

So it was a false alarm. My apologies. I could not find anything in the source that looked suspicious and also there were no initialization issues reported by valgrind, which made it rather unlikely that the dihedral style is to blame but rather suggested it was an issue of the tester code (or rather its input).

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
