### PR TITLE
 Time-dependent dumps for variable timestep

### LINKED ISSUE #2011: [Feature Request] Dump written every n time units for simulations with variable timestep
**Summary**

Implement an option for a dump to be written every n time units (e.g. 100 fs). 

**Detailed Description**

Currently, it is impossible to write a dump every n time units if a variable timestep is used. Such an option would be useful for visualising and analysing simulations where the timestep varies, e.g. modelling of sputtering or combustion.
I am willing to implement this, but I am not sure what is the best way to do it. I have a partial workaround (see the snippet below) which works without any change in the source code, but it has two issues:
1. It writes a dump header every `N`.
1. The accuracy (how close a frame is to a correct dump time) depends on the `N` parameter of the dump. Low `N` gives a better accuracy but slows down simulation, especially if potential energy per atom is written.  

I think the first issue can be avoided by introducing a new flag, e.g. `skip_empty`, and modify the line below, so it only writes header if there are atoms to be dumped or the flag is set to `false`:
https://github.com/lammps/lammps/blob/0711232e5b31fcf727803146636816b234283f8d/src/dump.cpp#L389

i.e.:
`if (filewriter && (!skip_empty || (skip_empty && nheader != 0))) write_header(nheader);`

I am not sure how to solve the second issue. I am also open to different implementations of this feature.

**Further Information, Files, and Links**

The snippet below writes a dump only every `n_time_every` time units:
`variable n_time_every equal 100`
`variable N equal 1`
`variable thresh atom (floor(time)%${n_time_every})`
`dump dump all atom $N dump.lammpstrj`
`dump_modify dump thresh v_thresh != LAST time yes`

### PR DESCRIPTION
**Pull request by mkanski**
**Summary**

This PR implements new dump feature which enables outputting data based on an increment of simulation time instead of timesteps. This will be useful for simulations with a variable timestep, see #2011 for more details.

**Related Issues**

Closes #2011 

**Author(s)**

Michał Kański, Jagiellonian University, michal.kanski@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues

**Implementation Notes**

Outputting dumps every `M` time units is achieved by checking at every step if the simulation time will exceed a multiply of `M` at the next step. Since the check is done at the end of a step, the value of `dt` is already updated if `fix dt/reset` is used. I also added a support for `dump_modify time` to `xyz`, `xyz/gz`, and `xyz/zstd` dump styles. 

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

Tested dump_styles:
- [x] `atom`
- [x] `atom/gz`
- [x] `atom/zstd`
- [x] `atom/mpiio`
- [ ] `atom/adios` - not tested
- [x] `cfg`
- [x] `cfg/gz`
- [x] `cfg/zstd`
- [x] `cfg/mpiio`
- [x] `custom`
- [ ] `custom/adios` - not tested
- [x] `custom/gz`
- [x] `custom/zstd`
- [x] `dcd` - disabled, because it assumes a constant dt
- [ ] `h5md` - I couldn't get it to work, even without time-dependent dumping (segmentation fault)
- [x] `image`
- [x] `local`
- [x] `molfile`
- [x] `movie`
- [ ] `netcdf` - I couldn't get it to work, even without time-dependent dumping. Exits with error:
`ERROR on proc 0: NetCDF failed with error 'NetCDF: Unknown file format' (while accessing 'traj.nc')  in line 297 of /home/michal/Research/LAMMPS/development/src/USER-NETCDF/dump_netcdf.cpp. (src/USER-NETCDF/dump_netcdf.cpp:1030)`
- [ ] `netcdf/mpiio` - I couldn't get it to work, even without time-dependent dumping (segmentation fault)
- [ ] `vtk` - not tested, installing `libvtk` requires installing about 200 different packages as well
- [x] `xtc` -  disabled, similar like for `dcd`
- [x] `xyz`
- [x] `xyz/gz`
- [x] `xyz/zstd`
- [x] `xyz/mpiio`

### CODE REVIEW

**Comment by sjplimp** [comment]
What is the syntax for this command(s)?

**Comment by sjplimp** [comment]
Also, please explain (here) the logic for how/when you trigger a compute like
compute pe/atom needed for dump output, when you
don't know the tilmestep it will be needed?

**Comment by akohlmey** [comment]
> Also, please explain (here) the logic for how/when you trigger a compute like
> compute pe/atom needed for dump output, when you
> don't know the tilmestep it will be needed?

@sjplimp please note the discussion on issue #2011 which has some background info about this and why it is implemented as an alternate style instead of incorporating it into the existing dump styles. The motivation is that with the `dump_modify every` option one can do an approximation of a time based regular output without impacting efficiency, but this implementation will sacrifice efficiency (e.g. by triggering computes more often) to have a closer match to the desired output freqency.

**Comment by akohlmey** [comment]
> What is the syntax for this command(s)?

I guess what @sjplimp is trying to say here is: please add some documentation for the new dump styles.

**Comment by mkanski** [comment]
I'm sorry for a late response. 
The syntax is as follows:
for xyz: `dump ID group-ID xyz/time N file time_frequency`
for custom: `dump ID group-ID custom/time N file args time_frequency`

Having `time_frequency` as the last argument for `dump custom` is unintuitive, but this way I can derive `dump custom/time` from `dump custom` with only a slight change in the line below (reducing `narg` by one, so the last argument is not used in the constructor of `DumpCustom`:
https://github.com/lammps/lammps/pull/2025/files#diff-142799967bd154845398930bde5878c2R41-R42
I would prefer that `time_frequency` was the first argument after `file`, but I haven't found a clean way to implement it. Also, the meaning of `N` is a little bit different - now it is a frequency of a check whether a dump should be written. 

The check for computes works as follows:
The new class contains three new variables:
`time_every` - a time frequency of a dump
`next_time` - a double which stores next simulation time at which dump should be written (a multiple of `time_every`)
`write_time` - a variable needed for preparing computes; it can have three values: `1`- do not write, `-1` - write next time, `0` - write now 

Each `N` the dump is triggered as a normal one. However, the `count()` function has been modified. It now checks whether the simulation time plus timestep is higher than `next_time` (line 89 in `dump_custom_time.cpp`). If it is not, than it returns 0, and nothing is written to the dump. More importantly, the computes used in the dump are not updated every `N`, because it is done in `DumpCustom::count()` which is only triggered when the simulation time(+dt) is higher than `next_time` (line 107). If the condition is met, a new step is added to the computes (line 94 and 97) and `next_time` is set to `-1`, so the next time the dump is triggered it will be written with computes updated.

There is a small overhead here, because computes are updated twice as often as they should - at the correct step (triggered by lines 94 and 97) and the next one (through `DumpCustom::count()` invoked on the correct step), but I don't think it can be prevented.

**Comment by sjplimp** [comment]
@mkanski and @akohlmey Thanks for working on this.  I agree this is useful feature
to add to the code.

As I understand it there are 3 issues:

(a) how to know in advance the right timestep to perform the dump
(b) how to insure computes needed by the dump
     like pe/atom, stress/atom are invoked when needed, but not otherwise
     since these are expensive operations within the pair style
(c) how to code this so it works for all dump styles

An additional point.  I believe the only current way to change the timestep during a run is with fix reset/dt?  If this is the case, then b/c fix reset/dt operates at end-of-step() and output happens after that, it means you do know on step N, whether you need to do output on step N+1.  B/c you know exactly what the time will be at the end of step N+1.

So if the user specifies I want do ouput every DT and check every Mth step, you could check every Mth step, and decide if the next step is an output step.  If no, just return (do nothing until next Mth step).  If yes, trigger the computes to fire on the next step, then do output at the end of the next step.  If the user sets M to 1, I think this is exactly accurate, and is low overhead (no extra computations of energy/virial).

There is also the issue of changing the timestep between runs or within the loop of a "run every" with some logic that re-issues the timestep command.  But I think worst case
this would do output one step later than the Mth step, so that would be OK?

So how does that sound for a solution to (a) and (b) ?

Re (c): I don't see that making derived class versions of each dump style to support this is a good idea.  I think the decision to write a snapshot or not is best made outside the dumps, so that they need know nothing about it.  Thus I think the way you were starting to do this before is better.  I.e. as a check in Output::write().  Then this option will work as-is with all dump styles.  And the syntax of the dump commands are unchanged.  I.e. don't add an arg at
the end of the dump custom fields.

So add a dump modify option, like vtime (for variable time).  This could be a number.  Or even a variable that computes the next time, like nevery allows.

In Output::write(), I agree with Axel that the logic is getting messier as we add options.  But the logic is pretty similar for dumps, restarts, thermo.  So maybe some of that code duplication could be simplified.  And then this variable time option could be added to all 3 output options.

E.g. each of the 3 outputs call the same function to determine if the next step is the time to do output.  This would also create the opportunity to be more clever (in that function) about predicting the time that ouput is needed, so you don't have to check every timestep.  E.g. if nexttime - currenttime >> dt, then check a large number of steps from now, when the interval gets smaller, check more often.  Leveraging the fact that timesteps may get tiny, but there is no way they are going to get huge.

**Comment by sjplimp** [comment]
There might also be a way to flag dumps that need per-atom energy or viral, so
that unflagged dumps don't need to wait until step M+1 for output.  They
would be output on the Mth step if current time exceeds the specified time interval.

**Comment by sjplimp** [comment]
@mkanski Thank you for refactoring this more similar to its previous mode of operation.  I'm trying to read the code and verify it does what I expect.  But there are subtleties and I realize I don't know what you expect it to do!  The doc page is not yet sufficient to explain these details.  So here are my conceptual Qs:
(1) Should this work with every dump style (about 20 of them)?  Except DCD, which should prohibit its use b/c it requires equi-spaced snapshots.
(2) If you specify M as the check interval, you should get a dump file on each multiple-of-M step that exceeds the time interval?  What if the interval is less than M steps (with a current large timestep)?  Then do you miss one or more snapshots, but nothing else should be screwed up?  
(3) If computes are used by the dump then should your snapshots be on the M+1 step, not M?  E.g. if M = 10, and your time interval was exactly M steps, you would get snapshots on steps 11,21,31,etc ?
(4) Is this true if the dump uses any compute, or only the ones that require energy/virial ?  What does the comment about atom-variables that use computes are not yet supported mean?  Not seeing why that is.
(5) Related to variety of dump styles and file formats, is the idea to add the floating-point time as an extra field to each per-snapshot header.  I.e. does that need to be done to support that style?  If so, I'm wondering if there might be some other independent way to output info mapping dump time steps to "elapsed time" when doing variable timestepping, so we don't have to do that.

If it would be easier to discuss these details by phone, we can do that ... if so, might be helpful to have @akohlmey  involved.  Thanks

**Comment by sjplimp** [comment]
@mkanski Don't know if you've had a chance to read my recent Qs on this PR?
No rush on my part, just checking to see if we can move forward to getting this
released.  Thanks ...

**Comment by mkanski** [comment]
First of all, I'm sorry for not responding earlier. I have been writing my PhD thesis for the last few months, so I didn't have time to work on this. I've already passed all required exams and I'm finishing the thesis itself, so I believe I can go back to work on this PR in about a month. Then I'll answer your questions and we can schedule a meeting. Is that okay?

**Comment by sjplimp** [comment]
@mkanski No problem at all.  Good luck on the writing and congrats on your degree!

**Comment by akohlmey** [comment]
@mkanski can you please update us on the status of this PR.

**Comment by mkanski** [comment]
@akohlmey I'm sorry for the delay, but I gravely underestimated the time required to finish my PhD... I'm introducing the final corrections to the thesis and I will be able to get back to work on this PR in about two weeks.

**Comment by akohlmey** [comment]
@mkanski please note that this pull request has now merge conflicts that need to be resolved first

**Comment by mkanski** [comment]
I finally have some time to work on this PR. I came to a conclusion that there's little gain in allowing users to set the check interval, so now it is set to 1 (i.e. the check is performed every timestep). It also makes the implementation easier. 

To answer @sjplimp questions:
(1) Personally, I use only `dump xyz` and `dump custom`, so they are the only ones which are supported for now. I don't have much experience with other dump styles, but if the implementation isn't complicated, I can add it.
(2) (3) These two questions are what made me consider whether there were any advantages of check intervals other than 1. I found none, so I changed the code. Now the check is performed at every step which makes these two questions obsolete.
(4) Currently, at each step there is a check testing whether at the next step the snapshot should be written (line 1213 in dump.cpp). If so, all necessary computes are set to be, well, computed at the next step. I don't remember why I add this comment about atom-style computes. They do work correctly, so I deleted the comment.
(5) No, the information about the time doesn't need to be added, however I think it would be useful. In the current version, the time isn't written by default to snapshots. I don't see any other (easy) way of saving the information about the time. I see two more difficult solutions:
1. Adding a similar option to output every `n` time units for fixes and using `fix print`.
2. Saving information about the time to a separate file.

Things I still need to do in this PR:
- [ ] Handle the case when `dt` is larger than `2*time_interval`.
- [ ] Check if the behaviour is correct when `run every` is used
- [ ] Check if dumping information from fixes work
- [ ] Return an error if computes/fixes perform averaging
- [ ] Check the behaviour when `reset_timestep` is used
- [ ] Disable this feature for unsupported `dump_styles`

Is there anything I forgot about?

**Comment by mkanski** [comment]
I believe this feature is finally finished and ready for review. I haven't tested some dump styles, either because using them ended in errors or segmentation faults (probably some library mismatch?), or because enabling them would take more time than I wanted to spend on it. I disabled the new feature for those dump styles.

**Comment by akohlmey** [comment]
@sjplimp this is waiting for you to look at, please assign to me when you are done

**Comment by mkanski** [comment]
Hi. I used this code recently and actually it never really worked for custom dumps which output computes. The script I used for testing this had a line which invoked computes every timestep. When I deleted the line, LAMMPS exited with an error saying that the compute hadn't been calculated on the current timestep.

The situation is as follows. Normally, a custom dump is written at a given timestep:
https://github.com/lammps/lammps/blob/1a4511bb8db2ec6555e82805f7e015b08bd4248d/src/output.cpp#L293
and `invoked_flag` is set for every compute used by the dump:
https://github.com/lammps/lammps/blob/1a4511bb8db2ec6555e82805f7e015b08bd4248d/src/dump_custom.cpp#L585-L587
Next, a new timestep is added to the invocation list of computes:
https://github.com/lammps/lammps/blob/1a4511bb8db2ec6555e82805f7e015b08bd4248d/src/output.cpp#L305
**BUT** this is done only for the computes which were actually invoked in this timestep:
https://github.com/lammps/lammps/blob/1a4511bb8db2ec6555e82805f7e015b08bd4248d/src/modify.cpp#L1447-L1449

This works only if one knows the next timestep when the computes should be calculated. The idea I had for this PR to work was to check at each timestep if the dump should be written on the next timestep. When the condition is met, `Modify::addstep_compute()` is invoked, but it doesn't actually work correctly, because the computes haven't been calculated on this timestep, so `invoked_flag` isn't set and new timestep isn't added.

A workaround I found (commit 98e8b59) was to set all computes to be calculated on the next timestep, using `Modify::addstep_compute_all()`. This introduces a small overhead, because not all of them have to be calculated, but I think there are no larger repercussions. Please correct me, if I'm wrong.

**Comment by sjplimp** [comment]
@mkanski I have a couple ideas on this invoking compute issue and also possibly a way to avoid checking
every step.  I will try them out locally to see if there are unforseen issues.

**Pull request closed without merging**
