### PR TITLE
Add support to detect incomplete restart files and insufficient diskspace conditions

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request modifies the restart file format so that incomplete restart files can be detected on reading.
It also adds a new option to fix halt to detect how much disk space is available and thus provide an option to stop a run before storage runs out.
Finally, when writing restart files, the error status from previous writes is checked with `ferror()` before the restart file is closed and LAMMPS will exit reporting an I/O error in that case.

**Related Issues**

Tries to address some of the issues discussed in #934 

**Author(s)**

Axel Kohlmeyer (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

The changes to the restart file format are done in such a fashion, that old restart files can still be read.

**Implementation Notes**

This adds writing a second copy of the restart file magic string to the end of a binary restart file, and code to check for its presence and correctness, for new restart files.

It also adds (platform specific) code to `fix halt` to allow stopping a simulation when free disk space is running below a given threshold. Right now only Linux support is available.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by stanmoore1** [comment]
Would also be nice to check the `errno` from fwrite. It would just be in one or two places in `write_restart`.

**Comment by akohlmey** [comment]
> Would also be nice to check the `errno` from fwrite. It would just be in one or two places in `write_restart`.

For that I will implement `utils::sfwrite()` similar to `utils::sfread()` in a separate pull request.

**Comment by akohlmey** [comment]
> > Would also be nice to check the `errno` from fwrite. It would just be in one or two places in `write_restart`.
> 
> For that I will implement `utils::sfwrite()` similar to `utils::sfread()` in a separate pull request.

But for the time being, checking the return value of `fwrite()` when writing the magic string and testing with `ferror()` for any I/O errors before closing the file descriptor would cover most cases. Writing restarts and data files are "messy" since the write statements are scattered all over the place, so writing a wrapper for `fwrite()` is the cleaner option.

**Comment by stanmoore1** [comment]
Write_restart already has a few wrappers around fwrite. This one writes out the bulk of the data like atom coors and would be most likely to fail: https://github.com/lammps/lammps/blob/master/src/write_restart.cpp#L720.

**Comment by akohlmey** [comment]
> Write_restart already has a few wrappers around fwrite. This one writes out the bulk of the data like atom coords and would be most likely to fail: https://github.com/lammps/lammps/blob/master/src/write_restart.cpp#L720.

That is not really a "wrapper" but the core of restart writing, i.e. not the header. This will also call the various restart writing functions in all kinds of styles. The logic is a bit tricky because of the different output options (multi-file, MPI-IO, single file) and having to do an MPI call for the cleaner `error->all()` instead of calling `error->one()`. So checking with `ferror()` before `fclose()` seems like the safest option without adding much code.

**Comment by stanmoore1** [comment]
I added something like this when I was having trouble with data corruption:

```c++
size_t wrote = 0;
wrote = fwrite(vec,sizeof(double),n,fp);
if (wrote != n) {
  long lost = (n-wrote)*sizeof(double);
  printf("Lost %ld bytes, errno = %i\n,lost,errno);
  perror("Invalid write in write_double_vec");
}
```

But it would be cleaner in `utils::sfwrite()`. Just would be really nice to get the errno and perror it.

**Comment by akohlmey** [comment]
> But it would be cleaner in `utils::sfwrite()`. Just would be really nice to get the errno and perror it.

to the best of my knowledge, neither `fwrite()` nor `ferror()` set `errno` all you can tell is that you have a short/failed write.

**Comment by stanmoore1** [comment]
At least on POSIX systems, fwrite() sets errno, see https://stackoverflow.com/questions/5081599/fwrite-putting-error-indicator-on-stream-in-c. Also fwrite() calls write() which sets errno, at least in some cases:
https://stackoverflow.com/questions/37344556/in-linux-fwrite-command-does-not-set-errno-how-to-get-proper-errno-on-failure-c

**Comment by stanmoore1** [comment]
Also from http://man7.org/linux/man-pages/man3/fwrite.3p.html:

```
 The fwrite() function shall return the number of elements
       successfully written, which may be less than nitems if a write error
       is encountered. If size or nitems is 0, fwrite() shall return 0 and
       the state of the stream remains unchanged. Otherwise, if a write
       error occurs, the error indicator for the stream shall be set, and
       errno shall be set to indicate the error.
```

**Pull request merged**
