### PR TITLE
Fix bug introduced in commit 2af907a, and added in option to compute_bond_local to calculate bond velocities and kinetic energies

### PR DESCRIPTION
**Pull request by efremdan1**
I think these are supposed to be swapped.

### CODE REVIEW

**Comment by timattox** [comment]
If this is a correct fix (which it looks to be, IMHO), it would also need to be applied to the other instance in src/group.cpp around line 1680 as well.  But I am not familiar with this area of LAMMPS, and do not know how to test these changes.

**Comment by efremdan1** [comment]
Good point. Fixed that too.

**Comment by akohlmey** [comment]
Please break this down into two separate pull requests. You are addressing two very different issues here. I am very tempted to remove the code in those two places and instead place a generic (corrected) 3x3 matrix inversion into the math_extra.h include...

**Comment by timattox** [comment]
efremdan1 and akohlmey, when I manually apply the two "fix-only" changes from above, the bug introduced via 2af907a is repaired for my USER-DPD tests.

**Comment by efremdan1** [comment]
Sorry about that, I'm new to open-source. It's been broken down into #169 and #170. I think I'd agree with you about having a function for matrix inversion, given that it's used in group.cpp, compute_omega_chunk.cpp, and now compute_bond_local.cpp.

**Pull request closed without merging**
