### PR TITLE
Add compute ave/sphere/atom

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Add new `compute ave/sphere/atom` (along with Kokkos version) that computes local density and temperature using neighbors of atom i inside a sphere (cutoff distance specified by user).

**Related Issue(s)**

None

**Author(s)**

Stan Moore (SNL), original concept from Mitch Wood (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

**Implementation Notes**

Verified by comparing to OVITO

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by stanmoore1** [comment]
@sjplimp @akohlmey this is ready to merge from my point of view. Future work could include adding pressure or even making a general spherical averaging compute that can take in other computes/fixes, similar to `compute chunk/atom`.

**Comment by akohlmey** [comment]
@sjplimp should this be in src or rather in EXTRA-COMPUTE? I am leaning toward the latter.

Also, I am not overly happy with the name of this compute. I am concerned that there would be significant potential for people misunderstanding what it does and then asking confusing questions or being confused by the output. On the other hand, I cannot think of anything that is short and would be better. The best I can think of would be "local/phase/atom".

**Comment by akohlmey** [comment]
> The best I can think of would be "local/phase/atom".

I just need to complain and a better idea comes to mind. :-(
If this **will** be expanded to perform local averaging of data, then a) it could be called `localavg/atom` and then it would also be justified to leave it in src.

**Comment by stanmoore1** [comment]
>If this will be expanded to perform local averaging of data, then a) it could be called localavg/atom and then it would also be justified to leave it in src.

I would prefer `spherical/atom` or something like that.

**Comment by sjplimp** [comment]
How about compute ave/sphere/atom, similar to the fix ave/* commands.

**Comment by akohlmey** [comment]
> How about compute ave/sphere/atom, similar to the fix ave/* commands.

That would work for me. A bit verbose, but allows to include variants that e.g. average over other shapes.

**Comment by stanmoore1** [comment]
I'm fine with `ave/sphere/atom` and I'm fine if it goes into `EXTRA-COMPUTE` for now. Should I rename the files?

**Comment by stanmoore1** [comment]
What about `compute property/sphere`?

**Comment by sjplimp** [comment]
It has to end in /atom b/c it produces a per-atom quantity.  I think ave/sphere/atom is more descriptive.

**Comment by stanmoore1** [comment]
Sounds good. Should it go in `EXTRA-COMPUTE` or stay in `src`? @akohlmey what is the criteria for `EXTRA-COMPUTE` anyway, seems sort of arbitrary, similar to USER packages...

**Comment by akohlmey** [comment]
> Sounds good. Should it go in `EXTRA-COMPUTE` or stay in `src`? @akohlmey what is the criteria for `EXTRA-COMPUTE` anyway, seems sort of arbitrary, similar to USER packages...

It is a bit of a sliding scale and based on personal preferences. In src are base and commonly used functionality. In the EXTRA- folders more unusual ones. E.g. compute rdf is in src and compute adf is in EXTRA-COMPUTE.
This one close to the boundary but I think putting it in EXTRA-COMPITE will be better for now. If this becomes a frequently used feature, we can move it any time.

**Comment by sjplimp** [comment]
The motivation for EXTRA was simply to keep the src dir small.  I'd say EXTRA-COMPUTE for now.  We can always
move it into src later, or make a AVE-SPHERE package if there becomes several related computes.

**Comment by stanmoore1** [comment]
OK, this will create a new dependency between KOKKOS and EXTRA-COMPUTE, that is OK right?

**Comment by stanmoore1** [comment]
@akohlmey @sjplimp I made the changes, can you please review? Thanks

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
