### PR TITLE
Add Kokkos package option to build atom map in serial on CPU

### LINKED ISSUE #4075: [BUG] Major performance regression in Special.build() component of replicate at large scale (512 nodes+)
**Summary**

When replicating a molecular system (atom_style real), Special.build (from special.cpp) is called to build 1-2, 1-3, 1-4 lists and perform tagging. At the end of the `dedup` and `combine` methods called during this process, the `atom->map_set` function is called.

When using Kokkos backend, this is implemented in `src/KOKKOS/atom_map_kokkos.cpp`. This was recently refactored as part of commit #806af53, which resulted in a **25x slowdown at scale** on the GPUs when compared to the `stable_23Jun2022_update4` version of LAMMPS. When using the Serial backend of Kokkos, the performance is actually improved between these two commits, so this seems like it could possibly be a Kokkos performance bug. Non-Kokkos atom mapping is also performing well at scale.

By use of internal code timers and tracing libraries, we have identified the following chunk of code inside of `map_set` as taking >95% of this replicate time at scale **only on rank 0** (line 198):
```
  mapSorter.create_permute_vector(LMPDeviceType());
  mapSorter.sort(LMPDeviceType(), d_tag_sorted, 0, nall);
  mapSorter.sort(LMPDeviceType(), d_i_sorted, 0, nall);
```
All other ranks complete this section of code in less than 5 seconds, but rank 0 takes 300+ seconds. I suspect rank imbalance, but I haven't dealt with Kokkos code enough to be able to identify the exact issue.

Note that profiling libraries often flag this as an MPI issue with either Barrier or Allreduce, but that's just a red herring because the other ranks are all waiting on rank 0, and the waiting happens to be in MPI synchronization.

Performance data provided at the bottom of this ticket.

**LAMMPS Version and Platform**

Current develop branch tested on OLCF's Frontier and Summit. Data at the bottom of this ticket is provided from Summit, but similar (and worse scaling) has been observed on Frontier.

**Expected Behavior**

Performance-neutral or improved performance from stable_23Jun2022_update4 to current.

**Actual Behavior**

25x slow-down at scale.

**Steps to Reproduce**

[w32k.data.gz](https://github.com/lammps/lammps/files/14250604/w32k.data.gz)
Data file attached (bulk water system with 98,304 atoms). Replicate this 4x4x4 to get a single-node sized problem, 8x8x8 to get the 8-node problem, etc., since scaling is done in powers of 8. Replication is done by defining the `nx, ny, nz` variables at run-time. Input file:
```
variable        nx index 1
variable        ny index 1
variable        nz index 1

units           real
atom_style      full
pair_style      lj/cut/coul/long 9.0
bond_style      harmonic
angle_style     harmonic
kspace_style    pppm 1.e-5
kspace_modify   collective yes

read_data       w32k.data.gz
include         spce.ff.lmp

replicate       ${nx} ${ny} ${nz} bbox
```

**Further Information, Files, and Links**

On Summit, we run 6 MPI ranks per node (1 V100 per rank), and this problem is weak-scaled with 6.29 million atoms per node (~1mil atoms per rank).
**This table provides the time it takes to replicate, and in parentheses the time that the Special build takes.**

|           What         | Nnodes |   current develop   | stable_23Jun2022_update4 |
| ---------------------- | ------ | ------------------- | ------------------------ |
| Default CPU-based      | 1      | 1.042  (0.699)      | 1.010 (0.653)            |
| Default CPU-based      | 8      | 1.269  (0.772)      | 1.188 (0.708)            |
| Default CPU-based      | 512    | 1.444  (0.784)      | 1.296 (0.730)            |
| Default CPU-based      | 4096   | 6.206  (4.037)      | 10.091 (5.338)           |
| Serial-Kokkos          | 1      | 5.241  (4.681)      | 13.093 (1.140)           |
| Serial-Kokkos          | 8      | 5.637  (4.958)      | 13.170 (1.226)           |
| Serial-Kokkos          | 512    | 6.153  (5.401)      | 19.515 (1.290)           |
| Serial-Kokkos          | 4096   | 13.12  (8.333)      | 25.454 (1.970)           |
| GPU-Kokkos             | 1      | 4.798  (4.296)      | 3.731 (1.145)            |
| GPU-Kokkos             | 8      | 5.078  (4.433)      | 3.933 (1.213)            |
| GPU-Kokkos             | 512    | 16.194 (13.269)     | 5.716 (1.903)            |
| GPU-Kokkos             | 4096   | 423.27 (331.1)      | 16.378 (4.815)           |

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Add Kokkos package option to build atom map in serial on CPU

**Related Issue(s)**

Fixes #4075

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
@hagertnl most of the necessary changes are here, but it hangs on V100, still need to debug tomorrow.

**Comment by stanmoore1** [comment]
@hagertnl this is passing my tests now, can you give it a try? Just FYI, using `-pk kokkos atom/map no` is slower than `-pk kokkos atom/map device` (default) with a hash map on a single V100. I also tested against the `stable_23Jun2022_update4` version of LAMMPS and this PR is a little faster for `-pk kokkos atom/map no` than the stable, so I think this will restore the performance from before. But I only tested on V100 not Frontier.

**Comment by hagertnl** [comment]
Pulling down now! I'll give it a quick test run on Summit just for apples-to-apples comparison then run it on Frontier. Thanks Stan!

**Comment by hagertnl** [comment]
My first attempt at 4096 Summit nodes hit:
```
Finding 1-2 1-3 1-4 neighbors ...
  special bond factors lj:    0        0        0
  special bond factors coul:  0        0        0
     2 = max # of 1-2 neighbors
[a07n02:1154766:0:1154766] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8f0006)
==== backtrace (tid:1154766) ====
 0 0x0000000000069e84 ucs_debug_print_backtrace()  ???:0
 1 0x00000000106d7018 LAMMPS_NS::Special::onethree_build()  /gpfs/alpine2/stf243/proj-shared/hagertnl/olcf6/lammps/build/lammps/src/Obj_summit_gpu/../special.cpp:411
 2 0x00000000106de078 LAMMPS_NS::Special::build()  /gpfs/alpine2/stf243/proj-shared/hagertnl/olcf6/lammps/build/lammps/src/Obj_summit_gpu/../special.cpp:125
 3 0x00000000100e9998 LAMMPS_NS::Replicate::command()  /gpfs/alpine2/stf243/proj-shared/hagertnl/olcf6/lammps/build/lammps/src/Obj_summit_gpu/../replicate.cpp:814
 4 0x00000000100a97a0 LAMMPS_NS::Input::execute_command()  /gpfs/alpine2/stf243/proj-shared/hagertnl/olcf6/lammps/build/lammps/src/Obj_summit_gpu/../input.cpp:868
 5 0x00000000100aa1a0 LAMMPS_NS::Input::file()  /gpfs/alpine2/stf243/proj-shared/hagertnl/olcf6/lammps/build/lammps/src/Obj_summit_gpu/../input.cpp:313
 6 0x0000000010016490 main()  /gpfs/alpine2/stf243/proj-shared/hagertnl/olcf6/lammps/build/lammps/src/Obj_summit_gpu/../main.cpp:77
 7 0x0000000000029f5c generic_start_main.isra.0()  ???:0
 8 0x000000000002a0f4 __libc_start_main()  ???:0
=================================
```

**Comment by stanmoore1** [comment]
OK I was testing with rhodo, let me try the water system

**Comment by stanmoore1** [comment]
Actually I can reproduce a segfault on multiple GPUs, will debug

**Comment by hagertnl** [comment]
I turned `special_bonds lj/coul 1 1 1` on and it bypassed the seg-fault for the moment. I got the following timing:
```
Replication is creating a 64x64x64 = 262144 times larger system...
  orthogonal box = (-49.901276 -49.901276 -49.901276) to (6337.462 6337.462 6337.462)
  24 by 32 by 32 MPI processor grid
  bounding box image = (-1 -1 -1) to (1 1 1)
  bounding box extra memory = 17.75 MB
  average # of replicas added to proc = 87.35 out of 262144 (0.03%)
  25769803776 atoms
  17179869184 bonds
  8589934592 angles
Finding 1-2 1-3 1-4 neighbors ...
  special bond factors lj:    1        1        1
  special bond factors coul:  1        1        1
     2 = max # of 1-2 neighbors
     2 = max # of special neighbors
  special bonds CPU = 2.223 seconds
  replicate CPU = 4.671 seconds
```
Almost a 100x speedup!

**Comment by stanmoore1** [comment]
>Almost a 100x speedup!

Great. Just a note, we typically don't try to optimize initialization/setup time (unless it is really huge) because we assume that a user is going to timestep for 12 or 24 hours, so ~7 minutes is negligible compared to that time. But I understand that your benchmark is including init time...

**Comment by hagertnl** [comment]
No problem there -- we aren't really considering the init time in the benchmark, but we just need the total walltime of the benchmark to be reasonable, and when the init time was an order of magnitude longer than the core compute time, that was getting to be a barrier.

**Comment by stanmoore1** [comment]
OK makes sense. I think I'll have the segfault fixed soon, give me a bit.

**Comment by hagertnl** [comment]
I also hit this error with `atom/map no`, which I don't hit it with `atom/map device`:
```
Finding SHAKE clusters ...
ERROR: Overflow output in rendezvous_a2a (../comm.cpp:1151)
Last command: fix             1 all shake 1e-6 500 0 b 1 a 1
Completed with exit code: 1
```

**Comment by stanmoore1** [comment]
I think it is the same bug. One thing you will want to check carefully is if `atom/map no` slows down the "Loop time" (even though it speeds up the initialization time), since it is rebuilding the atom map on the host every reneighbor during the run too, not just at the beginning.

**Comment by stanmoore1** [comment]
@hagertnl segfault should be fixed now

**Comment by hagertnl** [comment]
Can confirm! Able to get to the run stage now, waiting on timings now. Summit's per-timestep numbers are a bit wonky, so I may just bring it to Frontier and look at the timesteps/s there.

**Comment by stanmoore1** [comment]
Here is what I'm seeing on our V100 testbed and rhodo:
```
device.txt:Loop time of 9.05245 on 4 procs for 100 steps with 2048000 atoms
host.txt:Loop time of 11.716 on 4 procs for 100 steps with 2048000 atoms
stable.txt:Loop time of 14.4525 on 4 procs for 100 steps with 2048000 atoms

device.txt:  special bonds CPU = 0.010 seconds
device.txt:  special bonds CPU = 3.617 seconds
host.txt:  special bonds CPU = 0.008 seconds
host.txt:  special bonds CPU = 3.809 seconds
stable.txt:  special bonds CPU = 0.006 seconds
stable.txt:  special bonds CPU = 0.650 seconds
```

**Comment by stanmoore1** [comment]
That is with `hash` atom map. No doubt the "at-scale" behavior will be different, but hopefully this will keep the init time from blowing up like before.

**Comment by stanmoore1** [comment]
If the "Loop time" does slow down on Frontier, I have an idea on how to speed up the init time while keeping the "Loop time" fast, let me know what you see....

**Comment by hagertnl** [comment]
Single-node with 21 million atoms:
```
atom/map no: Loop time of 36.7712 on 8 procs for 50 steps with 21233664 atoms
atom/map device: Loop time of 35.1953 on 8 procs for 50 steps with 21233664 atoms
```
8-node with 170 million atoms:
```
atom/map no: Loop time of 50.9662 on 64 procs for 50 steps with 169869312 atoms
atom/map device: Loop time of 49.8619 on 64 procs for 50 steps with 169869312 atoms
```
64-node with 1.35 bil atoms:
```
atom/map no: Loop time of 127.175 on 512 procs for 100 steps with 1358954496 atoms
atom/map device: Loop time of 125.51 on 512 procs for 100 steps with 1358954496 atoms
```
Looking pretty good from an atom mapping perspective so far. The replicate times are showing similar trends -- atom/map no is a few percent longer than atom/map device. I'll keep you posted as I go up.

**Comment by stanmoore1** [comment]
>Looking pretty good from an atom mapping perspective so far. The replicate times are showing similar trends -- atom/map no is a few percent longer than atom/map device. I'll keep you posted as I go up.

Great thanks, I'm really curious to know if the Loop time will have a similar slowdown as replicate at scale with `atom/map device` vs `host`

**Comment by hagertnl** [comment]
Our 4096 node job finished in excellent time -- using 87 billion atoms, we see about a 3x speedup from some older source (I think comparable to `stable` branch) on a 25 billion atom problem. Only 21 seconds to replicate the whole system. Very impactful change there. I'll also go ahead and toggle the atom/map keyword and re-send the job just to get apples to apples comparison.

**Comment by stanmoore1** [comment]
@hagertnl good to hear, hopefully it will be even faster once we get some better device sorting options from Kokkos (work in progress).

**Comment by hagertnl** [comment]
4096 comparison of atom/map no vs device:

```
atom/map no:

special bonds CPU = 19.981 seconds
replicate CPU = 21.825 seconds
find clusters CPU = 15.307 seconds
Loop time of 69.6271 on 32768 procs for 50 steps with 86973087744 atoms

atom/map device:
special bonds CPU = 1349.085 seconds
replicate CPU = 1684.824 seconds
find clusters CPU = 1017.171 seconds
Loop time of 311.07 on 32768 procs for 50 steps with 86973087744 atoms
```
So with 87 bil atoms on 32K MPI ranks, we see about a 4.5x speedup in Loop time by use of atom/map no.

**Comment by stanmoore1** [comment]
@hagertnl Good to know, thanks. @akohlmey This is ready to merge from my POV.

**Comment by hagertnl** [comment]
It looks like I'm still having issues on the V100's with the latest commits -- ~~a single-node~~ 8-node run on Summit with 50mil atoms just hangs with:
```
Setting up Verlet run ...
  Unit style    : real
  Current step  : 0
  Time step     : 0.5
```

**Comment by stanmoore1** [comment]
OK I will take a look

**Comment by stanmoore1** [comment]
@hagertnl I can't reproduce the hang on 8 nodes x 4 GPUs per node, can you post `spce.ff.lmp` from https://github.com/lammps/lammps/issues/4075 just to be sure we are using the same files?

**Comment by hagertnl** [comment]
I was just about to report back. This appears to be a Summit problem, not a LAMMPS issue. There was some issue with the GPU-aware compatibility of the modules I had loaded. I've run with this stack before, so I'm not sure why it's causing me issues now, but turning off GPU-aware MPI or downgrading CUDA version both work around the issue.

**Comment by stanmoore1** [comment]
Ah yeah, Kokkos bundled with LAMMPS requires CUDA 11.1 or earlier on Summit, unless you turn off `cudaMallocAsync`, then you can use 11.2. Any newer version of CUDA than this is broken with GPU/aware MPI and MPS using Spectrum MPI

**Comment by hagertnl** [comment]
> and MPS

I'm only running 1 rank per GPU, would this still be affected? Yeah I was trying cuda/11.7.1.
For some reason, I thought that has worked for me before, it's quite possible I'm mistaken though.

**Comment by stanmoore1** [comment]
Yes last I checked even 1 rank per GPU is broken with GPU-aware for cuda/11.7.1, with or without MPS. Last I heard from OLCF Help:

```
IBM officially only supports up to 11.1 with Spectrum 10.4. We have a ticket open with IBM but it's unclear what their timeline is for a fix.
```

From my personal experience 11.2 worked as well with GPU-aware MPI, unless you turn on MPS and then it hangs. However with the latest Kokkos version, you have to disable `cudaMallocAsync` or 11.2 is now broken with GPU-aware too. So that leaves 11.1 which works unconditionally.

**Comment by hagertnl** [comment]
Ah. Summit's newest stack (as of January 2024) includes `spectrum-mpi/10.4.0.6-20230210`, which is supposed to fully support CUDA/11.7.1. This would be the first case I've encountered of it not supporting CUDA/11.7.1.

**Comment by stanmoore1** [comment]
Ah haven't tried that yet. It still could be an issue with `cudaMallocAsync`--that is currently broken on ALCF Polaris with Cray MPICH, even with a later CUDA like CUDA 11.8 for example. Could try compiling with `-DKokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC:BOOL=OFF` if using CMake or `KOKKOS_CUDA_OPTIONS = "enable_lambda,disable_malloc_async"`  if using Makefile

**Comment by hagertnl** [comment]
That worked for me. So looks like the same issue you mentioned. I'll work internally to try to get that confirmed and documented so that folks don't have to bang their heads into a wall.

**Comment by stanmoore1** [comment]
Nick here are some related issues:
https://github.com/openucx/ucx/issues/7194
https://github.com/kokkos/kokkos/issues/4228

Part of me just wants to disable `cudaMallocAsync` in LAMMPS since it causes a lot of headaches. It did give a ~10% speedup for one benchmark (bead-spring) but was mostly performance neutral in other benchmarks...

**Review by akohlmey — APPROVED** [review]

**Review by ndtrung81 — APPROVED** [review]

**Review by athomps — APPROVED** [review]
The `atom/map no` completely fixes a slowdown that was seen when running with an atom map versus without. For 92M atoms on 4096 GPUs on Frontier, the slowdown was roughly 2x and even greater on larger node counts. 

The default setting of `atom/map device` should be added to the bottom of the doc page.

**Comment by stanmoore1** [comment]
>The default setting of atom/map device should be added to the bottom of the doc page.

It's a little buried at the bottom but it is there: https://github.com/lammps/lammps/pull/4079/files#diff-993a5e06aef266e691d81005dbe68e99fa50a4ab629479479441e6a05af7d3a5R737

**Comment by akohlmey** [comment]
@stanmoore1 I have changed the formatting of the Defaults section to make those settings stand out more.

**Pull request merged**
