### PR TITLE
KOKKOS Package bugfix: Workaround for issue #1037

### LINKED ISSUE #1037: KOKKOS package error when an MPI rank has no atoms
When running the KOKKOS package on a GPU and when an MPI rank has no atoms, the following error can occur: 
```
Cuda const random access View using Cuda texture memory requires Kokkos to allocate the View's memory.
```
This is due to an issue in the Kokkos library and has been reported to Kokkos developers: https://github.com/kokkos/kokkos/issues/1691. It would be good to patch this before the stable release.

### PR DESCRIPTION
**Pull request by stanmoore1**
## Purpose
Workaround that fixes #1037.

## Author(s)
Stan Moore (Sandia)

## Backward Compatibility
No issues.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@rbberger @akohlmey it looks like there was an error with Jenkins doc tests and it needs to be restarted before this PR can be merged. Any way to make this less fragile?

**Comment by akohlmey** [comment]
I don't think there is a problem with Jenkins. Docs **are** broken and
@sjplimp must have merged his doc refactoring PRs without paying attention.
I notified him and he said, it'll be fixed with the next PR...
Just pull the master and do 'make html' in the doc folder.

That said, we had two power failures in the machine room hosting he Jenkins
server. Not sure what that has done to the state of the Jenkins machine.

Nevertheless, docs need to be fixed.

Axel.

--
Dr. Axel Kohlmeyer  akohlmey@gmail.com  http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste. Italy.

**Comment by stanmoore1** [comment]
@akohlmey If not already, in GitHub Settings -->Branches-->Branch protection rules, can we "Require status checks to pass before merging", i.e. why can't we require Jenkins tests to pass before PRs are allowed to merge? Seems like that would have prevented this issue.

**Comment by akohlmey** [comment]
Please discuss this with @sjplimp. I am not in the mood for this right now.



--
Dr. Axel Kohlmeyer  akohlmey@gmail.com  http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste. Italy.

**Comment by stanmoore1** [comment]
Looks like the docs are fine--the Jenkins test finally passed. The failed tests were due to connection issues, see https://ci.lammps.org/job/lammps/job/pull-requests/job/build-docs-pr/1523/console, probably from the power outages. @sjplimp said he would never knowingly merge a PR unless the merge button was "green" i.e. all the tests passed, and he would be fine with enforcing the checks. Except what happens when the test is broken and he needs to merge in a PR to fix it but can't merge since the test doesn't pass? Sort of a catch-22...

**Comment by sjplimp** [comment]
@akohlmey  and @stanmoore1 I don't think the "Merge pull request" button is green
unless all tests have passed (see PR #1036).  I don't think I ever push Merge
if it's not green (at least that I can recall).  Are you saying an incorrect link
in the doc pages will fail the check?  If so, how would we fix it now w/out a new PR?
Why is the button green now on this PR?

**Comment by rbberger** [comment]
@sjplimp @stanmoore1 as Axel mentioned, we had two power failures within 72 hours which shook things up a bit.

**Comment by stanmoore1** [comment]
@rbberger no worries, that is understandable

**Pull request merged**
