### PR TITLE
Add streamlined version of fix sgcmc from USER-VCSGC package

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This imports the `fix sgcmc` command from the USER-VCSGC package into the LAMMPS distribution.
This version has optional features removed and was updated to be compatible with the current internal interfaces and some coding style conventions

**Related Issue(s)**

N/A

**Author(s)**

Original author:  Alexander Stukowski
Updates for integration into LAMMPS: Aidan Thompson, SNL and Axel Kohlmeyer, Temple U.

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

N/A

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] One or more example input decks are included

**Further Information, Files, and Links**

Original source code is at: https://gitlab.com/materials-modeling/vcsgc-lammps
Original documentation is at: https://vcsgc-lammps.materialsmodeling.org/

### CODE REVIEW

**Comment by akohlmey** [comment]
@athomps as discussed here is a first draft of the imported code. I may make a few more programming style changes, but most were already done in the lammps-plugin version. Example is imported (and adjusted to be a shorter run with less frequent output but with a larger system, so it can be run with 4 MPI processes) and documentation, too (citations are missing currently).

**Comment by akohlmey** [comment]
@athomps this is now completed as far as I am concerned. Please have a look and either let me know what additional changes you want me to do or implement them yourself, and how you want to proceed with this.

**Comment by athomps** [comment]
This looks pretty good. I verified that the original code:

`git@gitlab.com:materials-modeling/vcsgc-lammps.git`
`commit 09b960a81fd3754af4f464bf1ecbedccb54531d3`

matches the new output on the new example for np1 and np4.

**Comment by akohlmey** [comment]
> matches the new output on the new example for np1 and np4.

So what is the next step?

**Review by athomps — APPROVED** [review]
I approve.

**Pull request merged**
