### PR TITLE
Collected small changes and bugfixes

### LINKED ISSUE #3253: Reduce warnings when compiling LAMMPS
**Summary**

Try to reduce warnings when compiling LAMMPS

**Detailed Description**

Here are some warnings I see with GCC 8.3.1, CUDA 11.6.0

```
../fmt/format.h:2450:90: warning: declaration ‘class std::system_error’ does not declare anything
 FMT_API auto vsystem_error(int error_code, string_view format_str,
```

```
In file included from ../style_kspace.h:12,
                 from ../lammps.cpp:27:
../pppm_disp.h:30: warning: "LMP_FFT_LIB" redefined
 #define LMP_FFT_LIB "KISS FFT"
 
In file included from ../style_kspace.h:8,
                 from ../lammps.cpp:27:
../pppm.h:30: note: this is the location of the previous definition
 #define LMP_FFT_LIB "cuFFT"
```

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request collects small changes and bugfixes.

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Implementation Notes**

The following individual changes are included:
- add more fixes for issues with `dump_modify every/time`
- return null when querying `Modify` for fixes or computes with a non-existing index
- silence compiler warnings
- consolidate all generic FFT library related settings, defines, and typedefs into a single new header file. Fixes #3253
- plug small memory leak in fix electrode/thermo
- documentation updates on the state of VisualStudio support and native Windows compilation
- update src/.gitignore for recently added files and packages
- implement a "make no-installed" target that executes faster than "make no-all" if only a few packages are installed

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp this PR now has a "make no-installed" target for the GNU make build.

**Comment by sjplimp** [comment]
thanks - I will use it a lot!

**Review by stanmoore1 — APPROVED** [review]

**Comment by sjplimp** [comment]
@akohlmey Actually, is there some reason not to make the new "make no-installed", just be a replacement for "make no-all" ?
The end state is the same with either, correct?  Seems like the new one would almost always be quicker.

**Comment by stanmoore1** [comment]
>Actually, is there some reason not to make the new "make no-installed", just be a replacement for "make no-all" ?
I second this suggestion

**Comment by akohlmey** [comment]
> @akohlmey Actually, is there some reason not to make the new "make no-installed", just be a replacement for "make no-all" ? The end state is the same with either, correct? Seems like the new one would almost always be quicker.

I mentioned this already in our email conversation. The end state is only the same if there was no problem or error with any of the make-yes-package or make no-package done earlier. This is not only about copying files but also about editing the Makefile.settings etc. Make no-installed will only process packages with copied files. Only "make no-all" will make certain that **everything** is reset properly if something went wrong.

**Comment by stanmoore1** [comment]
Can we add an abbreviation `make ni` or `make noi` similar to the existing `make pi` abbreviation for `make package-installed`?

**Comment by sjplimp** [comment]
yes, I like the abbrev idea

**Comment by sjplimp** [comment]
maybe "make no-pi" or "make cake" ...

**Comment by stanmoore1** [comment]
I'm fine with either `make no-pi` or `make noi`

**Comment by akohlmey** [comment]
"make my-day"?

**Comment by akohlmey** [comment]
The option most consistent with the other abbreviations would be "make ni", which reminds me of Monty Python and the Holy Grail: https://www.youtube.com/watch?v=zIV4poUZAQo

I personally have no preference. Just let me know which you want.

**Comment by sjplimp** [comment]
"make ni" is indeed consistent - bonus points for M Py ref

**Pull request merged**
