### PR TITLE
Documentation and Build script and Info updates for stable release

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request collects various updates and changes to get LAMMPS ready for the stable release. This is predominantly including updates and corrections to the manual and build/install scripts.

**Author(s)**

Axel Kohlmeyer an Richard Berger (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

The following individual changes are included:
- includes and thus closes #1893 
- includes and thus closes #1903 
- Add a new "mode=print" setting to the conventional build, where you can get information about the compiler and linker flags in used when compiling and linking LAMMPS. Particularly useful when linking with LAMMPS as a library
- Add an `make html-offline` command to allow building the html documentation in a form so that the embedded math can be viewed when offline. This requires internet access to download MathJax when building the offline version for the first time.
- Add a script to check that all packages are listed in the overview tables
- Update embedded math to be compatible with the "imgmath" html_math_renderer, which recovers the correct generation of ePUB format manual.
- Rewrite of the USER-QMMM support in CMake to not include the pwqmmm.c source and thus avoid dependencies on the QE libraries. Enforce enabling of `BUILD_LIB` and recommend building a shared library when enabling the USER-QMMM package
- Update the README for the qmmm library to cover both CMake and traditional make and include more details of the process
- Remove mentioning of SVN/subversion for following LAMMPS development. The existing access through GitHub's svn emulation remains in place, so existing users are not affected. We just don't mention it anymore so usage will hopefully die away some time.
- Most of the LAMMPS input script examples will use syntax highlighting
- Fixes to issues from the txt2rst conversion
- Correcting, updating, and expanding this documentation for building LAMMPS as a library and how to link a calling code to it with examples for CMake and tranditional make builds.
- Updating basic build documentation to reflect the current options and procedures and describing the CMake and traditional make variants in a more consistent fashion
- Replacing several cases of `.. parsed-literal` in the documentation with preformatted text to use the `.. code-block` directive instead for better typesetting and syntax highlighting.
- convert the remaining math formula pictures to use embedded math

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by evoyiatzis** [comment]
at pair_coul.rst line 375: the sentences about pair styles should be in plural.

**Comment by akohlmey** [comment]
@sjplimp this PR has now multiple things, that we should talk over.

**Comment by rbberger** [comment]
@akohlmey btw, there is an option in the Sphinx theme to only show the LAMMPS logo, so LAMMPS doesn't show up twice in the navigation:

doc/utils/sphinx-config/conf.py:
```python
html_theme_options = {
    'logo_only': True
}
```

**Comment by akohlmey** [comment]
> @akohlmey btw, there is an option in the Sphinx theme to only show the LAMMPS logo, so LAMMPS doesn't show up twice in the navigation:
> 
> doc/utils/sphinx-config/conf.py:
> 
> ```python
> html_theme_options = {
>     'logo_only': True
> }
> ```

Thanks, I will check it out.

**Pull request merged**
