### PR TITLE
[BUGFIX] Scaling of cdof for fix ave/chunk norm all

### PR DESCRIPTION
**Pull request by ssande7**
**Summary**

When calculating temperature, fix ave/chunk uses (cdof + Natoms*adof) as the degrees of freedom. However, under norm all, Natoms is the number of atoms summed over all samples, while cdof isn't scaled accordingly. The difference is apparent in the attached input script, which uses a single system-wide chunk to compute temperature, setting cdof to -2 to match the temperature compute used by fix nvt. Using norm sample produces the correct temperature measurement, whereas norm all reports a temperature that is slightly too low (most obvious in smaller systems with long averaging periods). This bugfix adds a scaling factor to cdof of Nrepeats in the case that norm all is used. Running the same input script with this bugfix produces identical temperature output with norm all and norm sample, as would be expected.

**Related Issue(s)**

None.

**Author(s)**

Stephen Sanderson - University of Queensland

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [ ] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**
Example script with output from old and new versions
[cdof_bug.tar.gz](https://github.com/lammps/lammps/files/6146739/cdof_bug.tar.gz)

### CODE REVIEW

**Comment by sjplimp** [comment]
@ssande7 Good catch on this.  I think this is the case but want to verify.  This change will work if the # of atoms in a particular chunk varies from one sampling interval to the next?

**Comment by ssande7** [comment]
Thanks @sjplimp. I think this change should make things consistent between norm all and norm sample. Norm sample calculates the temperature as:
T = Sum_samples(Sum_atoms(m*v*v) / (k_B * (cdof + N_atoms * adof))) / N_samples
and norm all now calculates it as:
T = Sum_samples(Sum_atoms(m*v*v)) / (k_B * Sum_samples(cdof + N_atoms*adof))

There is the interesting question though of whether a degrees of freedom per chunk is a definable quantity when the number of atoms per chunk isn't consistent between chunks, since two chunks with a different number of atoms but the same cdof would report a slightly different temperature even if the KE per atom was fixed across the system. In the extreme case, a chunk with a very low number of (or no) atoms could end up with <= 0 DoF, and report a nan or negative temperature. This is consistent between norm all and norm sample though, and can be inferred from the documentation of fix ave/chunk. In such cases, I think DoF corrections are more appropriately applied via adof than cdof.

**Comment by sjplimp** [comment]
Thanks for the clarification. I think the only thing this lacks is some added text on the fix ave/chunk doc page. I think the way it is now, the description of nsample all and the formulas for DOF(adof,cdof) and the description of the cdof,adof keywords would make a user think it was computed the old way. (Which makes sense since I probably wrote the code and the doc info to match).  So if we are changing that to your new formula, then the doc page should explain that is how it is done when nsample all is used.

**Comment by ssande7** [comment]
My first interpretation of the documentation was that this was already the intended behaviour, but upon re-reading I see your point. I've updated the norm all doc text to hopefully clarify.
Another thing I noticed though is that there may be some interesting interactions with the 'ave running' option, which I'll look into quickly now.

**Comment by ssande7** [comment]
> Another thing I noticed though is that there may be some interesting interactions with the 'ave running' option, which I'll look into quickly now.

I couldn't see anything obvious in the code that would cause issues, and a quick test with the included script from above (modified to use ave running) gave identical results for norm sample and norm all so I think it's ok, but someone more familiar than I am with that bit of code should probably double check.

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
