### PR TITLE
Add support for testing pair styles in the GPU package

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This extends the pair style tester tool to run tests for styles in the GPU package.

**Related Issues**

#2307 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

This is missing tests for splitting the calculation between CPU and GPU and for running the neighbor list build on the CPU.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by rbberger** [comment]
Once merged, I could switch the unit test container to the GPU-enabled one to run these.

**Comment by akohlmey** [comment]
> Once merged, I could switch the unit test container to the GPU-enabled one to run these.

This needs work and I don't expect to be doing that for a while. I mostly made this available quickly to allow using the tests that work so that further changes to the GPU kernels for those can be done with some confidence and without having to construct tests manually for them. But it requires some really ugly changes to input templates, so I am not even convinced that this is the route to go for GPU enabled testing.

**Comment by rbberger** [comment]
Looking at the output on my machine, there are a lot of issues with large deltas (OpenCL, default settings).

```
17: Test command: /home/richard/GitHub/lammps/lammps/build3/unittest/force-styles/test_pair_style "/home/richard/GitHub/lammps/lammps/unittest/force-styles/tests/mol-pair-beck.yaml"
17: Environment variables: 
17:  LAMMPS_POTENTIALS=/home/richard/GitHub/lammps/lammps/potentials
17:  PYTHONPATH=/home/richard/GitHub/lammps/lammps/unittest/force-styles/tests:
17: Test timeout computed to be: 1500
17: [==========] Running 7 tests from 1 test suite.
17: [----------] Global test environment set-up.
17: [----------] 7 tests from PairStyle
17: [ RUN      ] PairStyle.plain
17: [       OK ] PairStyle.plain (8 ms)
17: [ RUN      ] PairStyle.omp
17: [  SKIPPED ] PairStyle.omp (0 ms)
17: [ RUN      ] PairStyle.gpu
17: /home/richard/GitHub/lammps/lammps/unittest/force-styles/test_pair_style.cpp:855: Failure
17: Expected: (err) <= (epsilon)
17:   Actual: 3.7439515126086566e-06 vs 3.7500000000000002e-13
17: /home/richard/GitHub/lammps/lammps/unittest/force-styles/test_pair_style.cpp:856: Failure
```

**Comment by akohlmey** [comment]
> Looking at the output on my machine, there are a lot of issues with large deltas (OpenCL, default settings).
> 
[...]

> So yeah, it will be more work.

please seem my comment about that in the discussion for PR #2307. those are likely bugs in the GPU pair style and not the tester. my comment here about needing work was in reference to the tester tool itself.

**Comment by rbberger** [comment]
To save some debugging: one of the errors in the KSpaceStyle tests is
```
ERROR: Cannot (yet) do analytic differentiation with pppm/gpu (src/GPU/pppm_gpu.cpp:137)
```

**Comment by akohlmey** [comment]
updated to latest master and include bugfixes and updates from PR #2313

**Comment by akohlmey** [comment]
updated to latest master and fix a few issues like truncated creation dates. all .yaml files recreated.

**Comment by akohlmey** [comment]
@ndtrung81 this PR is slowly approaching a state where it can be seriously considered for inclusion. We have by now sufficient introspection and flexibility in the test inputs to be able to run tests at least on a subset of the inputs. But the tests put a lot of strain on "management" of restarting, data files etc. and with rather small and sometimes "difficult" inputs, they trigger quite a few issues. Apparently more with CUDA than with OpenCL. When you have some time, please contact me directly so that we can talk in person about a strategy for addressing the remaining issues.

**Comment by akohlmey** [comment]
@ndtrung81 I have updated this to the latest master, fixed a few minor issues and am now checking again which tests will run and which will need to be skipped. So far, things look quite promising. With current list of skipped tests, there are no more GPU memory access issues using the CUDA backend, only some failures due to (small) floating point math differences (for mixed and double precision). Will check OpenCL next and also try to re-enable tests that were flagged to be skipped.

**Comment by ndtrung81** [comment]
@akohlmey thanks for the updates and for adding these unit tests.

**Review by sjplimp — APPROVED** [review]

**Comment by akohlmey** [comment]
@ndtrung81 here is a status update on the GPU testing (and implicitly on the status of the GPU package).
All enabled tests pass for CUDA and OpenCL with double precision (mixed/single still needs some tweaks for precision).
All tests with tabulated long-range coulomb need to be skipped due to numerical differences, but the non-tabulated ones pass.
All tersoff tests fail with memory errors, so those styles still need to be corrected after the latest updates to the GPU package.
Also lj/charmm/coul/charmm fails with a GPU memory access error, so there seems to be a bug in there too.
I have fixed a few more issues where I could track down the problems myself, so I will merge this PR now and we can look into the remaining issues later. The problematic tests are now skipped via adding "gpu" to the "skip_tests" field in the test yaml file.

**Comment by ndtrung81** [comment]
Maybe @wmbrownIntel can help with the failed tests with tersoff*/gpu. I attach here a simple input script that produces the crashes both with OpenCL and CUDA builds, with either neigh no and neigh yes. The memory access issues seem to be related to the  three_end kernel.

[in.threebody.txt](https://github.com/lammps/lammps/files/6306006/in.threebody.txt)

**Comment by wmbrownIntel** [comment]
@ndtrung81 Yes, this was my fault. I added a pull request #2711 that should fix the issue. If charm/coul/charm is still failing can you send me the reproducer for that, I will likely be going on extended leave soon. Thanks.

**Comment by akohlmey** [comment]
> @ndtrung81 Yes, this was my fault. I added a pull request #2711 that should fix the issue. If charm/coul/charm is still failing can you send me the reproducer for that, I will likely be going on extended leave soon. Thanks.

@wmbrownIntel I've check out your PR #2711 and it does indeed resolve the issues we were seeing in the unittest runs with tersoff/gpu, so I am enabling those in the corresponding YAML inputs.

Pair style lj/charmm/coul/charmm, however, is still failing. I am attaching the input that is assembled by the unittest tool that fails. For comparison, I am also attaching a similar input for lj/cut/coul/cut which does not generate the failure. I can reproduce this with both the CUDA and OpenCL backend.

The failure with -sf gpu also produces messages like the following the "dmesg" output from the Linux kernel:
```
[419927.633671] NVRM: Xid (PCI:0000:01:00): 31, pid=1815051, Ch 00000019, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_1 faulted @ 0x0_00000000. Fault is of type FAULT_PDE ACCESS_TYPE_READ
[420446.764261] NVRM: Xid (PCI:0000:01:00): 31, pid=1816059, Ch 00000018, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_1 faulted @ 0x0_00000000. Fault is of type FAULT_PDE ACCESS_TYPE_READ
```

[out.fails.txt](https://github.com/lammps/lammps/files/6332571/out.fails.txt)
[out.works.txt](https://github.com/lammps/lammps/files/6332572/out.works.txt)
[log.works.txt](https://github.com/lammps/lammps/files/6332573/log.works.txt)
[in.works.txt](https://github.com/lammps/lammps/files/6332574/in.works.txt)
[in.fails.txt](https://github.com/lammps/lammps/files/6332575/in.fails.txt)
[data.fourmol.txt](https://github.com/lammps/lammps/files/6332576/data.fourmol.txt)

**Comment by wmbrownIntel** [comment]
@akohlmey @ndtrung81 Thanks Axel for the files. I committed another fix to PR #2711 that should fix this issue.

**Pull request merged**
