### PR TITLE
Fix element mapping and a few other issues for interlayer potentials 

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This addresses some issues in multiple interlayer potentials in the USER-MISC package, that would crash when used in setups with additional elements. example shown on [lammps-users](https://sourceforge.net/p/lammps/mailman/message/36659505/)

**Author(s)**

Axel Kohlmeyer (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This will disallow incorrect use of `pair_coeff` statements and `pair_modify shift` statements with these pair styles, that were previously accepted.

**Implementation Notes**

Processing of `pair_coeff` did not enforce using only '* *' type assignment arguments and would lead to incorrect flagging of pairs of atom types with setflag, which in turn will lead to incorrect neighbor (skip) lists, which will lead to segfaults when looking up non-existing parameters. This PR applies similar procedures as with other manybody potentials that require '* *' coeff settings. 

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by oywg11** [comment]
@akohlmey Thanks for fixing this bug. I just downloaded and compiled the new codes and found it works when including an extra element except for B, N, C and H. So I approve for ilp/graphene/hbn and kolmogorov/crespi/full. However, for kolmogorov/crespi/z, it's actually a two-body potential like lj/cut since it does not calculate the local normals. Thus, for this pair_style, it's better to keep as it's original form.

**Comment by akohlmey** [comment]
> @akohlmey Thanks for fixing this bug. I just downloaded and compiled the new codes and found it works when including an extra element except for B, N, C and H. So I approve for ilp/graphene/hbn and kolmogorov/crespi/full. However, for kolmogorov/crespi/z, it's actually a two-body potential like lj/cut since it does not calculate the local normals. Thus, for this pair_style, it's better to keep as it's original form.

This has nothing to do with many-body vs. pairwise-additive nature of the potential, but how LAMMPS builds neighbor lists for pair style hybrid and hybrid/overlay. when assigning parameters with an element map, enforcing the 'pair_coeff * *' syntax is a must or else there will be segmentation faults from trying to access non-existing parameter sets.

**Comment by oywg11** [comment]
> > @akohlmey Thanks for fixing this bug. I just downloaded and compiled the new codes and found it works when including an extra element except for B, N, C and H. So I approve for ilp/graphene/hbn and kolmogorov/crespi/full. However, for kolmogorov/crespi/z, it's actually a two-body potential like lj/cut since it does not calculate the local normals. Thus, for this pair_style, it's better to keep as it's original form.
> 
> This has nothing to do with many-body vs. pairwise-additive nature of the potential, but how LAMMPS builds neighbor lists for pair style hybrid and hybrid/overlay. when assigning parameters with an element map, enforcing the 'pair_coeff * *' syntax is a must or else there will be segmentation faults from trying to access non-existing parameter sets.

What I concerned is to calculate the energy and force correctly. If one uses "pair_coeff * * kolmogorov/crespi/z  CC.KC      C C", then with the present codes, it also calculates the interaction for the carbon atoms within the same layer, which should be avoided. If you think the above formula is the correct way to call this potential, then the molecule id should be also introduced to this pair_style to skip the calculation of the KC interaction within the same layer. This is true also for pair lebedeva/z.

**Comment by akohlmey** [comment]
> > > @akohlmey Thanks for fixing this bug. I just downloaded and compiled the new codes and found it works when including an extra element except for B, N, C and H. So I approve for ilp/graphene/hbn and kolmogorov/crespi/full. However, for kolmogorov/crespi/z, it's actually a two-body potential like lj/cut since it does not calculate the local normals. Thus, for this pair_style, it's better to keep as it's original form.
> > 
> > 
> > This has nothing to do with many-body vs. pairwise-additive nature of the potential, but how LAMMPS builds neighbor lists for pair style hybrid and hybrid/overlay. when assigning parameters with an element map, enforcing the 'pair_coeff * *' syntax is a must or else there will be segmentation faults from trying to access non-existing parameter sets.
> 
> What I concerned is to calculate the energy and force correctly. If one uses "pair_coeff * * kolmogorov/crespi/z CC.KC C C", then with the present codes, it also calculates the interaction for the carbon atoms within the same layer, which should be avoided. If you think the above formula is the correct way to call this potential, then the molecule id should be also introduced to this pair_style to skip the calculation of the KC interaction within the same layer. This is true also for pair lebedeva/z.

ok, i see your point.

**Comment by akohlmey** [comment]
@oywg11 i've restored the old `coeff` function with one small tweak. setflag is not set for pairs of types, where one or both types are mapped to NULL in the hybrid pair style. this should take care of avoiding segfaults from accessing non-existing parameters as well. in addition, i noticed another inconsistency, restartinfo needs to be set to 0 for these styles, but not all did. thanks for pointing out the lebedeva style. that i have aligned with the other settings as well. and also updated the examples using rebo in the docs for the change in the rebo potential that just got merged to master.

**Pull request merged**
