### PR TITLE
Refactor CMake configuration

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

This is an effort to refactor the CMake configuration by moving code from the main configuration file into utility functions and include files.

Over time this main file has grown to almost 2000 lines, up to the point where it is hard to see what it is actually doing, even for people who originally worked on it. This brings it back down to about 720 lines.
A large chunk of package configurations is now placed in `cmake/Modules/Packages/*.cmake` files. 

Not perfect, it's still a beast, but hopefully a step in the right direction.

**Author(s)**

@rbberger (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by junghans** [comment]
Is there a reason you didn't move
https://github.com/lammps/lammps/blob/e788d326781bec8e6fac44596a4fce87c3c9f11e/cmake/CMakeLists.txt#L230-L287
and
https://github.com/lammps/lammps/blob/e788d326781bec8e6fac44596a4fce87c3c9f11e/cmake/CMakeLists.txt#L464-L480
to separate files?

However if we are going to create one file per package, it might be better to just put a `CMakeLists.txt` in each package directory, which is more the CMake standard.

**Comment by rbberger** [comment]
@junghans no reason, just didn't get to it yet. I wanted to get some feedback.

I'll experiment with your suggestion of moving the CMakeLists.txt to each package folder. The primary reason I did it this way is to preserve the variable scopes and keep stuff in the `cmake` folder. I'll need to see the pro and cons.

**Comment by akohlmey** [comment]
> I'll experiment with your suggestion of moving the CMakeLists.txt to each package folder. The primary reason I did it this way is to preserve the variable scopes and keep stuff in the `cmake` folder. I'll need to see the pro and cons.

don't think it is such a good idea to move cmake files into package folders. it will just needlessly scatter them. it is not like we have a hierarchical build where the build is recursing through folders to do independent builds in each of them. instead we have one "flat" build for the LAMMPS executable. it seems much more logical to me to keep all files for that in the cmake folder or a subfolder.

**Comment by junghans** [comment]
> > I'll experiment with your suggestion of moving the CMakeLists.txt to each package folder. The primary reason I did it this way is to preserve the variable scopes and keep stuff in the `cmake` folder. I'll need to see the pro and cons.
> 
> don't think it is such a good idea to move cmake files into package folders. it will just needlessly scatter them. it is not like we have a hierarchical build where the build is recursing through folders to do independent builds in each of them. instead we have one "flat" build for the LAMMPS executable. it seems much more logical to me to keep all files for that in the cmake folder or a subfolder.

If we don't have a fully all-in-one `CMakeLists.txt` anyhow, I honestly think more naturally to have the `CMakeLists.txt` next to the Makefile, instead of hidden away in the `cmake/` folder, so that changes can be directly compared.

In retrospective we should create the lammps target first and just add packages to it with `target_sources` and `target_link_libraries` would be rid of a lot of issues, however that would need at least cmake-3.

**Comment by akohlmey** [comment]
> If we don't have a fully all-in-one `CMakeLists.txt` anyhow, I honestly think more naturally to have the `CMakeLists.txt` next to the Makefile, instead of hidden away in the `cmake/` folder, so that changes can be directly compared.

this goes contrary to my experience with the various Install.py files in the lib tree. it has become a bit of a nightmare to keep them all consistent and avoid duplicated or non uniform code, especially when other developers, that maintain packages and their libraries, make changes to them, that are not consistent, since they only look at the folder that they consider themselves responsible for.

**Pull request merged**
