### PR TITLE
Minted docs

### PR DESCRIPTION
**Pull request by HaoZeke**
## Purpose
Mostly a readability change. I am also attaching the produced output file. Suggestions for better colors are welcomed.

A summary of changes would be:

* Addition of a TOC
* Syntax highlighting with [minted](https://github.com/gpoore/minted)
* Proper `TeX` style double quotes
* Some minor grammatical corrections

## Author(s)

Rohit Goswami <r95g10 at gmail.com>

## Backward Compatibility
N/A. I suppose people with the older docs will have to update to this set. They don't necessarily have to though so there is no compatibility trouble.

## Implementation Notes

Standard highlighting via [minted](https://github.com/gpoore/minted) along with general `TeX` updates.
The `Makefile` was modified to call the same `$VENV` as defined for the `Sphinx` build. This may or may not be optimal, it just seemed silly to have a whole new `$VENV_PYGMENTS` or something like that.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
N/A
- [ ] The source code follows the LAMMPS formatting guidelines
N/A

## Further Information, Files, and Links

Attached below are the before and after versions of the `Developer.pdf` file:

* [Before](https://github.com/lammps/lammps/files/2262543/Developer.pdf)
* [After](https://github.com/lammps/lammps/files/2262639/Developer.pdf)
* [After v2](https://github.com/lammps/lammps/files/2317090/Developer.pdf)

### CODE REVIEW

**Comment by akohlmey** [comment]
@HaoZeke please see `tools/doxygen` for an alternate approach to make the developer docs more pleasant to look at and useful). More important than a visual upgrade, however, would be an expansion discussing more development relevant issues and update the contents to the current state of LAMMPS (the basics are still the same, but many small details have been modified since that text was drafted).

**Comment by HaoZeke** [comment]
Yup, I'll look into both, actually this was just sitting on a local branch from when I started working with the source...

**Comment by rbberger** [comment]
currently the build is failing because our CI containers don't have minted installed. I'll update them in the coming days but don't want to touch them while we're working on the stable release. I'm also waiting to see what other core developers think of this.

**Comment by HaoZeke** [comment]
@rbberger in hindsight I agree. Inline code looks almost redacted. I'll remove the background and change the color instead.

**Comment by akohlmey** [comment]
@HaoZeke if you want this to go in, you have to resolve the current merge conflict *and* find somebody among the LAMMPS developers to support your submission through adding an approving review. since this doesn't add any significant value nor updates/improves the text for recent changes to LAMMPS. i am inclined to close this soon.

**Comment by HaoZeke** [comment]
Since the merge conflict was trivial, I resolved that. Apart from that, sadly I have not much time to devote to adding further value to the documentation, and that includes being unable to look for someone to approve of these changes. Please feel free to close this if required.

**Comment by akohlmey** [comment]
ok. i've moved over the changes, that don't require installing any additional Latex packages to PR #1152 and will close this now. As mentioned before, if people want a more fancy looking developer's guide (and a call tree etc), they can also go to `tools/doxygen` and follow the instructions in the README there. Thanks for your efforts.

**Pull request closed without merging**
