### PR TITLE
Unit tests, bugfixes and file reader refactor for some INTERLAYER pair styles

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request adds unit tests, fixes some bugs and memory leaks, and refactors the potential file reader code in multiple pair styles of the INTERLAYER package

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues. Unit tests were created before refactor and could be reproduced after.

**Implementation Notes**

The code uses only a global cutoff, so references to cut[i][j] were removed for clarity.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by akohlmey** [comment]
@oywg11 you already have an internal scaling factor, but if you look at pair_sw.cpp and compare to the two modified pair styles here you should see that it would be very straightforward to implement automatic conversion from "metal" to "real" units with just a few added lines of code.

**Comment by oywg11** [comment]
@akohlmey Many thanks for the corrections and suggestions, I will check it carefully, perform some benchmark tests, and give you feedback soon.

**Review by sjplimp — APPROVED** [review]

**Comment by akohlmey** [comment]
@oywg11 made some more refactoring changes. got rid of some more redundancy and unneeded allocations and moved the replicated taper function(s) to a common header file. Finally, I also ran the files through clang-format using the "LAMMPS" settings.
Unit conversion is also included and checked.

**Comment by oywg11** [comment]
@akohlmey I did the benchmark tests and the energy outputs are exactly the same as before. Many thanks for your excellent work! The structure of the codes in the INTERLAYER package becomes more unified now.  I'm currently working on adding new types of interlayer potential to this package and will follow the updated structure built here.

**Review by oywg11 — APPROVED** [review]

**Pull request merged**
