### PR TITLE
Fix bond create updated

### PR DESCRIPTION
**Pull request by aminaramoon**
this is a pull request for fix_bond_create with updated feature.

The old version applies a static angle, dihedral or improper dihedral style to the newly created angle, and dihedral angles. with this update, user can define different types of angles, and dihedral angles to assign to new coordinates based on the types of atoms forming the coordinate.

This class is fully backward compatible, and utilizes a new class "type_detector" which can decide the type of new created coordinates.

the doc for fix_bond_create is also updated.

usage:

variable id string "1 2 3 1, 2 1 3 2"  // states that if angle is formed by atoms with types <1-2-3> => 1, and <2-1-3> =>2

fix  1 all bond/create 10 1 3 10 1 iparam 2 1 jparam 3 3 atype id dtype 4

### CODE REVIEW

**Comment by akohlmey** [comment]
As Richard already remarked on a previous pull request, your changes are full of whitespace changes. I can't easily see, what it is that you are actually adding because of that. Those changes need to be undone and reformatted to the common style in LAMMPS using an indentation of 2 blanks per level.
Also, what about my suggestion to create a derived class instead of modifying the existing one?

**Comment by aminaramoon** [comment]
I think you suggested that I add another "create_chain" class instead of extending and modifying the "Create_atoms" class. I am changing my code and trying to create the modified class, but for this case, I think the changes to the main are limitted to a few lines, and having a class overriding this class may not be the best option ? I am willing to do it tho, if you want it.

**Comment by aminaramoon** [comment]
I will reformat the code and make sure changes are easy to read and send it push it back again,

Best

**Comment by aminaramoon** [comment]
One more thing, when you mentioned a lot of white space, I thought I had accidentally reformatted the codes, when I checked the committed one by one, the changes are very clear as I have removed a few lines and replaced them with others, and no reformatting has been done. Please check the codes again commite by commit as it makes it easier to track changes, and let me know whether you want to reformat it again.

Sorry for inconvenience

**Pull request closed without merging**
