### PR TITLE
Cluster/fragment/aggregate bugfixes

### PR DESCRIPTION
**Pull request by danicholson**
## Purpose

Fixes for two issues in the fragment/aggregate/cluster computes. These issues have been flagged in the following lammps-users messages:

https://sourceforge.net/p/lammps/mailman/message/36105303/
https://sourceforge.net/p/lammps/mailman/message/36108054/

## Author(s)

David Nicholson (MIT)

## Backward Compatibility

No issues anticipated.

## Implementation Notes

The first issue is with compute fragment/atom and compute aggregate/atom. When the newton flag is on for bonded interactions, the current algorithm can end up in a loop. This PR adds reverse communication to propagate changes to bonded ghost atoms back to their local processors. With similar changes to this one, it should also be possible to use half lists, rather than full lists, for pairwise clustering in compute aggregate/atom and compute cluster/atom. I do not know how much this would impact performance, but it may be worth looking into.

The second issue is for compute cluster/atom and compute aggregate/atom with multiple run statements. It should only occur when the neighbor list was built on the last step of the first run, and when running with "pre yes" on the second run. When the second run is started, Integrate::setup() will exchange atoms and update perpetual neighbor lists, but not the list for compute cluster/atom. When Neighbor::build_one(...) is called from compute cluster(or aggregate)/atom on the first step of the second run, the occasional neighbor list will register as up to date when it is not. The fix adds a check in Neighbor::build_one(...) to see if it is executed on the first step of a run. If so, the neighbor list is set to re-build even if it appears up-to-date.

## Post Submission Checklist

- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by akohlmey** [comment]
Thanks for your efforts. haven't had time to test it, but your description is consistent with what i saw when trying to debug the issue. sadly, i ran out of time before completing that.

i am a bit concerned about the change to `neighbor.cpp` as this may affect behavior of other computes and fixes.

wouldn't it be less intrusive to change `neighbor->build_one(list);`
into `neighbor->build_one(list,1);` in the affected compute styles?
after reading through the comment in neighbor.cpp, this seems to me what is intended.

**Comment by danicholson** [comment]
@akohlmey sure that would work as well. I was thinking that using `build_one(list,1)` could result in extra re-building of  the occasional neighbor list when it's not really necessary. However, this will only happen if the compute is called more frequently than re-neighboring occurs, which is probably not a normal use case. The other reason for my choice is that other methods that use `build_one` may suffer from the same problem under these circumstances, so I thought that it may be better to fix the problem closer to the root. For example, I have attached a `hexorder/atom` example that is broken without this change.

[in.hex.txt](https://github.com/lammps/lammps/files/1469067/in.hex.txt)
[log.hex.txt](https://github.com/lammps/lammps/files/1469068/log.hex.txt)

**Comment by akohlmey** [comment]
@danicholson the concern is, that there may be just as many, if not more, styles that require the code in neighbor.cpp as is. It'll be easy to get code merged that addresses the issues you are pointing out in the individual style. If you feel strongly about this, i suggest you contact @sjplimp directly and discuss this with him in person. otherwise, i'll be happy to adapt this to work without having to change neighbor.cpp.

**Comment by danicholson** [comment]
@akohlmey I understand the concern, and I don't feel too strongly about changing neighbor.cpp. I committed changes to move the fix to the three individual styles that I found to be affected by the problem. Feel free to re-work them as you see fit.

**Comment by akohlmey** [comment]
@danicholson this looks good to me. i'll run some extended tests on this and will then assign it to @sjplimp 
it'll take a few days until it is merged as the big man is receiving an award at the supercomputing conference and will have to give the folks there a song and dance. ;-)

**Pull request merged**
