### PR TITLE
Refactor Kokkos `AtomVec`

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Greatly reduce duplicated code in Kokkos `AtomVec` styles by inheriting from non-Kokkos atom_vec styles and removing Kokkos host methods, falling back to original CPU (non-Kokkos) methods instead. This requires virtual inheritance for non-Kokkos atom_vec styles.

**Related Issue(s)**

Should address restart read/write issues in #3538.

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
Kokkos regression tests pass now.

**Comment by stanmoore1** [comment]
This is ready to merge from my POV.

**Comment by stanmoore1** [comment]
@akohlmey Steve was wondering if there is any potential performance impact from using virtual inheritance in the `AtomVec` styles, i.e. if calling the class functions would be slower since it inherits from a virtual base. As far as I know, the only impact is that a `dynamic_cast` is required, which is slower that `static_cast`, but this is typically called once during `init()` so no performance impact. Can you confirm?

**Review by sjplimp — APPROVED** [review]

**Comment by stanmoore1** [comment]
Quick search suggests: "Common implementations will make access to data members of virtual base classes use an additional indirection." Maybe we want to do a quick performance check before merging.

https://stackoverflow.com/questions/4899657/performance-impact-of-virtual-inheritance

**Comment by akohlmey** [comment]
> Can you confirm?

I don't expect that it will matter much.
- most of the access to the stored pointers are through the copied pointer variables in the Atom class
- almost all data access within the AtomVec classes is in the base class itself or to local data members
- affected functions in the AtomVec classes are virtual already

**Comment by stanmoore1** [comment]
I ran this on my Linux box with the LJ benchmark (vanilla CPU) and I don't see any noticeable slowdown.

**Comment by stanmoore1** [comment]
So I think it can be merged now.

**Pull request merged**
