### PR TITLE
cmake: start documenting packages and options

### PR DESCRIPTION
**Pull request by junghans**
**Summary**

With CMake-3.10, we can now use `set_package_properties()` and `add_feature_info()` to document things in the feature summary.

**Related Issues**

None

**Author(s)**

@junghans 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

**Implementation Notes**

All CMake

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

https://cmake.org/cmake/help/v3.10/module/FeatureSummary.html

### CODE REVIEW

**Comment by junghans** [comment]
@akohlmey have a look it this is something of interest and if so I can document some more options / packages.

**Comment by akohlmey** [comment]
thanks for the suggestion. let us take a look at this after #2004 and #1970 are merged, which include - in part - significant changes to the documentation and particularly the build process.  There is still more to come, especially in terms to making the style of typesetting more consistent and also use headlines instead of explicit boldface.  Right now information about compiling LAMMPS and developing/modifying LAMMPS and using the library interface is a bit convoluted and parts of it are repeated in places where they are not really needed.  To a large degree, this is just stuff that has accumulated over time and is due to different developers adding parts to different parts of the documentation without being aware of the other additions. With #1970 i am trying to make this a bit more consistent and less redundant.

**Comment by junghans** [comment]
@akohlmey sounds good, these changes just apply to the CMake feature summary, but it would be good have them consistent with #1970.

**Comment by akohlmey** [comment]
while #1970 has been discontinued. its contents have been integrated into LAMMPS. we also have integrated the developer guide document into the .rst format manual sources. Since we also are getting close to the next stable release, this would now be a good point to revisit this and a) review and correct the documentation of the CMake build process and make the documentation for it (more) consistent (i've done it in parts, but not systematically for the entire manual). and b) consider changes like this (but this is still incomplete, right?) that can help inexperienced people with the build process.

**Comment by junghans** [comment]
No time, sorry.

**Comment by junghans** [comment]
Actually now I remember this PR had close to nothing to do with #1970, it is more about documenting the enabled option in the CMake summary.

Not sure how useful it really is. On the other hand it will guide user towards other options they could enable.

**Comment by junghans** [comment]
@rbberger @akohlmey can you have a look if this is now too much output?

**Comment by rbberger** [comment]
```
-- The following features have been enabled:

 * PKG_GRANULAR, The GRANULAR package
 * PKG_KSPACE, The KSPACE package
 * PKG_MANYBODY, The MANYBODY package
 * PKG_MOLECULE, The MOLECULE package
 * PKG_USER-OMP, The USER-OMP package
 * BUILD_MPI, Build with MPI
 * BUILD_OMP, OpenMP-enabled version

-- The following features have been disabled:

 * PKG_ASPHERE, The ASPHERE package
 * PKG_BODY, The BODY package
 * PKG_CLASS2, The CLASS2 package
 * PKG_COLLOID, The COLLOID package
 * PKG_COMPRESS, The COMPRESS package
 * PKG_DIPOLE, The DIPOLE package
 * PKG_LATTE, The LATTE package
 * PKG_MC, The MC package
 * PKG_MESSAGE, The MESSAGE package
 * PKG_MISC, The MISC package
 * PKG_MLIAP, The MLIAP package
 * PKG_PERI, The PERI package
 * PKG_POEMS, The POEMS package
 * PKG_QEQ, The QEQ package
 * PKG_REPLICA, The REPLICA package
 * PKG_RIGID, The RIGID package
 * PKG_SHOCK, The SHOCK package
 * PKG_SPIN, The SPIN package
 * PKG_SNAP, The SNAP package
 * PKG_SRD, The SRD package
 * PKG_KIM, The KIM package
 * PKG_PYTHON, The PYTHON package
 * PKG_MSCG, The MSCG package
 * PKG_MPIIO, The MPIIO package
 * PKG_VORONOI, The VORONOI package
 * PKG_USER-ATC, The USER-ATC package
 * PKG_USER-AWPMD, The USER-AWPMD package
 * PKG_USER-BOCS, The USER-BOCS package
 * PKG_USER-CGDNA, The USER-CGDNA package
 * PKG_USER-MESODPD, The USER-MESODPD package
 * PKG_USER-CGSDK, The USER-CGSDK package
 * PKG_USER-COLVARS, The USER-COLVARS package
 * PKG_USER-DIFFRACTION, The USER-DIFFRACTION package
 * PKG_USER-DPD, The USER-DPD package
 * PKG_USER-DRUDE, The USER-DRUDE package
 * PKG_USER-EFF, The USER-EFF package
 * PKG_USER-FEP, The USER-FEP package
 * PKG_USER-H5MD, The USER-H5MD package
 * PKG_USER-LB, The USER-LB package
 * PKG_USER-MANIFOLD, The USER-MANIFOLD package
 * PKG_USER-MEAMC, The USER-MEAMC package
 * PKG_USER-MESONT, The USER-MESONT package
 * PKG_USER-MGPT, The USER-MGPT package
 * PKG_USER-MISC, The USER-MISC package
 * PKG_USER-MOFFF, The USER-MOFFF package
 * PKG_USER-MOLFILE, The USER-MOLFILE package
 * PKG_USER-NETCDF, The USER-NETCDF package
 * PKG_USER-PHONON, The USER-PHONON package
 * PKG_USER-PLUMED, The USER-PLUMED package
 * PKG_USER-PTM, The USER-PTM package
 * PKG_USER-QTB, The USER-QTB package
 * PKG_USER-REACTION, The USER-REACTION package
 * PKG_USER-REAXC, The USER-REAXC package
 * PKG_USER-SCAFACOS, The USER-SCAFACOS package
 * PKG_USER-SDPD, The USER-SDPD package
 * PKG_USER-SMD, The USER-SMD package
 * PKG_USER-SMTBQ, The USER-SMTBQ package
 * PKG_USER-SPH, The USER-SPH package
 * PKG_USER-TALLY, The USER-TALLY package
 * PKG_USER-UEF, The USER-UEF package
 * PKG_USER-VTK, The USER-VTK package
 * PKG_USER-QUIP, The USER-QUIP package
 * PKG_USER-QMMM, The USER-QMMM package
 * PKG_USER-YAFF, The USER-YAFF package
 * PKG_USER-ADIOS, The USER-ADIOS package
 * PKG_CORESHELL, The CORESHELL package
 * PKG_KOKKOS, The KOKKOS package
 * PKG_OPT, The OPT package
 * PKG_USER-INTEL, The USER-INTEL package
 * PKG_GPU, The GPU package
```
I'm in favor of shorter output by default. E.g. I wouldn't show the disabled ones.

**Comment by akohlmey** [comment]
What about the following change:
```
  diff --git a/cmake/CMakeLists.txt b/cmake/CMakeLists.txt
  index 8b7b798d95..3bc4129dfc 100644
  --- a/cmake/CMakeLists.txt
  +++ b/cmake/CMakeLists.txt
  @@ -699,11 +699,14 @@ include(CodingStandard)
   ###############################################################################
   # Print package summary
   ###############################################################################
  +set(ENABLED_PACKAGES "")
   foreach(PKG ${STANDARD_PACKAGES} ${SUFFIX_PACKAGES})
     if(PKG_${PKG})
  -    message(STATUS "Building package: ${PKG}")
  +    list(APPEND ENABLED_PACKAGES ${PKG})
     endif()
   endforeach()
  +list(SORT ENABLED_PACKAGES)
  +message(STATUS "Enabled packages: ${ENABLED_PACKAGES}")
```
That only shows the enabled packages and in a more compact fashion:
```
[...]
-- Found MPI: TRUE (found version "3.1")  
-- Enabled packages: ASPHERE;BODY;CLASS2;COLLOID;COMPRESS;CORESHELL;DIPOLE;GRANULAR;KIM;KOKKOS;KSPACE;MANYBODY;MC;MISC;MLIAP;MOLECULE;MPIIO;OPT;PERI;POEMS;PYTHON;QEQ;REPLICA;RIGID;SHOCK;SNAP;SPIN;SRD;USER-ATC;USER-AWPMD;USER-BOCS;USER-CGDNA;USER-CGSDK;USER-COLVARS;USER-DIFFRACTION;USER-DPD;USER-DRUDE;USER-EFF;USER-FEP;USER-INTEL;USER-LB;USER-MANIFOLD;USER-MEAMC;USER-MESODPD;USER-MISC;USER-MOFFF;USER-MOLFILE;USER-OMP;USER-PHONON;USER-PTM;USER-QTB;USER-REACTION;USER-REAXC;USER-SDPD;USER-SMD;USER-SMTBQ;USER-SPH;USER-TALLY;USER-UEF;USER-YAFF;VORONOI
-- The following tools and libraries have been found and configured:
 * Git
 * OpenMP
 * LAPACK
[...]
```
FWIW, on the console the very long line wraps around.
And the list of the enabled packages is also easily available from `lmp -h`

**Comment by junghans** [comment]
In 23f604d06ca4ca0524c5bdfc7687240d7f1c5a8d the status of disabled packages were enabled, the idea being to help the user to discover options he might want to enable.

**Comment by akohlmey** [comment]
> In [23f604d](https://github.com/lammps/lammps/commit/23f604d06ca4ca0524c5bdfc7687240d7f1c5a8d) the status of disabled packages were enabled, the idea being to help the user to discover options he might want to enable.

This is the wrong place to do it. That is what the manual is for, we have the `Packages_details.html` page for that purpose. Statements like `* PKG_ASPHERE, The ASPHERE package` are highly redundant and do not provide any useful information.
The more I am digging around this, the more I feel that we need to make the CMake output more compact and think about which details to include and what we can drop. e.g. I've just disabled the printing of each generated header file name. That was useful when CMake support was in its infancy, but that code has been largely unchanged for a long time now, So just a single line is sufficient. 

Anyway, I think I'll change the package summary as outlined in the diff and move this a few lines down. And add one more line to show if unit tests are included. That looks good enough for now.  I would be OK to use a more generic mechanism to produce the same output, for as long as it allows to keep things compact and organized. With too many output lines, important information is too easily drowned by less relevant output.

**Comment by akohlmey** [comment]
Here is a crazy idea: If the intent is to inform users about available features, we could provide URLs to the relevant sections in the manual, where appropriate. Part of the recent changes to code and manual were motivated to reduce the effort to keep different (replicated) versions of the same information consistent and in sync. It would be better to just point to a canonical location (and - ideally - add a test to confirm it is still a valid destination).

**Comment by junghans** [comment]
> > In [23f604d](https://github.com/lammps/lammps/commit/23f604d06ca4ca0524c5bdfc7687240d7f1c5a8d) the status of disabled packages were enabled, the idea being to help the user to discover options he might want to enable.
> 
> This is the wrong place to do it. That is what the manual is for, we have the `Packages_details.html` page for that purpose. Statements like `* PKG_ASPHERE, The ASPHERE package` are highly redundant and do not provide any useful information.

We can make the doc string whatever we want once we agreed on something.

> The more I am digging around this, the more I feel that we need to make the CMake output more compact and think about which details to include and what we can drop. e.g. I've just disabled the printing of each generated header file name. That was useful when CMake support was in its infancy, but that code has been largely unchanged for a long time now, So just a single line is sufficient.

I personally think most of the output isn't very useful as normal users that don't really care what internal defines are set and what linker flags are used. So this could easily be hidden under something like a CMAKE_VERBOSE_SUMMARY option. Originally I only added that for @sjplimp. Alternatively we could wrap it into `if ($ENV{'USER'} STREQUAL "steve")` ;-)


> Here is a crazy idea: If the intent is to inform users about available features, we could provide URLs to the relevant sections in the manual, where appropriate. Part of the recent changes to code and manual were motivated to reduce the effort to keep different (replicated) versions of the same information consistent and in sync. It would be better to just point to a canonical location (and - ideally - add a test to confirm it is still a valid destination).

Whenever I need to look up options, I find myself on networkless machines hence a URL is only partially useful for me. Usually I grep through `cmake -LH`, but I don't expect a normal user to do that.

My original thinking was to have an easy way to remind the user that there are some useful option he might want to enable additionally. If we can agreed what these "useful" options should be (and I agree package might be a bad idea), we could just show those. CMake's summary feature offers a `RECOMMENDED` type for that and we could only print the disabled `RECOMMENDED` options.

**Comment by akohlmey** [comment]
> > > In [23f604d](https://github.com/lammps/lammps/commit/23f604d06ca4ca0524c5bdfc7687240d7f1c5a8d) the status of disabled packages were enabled, the idea being to help the user to discover options he might want to enable.
> > 
> > 
> > This is the wrong place to do it. That is what the manual is for, we have the `Packages_details.html` page for that purpose. Statements like `* PKG_ASPHERE, The ASPHERE package` are highly redundant and do not provide any useful information.
> 
> We can make the doc string whatever we want once we agreed on something.

I won't agree. This is just too verbose.

> I personally think most of the output isn't very useful as normal users that don't really care what internal defines are set and what linker flags are used. So this could easily be hidden under something like a CMAKE_VERBOSE_SUMMARY option. Originally I only added that for @sjplimp. Alternatively we could wrap it into `if ($ENV{'USER'} STREQUAL "steve")` ;-)

What is a "normal user"? Will that person care? But it is quite helpful to a developer (I typically have a whole bunch of different build folders with different settings and environments active at the same time, so seeing what is active *is* helpful.


> > Here is a crazy idea: If the intent is to inform users about available features, we could provide URLs to the relevant sections in the manual, where appropriate. Part of the recent changes to code and manual were motivated to reduce the effort to keep different (replicated) versions of the same information consistent and in sync. It would be better to just point to a canonical location (and - ideally - add a test to confirm it is still a valid destination).
> 
> Whenever I need to look up options, I find myself on networkless machines hence a URL is only partially useful for me. Usually I grep through `cmake -LH`, but I don't expect a normal user to do that.

You live indeed in a very CMake centric world. Why not read/grep through doc/src/*.rst? I don't want to replicate information into another location.

> My original thinking was to have an easy way to remind the user that there are some useful option he might want to enable additionally. If we can agreed what these "useful" options should be (and I agree package might be a bad idea), we could just show those. CMake's summary feature offers a `RECOMMENDED` type for that and we could only print the disabled `RECOMMENDED` options.

This just requires more effort to maintain it. Time and effort we don't have, given the small number of people working on things and the parts they are working on. Looking things up in the manual is the way to go.

This discussion now has me fully convinced that this is the wrong approach for LAMMPS.
We don't want more places for people to find relevant information but fewer. That is why a lot of the changes were made to the manual in recent months. While reviewing the manual there were up to 4 places that we essentially documenting the same thing (with slightly different focus). This has now been mostly consolidated to just one location with a short referral paragraph or nothing in the other places. I very much want to keep it that way. In my personal opinion, the way to provide recommended features with CMake are the "preset" files.

**Pull request closed without merging**
