### PR TITLE
Documenation Reorganization

### PR DESCRIPTION
**Pull request by rbberger**
## Purpose
Steve wants to gradually split up larger sections of the manual into smaller pages. This is a work branch to collect these changes. I'm also creating the pull request immediately, which automatically triggers building the new docs and creates artifacts we can then download and view.

## Author(s)
@sjplimp @rbberger

### CODE REVIEW

**Comment by sjplimp** [comment]
@rbberger Replaced all the Section files with new top-level files and sub-files underneath them, similar to Errors.txt.  Pasted old content into many of these files.  Some need new content or additional massaging. But the hi-level structure should now be about right.

**Comment by rbberger** [comment]
@sjplimp there's a lot of links to the old Section_* files spread out in the files. I'll look to see if we can use `sed` for this. Also the PDF build now fails.

**Comment by sjplimp** [comment]
@rbberger yes, I was going to wait to fix links until all the content
was edited/added

**Comment by rbberger** [comment]
As discussed with Steve, we will start over.

**Pull request closed without merging**
