### PR TITLE
Optimize Kokkos neigh list for GPUs

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Optimize Kokkos neigh list for GPUs:
- Add a `-pk kokkos neigh/transpose` option to use optimal memory layout for building neigh list, can be much faster in some cases (e.g. ReaxFF), but is slightly slower in other cases (e.g Lennard-Jones benchmark)
- Add a GPU optimized version of Ghost neigh list build (e.g. used in ReaxFF)
- Also fix a potential bug with shared memory and `Size` neigh list build

**Related Issue(s)**

#3169 

**Author(s)**

Stan Moore (SNL), Evan Weinberg (NVIDIA), compile error fixed by Nick Curtis (AMD)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
I see over 2x speedup in neigh time for the ReaxFF HNS benchmark on V100 with this PR.

**Comment by stanmoore1** [comment]
This also helps on AMD. I tried using 64x2 instead of 32x4 for the transpose but it was a little slower. 64x4 runs out of shared memory on AMD.

**Comment by weinbe2** [comment]
This PR gives a sub-percentile end-to-end perf boost on A100-80GB; that said, it's still a win, and a win is a win! (The boost on V100 is certainly a big win!) Thanks @stanmoore1 !

**Comment by stanmoore1** [comment]
This is ready to merge from my point of view.

**Review by weinbe2 — APPROVED** [review]
Adding a formal +1 approval

**Review by sjplimp — APPROVED** [review]

**Comment by stanmoore1** [comment]
Just for an accurate record, @weinbe2 found on A100 that using the optimized Ghost neigh list in this PR is faster, but using the transpose option was slower a little slower for A100.

**Pull request merged**
