### PR TITLE
Final build system changes for stable release

### PR DESCRIPTION
**Pull request by akohlmey**
## Purpose

This pull request updates the installation scripts in the `lib` folder to simplify them and make them consistent. There will be one more PR with the corresponding updates to the documentation.

## Author(s)

Axel Kohlmeyer (Temple U)

## Backward Compatibility

Flags and settings for various `Install.py` scripts in `lib` are changed.

## Implementation Notes

- all python scripts have been tested with python 2.7 and python 3.5
- names of flags for `Install.py` have been synchronized where possible
- download/install options for restricted to current working directory. specifying path only works to use existing installation
- add or update `Makefile.mpi` and `Makefile.serial` where possible and synchronize settings with `make mpi` and `make serial`, respectively.
- tweak master makefile to use `$(PYTHON)` throughout, so it can be overridden (default remains `python`)
- move `#include "mscg.h"` line from `fix_mscg.h` header file to implementation file `fix_mscg.cpp` (where it belongs) and thus avoid type and namespace clashes with several packages.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [x] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by giacomofiorin** [comment]
Thanks.  It is a major improvement for my point of view to use machine names that are the same as those for LAMMPS core files (there is no reason otherwise for Colvars, and I argue that most other libraries should be able to import flags from LAMMPS.

I notice that you left the function `get_lammps_machine_flags()` in place in `lib/colvars/Install.py`: do you want to comment it out or leave it available?

**Comment by akohlmey** [comment]
@giacomofiorin i have focused so far on getting things to work consistently with python 2.7 and 3.x, fix bugs and problems without making too many changes. I don't want to delay the release more than needed.
I don't see the current setup as the final solution, but a step in the right direction. thanks for pointing out the unused function, i'll remove it. if we want to access common compiler settings, we should do it in a general way, that can be replicated across all Makefile components in src, lib and beyond.

**Comment by giacomofiorin** [comment]
Sounds reasonable.  I hope that part of that function can be useful towards implementing it

FYI, it is still being used: I can't add a review comment on code that is not part of this diff, but here it is:
```
if not os.path.exists("Makefile.%s" % machine):
  machine_flags = get_lammps_machine_flags(machine)
  gen_colvars_makefile_machine(machine, machine_flags)
if not os.path.exists("Makefile.%s" % machine):
error("lib/%s/Makefile.%s does not exist" % (lib,machine))
```
You could just remove or comment the first three lines.

**Comment by akohlmey** [comment]
then i'll just put it back. we can sort the details out after the release.

**Pull request merged**
