### PR TITLE
cmake: do not install mpi.h without library

### PR DESCRIPTION
**Pull request by junghans**
**Summary**

Internal `mpi.h` got installed even without shared library

**Related Issue(s)**

**Author(s)**

@junghans 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No, but nobody should rely on that header.

**Implementation Notes**

CMake-only

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
STUBS/mpi.h should not be needed when installing a library compiled without MPI (and with STUBS MPI).
as of recent, the requirement to have an mpi.h header present has been lifted as you can compile LAMMPS with -DLAMMPS_LIB_NO_MPI. That will exclude the prototype of `lammps_open()` from the header (which is the only function requiring the mpi.h header). This applied even to the case of having LAMMPS compiled *with* MPI (as a shared library), as that
would only require the MPI **runtime** to be present, but not the MPI development headers for as long as the calling application has no need to call `lammps_open`. Whether the library was compiled with STUBS or a regular MPI library can be checked at runtime via `lammps_config_has_mpi_support()`.

On top of that, we also have the new `lammps_open_fortran()` function, which requires the fortran representation of an MPI communicator, i.e. an integer. and thus one could compile an application that connects two libraries which do use MPI without having the MPI header present, if they use `MPI_Comm_f2c()` and `MPI_Comm_c2f()` to convert the c-style communicator accordingly and call `lammps_open_fortran()` this gets even fancier when using a "plugin" loader for the LAMMPS shared library (see examples/COUPLE/plugin).

**Comment by akohlmey** [comment]
...and let me reiterate. From the my perspective we should at the moment only support and endorse using the C-library interface, the python module and (when reasonably complete) the fortran 03 style interface for systemwide installation and use for writing your own application. the C++ interface could require pretty much *any* header from the C++ sources in `src`. So unless there is a specific documentation that defines which functionality of the C++ interface is supported and meant to be available and which not by an installation with "make install", there is no need to install *any* header outside of `library.h` (considering my previous comment). Other uses should use an in place compilation and expecting CMake things to work is something that none of the core LAMMPS people currently wants to deal with since that is a marginal use case. Please keep in mind that there is still a very large group of people using the old style build process. The library interface setup is still mostly unchanged from the original setup from a long time ago, and thus somehow assuming that you compile with the traditional make and not CMake. Getting on top of that is being considered, but the priorities are C > Python > Fortran > C++ > CMake support, and we are working very hard to have the first two in a reasonable shape (implementation and documentation) for the upcoming stable release (not sure if it can be done so it passes all tests and possible use cases, LAMMPS is too flexible and has too many options and variants of use to get that all sorted out **and** futureproof/refactor the interfaces).

Having to deal with and argue about CMake issues related to this before the code and documentation has matured to a sufficient degree is a distraction and dissipates energy that could be used more productively. I understand that this is frustrating for either side, but please understand that it is impossible to do everything at the same time. So priorities are needed.

**Comment by junghans** [comment]
I guess we should add `-DLAMMPS_LIB_NO_MPI` as interface define to external target then when the library is build serially and not install `mpi.h` at all.

**Comment by junghans** [comment]
Ok, this will get rid of the lonely `mpi.h` when installing the serial binary (`BUILD_SHARED_LIBS=OFF`) [the original issue] and exports `LAMMPS_LIB_NO_MPI` into the interface when installing a serial library (`BUILD_SHARED_LIBS=ON`).

**Review by rbberger — APPROVED** [review]
Looks good.

**Pull request merged**
