### PR TITLE
Angle class2 update

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

The angle class2 and variant class2/p6 were not using the specified r1/r2 distances for the BondAngle term.  They were
using the ones for the BondBond term.  This corrects that.  However it is likely a non-issue since it is likely in all cases that
the r1/r2 values in both terms are the same.  Also an important note was added to the doc page explaining that the order of I,J,K Angles in the data file needs to match the ordering of r1/r2 in those 2 sets of coefficients.

**Related Issue(s)**

N/A

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This should only change the energy/forces of the class2 angle term if the bond/angle cross term uses different r1/r1 coeffs versus the bond/bond cross term.

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
what about the KOKKOS and OPENMP versions?

**Comment by sjplimp** [comment]
good catch - done

**Review by stanmoore1 — APPROVED** [review]

**Review by akohlmey — CHANGES_REQUESTED** [review]
- KOKKOS version currently doesn't compile
- The changes **do** alter the forces for all of the force tests in the unit test tree so those will need to be reset after all other changes are complete

**Comment by sjplimp** [comment]
Is the altered force test b/c the r1,r2 coeffs were different for the bond-bond and bond-angle cross terms?

**Comment by akohlmey** [comment]
> Is the altered force test b/c the r1,r2 coeffs were different for the bond-bond and bond-angle cross terms?

probably. inputs are here: https://github.com/lammps/lammps/blob/develop/unittest/force-styles/tests/angle-class2.yaml and here: https://github.com/lammps/lammps/blob/develop/unittest/force-styles/tests/angle-class2_p6.yaml

**Pull request merged**
