### PR TITLE
Relax error check on accessing fixes that produce variable size vectors/arrays

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

A recent PR #4122 was too aggressive in error checking when a global vector or array that is variable size is accessed out of bounds.  A few of the examples that compute viscosity and heat capacity do this on step 0 before fix ave/chunk have knows the # of chunks.  So they depend on zero values being returned.  This change allows that again, although other use cases are still treated more agressively with error checking.

**Related Issue(s)**

N/A

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by sjplimp** [comment]
@stanmoore1 I think this fixes the 3 examples scripts you flagged.  Please check if you agree, then you can pass this on to @akohlmey to approve and merge.

**Comment by stanmoore1** [comment]
Will do, thanks @sjplimp!

**Comment by akohlmey** [comment]
This passes the Jenkins' run regression tests where 3 were previously failing.

**Comment by akohlmey** [comment]
@stanmoore1 FYI, this PR is one of the "must haves" for the feature release early next week.

**Review by akohlmey — APPROVED** [review]

**Review by stanmoore1 — APPROVED** [review]
I approve.

**Pull request merged**
