### PR TITLE
Improvements to the GPU library Makefiles

### PR DESCRIPTION
**Pull request by ndtrung81**
**Summary**

This PR added two Makefiles for CUDA and OpenCL APIs similar to what has been done in Makefile.hip for the HIP API. The underlying Nvidia.makefile and Opencl.makefile are also updated to be less tedious, and more effective for adding new pair styles.

**Related Issue(s)**

N/A

**Author(s)**

Trung Nguyen (Northwestern)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Should be maintained.

**Implementation Notes**

Nvidia.makefile is now the same as Nvidia.makefile_multi.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@ndtrung81 do you see a chance to reduce the number of "makefiles" in the lib/gpu folder? In most cases, using CMake would be preferred anyway, since it can better adjust to the toolkit in use.

**Comment by ndtrung81** [comment]
@akohlmey yes, I found a couple of obsolete makefiles that can be removed. I will create a separate PR for this change then.

**Comment by akohlmey** [comment]
> @akohlmey yes, I found a couple of obsolete makefiles that can be removed. I will create a separate PR for this change then.

or just provide the names. I have a "generic" feature branch for such changes where I could just remove those files.

**Comment by ndtrung81** [comment]
Please remove Makefile.linux.double, Makefile.linux.single, Makefile.linux.mixed, Makefile.mpi, Makefile.serial_opencl and Makefile.xk7. Rename Makefile.fermi to Makefile.turing, changing CUDA_ARCH from sm_35 to sm_75.

**Pull request merged**
