### PR TITLE
Kokkos SNAP cleanup/optimizations --- templating, Kokkos::LaunchBounds, tuning

### PR DESCRIPTION
**Pull request by weinbe2**
**Summary**

Note: this PR is still WIP because I'm doing performance checks across a wider variety of SNAP sample inputs, as opposed to the spot tests I've done thus far (2J8, 2J14 Tungsten benchmarks). The core of the work is complete. I don't expect any surprises. 

This PR is a "miscellaneous" collection of updates to SNAP potential within the Kokkos package when using the Cuda backend (though it should generalize well to any GPU). It does not include any algorithmic overhauls. The PR features multiple discrete and largely orthogonal commits related to code readability and cleanliness, empirical performance stability across different CUDA toolkit versions, and some small (~1-2%) performance boosts. More details on each commit are given under Implementation Notes. Readability, cleanliness, and overall design choices are of course all up to discussion; I'm not married to any one convention.

This PR has no effect to the CPU Kokkos backend (it may actually give a ~1% speed-up, for much the same reason other SNAP PRs have caused slowdowns---no good reason). This has no effect on the CPU implementation in the SNAP package, which has historically been faster than the Kokkos/CPU backend.

Overall performance notes below, with some per-PR speedups given under Implementation Details. For robustness, I note that `master` is specifically the `patch_10Feb2021` tag at time of filing.

**Related Issue(s)**

Iterative improvement on #2549, other Kokkos/SNAP PRs.

**Author(s)**

Evan Weinberg (NVIDIA). eweinberg [at] nvidia.com preferred, evansweinberg [at] gmail.com for "long-lived".

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues.

**Implementation Notes**

* https://github.com/lammps/lammps/commit/d23755085467590d5382322139f6cd933b64c302 +https://github.com/lammps/lammps/commit/334c0d9969a1c164b39654258cbd083a85c5ca46: Replace the `dir` runtime variable in the `SNAKokkos` class with a template parameter to the `*ComputeFusedDeidrj` tag. Latter commit fixes a host CPU compile-time error uncovered when compiling with just the `Serial` Kokkos backend. Generally iso-performance.
* https://github.com/lammps/lammps/commit/fc572a0ca8a6cd0e711899896dff2431c9b790fa: Cleanup of various "magic numbers", such as the `4`s in the `{vector_length, 4, 1}` tilesizes passed to Rank-3 `MDRangePolicy`, replacing them with `static constexpr int` values defined in `pair_snap_kokkos.h`. This streamlines further performance tuning, and opens up the possibility of cleaner per-accelerator tuning if strictly necessary. Also introduces a wrapper for determining scratch memory allocations.
* https://github.com/lammps/lammps/commit/dd2fc5df62f1406a61b842aaf5d8931ef26a9573: Adds `Kokkos::LaunchBounds` declarations to the various performance-critical kernels, which maps to CUDA `__launch_bounds__` "under the hood". The bounds are self-consistently set with the `static constexpr int` team/tile sizes in https://github.com/lammps/lammps/commit/fc572a0ca8a6cd0e711899896dff2431c9b790fa. This empirically leads to performance stability across CUDA toolkit versions, smoothing out regressions in 11.0 and 11.1 relative to 10.1.
* https://github.com/lammps/lammps/commit/ca39dea58bb657893322ce68f446b9e32ec1e644: Purely cleanup, hiding some of the repetitive details in the Rank-3 `MDRangePolicy` behind a templated "`Snap3DRangePolicy`" and in the AoSoA team policies behind a templated "`SnapAoSoATeamPolicy`". Not married to any names or design choices.
* https://github.com/lammps/lammps/commit/8e8ef0cf63330504b2a71602fbeb293648bcf3b1: Found a 1-2% speed-up from re-tuning the `{32, 4, 1}` tiling of `ComputeYi` and `ComputeZi` to `{32, 8, 1}` (abstracted behind the other cleanups above).

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

None.

### CODE REVIEW

**Comment by stanmoore1** [comment]
Thanks @weinbe2 I'll take a look.

**Comment by weinbe2** [comment]
Performance differences pre- and post-`Kokkos::LaunchBounds` (note this is pre-ComputeYi re-tuning), measured on Summit. 2J8 problem, 16,000 atoms.

| CUDA version | fc572a0 | dd2fc5d | % change |
|---|---|---|---|
| 10.1.243 | 38.766 | 39.449 | +1.76% |
| 11.0.3 | 37.975 | 38.191 |  +0.57% |
| 11.1.1 | 37.223 | 39.336 | +5.68% |
| 11.2.0 | 41.730 | 41.388 | -0.82% |

The addition of `Kokkos::LaunchBounds` is broadly beneficial, except to a marginal perf loss for 11.2.0.

**Comment by stanmoore1** [comment]
@weinbe2 the performance looks fine to me, I wouldn't worry about a sub-1% regression.

**Comment by weinbe2** [comment]
@stanmoore1 accidentally missed your message... sooo:

Performance comparisons between `master` and this PR, using CUDA 11.2.0 on Summit (speedups to be larger for other CUDA versions since 11.2.0 is the worst case of the `Kokkos::LaunchBounds` change).

Input file | 2Jmax | Problem Size (atoms) | Timesteps/sec master | Timesteps/sec PR | Perf change | Comment
-- | -- | -- | -- | -- | -- | --
2J8 benchmark | 8 | 4000 | 307.695 | 309.182 | ~1x  | Benchmark problem
2J14 benchmark | 14 | 4000 | 32.4867 | 32.7502 | 1.01x | ECP KPP problem
in.snap.W.2940 | 8 | 128 | 1315.24 | 1306.75 | 0.99x  | /examples/snap/ single atom
" | " | 1024 | 758.898 | 754.505 |  0.99x | increased problem size
in.snap.WBe.PRB2019 | 8 | 128 | 1279.49 | 1269.00 | 0.99x | /examples/snap/ multi-atom, no chem
" | " | 1024 | 744.639 | 741.668 | ~1x | increased problem size
in.snap.InP.JCPA2020 | 6 | 512 | 816.806 | 811.176 | 0.99x | /examples/snap/ multi-atom, yes chem
" | " | 4096 | 200.118 | 201.826 | 1.01x | increased problem size

**Review by stanmoore1 — APPROVED** [review]

**Comment by stanmoore1** [comment]
@weinbe2 the code looks OK to me.

**Comment by stanmoore1** [comment]
I'm going to spot check this on Summit, then it should be ready to merge.

**Comment by stanmoore1** [comment]
Performance and numerical correctness were good for my spot check.

**Pull request merged**
