### PR TITLE
Fix rcb balance issue

### PR DESCRIPTION
**Pull request by akohlmey**
## Purpose

 implement changes suggested in issue #888

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp here is the "lost commit" rebased to the current master and another doc update commit, that may have been lost in the process as well. FYI, the branch is "open", so you can pull it and push changes to it.

**Comment by sjplimp** [comment]
changed the corner case with shrink-wrap size = 0.0 to reset it to original box
size, not something based on neighbor skin, which could produce a box size
larger than original box

**Comment by akohlmey** [comment]
@sjplimp it is a bit difficult to see what are the real final changes that are going to be applied to master with a pull request that was created such a long time ago. however, i did a manual test merge in my local repository and compared that to master and it looks ok there. so i am handing this back to you for merging.

**Comment by sjplimp** [comment]
@akohlmey I made my changes to all 3 files based on the current master files, so it should be fine.

**Pull request merged**
