### PR TITLE
Refactor some declarations in KOKKOS package

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

Adds C++11 template helpers to shrink larger declarations.

* Consistently make use of existing `typename AT` instead of `typename ArrayTypes<DeviceType>`
* Adds `KKDeviceType` to avoid having to write `typename KKDevice<DeviceType>::value`
* Adds `KKScatterView` in `kokkos_type.h`
* Add aliases `KKScatterSum`, `KKScatterDuplicated`, and `KKScatterNonDuplicated`
* Add `DupScatterView` and `NonDupScatterView` to shrink declaration further.
* Add `NeedDup_v` and `AtomicDup_v` helper aliases

**Related Issue(s)**

**Author(s)**

@rbberger  (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Review by stanmoore1 — APPROVED** [review]
Looks good, thanks @rbberger!

**Comment by stanmoore1** [comment]
@rbberger do you have more changes, or should I run this through Kokkos regression testing?

**Comment by rbberger** [comment]
@stanmoore1 One more, pushing in a few minutes

**Comment by stanmoore1** [comment]
Running Kokkos regression tests now.

**Comment by stanmoore1** [comment]
Kokkos regression tests all passed, this is ready to merge in my opinion.

**Comment by akohlmey** [comment]
This now has merge conflicts

**Comment by stanmoore1** [comment]
@akohlmey fixed

**Pull request merged**
