### PR TITLE
Implementation of analytical expressions for Born matrix of some potentials & inclusion of angle contribution to stress/mop/profile

### PR DESCRIPTION
**Pull request by evoyiatzis**
**Summary**

Implementation of analytical first and second order derivatives of potential energy with respect to distance for bond style gaussian - mm3 - harmonic_shift_cut, angle style quartic - mm3 - cosine_periodic and dihedral style helix - quadratic. It also fixes a missing flag for born_matrix calculations in angle style fourier.

Implementation of compute_angle() and compute_dihedral() methods in compute stress/mop/profile which handle the angle and dihedral contributions to local stress. The compute_angle() method is almost identical to the one at compute stress/mop and differs in having a loop around the locations of the planes where the stress profile has been requested. 

**Related Issue(s)**

No related issue

**Author(s)**

E. Voyiatzis - email evoyiatzis@gmail.com (NovaMechanics Ltd)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issue with backward compatibility

**Implementation Notes**

For simple test systems, the energy was obtained via the bond_write/angle_write/dihedral_write  commands and the numerical  values of the first and second partial derivatives were obtained via numerical differentiation. These data agree with the implemented expressions in the born_matrix functions.
The results from compute stress/mop/profile has been checked against results from compute stress/mop and the angle contributions have been found to be the same up to numerical precision.

**Post Submission Checklist**

- [X] The feature or features in this pull request is complete
- [X] Licensing information is complete
- [X] Corresponding author information is complete
- [X] The source code follows the LAMMPS formatting guidelines
- [X] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@evoyiatzis the changes to compute stress/mop and stress/mop/profile currently conflict with upstream. You should merge in the develop branch and resolve the conflicts.

**Comment by akohlmey** [comment]
@evoyiatzis yes, the merge conflict seems to be gone. things are currently moving rather slowly due to the LAMMPS workshop, multiple vacations, other commitments, side projects etc.

**Comment by evoyiatzis** [comment]
The 36th Windows Unit test fails with the message 

36: [ RUN      ] ComputeGlobalTest.Geometry
36: D:\a\lammps\lammps\unittest\commands\test_compute_global.cpp(232): error: Expected equality of these values:
36:   mop2[0][1]
36:     Which is: 8.0124486875236979e-312
36:   0.0
36:     Which is: 0
36: D:\a\lammps\lammps\unittest\commands\test_compute_global.cpp(233): error: Expected equality of these values:
36:   mop2[0][2]
36:     Which is: 8.0124895595587905e-312
36:   0.0
36:     Which is: 0

In my eyes 8.0124895595587905e-312 is quite close to 0. Also, the code passes the unit test on MacOS.

**Comment by akohlmey** [comment]
> The 36th Windows Unit test fails with the message
> 
> 36: [ RUN ] ComputeGlobalTest.Geometry 36: D:\a\lammps\lammps\unittest\commands\test_compute_global.cpp(232): error: Expected equality of these values: 36: mop2[0][1] 36: Which is: 8.0124486875236979e-312 36: 0.0 36: Which is: 0 36: D:\a\lammps\lammps\unittest\commands\test_compute_global.cpp(233): error: Expected equality of these values: 36: mop2[0][2] 36: Which is: 8.0124895595587905e-312 36: 0.0 36: Which is: 0
> 
> In my eyes 8.0124895595587905e-312 is quite close to 0. Also, the code passes the unit test on MacOS.

If this was around 1e-15 I would more easily believe that this is a rounding issue. However, this looks more like there is access to uninitialized data. This does not always show, especially not outside the unit tests, since many memory allocator algorithms use a copy-on-write mmap() of the /dev/zero device to allocate large chunks of memory quickly on the heap. Those are 0.0 on the first use, but will have some random bit-patterns. Since also there are failing Linux unit tests, I would suggest to test on Linux after setting up valgrind and use `ctest -T memcheck` to have a look at possible memory access issues.

**Comment by evoyiatzis** [comment]
> 
> If this was around 1e-15 I would more easily believe that this is a rounding issue. However, this looks more like there is access to uninitialized data. This does not always show, especially not outside the unit tests, since many memory allocator algorithms use a copy-on-write mmap() of the /dev/zero device to allocate large chunks of memory quickly on the heap. Those are 0.0 on the first use, but will have some random bit-patterns. Since also there are failing Linux unit tests, I would suggest to test on Linux after setting up valgrind and use `ctest -T memcheck` to have a look at possible memory access issues.

Thanks for the suggestion. I will look into it.

**Comment by evoyiatzis** [comment]
Closed by accident! I just realized it.

**Comment by athomps** [comment]
@evoyiatzis I just looked at this again. It looks very close to being finished, but there are some outstanding issues with uninitialized data. Do you have any updates?

**Comment by evoyiatzis** [comment]
@athomps   the one discussed on 27 - 28 Sep has been resolved.  are there still outstanding issues?

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
