### PR TITLE
Implement force history in Mindlin granular pair styles

### PR DESCRIPTION
**Pull request by jibril-b-coulibaly**
**Summary**

All styles with contact history are currently implemented by storing the accumulated tangential displacement $\xi$. This works fine when the tangent stiffness is constant. For the Mindlin styles (*mindlin* and *mindlin_rescale*), the tangent force is currently given by $F_t = -k_t a \xi$ (we neglect damping for simplicity). The stiffness depends linearly on the contact area which makes this approach inadequate, in particular:
1. tangential force increases with increasing normal displacement (increasing $a$) and zero tangential displacement
2. tangential force decreases with decreasing normal displacement (decreasing $a$) and zero tangential displacement. The re-scaling of $a$ by the *mindlin_rescale* therefore decreases the force proportionally to $a^2$ instead of $a$ as expected.

These aspects, and their resolution by the present PR, are illustrated in the MWE pasted at the end. This supports the redefinition of the contact history for Mindlin styles to be the accumulated tangential force and not the accumulated tangential displacement. This is consistent with [Johnson, 1985](https://doi.org/10.1017/CBO9781139171731) and other displacement-driven formulations of the Mindlin & Deresiewicz, 1953 model, e.g., [Thornton et al., 2013](http://dx.doi.org/10.1016/j.powtec.2012.08.012) (cited in the doc) or [Di Renzo & Di Maio, 2004](https://dx.doi.org/10.1016/j.ces.2003.09.037).

The same formulation is also present in older styles *gran hertz/history*. I have not addressed them there because I wasn't sure if style *granular* is supposed to eventually supersede the *gran* styles.

The documentation is updated accordingly and typos have been fixed.

**Author(s)**

Jibril B. Coulibaly, Northwestern University (jibril.coulibaly@northwestern.edu)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No breaking of backward compatibility

**Implementation Notes**

For the Mindlin styles only:

- the `history` vector now stores the elastic part of the tangential force
- identical formulas apply for the change of frame of reference (Luding, 2008)
- the elastic force is incremented `history -= k_t * vtr * dt` instead of the displacement `history += vtr * dt`
- the tangential force calculations and Coulomb limit re-scaling are adjusted accordingly

For all other styles, the accumulated displacement formulation is left unchanged. Both formulations are equivalent when the stiffness is constant and we might want to generalize the accumulated tangential force formulation.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

MWE showing abnormal changes in tangential force in absence of tangential displacement:
```
# LAMMPS input file showing changes in tangential force with no change in tangent displacement when using mindlin styles
#
# * CASE 1 - mindlin:
#    + Expected behavior: tangential force remains constant during loading and unloading (unless Coulomb limit reached)
#    + LAMMPS 15 Jun 2020: tangential force increases during loading and decreases during unloading proportional to contact radius $a$: issue
#    + This patch: tangential force remains constant during loading and unloading: expected behavior
#
# * CASE 2 - mindlin_rescale:
#    + Expected behavior: tangential force remains constant during loading, decrease by factor $a$ during unloading (unless Coulomb limit reached)
#    + LAMMPS 15 Jun 2020: tangential force increases during loading and unloading, decrease by factor $a^2$, instead of $a$: issue
#    + This patch: tangential force remains constant during loading and decreases by factor $a$ during unloading: expected behavior
#
# * CASE 3 - liinear_history:
#    + Expected behavior: tangential force remains constant during loading and unloading (unless Coulomb limit reached)
#    + LAMMPS 15 Jun 2020: expected behavior: formulation correct for constant tangential sitffness
#    + This patch: expected behavior: formulation unchanged for style linear_history
#

units si
dimension 3
boundary p p p
atom_style sphere
comm_modify	vel yes
newton off
atom_modify map yes

region box block -5 5 -5 5 -5 5
create_box 1 box

create_atoms 1 single -0.25 0.0 0.0 #Create particle 1
create_atoms 1 single -0.25 -0.8 0.0 #Create particle 2
set group all diameter 1.0 # Unit diameter

pair_style	granular

# Case 1: mindlin. Comment / uncomment to change pair_style
pair_coeff * * hertz/material 1000 0 0.3 tangential mindlin NULL 0 0.1

# Case 2: mindlin_rescale. Comment / uncomment to change pair_style
#pair_coeff * * hertz/material 1000 0 0.3 tangential mindlin_rescale NULL 0 0.1

# Case 3: linear history. Comment / uncomment to change pair_style
#pair_coeff * * hertz/material 1000 0 0.3 tangential linear_history 100 0 0.1


# -- Monotonic oblique loading to generate some tangential force

compute 1 all pair/local force p4 
compute 2 all reduce ave c_1[*]

variable vx equal 1e5
variable vy equal 1e5
group p2 id 2
fix 1 p2 move variable NULL NULL NULL v_vx v_vy NULL
thermo 1
thermo_style custom step c_2[*]
run 10


# -- Loading / Unloading in normal direction to assess variation of tangential force

variable Nrun equal 10000
variable var_ft equal c_2[2]/$(c_2[2])

variable delta equal "1.0 - sqrt((x[1]-x[2])^2 + (y[1]-y[2])^2)"
variable a equal sqrt(0.5*v_delta)
variable var_a equal v_a/$(v_a)
variable var_a_sq equal v_a*v_a/$(v_a*v_a)

variable vx equal $(0.1*(x[1]-x[2])/(v_Nrun*dt)) # Loading (comment for unloading)
variable vy equal $(0.1*(y[1]-y[2])/(v_Nrun*dt)) # Loading (comment for unloading)

#variable vx equal $(-0.1*(x[1]-x[2])/(v_Nrun*dt)) # Unloading (comment for loading)
#variable vy equal $(-0.1*(y[1]-y[2])/(v_Nrun*dt)) # Unloading (comment for loading)

thermo_style custom step c_2[*] v_var_ft v_var_a v_var_a_sq
thermo $(v_Nrun/10)
run $(v_Nrun)
```

### CODE REVIEW

**Comment by jibril-b-coulibaly** [comment]
Dear developers and reviewers,

I am following up on this PR. I would appreciate some feedback on the principles and relevance of the proposed change, i.e., storing the elastic tangential force history instead of tangential displacement history, for Mindlin styles.

I am aware of the current difficulties we all face and only remotely understand the demand of maintaining a large software with an active developer community. While recognizing other PRs importance and priority, I would kindly request some feedback for moving this PR forward as it may impact the correctness of the related granular simulations.

Best Regards

**Comment by sjplimp** [comment]
@jibril-b-coulibaly Dan B has said he will look at it.  But he didn't find out about it until recently
b/c somehow the auto-notification of GHub didn't work for him.  So some feedback soon I think.

**Comment by dsbolin** [comment]
@jibril-b-coulibaly Apologies for the delay, and thank you (again) for your contribution and detailed insights into the granular code!

I haven't looked into this in as much detail as you have, so I'm happy to defer to you. I will read up on the theory a little more, but my first thought is this: the true Mindlin-Dersiewicz conditions are extremely complicated, see e.g. [Vu-Quoc and Zhang](https://doi.org/10.1016/S0167-6636(98)00064-7) . Both the proposed changes and the existing code are coarse approximations to the theory. It isn't obvious to me that one is clearly a better approximation than the other. For instance, it's not obvious to me that tangential force increasing with increasing normal displacement and zero tangential displacement is wrong - in a biaxial loading, strain in e.g. the primary direction will increase stress in the secondary direction, even with zero strain in the secondary direction (Poisson effect). This is just my superficial justification for not discounting this behavior qualitatively, correct me if it doesn't apply here.

The current implementation has some historical/community justification behind it (my understanding is that `mindlin` mirrors the LIGGGHTS/EDEM/pair gran/hertz/history implementations). So in that sense, I think there is value having it as an option. The `rescale` option is based on some discussion with Otis Walton (and possibly published work of his, but I can't seem to find the reference). Your suggestions may provide an additional improvement, and I would not discount them, as they do match some of the literature you cited more closely. How would you feel about adding your proposed method as an additional option (e.g. `mindlin/force`?) rather than replacing the existing `mindlin` code?

**Comment by jibril-b-coulibaly** [comment]
@dsbolin thank you very much for your informed and detailed answer.

I would agree with you that the
>true Mindlin-Dersiewicz conditions are extremely complicated

and I am in favor of using the simplified version. My understanding is that the 2 major simplifications are that:

- the tangential stiffness is considered constant and equal to 8 G_eff (i.e., the initial tangential stiffness of the true (non-constant) Mindlin partial-slip solution)
- the complex and irreversible path-dependence of the true Mindlin-Dersiewicz conditions is disregarded and the constant tangential stiffness of 8 G_eff is used instead

**1. Mindlin and tangential force for no tangential displacement**
Regarding the analogy with Poisson's effect in bi-axial compression, I believe this would also occur for frictionless disks, so I am not sure if this would apply for identifying the tangential displacement/force relationship. To investigate whether
> tangential force increasing with increasing normal displacement and zero tangential displacement

is correct or not, I based the argument that it should not be correct in my (also recent) understanding of the Mindlin, Deresiewicz model. In [Johnson, 1985](https://doi.org/10.1017/CBO9781139171731) (7.3 Simultaneous variation of normal and tangential forces) it is reported:
> Consider the case where tangential force, having been applied, is kept constant while the normal force is varied. Increasing the normal force increases the area of contact, but leaves the tangential traction unchanged, so that a traction-free annulus grows at the edge of the contact area.

This approach is force-based so it does not really tell if the tangential displacement would also remain unaffected. From the consideration (also presented in Johnson 1985) that normal and tangential strain (displacement) fields can be decoupled, I assume tangential displacement should also remain constant in that case. This seems to be further supported by the displacement formulation of the Mindlin & Deresiewicz conditions by [Di Renzo & Di Maio, 2004](https://dx.doi.org/10.1016/j.ces.2003.09.037). In that paper (2.1.3. Normal displacement varying, tangential displacement varying), Eq (20) shows that increasing normal displacement at constant tangential displacement should cause no change in tangential force. A similar result is obtained for example by [Agnolin  Roux, 2007](http://dx.doi.org/10.1103/PhysRevE.76.061302) and  [Thornton et al., 2013](http://dx.doi.org/10.1016/j.powtec.2012.08.012), where the tangential force is formulated incrementally, i.e., effectively storing the tangential force instead of the tangential displacement.

**2. Mindlin rescale and decreasing normal displacement**

The `rescale` option appears to be a simplification of the Mindlin & Deresiewicz conditions when the normal force decreases. Following the previously quoted sentence, [Johnson, 1985](https://doi.org/10.1017/CBO9781139171731) continues:
> Decreasing the normal force causes a reduction in the contact area and thereby releases some of the tangential traction. In order to maintain equilibrium with the constant tangential force the inner boundary of the annulus of slip must contract until eventually, when P reaches the value Q/mu, the contact will slide.

It appears that the `mindlin_rescale` option does so in a simplified way by re-normalizing the current tangential displacement by the new contact radius `a`. I could not find the paper by Walton but it is referred to by both [Agnolin  Roux, 2007](http://dx.doi.org/10.1103/PhysRevE.76.061302) and [Thornton et al., 2013](http://dx.doi.org/10.1016/j.powtec.2012.08.012) who use a similar technique as the `mindlin_rescale`.

However, these papers perform such re-normalization on the tangential force, and not the tangential displacement. This is what I highlighted in my MWE, case 2. When both storing and normalizing the tangential displacement, the tangential force is effectively normalized twice, resulting in a normalization of `a^2`, instead of the expected `a`. Such unloading behavior also supports the idea of storing and incrementing the tangential force.

**3. Implementation**

I will gladly write the proposed modification on the side of the existing `mindlin` options. As it affects both `mindlin` and `mindlin/rescale`, I would suggest to implement it as an option for both `mindlin` styles, instead of 2 new separate styles.

Hoping this was clear and concise enough, I will go on to perform these requested changes.

**Comment by dsbolin** [comment]
@jibril-b-coulibaly Thank you for the detailed explanation! I think I now see both your points, and I agree that your suggested changes are an overall improvement over the existing `mindlin` options. To summarize my understanding: the current displacement-based `mindlin` implementation is problematic for the reasons you point out, but in the same way that most/many tangential model implementations are problematic. The current `mindlin/rescale` implementation is problematic in its own special way, as compared to other implementations and the literature. I suggest the following: 
- keep `mindlin` for historical reasons as I mentioned, with the option of the force-based rather than displacement-based formulation as you suggest; make the default behavior displacement-based (i.e. current behavior)
- change `mindlin/rescale` so that its default behavior is force-based, as you suggest. Possibly keep the current behavior (displacement-based) as an option

I could see how this would cause some confusion, since in one case, the default behavior is displacement-based, in the other it is force-based; however, it would make the default behavior consistent with most other implementations and the literature (though arguably, as you point out, displacement-based treatment for `mindlin` is not even consistent with the literature). I'm certainly open to variations on this and would defer to you, what are your thoughts?

**Comment by jibril-b-coulibaly** [comment]
@dsbolin thank you for your suggestions.

> the current displacement-based mindlin implementation is problematic for the reasons you point out, but in the same way that most/many tangential model implementations are problematic. The current mindlin/rescale implementation is problematic in its own special way, as compared to other implementations and the literature.

I would complement it with the following:
- 1- both displacement-based `mindlin` and `mindlin_rescale` are identically problematic upon (oblique) loading
- 2- `mindlin_rescale` is problematic in its own way upon (oblique) unloading (normalization by `a^2`)

Regarding other tangential models (`linear_nohistory` and `linear_history`) this problem does not occur because the tangential stiffness is constant and independent of the normal indentation/contact area. For these models, storing the tangential force or the tangential displacement is effectively identical. For the displacement-based `mindlin` model, we have an additional consequence:
- 3- `mindlin` already performs normalization by `a` upon unloading (and behaves kind of like the intended `mindlin_rescale`) because what makes it problematic is that the displacement-based force is, at all times, proportional to `a`.

I agree that given the implementation history, it is a good idea to allow both a displacement-based and a force-based model, for both `mindlin` and `mindlin_rescale` as you suggest. Although some combinations might have issues (that we can inform about in the doc), it would be a more simple and symmetric implementation to allow for all 4 cases. This would differ from implementing defaults as you suggested, but in order to avoid optional keywords that would be specific to the tangential styles, and in a similar manner as `hertz` and `hertz/material`, I suggest implementing the 4 following cases, ordered from "worst" to "best" model (with lots of caution on "worst" and "best") :

- `mindlin_rescale`: displacement-based, unchanged, with the previously identified problems
- `mindlin`; displacement-based, unchanged, with the previously identified problems
- `mindlin/force`: force-based version of `mindlin`. Solves the previously identified problem (1) upon loading. Is not energetically consistent upon unloading (discussion of Walton, [Agnolin  Roux, 2007](http://dx.doi.org/10.1103/PhysRevE.76.061302) and  [Thornton et al., 2013](http://dx.doi.org/10.1016/j.powtec.2012.08.012))
- `mindlin_rescale/force`: same as `mindlin/force` upon loading. Solves the previously identified problems (2) and (3) and is energetically consistent upon unloading (same implementation as, [Agnolin  Roux, 2007](http://dx.doi.org/10.1103/PhysRevE.76.061302) and  [Thornton et al., 2013](http://dx.doi.org/10.1016/j.powtec.2012.08.012))

Would that work ?

**Comment by dsbolin** [comment]
@jibril-b-coulibaly That sounds great. Minor tweak: how do you feel about the names being: `mindlin_rescale`, `mindlin`, `mindlin_force` and `mindlin_rescale_force` instead? The `/` makes sense given the history of the development of these variants, but I feel like the combination of `_` and `/` could be confusing to someone coming at this with fresh eyes? I don't feel strongly about this, happy with whatever you choose.
Thanks again!

**Comment by sjplimp** [comment]
@dsbolin @jibril-b-coulibaly If you are now talking about syntax for the 4 options for the input script command ... we typically avoid underscores in command args.  As Dan noted the "/" implies a derivative version.  So does mindlin (original, correct?) and mindlin/force and mindlin/rescale and mindlin/rescale/force make conceptual sense?

**Comment by jibril-b-coulibaly** [comment]
@sjplimp Thank you very much for your input. This is very valuable as I would not have known syntax preferences.

- Suffixing `/force` would make conceptual sense a a derivative version of the original `mindlin` and `mindlin_rescale`.
- `mindlin_rescale` is not exactly, in my mind, a derivative version of `mindlin` (they do different things upon unloading, v.s. doing the same thing in a different way like `hertz` and `hertz/material`)
- Although underscores should be avoided, changing to `mindlin/rescale` would not be backward compatible with the original `mindlin_rescale`

This is ma rationale to support `mindlin`, `mindlin_rescale`, `mindlin/force`, `mindlin_rescale/force`. If underscores take precedence over backward compatibility, then `mindlin/rescale/force` is also fine with me.

**Comment by dsbolin** [comment]
@sjplimp @jibril-b-coulibaly To clarify, these are not names of separate pair styles, but names of options to the `pair coeff` command of the `pair granular` pair style, particularly sub-options to the `tangential` model specifications. Different options do lead to different pair interactions, but as far as implementation and syntax, they are treated as part of the same pair style. I suggested keeping it all underscores, because other existing options to `pair coeff` for `pair granular` also have underscores, e.g. `tangential linear_history`, `damping mass_velocity`, etc.  So the full syntax would be:
```
pair_style granular
pair_coeff * * hertz 1000.0 50.0 tangential mindlin 1.0 0.4 damping mass_velocity
```

or

```
pair_style granular
pair_coeff * * hertz 1000.0 50.0 tangential mindlin_force 1.0 0.4 damping mass_velocity
```
etc.

What you're suggesting would make it:

```
pair_style granular
pair_coeff * * hertz 1000.0 50.0 tangential mindlin/force 1.0 0.4 damping mass_velocity
```
etc.

**Comment by sjplimp** [comment]
@jibril-b-coulibaly @dsbolin I think I now agree with either of your last suggestions.  Either all 4 variants of tangential could have only underscores, if that's consistent with all the other pair_granular coeff options.  Or mindlin and mindlin_rescale with or without /force
added to each would also be fine.

**Comment by jibril-b-coulibaly** [comment]
I restored the original `mindlin` and `mindlin_rescale`. I implemented the stored tangential force in `mindlin/force` and `mindlin_rescale/force` and adjusted the documentation accordingly.

I have an issue that might be problematic with `EPSILON = 1e-10` defined herein. I am thinking the threshold might be passed for small granular media with small forces, e.g. micrometer particles in `si` units (see e.g., issue #2105).
Do you think it could be resolved the same way here, i.e. replacing:

```cpp
if (fabs(rsht) < EPSILON) rsht = 0;
```

by something similar to
```cpp
if (fabs(rsht) == 0) rsht = 0;
```

Thank you for your guidance

**Comment by akohlmey** [comment]
> by something similar to
> 
> ```c++
> if (fabs(rsht) == 0) rsht = 0;
> ```

This statement has no effect. What you should be looking for is a (relevant) parameter p that has the same unit as 'rsht' and then you can use `p*EPSILON` as threshold - adjusting EPSILON if p is usually large -  so that this becomes a relative threshold instead of an absolute one.

> Thank you for your guidance

**Comment by dsbolin** [comment]
@jibril-b-coulibaly Good point. Note that `rsht` is a dot product of tangential displacement and (normalized) contact vector, so its units are just length. All this is meant as a check as to whether the tangential displacement is no longer perpendicular to the contact vector $\mathbf{n}$, i.e. if the dot product is > 0. Strictly speaking, the correct normalization is the magnitude of the tangential displacement, which would make `rsht` 0-1; however, the square root is a notoriously slow operation, and this is done for every pair at every step, hence the 'lazy' simple comparison to `EPSILON`. My suggestion for a compromise: how about comparing to  `Reff*EPSILON` instead? This would address your concerns about units I think?

**Comment by jibril-b-coulibaly** [comment]
Thank you @dsbolin @akohlmey for the suggestion.

Regarding the implementation of the history update as proposed by [Luding 2008](https://doi.org/10.1007/s10035-008-0099-x), I have a question about the dot product that might suppress the need for `EPSILON` altogether. The history update starts with:

```cpp
rsht = history[0]*nx + history[1]*ny + history[2]*nz;
if (fabs(rsht) < EPSILON) rsht = 0; // EPSILON = 1e-10 can fail for small granular media: 
if (rsht > 0) {
```

`rsht` is defined as the dot product between the previous accumulated displacement `history`, and the current normal vector. This could miss rotation of the frame of reference in some directions as illustrated below in 2D:
- if the pair rotates counter-clockwise, `rsht` is positive and the `history` vector is transported
- if the pair rotates clockwise, `rsht` is negative, skips the test, and the `history` vector is not transported as it should.

luding

If that is the case, I do not see the need for the variable `EPSILON`. The scaling factor should also be corrected in
```cpp
scalefac = shrmag/(shrmag - rsht);
```
since `shrmag - rsht` is not exactly the norm of the projected `history` vector $\xi' - n (\xi' \cdot n)$.

**Comment by dsbolin** [comment]
@jibril-b-coulibaly Sorry, not sure I follow. Would the **fabs**(`rsht`) not take care of the two possibilities you listed? 

Your are correct that the `EPSILON` check isn't strictly needed. The rationale for it is to avoid the somewhat expensive rotations of the tangential displacement in cases where the dot product being non-zero is caused by numerical differences rather than rigid-body rotations - i.e. only rotate displacements if the pair has actually undergone rigid body rotation. This follows the original `pair gran/hertz/history` implementation (though that one has an error in not rescaling the displacements).

Having said that, there is another problem with this approach that I'm aware of but don't have a good fix for, and that's rigid body rotation about the contact vector $\mathbf{n}$ (no easy way to visualize in 2D). These are completely missed in Luding's paper and in the current implementation (and most others I'm aware of). This is something I've wanted to revisit at some point, but ran out of time, shifted focus, etc.  Happy to discuss more, but maybe we should create a separate pull request/discussion from the `mindlin`, `mindlin_rescale` displacement vs force issue of this one?

**Comment by dsbolin** [comment]
Sorry, disregard - I see what you mean now, the second `if` statement is the problem, not the `EPSILON` comparison. Yes, this needs to be corrected.

**Comment by jibril-b-coulibaly** [comment]
That is right. I think the test `if (rsht > 0)` should be deleted altogether.

First, unless there is a specific reason why we would only update the frame of reference if the deviation from perpendicular is large enough, I believe it should be updated on every timestep.

Second, the current implementation does not exactly performs the rescaling, i.e. `scalefac = shrmag/(shrmag - rsht);` is not the adequate formula (this formula is the one in the doc and is consistent, but it is not the one given in Luding 2008.

I suggest the following changes, in 2de9899

**Comment by dsbolin** [comment]
@jibril-b-coulibaly I suspect you're right (as usual). I'll take a look later this week at the rescaling equations (sorry I'm a bit swamped currently).

As for this:
>  a specific reason why we would only update the frame of reference if the deviation from perpendicular is large enough

Two reasons:
1. Computational cost. For a simple pair style like pair gran/hooke, the extra `sqrt` could add noticeable computational cost (maybe ~10-20%)
2. When you have very small rigid body rotations (or essentially none, but the relevant dot product would be non-zero due to machine precision), the re-scaling amounts to redundant operations with very small numbers, and you may introduce unwanted/unnecessary loss of precision.

**Comment by jibril-b-coulibaly** [comment]
@dsbolin I understand! I am piecing these considerations together with your previous comment about the dot product and I see what I was missing.

To get a test that is (1) cheap, (2) uses a relative value as suggest by @akohlmey, and (3) would work for `history` being either the accumulated displacement or the force, I propose to normalize the dot product by the critical displacement / force.
This would require to separate cases for testing, but seems to be the only way to normalize `history` that can be a force or a displacement depending on the tangential style. This would look something like:

```cpp
bool dev;
if (tangential_model[itype][jtype] == TANGENTIAL_MINDLIN_FORCE ||
    tangential_model[itype][jtype] == TANGENTIAL_MINDLIN_RESCALE_FORCE)
  dev = fabs(rsht) < EPSILON*Fscrit;
else
  dev = fabs(rsht)*k_tangential < EPSILON*Fscrit;
if dev {
//update frame of reference
```

**Comment by akohlmey** [comment]
Updated to latest master and fixed issues in the added documentation text

**Comment by dsbolin** [comment]
@jibril-b-coulibaly Sorry for the delay responding. About this:

> Second, the current implementation does not exactly perform the rescaling, i.e. scalefac = shrmag/(shrmag - rsht); is not the adequate formula. This formula is the one in the doc and is consistent, but it is not the one given in Luding 2008 which uses $| \xi |$ instead of $| \xi' | - n \cdot \xi'$

I think my original reasoning was that the rotation (i.e. removal of non-tangential component, followed by rescaling) is done before the displacement is updated, so the magnitude of the displacement at the previous time step should be preserved. So, in the current scheme, steps are :
1. Rotate displacement from the previous time step $\xi'$ into new frame of reference
  i. Remove non-tangential component \xi'  - (n \cdot \xi) n
  ii. Rescale to preserve magnitude of $\xi'$, i.e. multiply by $\frac{|\xi' |} { | \xi' | - n \cdot \xi'} $
2. The resulting displacement (denoted somewhat confusingly as $\xi$ in the doc page) is then incremented with the current time step tangential displacement.

I think the doc page may need clarification, in that $\xi$ is accumulated displacement corrected at the current time step due to possible rotation, but *before* it is incremented with the current timestep displacement. Taking the magnitude of both sides of the equation in the doc page shows that $|\xi| = |\xi'|$. 

The description in the Luding paper isn't entirely clear to me, so I'm not sure there's a disagreement there?

**Comment by jibril-b-coulibaly** [comment]
@dsbolin, thank you for taking the time to elaborate.

I agree with everything, in particular the rescaling procedure in order to obtain $|\xi| = |\xi'|$ with only tangential components.
My objection, and I should have made that clearer/simpler, is that:

- $| \xi' | - n \cdot \xi'$ is not the norm of $\xi'$ after removal of the non-tangential component
- The norm of $\xi'$ after removal of the non-tangential component is $ | \xi' - (n \cdot \xi') n | $, which differs since $\xi'$ and $(n \cdot \xi') n$ are not colinear.

This is the change I made to the formula in the doc: $\xi'$ is rescaled multiplying by $\frac{|\xi' |} { | \xi' - (n \cdot \xi') n |} $.

In the code, the magnitude of `history` after projection (`history[0] -= rsht*nx`, same for y and z), named `prjmag` is used in the scaling, i.e. `scalefac = shrmag / prjmag` instead of `scalefac = shrmag / (shrmag - rsht)`.

**Comment by dsbolin** [comment]
@jibril-b-coulibaly Thanks, I see it now - I think I had made a basic algebra mistake treating the norm as linear (clearly it's not). Thanks for the correction.

I'll go ahead and submit my review as approved. Sorry this took so long, and thank you for your patience and detailed explanations throughout!

**Comment by akohlmey** [comment]
@dsbolin @jibril-b-coulibaly thanks a **lot** for your effort and extensive discussions to work out the details of this contribution. @jibril-b-coulibaly do you have any additional changes planned for this, or do you consider this ready to be merged now, too? @sjplimp do you want to have a quick check for any formal details? I did some minor touching up a week ago and currently don't see anything cosmetic that requires an update.

**Comment by jibril-b-coulibaly** [comment]
Thank you @dsbolin @akohlmey @sjplimp. There is no additional change that I wish to add, this is ready to be merged

**Pull request merged**
