### PR TITLE
ML-PACE: upd/refactor includes

### PR DESCRIPTION
**Pull request by yury-lysogorskiy**
**Summary**

Refactor and update includes (see https://github.com/ICAMS/lammps-user-pace/pull/12)

**Related Issue(s)**

**Author(s)**

Axel Kohlmeyer and Yury Lysogorskiy

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@yury-lysogorskiy added support for KOKKOS and conventional make.

**Review by stanmoore1 — APPROVED** [review]

**Comment by stanmoore1** [comment]
I just tried to build `/lib/pace` with `python Install.py -b` and get this error:
```
src/ML-PACE/ace/ace_clebsch_gordan.cpp:1:10: fatal error: ace/ace_clebsch_gordan.h: No such file or directory
 #include "ace/ace_clebsch_gordan.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [src/ML-PACE/ace/ace_clebsch_gordan.o] Error 1
make: *** Waiting for unfinished jobs....
src/ML-PACE/ace/ace_spherical_polar.cpp:4:10: fatal error: ace/ace_spherical_polar.h: No such file or directory
 #include "ace/ace_spherical_polar.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by akohlmey** [comment]
> I just tried to build `/lib/pace` with `python Install.py -b` and get this error:
> 
> ```
> src/ML-PACE/ace/ace_clebsch_gordan.cpp:1:10: fatal error: ace/ace_clebsch_gordan.h: No such file or directory
>  #include "ace/ace_clebsch_gordan.h"
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [src/ML-PACE/ace/ace_clebsch_gordan.o] Error 1
> make: *** Waiting for unfinished jobs....
> src/ML-PACE/ace/ace_spherical_polar.cpp:4:10: fatal error: ace/ace_spherical_polar.h: No such file or directory
>  #include "ace/ace_spherical_polar.h"
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```

the updates to the Makefile in lib/pace were missing. Please pull and try again.

**Comment by stanmoore1** [comment]
Got farther and built `/lib/pace`, but now get an error when compiling LAMMPS:
```
../pair_pace_extrapolation.cpp:42:10: fatal error: ace/ace_b_basis.h: No such file or directory
 #include "ace/ace_b_basis.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by akohlmey** [comment]
> Got farther and built `/lib/pace`, but now get an error when compiling LAMMPS:
> 
> ```
> ../pair_pace_extrapolation.cpp:42:10: fatal error: ace/ace_b_basis.h: No such file or directory
>  #include "ace/ace_b_basis.h"
>           ^~~~~~~~~~~~~~~~~~~
> compilation terminated.
> ```

Grrr... It needed updates to Makefile.lammps as well. Hopefully, there is nothing else missing.

**Comment by stanmoore1** [comment]
Works now, thanks @akohlmey

**Pull request merged**
