### PR TITLE
Partially complete check of URLs in the LAMMPS manual

### LINKED ISSUE #2301: Check all URLs in the LAMMPS manual to be current and valid
**Summary**

In preparation for the upcoming stable release we should check whether any URLs in the LAMMPS manual (and README files and sources?) are current and pointing to the expected up-to-date destination.

### PR DESCRIPTION
**Pull request by mmansell7**
**Summary**

A random selection of URLs in the Manual UP TO SECTION 8.6.6 "Drude induced dipoles" was checked, and corrections were made where appropriate.

**Related Issues**

Partially fixes #2301 

**Author(s)**

Matt Mansell, independent researcher

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Changes are fully backward compatible.

**Implementation Notes**

1. I created and checked out a local branch as a copy of the lammps master branch
2. cd doc
3. build html
4. I opened html/Intro.html in Google Chrome
5. I proceeded through each page using the "Next" button. On each page, I randomly chose links to check.  I estimate that I checked 90% of links to web resources and 20% of links to other pages in the Manual.
6. If the link was broken, or if the link pointed to an inappropriate url, I replaced the url (in the corresponding src/*.rst file) with an appropriate working link. If the link text seemed unclear or incorrect, I updated the link text (in the corresponding src/*.rst file).

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

Known unresolved issues:
1. Complete review of the remainder of the Manual.

2. In Manual.rst/Manual.html: link to "Developer.pdf" only works if there is a "local" Developer.pdf, which
     is not true if the documentation was built as html (make html) and not as pdf (make pdf).  This is not 
     issue in the online version of the Manual, since there is a "Developer.pdf" file online.

3. Install_git.rst: line 83: seems to be a link to the wrong url, but I cannot identify the correct url.

4. Check README files(?)

5. Check sources(?)

### CODE REVIEW

**Comment by akohlmey** [comment]
@mmansell7 thanks for your efforts. much appreciated.
We are currently doing a significant overhaul of some parts of the manual, so you may want to keep your branch in-sync with the upstream master branch. Right now, for example, there is a merge conflict for the file `doc/src/Intro_website.rst`.

Some answers to your questions.

Developer.pdf: that file is obsolete and has been removed from the distribution. The contents of the source .tex file have been converted to restructured text and - somewhat - revised (still more to do) and integrated into the new "Programmer Guide" part of the manual.

Install_git.rst: there is no URL on line 83 of Install_git.rst in current master. Can you let me know which URL specifically you are referring to?

README files: yes, they may need updates, too. Those are not as important as the manual itself, but still worth checking. Those files tend to get even faster outdated than the main manual sources. This is a reason why we try to minimize or localize the content of those files and have most docs in the manual directly.

source files: yes, but even less so than README files. everything I wrote about README files applies to sources in an even more drastic fashion since even fewer people look at them, and often people "vanish" (i.e. move to a new job or leave research altogether) after completing the contribution to LAMMPS.

**Comment by mmansell7** [comment]
@akohlmey Thank you for the clarifications.  I am planning to get back to work on this PR shortly.  Thanks also for notifying @eagunn about potential overlap of this PR with #2334. I will try not to duplicate effort or introduce conflicts with that branch.

Install_git.rst, line 83: it is not a web URL, but a link to another page in the Manual (`:doc:'this page <Errors_bugs>'`). The destination page is supposed to discuss "Stable versions and what tagID to use...", but there is no explicit discussion of those topics on the "Errors_bugs" page.  Maybe "Errors_bugs" is the correct destination, but I was sufficiently uncertain that I wanted to ask about it.

**Comment by akohlmey** [comment]
> Install_git.rst, line 83: it is not a web URL, but a link to another page in the Manual (`:doc:'this page <Errors_bugs>'`). The destination page is supposed to discuss "Stable versions and what tagID to use...", but there is no explicit discussion of those topics on the "Errors_bugs" page. Maybe "Errors_bugs" is the correct destination, but I was sufficiently uncertain that I wanted to ask about it.

Ok. that link is indeed bogus. Looks like a copy-and-forgot-to-modify issue. I just fixed that. The proper target for that is external at: https://lammps.sandia.gov/bug.html#version

I made that change and also a few formatting updates in commit a72ebb2ab2ef72621b6b6b758c0f8a9a0254ae40 in my "small fixes collection PR" .

**Comment by mmansell7** [comment]
I have completed review of all User Documentation and Programmer Documentation pages, following the same procedure described in my earlier comment.  That is, I am not explicitly following every single link, rather doing my best to follow all "external" links (to URLs on the web) and a random sample covering a reasonable portion of "internal" links (to other Man pages).

I have been periodically merging with master and with PR #2334 , which was also created to address this issue #2301 .

I hope to continue on with the Indexes (Commands, Fixes, etc.) next.  However, there are so many pages that I may have to adjust the procedure and accept a lower coverage.

**Comment by akohlmey** [comment]
> I have completed review of all User Documentation and Programmer Documentation pages, following the same procedure described in my earlier comment. That is, I am not explicitly following every single link, rather doing my best to follow all "external" links (to URLs on the web) and a random sample covering a reasonable portion of "internal" links (to other Man pages).

@mmansell7 thanks a lot for your efforts. this is really helpful and comes at a very opportune time.
 
> I have been periodically merging with master and with PR #2334 , which was also created to address this issue #2301 .

hmm... that is actually making things a bit more complicated for me, but see below for my suggestion to deal with it.

> I hope to continue on with the Indexes (Commands, Fixes, etc.) next. However, there are so many pages that I may have to adjust the procedure and accept a lower coverage.

Indices are mostly auto-generated and the script run during "make style_check" in the doc folder should check for completeness and consistency with the C++ source. Internal link consistency should be done by sphinx itself.

given the complicated nature of reviewing these changes, I am thinking about doing a "manual" merge, i.e. download your branch and then do a side-by-side comparison  with a feature branch of my own (which has additional revisions to the documentation) and then transfer the parts I like, modify what needs adjustments and retain what may be done in anticipation of upcoming changes. i'd be incorporating changes from #2334 in the same branch as well.

that would mean it is likely best to "abandon" this branch and then start working on something that doesn't overlap with this, e.g. README files or source code or wait until #2336 has been merged and then start a new feature branch from master.

Please let me know what you think and what is a way to move forward that is agreeable with you.

**Comment by mmansell7** [comment]
@akohlmey Thanks for the positive feedback.  I am super glad it is beneficial! And my apologies for introducing unnecessary complications.

> that would mean it is likely best to "abandon" this branch and then start working on something that doesn't overlap with this, e.g. README files or source code... 
> 
> Please let me know what you think and what is a way to move forward that is agreeable with you.

I am good with your suggestion ("abandon" this branch...move on to READMEs), but also entirely open to other suggestions.  So, unless you or someone else gives different guidance, I will get to work on the READMEs when I resume this effort, and I will create a new PR to share any edits to the READMEs.

**Comment by akohlmey** [comment]
> @akohlmey Thanks for the positive feedback. I am super glad it is beneficial!

yes. for me personally, this is the most effective way to implement these kind of things. I don't mind the editing, but the finding of the issues is what is hard and as somebody that is looking at these files all the time and has written a significant chunk of the programmer guide files, I tend to become blind to issues. So even without the edits, just pointing out where things are amiss, this is already very helpful. Having the suggested edits makes it even easier for somebody like me.
 
> > that would mean it is likely best to "abandon" this branch and then start working on something that doesn't overlap with this, e.g. README files or source code...
> > Please let me know what you think and what is a way to move forward that is agreeable with you.
> 
> I am good with your suggestion ("abandon" this branch...move on to READMEs), but also entirely open to other suggestions. 

great. then let's do this then. I have been thinking about this some more and will create a separate feature branch for documentation updates. That will make it easier for @sjplimp and others to review the changes.

**Pull request closed without merging**
