### PR TITLE
Msmeam t1m force error

### PR DESCRIPTION
**Pull request by athomps**
**Summary**

This fixes an error that was discovered in pair_style meam/ms.  Forces were incorrect for elements with non-zero t1m in the MS-MEAM library file.

**Related Issue(s)**

None

**Author(s)**

Aidan Thompson, Mike Baskes

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

The official MS-MEAM examples are not affected, because they have t1m=0. This will only affect previous simulations with non-zero t1m. 

**Implementation Notes**

Simple cut-n-paste from t3m term in force calculation. Also copied to KOKKOS package.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by athomps** [comment]
Apologies for the stale baseline. However, only two files actually changed.

**Comment by akohlmey** [comment]
> Apologies for the stale baseline. However, only two files actually changed.

I've cherry-picked commit 2ef030f33c23674d1df5ff096ba46c9507f32757 into PR #4090 and the excessive redundant history is gone.

This was caused by merging with "stable". This branch has diverged from "develop" and "release" because of backporting of bugfixes and making update releases for the stable branch. Thus you can either contribute to the "maintenance" (which has the development changes for "stable" branch) or "develop" (which has the development changes for "release").

It is probably a good idea at this point to do `git checkout develop` and then `git reset --hard upstream/develop` or `git branch -D develop` and then `git checkout develop` to reset the state of your develop branch.

**Comment by akohlmey** [comment]
@athomps please stop pushing changes to this branch. I have already cherry-picked all your changes and had done the port to KOKKOS (yours is not fully correct and will segfault).

Your second set of changes also changes the forces for the pair style meam/ms unit test and thus the corresponding data needs to be updated. PR #4090 has all these changes.

**Comment by athomps** [comment]
Okay, I will withdraw this PR and submit further updates to PR https://github.com/lammps/lammps/pull/4090

**Comment by athomps** [comment]
Switching to PR https://github.com/lammps/lammps/pull/4090

**Pull request closed without merging**
