### PR TITLE
unit tests for beck, morse, few LJ derivatives, few buck/coul and born/coul

### PR DESCRIPTION
**Pull request by abhiShandy**
**Summary**

Unit tests for the following pair-styles

- Beck
- Buck/coul/cut
- LJ/cut/coul/debye
- LJ/smooth
- LJ/smooth/linear
- Morse
- Born/coul/long
- Born/coul/long/cs
- Born/coul/msm
- Buck/coul/cut
- Buck/coul/long
- Buck/coul/msm
- LJ/cubic
- LJ/expand
- LJ/cut/coul/dsf
- LJ/cut/coul/wolf
- zbl

**Related Issues**

#2099 
includes #2268 

**Author(s)**

Abhishek Shandilya, RPI

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

- Curve fitting used for Beck and Morse
- LJ derivatives have same parameters as LJ/cut
- Parameters and settings for \*/coul/\* are copied from its parent style and LJ/coul/*
- Also includes bugfixes for pair styles buck/coul/cut/omp, lj/cubic, lj/expand, zbl

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by akohlmey** [comment]
@abhiShandy thanks again. Please note, this set of tests also exposed a bug in the USER-OMP package. If you don't enable the package, the test will pass, as tests for styles that are not available will be skipped. Even if you don't run the full tests yourself, you can check from the integration testing for the PR. To unit_tests test will always be successful, if the tests run. So to see if individual tests fail, you need to click on "Details", then on one of the three test sets (LAMMPS is compiled and tested with 3 different compilation settings) and see the overview of that test run. If one or more tests have failed, the will be a number next to the "Tests" menu item (between "Changes" and "Artifacts"). Clicking on "Tests" will show the screen output of the test run (the same as what you would see with `ctest -V`) and you can see which specific test failed. Check out: https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Fubuntu%2Funit_tests%2Fcmake_mpi_openmp_bigbig_shared/detail/cmake_mpi_openmp_bigbig_shared/552/tests

I have identified and fixed the bug in this case. Some more info, that may be helpful: When testing locally, you can take advantage of the ctest command line flags to narrow down which tests to run (example `ctest -R buck_coul_cut -V`) and pass the verbose flag to the tester program to see the LAMMPS internal output to better identify why some input is not completing and where it fails (example `TEST_ARGS=-v -R buck_coul_cut -V`). This latter feature can also be used to selectively update the reference data (example `TEST_ARGS=-v -R buck_coul_cut`).

**Comment by akohlmey** [comment]
The integration testing confirms the bug in pair style buck/coul/cut is now fixed.
https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Fubuntu%2Funit_tests%2Fcmake_mpi_openmp_smallbig
_shared/detail/cmake_mpi_openmp_smallbig_shared/553/tests

**Comment by abhiShandy** [comment]
Thanks for pointing it out. I should setup OpenMP on my Mac.

Thanks for fixing the bug too. Interestingly, I found the same line of code in several other (64 in total) pair-styles by `grep "fpair = (forcecoul + factor" */pair*cpp`. All of them may not be bugs, but matching lines in USER-OMP specifically concerns me. Why weren't they caught by the automated tests?

```bash
USER-OMP/pair_born_coul_long_omp.cpp:        fpair = (forcecoul + factor_lj*forceborn)*r2inv;
USER-OMP/pair_born_coul_msm_omp.cpp:        fpair = (forcecoul + factor_lj*forceborn)*r2inv;
USER-OMP/pair_born_coul_wolf_omp.cpp:        fpair = (forcecoul + factor_lj*forceborn)*r2inv;
USER-OMP/pair_buck_coul_long_omp.cpp:        fpair = (forcecoul + factor_lj*forcebuck)*r2inv;
USER-OMP/pair_buck_coul_msm_omp.cpp:        fpair = (forcecoul + factor_lj*forcebuck)*r2inv;
USER-OMP/pair_lj_cut_coul_dsf_omp.cpp:        fpair = (forcecoul + factor_lj*forcelj) * r2inv;
USER-OMP/pair_lj_cut_coul_wolf_omp.cpp:        fpair = (forcecoul + factor_lj*forcelj) * r2inv;
USER-OMP/pair_lj_cut_thole_long_omp.cpp:        fpair = (forcecoul + factor_lj*forcelj) * r2inv;
```

**Comment by akohlmey** [comment]
> Thanks for pointing it out. I should setup OpenMP on my Mac.
> 
> Thanks for fixing the bug too. Interestingly, I found the same line of code in several other (64 in total) pair-styles by `grep "fpair = (forcecoul + factor" */pair*cpp`. All of them may not be bugs, but matching lines in USER-OMP specifically concerns me. Why weren't they caught by the automated tests?
> 
> ```shell
> USER-OMP/pair_born_coul_long_omp.cpp:        fpair = (forcecoul + factor_lj*forceborn)*r2inv;
> USER-OMP/pair_born_coul_msm_omp.cpp:        fpair = (forcecoul + factor_lj*forceborn)*r2inv;
> USER-OMP/pair_born_coul_wolf_omp.cpp:        fpair = (forcecoul + factor_lj*forceborn)*r2inv;
> USER-OMP/pair_buck_coul_long_omp.cpp:        fpair = (forcecoul + factor_lj*forcebuck)*r2inv;
> USER-OMP/pair_buck_coul_msm_omp.cpp:        fpair = (forcecoul + factor_lj*forcebuck)*r2inv;
> USER-OMP/pair_lj_cut_coul_dsf_omp.cpp:        fpair = (forcecoul + factor_lj*forcelj) * r2inv;
> USER-OMP/pair_lj_cut_coul_wolf_omp.cpp:        fpair = (forcecoul + factor_lj*forcelj) * r2inv;
> USER-OMP/pair_lj_cut_thole_long_omp.cpp:        fpair = (forcecoul + factor_lj*forcelj) * r2inv;
> ```

those are all correct. those are all pair styles with long-range coulomb and there factor_coul needs to be applied to the *full* coulomb instead of the damped coulomb. Therefore forcecoul already includes it. With cutoff coulomb, you always compute the full coulomb. This is an example why it is a good idea to use the molecular template. This would not have shown with the atomic input template. Possibly during implementation only an atomic input deck was tested.

**Comment by akohlmey** [comment]
The progress in code coverage from added testing in this PR can be seen here: https://codecov.io/gh/lammps/lammps/pull/2267

**Comment by abhiShandy** [comment]
> The progress in code coverage from added testing in this PR can be seen here: https://codecov.io/gh/lammps/lammps/pull/2267

Yay! We have crossed the 25% mark

**Pull request merged**
