### PR TITLE
Adding ubuf union to Kokkos atom_vec styles

### PR DESCRIPTION
**Pull request by stanmoore1**
Adding ubuf union to Kokkos atom_vec styles

### CODE REVIEW

**Comment by stanmoore1** [comment]
Fixes #369

**Comment by stanmoore1** [comment]
This PR passes our internal regression testing. @akohlmey what is the "test-for-regression" label used for?

**Comment by akohlmey** [comment]
@stanmoore1 the test-for-regression label will trigger additional tests in jenkins that require to run a freshly compiled executable. the default tests for pull requests currently only test whether the code can be compiled. more thorough (and time consuming) tests will be run when merged into master. @rbberger can tell you more details and also whether this applies to kokkos enabled builds (i think not yet).

**Comment by rbberger** [comment]
@stanmoore1 right now it's not running any tests for kokkos enabled builds. It executes about 160 test cases (commands and slimmed down examples) and takes about 10 minutes to complete. This was put in place to ensure nothing breaks in core. I'm planning to add more labels for more tougher tests.

**Pull request merged**
