### PR TITLE
Chem snap

### LINKED ISSUE #2166: [BUG] Kokkos/SNAP gives out-of-bounds errors when running with two atoms without chem-snap
**Summary**

The recent chem snap PR appears to introduce a silent bug (i.e., it accidentally gives the right temperature, energies, pressure) for systems with two elements but without the proper modifications for chem snap. (Specific example: the system described by `/examples/snap/in.snap.WBe.PRB2019`). The bug can be diagnosed via compiling with `-DKOKKOS_ENABLE_DEBUG_BOUNDS_CHECK`, which throws errors when out-of-range accesses occur on multi-dimensional Views.

This does not occur with single-atom systems (for ex, `/examples/snap/in.snap.Mo_Chen`) or with two atom systems with chem snap properly configured (for ex, the recent `/examples/snap/in.snap.InP.JCPA2020`).

**LAMMPS Version and Platform**

Commit `77f6fecc868fbeb14a30a1d66a9d1af21aece5e6` (master branch at time of filing), corresponding to merging PR #1971. This issue does not occur in `patch_15Jun2020` as it predates the aforementioned PR.

Reproduced on Ubuntu 18.04.3 and 16.04.6, Kokkos CUDA backend. May not be confined to the CUDA backend only.

**Expected Behavior**

MD simulations with the SNAP potential should not have out-of-range memory accesses as it corresponds to potentially undefined behavior.

**Actual Behavior**

There are out-of-range memory accesses.

**Steps to Reproduce**

Configure LAMMPS with the SNAP and Kokkos packages. Build against the CUDA backend with the pre-processor define `-DKOKKOS_ENABLE_DEBUG_BOUNDS_CHECK`. (For `Makefile` builds, this corresponds to adding `-DKOKKOS_ENABLE_DEBUG_BOUNDS_CHECK` to the `CCFLAGS` and `LINKFLAGS` lines in `Makefile.kokkos_cuda_mpi`. [The latter may not be necessary, but better to be pedantic...].)

Run LAMMPS using the input file `/examples/snap/in.snap.WBe.PRB2019`, i.e., copy/statically link `lmp_kokkos_cuda_mpi` to the directory `/examples/snap/` and run, for ex:

`mpirun -np 1 ./lmp_kokkos_cuda_mpi -k on g 1 -sf kk -pk kokkos newton on neigh half -in in.snap.WBe.PRB2019`

The preprocessing info will print as normal, but then the output will quickly trigger `View bounds` errors, representative:

```
[...]
Setting up Verlet run ...
  Unit style    : metal
  Current step  : 0
  Time step     : 0.0005
:0: : block: [211,0,0], thread: [0,32,0] Assertion `View bounds error of view sna:ylist` failed.
:0: : block: [211,0,0], thread: [0,33,0] Assertion `View bounds error of view sna:ylist` failed.
:0: : block: [211,0,0], thread: [0,34,0] Assertion `View bounds error of view sna:ylist` failed.
:0: : block: [211,0,0], thread: [0,35,0] Assertion `View bounds error of view sna:ylist` failed.
:0: : block: [211,0,0], thread: [0,36,0] Assertion `View bounds error of view sna:ylist` failed.
[...]
```

A run without out-of-bounds errors would not trigger this. 

As noted above, this does not occur with single-atom systems or two atom systems with chem snap properly configured.

**Further Information, Files, and Links**

This has not been checked against other Kokkos backends (Serial, OpenMP). This has not been checked against the non-Kokkos SNAP implementation either, though in that case one would need a different method to check for memory access errors for flattened multi-dimensional arrays.

### PR DESCRIPTION
**Pull request by charlessievers**
**Summary**

Remove extra for loop when not utilizing chem snap.

**Related Issues**

Potentially fixes #2166 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Implementation Notes**

I have run in.snap.W, in.snap.WBe, and in.snap.InP using both KOKKOS openmp and cuda while Kokkos_ENABLE_DEBUG=on and report no error.

### CODE REVIEW

**Comment by charlessievers** [comment]
@weinbe2 Here is the potential fix.

**Comment by weinbe2** [comment]
FYI, I just tested the `cmake` flags related to debug checking and it appears for the cmake build system you also need to specify `-DKokkos_ENABLE_DEBUG_BOUNDS_CHECK=yes` explicitly, not just `-DKokkos_ENABLE_DEBUG`. (It also made a huge difference in the compile time, so it's having some effect.)

This sort of surprised me, but when I dug into `CMakeLists.txt` it seemed to make sense. (On the other hand, when I stared at `Makefile.kokkos` it looked like `ENABLE_DEBUG` implied `ENABLE_DEBUG_BOUNDS_CHECK`... so someone should ultimately double check me.)

Testing your fix momentarily @charlessievers . One question I have which you may have a quick answer for---is this the only place where you would need to add an `if (chemflag)` before a loop over `nelements`? Or is there a chance/risk of needing this elsewhere?

**Comment by charlessievers** [comment]
> Testing your fix momentarily @charlessievers . One question I have which you may have a quick answer for---is this the only place where you would need to add an `if (chemflag)` before a loop over `nelements`? Or is there a chance/risk of needing this elsewhere?

Great question @weinbe2, that is the only for loop over nelements that I added to pair_snap_kokkos_impl.h. I added nelements to sna_kokkos_impl.h and set nelements to 1 if (!chemflag). This should be an isolated issue.

**Comment by weinbe2** [comment]
> > Testing your fix momentarily @charlessievers . One question I have which you may have a quick answer for---is this the only place where you would need to add an `if (chemflag)` before a loop over `nelements`? Or is there a chance/risk of needing this elsewhere?
> 
> Great question @weinbe2, that is the only for loop over nelements that I added to pair_snap_kokkos_impl.h. I added nelements to sna_kokkos_impl.h and set nelements to 1 if (!chemflag). This should be an isolated issue.

That makes perfect sense, thank you for explaining.

**Pull request merged**
