### PR TITLE
Add ghost option to npair_halffull

### PR DESCRIPTION
**Pull request by stanmoore1**
## Purpose
Add `ghost` option to `half from full` neighbor list capability.

## Author(s)
Stan Moore

## Backward Compatibility
No issues.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@akohlmey I'm finished with this PR, can you take a look?

**Comment by akohlmey** [comment]
@stanmoore1 what exactly do you want me to check out?
doing the neighbor list thing is far in "steve-country" and i am always scared a lot, when i have to mess with it.

**Comment by stanmoore1** [comment]
@akohlmey fair enough, I'll just assign to @sjplimp then. Thanks.

**Comment by akohlmey** [comment]
@stanmoore1 i'm adding the labels that should trigger the extended tests in our jenkins server. it is not likely that any of those may trigger this case, but you never know...

**Comment by stanmoore1** [comment]
@akohlmey yeah, I needed it for Kokkos ReaxFF, and Steve wanted me to add it to CPU as well.

**Pull request merged**
