### PR TITLE
Change defaults for KOKKOS package

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

- Change default neighbor binsize for KOKKOS package to use 2x the LAMMPS defaut when running on GPUs. This should improve performance in many cases if a user forgets to set this value.
- Change defaults when running on CPUs vs GPUs. For CPUs, use half neighbor list, newton on, non-threaded packing of comm buffers. For GPUs, use full neighbor list, newton off, threaded packing of comm buffers.

**Author(s)**

Stan Moore (Sandia)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Defaults changed.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@akohlmey "backend" is a proper English word. Please don't ask me to change it to "back-end" because is this not correct English.

**Comment by akohlmey** [comment]
> @akohlmey "backend" is a proper English word. Please don't ask me to change it to "back-end" because this is not correct English.

as a non-native speaker with english classes being my english is only as good as that of the spellchecker, if at all.
if that one fails, please educate it (and me) by adding words it considers misspelled, but that you know to be correct to "doc/utils/sphinx-config/false_positives.txt". then "make spellcheck" in doc will stop complaining and i will not be tempted to silence it.

if you see incorrectly spelled words in one place of the manual, it is usually worth grepping through the entire manual and looking for other occurrences. that is what i usually do, so it is likely that errors, which the spellchecker accepts, have been propagated the same way.

**Comment by stanmoore1** [comment]
@akohlmey I suppose hyphenation is really more of a style than "proper" vs "improper" and it has changed over time, for example, see https://www.quora.com/What-are-the-differences-and-when-should-I-use-back-end-back-end-and-backend. Using more hyphens avoids false positives of the spell checker.

**Comment by stanmoore1** [comment]
I changed this to be consistent with other places in the docs.

**Comment by akohlmey** [comment]
@stanmoore1 what do you think about having the KOKKOS devices default auto-detected when using the CMake configuration tool? it can test for availability of OpenMP, Pthreads, MPI, and CUDA, so the default could be chosen according to what is available and likely desired.

**Pull request merged**
