### PR TITLE
Implementation of Widom insertions through a new fix widom command

### PR DESCRIPTION
**Pull request by evoyiatzis**
**Summary**

Based on fix gcmc, a fix that performs widom insertions has been implemented

**Related Issues**

Related to my feature request #1754 

**Author(s)**

Evangelos Voyiatzis, Royal DSM (evoyiatzis@gmail.com)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No backward compatibility issues

**Implementation Notes**

The implementation has been based on the fix_gcmc.cpp & fix_gcmc.h code. The validity has been tested by reproducing reported values from the literature (see figure 4 from https://arxiv.org/pdf/1802.08045.pdf as an example)

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [X] Licensing information is complete
- [X] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [X] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [X] One or more example input decks are included

**Further Information, Files, and Links**

The test system is a Lennard-Jones 3d system with a single types of particles at a number density of 0.6. It is reported in the following paper https://arxiv.org/pdf/1802.08045.pdf at the "Lennard-Jones fluid and comparison with the Widom method" section.

[in.test.widom.txt](https://github.com/lammps/lammps/files/4918530/in.test.widom.txt)
[after_production.data.txt](https://github.com/lammps/lammps/files/4918534/after_production.data.txt)

### CODE REVIEW

**Comment by akohlmey** [comment]
@athomps since this is derived from fix gcmc and thus somewhat similar and something we could provide (some) support for, would it be justified to have this added to the MC package instead of USER-MISC?

**Comment by athomps** [comment]
This is a feature that will be useful to quite a broad range of LAMMPS users.   I support promoting it to the MC package.  If @evoyiatzis is motivated to provide a simple test example e.g. based on in.test.widom.txt above, I can help with documentation and minor code changes.

**Comment by akohlmey** [comment]
@athomps and @evoyiatzis FYI I updated the branch to the current master, completed the integration into the manual, fixed a few issues in the doc file and moved the sources to the MC package. I will a review/update of coding style and output formatting together with a possible similar refactoring in fix gcmc after everything else is deemed OK.

**Comment by evoyiatzis** [comment]
thanks for your time and effort @akohlmey  and @athomps . I have examples with water and a two component Lennard-Jones system. I will try to dig them up.

**Comment by evoyiatzis** [comment]
I am not sure in which directory I should add additional example files so bare with me while sharing them as attached files in the comments section. The following three files computes the chemical potential in a two Lennard-Jones system as reported in https://doi.org/10.1140/epjst/e2016-60094-x. The LJ parameters have been reported in https://doi.org/10.1103/PhysRevE.51.4626

[data.2lj_system.txt](https://github.com/lammps/lammps/files/4936522/data.2lj_system.txt)
[in.2lj.insertion.txt](https://github.com/lammps/lammps/files/4936523/in.2lj.insertion.txt)
[log.lammps.txt](https://github.com/lammps/lammps/files/4936527/log.lammps.txt)

**Comment by evoyiatzis** [comment]
The following three files computes the chemical potential in liquid water (using the flexible SPC/E model) as reported in https://arxiv.org/pdf/1802.08045.pdf in the "SPC/E Water" paragraph

[in.SPC-E_flexible.txt](https://github.com/lammps/lammps/files/4936763/in.SPC-E_flexible.txt)
[data.SPC-E_flexible.txt](https://github.com/lammps/lammps/files/4936764/data.SPC-E_flexible.txt)
[H2O.txt](https://github.com/lammps/lammps/files/4936768/H2O.txt)

**Comment by athomps** [comment]
I think these files should go in examples/gcmc.  If possible, it would be good make the LJ and H2O force field definitions (and H2O.txt) consistent with existing gcmc examples.  Same thing for filename conventions.  If it makes sense, we can also modify the gcmc examples and create new standard log files.

**Comment by akohlmey** [comment]
examples have been added, updated and renamed as needed. in the water example, i swapped the atom types to be consistent with the gcmc version, but left it flexible. if there are no further objection, this can be merged for the next patch.

**Comment by athomps** [comment]
Agreed

**Pull request merged**
