### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by e-kwsm**
**Summary**

Fix typo.

**Related Issues**

None.

**Author(s)**

No need to credit me.

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Backward compatible.

**Implementation Notes**

Nothing.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete

**Further Information, Files, and Links**

Nothing.

### CODE REVIEW

**Comment by akohlmey** [comment]
Thanks for your submission. Some of the changes, you better also submit to the corresponding upstream projects (Kokkos, Colvars, Plumed, etc.) or else they will re-emerge with the next update.
I also noticed that you are correcting a mistyped `which` to `witch` and are using in some cases british spelling (e.g. behaviour) while we try to stick to american spelling (i.e. behavior, neighbor, etc., "...ize" instead of "...ise" and so on).

**Comment by akohlmey** [comment]
@e-kwsm I fixed a few issues that were still present or where the changes were not consistent with the remainder of the text. Thanks again for taking the time and effort to do such a task.

**Comment by e-kwsm** [comment]
@akohlmey  Thank you. I opened PRs on upstreams:
* Colvars/colvars#333
* kokkos/kokkos#2883
* plumed/plumed2#560

The site of POEMS https://github.com/lammps/lammps/blob/3d66167f640520b31603325c0d6584551935db1a/lib/poems/README#L20 does not exist.

Should changes on third parties reverted?


Also, there are British English spelling, including function names, e.g., https://github.com/lammps/lammps/blob/3d66167f640520b31603325c0d6584551935db1a/src/USER-PTM/ptm_normalize_vertices.cpp#L14
They are not changed.

**Comment by akohlmey** [comment]
@e-kwsm thanks. This will do. Yes, poems is essentially abandoned.

**Pull request merged**
