### PR TITLE
create pair_species_coeff command

### PR DESCRIPTION
**Pull request by ellio167**
**Summary**

New command **pair_species_coeff** which reads species pairs with coefficients from a named parameter file and generates the corresponding **pair_coeff** commands from a mapping of LAMMPS atom types to species strings.

This provides an 'atom-type' agnostic way to specify pair coefficients in terms of (arbitrary) species strings.  This is designed to be useful for the creation of flexible **KIM Simulator Models**, but it is believed that the functionality is more broadly useful to the LAMMPS community.

**Author(s)**

Ronald Miller (Carleton U) <ronmiller@mae.carleton.ca>
Ryan S. Elliott (U. Minnesota) <relliott@umn.edu>

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

no breaking changes

**Implementation Notes**

Command arguments: param-file-name typeargs

Use contents of param-file-name typeargs to generate pair_coeff command strings and use `input->one()` to execute.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

No docs created yet, as I anticipate command name and/or argument changes being made based on feedback from @akohlmey or others.

### CODE REVIEW

**Comment by ellio167** [comment]
@akohlmey Is this something that makes sense to add to lammps at the "global" command level?  We need something along these lines for KIM SM support.  So, if it's not appropriate at the "global" command level, I will plan to submit (soon) a PR that will provide similar functionality that will be self-contained within the `kim_interactions` command.  Thanks!

**Comment by akohlmey** [comment]
> @akohlmey Is this something that makes sense to add to lammps at the "global" command level? We need something along these lines for KIM SM support. So, if it's not appropriate at the "global" command level, I will plan to submit (soon) a PR that will provide similar functionality that will be self-contained within the `kim_interactions` command. Thanks!

@ellio167 the biggest problem is that this is for atom types only.
I have been pondering different way of how to make symbolic types (atom/bond/angle/dihedral/improper) work, but there is always some inherent complexity and ugliness about it, that i have this far abandoned every attempt. 
given out currently rather ambitious TODO list for the next months, i don't think that i can revisit this any time soon. the best point to get started would be to do some brainstorming with @sjplimp and see what kind of approach would be doable and also attractive for other uses. i will send you a suggestion about this per personal e-mail.

**Comment by ellio167** [comment]
Sounds good.  Thanks!!!

**Comment by akohlmey** [comment]
if we implement some feature like this in LAMMPS, it will be done differently and in a more general way. so there is no point in keeping the PR open. Instead it would be better to submit a feature request issue, where a discussion on the topic can be had, and specifically requirements, design goals and constraints can be defined and discussed. thus closing this one now.

**Pull request closed without merging**
