### PR TITLE
MLIAP package

### PR DESCRIPTION
**Pull request by athomps**
**Summary**

A new package has been add that provides a general interface for machine-learning interatomic potentials.

**Related Issues**

None

**Author(s)**

Aidan Thompson, Sandia National Laboratories

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

New

**Implementation Notes**

This package is currently very SNAP-centric, but the implementation is much more general than SNAP.  It defines base MLIAPModel and MLIAPDescriptor classes, from which specific derived classes are derived, allowing the addition of many different energy models and descriptor styles. It currently reproduces all the SNAP potentials distributed with LAMMPS, and several examples are provided.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by athomps** [comment]
compute_mliap.cpp/h should not be included in this PR. They are prototypes for fitting potentials.

**Comment by akohlmey** [comment]
@athomps looking at this PR right now. I am adding CMake integration and am looking through some details. Will also update to the latest master.
Some questions/suggestions:
There seems to be a hard dependency on the SNAP package. Is that desired? If yes, it should be mentioned in the documentation. If not, we have to figure out a way to make it a soft dependency (could be a bit messy). It is easy to have this in CMake, but I don't think there is a clean way to do this in the conventional makefiles (e.g. USER-ATC depends on MANYBODY but i don't see that being required and thus will only fail at link time).
The `compute mliap` files are also causing issues. Wouldn't it be better to move them to a folder like `tools/mliap` and add a little README with some instructions how those are to be used?

**Comment by athomps** [comment]
@akohlmey compute_mliap.cpp/h should not be included in this PR. They are prototypes for fitting potentials. I could not figure out how to remove them after I submitted the PR.

**Comment by akohlmey** [comment]
> @akohlmey compute_mliap.cpp/h should not be included in this PR. They are prototypes for fitting potentials. I could not figure out how to remove them after I submitted the PR.

Try:
```
git rm src/MLIAP/compute_mliap.*
git commit
git push
```

**Comment by athomps** [comment]
The dependency on SNAP package is mentioned on the doc page.  There might be a way to eliminate it, and put the SNAP-specific classes in the SNAP package. It comes down to one line in pair_mliap.cpp:
        descriptor = new MLIAPDescriptorSNAP(lmp,arg[iarg+2]);
Is there a way to get around that?

**Comment by akohlmey** [comment]
> The dependency on SNAP package is mentioned on the doc page. There might be a way to eliminate it, and put the SNAP-specific classes in the SNAP package. It comes down to one line in pair_mliap.cpp:
> descriptor = new MLIAPDescriptorSNAP(lmp,arg[iarg+2]);
> Is there a way to get around that?

there would still be a "soft" dependency, i.e. one would still have to skip the compilation of the object files that require both packages enabled. and that is regardless of where you place the sources. Having a "hard" dependency is far less effort to implement.

**Comment by athomps** [comment]
> there would still be a "soft" dependency, i.e. one would still have to skip the compilation of the object files that require both packages enabled. and that is regardless of where you place the sources. Having a "hard" dependency is far less effort to implement.

What about using the input keyword "sna" to look up in the available Descriptor styles, like what is done for pair_styles, etc.?  If it is not found, exit with an error.

**Comment by akohlmey** [comment]
> > there would still be a "soft" dependency, i.e. one would still have to skip the compilation of the object files that require both packages enabled. and that is regardless of where you place the sources. Having a "hard" dependency is far less effort to implement.
> 
> What about using the input keyword "sna" to look up in the available Descriptor styles, like what is done for pair_styles, etc.? If it is not found, exit with an error.

same difference, that only would be a different mechanism to include a reference to that class. For a single class/package that is easier done by making the SNAP package set a define (LMP_SNAP) and just ifdef the lines. you still need to skip the compilation unless you want to wrap the entire snap related files in the MLIAP package also into ifdefs (and then work around compilers/linkers that don't like empty objects).

**Comment by akohlmey** [comment]
@athomps i can implement either way of the dependency. Just let me know which you prefer and then i'll make it work.

**Comment by athomps** [comment]
So what is the easiest way for conventional Makefile this? Right now, if SNAP package is not present, pair_mliap.cpp fails to compile.  That works for me :-).

**Comment by akohlmey** [comment]
> So what is the easiest way for conventional Makefile this? Right now, if SNAP package is not present, pair_mliap.cpp fails to compile. That works for me :-).

yes, that is what I call a "hard" dependency. We have the same for USER-ATC and MANYBODY. In CMake we can detect this and error out during the configuration step. That is why this is so much less effort than a "soft" dependency.

**Comment by akohlmey** [comment]
@athomps before making any additional changes, please first pull my changes from github. thanks.

**Comment by akohlmey** [comment]
@athomps FYI, I am chasing down some issue that causes a segmentation fault with restarts under certain circumstances that were exposed when creating a pair style test tool input.

**Comment by akohlmey** [comment]
@athomp testing now passes using reference data from the corresponding SNAP tests. As far as I can tell, this is now formally ready for merging. I had to fix a few small issues in other parts of LAMMPS to make it run smoothly, but that is it.

**Comment by athomps** [comment]
Thanks Axel!  Everything looks good to me.  Eventually, I think it should be possible for MLIAP and SNAP to share the same model/coeff and descriptor/param files, but I wanted to let things settle a bit before making the change in SNAP.

**Pull request merged**
