### PR TITLE
Update Kokkos library in LAMMPS to v3.6.0

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Update Kokkos library in LAMMPS to v3.6.0

**Related Issue(s)**

None

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
All Kokkos regression tests passed, just need to check performance.

**Comment by stanmoore1** [comment]
Performance on V100 looks good, need to check AMD GPU

**Review by sjplimp — APPROVED** [review]

**Comment by stanmoore1** [comment]
For Kokkos HIP, need to use:
`-DKokkos_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS=ON` (CMake)
`-DKOKKOS_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS` (Makefile)

at least for now, otherwise there is a potential performance regression, ref. https://github.com/kokkos/kokkos/pull/4644.

**Comment by stanmoore1** [comment]
@akohlmey is there some place we need to set `-DKokkos_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS=ON` for CMake with the Kokkos HIP backend, or just put the burden on the user?

**Comment by akohlmey** [comment]
> @akohlmey is there some place we need to set `-DKokkos_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS=ON` for CMake with the Kokkos HIP backend, or just put the burden on the user?

If you want to enforce this globally, it would need to go into cmake/Modules/Packages/KOKKOS.cmake, otherwise there would need to be a cmake/presets/kokkos-hip.cmake preset file similar to the kokkos-sycl.cmake or kokkos-cuda.cmake files.

**Comment by stanmoore1** [comment]
@akohlmey I added a preliminary `kokkos-hip.cmake`, can you double check? This is the CMake line I am using, but I don't think we want all the MPI lib hardcoded:

```
CXX=hipcc cmake ../cmake/ -D BUILD_MPI=yes -D CMAKE_BUILD_TYPE=Release -D PKG_KOKKOS=ON -D Kokkos_ENABLE_HIP=ON -D Kokkos_ARCH_VEGA90A=ON -D Kokkos_ARCH_ZEN3=ON -D CMAKE_CXX_FLAGS="-I/${MPICH_DIR}/include -munsafe-fp-atomics -DKOKKOS_ENABLE_HIP_MULTIPLE_KERNEL_INSTANTIATIONS" -D MPI_CXX_INCLUDE_DIRS=${MPICH_DIR}/include -D MPI_CXX_LIBRARIES="-L${MPICH_DIR}/lib -lmpi -L${CRAY_MPICH_ROOTDIR}/gtl/lib -lmpi_gtl_hsa"
```

**Comment by akohlmey** [comment]
> 

@stanmoore1 You are in a much better position to check and debug this than myself. With the preset file it should be possible to build a usable LAMMPS executable with something like:

```
cmake -S cmake -B build-hip -C cmake/presets/kokkos_hip.cmake -C cmake/presets/basic.cmake
cmake --build build-hip
```

Perhaps you would add the Cray specific flags as a comment. Those preset files have a similar function to the machine makefiles for the GNU build procedure.

**Comment by stanmoore1** [comment]
I tested the `kokkos-hip.cmake` preset on OLCF Crusher and it works when not using MPI. I put a comment about MPI when using Cray MPICH as well.

**Comment by stanmoore1** [comment]
@akohlmey using `hipFFT` with CMake doesn't seem to work: the default is always set to KISS, so hipFFT never gets enabled.

**Comment by stanmoore1** [comment]
KISS is set here by default: https://github.com/lammps/lammps/blob/develop/cmake/Modules/Packages/KSPACE.cmake#L11
Then CMake checks if `NOT KISS` here, which is never true: https://github.com/lammps/lammps/blob/develop/cmake/Modules/Packages/KOKKOS.cmake#L134

**Comment by stanmoore1** [comment]
And there is no option to set FFT = CUFFT or HIPFFT through CMake:
`set(FFT_VALUES KISS FFTW3 MKL)`

**Comment by stanmoore1** [comment]
Here is the output from CMake, you can see that HIP is enabled and it should choose `hipFFT` automatically but it picks `KISS` FFT instead.
```
$ cmake -D BUILD_MPI=no -S cmake -B build-hip -C cmake/presets/kokkos-hip.cmake -C cmake/presets/basic.cmake
loading initial cache file cmake/presets/kokkos-hip.cmake
loading initial cache file cmake/presets/basic.cmake
-- The CXX compiler identification is Clang 14.0.0
-- Check for working CXX compiler: /opt/rocm-5.1.0/hip/bin/hipcc
-- Check for working CXX compiler: /opt/rocm-5.1.0/hip/bin/hipcc - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Running check for auto-generated files from make-based build system
-- Looking for C++ include omp.h
-- Looking for C++ include omp.h - found
-- Found OpenMP_CXX: -fopenmp=libomp  
-- Found OpenMP: TRUE   
-- Found GZIP: /usr/bin/gzip  
-- Could NOT find FFMPEG (missing: FFMPEG_EXECUTABLE) 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'fftw3'
--   No package 'fftw3' found
-- Looking for C++ include cmath
-- Looking for C++ include cmath - found
-- Setting default Kokkos CXX standard to 14
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- The project name is: Kokkos
-- Compiler Version: 5.1.20531
-- Using -std=c++14 for C++14 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Experimental::HIP
--     Host Parallel: Kokkos::OpenMP
--       Host Serial: SERIAL
-- 
-- Architectures:
--  VEGA90A
-- Found TPLLIBDL: /usr/lib64/libdl.so  
-- Kokkos Devices: OPENMP;SERIAL;HIP, Kokkos Backends: OPENMP;SERIAL;HIP
-- Generating style headers...
-- Generating package headers...
-- Generating lmpinstalledpkgs.h...
-- Could NOT find ClangFormat: Found unsuitable version "0.0", but required is at least "8.0" (found /opt/cray/pe/cce/13.0.0/cce-clang/x86_64/bin/clang-format)
-- The following tools and libraries have been found and configured:
 * Git
 * OpenMP
 * PkgConfig
 * TPLLIBDL

-- <<< Build configuration >>>
   LAMMPS Version:   20220504
   Operating System: Linux SLES 15.3
   Build type:       RelWithDebInfo
   Install path:     /ccs/home/stamoor/.local
   Generator:        Unix Makefiles using /usr/bin/gmake
-- Enabled packages: KOKKOS;KSPACE;MANYBODY;MOLECULE;RIGID
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /opt/rocm-5.1.0/hip/bin/hipcc
      Type:          Clang
      Version:       14.0.0
      C++ Flags:     -O2 -g -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=4;LAMMPS_GZIP;FFT_KISS;$<BUILD_INTERFACE:LMP_KOKKOS>
      Options:       -munsafe-fp-atomics
-- <<< Linker flags: >>>
-- Executable name:  lmp
-- Static library flags:    
-- Kokkos Arch: 
-- <<< FFT settings >>>
-- Primary FFT lib:  KISS
-- Using double precision FFTs
-- Using non-threaded FFTs
-- Kokkos FFT: KISS
-- Configuring done
-- Generating done
-- Build files have been written to: /lammps/build-hip
```

**Comment by akohlmey** [comment]
@stanmoore1 the logic is the following: If you select KISS as FFT library, it applies to both, KOKKOS and non-KOKKOS. When you select (or LAMMPS auto-detects) any other FFT library **and** you have CUDA or HIP enabled with KOKKOS then cuFFT or hipFFT are used, respectively.

**Comment by stanmoore1** [comment]
> @stanmoore1 the logic is the following: If you select KISS as FFT library, it applies to both, KOKKOS and non-KOKKOS. When you select (or LAMMPS auto-detects) any other FFT library **and** you have CUDA or HIP enabled with KOKKOS then cuFFT or hipFFT are used, respectively.

@akohlmey I think this is bad logic. In this case you have to select FFTW3 or MKL or get hipFFT, which means you have to have the TPLs for FFTW3 or MKL available too.

**Pull request merged**
