### PR TITLE
Collected small changes and fixes

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request contains multiple small changes and fixes

**Related Issue(s)**

N/A

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

The following individual changes are included.
- simplify the preset for the IntelLLVM compiler. Use local linalg since local BLAS/LAPACK may not be ABI compatible.
- use `-fp-model precise` with IntelLLVM compilers.
- use std::vector<>.data() consistently in the ELECTRODE package and fix sgcmc to access the underlying pointer
- Skip tests with KokkosOpenMP when GPU support is included (e.g. CUDA, HIP, or SYCL) since KOKKOS enforces use of GPUs in that case, so we cannot test with OpenMP only as desired.
- relax some force-style test epsilon values for compatibility with IntelLLVM compilers
- must use fabs() instead of abs() when operating on floating point numbers in fix qeq/ctip
- reformat files with clang-format
- fix bug when building Kokkos atom map on the host (i.e. `-pk kokkos atom/map no`) using a "hash" style map. The shallow copy of `Kokkos::UnorderedMap` is not working as expected, need to use an alias instead
- consolidate kspace communication enumerators in kspace.h header
- remove unused code in PPPM/MSM styles of the DIELECTRIC package
- allow Sphinx 8.x for building the documentation
- replace globbed toctrees for pair, bond, angle, dihedral, improper, computes, and fixes with python script generated files so that duplicate entries are avoided (and Sphinx won't complain about them or pick the wrong one as the canonical one)

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Review by robeme — APPROVED** [review]
As far as ELECTRODE is concerned, everything is fine. However, @ludwig-ahrens and I noticed that some efield unit tests did not complete. We traced this back to the missing prerequisite `atom dipole` in the yamls `fix-timestep-efield_dipole_const.yaml` and `fix-timestep-efield_dipole_variable.yaml`. Would it be a good idea to add this prerequisite in both yamls?

**Comment by akohlmey** [comment]
> We traced this back to the missing prerequisite `atom dipole` in the yamls `fix-timestep-efield_dipole_const.yaml` and `fix-timestep-efield_dipole_variable.yaml`. Would it be a good idea to add this prerequisite in both yamls?

@robeme Thanks for the note. These tests were added only recently by @alphataubio.
Yes, the dependency needs to be added. This is done in commit e6c9353ccf028b9a9ad928bc8bc8709075af59b4

**Comment by akohlmey** [comment]
@ndtrung81 please have a look at the changes I made to the dielectric package.

**Comment by ndtrung81** [comment]
@akohlmey sorry for the bug in `msm_dielectric.cpp`. Thanks for fixing it! Also for cleaning up `pppm*/dielectric` and `pppm/gpu`.

**Comment by akohlmey** [comment]
@lammps/core this is waiting now for almost a week for a review...

**Review by ndtrung81 — APPROVED** [review]

**Pull request merged**
