### PR TITLE
Fix wall asphere 

### PR DESCRIPTION
**Pull request by aershadinia**

### CODE REVIEW

**Comment by akohlmey** [comment]
This pull request contains code full of errors that does not compile. There are also conceptual problems (e.g. all particles are assumed to be aspherical). This is completely unacceptable.

**Comment by aershadinia** [comment]
I is quite surprising for me that the code does not compile well since I have double checked the code several times. Would you please share the errors with me?
All the particles interacting with the wall have to be aspherical. Why do you deem it as a conceptual problem?

**Comment by akohlmey** [comment]
Pull requests are automatically checked through integration testing on ci.lammps.org
Just check the webpage for your pull request and you'll see a red 'x' next to commits that have failed the compilation test and a green checkmark next to commits that have been tested successfull.

The conceptual problem is that you *assume* this, but you do not check if this is the case. If somebody tries to run a mixed system or uses the wrong atom style, you'll get a nasty segmentation fault.

**Comment by aershadinia** [comment]
I understand why there were compile errors it was because I mistakenly uploaded an old file of mine. I will update the code.

I got your point about the conceptual problem. I will add some lines to my file to check whether particles interacting with the wall are aspherical or not. 

Thank you

**Comment by akohlmey** [comment]
As mentioned before, pull requests are automatically checked whether they can be merged with the current head revision and whether the code compiles. The status is reported on the webpage for the request. LAMMPS developers get automatic notification of the failure, thus it is in your own interest to make certain *before* submitting the request, that the code in your git repo works. Every failure will reduce the trust in your work.

**Pull request closed without merging**
