### PR TITLE
Fixed bugs with kernel (re)compiling when the global device got clear and reinitialized

### LINKED ISSUE #1748: Regression: Failing testcase with latest GPU package code
**Summary**

PR #1735 introduces a regression when running some examples with GPU support.

https://ci.lammps.org/job/lammps/job/master/job/cmake/job/cmake-testing-gpu-opencl/195/testReport/tests.test_examples/HugoniostatTestCase/test_hugoniostat_gpu/

**LAMMPS Version and Platform**

current master

**Details**

Running the `examples/hugoniostat/in.hugoniostat` example with `-pk gpu 1 -sf gpu` leads to an OpenCL error -38 `CL_INVALID_MEM_OBJECT` after the second `run` command.

```
Thread 1 "lmp" hit Breakpoint 1, ucl_opencl::UCL_Kernel::add_arg<int> (arg=0x555555c47ff0 <LAMMPS_AL::global_device+880>, 
    this=0x555555c483b0 <LAMMPS_AL::global_device+1840>) at /home/richard/GitHub/lammps/lammps/lib/gpu/geryon/ocl_kernel.h:232
232	  inline void add_arg(const UCL_D_Vec<numtyp> * const arg)
(gdb) continue
Continuing.
OpenCL error in file '/home/richard/GitHub/lammps/lammps/lib/gpu/geryon/ocl_kernel.h' in line 219 : -38.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

```

This is caused by

```
580	  _shared->k_build_nbor.run(&atom.x, &atom.dev_particle_id,
581	                            &cell_counts, &dev_nbor, &nbor_host,
582	                            &dev_numj_host, &_max_nbors, &cutoff_cast, &ncellx,
583	                            &ncelly, &ncellz, &inum, &nt, &nall,
584	                            &_threads_per_atom, &_cells_in_cutoff);
```
argument number 2, `atom.dev_particle_id`. The commit that causes this is dfbee325757688d1fe774b94720873f454327113. Seems like something isn't properly initialized.

**Full Stack trace:**
```
#0  ucl_opencl::UCL_Kernel::add_arg<int> (arg=0x555555c47ff0 <LAMMPS_AL::global_device+880>, this=0x555555c483b0 <LAMMPS_AL::global_device+1840>)
    at /home/richard/GitHub/lammps/lammps/lib/gpu/geryon/ocl_kernel.h:232
#1  ucl_opencl::UCL_Kernel::run<ucl_opencl::UCL_Vector<float, float>, ucl_opencl::UCL_D_Vec<int>, ucl_opencl::UCL_Vector<int, int>, ucl_opencl::UCL_D_Vec<int>, ucl_opencl::UCL_Vector<int, int>, ucl_opencl::UCL_D_Vec<int>, int, float const, int, int, int, int const, int const, int const, int, int> (
    a16=0x555555c6b304, a15=0x555555c6b2fc, a14=0x7fffffffd608, a13=0x7fffffffd618, a12=0x7fffffffd60c, a11=0x7fffffffd624, a10=0x7fffffffd620, 
    a9=0x7fffffffd61c, a8=0x7fffffffd62c, a7=<optimized out>, a6=0x555555c6af20, a5=0x555555c6ae58, a4=0x555555c6ad00, a3=0x555555c6b0c0, 
    a2=0x555555c47ff0 <LAMMPS_AL::global_device+880>, a1=0x555555c47c88 <LAMMPS_AL::global_device+8>, this=0x555555c483b0 <LAMMPS_AL::global_device+1840>)
    at /home/richard/GitHub/lammps/lammps/lib/gpu/geryon/ucl_arg_kludge.h:556
#2  LAMMPS_AL::Neighbor::build_nbor_list<float, double> (this=<optimized out>, x=0x555559450ce0, inum=<optimized out>, host_inum=0, nall=<optimized out>, 
    atom=..., sublo=0x555557a2b510, subhi=0x555557a2b528, tag=0x5555593b0c90, nspecial=0x0, special=0x0, success=@0x7fffffffd963: true, 
    mn=@0x7fffffffd820: 96) at /home/richard/GitHub/lammps/lammps/lib/gpu/lal_neighbor.cpp:580
#3  0x00005555559fc59b in LAMMPS_AL::BaseAtomic<float, double>::build_nbor_list (success=@0x7fffffffd963: true, special=0x0, nspecial=0x0, 
    tag=0x5555593b0c90, subhi=0x555557a2b528, sublo=0x555557a2b510, host_type=0x5555593c0ca0, host_x=0x555559450ce0, nall=2724, host_inum=0, inum=1000, 
    this=0x555555c49860 <LJCubicLMF>) at /home/richard/GitHub/lammps/lammps/lib/gpu/geryon/ocl_timer.h:80
#4  LAMMPS_AL::BaseAtomic<float, double>::build_nbor_list (success=@0x7fffffffd963: true, special=0x0, nspecial=0x0, tag=0x5555593b0c90, 
    subhi=0x555557a2b528, sublo=0x555557a2b510, host_type=0x5555593c0ca0, host_x=0x555559450ce0, nall=2724, host_inum=0, inum=1000, 
    this=0x555555c49860 <LJCubicLMF>) at /home/richard/GitHub/lammps/lammps/lib/gpu/lal_base_atomic.cpp:150
#5  LAMMPS_AL::BaseAtomic<float, double>::compute (this=0x555555c49860 <LJCubicLMF>, ago=<optimized out>, inum_full=<optimized out>, nall=2724, 
    host_x=0x555559450ce0, host_type=0x5555593c0ca0, sublo=0x555557a2b510, subhi=0x555557a2b528, tag=0x5555593b0c90, nspecial=0x0, special=0x0, eflag=true, 
    vflag=true, eatom=false, vatom=false, host_start=@0x7fffffffd964: 1000, ilist=0x7fffffffd968, jnum=0x7fffffffd970, cpu_time=0, 
    success=@0x7fffffffd963: true) at /home/richard/GitHub/lammps/lammps/lib/gpu/lal_base_atomic.cpp:241
#6  0x00005555559c8bf8 in ljcb_gpu_compute_n (ago=<optimized out>, inum_full=inum_full@entry=1000, nall=<optimized out>, host_x=<optimized out>, 
    host_type=<optimized out>, sublo=sublo@entry=0x555557a2b510, subhi=0x555557a2b528, tag=0x5555593b0c90, nspecial=0x0, special=0x0, eflag=true, 
    vflag=true, eatom=false, vatom=false, host_start=@0x7fffffffd964: 1000, ilist=0x7fffffffd968, jnum=0x7fffffffd970, cpu_time=<optimized out>, 
    success=@0x7fffffffd963: true) at /home/richard/GitHub/lammps/lammps/lib/gpu/lal_lj_cubic_ext.cpp:106
#7  0x00005555559a8101 in LAMMPS_NS::PairLJCubicGPU::compute (this=0x555557806c00, eflag=1, vflag=1)
    at /home/richard/GitHub/lammps/lammps/src/GPU/pair_lj_cubic_gpu.cpp:98
#8  0x0000555555954a12 in LAMMPS_NS::Verlet::setup (this=0x555555dda400, flag=1) at /home/richard/GitHub/lammps/lammps/src/verlet.cpp:131
#9  0x00005555559204f8 in LAMMPS_NS::Run::command (this=this@entry=0x7fffffffdb30, narg=narg@entry=1, arg=arg@entry=0x555556e01f80)
    at /home/richard/GitHub/lammps/lammps/src/run.cpp:177
#10 0x000055555580d8bf in LAMMPS_NS::Input::command_creator<LAMMPS_NS::Run> (lmp=<optimized out>, narg=1, arg=0x555556e01f80)
    at /home/richard/GitHub/lammps/lammps/src/input.cpp:878
#11 0x000055555580bc03 in LAMMPS_NS::Input::execute_command (this=0x555555d504a0) at /home/richard/GitHub/lammps/lammps/src/input.cpp:864
#12 0x000055555580c335 in LAMMPS_NS::Input::file (this=0x555555d504a0) at /home/richard/GitHub/lammps/lammps/src/input.cpp:229
#13 0x000055555567fde9 in main (argc=<optimized out>, argv=<optimized out>) at /home/richard/GitHub/lammps/lammps/src/main.cpp:65

```

### PR DESCRIPTION
**Pull request by ndtrung81**
**Summary**

This PR is to fix the bugs caused by the last PR #1735 when the global device is cleared (e.g., triggered by the clear command in the input script) and then initialized for a new run, as reported by @rbberger in #1748. 

**Related Issues**

fixes #1748 

**Author(s)**

Trung Nguyen (Northwestern)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

**Implementation Notes**

Initialize ucl_device with NULL in the constructor of the base classes and then check if it is changed from the last value in init_atomic() after the device is (re)initialied: if so, recompile the kernels, otherwise skip the kernel recompilation.

Note: the OpenCL build still show a gradual increase in memory allocation if multiple consecutive runs are called. massif shows this is associated with libopencl.so, which is not so helpful. The recommended practice with this case (OpenCL builds and multiple consecutive runs) is to add "pre no" to the run command.

Note: the base classes (BaseAtomic, BaseCharge, etc.) need to be refactored to reduce duplicated codes.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by ndtrung81** [comment]
@rbberger The example does not crash on my machine.

[quadro-gp100.txt](https://github.com/lammps/lammps/files/3806526/quadro-gp100.txt)

[gtx-1050.txt](https://github.com/lammps/lammps/files/3806530/gtx-1050.txt)

**Comment by ndtrung81** [comment]
@rbberger sorry I still don't understand why the example crashed with the latest changes for the jenkins regression. I have tried the changes on my machines, or applied them manually to the master branch, and it runs through in either cases. Is there anything I can do to resolve the issue? @akohlmey do you have any suggestions to move things forward? Thanks!

**Comment by ndtrung81** [comment]
@akohlmey @rbberger Please advise me how to proceed with this PR. Thanks!

**Comment by akohlmey** [comment]
> @akohlmey @rbberger Please advise me how to proceed with this PR. Thanks!

don't have time and access to suitable resources to look into this myself over the next few weeks.

**Comment by akohlmey** [comment]
@sjplimp @rbberger @ndtrung81 since i cannot reproduce the reported remaining crashes on my machine, we are out of options to track this down by ourselves and have effectively the choice between two not perfect version. So it seems to me it would be best to merge this anyway and hope for getting some reports from other users or not(!) and then track things down with that input.
To stick with our poilicies, though, I need some approval for merging it.

**Pull request merged**
