### PR TITLE
Improve Consistency of Include Statements

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This tries to implement a consistent handling of include statements throughout LAMMPS with the help of of the [Include What You Use tool](https://include-what-you-use.org/). The main objectives are
- reduce the number of include statements in headers to the minimum
- use includes in the implementation files according the "include what you use" principle and thus simplify dependencies by removing unused include statements
- resolve some issues that showed up in the process (e.g. replacing use of iostreams with stdio)
- improve namespace hygiene by placing definitions or bundled libraries into specific namespaces
- provide a document outlining the goals and applied rules (and exceptions)

**Related Issues**

This was inspired by PR #1539

**Author(s)**

Axel Kohlmeyer (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This may break external LAMMPS add-ons by removing hidden dependencies.

**Implementation Notes**

The processing with the IWYU tool cannot be automated, since it currently does not work 100% correct.
Also, this is not complete, but covers as much as I had time for. Will have to focus on other, more pressing tasks now to get a stable release done before the LAMMPS workshop.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by sjplimp** [comment]
In the past there have been problems (compile time I think, but possibly run-time) if
mpi.h is not the first include.  I think the issue was it needed to be before other
system includes.  If you put it after the file include itself (e.g. pair.h for pair.cpp), then you pull
in some system includes before mpi.h, e.g. via lmptype.h.  Separate issue: is there
a reason not to list the system include files first, followed by the LAMMPS ones 
(e.g. pair.h, followed by everything pair.cpp needs). That's the way it is now and
doesn't seem to conflict with anything in the Summary.

**Comment by akohlmey** [comment]
> In the past there have been problems (compile time I think, but possibly run-time) if
> mpi.h is not the first include. I think the issue was it needed to be before other
> system includes. If you put it after the file include itself (e.g. pair.h for pair.cpp), then you pull
> in some system includes before mpi.h, e.g. via lmptype.h. Separate issue: is there
> a reason not to list the system include files first, followed by the LAMMPS ones
> (e.g. pair.h, followed by everything pair.cpp needs). That's the way it is now and
> doesn't seem to conflict with anything in the Summary.

if we put the matching include first, it is *guaranteed* that the order of lmptype.h and mpi.h is as needed, since they are included by pointers.h. several files were including those first before other system headers, but this way it should be safer. i've been debating whether to explicitly include mpi.h at all, since it would be already included. i've kept/added it so far, since it reduced the number of false positives of the tool i am using to detect unused and missing headers.

i am leaning towards the convention that certain headers may be assumed to be included when pointers.h is explicitly or implicitly included. this would be particularly important for headers where the order matters.

right now, everything that includes pointers.h directly or indirectly may assume that also mpi.h, limits.h, stdint.h, inttypes.h, and stdio.h (or rather their c++ compliant version) is already included and in the right order. but that only works consistently, when the corresponding headers come first and the system headers after that.

**Comment by akohlmey** [comment]
in the long run, i probably either need to find a better tool for checking the includes, so that we can automate the process. or perhaps customize the tool i am currently using to have a "lammps-mode" so it won't report wrong suggestions. when it works it is quite nifty, since its log file has suggestions what to change, which can be applied with a bundled python script.

**Comment by ellio167** [comment]
@akohlmey FYI, I found that the version available on fedora is terribly out-of-date and gave all sorts of false behavior (when used on the kim-api).  The version (0.12) I tried through homebrew worked *much* better.  I also found the pragmas (`// IWYU pragma: begin_exports`, etc.) to be useful.

**Comment by akohlmey** [comment]
> @akohlmey FYI, I found that the version available on fedora is terribly out-of-date and gave all sorts of false behavior (when used on the kim-api). The version (0.12) I tried through homebrew worked _much_ better. I also found the pragmas (`// IWYU pragma: begin_exports`, etc.) to be useful.

thanks for the info. i was already using a self-compiled (newer) version. there are still lots of issues and choices, that i don't agree with. but i am thinking now, that it may be easier to just post-process the output rather than hack the tool. will have to see. a package as mighty as LAMMPS with most packages enabled, is putting such tools to a serious test.

**Comment by akohlmey** [comment]
@sjplimp just noticed an issue in the kim updates that confirm, that putting the header matching the .cpp file first is a good idea. In some of the cases, some system headers were included first before the matching .h file and thus compilation didn't fail, since those headers were using definitions that were not covered by pointers.h (e.g. std::string). This should have failed compiling input.cpp if not by chance some other headers also used the same definition and thus had the matching include already included. By placing the header include first, the compilation will fail right away when compiling the implementation and thus making debugging and fixing the issue much easier.

**Comment by akohlmey** [comment]
@sjplimp after rolling back the changes to the POEMS lib (will look into it post workshop) this is now ready for merging.

**Comment by stanmoore1** [comment]
Regression tests are failing with a compile error:

```
mpic++ -O3 -g  -DLAMMPS_GZIP -I../../lib/qmmm -I../../lib/colvars -I../../lib/awpmd/ivutils/include -I../../lib/awpmd/systems/interact -I../../lib/voronoi/includelink -DLMP_PYTHON -I../../lib/poems -DLMP_MPIIO -I../../lib/reax -I../../lib/meam       -I../../lib/molfile  -I/jenkins/slave/workspace/LAMMPS_perseus/lammps_testing/voronoi/include/voro++ -I/projects/sems/install/rhel6-x86_64/sems/compiler/python/2.7.9/include/python2.7 -I/projects/sems/install/rhel6-x86_64/sems/compiler/python/2.7.9/include/python2.7     -c ../meam_dens_final.cpp
In file included from ../meam_dens_final.cpp:1:0:
../meam.h:237:26: error: ‘size_t’ has not been declared
 template <typename TYPE, size_t maxi, size_t maxj>
                          ^~~~~~
../meam.h:237:39: error: ‘size_t’ has not been declared
 template <typename TYPE, size_t maxi, size_t maxj>
                                       ^~~~~~
../meam.h:238:41: error: ‘maxi’ was not declared in this scope
 static inline void setall2d(TYPE (&arr)[maxi][maxj], const TYPE v) {
```

**Pull request merged**
