### PR TITLE
Neighbor fixes

### PR DESCRIPTION
**Pull request by stanmoore1**
Fix bugs in neighborlist code

### CODE REVIEW

**Comment by stanmoore1** [comment]
This fixes #333.

**Comment by zqex** [comment]
This bugfix does not resolve the crash I reported on the list in relation to examples/USER/misc/srp

**Comment by akohlmey** [comment]
strange. it fixes it for me. did you do a "make package-update" after pulling the branch?

**Comment by zqex** [comment]
Dear Axel,

Indeed very strange. I couldn't merge the pull request, apparently write 
access to the stanmoore1:neighbor_fixes branch is required for this.

However, I manually ported the changes (just a few lines). Checked 
correctness with git diff vs. "files changed" on github, did make pu, 
recompiled, and reproduced the same crash.

-- 
   Mvh. Carsten

**Comment by akohlmey** [comment]
OK, you are correct. while the input runs on my machine, valgrind is still unhappy and complaining about illegal accesses. i've looked a bit closer and found a couple of bugs in fix srp and one issue in the neighbor list build during the setup phase of a run.

**Comment by akohlmey** [comment]
My proposed changes are now available in #339

**Pull request merged**
