### PR TITLE
Fix active

### PR DESCRIPTION
**Pull request by pdebuyl**
Change the direction of propulsion from z to x to enable self-propulsion in 2D in fix propel/self. Update the doc accordingly.

### CODE REVIEW

**Comment by pdebuyl** [comment]
I intended to file a PR against @Pakketeretet2 's branch, closing.

**Comment by gokulup009** [comment]
[active.zip](https://github.com/lammps/lammps/files/5307277/active.zip)

this directory contains two file one for lammps input script and another one for input data when I run the lammps script it gives the error    "Segmentation fault (core dumped) " please see it.

**Comment by akohlmey** [comment]
> [active.zip](https://github.com/lammps/lammps/files/5307277/active.zip)
> 
> this zip directory contains two file one for lammps input script and another one for input data when I run the lammps script it gives the error "Segmentation fault (core dumped) " please see it.

that is because fix propel/self currently has no provisions to support hybrid atom styles. it should be possible to adjust that.

**Comment by akohlmey** [comment]
> > [active.zip](https://github.com/lammps/lammps/files/5307277/active.zip)
> > this zip directory contains two file one for lammps input script and another one for input data when I run the lammps script it gives the error "Segmentation fault (core dumped) " please see it.
> 
> that is because fix propel/self currently has no provisions to support hybrid atom styles. it should be possible to adjust that.

a fix for this going to be in the next patch release.

**Pull request closed without merging**
