### PR TITLE
Smoothed Dissipative Particle Dynamics

### PR DESCRIPTION
**Pull request by DiscreteLogarithm**
## Purpose

Smoothed dissipative particle dynamics package. Adds pair sdpd/taitwater/isothermal for isothermal SDPD simulations of water. Also adds fix meso/move to move SPH/SDPD particles with prescribed velocities and fix rigid/meso to constrain clusters of SPH/SDPD particles to move as rigid bodies.

## Author(s)

Morteza Jalalvand

## Backward Compatibility

No issues.

## Implementation Notes

Ensembles of simulations measuring translational and rotational diffusion coefficients of sphere were performed and the results agrees with the theory. Also velocity and angular velocity autocorrelation functions showed power-law decay behaviour (with correct exponent) agreeing with theories that take hydrodynamic interactions into account. Results of tests will be published in a future paper.

No other feature of LAMMPS will be affected.

## Post Submission Checklist

- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines (mostly)

## Further Information, Files, and Links

Original SDPD paper:
doi.org/10.1103/PhysRevE.67.026705

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp please note, that changes to USER-SPH included here are from me. They fix issues that were inherited by USER-SDPD from that package, so it seemed logical to address them together.

**Comment by DiscreteLogarithm** [comment]
@akohlmey
Thanks for the improvements

**Comment by akohlmey** [comment]
@sjplimp the removal of the `Pair::single()` function is a borderline case. It is technically speaking not a cosmetic change, but on the other hand, it would return force and energy 0, which is certainly bogus and thus any usage of the single method *should* trigger an error, as it does now.

**Comment by sjplimp** [comment]
@akohlmey I agree with your logic.

**Pull request merged**
