### PR TITLE
[Issue #1403] Kspace parameter check fix 

### LINKED ISSUE #1403: [BUG?] Difference between grid parameter checks kspace
I was going through the flag check for the KSpace mesh settings. I noticed that there is a discrepancy between how the flag is set for `gridflag` and `gridflag_6`. One check is `&&` and the other check is `||`. I was wondering whether this deliberately done or which one of them should be fixed. 

Line [441 ](https://github.com/lammps/lammps/blob/f73ccc3025ad1003f24f7d1ed36393e96c0986e9/src/kspace.cpp#L441)to [456 ](https://github.com/lammps/lammps/blob/f73ccc3025ad1003f24f7d1ed36393e96c0986e9/src/kspace.cpp#L456)from `kspace.cpp`

```
    if (strcmp(arg[iarg],"mesh") == 0) {
      if (iarg+4 > narg) error->all(FLERR,"Illegal kspace_modify command");
      nx_pppm = nx_msm_max = force->inumeric(FLERR,arg[iarg+1]);
      ny_pppm = ny_msm_max = force->inumeric(FLERR,arg[iarg+2]);
      nz_pppm = nz_msm_max = force->inumeric(FLERR,arg[iarg+3]);
      if (nx_pppm == 0 && ny_pppm == 0 && nz_pppm == 0) gridflag = 0;
      else gridflag = 1;
      iarg += 4;
    } else if (strcmp(arg[iarg],"mesh/disp") == 0) {
      if (iarg+4 > narg) error->all(FLERR,"Illegal kspace_modify command");
      nx_pppm_6 = force->inumeric(FLERR,arg[iarg+1]);
      ny_pppm_6 = force->inumeric(FLERR,arg[iarg+2]);
      nz_pppm_6 = force->inumeric(FLERR,arg[iarg+3]);
      if (nx_pppm_6 == 0 || ny_pppm_6 == 0 || nz_pppm_6 == 0) gridflag_6 = 0;
      else gridflag_6 = 1;
iarg += 4;
```

### PR DESCRIPTION
**Pull request by tabedzki**
**Summary**

Changes the `mesh` and `mesh/disp` checks in `kspace.cpp` to `||` instead of `&&`. Also it errors out instead of silently ignoring user settings if one of the grid parameters is a non-positive number.

**Related Issues**

closes #1403 

**Author(s)**
Christian Tabedzki

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No.

**Implementation Notes**

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

None.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@rbberger @akohlmey The cmake test is failing, looks unrelated to this PR:

```
-- Looking for C++ include cmath
-- Looking for C++ include cmath - found
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find TBB (missing: TBB_LIBRARY TBB_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  Modules/FindTBB.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:1049 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by akohlmey** [comment]
> @rbberger @akohlmey The cmake test is failing, looks unrelated to this PR:
> 
> ```
> -- Looking for C++ include cmath
> -- Looking for C++ include cmath - found
> CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find TBB (missing: TBB_LIBRARY TBB_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   Modules/FindTBB.cmake:25 (find_package_handle_standard_args)
>   CMakeLists.txt:1049 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> ```

that is because this branch is based on an outdated master from several months ago where the processing of USER-INTEL in CMake was not working correctly.

Besides, the proposed changes don't look correct to me. Will give this a try myself tomorrow, and update the docs as needed, too.

**Comment by akohlmey** [comment]
@tabedzki things will work best for submitting changes to the LAMMPS project, if you keep a clean and up-to-date variant of the master branch in your fork. that way you can always update it with `--fast-forward` pulls from `https://github.com/lammps/lammps.git master` and you have no stray, unrelated commits in your history (we like to preserve the entire commit history of contributions, if available) that you need to undo in some form for the pull request. Through keeping `master` up-to-date, you can always base new feature branches on the latest upstream, which will avoid merge conflicts and make certain, that it is compatible with the automatic integration testing. For your own contribution, you can also consider using `git rebase` instead of `git merge` when keeping it up-to-date with upstream, but keep in mind, that rebasing of branches shared with others through pushing them to github, can cause problems, as those people will diverge from your history since rebasing will re-write the commit history and require forced pushes. In that case, simply merging will be cleaner.

**Comment by tabedzki** [comment]
Thanks for the advice Axel. This is my first time making a fork and
contribution to a open source project, especially on github.

**Comment by akohlmey** [comment]
> Thanks for the advice Axel. This is my first time making a fork and contribution to a open source project, especially on github.

yes, that is what I guessed. there is useful information in the github tutorial in the LAMMPS manual as well. but in general, you should look elsewhere for good git tutorials. one of the problems (and benefits) of git is, that it offers so many options to do essentially the same thing, so that there is no single "one true way (tm)" to do something. so a lot of what individual projects do and how things are handled are based on conventions rather than on requirements of the software. You can see how I would go about implementing what Stan was suggesting here:
https://github.com/lammps/lammps/pull/1492/files#diff-9d4915bb50fca9b017b91fe90765af18

**Comment by tabedzki** [comment]
@akohlmey just curious, why are the following lines included in the `kspace.h` file? Does the code use it somewhere or is just to keep track of all possible errors/warnings?

```
E: Kspace_modify mesh parameter must be all zero or all positive

Valid kspace mesh parameters are >0. The code will try to auto-detect
suitable values when all three mesh sizes are set to zero (the default).

E: Kspace_modify mesh/disp parameter must be all zero or all positive

Valid kspace mesh/disp parameters are >0. The code will try to auto-detect
suitable values when all three mesh sizes are set to zero [and]
the required accuracy via {force/disp/real} as well as
{force/disp/kspace} is set.
```

**Comment by akohlmey** [comment]
> @akohlmey just curious, why are the following lines included in the `kspace.h` file in your solution? Does the code use it somewhere or is just to keep track of all possible errors/warnings? Same question for `Error_messages.txt`

`Error_messages.txt` is part of the manual and it shall document all error messages present in LAMMPS. This goes back a long time and the reasoning is: we keep error messages in xxx.cpp files synchronized with the corresponding xxx.h file and the collected messages (errors and warnings) and then collected and synchronized with the manual. the first part can be done incrementally and easily checked when people submit changes. the second part is occasionally verified and can be (mostly) automated.

**Comment by tabedzki** [comment]
Ok. Thanks for explaining. So in the future, any future commits or user-packages should have the same thing, right?

**Comment by akohlmey** [comment]
> Ok. Thanks for explaining. So in the future, any future commits or user-packages should have the same thing, right?

yes, it will make it less effort to integrate contributions.

**Pull request closed without merging**
