### PR TITLE
cmake: allow to build against an external libkokkos

### PR DESCRIPTION
**Pull request by junghans**
**Summary**

Allow to use an external (pre-compiled) kokkos

**Related Issues**

None

**Author(s)**

@junghans

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

**Implementation Notes**

Only CMake changes

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@junghans how do we achieve, that an external kokkos library is compatible with the KOKKOS package in LAMMPS? Can you describe a scenario, where using an external kokkos library would be beneficial over using the bundled one, which is tested to work?
Assigning this to @stanmoore1 as he is the gatekeeper for all things KOKKOS in LAMMPS.

**Comment by junghans** [comment]
@akohlmey, we want to build a bigger piece of software, which uses lammps as library, but also another library, both of which use kokkos and hence we can to compile them with the same kokkos library to avoid symbol duplication.

**Comment by junghans** [comment]
@stanmoore1, this is how I would envision that will work on the lammps side:
```
cmake -DPKG_KOKKOS=ON -DEXTERNAL_KOKKOS=ON -DCMAKE_PREFIX_PATH=/path/to/kokkos.install ../cmake
```
There might be still some updates needed to make it work with the latest develop version of kokkos again.

**Comment by junghans** [comment]
Just FYI, to test this one has to use a reasonably new version of kokkos' develop branch, e.g. https://github.com/kokkos/kokkos/commit/f09736b079193facc9afb844a5200cd26f225fa1 and then build and install kokkos:
```bash
git clone -b develop https://github.com/kokkos/kokkos
mkdir build
cd build
cmake -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_DEPRECATED_CODE=ON -DCMAKE_INSTALL_PREFIX=$HOME/kokkos.install ..
make
make install
```
and then configure lammps with:
```
cmake -DPKG_KOKKOS=ON -DEXTERNAL_KOKKOS=ON -DCMAKE_PREFIX_PATH=$HOME/kokkos.install ../cmake
```

The only non-standard thing is `Kokkos_ENABLE_DEPRECATED_CODE=ON`, which means lammps uses deprecated kokkos code, but that not really an issue related to this PR.

**Comment by junghans** [comment]
@stanmoore1 can you have another look at this?

**Comment by stanmoore1** [comment]
This is fine--I am aware of the deprecated code issue and it is on my to-do list to fix it.

**Pull request merged**
