### PR TITLE
Support read_dump with dump style 'adios'

### PR DESCRIPTION
**Pull request by pnorbert**
**Summary**
Implement read_dump with format 'adios'. It modifies read_dump.cpp to support reading from one dataset by all processes.

**Author(s)**
@pnorbert ORNL
github.com://ornladios/ADIOS2 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

There is some fix in the adios style dump: the 'columns' attribute is now a vector of strings in both custom and atom dumps. The reader relies on this but it was mixed up so far in the two dump styles.

**Implementation Notes**

Introduced an isReaderParallel flag in read_dump.h, and this is set to true in case of the adios style. This flag is used in read_dump.cpp to enable reading a single file/dataset from all processes. In this case multiproc = 0 and multiproc_nfile = 1. Those variables control other scenarios for reading data from M files by N processes. 

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

These are missing from this WIP PR.
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The feature has been verified to work with the conventional build system

These are complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the CMake based build system
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

### CODE REVIEW

**Comment by akohlmey** [comment]
@pnorbert I just submitted a pull request in your LAMMPS fork with some suggested changes to fix compilation, formatting and programming style issues. Please merge and try it out.

@sjplimp no point in looking at this until my changes are included.

This submission also needs documentation added. Please note, that changes should be made directly to .rst files now and if corresponding .txt files still exist, they should be removed after updates to the .rst version.

**Comment by akohlmey** [comment]
@pnorbert do you feel this is now nearing completion? or what do you know is still missing?
@sjplimp this is now ready for you to have a look. My suggested changes are included.

**Comment by pnorbert** [comment]
- I have not tried to build with conventional build system.
- @sjplimp will give some more examples to play with, since there is only one example available in the PR.

**Comment by pnorbert** [comment]
Ready for merging. Tested conventional build. Added another example for rerun and read_dump to the repository.

**Comment by akohlmey** [comment]
> Ready for merging. Tested conventional build. Added another example for rerun and read_dump to the repository.

@sjplimp ?

**Comment by pnorbert** [comment]
The changes now support "timeout" in the rerun ... format adios command to enable concurrent runs. This works for the BP4 engine to stream through file. 

The staging engines don't seem to work for me properly, so this PR does not address concurrent runs with staging. 

Please merge. If I find the fix for staging, I will open a new PR.

**Pull request merged**
