### PR TITLE
Fix selfpropel

### PR DESCRIPTION
**Pull request by samueljmcameron**
**Summary**

Add a self-propulsion term in the direction of the particle's dipole orientation. This command is extremely similar to fix propel/self. The differences are two-fold. Firstly, this command uses dipole to indicate the direction of the self-propulsion force (superficial and not important at all). Secondly, this command allows one to compute the active pressure of the system (fix propel/self does not). This is the important difference. I would be happy to just implement these changes by editing propel/self, but I will let someone who knows best decide this.

**Related Issue(s)**

N/A.

**Author(s)**

Sam Cameron, University of Bristol. samuel.j.m.cameron at gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A.

**Implementation Notes**

Correctness was verified by manually checking that the forces add by this fix are equivalent to adding them ''by hand'' (i.e. do a run with zero timesteps, and compute the forces from dipole orientation directly from the dump file, and compare to the output forces). Correctness of the virial contribution was verified through longer simulations of non-interacting particles, and the expected pressure was obtained.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

N/A

### CODE REVIEW

**Comment by akohlmey** [comment]
@samueljmcameron yes, it would be better to add these changes to the existing fix propel/self. the naming of this fix would be too confusing in comparison with propel/self. a little word about the history of fix propel/self: it was started by somebody that has since left academia and it was finished of in a band-aid style so it was available for people that had asked for it in a reasonable, but not perfect shape.

in light of our previous discussion about user packages, i would propose the following:
if you are willing to take over maintenance for fix propel/self and in combination with the other two fixes that you have written and that are pending to be merged, there would now be sufficient justification to put all three fixes into a new user package, say USER-BROWNIAN. Thematically, it could also somewhat fit into the COLLOID package. @sjplimp, what do you think?
Since LAMMPS is already so big and has so many packages, I am always looking for ways to move things into existing packages before creating a new one.

**Comment by sjplimp** [comment]
I'd say a USER-BROWNIAN package.

**Comment by akohlmey** [comment]
@samueljmcameron there you have it. so I would suggest to close this PR and update your other PR and then move the fixes (one more time) to a new USER-BROWNIAN package folder (and correspondingly the examples). I leave it to you to either change the names to `fix brownian/sphere` / `fix brownian/asphere` (my personal preference) or leave it at `fix bd/sphere` and `fix bd/asphere` (not my preference but still acceptable). You should add your name (and contact info) in fix_propel_self.cpp and identify yourself as current maintainer. OR if you feel that it would be simpler for you, you can also close both PRs and submit a new one with the whole set of changes. Whatever you do, please ping me when done, because then there are likely some changes to the build system and documentation needed that are better done by me.

**Comment by samueljmcameron** [comment]
Okay that makes sense. I will do what you have suggested. Last question before I close this... When you say ''ping'' you, how do I do that? Sorry I am still somewhat unfamiliar with github PRs etc.

**Comment by akohlmey** [comment]
> Okay that makes sense. I will do what you have suggested. Last question before I close this... When you say ''ping'' you, how do I do that? Sorry I am still somewhat unfamiliar with github PRs etc.

just add a comment to the discussion that includes an "at-mention" of my github user id, i.e. @akohlmey 
that will generate a notification on our LAMMPS slack github channel and an email to me. I have disabled most notifications since there are so many on a busy project. I will see your comment eventually without, but that just speeds up the process (provided I am not occupied with some other task).

**Comment by samueljmcameron** [comment]
Okay great thanks. Closing this now and will move it to the other PR.

**Pull request closed without merging**
