### PR TITLE
Coulomb refactoring for tables and analytic

### LINKED ISSUE #94: Convert analytical approximation for erfc() to use double precision version
Apply the following change to all coul/long pair styles, this will improve the accuracy and precision of computing the analytical coulomb potential for use with long-range solvers significantly.

```diff
diff --git a/src/KSPACE/pair_lj_charmm_coul_long.cpp b/src/KSPACE/pair_lj_charmm_coul_long.cpp
index 2c709a3..f4695d9 100644
--- a/src/KSPACE/pair_lj_charmm_coul_long.cpp
+++ b/src/KSPACE/pair_lj_charmm_coul_long.cpp
@@ -30,18 +30,14 @@
 #include "neighbor.h"
 #include "neigh_list.h"
 #include "neigh_request.h"
+#include "math_special.h"
+#include "math_const.h"
 #include "memory.h"
 #include "error.h"
 
 using namespace LAMMPS_NS;
-
-#define EWALD_F   1.12837917
-#define EWALD_P   0.3275911
-#define A1        0.254829592
-#define A2       -0.284496736
-#define A3        1.421413741
-#define A4       -1.453152027
-#define A5        1.061405429
+using namespace MathSpecial;
+using namespace MathConst;
 
 /* ---------------------------------------------------------------------- */
 
@@ -144,11 +140,10 @@ void PairLJCharmmCoulLong::compute(int eflag, int vflag)
           if (!ncoultablebits || rsq <= tabinnersq) {
             r = sqrt(rsq);
             grij = g_ewald * r;
-            expm2 = exp(-grij*grij);
-            t = 1.0 / (1.0 + EWALD_P*grij);
-            erfc = t * (A1+t*(A2+t*(A3+t*(A4+t*A5)))) * expm2;
+            expm2 = expmsq(grij);
+            erfc = my_erfcx(grij) * expm2;
             prefactor = qqrd2e * qtmp*q[j]/r;
-            forcecoul = prefactor * (erfc + EWALD_F*grij*expm2);
+            forcecoul = prefactor * (erfc + MY_ISPI4*grij*expm2);
             if (factor_coul < 1.0) forcecoul -= (1.0-factor_coul)*prefactor;
           } else {
             union_int_float_t rsq_lookup;
@@ -479,11 +474,10 @@ void PairLJCharmmCoulLong::compute_outer(int eflag, int vflag)
           if (!ncoultablebits || rsq <= tabinnersq) {
             r = sqrt(rsq);
             grij = g_ewald * r;
-            expm2 = exp(-grij*grij);
-            t = 1.0 / (1.0 + EWALD_P*grij);
-            erfc = t * (A1+t*(A2+t*(A3+t*(A4+t*A5)))) * expm2;
+            expm2 = expmsq(grij);
+            erfc = my_erfcx(grij) * expm2;
             prefactor = qqrd2e * qtmp*q[j]/r;
-            forcecoul = prefactor * (erfc + EWALD_F*grij*expm2 - 1.0);
+            forcecoul = prefactor * (erfc + MY_ISPI4*grij*expm2 - 1.0);
             if (rsq > cut_in_off_sq) {
               if (rsq < cut_in_on_sq) {
                 rsw = (r - cut_in_off)/cut_in_diff;
@@ -572,7 +566,7 @@ void PairLJCharmmCoulLong::compute_outer(int eflag, int vflag)
         if (vflag) {
           if (rsq < cut_coulsq) {
             if (!ncoultablebits || rsq <= tabinnersq) {
-              forcecoul = prefactor * (erfc + EWALD_F*grij*expm2);
+              forcecoul = prefactor * (erfc + MY_ISPI4*grij*expm2);
               if (factor_coul < 1.0) forcecoul -= (1.0-factor_coul)*prefactor;
             } else {
               table = vtable[itable] + fraction*dvtable[itable];
@@ -966,11 +960,10 @@ double PairLJCharmmCoulLong::single(int i, int j, int itype, int jtype,
     if (!ncoultablebits || rsq <= tabinnersq) {
       r = sqrt(rsq);
       grij = g_ewald * r;
-      expm2 = exp(-grij*grij);
-      t = 1.0 / (1.0 + EWALD_P*grij);
-      erfc = t * (A1+t*(A2+t*(A3+t*(A4+t*A5)))) * expm2;
+      expm2 = expmsq(grij);
+      erfc = my_erfcx(grij) * expm2;
       prefactor = force->qqrd2e * atom->q[i]*atom->q[j]/r;
-      forcecoul = prefactor * (erfc + EWALD_F*grij*expm2);
+      forcecoul = prefactor * (erfc + MY_ISPI4*grij*expm2);
       if (factor_coul < 1.0) forcecoul -= (1.0-factor_coul)*prefactor;
     } else {
       union_int_float_t rsq_lookup;
```

Similar for pppm styles:
```diff
diff --git a/src/KSPACE/pppm.cpp b/src/KSPACE/pppm.cpp
index 9b18ad8..4ff1bd8 100644
--- a/src/KSPACE/pppm.cpp
+++ b/src/KSPACE/pppm.cpp
@@ -1200,23 +1200,24 @@ double PPPM::compute_qopt()
           sum2 = 0.0;
           sum3 = 0.0;
           sum4 = 0.0;
+          const double inv_gew = 1.0/g_ewald;
           for (nx = -2; nx <= 2; nx++) {
             qx = unitkx*(kper+nx_pppm*nx);
-            sx = exp(-0.25*square(qx/g_ewald));
+            sx = expmsq(0.5*qx*inv_gew);
             argx = 0.5*qx*xprd/nx_pppm;
             wx = powsinxx(argx,twoorder);
             qx *= qx;
 
             for (ny = -2; ny <= 2; ny++) {
               qy = unitky*(lper+ny_pppm*ny);
-              sy = exp(-0.25*square(qy/g_ewald));
+              sy = expmsq(0.5*qy*inv_gew);
               argy = 0.5*qy*yprd/ny_pppm;
               wy = powsinxx(argy,twoorder);
               qy *= qy;
 
               for (nz = -2; nz <= 2; nz++) {
                 qz = unitkz*(mper+nz_pppm*nz);
-                sz = exp(-0.25*square(qz/g_ewald));
+                sz = expmsq(0.5*qz*inv_gew);
                 argz = 0.5*qz*zprd_slab/nz_pppm;
                 wz = powsinxx(argz,twoorder);
                 qz *= qz;
@@ -1288,7 +1289,7 @@ double PPPM::newton_raphson_f()
   double zprd = domain->zprd;
   bigint natoms = atom->natoms;
 
-  double df_rspace = 2.0*q2*exp(-g_ewald*g_ewald*cutoff*cutoff) /
+  double df_rspace = 2.0*q2*expmsq(g_ewald*cutoff) /
        sqrt(natoms*cutoff*xprd*yprd*zprd);
 
   double df_kspace = compute_df_kspace();
@@ -1329,7 +1330,7 @@ double PPPM::final_accuracy()
 
   double df_kspace = compute_df_kspace();
   double q2_over_sqrt = q2 / sqrt(natoms*cutoff*xprd*yprd*zprd);
-  double df_rspace = 2.0 * q2_over_sqrt * exp(-g_ewald*g_ewald*cutoff*cutoff);
+  double df_rspace = 2.0 * q2_over_sqrt * expmsq(g_ewald*cutoff);
   double df_table = estimate_table_accuracy(q2_over_sqrt,df_rspace);
   double estimated_accuracy = sqrt(df_kspace*df_kspace + df_rspace*df_rspace +
                                    df_table*df_table);
@@ -1570,22 +1571,23 @@ void PPPM::compute_gf_ik()
           numerator = 12.5663706/sqk;
           denominator = gf_denom(snx,sny,snz);
           sum1 = 0.0;
+          const double inv_gew = 1.0/g_ewald;
 
           for (nx = -nbx; nx <= nbx; nx++) {
             qx = unitkx*(kper+nx_pppm*nx);
-            sx = exp(-0.25*square(qx/g_ewald));
+            sx = expmsq(0.5*qx*inv_gew);
             argx = 0.5*qx*xprd/nx_pppm;
             wx = powsinxx(argx,twoorder);
 
             for (ny = -nby; ny <= nby; ny++) {
               qy = unitky*(lper+ny_pppm*ny);
-              sy = exp(-0.25*square(qy/g_ewald));
+              sy = expmsq(0.5*qy*inv_gew);
               argy = 0.5*qy*yprd/ny_pppm;
               wy = powsinxx(argy,twoorder);
 
               for (nz = -nbz; nz <= nbz; nz++) {
                 qz = unitkz*(mper+nz_pppm*nz);
-                sz = exp(-0.25*square(qz/g_ewald));
+                sz = expmsq(0.5*qz*inv_gew);
                 argz = 0.5*qz*zprd_slab/nz_pppm;
                 wz = powsinxx(argz,twoorder);
 
@@ -1653,6 +1655,7 @@ void PPPM::compute_gf_ik_triclinic()
           numerator = 12.5663706/sqk;
           denominator = gf_denom(snx,sny,snz);
           sum1 = 0.0;
+          const double inv_gew = 1.0/g_ewald;
 
           for (nx = -nbx; nx <= nbx; nx++) {
             argx = MY_PI*kper/nx_pppm + MY_PI*nx;
@@ -1673,13 +1676,13 @@ void PPPM::compute_gf_ik_triclinic()
                 x2lamdaT(&b[0],&b[0]);
 
                 qx = unitk_lamda[0]+b[0];
-                sx = exp(-0.25*square(qx/g_ewald));
+                sx = expmsq(0.5*qx*inv_gew);
 
                 qy = unitk_lamda[1]+b[1];
-                sy = exp(-0.25*square(qy/g_ewald));
+                sy = expmsq(0.5*qy*inv_gew);
 
                 qz = unitk_lamda[2]+b[2];
-                sz = exp(-0.25*square(qz/g_ewald));
+                sz = expmsq(0.5*qz*inv_gew);
 
                 dot1 = unitk_lamda[0]*qx + unitk_lamda[1]*qy + unitk_lamda[2]*qz;
                 dot2 = qx*qx+qy*qy+qz*qz;
@@ -1716,6 +1719,7 @@ void PPPM::compute_gf_ad()
   int k,l,m,n,kper,lper,mper;
 
   const int twoorder = 2*order;
+  const double inv_gew = 1.0/g_ewald;
 
   for (int i = 0; i < 6; i++) sf_coeff[i] = 0.0;
 
@@ -1724,7 +1728,7 @@ void PPPM::compute_gf_ad()
     mper = m - nz_pppm*(2*m/nz_pppm);
     qz = unitkz*mper;
     snz = square(sin(0.5*qz*zprd_slab/nz_pppm));
-    sz = exp(-0.25*square(qz/g_ewald));
+    sz = expmsq(0.5*qz*inv_gew);
     argz = 0.5*qz*zprd_slab/nz_pppm;
     wz = powsinxx(argz,twoorder);
 
@@ -1732,7 +1736,7 @@ void PPPM::compute_gf_ad()
       lper = l - ny_pppm*(2*l/ny_pppm);
       qy = unitky*lper;
       sny = square(sin(0.5*qy*yprd/ny_pppm));
-      sy = exp(-0.25*square(qy/g_ewald));
+      sy = expmsq(0.5*qy*inv_gew);
       argy = 0.5*qy*yprd/ny_pppm;
       wy = powsinxx(argy,twoorder);
 
@@ -1740,7 +1744,7 @@ void PPPM::compute_gf_ad()
         kper = k - nx_pppm*(2*k/nx_pppm);
         qx = unitkx*kper;
         snx = square(sin(0.5*qx*xprd/nx_pppm));
-        sx = exp(-0.25*square(qx/g_ewald));
+        sx = expmsq(0.5*qx*inv_gew);
         argx = 0.5*qx*xprd/nx_pppm;
         wx = powsinxx(argx,twoorder);
```

### PR DESCRIPTION
**Pull request by akohlmey**
This pull request collects multiple enhancements to long-range coulomb interactions with analytic computation of erfc() and tabulated approximation. This closes #94 

## List of affected pair styles:
- [x] lj/class2/coul/long
- [ ] born/coul/long/cs
- [ ] buck/coul/long/cs
- [ ] coul/long/cs
- [ ] lj/cut/coul/long/cs
- [x] lj/cut/dipole/long
- [ ] born/coul/long/gpu
- [ ] buck/coul/long/gpu
- [ ] coul/dsf/gpu
- [ ] cou/long/gpu
- [ ] lj/charmm/coul/long/gpu
- [ ] lj/class2/coul/long/gpu
- [ ] lj/cut/coul/dsf/gpu
- [ ] lj/cut/coul/long/gpu
- [ ] lj/sdk/coul/long/gpu
- [x] buck/coul/long/kk
- [ ] coul/dsf/kk
- [x] cou/long/kk
- [x] lj/charmm/coul/long/kk
- [x] lj/class2/coul/long/kk
- [ ] lj/cut/coul/dsf/kk
- [x] lj/cut/coul/long/kk
- [x] born/coul/long
- [x] buck/coul/long
- [ ] buck/long/coul/long
- [x] coul/long
- [x] lj/charmm/coul/long
- [x] lj/cut/coul/long
- [x] lj/cut/tip4p/long
- [ ] lj/long/coul/long
- [ ] lj/long/tip4p/long
- [x] tip4p/long
- [x] nm/cut/coul/long
- [x] lj/charmm/coul/long/opt
- [x] lj/cut/coul/long/opt
- [x] lj/cut/tip4p/long/opt
- [ ] lj/long/coul/long/opt
- [x] lj/sdk/coul/long
- [ ] lj/cut/thole/long
- [ ] coul/long/soft
- [ ] lj/charmm/coul/long/soft
- [ ] lj/cut/coul/long/soft
- [ ] lj/cut/tip4p/long/soft
- [ ] tip4p/long/soft
- [x] born/coul/long/omp
- [x] buck/coul/long/omp
- [ ] buck/long/coul/long/omp
- [x] coul/dsf/omp
- [x] coul/long/omp
- [ ] coul/long/soft/omp
- [x] lj/charmm/coul/long/omp
- [x] lj/class2/coul/long/omp
- [x] lj/cut/coul/dsf/omp
- [x] lj/cut/coul/long/omp
- [ ] lj/cut/coul/long/soft/omp
- [ ] lj/cut/thole/long/omp
- [x] lj/cut/tip4p/long/omp
- [ ] lj/cut/tip4p/long/soft/omp
- [ ] lj/long/coul/long/omp
- [ ] lj/long/tip4p/long/omp
- [x] lj/sdk/coul/long/omp
- [x] nm/cut/coul/long/omp
- [x] tip4p/long/omp
- [ ] tip4p/long/soft/omp
- [ ] buck/coul/long/intel
- [ ] lj/charmm/coul/long/intel
- [ ] lj/cut/coul/long/intel

NOTE: this is a branch hosted directly on github with direct push access to all registered LAMMPS developers (not collaborators), who are invited to contribute changes.

This is already posted as a pull request, so we get automatic minimal integration testing via ci.lammps.org (tests whether the code compiles with 3 different sets of compilation settings).

### CODE REVIEW

**Comment by akohlmey** [comment]
@stanmoore1 on second thought, it is better to set this up as a pull request right away, which is in essence an issue attached to a specific branch. I've rebased the branch in my repo onto master and already merged the tabulation update (PR #321) as well.

**Comment by stanmoore1** [comment]
Fixes #94

**Comment by akohlmey** [comment]
This is a fantastic example of what a time saver git can be. I just took a branch that hasn't been updated for almost half a year, rebased it to a branch that differs by almost 10,000 commits (though not much in content); then merged in a pull request, that also was not in sync with upstream and had merge conflicts, and this all in a couple of hours. way back when it would have taken a day or two of hard work juggling manually editing patches and identifying relevant changes and tweaking them, so the patches go in cleanly. The mind boggles...

**Comment by stanmoore1** [comment]
Yes, I am a fan of Git.

**Comment by akohlmey** [comment]
this branch has become stale and there are too many merge conflicts. better to start over and handle the more difficult to implement cases first and also build a set of regression tests alongside the implementation, so we can confirm that previous results are preserved (within the limit of accuracy). Since the required constants and custom functions are already implemented, this can also be done now in increments.

**Pull request closed without merging**
