### PR TITLE
Add morse soft

### PR DESCRIPTION
**Pull request by Pakketeretet2**
This is a soft-core variant of the Morse potential for use with USER-FEP. It uses a transformation formula similar to lj/cut.

### CODE REVIEW

**Comment by akohlmey** [comment]
I think this pair style needs some more work. Steve asked for the necessary documentation, and this seemed like a no-brainer, but upon looking a bit closer, there are a few things that don't add up for me:

* the pair style command requires an option "scale", but that parameter doesn't seem to be used anywhere
* lj/cut/soft and coul/long/soft have a parameter alpha that seems to be missing (is it set to 1.0?)
* there seems to be something off with the force computation (at least in the Pair::single() function); when i construct a very similar lj/cut/soft potential, energies are similar for similar lambda, but forces not so much. also the response to lambda seems different. please see below for a test input.

i've added some preliminary docs and adjusted the code a bit in commits: 25bdc7b595051c41a951ccb5f8dbb35fc4ac5bd4 and 5194f601bade97d3b29bd856327ed64cd8aa0afd .
since nlambda is set to be integer, force evaluation can be made faster through using MathSpecial::powint().

```
units real
region box block 0 1 0 1 0 1
create_box 1 box

shell 'rm -fv morse*.dat'

pair_style morse 10.0
pair_coeff 1 1 100.0 1.65 3.93 10.0
pair_write 1 1 1000 rsq 0.1 10.0 morse.dat morse_100_10_3


pair_style morse/soft 2 10.0
pair_coeff 1 1 100.0 1.65 3.93 1.0 10.0
pair_write 1 1 1000 rsq 0.1 10.0 morse-soft.dat morse_100_10_3_1.0

pair_coeff 1 1 100.0 1.65 3.93 0.8 10.0
pair_write 1 1 1000 rsq 0.1 10.0 morse-soft.dat morse_100_10_3_0.8

pair_coeff 1 1 100.0 1.65 3.93 0.6 10.0
pair_write 1 1 1000 rsq 0.1 10.0 morse-soft.dat morse_100_10_3_0.6


pair_style lj/cut 10.0
pair_coeff 1 1 100.0 3.5 10.0
pair_write 1 1 1000 rsq 0.1 10.0 lj.dat lj_100_3.5


pair_style lj/cut/soft 2 0.5 10.0
pair_coeff 1 1 100.0 3.5 1.0 10.0
pair_write 1 1 1000 rsq 0.1 10.0 lj-soft.dat lj_100_3.5_1.0

pair_coeff 1 1 100.0 3.5 0.8 10.0
pair_write 1 1 1000 rsq 0.1 10.0 lj-soft.dat lj_100_3.5_0.8

pair_coeff 1 1 100.0 3.5 0.6 10.0
pair_write 1 1 1000 rsq 0.1 10.0 lj-soft.dat lj_100_3.5_0.6
```

**Comment by Pakketeretet2** [comment]
You are completely right. I have made an error in the derivation of the force formula _and_ I apparently did not replace the alpha from the smoothing formula (which name-clashes with the parameter alpha from the Morse potential) with the scale variable. I will fix it as soon as I have time, sorry.

I only added the Morse files, but I will look into the LJ ones as well, if those are indeed the ones that miss the parameter alpha.

**Comment by akohlmey** [comment]
pair style lj/cut/soft has nlambda and alphalj. lj/cut/coul/long/soft and lj/cut/coul/cut/soft have alphalj and alphac. so the logical name for the equivalent morse parameter would be alpham. the doc/pair_lj_soft.txt also makes recommendations for "good" values of alpha (0.5 for LJ and 10.0 for coulomb). also, i noticed that there is one location where there is a division by "r". since r == 0.0 is valid for soft core potentials, this needs to be properly caught and handled.

**Comment by Pakketeretet2** [comment]
Yes, makes sense. Thanks for the heads-up.

**Pull request merged**
