### PR TITLE
Optimize KOKKOS package for small systems

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

This PR adds several optimizations to the KOKKOS package for small systems when running on GPUs
- an option to thread over neighbors in addition to threading over atoms
- fused forward communication pack/unpack that reduces the number of CUDA kernel launches when running on a single MPI rank
- many other small optimizations

**Author(s)**

Stan Moore (Sandia)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@akohlmey this PR need to be merged after #1364, and actually includes the changes in #1364 to avoid merge conflicts. Is there a better way to signify an order dependency of PRs, or should I just wait to assign this PR to you until after that other PR is merged?

**Comment by akohlmey** [comment]
> @akohlmey this PR need to be merged after #1364, and actually includes the changes in #1364 to avoid merge conflicts. Is there a better way to signify an order dependency of PRs, or should I just wait to assign this PR to you until after that other PR is merged?

assigning it to me only after all prerequisites are included is the easiest way.
another option is to close $1364 with a suitable comment added to both pull requests
or un-assign me from #1364 and put the text "closes #1364" (w/o quotes) into the pull request summary.

**Comment by stanmoore1** [comment]
I'm done coding, running regression and performance tests now.

**Comment by stanmoore1** [comment]
For 1000 Lennard-Jones atoms, I'm seeing a little over 2x speedup on a single V100 GPU from this PR.

**Comment by stanmoore1** [comment]
Some regression tests are still failing with this PR, looking into this.

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
