### PR TITLE
Linkage mode improvements and documentation updates for USER-PLUMED package

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Added some links missing for the new USER-PLUMED package to the doc pages.
Also implemented all three linkage modes for both, conventional build and cmake build, using a pre-installed plumed or downloading/compiling it on-the-fly inside the build folder.

## Author(s)

Steve Plimpton (SNL) 
Axel Kohlmeyer (Temple U)

## Backward Compatibility

LAMMPS: yes, Plumed: only tested on Linux and with Plumed-2.4.3

## Implementation Notes

So far, it seems to be possible to have an interface without copying code from plumed to LAMMPS and by only include Plumed.h and setting a define or two.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey There is a also a blank CMake section for user-plumed on the Build_extras.txt doc
page.  It should either say "no additional settings needed" or list relevant CMake variables
that were added.

**Comment by akohlmey** [comment]
@sjplimp Actually, most of these instructions are not applicable at the moment (they didn't work with the original patch either, which was very inconsistent in that regard and only worked by chance) and I disagree with the recommendation.
Right now, the only supported linkage mode is static linkage, and for that it is most convenient (and i would recommend) to use the automatic download and internal build of plumed via `make lib-plumed args=-b` or `cd lib/plumed; python Install.py -b`

Other linkage modes require modifications to Install.py and a different Makefile.lammps template to use different preprocessor directives. Of course making this all work with CMake it is an even bigger challenge. However, the current CMake setup should work transparently with a correctly pre-installed Plumed package. Hence my suggestions to the mailing list to use the conventional build if you don't have  Plumed installed already and use CMake if you have. Regardless of the build system, you'll currently always get static linkage of Plumed into LAMMPS, so the resulting executable should be unaffected by any changes/updates to the installed Plumed library.

**Comment by sjplimp** [comment]
@akohlmey this is all fine.  But the CMake section of the Build_extras.txt doc page should say something.  And your suggestions about CMake vs make should be there somewhere also.
Maybe the CMake section should say: "CMake should work with no additional settings with a correctly pre-installed Plumed package. (meaning it is installed somewhere CMake can find it?)"

**Comment by akohlmey** [comment]
@sjplimp please check out the update build instructions. Please let me know, if there is something missing or too confusing. Since you come "from the outside" to this, your perspective is very valuable.

@gtribello please have a quick look if this catches everything. If changed the bias a little bit towards recommending a static linkage, as this will be more likely to work with people that have less experience in building executables and installing libraries. LAMMPS has a lot of these users. Power users will know what suits them best anyway.

No worries, if this PR is getting merged before it is perfect, we still have a couple of weeks until the stable release, which is the point in time, where this part of the docs should be rock-solid.

**Comment by akohlmey** [comment]
@junghans i've tried all permutations of download yes/no, linkage static/shared/runtime on my Linux box at home and with the changes here got it to work in all cases. There was a dependency on BLAS/LAPACK missing. Haven't tried non-Linux systems yet or the Linux-to-Windows cross-compiler. Please let us know, if you see something that is wrong or flawed in your opinion. Thanks.

**Comment by sjplimp** [comment]
@akohlmey yes, new doc info in Build_extra.txt looks great - thanks

**Pull request merged**
