### PR TITLE
Update reaxff_ffield.cpp

### PR DESCRIPTION
**Pull request by fenggo**
BUG fixes: four-body interaction j-k-l-m and j-l-k-m shares the same value

**Summary**

**Related Issue(s)**

**Author(s)**

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by stanmoore1** [comment]
@fenggo can you comment more on this PR, was there an actual bug fixed, or just code cleanup??

**Comment by fenggo** [comment]
> 
I have impliment my ReaxFF-nn model to GULP package, and I found that in GULP the torsion angle like H-C-N-N use the same variable as H-N-C-N, I have look up the parameter files in LAMMPS potential directory, for example, "ffield.reax.lg":
25    ! Nr of torsions;at1;at2;at3;at4;;V1;V2;V3;V2(BO);vconj;n.u;n
  1  1  1  1   0.0000  48.4194   0.3163  -8.6506  -1.7255   0.0000   0.0000
  1  1  1  2   0.0000  63.3484   0.2210  -8.8401  -1.8081   0.0000   0.0000
  2  1  1  2   0.0000  45.2741   0.4171  -6.9800  -1.2359   0.0000   0.0000
  0  1  2  0   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
  0  2  2  0   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
  0  1  3  0   1.7254  86.0769   0.3440  -4.2330  -2.0000   0.0000   0.0000
  0  2  3  0   0.0000   0.1000   0.0200  -2.5415   0.0000   0.0000   0.0000
  0  3  3  0   1.2314 116.5137   0.5599  -4.1412   0.0000   0.0000   0.0000
  0  1  4  0  -1.3258 149.8644   0.4790  -7.1541  -2.0000   0.0000   0.0000
  0  2  4  0   0.0000   0.1000   0.0200  -2.5415   0.0000   0.0000   0.0000
  0  3  4  0   1.3168  57.0732   0.2679  -4.1516  -2.0000   0.0000   0.0000
  0  4  4  0   2.0000  75.3685  -0.7852  -9.0000  -2.0000   0.0000   0.0000
  0  1  1  0   0.0930  18.6070  -1.3191  -9.0000  -1.0000   0.0000   0.0000
  4  1  4  4  -2.0000  20.6655  -1.5000  -9.0000  -2.0000   0.0000   0.0000
  1  1  3  3   1.2707  21.6200   1.5000  -9.0000  -2.0000   0.0000   0.0000
  1  3  3  1  -1.8804  79.9255  -1.5000  -4.1940  -2.0000   0.0000   0.0000
  3  1  3  3  -2.0000  22.5092   1.5000  -8.9500  -2.0000   0.0000   0.0000
  1  4  4  3   0.1040  70.1152   0.5284  -3.5026  -2.0000   0.0000   0.0000
  1  1  3  4   1.2181 119.6186  -1.5000  -7.0635  -2.0000   0.0000   0.0000
  2  1  3  4  -2.0000 156.6604   1.1004  -7.3729  -2.0000   0.0000   0.0000
  1  3  4  3   2.0000  96.6281  -1.5000  -3.8076  -2.0000   0.0000   0.0000
  1  1  4  2  -2.0000 147.2445  -1.5000  -7.0142  -2.0000   0.0000   0.0000
  1  1  4  3  -2.0000  47.8326  -1.5000  -9.0000  -2.0000   0.0000   0.0000
  2  3  4  3  -0.2997 152.9040  -1.5000  -4.4564  -2.0000   0.0000   0.0000
  2  4  4  3   0.1040  70.1152   0.5284  -3.5026  -2.0000   0.0000   0.0000

In the file, it have "2  1  3  4" but no "2 3 1 4" vairable, and they should use the same value, however, it cause problems, torsion variable "0 1 3 0" is present, it will use this variable instead.

 The "2 3 1 4" torsion angle will use the value of torsion variable "2  1  3  4" or  "0  1  3  0"?
In the GULP case it will use  "2  1  3  4", and in current lammps ReaxFF it will use the value of "0  1  3 0".

I guess the logic of ReaxFF is they treat "1-3" and "3-1" as the same, since their bond-order value is the same, atom "2" and "4" bonded to the same bond "1-3", whether they are "1-3" or "3-1".

**Comment by athomps** [comment]
@fenggo The gold standard for issues like this is not GULP but ReaxFF.  Looking at the ReaxFF parameterizations that we provide with LAMMPS, I see multiple examples where the GULP convention is not respected e.g. ffield.reax.FC
```
  1  1  3  2  -1.4358  36.7830  -1.0000  -8.1821  -1.0000   0.0000   0.0000
  2  1  3  1  -1.3959  34.5053   0.7200  -2.5714  -2.1641   0.0000   0.0000
``` 
Adopting your PR would break those examples.  I suggest instead that you continue using the existing LAMMPS code.  You can still reproduce the GULP convention by explicitly adding duplicate entries in the ReaxFF parameter file e.g.
```
2 1 3 4 -2.0000 156.6604 1.1004 -7.3729 -2.0000 0.0000 0.0000
4 1 3 2 -2.0000 156.6604 1.1004 -7.3729 -2.0000 0.0000 0.0000
```
Let me know if this is acceptable, so we can close the PR.

**Review by athomps — COMMENTED** [review]
I recommend that this PR be withdrawn.

**Comment by stanmoore1** [comment]
This PR also causes one or more ReaxFF unit tests to fail, so I think @athomps's concerns are valid.

**Pull request closed without merging**
