### PR TITLE
Recover Kokkos compilation

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

The Kokkos compile is currently broken due to changes to the parent `GridComm` class. The `gridcomm_kokkos.h` file depends on `fftdata_kokkos.h` which is only installed with the `KSPACE` package. This PR adds a requirement that the `KSPACE` package be installed to use `gridcomm_kokkos`. The long-term solution is to extract raw pointers from the views and pass those around as `void*` to support other use cases of the gridcomm class (outside the scope of this PR).

**Related Issue(s)**

None

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
@akohlmey does this need a change for CMake?

**Comment by junghans** [comment]
@snikolov3 had some problems with the install in #2751, but I am not sure if he used kokkos there.

**Comment by akohlmey** [comment]
> @akohlmey does this need a change for CMake?

I'll check it out and will update the PR, if needed.

**Comment by akohlmey** [comment]
> @snikolov3 had some problems with the install in #2751, but I am not sure if he used kokkos there.

That was a completely different issue. Having a "sanitized" and "installable" set of LAMMPS headers (that will live in a "include/lammps" folder and be included with "lammps/some_name.h") is a goal for the next development cycle. How to deal with fmtlib in that case has yet to be figured out. We'll probably need a define that indicates that we are compiling LAMMPS itself and not using the headers for using the C++ interface in a different code. For now, the only clean way to do this is to not "install" LAMMPS but use it in place.

**Comment by snikolov3** [comment]
Yea Axel is correct. In my case, I did use Kokkos, but I was using Lammps
in another code which had trouble finding the fmtlib header files.

**Comment by akohlmey** [comment]
> > @akohlmey does this need a change for CMake?
> 
> I'll check it out and will update the PR, if needed.

That was already pre-empted. As it stands, `fft3d_kokkos.cpp`, `gridcomm_kokkos.cpp` and `remap_kokkos.cpp` are only compiled if the KSPACE package is enabled. The logic in CMake is a bit different.
Fortunately in this case.

**Comment by stanmoore1** [comment]
>As it stands, fft3d_kokkos.cpp, gridcomm_kokkos.cpp and remap_kokkos.cpp are only compiled if the KSPACE package is enabled. The logic in CMake is a bit different.

Great thank you for checking.

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
