### PR TITLE
Reorganization of the programming guide

### PR DESCRIPTION
**Pull request by jtclemm**
**Summary**

Based on discussion with Axel, I took a stab at reorganizing the intro to the programming guide. The driving motivation was to reduce redundancy, improve organization, and provide more cross-references to make it easier to digest. Hopefully, this will help readers find relevant information. 

**Author(s)**

Joel Clemmer (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

### CODE REVIEW

**Comment by jtclemm** [comment]
@akohlmey I tested out some initial reorganization of the text, although there is still a lot to be done. Please let me know what thoughts you have (good, bad, etc.) and maybe we can iterate or pivot.

Note that I reassigned some ambiguous labels (strongly preferred, mostly strict, suggested) to strict, preferred, or optional to keep things consistent, a very debatable change.

**Comment by akohlmey** [comment]
@jtclemm This looks fine to me, so far. I had to do some "technical fixups" with sphinx syntax, a duplicate reference label, and spelling.

I also made a few small edits in the hope of clarifying a few details.

I think at this point it would be a good idea for @sjplimp to look this over and give his notes.

**Comment by sjplimp** [comment]
@jtclemm @akohlmey I read thru all the doc files in this PR and think they all read well.  Thanks for working on this.  I made a few minor edits for clarity.

**Comment by akohlmey** [comment]
@jtclemm I think we should merge this now and put additional changes in a new pull request.

**Comment by jtclemm** [comment]
> @jtclemm I think we should merge this now and put additional changes in a new pull request.

Sounds good to me. Thanks!

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
