### PR TITLE
Patch of class2 dihedral

### PR DESCRIPTION
**Pull request by LucienPan0903**
Fix the NAN problem when any two bonds are nearly parallel

**Summary**

When any two bonds of the dihedral are nearly parallel, the costh12 costh13 costh23 will exceed the limit of [-1,1] slightly because of cut-off error, leading  acos(costh12), acos(costh13) or acos(costh23) to be NAN.

**Related Issues**

_If this addresses an open GitHub issue for this project, please mention the issue number here, and describe the relation. Use the phrases `fixes #221` or `closes #135`, when you want an issue to be automatically closed when the pull request is merged_

**Author(s)**

Lucien Pan

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This fix is backward compatibility

**Implementation Notes**

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@LucienPan0903 this pull request cannot be merged in the current form since it reverts changes to the master branch that were merged recently. Please correct it so that it only contains the changes that you intend to be added.

**Comment by LucienPan0903** [comment]
Hi Akohlmey, I have correct the file.

**Comment by akohlmey** [comment]
> Hi Akohlmey, I have correct the file.

Sorry, but not yet completely. There are still differences in whitespace: you are now deleting empty lines an have no EOL character at the end of the file.

**Comment by LucienPan0903** [comment]
Fixed now. Thank you!

**Comment by akohlmey** [comment]
> Fixed now. Thank you!

Great. Much appreciated.

**Pull request merged**
