### PR TITLE
Remove suffix from style names when writing restart files

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

By removing the style suffix from style names when writing binary restarts, the resulting restart file should be readable with suffixes enabled or without. This also includes some minor changes to the restart procedure to better match stored restart data from fixes.

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

For restarts written prior to this change, the same accelerator/suffix must be enabled to read the restart.
This is the old behavior and thus this change should not introduce any compatibility problems.
Behavior of restarting without a suffix of with a different suffix from a restart written with suffixes remove has not be fully verified.

**Implementation Notes**

This introduces a new utility function `utils::strip_style_suffix()` providing a string operation needed by this change multiple times.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by stanmoore1** [comment]
There seems to be some issues with Kokkos writing out a slightly different restart format, need to check this.

**Comment by stanmoore1** [comment]
This should work correctly for Kokkos with #3555, but I need to confirm.

**Comment by akohlmey** [comment]
@stanmoore1 I am seeing an improvement. I can restart a non-KOKKOS run from either a KOKKOS or a non-KOKKOS restart file. However, a KOKKOS run fails on restart consistently with:
```
LAMMPS (3 Nov 2022)
KOKKOS mode is enabled (src/KOKKOS/kokkos.cpp:106)
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
  In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
  For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
  For unit testing set OMP_PROC_BIND=false
  using 4 OpenMP thread(s) per MPI task
Reading restart file ...
  restart file = 3 Nov 2022, LAMMPS = 3 Nov 2022
==2030121== Invalid free() / delete / delete[] / realloc()
==2030121==    at 0x48480E4: free (vg_replace_malloc.c:872)
==2030121==    by 0x50BB667: destroy<long int> (memory.h:200)
==2030121==    by 0x50BB667: LAMMPS_NS::AtomVec::~AtomVec() (atom_vec.cpp:110)
==2030121==    by 0x64687B2: virtual thunk to LAMMPS_NS::AtomVecFullKokkos::~AtomVecFullKokkos() (atom_vec_full_kokkos.h:31)
==2030121==    by 0x50A01AD: LAMMPS_NS::Atom::create_avec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**, int) (atom.cpp:661)
==2030121==    by 0x543E256: LAMMPS_NS::ReadRestart::header() (read_restart.cpp:770)
==2030121==    by 0x543F6F7: LAMMPS_NS::ReadRestart::command(int, char**) (read_restart.cpp:129)
==2030121==    by 0x52EA13E: LAMMPS_NS::Input::execute_command() (input.cpp:852)
==2030121==    by 0x52EA85D: LAMMPS_NS::Input::file() (input.cpp:302)
==2030121==    by 0x4012FD: main (main.cpp:76)
==2030121==  Address 0x175b1100 is 176 bytes inside a block of size 208 alloc'd
==2030121==    at 0x484586F: malloc (vg_replace_malloc.c:381)
==2030121==    by 0x75DCFCB: Kokkos::HostSpace::impl_allocate(char const*, unsigned long, unsigned long, Kokkos_Profiling_SpaceHandle) const (Kokkos_HostSpace.cpp:153)
==2030121==    by 0x75DD224: Kokkos::HostSpace::allocate(char const*, unsigned long, unsigned long) const (Kokkos_HostSpace.cpp:128)
==2030121==    by 0x54815FC: Kokkos::Impl::SharedAllocationHeader* Kokkos::Impl::checked_allocation_with_header<Kokkos::HostSpace>(Kokkos::HostSpace const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) (Kokkos_MemorySpace.hpp:72)
==2030121==    by 0x75DD614: Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, void>::SharedAllocationRecord(Kokkos::HostSpace const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(Kokkos::Impl::SharedAllocationRecord<void, void>*)) (Kokkos_HostSpace.cpp:312)
==2030121==    by 0x64661D7: SharedAllocationRecord (Kokkos_SharedAlloc.hpp:328)
==2030121==    by 0x64661D7: allocate (Kokkos_SharedAlloc.hpp:343)
==2030121==    by 0x64661D7: allocate_shared<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::integral_constant<unsigned int, 0>, Kokkos::HostSpace, Kokkos::OpenMP> (Kokkos_ViewMapping.hpp:3459)
==2030121==    by 0x64661D7: View<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (Kokkos_View.hpp:1483)
==2030121==    by 0x64661D7: View<std::__cxx11::basic_string<char> > (Kokkos_View.hpp:1591)
==2030121==    by 0x64661D7: DualView (Kokkos_DualView.hpp:242)
==2030121==    by 0x64661D7: create_kokkos<Kokkos::DualView<double*, Kokkos::LayoutRight, Kokkos::OpenMP> > (memory_kokkos.h:41)
==2030121==    by 0x64661D7: grow_kokkos<Kokkos::DualView<double*, Kokkos::LayoutRight, Kokkos::OpenMP> > (memory_kokkos.h:76)
==2030121==    by 0x64661D7: LAMMPS_NS::AtomVecFullKokkos::grow(int) (atom_vec_full_kokkos.cpp:64)
==2030121==    by 0x50A020E: LAMMPS_NS::Atom::create_avec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**, int) (atom.cpp:678)
==2030121==    by 0x52E3646: LAMMPS_NS::Input::atom_style() (input.cpp:1367)
==2030121==    by 0x52EA2E0: LAMMPS_NS::Input::execute_command() (input.cpp:771)
==2030121==    by 0x52EA85D: LAMMPS_NS::Input::file() (input.cpp:302)
==2030121==    by 0x4012FD: main (main.cpp:76)
==2030121== 
==2030121== Invalid free() / delete / delete[] / realloc()
==2030121==    at 0x48480E4: free (vg_replace_malloc.c:872)
==2030121==    by 0x50BB657: destroy<long int> (memory.h:199)
==2030121==    by 0x50BB657: LAMMPS_NS::AtomVec::~AtomVec() (atom_vec.cpp:110)
==2030121==    by 0x64687B2: virtual thunk to LAMMPS_NS::AtomVecFullKokkos::~AtomVecFullKokkos() (atom_vec_full_kokkos.h:31)
==2030121==    by 0x50A01AD: LAMMPS_NS::Atom::create_avec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**, int) (atom.cpp:661)
==2030121==    by 0x543E256: LAMMPS_NS::ReadRestart::header() (read_restart.cpp:770)
==2030121==    by 0x543F6F7: LAMMPS_NS::ReadRestart::command(int, char**) (read_restart.cpp:129)
==2030121==    by 0x52EA13E: LAMMPS_NS::Input::execute_command() (input.cpp:852)
==2030121==    by 0x52EA85D: LAMMPS_NS::Input::file() (input.cpp:302)
==2030121==    by 0x4012FD: main (main.cpp:76)
==2030121==  Address 0x175b2380 is 144 bytes inside a block of size 216 alloc'd
==2030121==    at 0x484586F: malloc (vg_replace_malloc.c:381)
==2030121==    by 0x75DCFCB: Kokkos::HostSpace::impl_allocate(char const*, unsigned long, unsigned long, Kokkos_Profiling_SpaceHandle) const (Kokkos_HostSpace.cpp:153)
==2030121==    by 0x75DD224: Kokkos::HostSpace::allocate(char const*, unsigned long, unsigned long) const (Kokkos_HostSpace.cpp:128)
==2030121==    by 0x54815FC: Kokkos::Impl::SharedAllocationHeader* Kokkos::Impl::checked_allocation_with_header<Kokkos::HostSpace>(Kokkos::HostSpace const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) (Kokkos_MemorySpace.hpp:72)
==2030121==    by 0x75DD614: Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, void>::SharedAllocationRecord(Kokkos::HostSpace const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, void (*)(Kokkos::Impl::SharedAllocationRecord<void, void>*)) (Kokkos_HostSpace.cpp:312)
==2030121==    by 0x5482598: SharedAllocationRecord (Kokkos_SharedAlloc.hpp:328)
==2030121==    by 0x5482598: allocate (Kokkos_SharedAlloc.hpp:343)
==2030121==    by 0x5482598: allocate_shared<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::integral_constant<unsigned int, 0>, Kokkos::HostSpace, Kokkos::OpenMP> (Kokkos_ViewMapping.hpp:3459)
==2030121==    by 0x5482598: View<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (Kokkos_View.hpp:1483)
==2030121==    by 0x5482598: View<std::__cxx11::basic_string<char> > (Kokkos_View.hpp:1591)
==2030121==    by 0x5482598: Kokkos::DualView<int**, Kokkos::LayoutRight, Kokkos::OpenMP, void>::DualView(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long) (Kokkos_DualView.hpp:242)
==2030121==    by 0x5489290: create_kokkos<Kokkos::DualView<int**, Kokkos::LayoutRight, Kokkos::OpenMP> > (memory_kokkos.h:173)
==2030121==    by 0x5489290: Kokkos::DualView<int**, Kokkos::LayoutRight, Kokkos::OpenMP, void> LAMMPS_NS::MemoryKokkos::grow_kokkos<Kokkos::DualView<int**, Kokkos::LayoutRight, Kokkos::OpenMP, void> >(Kokkos::DualView<int**, Kokkos::LayoutRight, Kokkos::OpenMP, void>&, Kokkos::DualView<int**, Kokkos::LayoutRight, Kokkos::OpenMP, void>::value_type**&, int, int, char const*) (memory_kokkos.h:275)
==2030121==    by 0x6464D34: LAMMPS_NS::AtomVecFullKokkos::grow(int) (atom_vec_full_kokkos.cpp:67)
==2030121==    by 0x50A020E: LAMMPS_NS::Atom::create_avec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**, int) (atom.cpp:678)
==2030121==    by 0x52E3646: LAMMPS_NS::Input::atom_style() (input.cpp:1367)
==2030121==    by 0x52EA2E0: LAMMPS_NS::Input::execute_command() (input.cpp:771)
==2030121==    by 0x52EA85D: LAMMPS_NS::Input::file() (input.cpp:302)
==2030121== 
```

Inputs are attached
[in.restart.txt](https://github.com/lammps/lammps/files/10231475/in.restart.txt)
[in.rhodo.txt](https://github.com/lammps/lammps/files/10231476/in.rhodo.txt)


```

**Comment by stanmoore1** [comment]
Thanks @akohlmey, could be a new bug from #3555. I'll take a look.

**Comment by stanmoore1** [comment]
@akohlmey should be fixed.

**Comment by akohlmey** [comment]
> @akohlmey should be fixed.

Thanks, the crash is gone. There are still some small but same discrepancies in thermodynamic data when restarting "across". So it seems something is still lost or mixed up. No idea where this is coming from, though.

**Comment by stanmoore1** [comment]
Weird, I'll take another look.

**Comment by akohlmey** [comment]
One more thing. May be related? There seems to be a memory leak in the KOKKOS version of fix shake.
Strangely, this is only reported for the "xshake" array. Others that are allocated and freed inadjacent lines are not reported.
```
==2042197== 786,432 bytes in 1 blocks are definitely lost in loss record 18 of 18
==2042197==    at 0x484A803: memalign (vg_replace_malloc.c:1516)
==2042197==    by 0x484A91F: posix_memalign (vg_replace_malloc.c:1688)
==2042197==    by 0x5351066: LAMMPS_NS::Memory::smalloc(long, char const*) (memory.cpp:58)
==2042197==    by 0x5CB17D2: create<double> (memory.h:138)
==2042197==    by 0x5CB17D2: LAMMPS_NS::FixShake::grow_arrays(int) (fix_shake.cpp:2851)
==2042197==    by 0x5CBCB9F: LAMMPS_NS::FixShake::FixShake(LAMMPS_NS::LAMMPS*, int, char**) (fix_shake.cpp:92)
==2042197==    by 0x6675CFB: LAMMPS_NS::FixShakeKokkos<Kokkos::OpenMP>::FixShakeKokkos(LAMMPS_NS::LAMMPS*, int, char**) (fix_shake_kokkos.cpp:53)
==2042197==    by 0x5365560: LAMMPS_NS::Fix* style_creator<LAMMPS_NS::Fix, LAMMPS_NS::FixShakeKokkos<Kokkos::OpenMP> >(LAMMPS_NS::LAMMPS*, int, char**) (modify.cpp:44)
==2042197==    by 0x5370BEB: LAMMPS_NS::Modify::add_fix(int, char**, int) (modify.cpp:886)
==2042197==    by 0x52EA3AE: LAMMPS_NS::Input::execute_command() (input.cpp:786)
==2042197==    by 0x52EA86D: LAMMPS_NS::Input::file() (input.cpp:302)
==2042197==    by 0x4012FD: main (main.cpp:76)
```

**Comment by stanmoore1** [comment]
So Rhodo benchmark uses NPT, which changes the volume. The KSpace grid depends on volume, but is only adjusted at the beginning of the run (during `setup`). I think that is the discrepancy here. Could hard code PPPM params and see if it goes away.

**Comment by akohlmey** [comment]
> So Rhodo benchmark uses NPT, which changes the volume. The KSpace grid depends on volume, but is only adjusted at the beginning of the run (during `setup`). I think that is the discrepancy here. Could hard code PPPM params and see if it goes away.

Actually, it looks that I overlooked a final write_restart command in in.restart and thus when using in.restart multiple times, it would not restart from the same data.

**Comment by akohlmey** [comment]
@stanmoore1 confirmed. This was my error. I can restart with fix nvt *and* fix npt and get identical thermodynamic data.

The fix shake/kk memory leak is unrelated.

**Comment by stanmoore1** [comment]
Fixed the memory leak. https://github.com/lammps/lammps/blob/develop/src/RIGID/fix_shake.cpp#L92: I think in general calling member functions from the constructor of a class is poor practice, since a virtual override can't be used in the constructor. This can lead to unexpected behavior if you aren't looking for that...

**Review by stanmoore1 — APPROVED** [review]
I approve. @akohlmey thanks for working on this

**Comment by akohlmey** [comment]
> I think in general calling member functions from the constructor of a class is poor practice, since a virtual override can't be used in the constructor.

I am well aware of that. This is why some time ago, I went through the entire code base and added explicit scope to those calls, so that people are more aware that this is not calling the corresponding virtual override.

Unfortunately, this is a legacy in LAMMPS that is next to impossible to get rid of. I suspect this goes back to when LAMMPS was in Fortran and construction and initialization was always explicit. We have similar problems with static code analysis because data is often not initialized in the constructor, but in some initialization function. Now *we* know that this function is always called, but analysis tools don't. Please see the attached PDF for an example.
[Coverity Scan - Project LAMMPS_ Overview.pdf](https://github.com/lammps/lammps/files/10232042/Coverity.Scan.-.Project.LAMMPS_.Overview.pdf)

**Pull request merged**
