### PR TITLE
Read data improve

### PR DESCRIPTION
**Pull request by valleymouth**
**Summary**

Currently, there is no easy way to implement custom sections and headers in the data file. This pull request address that by allowing a class to inherit from ReadData and override a set of virtual functions. 

**Related Issues**

No related issues.

**Author(s)**

Denis Taniguchi (denis.taniguchi@gmail.com) - Newcastle University

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No backward compatibility issue since there was no way to inherit from ReadData.

**Implementation Notes**

Besides changing ReadData members from private to protected and making its destructor virtual, 4 new methods were included.
```
  virtual void init_flags(int *);
  virtual bool parse_section(int, int *);
  virtual bool parse_header(int);
  virtual bool check_section(char *);
```
The functionality provided by these methods were already present in the original ReadData implementation. By taking them out from the original methods we allow the user to inherit from ReadData and override the new methods to introduce new sections and headers. The previous approach would be to copy all ReadData code to a new class and modify the section and header parse loop.
An example of header extension would be:
```
bool MyReadData::parse_header(int firstpass)
{
  int parsed = ReadData::parse_header(firstpass);
  if (strstr(line,"atom types")) {
    do_something();
  } else if (strstr(line,"new header")) {
    int num = 0;
    sscanf(line,"%d",&num);
    do_something_else(num);
  } else return parsed;
  return true;
}
```
The implementation was tested against a couple of examples in the lammps/examples folder.
An example of inheriting and extending ReadData is given in the attached file (probably not compilable).

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

[my_read_data.h.txt](https://github.com/lammps/lammps/files/3043748/my_read_data.h.txt)
[my_read_data.cpp.txt](https://github.com/lammps/lammps/files/3043749/my_read_data.cpp.txt)

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp this is one for you to look at first.
@valleymouth have you looked into how sections can be added to data files by fixes, e.g. fix cmap or fix property/atom?

**Comment by valleymouth** [comment]
@akohlmey Do you mean if I considered that to be an alternative to this pull request or if I did something to change the way sections are forwarded to fixes?

**Comment by akohlmey** [comment]
> @akohlmey Do you mean if I considered that to be an alternative to this pull request or if I did something to change the way sections are forwarded to fixes?

as an alternative.

to explain: changes to core functionality make me nervous (as they should), and the read_data  code is particularly complex and convoluted and the flow of control difficult to follow. ...and all this for a file format with significant design flaws. if i myself would want to implement support for a modified file format i would a) start this as a separate command from scratch and b) design/use a file format, that is self descriptive and structured. this could be based on something sophisticated as hdf5 (which can also be read in parallel and be used for restarts, too) or something widely used like JSON or XML (i don't like XML very much, because the syntax requires, that you always have to parse it completely and that you cannot skip ahead). i've tried what could be done to improve the situation by having comments, that provide additional information and can be used to do checks and print warnings, but this has reached the limit that can be done without breaking compatibility with legacy tools.

**Comment by valleymouth** [comment]
@akohlmey I understand your point. Maybe if I explain where this is coming from you could point me to a better way to do this. We use LAMMPS to microbial community simulations. There is a lot of input data related to how microbes (grow rate, chemical propeties, etc.) that previous developers decided to put inside the data file. Maybe they where induced by a few comments in read_data.cpp that says to modify here and there to add custom headers and sections. So what they did was to make a full copy of read_data.* and create a my_read_data.* with the modification to read microbial data. I totally agree that we should have used something better like hdf5, json, xml (I would choose json for the reasons you pointed out as well). Specially when you start considering the development of a pre-processor to setup the simulation case.
The intent here was to provide a way to maximise code reuse for users that decided to extend ReadData, without modifying LAMMPS functionalities. But I share your concern about modifying such a core class...

**Comment by akohlmey** [comment]
> The intent here was to provide a way to maximise code reuse for users that decided to extend ReadData, without modifying LAMMPS functionalities. But I share your concern about modifying such a core class...

let's wait for what @sjplimp has to say. since he designed and wrote most of this code. 

yes. there are these comments about how changes could be added. this usually goes along with new atom styles as well. over time, this became more complex and fix property/atom was specifically designed to offload and generalize some of this. that fix is using ideas from the LIGGGHTS fork for granular media simulations, where they needed to simplify the process of adding per-atom properties and wanted avoid having to write new atom styles all the time (and many permutations for different combinations of properties). the USER-DPD package, for example has adopted using fix property/atom to store specific per atom data (although not in a perfect way).

there is credit to either approach. it depends on how the data is used and how it needs to be handled with domain decomposition. if it is like potential parameters, it can be replicated and then adding this to a data file is complex and sometimes impractical (like *Coeff or Mass data), if it is data, that has to migrate with individual atoms and is modified and propagated, than extending read_data (and write_data??) may be the best way.

from your description, it could be that writing a custom fix (using a custom, e.g. JSON based, file format) is the more maintainable approach, as it decouples read_data and your specific type of simulation.

**Comment by Adrian-Diaz** [comment]
I'm having trouble seeing the functionality to actually perform the new read-ins when a novel keyword is encountered for a section; typically these are routines in read_data.cpp and atom.cpp that are called by read_data.cpp

**Comment by valleymouth** [comment]
@Adrian-Diaz The new sections must be implemented by the user in a new class inheriting from ReadData. An example is in the attached files: my_read_data.h.txt and my_read_data.cpp.txt. But before even going there I think the main developers must decide what the data file actually is. If it is not intended to be extended (customised), that should be clear it the comments, as is not today.

**Comment by akohlmey** [comment]
> @Adrian-Diaz The new sections must be implemented by the user in a new class inheriting from ReadData. An example is in the attached files: my_read_data.h.txt and my_read_data.cpp.txt. But before even going there I think the main developers must decide what the data file actually is. If it is not intended to be extended (customised), that should be clear it the comments, as is not today.

i should add to this, that one has to keep in mind that LAMMPS has been around a very long time, the "LAMMPS paper" is almost 25 years old. The SCM history of the C++ version goes back to 2005, the Fortran 90 version had a similar format and that went on for quite a while. over such a long period, design decisions can change, but comments in the code may not always reflect this and people may choose to keep them in there, even if this is not longer the preferred option. As LAMMPS has been growing quite rapidly in recent years, so have questions of maintainability of certain code constructs.

the monolithic data file format has its advantages, but i usually recommend people to split it in two pieces, and put only the system topology and geometry into the data file and have the force field style and coefficients in the input file or in a file included via the include keyword. that makes things easier to manage and edit (you can tell read_data to skip *Coeff sections when reading or write_data to skip writing those, and there is a write_coeff command that writes out the parameter info into a separate file in the syntax required for an input file.

as mentioned before, the lack of self-descriptive sections require that LAMMPS reads the data file multiple times and uses the information gathered in the first part for subsequent reads. that is suboptimal, and even worse is the fact, that the choice of atom_style and other settings can define how parts of the file are formatted, but you cannot easily infer those settings from the data file without a lot of guessing.

so ultimately, there are two questions to answer:
- do the LAMMPS (core) developers want to support that other people can write customized data file reader classes (and corresponding commands) that are derived from the ReadData class? This is this is a decision for @sjplimp to make, as he has the final word.
- is this approach, i.e. putting the additional information into the data file a good idea? or are there alternatives, that are a better match? or can what is required already be implemented by using existing functionality?

having a derived class is certainly preferred over modifying the code in read_data.cpp and read_data.h directly (which is where the comments referred to above are about). however, my personal preference has always been to stay away from that, and read in a separate file with the additional information. this keeps things simpler and it is easier to implement, but less convenient for the person to run simulations.
and the question i am raising is, that if somebody is about to invest some energy, would it be better to look into a complete new approach (and class) with a different file format, or stick with the old. i don't think there is an easy answer to this.

**Comment by Adrian-Diaz** [comment]
I'm of the opinion, as Axel mentioned before, that a very different read in style or format can just be done as a command class if for some reason the individual doesn't want to just add the header keywords to the control block and corresponding body read in routine in read_data.cpp. This is after all how read data is invoked from the input script and you might even be able to copy and relabel it as a different command to do what is of interest; in so doing also preventing any undo mayhem that may arise unintentionally.

**Comment by Adrian-Diaz** [comment]
I'm of the opinion that suggesting the package is a nice formality since the act of recognition provides more integration with the whole code if it is a package mismanagement. Definitely shouldn't spend time trying to identify close misspellings however since that's already the only possibility.

**Comment by sjplimp** [comment]
@valleymouth Just looking at this for the first time. I'm unclear on some hi-level motivations.  It looks like you want the ability to read additional header values, as well as sections.  My first Q is where are these values stored within LAMMPS once they are read?  For header values, it seems like it would be just as easy to not put them in the data file, but make your own command (e.g. microbial), that takes keyword/value(s), or a filename with a list of valuesin it.  For sections, what do you mean?  Are these per-atom values, or per-type values (like masses)?  Again where are they stored within LAMMPS and how does the user-added virtual class know where to store them?  Is it in some data structs that you've also added to atom.cpp ?  In which case, the mechanism you propose is not very self-contained.  Could you send us (me and Axel) some small examples of data files and input scripts that use this, and tell us where you want to store the microbial data within LAMMPS?

**Comment by akohlmey** [comment]
@valleymouth this has been sitting here waiting for your reaction. Please respond soon or we will close the pull request. The examples you provided with the PR are not pointing out any usefulness. We need to see what this modification enables in real use.

**Comment by valleymouth** [comment]
@akohlmey Apologies for the late reply. After refactoring our code, I don't think this PR is useful. The read_data fix is enough to provide flexibility. And if you need more than that it is probably a good idea to use your own XML/JSON file. So it was ok to close this anyway. Thanks.

**Pull request closed without merging**
