### PR TITLE
Fixing execution space issues in KOKKOS package

### PR DESCRIPTION
**Pull request by stanmoore1**
## Purpose

Fixing execution space issues in KOKKOS package. These changes are necessary for the kk/host suffix that will be documented soon.

## Author(s)

Stan Moore

## Backward Compatibility

No issues

## Implementation Notes

Will run through Kokkos regression tests

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by akohlmey** [comment]
@stanmoore1 is this required for any existing feature?
if not, can we wait with merging this until after the upcoming stable release?

**Comment by stanmoore1** [comment]
@akohlmey yes this can wait until after the stable release; it is for a currently undocumented feature. I also still have more changes to add, hence I haven't assigned to @sjplimp.

**Comment by akohlmey** [comment]
@stanmoore1 just a reminder. We're back in (normal development) business and the moratorium on merging non-critical changes over.

**Comment by stanmoore1** [comment]
Still a few corner cases that need to be fixed, but this is the bulk of the needed changes so I'm assigning to Steve to be merged, will revisit in the future when I get a chance

**Pull request merged**
