### PR TITLE
Add doxygen and graphviz processing into the documentation build

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

In preparation of the library interface refactoring and addition of a Programmer guide to the manual this PR updates the documentation build infrastructure to include doxygen and fortran file processing for extracting API information directly
from source code. This PR only adds the infrastructure but contains no updates to the manual itself.

This also adds an indication of the git status of the html documentation in preparation of having the master branch docs autogenerated by jenkins and uploaded to docs.lammps.org

**Related Issues**

#2257 
#1944 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

It may be required to do a "make clean-all" in the doc folder or re-run cmake in the build folder when BUILD_DOCS is enabled.

**Implementation Notes**

Previously there would be conflicts and timestamp collisions between building the documentation in the doc folder and via cmake or when using multiple cmake builds concurrently. this should now be resolved (albeit not very elegantly).

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] A package specific README file has been included or updated

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp @rbberger @junghans before I can start with integrating the contents from the progguide branch we need to make certain the build system for both the conventional and the cmake based manual build is able to handle the additional steps. That is LAMMPS source files need to be processed with doxygen and the output of that (selectively) integrated into the documentation. This is the first step of providing the infrastructure. Please test it and report any issues. This is a branch directly hosted in the LAMMPS project on GitHub (not my personal fork), so you can access and modify it more easily.

**Comment by akohlmey** [comment]
@rbberger FWIW, you may also want to look into the output folder of how the LAMMPS class graph image is created via graphviz. This is supposed to be an optional step to be used by people working on the documentation only and a current copy of the resulting image should be included in the distribution. The may be other graphs added in the future (e.g. to visualize the flow of control in certain parts of LAMMPS).

**Comment by rbberger** [comment]
@akohlmey I did an initial round of changes. In the end, I left the `configure_file` step for `conf.py`, since it's a simple and elegant solution to the problem. The majority of my changes are about reorganizing the copy operations. Many static files, images don't have to be explicitly copied if put into the right place. Note the current CMake build is missing files that are referenced via relative links (JPG/*, PDF/*). Currently, the Makefile does some hackery for this. This can be avoided by using 
```
:download:`pdf <doc/mypdf.pdf>`
```
and automatically scaled images.

**Comment by rbberger** [comment]
After looking at what the `:download:` role does, I don't see us adapting it because it creates some really ugly URLs. E.g., `_downloads/308e5851e833f44fc5430be478c1cf19/SMD_LAMMPS_userguide.pdf` instead of `PDF/SMD_LAMMPS_userguide.pdf`. So I'll fixup the CMake build and just copy of the PDF folder.

**Comment by rbberger** [comment]
@junghans ok, I'm done with my initial pass. Can you please take a look at the CMake changes?

**Comment by akohlmey** [comment]
Updated to current master and fixed a few minor issues that caused 3 unit tests to fail on the jenkins server.

**Pull request merged**
