### PR TITLE
unit tests for few LJ derivatives and ZBL

### PR DESCRIPTION
**Pull request by abhiShandy**
**Summary**

Unit tests with bugs for 5 pair-styles

- [x] LJ/cubic: Non-numeric atom coordinates - simulation unstable
- [x] LJ/expand: Bond atoms are missing
- [ ] LJ/cut/coul/dsf: Single method not available
- [x] LJ/cut/coul/wolf: Errors are very high
- [ ] zbl: Incorrect args for pair coefficient

**Related Issues**

#2099 

**Author(s)**

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

- Params for LJ derivatives are same as that of LJ/cut
- Params for ZBL are atomic numbers of respective atom types in Fourmol template (C, N, He, O, O)

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
lj/cubic is fixed and passes my test. There were multiple issues.
lj/cut/coul/wolf also had an initialization issue. This is fixed, too.
lj/expand needed some tweaking of the parameters to reduce the forces (basically when adding delta, sigma needs to be reduced by the same amount or a bit more. otherwise it "inflates" the atoms too much)

**Comment by akohlmey** [comment]
pair style zbl was not writing the data file correctly.
I don't see any issue with lj/cut/coul/dsf. It explicitly advertises that it has not single function (see `single_enable = 0;` in the constructor). Both coul/dsf and coul/wolf are closely related and compute a "global" term for the whole system before computing pairwise interactions. This is not well defined for the single function (it is effectively a manybody term) and thus the tester will skip the "single" section, if the pair style is signals it has no single function.

**Comment by akohlmey** [comment]
@abhiShandy if you don't mind, I will now merge this branch into PR #2267 to make it simpler for the colleagues reviewing the PRs.

**Comment by abhiShandy** [comment]
Thanks for the fixing the bugs. I have a lot to learn. I'll close this PR since it's merged with 2267

**Comment by akohlmey** [comment]
> Thanks for the fixing the bugs. I have a lot to learn. I'll close this PR since it's merged with 2267

Don't worry about about not fixing the bugs. This division of work is extremely effective. You do the time consuming parts, and for the most part it works well. And I can focus on the parts where my experience helps the most. It usually takes me only a small fraction of the time than it would take less experienced people to identify and correct the bugs. In most cases they are similar to other bugs that I have fixed in the past.

**Pull request closed without merging**
