### PR TITLE
Collected small KOKKOS changes

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request combine multiple, mostly cosmetic changes to the KOKKOS package that avoid compiler warnings and remove dead code.

**Related Issue(s)**

N/A

**Author(s)**

Axel Kohlmeyer, Temple U and Stan Moore, SNL, with a little help from the Kokkos developers

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known problems.

**Implementation Notes**

This addresses the following kinds of warnings:
- unused variable
- unused parameter
- signed vs. unsigned comparison
- reordered initialization of class members

For the linesearch update the equivalent change is also applied to the base version.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@stanmoore1 attached are the deprecation warning from the Kokkos library I had mentioned and some other warnings I don't know what to make of
[kokkos-warnings.txt](https://github.com/lammps/lammps/files/13890777/kokkos-warnings.txt)

Those warnings also show up in a few other parts of LAMMPS, mostly rarely used stuff that is quite old.

**Comment by stanmoore1** [comment]
Thanks @akohlmey! Running this through Kokkos regression testing now.

**Comment by stanmoore1** [comment]
> @stanmoore1 attached are the deprecation warning from the Kokkos library I had mentioned and some other warnings I don't know what to make of [kokkos-warnings.txt](https://github.com/lammps/lammps/files/13890777/kokkos-warnings.txt)
> 
> Those warnings also show up in a few other parts of LAMMPS, mostly rarely used stuff that is quite old.

OK I will take a look.

**Comment by stanmoore1** [comment]
@akohlmey I fixed all the warnings I saw. Running through regression testing now.

**Comment by stanmoore1** [comment]
Kokkos regression tests passed, this is ready to merge from my POV.

**Review by stanmoore1 — APPROVED** [review]

**Comment by akohlmey** [comment]
> @akohlmey I fixed all the warnings I saw. Running through regression testing now.

Thanks. I don't see any new warnings with GCC 13, but some more with CLang 17 indicating unused variables and function parameters. Will push commits now.

**Comment by stanmoore1** [comment]
Thanks!

**Comment by stanmoore1** [comment]
Are you planning to report b5aa04c to the upstream Kokkos repo? I try to keep the bundled version in sync with Kokkos Github as much as possible.

**Comment by akohlmey** [comment]
@stanmoore1 do you want to give this PR branch one more check, or can I merge it?

**Comment by stanmoore1** [comment]
I looked over all the new changes and everything seems reasonable, so please go ahead and merge. When you merge it will trigger another round of regression testing and I'll make sure it passes.

**Pull request merged**
