### PR TITLE
remove fftw_cleanup() from main()

### PR DESCRIPTION
**Pull request by junghans**
**Summary**

This bothered me for a while that the consumer needs to know about the fftw dep. This change make the lib interface a bit cleaner. The code could put `LAMMPS::cleanup()`  into `LAMMPS::~LAMMPS()`, but maybe the user only wants to call it once.

**Related Issues**

**Author(s)**

@junghans 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No, new library function.

**Implementation Notes**

Only code moves, no new code.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
I don't see a need to add a new member function for this, it can just go into the destructor. But it needs some additional care. Calling `fftw_cleanup()` impacts global static data, so it will render existing plans useless. That would be a problem when somebody creates multiple LAMMPS instances in the same process, so there also has to be an "instance counter" static variable added to the LAMMPS class that gets incremented in each constructor and decremented in each destructor and then calls `fftw_cleanup()`  only if the last active LAMMPS instance for the process is deleted. To avoid this is the reason why the call had been in the main.cpp function and mainly it was only added to avoid valgrind reporting a small but hard to find memory leak. So if we change this, we need to change it without causing problems and it should be self contained.

**Comment by sjplimp** [comment]
I don't know the details of how FFTW is structured as a lib, but
I'm not clear on why anything about FFTW should be at the
top level of LAMMPS.  Whether LAMMPS is compiled with
FFTW support or not, a user will only use FFTW if kspace_style pppm
is invoked.  And once that style is destroyed, e.g. by
invoking a new Kspace style, it seems like FFTW should
go away completely.  So why is this not in the destructor
of PPPM or the parent Kspace class?  That could happen
multiple times in an input script, e.g. PPPM is created, then
destroyed.

**Comment by akohlmey** [comment]
> So why is this not in the destructor
> of PPPM or the parent Kspace class? That could happen
> multiple times in an input script, e.g. PPPM is created, then
> destroyed.

The secret is in the documentation of `fftw_cleanup()`. This is cleaning up **static** **global** "wisdom" data, that gets incrementally updated and never deleted unless you explicitly delete.
But since this is not associated with the state of individual plans, you may only safely call this function, when there is no other plan in the same address space active (e.g. in a different LAMMPS instance). The purpose is keep us from chasing a (bogus) memory leak. We had the same discussion when I proposed this change many, many years ago, BTW.

**Comment by junghans** [comment]
We could also make it non-class function and name it something like `lammps_global_cleanup()` to make it more clear, that would also allow to call it at the very end of `main()` even after `delete lammps`.

**Comment by akohlmey** [comment]
> We could also make it non-class function and name it something like `lammps_global_cleanup()` to make it more clear, that would also allow to call it at the very end of `main()` even after `delete lammps`.

The more i think about this now, the more I am leaning towards just removing the call to fftw_cleanup() in main.cpp altogether and be done with it. Instead I would just add a suppression to my valgrind installation to keep me from chasing this specific leak again (and perhaps make my suppression files available). There are several other similar cases that have popped up since, e.g. from OpenMP runtime libraries, and I have become more competent in writing such suppression files, too.
Tracking LAMMPS instances is not enough if somebody uses LAMMPS as a library, but also uses FFTs from FFTW somewhere else directly. Calling `fftw_cleanup()` in that case can mess things up badly without the person easily knowing were it is coming from. The little convenience is not worth adding a global function or a new class member.

**Comment by junghans** [comment]
Your call I am happy as long as we can make fftw a private dep.

**Comment by akohlmey** [comment]
> Your call I am happy as long as we can make fftw a private dep.

yes, just take that call out of main.cpp.

**Pull request merged**
