### PR TITLE
Porting to new default platform for AMD/HIP in ROCm 4.1

### PR DESCRIPTION
**Pull request by arghdos**
**Summary**

Fix for new default ROCm platform string ("amd" instead of the old "hcc").

**Author(s)**

Nicholas Curtis (AMD); arghdos@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

I tested this on the new ROCm 4.1 install, and didn't change anything on the older 4.0 ROCm version so it _should_ work there, but we'll probably want to verify.

**Implementation Notes**

Mostly just adding conditionals in make / cmake.  There was one spot in the code where we had a bare __HIP_PLATFORM_HCC__.

Additionally, updated the docs to reflect the new default.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [x] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

N/A

### CODE REVIEW

**Comment by rbberger** [comment]
@arghdos updated the container definitions. The only problem I found was with USER-PTM creating a linking error due to using sqrt in one of its headers.
```
/usr/bin/cmake -E cmake_link_script CMakeFiles/lmp.dir/link.txt --verbose=1
/usr/bin/hipcc  -O2 -g -DNDEBUG   CMakeFiles/lmp.dir/home/richard/GitHub/lammps/lammps/src/main.cpp.o  -o lmp  -Wl,-rpath,/usr/lib/x86_64-linux-gnu/hdf5/serial: liblammps.a /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libfftw3.so /usr/lib/x86_64-linux-gnu/libfftw3_omp.so /usr/lib/x86_64-linux-gnu/libpython3.8.so /usr/lib/x86_64-linux-gnu/libvoro++.so liblammps_colvars.a liblammps_lepton.a -ldl /usr/lib/x86_64-linux-gnu/libnetcdf.so /usr/lib/x86_64-linux-gnu/libnetcdf.so /usr/lib/x86_64-linux-gnu/libzstd.so -lm liblammps_poems.a liblammps_awpmd.a /usr/lib/x86_64-linux-gnu/libopenblas.so liblammps_h5md.a /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so /usr/lib/x86_64-linux-gnu/libpthread.so /usr/lib/x86_64-linux-gnu/libsz.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libdl.so -lm -lpthread liblammps_gpu.a liblammps_mpi_stubs.a 
/usr/bin/ld: liblammps.a(compute_ptm_atom.cpp.o): in function `_GLOBAL__sub_I_compute_ptm_atom.cpp':
/home/richard/GitHub/lammps/lammps/src/USER-PTM/ptm_constants.h:90: undefined reference to `_ZL4sqrtIiEN15__hip_enable_ifIXsr3std14numeric_limitsIT_EE10is_integerEdE4typeES1_'
/usr/bin/ld: /home/richard/GitHub/lammps/lammps/src/USER-PTM/ptm_constants.h:90: undefined reference to `_ZL4sqrtIiEN15__hip_enable_ifIXsr3std14numeric_limitsIT_EE10is_integerEdE4typeES1_'
/usr/bin/ld: /home/richard/GitHub/lammps/lammps/src/USER-PTM/ptm_constants.h:91: undefined reference to `_ZL4sqrtIiEN15__hip_enable_ifIXsr3std14numeric_limitsIT_EE10is_integerEdE4typeES1_'
/usr/bin/ld: /home/richard/GitHub/lammps/lammps/src/USER-PTM/ptm_constants.h:91: undefined reference to `_ZL4sqrtIiEN15__hip_enable_ifIXsr3std14numeric_limitsIT_EE10is_integerEdE4typeES1_'
/usr/bin/ld: /home/richard/GitHub/lammps/lammps/src/USER-PTM/ptm_constants.h:92: undefined reference to `_ZL4sqrtIiEN15__hip_enable_ifIXsr3std14numeric_limitsIT_EE10is_integerEdE4typeES1_'
/usr/bin/ld: liblammps.a(compute_ptm_atom.cpp.o):/home/richard/GitHub/lammps/lammps/src/USER-PTM/ptm_constants.h:92: more undefined references to `_ZL4sqrtIiEN15__hip_enable_ifIXsr3std14numeric_limitsIT_EE10is_integerEdE4typeES1_' follow
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```
There is an easy workaround for this, but you might want to show this to the `hipcc` folks if you know them. We should be getting a Radeon VII soon for testing.

**Comment by arghdos** [comment]
@rbberger -- yeah, it's probably just a missing overload or something.
I'll go take a look, and hand it off to the compiler folks as needed :)

**Review by akohlmey — APPROVED** [review]

**Comment by arghdos** [comment]
@rbberger -- strangely, I can't reproduce the USER-PTM build issue, on my local R7 box, when configured with:

>cmake -D PKG_GPU=on -D GPU_API=HIP -D HIP_ARCH=gfx906 -D CMAKE_CXX_COMPILER=hipcc ../cmake/

If you still see it on your end:

Was this on a specific image e.g., UB18 vs 20? (I'm on the latter).  
Can you run some quick diagnostics on the system, e.g.?

```
$ cat /opt/rocm/.info/version
4.1.0-26
$ dkms status
amdgpu, 4.1-26, 5.4.0-56-generic, x86_64: installed
```

There's some other things [here](https://github.com/amddcgpuce/rocmtechsupport/blob/master/rocm_techsupport.sh) that may be useful if I don't spot anything immediately obvious (and/or my configure line is right :))

**Comment by rbberger** [comment]
@arghdos what I did was build our Ubuntu 20.04 ROCm Singularity container and ran the following build script https://github.com/lammps/lammps-testing/blob/master/scripts/builds/cmake_gpu_hip_serial_bigbig_static.sh

**Comment by arghdos** [comment]
Thanks @rbberger -- taking a look now.  Had to change the HIP_PLATFORM export from hcc to amd, and I'm missing some dependencies, but I'm on it :)

**Comment by arghdos** [comment]
Ok, I can reproduce now -- looking into it.

**Comment by arghdos** [comment]
I'm able to work around it for the moment by changing these to, e.g.:

`sqrt(2)` - > `sqrt(2.)`

to avoid the missing overload.  IMO it's a bug in the HIP runtime, but ... trying to get a standalone repro.

**Comment by akohlmey** [comment]
> I'm able to work around it for the moment by changing these to, e.g.:
> 
> `sqrt(2)` - > `sqrt(2.)`
> 
> to avoid the missing overload. IMO it's a bug in the HIP runtime, but ... trying to get a standalone repro.

@arghdos we have changed this code in upstream to have all these constants pre-computed. This kind of issue with mismatched argument types have caused problems on and off with some (unusual) compilers, so it is safer for the base code to have those pre-computed and then use a preprocessor define to represent the meaning.

If there is nothing else that needs to be changed in this PR, we'll be merging it later today. Please let us know.

**Comment by arghdos** [comment]
Gotcha -- let me make sure I removed all of them, do a fresh build and check there's nothing else and I'll give you the all clear.

**Comment by arghdos** [comment]
Yeah, that did it -- @akohlmey, you're good to go.
For posterity, here's the diff of things I needed to change to get the script to compile:
[constant_patch.txt](https://github.com/lammps/lammps/files/6266733/constant_patch.txt)

**Pull request merged**
