### PR TITLE
Adding KOKKOS support for pair yukawa/colloid, fix efield and fix spring/self

### PR DESCRIPTION
**Pull request by ndtrung81**
**Summary**

This PR adds KOKKOS support for pair yukawa/colloid, fix efield and fix spring/self

**Related Issue(s)**

N/A

**Author(s)**

Trung Nguyen (U Chicago)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Should maintain backward compatiblity.

**Implementation Notes**

For fix efield/kk, there is an unresolved issue with unwrap if used in the overloaded operator() (which could have made the implementation more concise), instead of using lambda (as in the current implementation.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@ndtrung81 this needs updates to the documentation. For example, additional `.. index::` on the individual command pages and a "k" added in the `Commands_<type>.rst` overview pages.

**Comment by ndtrung81** [comment]
@stanmoore1 just a gentle nudge, if you have some time to review the PR.

**Comment by stanmoore1** [comment]
@ndtrung81 thanks will do

**Review by stanmoore1 — APPROVED** [review]
I approve

**Pull request merged**
