### PR TITLE
Add slideshow feature to LAMMPS GUI

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

Add a feature to LAMMPS GUI so that it will automatically display a slide show window of images created by dump image.  This is facilitated by making `DumpImage::write()` store the name of the current file it just wrote in the Thermo class so that it can be retrived by `lammps_last_thermo()` similar to the timestep or line number.

The syntax highlighting class was rewritten from scratch to be more robust and more consistent.

In addition, various small updates to the packaging of LAMMPS GUI binaries are included to make the packages more consistent across platforms.

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

When there are multiple dump image commands active in the same input, the behavior is undefined.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp habemus slideshow! Not a bad turnaround. :wink:
The best solution was in the end to have dump image class update the expanded filename after(!) the file was written.

You said you had some notes on the howto document. Can you either edit this branch or add your notes on GitHub?

**Review by sjplimp — APPROVED** [review]

**Comment by sjplimp** [comment]
nice work - I will wait to try it out after this PR is merged and becomes part of the exe for LAMMPS GUI

**Comment by sjplimp** [comment]
I now think this various current-state info would be better stored in a top-level Interactive class, rather than in Thermo -- could refactor that in a future PR

**Comment by akohlmey** [comment]
> I will wait to try it out after this PR is merged and becomes part of the exe for LAMMPS GUI

FYI, the binary packages that I am posting are directly built from the current pull request, so there is no need to wait for it to be merged. I just uploaded new packages with the latest features. There won't be new ones for the next two weeks while I am helping with an HPC workshop in Colombia.

**Pull request merged**
