### PR TITLE
Improved python interface

### PR DESCRIPTION
**Pull request by rbberger**
This introduces an alternative Python wrapper to LAMMPS. While it internally uses the existing low-level interface, it builds abstractions on top of it.

```python
from lammps import lammps, PyLammps, IPyLammps
lmp = lammps()

# wrap original lammps interface
L = PyLammps(lmp)

# OR use the iPython version for additional output capabilities
L = IPyLammps(lmp)
```

Using this a LAMMPS input script can be written as follows:

```python
# 3d Lennard-Jones melt

L.units("lj")
L.atom_style("atomic")
L.atom_modify("map array")

L.lattice("fcc", 0.8442)
L.region("box block", 0, 4, 0, 4, 0, 4)
L.create_box(1, "box")
L.create_atoms(1, "box")
L.mass(1, 1.0)

L.velocity("all create", 1.44, 87287, "loop geom")

L.pair_style("lj/cut", 2.5)
L.pair_coeff(1, 1, 1.0, 1.0, 2.5)

L.neighbor(0.3, "bin")
L.neigh_modify("delay 0 every 20 check no")

L.fix("1 all nve")

L.variable("fx atom fx")

L.run(10)
```
Note that LAMMPS commands become functions, while everything else can be passed as either one string, or individual parameters. Parameter lists are automatically joined to one command string during the function call. E.g.,

```python
L.velocity("all create", 1.44, 87287, "loop geom")
```
becomes
```python
lmp.command("velocity all create 1.44 87287 loop geom")
```
in the original interface.

It also gives you an easier way to query the system state, evaluate variable expressions and access atom data. See `examples/ipython/interface_usage.ipynb` for more details.

Finally the original code was reformatted to conform to PEP8.

### CODE REVIEW

**Comment by akohlmey** [comment]
LammpsWrapper is a bit long. How about PyLammps? or PyLAMMPS? ...and IPyLammps?

**Comment by rbberger** [comment]
Sounds reasonable. I'll also add the import from `__future__` so Travis is happy.

**Comment by akohlmey** [comment]
Looks like python2 support still needs some work. I just installed the python wrapper and got this with the first notebook (interface_usage):
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-f277999a9061> in <module>()
      5 L.atom_modify("map array")
      6 
----> 7 L.lattice("fcc", 0.8442)
      8 L.region("box block", 0, 4, 0, 4, 0, 4)
      9 L.create_box(1, "box")

/home/akohlmey/.local/lib/python2.7/site-packages/lammps.pyc in handler(*args, **kwargs)
    560       with OutputCapture() as capture:
    561         self.lmp.command(' '.join(cmd_args))
--> 562         output = capture.output
    563       lines = output.splitlines()
    564 

/home/akohlmey/.local/lib/python2.7/site-packages/lammps.pyc in output(self)
    308   @property
    309   def output(self):
--> 310     return self.read_pipe(self.stdout_pipe_read)
    311 
    312 

/home/akohlmey/.local/lib/python2.7/site-packages/lammps.pyc in read_pipe(self, pipe)
    303     out = ""
    304     while self.more_data(pipe):
--> 305       out += str(os.read(pipe, 1024), 'utf-8')
    306     return out
    307 

TypeError: str() takes at most 1 argument (2 given)
```

**Comment by akohlmey** [comment]
This change seems to make it work:
```
diff --git a/python/lammps.py b/python/lammps.py
index 03c1cc7..7cb3ec0 100644
--- a/python/lammps.py
+++ b/python/lammps.py
@@ -302,7 +302,8 @@ class OutputCapture(object):
   def read_pipe(self, pipe):
     out = ""
     while self.more_data(pipe):
-      out += str(os.read(pipe, 1024), 'utf-8')
+      value = str(os.read(pipe, 1024)).encode()
+      out += str(value)
     return out
 
   @property

```

**Pull request merged**
