### PR TITLE
KOKKOS version of fix viscous and fix dt/reset

### PR DESCRIPTION
**Pull request by mkanski**
**Summary**

Recently, I started using graphics card for calculations with KOKKOS package. I noticed though that about 45% time of my simulations is spent as "Modify". I tracked this down to two fixes which are not ported to KOKKOS - `fix viscous` and `fix dt/reset`. This PR contains KOKKOS versions of these two fixes. They appear to be working, but I'll test them further before asking for merge. I created this PR to mark that I'm working on porting these two fixes, 

**Related Issue(s)**

N/A

**Author(s)**

Michał Kański, Jagiellonian University
e-mail: michal.kanski@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes.

**Implementation Notes**

I had no prior experience with KOKKOS library, so this fixes may not be the most efficient implementations. Generally, I based my code on existing KOKKOS files, such as `fix setforce`.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by stanmoore1** [comment]
Thanks @mkanski! @akohlmey it looks like there are no examples of `fix viscous`, we should consider adding one for the regression tests.

**Comment by akohlmey** [comment]
> @akohlmey it looks like there are no examples of `fix viscous`, we should consider adding one for the regression tests.

There is a whole lot of LAMMPS functionality for which we don't have tests. Code coverage information from the automated testing at Temple can be viewed here: https://app.codecov.io/gh/lammps/lammps

Unless we can find a volunteer that is willing to take on cleaning up the entire examples tree and integrate regression testing in the way we have discussed before, it is not likely that much work will be done there soon. I have several more urgent items on my TODO list (which includes replacing Jenkins with something that is less effort to maintain and keep up-to-date).

**Comment by mkanski** [comment]
I have no experience in regression tests, so I've created a simple examples (attached) using per-atom and per-type masses to test both `dt/reset` and `fix viscous` at the same time and it appears everything works the same as for the standard commands.

I tested following cases:
KOKKOS serial
KOKKOS OpenMP (16 threads)
KOKKOS OpenMPI (16 MPI tasks)
KOKOOS OpenMP-OpenMPI (4 threads, 4 MPI tasks)
KOKKOS AMPERE86 (1 GPU)

What else should be tested?

[rmass.in.txt](https://github.com/lammps/lammps/files/10196123/rmass.in.txt)
[mass.in.txt](https://github.com/lammps/lammps/files/10196125/mass.in.txt)

**Comment by stanmoore1** [comment]
@mkanski this looks great. Is your "Modify" time smaller/as expected now?

**Comment by mkanski** [comment]
@stanmoore1 Yes, it decreased to ~2% of the total time, so I'm more than happy with it.

**Comment by stanmoore1** [comment]
Great, I think this PR is ready for review.

**Comment by stanmoore1** [comment]
I confirm this gives the correct answer on a V100 GPU. I added the examples to our internal regression testing.

**Comment by stanmoore1** [comment]
This is ready to merge from my POV. Great job @mkanski!

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
