### PR TITLE
Add support for "internal" kim_match_pairs command

### PR DESCRIPTION
**Pull request by ellio167**
**Summary**

Add support for a `kim_match_pairs` command within processing for KIM Simulator Model commands to the `kim_interactions` command.

**Related Issues**

PR #1989 would provide the necessary support, but that PR is likely to take time to resolve.  In the meantime, we would like to have this feature available for KIM SM's.

**Author(s)**
Ron Miller (Carleton U)
Ryan S. Elliott (UMinn)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues

**Implementation Notes**

None

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by ellio167** [comment]
@ProfessorMiller

**Comment by akohlmey** [comment]
@ellio167 a convention in LAMMPS is that undocumented styles and commands are in upper case. it may also be useful to include a comment in the source code (e.g. where the internal command is parsed) mentioning that a) this is an internal command, b) what uses it, and b) why it is not documented or should not be used outside of the existing use cases.

**Comment by ellio167** [comment]
@akohlmey Happy to provide those changes (done in 1cee0cf).  Let me know if anything else can/should be improved.

**Comment by akohlmey** [comment]
> @akohlmey Happy to provide those changes (done in [1cee0cf](https://github.com/lammps/lammps/commit/1cee0cf50e583658002c6330ba54d96af5e01592)). Let me know if anything else can/should be improved.

thanks. this looks nicer than anticipated. well done!

**Pull request merged**
