### PR TITLE
Collected small changes and fixes

### LINKED ISSUE #4093: [BUG] Compute RDF unphysical with neighbor multi
**Summary**

`compute rdf` produces incorrect results with `neighbor multi`, the curve decays to zero. My scenario is a WCA liquid for which I want an RDF for comparably long distances. The issue does not occur with `neighbor bin`.

**LAMMPS Version and Platform**

7 Feb 2024 - Development - patch_7Feb2024_update1-147-g4d89741d8c

**Expected Behavior**

`neighbor multi` should lead to the same RDF as `neighbor bin`.

**Actual Behavior**

The RDF produced with `neighbor multi` decays to zero as shown in the plot.

**Steps to Reproduce**

A simplified input script is attached ([in.spheres.txt](https://github.com/lammps/lammps/files/14438358/in.spheres.txt)). Equilibrate a system of WCA spheres. Next, make sure to use `neighbor bin` and measure the RDF with `compute rdf`. Subsequently, turn to `neighbor multi` and measure it again. The discrepancies can be spotted directly in the output files without plotting if desired.

**Further Information, Files, and Links**

Longer force cutoffs can solve the issue. Note that if I calculate the RDF in post-processing, it’s fine in both cases.

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request combines multiple small fixes and changes.

**Related Issue(s)**

Fixes #4093 by disallowing the combination of options
Fixes issue mentioned here: https://matsci.org/t/invalid-dump-frequency-error-when-exceeding-32-bit-integer-timestep/53947

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

The following individual changes are included:
- when searching for fix drude, more stringent search patterns are required to avoid false positives
- bug fixes for meam/ms pair style from @athomps 
- try alternate approach to avoid triggering the "fix not computed at compatible time" error with write_dump. This should also work with timestep numbers that require 64-bit integers.
- flag incompatibilities of some computes and fixes with "multi" or "multi/old" style neighbor lists
- add a "report" style to fix balance to enable monitoring imbalance without rebalancing the subdomain. may be used with fix halt to stop a job when the system has changed too much.
- more notes for porting old code to current LAMMPS

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey I want to talk to Joel about neigh multi and cutoffs before this PR is merged

**Comment by sjplimp** [comment]
@akohlmey all clear on neigh multi error messages

For the write_dump.cpp change, I don't understand what you mean by work-around.  If the fix is not current (or compatible) with the current timestep, won't it still print bad values into the dump snapshot ?

**Comment by akohlmey** [comment]
> If the fix is not current (or compatible) with the current timestep, won't it still print bad values into the dump snapshot ?

When you have a write_dump you know you get whatever is currently stored. The workaround to outsmart a check the Output class does on *future* outputs. This happens because of how write_dump works, i.e. set up a regular dump, but then tell the Output class to write this dump's output just once.

Below is a simple test input. Try running this without the workaround, i.e. use the line
```
dumpargs[3] = utils::strdup("1");    // dump frequency
```
Then try with the current code and finally with the change in this pull request.
```
region box block 0 1 0 1 0 1
create_box 1 box
create_atoms 1 single 0.5 0.5 0.5
pair_style zero 2.5
pair_coeff 1 1
mass 1 1.0
reset_timestep 200
fix 1 all ave/atom 10 2 20 x y z
run 100 post no
write_dump all custom 0.lammpstrj id type x y z f_1[1] f_1[2] f_1[3]
unfix 1
reset_timestep 2147483647001
fix 1 all ave/atom 10 2 20 x y z
run 40 post no
write_dump all custom 1.lammpstrj id type x y z f_1[1] f_1[2] f_1[3]
```

**Comment by rbberger** [comment]
@akohlmey something small for this PR: https://github.com/lammps/lammps/blob/develop/cmake/presets/kokkos-hip.cmake#L16 should be:
```cmake
set(FFT_KOKKOS "HIPFFT" CACHE STRING "" FORCE)
```
This might be in other places too.

**Comment by akohlmey** [comment]
> This might be in other places too.

I recall that it *was* in the KOKKOS/CUDA preset, but that was fixed about a couple of weeks ago...

**Review by stanmoore1 — APPROVED** [review]
I approve

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
