### PR TITLE
make more descriptive log entry for replicate

### PR DESCRIPTION
**Pull request by srtee**
**Summary**

Makes more descriptive log entry for replicate by including the number of copies made in each dimension.

**Author(s)**

Shern Ren Tee (Uni of Queensland)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues expected

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by akohlmey** [comment]
Thanks. However, the call to `fmt::format()` is not needed, since `utils::logmesg()` is overloaded to also accept a format string with a variable number of arguments, and the mention of x-, y-, z-dimension is redundant, but one could also mention the total replication amount. See https://github.com/lammps/lammps/pull/3485/commits/cbec6cdc6c3a202a78901a530973eab517643e55 for an alternative.

**Comment by stanmoore1** [comment]
@akohlmey Seems like https://github.com/lammps/lammps/commit/cbec6cdc6c3a202a78901a530973eab517643e55 (and other commits where the main idea is moved from one PR into another PR) should be a coauthored commit (i.e. by both @srtee and @akohlmey). This preserves the acknowledgment and encourages more contributions. Another example would be https://github.com/lammps/lammps/pull/3483 which was morphed into https://github.com/lammps/lammps/pull/3485/commits/3bf0595078f52a6f1db01c0b5c45db5dc4d97a14.

**Comment by akohlmey** [comment]
> @akohlmey Seems like [cbec6cd](https://github.com/lammps/lammps/commit/cbec6cdc6c3a202a78901a530973eab517643e55) (and other commits where the main idea is moved from one PR into another PR) should be a coauthored commit (i.e. by both @srtee and @akohlmey). This preserves the acknowledgment and encourages more contributions. Another example would be #3483 which was morphed into [3bf0595](https://github.com/lammps/lammps/commit/3bf0595078f52a6f1db01c0b5c45db5dc4d97a14).

I usually cherry-pick those kind of commits. But in both of these cases the changes were essentially one-liners *and* had to be modified. So treating them more like a feature request (i.e. acknowledge them in the github discussion) seems adequate to me.

To illustrate, the following changes were added to PR #3485 without change through cherry-pick:
https://github.com/lammps/lammps/pull/3485/commits/51c6eddd0db02722784633596d0746bacc9979b3 https://github.com/lammps/lammps/pull/3485/commits/f867adc54161236431308a457edef0acb9011162

**Comment by srtee** [comment]
All makes sense -- closing PR now!

**Pull request closed without merging**
