### PR TITLE
cmake: ninja-1.10 supports Fortran now

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by akohlmey** [comment]
Sorry, but we cannot remove this check unconditionally. It will result in failure for most people that enable ninja format output.

**Comment by junghans** [comment]
Good point, I will add a version check.

**Comment by junghans** [comment]
@akohlmey done.

**Comment by akohlmey** [comment]
Thanks. I will wait on this a little bit until after I had time to talk it over with @rbberger 
I think this has the potential to be a bit more generalized and thus also smoothly handle the download feature for external libraries (which ninja does not support either).
The fortran compatibility also affects the internal "linalg" LAPACK/BLAS copy, and will be needed for the upcoming merge of PR #1873, which includes a fortran library.
I also want to discuss with him, what improvements we can do now that we require cmake 3.10.
Most likely we'll use this PR as inspiration, but reimplement it somewhat differently and in tandem with a bunch of additional cmake updates.

**Comment by junghans** [comment]
In newer cmake versions one can make `ExternalProject_Add()` work easily, see #1940 for a start.

**Comment by junghans** [comment]
I made this part of #1940

**Pull request closed without merging**
