### PR TITLE
Kokkos exchange comm for fixes 

### PR DESCRIPTION
**Pull request by valleymouth**
**Summary**

This pull request implements exchange communication for fixes on Kokkos. This is a particular issue when using FixNeighHistory, which would fallback to classic communication. We expect to improve performance when using cuda-aware MPI implementations due to reduced number of copies to host memory.

This also adds support for exchange on device for `fix qeq/reaxff/kk` and `fix shake/kk`

**Related Issues**

No issue related to this pull request.

**Author(s)**

Denis Taniguchi (denis.taniguchi@gmail.com) - Newcastle University
Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No backward compatibility issues.

**Implementation Notes**

Major changes can be seen in CommKokkos::exchange_device. After all AtomVec exchanges are performed we loop over the fixes flagged as extra_grow. We call pack_exchange_kokkos/unpack_exchange_kokkos in each of them. Each fix has a separate call to MPI_Irecv/MPI_Send/MPI_Wait. Since there is no guarantee that the unpack in fixes will happen in the same order as in AtomVec (remember that we rely on atomic operations to define the index of the new incoming atom in AtomVec) we need a new interface that returns the indices assigned to each unpacked atom. That was included in AtomVecKokkos with empty default implementation (returning 0). Those indices are used while unpacking data for fixes ensuring that we correctly match the info in AtomVec with info in fixes.
This pull request include implementations for AtomVecSphereKokkos, FixNeighHistoryKokkos, and FixWallGranKokkos already compatible with the new feature in CommKokkos.
If you use AtomVecs not compatible with exchange comm for fixes we fallback to classic comm. This is verified using a new unpack_exchange_indices_flag member variable in AtomVecKokkos. If you wish to make your AtomVec* compatible with fixes exchange, set unpack_exchange_indices_flag to 1 and implement:
```
int unpack_exchange_kokkos(
  DAT::tdual_xfloat_2d &k_buf,
  DAT::tdual_int_1d &indices,
  int nrecv, int nlocal, int dim,
  X_FLOAT lo, X_FLOAT hi,
  ExecutionSpace `space);
```
Fixes must provide:
```
virtual int pack_exchange_kokkos(const int &nsend,DAT::tdual_xfloat_2d &buf,
                                 DAT::tdual_int_1d k_sendlist,
                                 DAT::tdual_int_1d k_copylist,
                                 ExecutionSpace space, int dim,
                                 X_FLOAT lo, X_FLOAT hi);
virtual void unpack_exchange_kokkos(DAT::tdual_xfloat_2d &k_buf,
                                    DAT::tdual_int_1d &indices,int nrecv,
                                    int nlocal,int dim,X_FLOAT lo,X_FLOAT hi,
                                    ExecutionSpace space);
```
Implementation was validated using the attached case, which is a variation of the chute case.
An example of command to run the case is given bellow:
`mpirun -np 3 lmp_kokkos_cuda_mpi -k on g 3 -sf kk -pk kokkos neigh half -in in.gran`

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

[in.gran.txt](https://github.com/lammps/lammps/files/3020186/in.gran.txt)
[data.chute.txt](https://github.com/lammps/lammps/files/3020188/data.chute.txt)

### CODE REVIEW

**Comment by akohlmey** [comment]
@valleymouth please note, that your changes break when compiling KOKKOS with OpenMP instead of CUDA.

**Comment by valleymouth** [comment]
Forgot to mention that the only wall/gran style ported so far is the hooke/history.

**Comment by valleymouth** [comment]
@akohlmey I always forget about OpenMP. Ok, I will work on it.

**Comment by akohlmey** [comment]
> @akohlmey I always forget about OpenMP. Ok, I will work on it.

well, there are even more modes, that KOKKOS should support: serial, MPI-only.

**Comment by stanmoore1** [comment]
Thanks @valleymouth, good work. I'll run this through the Kokkos regression tests.

**Comment by valleymouth** [comment]
@stanmoore1 Brilliant! Let me know if you need help.

**Comment by stanmoore1** [comment]
Kokkos GPU tests passed.

**Comment by stanmoore1** [comment]
I want to do a few more checks on this before merging

**Comment by stanmoore1** [comment]
@valleymouth sorry for the delay. I'm picking this back up now.

**Comment by valleymouth** [comment]
@stanmoore1 That's great! Let me know if you need any help.

**Comment by akohlmey** [comment]
@stanmoore1 this now has a merge conflict in src/KOKKOS/comm_kokkos.cpp and it is not clear to me how to resolve it. or to tell, whether this change is still needed. can you please check it?

**Comment by stanmoore1** [comment]
Yes, sorry for the delay, this is on my to-do list.

**Comment by stanmoore1** [comment]
This PR got out of sync, needs work to fast forward to latest develop. Closing for now, can revisit in the future.

**Comment by stanmoore1** [comment]
Reopening, will fix merge conflicts.

**Comment by stanmoore1** [comment]
Kokkos regression tests pass now. I'm going to do a little code cleanup, then it should be ready to merge.

**Comment by vladgl** [comment]
@stanmoore1 When this PR is planned to be merged to develop? We are currently working on a new fix and its kokkos variant which exchanges additional data, and it would be great to add better exchange communication.

**Comment by stanmoore1** [comment]
@vladgl I want to do a little more cleanup/refactoring but this is very high on my to-do list, should be merged soon.

**Comment by stanmoore1** [comment]
This appears to be working correctly. Running Kokkos regression tests now.

**Comment by stanmoore1** [comment]
Missed some changes for `FixWallGranKokkos`

**Comment by stanmoore1** [comment]
This passes my tests on CPU with the Serial backend, need to test GPU and run regression tests, then it should be ready.

**Comment by stanmoore1** [comment]
@akohlmey I can't reproduce the compilation errors with the Intel compiler and this PR. Any ideas?

**Comment by stanmoore1** [comment]
@akohlmey also are you going to fix the trailing whitespace in `VORONOI` or should I? It isn't related to any changes in this PR.

**Comment by akohlmey** [comment]
> @akohlmey I can't reproduce the compilation errors with the Intel compiler and this PR. Any ideas?

This is not only with the Intel compiler. It is just when this group of test fails, others are not even attempted.
Are you including the GRANULAR package? This seems to be related to its recent refactor which significantly changed fix wall/gran without updating the KOKKOS version.

**Comment by akohlmey** [comment]
> @akohlmey also are you going to fix the trailing whitespace in `VORONOI` or should I? It isn't related to any changes in this PR.

I've added this to #3703.

**Comment by akohlmey** [comment]
@stanmoore1 fixes for the run and regression tests have arrived in upstream and I've merged it with this branch and re-enabled the tests.

**Comment by stanmoore1** [comment]
Still seeing a crash with fix shake and this PR, tracked it down to the random order of ghosts from Kokkos border comm, which messes up some assumptions in building the atom_map. Steve suggested using `closest_image` function instead of `minimum_image_once` in fix shake.

**Comment by stanmoore1** [comment]
Re-running Kokkos regression tests for this PR.

**Comment by akohlmey** [comment]
> Re-running Kokkos regression tests for this PR.

@stanmoore1 FYI, had to re-bless only one (1!) of the general regressions tests (fix deposit with molecules + shake) and that started to diverge only after 4000, which is pretty good.

**Comment by stanmoore1** [comment]
I think I finally got the issues fixed. Re-running Kokkos regression tests.

**Comment by stanmoore1** [comment]
This gives ~15% speedup on a ~2M atom rhodo problem running on 2 V100 GPUs, since it doesn't have to transfer data for fix shake exchange comm down to CPU. @arghdos @weinbe2

**Comment by stanmoore1** [comment]
It gives ~1.7x speedup on the Chute benchmark with `fix neigh history` for 12.8M atoms on 2 V100. I also fixed a bug in `fix neigh/history/kk` where it wasn't transferring the correct data between CPU and GPU when using exchange comm on the host CPU (which was previously the only option), which made that option slower (and is what I compared to).
 
 Seems to be in the noise for `fix qeq/reaxff` and ReaxFF HNS benchmark with 668k atoms on 2 V100 though.

**Review by stanmoore1 — APPROVED** [review]
Kokkos regression tests passed.

**Comment by skyreflectedinmirrors** [comment]
Sounds great -- having @IanBogle take a look while I'm on vacation :)

**Comment by sjplimp** [comment]
Nice work @stanmoore1 !

**Review by sjplimp — APPROVED** [review]

**Comment by skyreflectedinmirrors** [comment]
>This gives ~15% speedup on a ~2M atom rhodo problem running on 2 V100 GPUs

For posterity, this is about what we saw as well.

**Pull request merged**
