### PR TITLE
refactoring of neighbor history

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

_Briefly describe the new feature(s), enhancement(s), or bugfix(es) included in this pull request. If this addresses an open GitHub Issue, mention the issue number, e.g. with `fixes #221` or `closes #135`, so that issue will be automatically closed when the pull request is merged_

## Author(s)

Steve Plimpton

## Backward Compatibility

N/A

## Implementation Notes

This removes logic from the neighbor list building (npair methods) for neighbor
list history, and moves it to FixNeighHistory.  The latter is a renaming of
what was originally FixShearHistory, since in a generic sense it can preserve
any kind of per-neighbor values from one neighbor-list build to the next.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey, this needs some changes in USER-OMP to be compatible
with the refactoring.  Specifically:

pair_gran (small changes)
fix_shear_history (now fix_neigh_history) (larger changes, including new post_neighbor method)
npair methods (those with size in the file name)

Also, I just realized the new post_neighbor hooks still need to be added to Respa
and Min, similar to Verlet.

**Comment by sjplimp** [comment]
@stanmoore1, there may be some small KOKKOS package changes
needed for this PR due to removing the dnum and dpage options from neighbor
lists and neighbor.cpp. Those values are now stored in
a new FixNeighHistory, to separate them conceptually from neighbor list building.

**Comment by stanmoore1** [comment]
I fixed the Kokkos compile errors, but there is a USER-OMP compile issue:

<pre>
../npair_half_size_bin_newtoff_omp.cpp:23:31: fatal error: fix_shear_history.h: No such file or directory
 #include "fix_shear_history.h"
                               ^
compilation terminated.
make[1]: *** [npair_half_size_bin_newtoff_omp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../npair_half_size_bin_newton_omp.cpp:23:31: fatal error: fix_shear_history.h: No such file or directory
 #include "fix_shear_history.h"
                               ^
compilation terminated.
make[1]: *** [npair_half_size_bin_newton_omp.o] Error 1
make[1]: Leaving directory `<https://jenkins.sandia.gov/job/LAMMPS_face_KOKKOS_heavy_GitHub/ws/src/Obj_kokkos_omp'>
make: *** [kokkos_omp] Error 2
Build step 'Execute shell' marked build as failure

</pre>

**Comment by akohlmey** [comment]
@stanmoore1 yes. still working on this one. this is more complex to sort out for USER-OMP as there are changes in the serial code that never made it to USER-OMP for some reason. i am tempted to drop support for granular styles in USER-OMP completely, as those are the least parallel efficient pair styles with the threading strategy employed in USER-OMP. with a bit of luck, i can complete the work on this today.

**Comment by akohlmey** [comment]
@sjplimp this is now ready for your final updates to the `Respa` and `Min` classes as mentioned above.

**Comment by akohlmey** [comment]
@sjplimp please assign the PR back to me after you are done, and i'll check if and how this affects `RespaOMP`.

**Comment by sjplimp** [comment]
@akohlmey, I made the min and respa changes.  Also refactored the rRESPA neigh lists which affects several pair styles and NPair class methods that build and use those neighbor lists.  So there are OMP
analogs of those pair styles you will likely need to make some cosmetic changes to. The rRESPA neigh list change is simply to stop treating them as 3 separate neigh lists, and just as one with 3 internal paged data structs.  Simpler that way I think; removes complexity from the Neighbor class.

**Comment by akohlmey** [comment]
@sjplimp FYI, the jenkins builds fail on a non-USER-OMP pair style: lj/long/coul/long

**Comment by sjplimp** [comment]
@sjplimp FYI, the jenkins builds fail on a non-USER-OMP pair style:
lj/long/coul/long

hmmm - works for me via g++ build on my box - file is attached.
Same in my git and my SVN lammps (not checked into SVN yet).

Steve

**Comment by akohlmey** [comment]
my bad. it is `lj/long/dipole/long`. i just pulled the branch to my desktop at home and had it fail there, too.

**Comment by sjplimp** [comment]
>> my bad. it is `lj/long/dipole/long

ok - I missed that one, b/c it does not actually support rRESPA.
But for some reason it has this method below still in it.

The method can just be deleted.
Can you do that when you make the OMP changes?

Thanks,
Steve

------------------------------

/* ----------------------------------------------------------------------
   neighbor callback to inform pair style of neighbor list to use
   regular or rRESPA
------------------------------------------------------------------------- */

void PairLJLongDipoleLong::init_list(int id, NeighList *ptr)
{
  if (id == 0) list = ptr;
  else if (id == 1) listinner = ptr;
  else if (id == 2) listmiddle = ptr;
  else if (id == 3) listouter = ptr;

  if (id)
    error->all(FLERR,"Pair style lj/long/dipole/long does not currently support respa");
}

**Comment by akohlmey** [comment]
and it looks like `lj/cut/coul/long/soft` and `lj/cut/coul/thole/long` are missing some updates, too.
i'll take a look. will likely have to go over a bunch of pair styles in USER-OMP anyway.

**Comment by akohlmey** [comment]
@sjplimp i've completed all changes required to make the code compile again and update `respa/omp`. This should be ready to merge as far as i am concerned.

**Pull request merged**
