### PR TITLE
Add support for Sphinx+PDF+MathJax

### LINKED ISSUE #1138: Convert embedded MathJax to explicitly rendered pictures
## Summary

A few LAMMPS doc pages use MathJax to typeset equations. This works ok for HTML pages, but fails for PDF files created with htmldoc.

## Type of Issue

Enhancement(?)

## Detailed Description

The LAMMPS documentation typesets equations by processing single-page latex files into jpeg images. Some recent contributions uses MathJax instead, which is not compatible with the tools used to generate the PDF format manual. Converting those into the common LAMMPS style will improve the PDF manual.

## Further Information, Files, and Links

An alternate approach to create PDF files from the documentation, that does not require txt2html and htmldoc would be preferable and would allow to use RST markup instead of the custom markup from txt2html. at the moment, we convert txt2html files to rst in order to build the visually enhanced html manual version.

### PR DESCRIPTION
**Pull request by eofetis**
## Purpose

This closes #1138 

## Author(s)

Evgenii Fetisov @ PNNL

## Backward Compatibility

Should not break any inputs.

## Implementation Notes

'make pdf' now invokes Sphinx (same as 'make html') and correctly produces "Manual.pdf" (with hyper refs and sidebar links) using pdflatex with MathJax equations processed correctly. This eliminated the need for 'txt2html' and 'htmldoc'. However, MathJax and pdflatex are not compatible when it comes to equations so the make script manually removes duplicate "\begin{equation}" and "\end{equation}". This will require further consistency in only using sphinx.ext.mathjax to process math equations vs sphinx.ext.imgmath (however, only one of these extensions can be used at a time so there should be no problems here).

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [NA] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by akohlmey** [comment]
@eofetis thanks for your submission. this looks promising. since this affects the distribution of LAMMPS and future plans for how to maintain the documentation, we will have to have an internal discussion among the LAMMPS core developers first. i will post an update here, after we have reached a consensus. thanks again for your effort.

**Comment by akohlmey** [comment]
@eofetis @sjplimp i've augmented the Makefile for the doc build, so that `make old` will now do the old style html build as well as the old style pdf build and put everything into the `old` folder. I think this is now ready for a discussion.

**Comment by eofetis** [comment]
@akohlmey both ways (make pdf and make old) work for me locally.

BTW, the reason 3 JPG files have been changed is because there was something screwed up in their dpi encoding making their actual width 600in (can be seen in Inkscape for example) and thus messing up with pdflatex.

Also, .gitignore in this pull request currently has "/latex" duplicated.

**Comment by akohlmey** [comment]
@eofetis thanks for the note. i've updated .gitignore.

**Comment by eofetis** [comment]
@akohlmey Actually, after seeing your #1334 I played a little bit with generated RST files. Turns out \begin{equation} and \end{equation} are not even needed for MathJax processing. This will eliminate the need for the 'sed' commands in Makefile (once RST files themselves are fixed)

**Pull request merged**
