### PR TITLE
Rendezvous2

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

2nd attempt to submit rendezvous protocol changes.

**Author(s)**

Steve Plimpton (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

yes

**Implementation Notes**

This is the second attempt to merge this feature. Details are at #1238 

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey you can redo the testing with these 2 changes

**Comment by akohlmey** [comment]
@sjplimp @stanmoore1 the failure on `lammps/pull-requests/regression-pr` is a false positive in the testing process, that i have not found out yet how to correct. when i run tests manually with this branch, they now all complete for a large variety of inputs from the examples folder. so this is good to go regardless.

**Comment by stanmoore1** [comment]
@akohlmey sometimes just have to rebless the gold standard for the tests when there are false positives. A change in the order of operations can cause exponential diverging trajectories.

**Comment by akohlmey** [comment]
> @akohlmey sometimes just have to rebless the gold standard for the tests when there are false positives. A change in the order of operations can cause exponential diverging trajectories.

problem is, i cannot figure out without richard's help where that data is held and how i perform this task. i've tried a bunch of things, but nothing had any consequences, so we'll have to accept this false positive for now, until richard has time to do it for us or instruct me how to do it.

**Comment by stanmoore1** [comment]
In Jenkins I temporarily change the run command to:

```
python lammps-testing/lammps_testing/regression.py 8 'mpiexec -np 8 /home/jenkins/workspace/lammps/pull-requests/regression-pr/lammps/src/lmp_mpi -v CORES 8' lammps-testing/tests/examples -only micelle  -auto-rebless True -min-same-rows 0
```
Or can delete the files `log.15Mar19.linux.8.micelle-rigid` and `log.15Mar19.linux.8.micelle`. Not sure how to delete them outside of Jenkins though.

**Pull request merged**
