### PR TITLE
Adding test examples for the SPIN package and correcting some bugs

### PR DESCRIPTION
**Pull request by julient31**
**Summary**

This PR contains three main modifications:
- setting three first test examples for the SPIN package (in examples/SPIN/test_problems) with an associated README file.
- improvements of the SPIN package's documentation (mainly fix_langevin_spin.txt, pair_spin_exchange.txt, and compute_spin.txt).
- correction of some bugs (mainly found and solved with the benchmark examples), for example in fix precession/spin.

**Related Issues**

None

**Author(s)**

Julien Tranchida (jtranch@sandia.gov)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

Correctness of the changes is checked with the newly setup benchmark examples.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@julient31 I would not talk about "benchmark" in this context here, but about "validation". The former term is too often used in the context of LAMMPS to describe how fast a calculation is or how well it parallelizes rather than how accurate it is. Also there are references and files/folders using "benchmarck" instead of "benchmark".  I would be ok with the term "benchmark" if @sjplimp, @athomps, @stanmoore1 can assure me that there would be no confusion, but at least the typo needs to be resolved. ;-)

**Comment by athomps** [comment]
@julient31 @akohlmey I agree that the term benchmark is confusing because it collides with the same word used in the context of LAMMPS performance.  More generally, benchmarks are things that are measures of performance, capacity, distance traveled i.e. magnitudes. The examples provided appear to be measures of correctness rather than performance. I suggest replacing benchmarck with test.  It's less exciting, but it is an accurate description and contains fewer characters.

**Comment by julient31** [comment]
@akohlmey @athomps Yes good point: benchmark was not very well chosen. I renamed the directory 'test_problems', and the sub-directories will be validating different calculations (validation_damped_exchange, validation_damped_precession, ...). 
@akohlmey , Axel, as I corrected the dump commands, would you like/need me to regenerate the log files in the other examples? (for example log.30Apr19.spin.iron.g++.1, ...).

**Comment by akohlmey** [comment]
> @akohlmey , Axel, as I corrected the dump commands, would you like/need me to regenerate the log files in the other examples? (for example log.30Apr19.spin.iron.g++.1, ...).

Yes. Not so much because of the dump command changes, but since it looks you also changed the thermo settings.

**Comment by julient31** [comment]
@akohlmey I generated fresh log files corresponding to the current results of the code / input examples. 
Also Axel, I left in the examples/SPIN directory a shell script (run_spin_examples.sh) that is running all the examples and generating the associated log files. It's a little bit 'messy', I would like to keep it there to regenerate fresh log files each time I modify the SPIN package of the examples. 
Is it fine to leave it there? Otherwise, let me know, I'll remove right away. 
Thanks a lot!

**Comment by akohlmey** [comment]
@athomps for me to merge it, you need to assign the PR to me. Thanks.

**Comment by rbberger** [comment]
@julient31 I've updated the docs to be RST only. Please review my changes.

**Comment by julient31** [comment]
@rbberger Thanks for converting the files Richard! I'll write/update directly .rst files next time.
I checked them and that all look good to me!

**Pull request merged**
