### PR TITLE
Extension of msi2lmp to produce data files with atom_style charge

### PR DESCRIPTION
**Pull request by evoyiatzis**
## Purpose

A new command line option (-reaxff) has been added to the code. The goal is to convert material studio files to LAMMPS data files with a file format corresponding to atom_style charge instead of atom_style full. The reason is to treat systems with potentials such as ReaxFF and Stillinger Weber which do not contain explicit connectivity. No automatic assignment of force field parameters is made.

## Author(s)

Evangelos Voyiatzis

## Implementation Notes

An external int is added in the msi2lmp.h file to store the wish of the user. The modification in the car file is a quick & dirty fix of a bug (a proper fix will be implemented by Axel) and not related to this extension. If the flag is specified in the command line then also the -ignore option is enabled. The reason is that we are interested in extracting only the mass and the chemical nature of the atom types from the frc files and not the parameters of the original force field used to create the car & mdf files. Moreover, the total number of bonds, angles, dihedrals, impropers and all bonded terms is hard-coded to zero in the MakeLists.c file.  

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ X] The feature or features in this pull request is complete
- [ X] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ X] The source code follows the LAMMPS formatting guidelines

### CODE REVIEW

**Comment by akohlmey** [comment]
Thanks for your submission. There are some small technical issues, but primarily, I don't see much value in it, as it replicates functionality, that is already elsewhere. The conversion, you desire can be easily done with VMD and the TopoTools plugin. since no topology data is required, you can just read the .car file and then write out a data file. Also, you could just do a conversion with msi2lmp and use the -i flag to have it insert dummy values in case of unusual/unsupported atom typing and then use the data tool from Pizza.py to reduce all bonded topology data from the temporary data file. The upshot is, that an already difficult to maintain and complex tool like msi2lmp is not getting any more complex.

**Comment by evoyiatzis** [comment]
You call the orders Axel :) 
I might spend some time to overcome the limitation of the Morse potential. If this would be of interest please send me any relevant info/advice.

**Comment by akohlmey** [comment]
`msi2lmp` has multiple known limitations. It wasn't written by me, and I'm only the maintainer by default, since I ported the code to work on windows for a number of tutorials, and found/fixed a significant amount of bugs and inconsistencies in the process. I have no reference to compare its functionality to outside of existing files and trivial tests. Thus i cannot (and do not want to) change any functionality that requires access to MS to validate it. Please keep in mind, that the core of the functionality is over 20 years old. Rather than trying to hack new features into this code, I would consider a clean rewrite from scratch in a more convenient programming language, e.g. python. The conversion process is not a time critical one and the convenience in handling structured data and automatic memory management should result in a much cleaner and more maintainable tool. The existing code and still serve as a reference and benchmark.

**Comment by akohlmey** [comment]
for future reference, please do not submit pull requests, that contain unrelated changes (`examples/ELASTIC/compliance.py`) or have changes that will conflict with other, equivalent changes. This just creates needless work and confusion. Ideally, each pull request contains just one self-contained change set. if it is dependent on other changes, please just mention this in the submit message, but omit those changes. thanks for your understanding.

**Comment by evoyiatzis** [comment]
true my bad !

**Pull request closed without merging**
