### PR TITLE
Add support for GitHub Codespaces

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

GitHub is adding a feature that turns your web browser into a fully functioning development environment: [Codespaces](https://github.com/features/codespaces/)

A codespace is essentially a container running in the cloud with a checkout of the code repository. The IDE is an online version of [Visual Studio Code](https://code.visualstudio.com/). 

This could be very useful in tutorials and workshops since it removes the need to install prerequisites or a VM. All tools, such as a compiler, CMake, text editors, etc are installed in the container.

This PR adds the minimal set of files needed to enable users to launch their codespace for LAMMPS based on Ubuntu 18.04.

**Note: This GitHub feature is currently in private beta. However, the `.devcontainer` a directory can already be used by VisualStudio Code to create a [container-based development environment](https://code.visualstudio.com/docs/remote/containers).**

Once publicly available, users can create a code space by clicking the "Code" button at the repository page and "Open with Codespaces".

lauch_codespace

codespaces

**Author(s)**

@rbberger 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Implementation Notes**

The container definition files are stored in https://github/lammps/buildenv.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@rbberger is this something we want to get ready and included into the stable release? I went to https://github.com/features/codespaces and it looks like this is still in early access testing.

**Comment by rbberger** [comment]
@akohlmey no, as long as it's in early access testing I wouldn't want to merge this in master.

**Comment by akohlmey** [comment]
@rbberger just read that codespaces will be a for a fee service once the (currently public) beta has ended. Do we still want to include it in the distribution?

**Comment by rbberger** [comment]
@akohlmey too bad. no, let's close it then if there's no free tier

**Pull request closed without merging**
