### PR TITLE
fix the problem with COM, gyration, inertia ... calculation over a chunk computes with PBC.

### PR DESCRIPTION
**Pull request by avoronts**
I fixed the problem with COM calculation over a chunk computes with PBC.
Problem appeared when chunk crossed the boundary.
Solution is shifting origin close to chunk atoms, making calculation and shifting it back.
Also in gyration, inertia, omega, torque calculation one have to take nearest to COM copy of atoms.

I don't understand how you chose origin in compute_dipole_chunk, so i didn't correct it. But correction  is have to be done. 

## Purpose

I think distance with PBC should be calculated to the nearest image of atom. It is natural for molecules and clusters.

## Author(s)

Alexander Vorontsov, South Ural State University, Chelyabinsk, Russia

## Backward Compatibility

I made minor changes in existing files, so everything should be OK. 

## Implementation Notes

I've add  'origin' array, that takes MIN coordinates x_min, y_min, z_min of atoms of a chunk. COM calculation was performed with  nearest to origin images of atoms. After COM calculations origin shifted back.

In gyration, inertia, omega, torque calculation distance from atom to COM is calculated for nearest to COM copy of it.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

Simple test 
-------input_file------
...
boundary   p p p
region  reg block 0. 50. 0. 50. 0. 50.
create_box 1 reg
create_atoms 1 single 0 0 0
create_atoms 1 single 49 49 49
................
compute  clust_old all cluster/atom 8.0
compute chunk1 all chunk/atom c_clust_old
compute size all property/chunk chunk1 count
compute size_chunk all global/atom c_chunk1 c_size
compute com all com/chunk chunk1
compute com_chunk all global/atom c_chunk1 c_com[ * ]
compute gyr all gyration/chunk chunk1
compute gyr_chunk all global/atom c_chunk1 c_gyr
...
dump   clust_dump all custom 50 dump.txt id x y z c_clust_old c_size_chunk c_com_chunk[ * ] c_gyr_chunk[ * ]

run 0

--------- new result --------
ITEM: TIMESTEP
0
ITEM: NUMBER OF ATOMS
2
ITEM: BOX BOUNDS pp pp pp
0.0000000000000000e+00 5.0000000000000000e+01
0.0000000000000000e+00 5.0000000000000000e+01
0.0000000000000000e+00 5.0000000000000000e+01
ITEM: ATOMS id x y z c_clust_old c_size_chunk c_com_chunk[1] c_com_chunk[2] c_com_chunk[3] c_gyr_chunk[*]
     1      0    0.00000    0.00000    1.00000      2   49.50000   49.50000   49.50000    0.86603
     2     49   49.00000   49.00000    1.00000      2   49.50000   49.50000   49.50000    0.86603

-------  old  result --------------------
ITEM: TIMESTEP
0
ITEM: NUMBER OF ATOMS
2
ITEM: BOX BOUNDS pp pp pp
0.0000000000000000e+00 5.0000000000000000e+01
0.0000000000000000e+00 5.0000000000000000e+01
0.0000000000000000e+00 5.0000000000000000e+01
ITEM: ATOMS id x y z c_clust_old c_size_chunk c_com_chunk[1] c_com_chunk[2] c_com_chunk[3] c_gyr_chunk[*].
     1      0    0.00000    0.00000    1.00000      2   24.50000   24.50000   24.50000   42.43524.
     2     49   49.00000   49.00000    1.00000      2   24.50000   24.50000   24.50000   42.43524.

### CODE REVIEW

**Comment by akohlmey** [comment]
please remove all "added by..." comments. due to using git we already know who changed what and when.
also please provide some simple _complete_ examples demonstrating the issue.

**Comment by avoronts** [comment]
Simple test for compute_COM_chunk and compute_gyration_chunk
[test_COM_gyration.in.txt](https://github.com/lammps/lammps/files/1148505/test_COM_gyration.in.txt)

The other computes I didn't test.

**Comment by akohlmey** [comment]
Just a quick note. We will be looking into this after the LAMMPS workshop. This likely requires some more in-depth checking and possibly a more general/flexible solution.

Thanks for pointing out the issue and providing a suggestion for addressing it.

**Comment by zqex** [comment]
The calculation of CM and RG tensor currently in LAMMPS is CORRECT for chunk=molecule IF the user loads unwrapped coordinates. The computes are in general wrong for chunks=aggregates of particles.   As far as I can see, this bug fix fails in both these cases.

For molecules and unwrapped coordinates: Since LAMMPS uses unwrapped coordinates, the CM is calculated correctly, and hence also the RG tensor, since the relative coordinates to the CM makes sense.

IF the user supplies a molecule configuration with wrapped coordinates or resets image info, then centre of mass / RG tensor is in general illdefined. Only in the case where it would work is IF the whole molecule is inside the simulation domain, such that image reset is just a translation. (which is not that clearly stated in the manual)

The general solution solution is to traverse the structure from some arbitrary starting bead, and add image shifts to the wrapped bead coordinates such that each bond between unwrapped coordinates obeys the minimum image convention, this makes the unwrapped coordinate representation of the molecule contiguous in real space. In that case CM and RG tensor is again well defined. Note that this works even for (acyclic) molecules that are much larger than the simulation box. Note there are still issues with since the CM depends on a arbitrary choice of starting bead, so MSD of CM has to be computed with care if this information is not correctly preserved between runs.

An example of a special case where the solution above fails is a large single contiguous polymer where the head and tail beads are located at the same point in wrapped coordinates, but differ from zero by an image vector. Hence the molecule is a ring in wrapped coordinates and a linear polymer in unwrapped coordinates. The polymer has a well defined CM / RG tensor, but the ring molecule does not. There is no way to fix this. (its a bit like constructing a Penrose triangle)

Hence a correct fix would identify and halt in the case where loops exists such that not all bond vectors between unwrapped bead coordinates belong to the minimum image (i.e. ix=iy=iz=0). (which is a rather nasty criterion to implement) NB fix bond create happily creates such bonds, since the minimum image distance is used for making the bonds.

If the chunk is an aggregate of non-bonded particles, then each bead can involve an arbitrary image shift despite the aggregate being of limited size in wrapped coordinates. In that case beads again needs to be shifted into a common image such that all pair distances between neighbouring beads in the aggregate belong to the minimum image.

The proposed code shifts all unwrapped coordinates in a chunk by a specific constant, hence the CM / RG tensor will be wrong. The proposed code would work for an aggregate IF the WRAPPED coordinates relative to a shifted origin on the aggregate used though. But in that case it would fail for a polymer with unwrapped coordinates where LAMMPS currently is correct.

In the case of a chunk = aggregate that straggles two opposite period boundaries turning it into an infinite rod in unwrapped coordinates, again there is no well defined CM point or RG tensor. A correct fix would identify this case and halt.

I think the solution is to update the documentation, and request the user to use meaningful configurations when using these computes, since there is no easy general solution to fixing this within LAMMPS.

**Comment by akohlmey** [comment]
this will need a more general solution, that will have to be implemented by the LAMMPS developers. This PR is thus converted into issue #1710

**Pull request closed without merging**
