### PR TITLE
New neighbor list code with updates for USER-OMP and USER-DPD

### PR DESCRIPTION
**Pull request by akohlmey**
This pull request provides the updated the new-neighbor branch with changes required for USER-DPD and USER-OMP and a bugfix. I've also updated it with the latest changes from the master branch.
There still seems to be an issue in the baseline code that is exposed with running loops like in the examples/USER/misc/basal input deck.

@timattox This moves the pull request to the official LAMMPS git repository, as we now officially changed the development workflow and do the git based development there. However, the branch itself remains in akohlmey/lammps, so if you have additional updates, you should still post the PR against akohlmey/lammps:new-neighbor. This will remain a one-off.

@sjplimp Please let me know, how you want to proceed. I'm assigning it to you, since i updated it to the latest changes in master and resolved the resulting conflicts, so it is ready to merge as far as USER-DPD and USER-OMP are concerned.

### CODE REVIEW

**Comment by stanmoore1** [comment]
I'm working on adding these changes to the KOKKOS package. After that is finished, I believe this pull request can be merged.

**Comment by stanmoore1** [comment]
@akohlmey I did some testing with this using USER-OMP and it is failing on the USER-DPD examples with "ERROR: Requested neighbor pair method does not exist (../neighbor.cpp:758)" whereas without the neighbor refactor it runs OK.

**Comment by akohlmey** [comment]
@stanmoore1 didn't have time to check this, but there may be some changes in the baseline that may require additional settings here. This is something for @timattox to check out. Most likely, it just needs the creation of some dummy class aliases, that redirect the style to some generic variant, like it is done in USER-OMP.

**Comment by timattox** [comment]
I will have a look into this tomorrow.

**Comment by akohlmey** [comment]
@stanmoore1 please check again, i've merged tim's changes and updated the pull request.

**Comment by stanmoore1** [comment]
Yes, that fixed the problem.

**Comment by stanmoore1** [comment]
@akohlmey, once you merge my pull request, this can be sent to Steve.

**Comment by akohlmey** [comment]
done

**Pull request merged**
