### PR TITLE
GPU.cmake: clean up mpi_stubs special handling

### PR DESCRIPTION
**Pull request by junghans**
**Summary**

Some minor clean up releated to `mpi_stubs`.

**Related Issues**

See discussion here: https://github.com/lammps/lammps/pull/2325#discussion_r479855223

**Author(s)**

@junghans

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

yes

**Implementation Notes**

CMake-only

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by junghans** [comment]
@rbberger can you remember why we didn't do it this way to start with?

**Comment by rbberger** [comment]
Honestly, no. There were these discussions about including LAMMPS in another CMake project, maybe that's where it produced some issues.

**Comment by junghans** [comment]
I ran the example in `examples/COUPLE/simple` again and that still works.

**Comment by akohlmey** [comment]
If I look through the commit history for this I find that this "hack" was implemented to make certain that when compiling a serial version the mpi.h file from the STUBS folder is used and not one from a system folder.   I don't think we can do this change and I certainly don't want to do this while we are converging toward a stable release. This is different from the case of compiling a fortran library for the tester of the fortran interface.

**Comment by akohlmey** [comment]
been thinking about this some more. this is a very minor change. the current code works so there really isn't much need to apply this. let us revisit this issue (and some others) when we revise the minimum supported CMake version the next time (i.e. perhaps in 2-3 years).

**Pull request closed without merging**
