### PR TITLE
New feature compute fep/ta

### PR DESCRIPTION
**Pull request by davidfir3**
**Summary**

Add new style compute fep/ta for FEP package. This compute adopts the test-area approach, by perturbing the area of interfaces, to evaluate the change in the free energy.

**Related Issue(s)**

N/A

**Author(s)**

Shifeng Ke, Zhejiang University (3160104230@zju.edu.cn)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

The perturbation is implemented by scaling box size in three dimensions and then remapping the positions of atoms (both local and ghost). Neither inter-processor communication nor neighbor list rebuilding is operated when changing box size.

After energy computation of the perturbed state, restore box size, energy, virials and atom arrays to the initial values.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by agiliopadua** [comment]
Great addition! I'm going to run a test myself.
Can you provide at leat one simple test case in examples/PACKAGES/fep , e.g. on a LJ fluid from Gloor, Jackson JCP 2005 or on a water model from Vega, De Miguel JCP 126, 154707 (2007)?

**Comment by davidfir3** [comment]
@agiliopadua Thanks for your approval! I'll try my best to add required test cases ASAP.

**Comment by akohlmey** [comment]
@davidfir3 thanks for your contribution. I've made some - mostly  cosmetic - updates to your PR branch that align it better with our current state for preferred formatting and programming style (the equivalent change to compute fep is forthcoming in a different pull request), and also fully integrate it into the build system and manual.

**Comment by agiliopadua** [comment]
Thank you for the example. My opinion is:
- document the issue with the constraints so that users are aware (I suppose it's possible to circumvent this by doing a rerun without constraints),
- don't complicate things. The package is useful for you and possible many others as is; if people feel the need to add functionality they will.

**Review by agiliopadua — COMMENTED** [review]
The code seems to work fine.
It would be useful to add in the Restrictions section of the doc page a note on the issues of using this compute with constraints.

**Comment by davidfir3** [comment]
Thanks for your advise. I'll update the doc page and the example.

**Review by agiliopadua — APPROVED** [review]

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
