### PR TITLE
Improved performance for setup on large numbers of MPI ranks

### PR DESCRIPTION
**Pull request by akohlmey**
## Purpose

This is a small package/patch COMM_NPROCS that addresses some scalability performance issues I’ve observed when setting up large molecular systems on large numbers of MPI ranks (e.g. +100Ms of particles on +10Ks MPI ranks). The suggested changes largely address logic in a few places that involves loops over processors, which become prohibitive in setting up large-scale runs. I suspect most users will see negligible performance impact from these changes, but if you regularly run large systems on +10K MPI ranks, then they might be worth taking a look at if you observe rather long setup times when replicating systems, building molecular topologies, or creating remap plans for 3D FFTs. 

With these changes, I was able to successfully setup a modified rhodo replicated system (without kspace method) with 36.86 billion particles on 786,432 MPI ranks in 42 seconds compared to the original projected time of 18 hours. Again, this was just setting up the simulation in LAMMPS. With the changes below, I’m currently projecting the PPPM setup time to be ~6 minutes for the same system, compared to the original projected time of 12 days. And, in this case, the PPPM setup time would further improve if an additional hint could be passed during creation of one of the plans (the last one).

My edits and suggestions certainly don’t cover 100% of use cases in LAMMPS (everything works with rhodo), but hopefully they all can be adapted and included in the LAMMPS source and, at the very least, activated in certain cases and/or by specific request from a user with additional keywords as in my implementation.

The changes to replicate have been removed here and filed separately by @stanmoore1 as PR #723 

## Author(s)

Christopher Knight (ANL)

## Backward Compatibility

Unknown

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

https://sourceforge.net/p/lammps/mailman/message/36005998/

### CODE REVIEW

**Comment by akohlmey** [comment]
TODO: test carefully. document new options.

**Comment by stanmoore1** [comment]
I've also noticed large setup times when using `replicate` with large systems and lots of MPI ranks.

**Comment by stanmoore1** [comment]
Looks like there are two options to try with this PR: `comm_modify ring_neighbor`, and `replicate * * * memory`. I tried using the enhanced `replicate` but it crashed (and it also has some rogue debug output that will need to be removed):

<pre>
Replicate::bounding box image: lo= 0 -1 -1  hi= 0 1 1
Replicate:: buf_all memory allocating       0.03 MB
Replicate: average # of replicas added to proc= 34.548828 out of 32768 (0.105435 %)
  10032 atoms
ERROR: Replicate did not assign all atoms correctly (../replicate.cpp:675)
Last command: replicate 32 32 32 memory
</pre>

**Comment by stanmoore1** [comment]
Could be a bug with triclinic. If I turn that off it replicates fine.

**Comment by stanmoore1** [comment]
This does work for the rhodo benchmark.

**Comment by stanmoore1** [comment]
Here is a very simple LJ benchmark that I've modified to be triclinic: 
[in.lj.txt](https://github.com/lammps/lammps/files/1419913/in.lj.txt)

This test also fails on a single MPI rank with:

<pre>
LAMMPS (23 Oct 2017)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (../comm.cpp:95)
  using 1 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 1.6796 1.6796 1.6796
Created orthogonal box = (0 0 0) to (33.5919 33.5919 33.5919)
  1 by 1 by 1 MPI processor grid
Created 32000 atoms
  Time spent = 0.0162409 secs
Changing box ...
  triclinic box = (0 0 0) to (33.5919 33.5919 33.5919) with tilt (0 0 0)
  triclinic box = (0 0 0) to (33.5919 33.5919 33.5919) with tilt (0 8.39798 0)
Replicating atoms ...
  triclinic box = (0 0 0) to (134.368 134.368 134.368) with tilt (0 33.5919 0)
  1 by 1 by 1 MPI processor grid
Replicate::bounding box image: lo= -1 0 0  hi= 0 0 0
Replicate:: buf_all memory allocating       2.69 MB
Replicate: average # of replicas added to proc= 8.000000 out of 64 (12.500000 %)
  256000 atoms
ERROR: Replicate did not assign all atoms correctly (../replicate.cpp:675)
Last command: replicate 4 4 4 memory
</pre>

**Comment by stanmoore1** [comment]
Chris Knight has a pending fix for the triclinic case. @sjplimp recommended replacing the `memory` keyword in the replicate command with `bbox` (i.e. bounding box).

**Comment by akohlmey** [comment]
FYI: triclinic patch is merged, `memory` keyword changed to `bbox`, `comm_modify ring_neighbor` changed to `comm_modify ring_neighbors yes/no` for consistency with other `comm_modify` keyword.
some minimal documentation is added as well and the added code slightly reformatted to be closer to LAMMPS style (no tabs, no trailing blanks, 1 blank between if/for and parenthesis.

**Comment by stanmoore1** [comment]
For a 0.5 billion atom run, the replicate `bbox` option reduced my time spent in replicate from 20 minutes to less than 1 second.

**Comment by stanmoore1** [comment]
Though that comparison wasn't using the exact same # of MPI ranks in each of the two cases, but regardless this PR really helps speedup replicate.

**Comment by stanmoore1** [comment]
@akohlmey This looks good to me, what else needs to be done?

**Comment by akohlmey** [comment]
it'll probably need some testing for the tweaks in KSPACE/remap.cpp. Possibly a check with a triclinic system using pppm, and documenting the speed differences.
outside of that, i'd say @sjplimp should have a closer look next and then merge it, if he likes it. i'd expect we'll be aiming to have the next stable release in early december, so it'll be good to give these modifications some airing and add a few tests to the regression suite with those changes enabled.

**Comment by cjknight** [comment]
FWIW, the replicate, comm->ring, and remap/pppm changes are all independent of one another and could be separately merged one at a time.

**Comment by stanmoore1** [comment]
I tested this PR for a triclinic SPC/E water system and it works fine as far as I can tell, but I'm guessing Steve will have some comments. I'd like to break out the replicate files into a new PR so it can get merged faster.

**Comment by stanmoore1** [comment]
I split out the replicate changes as PR #723.

**Comment by stanmoore1** [comment]
@akohlmey I'm ready to assign this to Steve for his consideration as soon as the Jenkins runs finish, unless you have any more changes.

**Comment by stanmoore1** [comment]
@sjplimp should look at and address these comments though: 
https://github.com/lammps/lammps/pull/713/files#diff-724bbf33c6f79d111ed053a7c2187e29L461
```
// ask Steve Plimpton about method to more accurately determine
// maximum number of procs contributing to pencil
```
https://github.com/lammps/lammps/pull/713/files#diff-c404edb6d8291da8e0a28db0672bd4d5R759
```
// -- good chance this isn't appropriate for 100% use cases...
```

**Comment by akohlmey** [comment]
@stanmoore1 as pointed out in an earlier comment, the remap changes should be selectable (and probably off by default or the default should be selected on some heuristic based on the number of MPI ranks per "world") via `kspace_modify`, so that we people can select either code path in case of issues.

**Comment by stanmoore1** [comment]
>as pointed out in an earlier comment, the remap changes should be selectable (and probably off by default or the default should be selected on some heuristic based on the number of MPI ranks per "world") via kspace_modify, so that we people can select either code path in case of issues.

@akohlmey I believe @cjknight addressed this in 077d814

**Comment by stanmoore1** [comment]
Assigned to @sjplimp.

**Comment by akohlmey** [comment]
@sjplimp is there something left in this pull request that we want to merge into LAMMPS? it would need to be updated to recent changes to upstream. i can try doing the latter. otherwise, we should just close it.

**Comment by cjknight** [comment]
Yup, sure thing. I’ll take a look after machines come out of maintenance.

**Comment by cjknight** [comment]
Here’s a quick update; mixed results so far…

The rhodo system used here is weak-scaled using 46,785 particles per MPI rank (16 MPI ranks per BG/Q node), which maps to my 36B atoms on 0.75M MPI ranks problem. For 100-step runs (arbitrary number to check consistency for several steps), I see the following “Total wall time” times. The last column is the “special bonds CPU” time in seconds, which largely accounts for the increased runtime relative to my ring() hack for larger node counts.


#nodes   orig  chris  rendezvous   rendezvous-special
512   0:16:37    0:04:26   0:04:36   9.30038
1024  0:29:00   0:04:26   0:05:18   42.2376
2048  0:49:14   0:04:35   0:07:42  171.131
4096   —           0:04:41   crash


Rendezvous is definitely an improvement over the original ring() implementation. I didn’t profile the 2048-node (32,768 ranks) case yet. The crash at 4096 nodes looks like it’s coming a realloc() in Atom::add_callback(). I’m trying to reproduce the issue on fewer nodes to make running a debugger easier.

chris

**Comment by sjplimp** [comment]
@cjknight Thanks for running these tests.  So the 2048 node case is 1.5B atoms?
That crash is at an odd location, where the memory involved is tiny.  Can you tell
when during the setup it happens?  I don't think that would have anything to do with
specia bonds setup.  Better news is that I realized there is a way to do this rendezvous
operation with much less comm (and memory).  So I will post an updated version
you can try.  Possibly today, but maybe next week.  I'd wait to debug the memory
issue in case it goes away with the new version.

**Comment by sjplimp** [comment]
@cjknight I just pushed my latest changes to PR #1238.  I'm hoping it will be faster
than the previous, and also possibly fix the crash on 2048 nodes you had.  One new Q.
The setup of fix shake for rhodo also does ring comm.  I have not yet added a rendezvous replacement in fix shake.  Does your version with the fast setup for rhodo include your
optimized ring comm for SHAKE as well?  In which case differences between your version
and my newest version for total setup (or wall) time, could be mis-leadiing if the SHAKE
setup time is included.

**Comment by sjplimp** [comment]
@cjknight Hi Chris - just pushed more changes to PR #1238 which now includes
the new algorithm for fix shake setup.  So if you now run a huge rhodo problem I'm interested
to see if setup for both special_bonds and shake is now more scalable to large proc count.
Also if the run time (e.g. 100 step benchmakr) is the same as in your previous tests.
I don't think the latter should unless something about the setup is putting
data structs in different orderings (don't think it should).  Thanks!

**Comment by cjknight** [comment]
@sjplimp <https://github.com/sjplimp> Hi Steve, 

Just grabbed the latest changes before machine started draining for the 32768-node test. With the previous PR changes, the rendezvous wall times were much closer to the times with my version (which used the modified ring comm also in SHAKE) and the 4096-node test was successful. 

rendezvous2
#nodes   #atoms  orig           chris  rendezvous   rendezvous-special
512        384M      0:16:37    0:04:26   0:04:32    4.55119
1024      768M      0:29:00    0:04:26   0:04:42    5.50346
2048     1.54B      0:49:14     0:04:34   0:04:56    6.22061
4096     3.07B          —          0:04:43  0:05:53    23.8532



With the latest changes, I ran a 512-node job and see further improvement in the wall time. 

rendezvous3
#nodes   #atoms  orig           chris  rendezvous   rendezvous-special
512        384M      0:16:37    0:04:26   0:04:27    4.024

1024- and 2048-node tests with the latest changes should run by morning. The 32768-node job should start around this time tomorrow night with the others {4096, 8192, 16384} following later in case there are any more changes you want to push in beforehand. I can queue up a full-machine job for completeness if the 32K-node job is successful, which would probably run Sunday or Monday night.

chris

**Comment by cjknight** [comment]
Unfortunately, the 4096- and 8192- node tests crashed in what looks to be the memory->create() call in FixShake::pre_neighbor() (fortunately with time for me to hold the two larger jobs). I’m trying to reproduce on smaller number of nodes to make debugging easier.

**Comment by sjplimp** [comment]
@cjknight If you mean these lines in FixShake::pre_neighbor ...
// extend size of SHAKE list if necessary
  if (nlocal > maxlist) {
    maxlist = nlocal;
    memory->destroy(list);
    memory->create(list,maxlist,"shake:list");
  }
then I can't imagine how they could fail.  That code has
been there for a long time.
@akohlmey you mentioned a memory issue with the rendezvous PR 
I believe - it is possibly related to the issue Chris is having with huge runs?

**Comment by akohlmey** [comment]
@sjplimp assigning this PR to you, so you can close it when the work is done. if you want to automate this, you can also put the text `closes #713` into the description field of PR #1238 . that will close this PR automatically when the other PR is merged.

**Pull request closed without merging**
