### PR TITLE
Improve lookup table accuracy

### PR DESCRIPTION
**Pull request by akohlmey**
When using fast table lookup through truncating the single precision floating point mantissa, there seems to be an inconsistency in computing the value of the variable `fraction`. Throughout the code, the truncated single precision number (`rsq_lookup.f`) is used rather than `rsq`. This pull request changes these code segments to use `rsq`. This should improve the accuracy of tabulation, since tables are all in double precision and their contents is computed using the (double precision) erfc() library function (and not the fast polynomial approximation).

### CODE REVIEW

**Comment by akohlmey** [comment]
@timattox you may want to have a look at this as it touches files in USER-DPD. I am certain the code was just copied and adapted, but if we make this change, it should be done consistent throughout LAMMPS. It will affect numerical output for tabulated styles with lookup tables, but should not affect the physics. The current behavior is that rsq is truncated to single precision before being doing linear interpolation, and my change will remove that truncation (for better accuracy and consistency).

**Comment by timattox** [comment]
I'm looking at it now.  Thanks for the heads up.

**Comment by akohlmey** [comment]
@sjplimp we should probably put this PR on hold until the erfc() changes are complete and merge them into master at the same time, so that we have only one patch introducing (small) numerical changes to lots of coulomb related pair styles.

**Comment by stanmoore1** [comment]
>>hold until the erfc() changes are complete

That would be nice for the regression testing.

**Pull request merged**
