### PR TITLE
Adding the kokkos variants for lj/cut/dipole/cut and lj/expand/coul/long

### PR DESCRIPTION
**Pull request by ndtrung81**
**Summary**

This PR adds the kokkos variants for lj/cut/dipole/cut and lj/expand/coul/long, adds AtomVecDipoleKokkos, and enables FixNVESphereKokkos to update dipole.

Note: examples/dipole/in.dipole can be used to test lj/cut/dipole/cut/kk.

**Related Issue(s)**

N/A

**Author(s)**

Trung Nguyen (U Chicago)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Should maintain.

**Implementation Notes**

Some changes to the top-level files were made: 1) re-arranged tdual_float_1d_4 in kokkos_type.h to define mu-related structs. 2) added k_mu to atom_kokkos.h, 3) added MU_MASK to atom_masks.h, 4) copymode is checked in the destructor of the parent classes to avoid memory access errors.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by stanmoore1** [comment]
@ndtrung81 this is missing `atom_vec_dipole_kokkos`, probably just got omitted?

**Comment by ndtrung81** [comment]
@stanmoore1 oops thanks for pointing this out, added them in [e19f873](https://github.com/lammps/lammps/pull/3623/commits/e19f873f4904b1e49a839439559aeb9be666493d)

**Comment by stanmoore1** [comment]
I confirm I get the correct thermo output for 1 and 4 GPUs (vs CPU) for the dipole example.

**Review by stanmoore1 — APPROVED** [review]
I approve

**Comment by ndtrung81** [comment]
thanks @stanmoore1

**Comment by stanmoore1** [comment]
> thanks @stanmoore1

Thanks to you too @ndtrung81, nice work!

**Comment by akohlmey** [comment]
@ndtrung81 @stanmoore1 this still produces a segmentation fault when loading a data file as part of the pair style unit test for lj/cut/dipole/cut/kk

```
Thread 1 "test_pair_style" received signal SIGSEGV, Segmentation fault.
0x00007ffff5ad4c66 in LAMMPS_NS::AtomVecDipole::data_atom_post (this=0x59f4a0, ilocal=<optimized out>) at /home/akohlmey/compile/lammps/src/DIPOLE/atom_vec_dipole.cpp:68
68	  double *mu_one = mu[ilocal];
(gdb) print mu
$1 = (double **) 0x0
(gdb) where
#0  0x00007ffff5ad4c66 in LAMMPS_NS::AtomVecDipole::data_atom_post (this=0x59f4a0, ilocal=<optimized out>) at /home/akohlmey/compile/lammps/src/DIPOLE/atom_vec_dipole.cpp:68
#1  0x00007ffff55e3f47 in LAMMPS_NS::AtomVecHybrid::data_atom_post (this=0x59a4c0, ilocal=0) at /home/akohlmey/compile/lammps/src/atom_vec_hybrid.cpp:367
#2  0x00007ffff55dbfaa in LAMMPS_NS::AtomVec::data_atom (this=0x59a6f0, coord=<optimized out>, imagetmp=<optimized out>, values=std::vector of length 15, capacity 16 = {...}, extract="1")
    at /home/akohlmey/compile/lammps/src/atom_vec.cpp:1723
#3  0x00007ffff55c9210 in LAMMPS_NS::Atom::data_atoms (this=0x55e980, n=n@entry=29, 
    buf=0x7ffff0b15010 "10 1 2.018528355553699 -1.4283966846517357 -0.9673352727113302 2 0.07 12.0107 0.238732414637843 0.598323762260729 0.6736604951785857 0.4338089588170229 0 0 0", id_offset=0, mol_offset=0, type_offset=0, 
    shiftflag=0, shift=0x5ac0b8, labelflag=0, ilabel=0x5a4820) at /home/akohlmey/compile/lammps/src/atom.cpp:1179
#4  0x00007ffff58d35a0 in LAMMPS_NS::ReadData::atoms (this=this@entry=0x5abe50) at /home/akohlmey/compile/lammps/src/read_data.cpp:1396
#5  0x00007ffff58dc9b5 in LAMMPS_NS::ReadData::command (this=0x5abe50, narg=<optimized out>, arg=0x59a3a0) at /home/akohlmey/compile/lammps/src/read_data.cpp:622
#6  0x00007ffff57b81a5 in LAMMPS_NS::Input::execute_command (this=this@entry=0x575bb0) at /home/akohlmey/compile/lammps/src/input.cpp:852
#7  0x00007ffff57b8442 in LAMMPS_NS::Input::file (this=this@entry=0x575bb0) at /home/akohlmey/compile/lammps/src/input.cpp:302
#8  0x00007ffff57b8641 in LAMMPS_NS::Input::file (this=0x575bb0, filename=<optimized out>) at /home/akohlmey/compile/lammps/src/input.cpp:343
#9  0x000000000040e484 in operator() (filename="/home/akohlmey/compile/lammps/unittest/force-styles/tests/in.dipole", __closure=<synthetic pointer>) at /usr/include/c++/12/bits/basic_string.h:233
#10 init_lammps (argc=argc@entry=12, argv=argv@entry=0x7fffffffc9d0, cfg=..., newton=newton@entry=true) at /home/akohlmey/compile/lammps/unittest/force-styles/test_pair_style.cpp:113
#11 0x00000000004188da in PairStyle_kokkos_omp_Test::TestBody (this=<optimized out>) at /home/akohlmey/compile/lammps/unittest/force-styles/test_pair_style.cpp:648
```

**Comment by ndtrung81** [comment]
@akohlmey thanks for pointing out the bug. Maybe [44ff363](https://github.com/lammps/lammps/pull/3623/commits/44ff3631694d281fc0bc7afa6a3b190fd3efbd36) can fix it.

**Comment by ndtrung81** [comment]
The test with the pair style lj/cut/dipole/cut/kk now fails due to significant numerical differences in the forces vs reference values.

**Comment by akohlmey** [comment]
> The test with the pair style lj/cut/dipole/cut/kk now fails due to significant numerical differences in the forces vs reference values.

Yes, there are two issues. I already fixed the missing application of factor_lj to scale the forces.
Now I am still seeing a mismatch between evdwl + ecoul and:
```
compute pe all pe/atom pair
compute sum all reduce sum c_pe
```

The pe/atom sum is 0.0. I compared the lj/cut/dipole/cut/kk code with lj/cut/coul/cut/kk but cannot find the difference.

**Comment by stanmoore1** [comment]
>The pe/atom sum is 0.0. I compared the lj/cut/dipole/cut/kk with lj/cut/coul/cut/kk but cannot find the difference.

That is helpful, I can take a look

**Comment by akohlmey** [comment]
> > The pe/atom sum is 0.0. I compared the lj/cut/dipole/cut/kk with lj/cut/coul/cut/kk but cannot find the difference.
> 
> That is helpful, I can take a look

Here is a standalone reproducer input. Simpler to work with than the pair style tester code. ;-)
[in.dipole.txt](https://github.com/lammps/lammps/files/10573996/in.dipole.txt)
[data.dipole.txt](https://github.com/lammps/lammps/files/10573997/data.dipole.txt)

**Comment by akohlmey** [comment]
> > The pe/atom sum is 0.0. I compared the lj/cut/dipole/cut/kk with lj/cut/coul/cut/kk but cannot find the difference.
> 
> That is helpful, I can take a look

I think I have figured it out: the ev_tally_xyz_atom() function in `pair_lj_cut_dipole_cut_kokkos.cpp` only tallies the per-atom virial, not energy. Overall the code calling the two tally functions seems a bit strange.

**Comment by ndtrung81** [comment]
@akohlmey thanks for pointing out the per atom energy sum issue. I can fix the energy sum now in my local copy, the per-atom virial terms are still not correct though. Will try to fix it. The two tally functions are strange because they were adopted from the pair gran history kokkos (the only one that provides tally_xyz), and I figured out that I can drop one of them to resemble a regular pair style.

**Comment by ndtrung81** [comment]
@akohlmey the changes in 0823117 give consistent results with the CPU version for the standalone input you shared. I am building and running the unit test on my machine.

**Comment by akohlmey** [comment]
> @akohlmey the changes in [0823117](https://github.com/lammps/lammps/commit/0823117ec551c9258416fee4df8b7f39281cf394) give consistent results with the CPU version for the standalone input you shared. I am building and running the unit test on my machine.

It will likely produce the same results (unless something else is off), since the input is a stripped down version of what the tester runs.

**Comment by stanmoore1** [comment]
I think this needs a small tweak for full neigh lists, give me a bit and I'll push an update

**Comment by stanmoore1** [comment]
This passes all my tests now, including per-atom energy and virial.

**Comment by ndtrung81** [comment]
@akohlmey the unit test passed as you expected. This is a pretty good practice for me with the unit tests, thanks!

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
