### PR TITLE
Add Kspace NVPL FFT support

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

Adds support to build KSpace and its KOKKOS variants with [NVPL FFT](https://docs.nvidia.com/nvpl/_static/fft/index.html), which is the optimized FFT from NVIDIA for Grace CPUs.

~Also fixes a bug in one of the Kokkos files.~

**Related Issue(s)**

**Author(s)**

@rbberger 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Review by sjplimp — APPROVED** [review]

**Review by stanmoore1 — APPROVED** [review]
I approve

**Comment by akohlmey** [comment]
@rbberger Shouldn't there be updates for the documentation with this change?

**Comment by rbberger** [comment]
@akohlmey Ok, I'll look into that.

**Comment by akohlmey** [comment]
Thanks. grep suggests to edit doc/src/Build_settings.rst. Perhaps, you should also contribute a "machine" makefile for GNU make (or declare it a CMake-only feature ;-) )

**Comment by rbberger** [comment]
Won't make a machine file, since NVPL isn't installed on any systems I know of. But I added the docs for Makefiles anyway.

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
