### PR TITLE
User hadress

### PR DESCRIPTION
**Pull request by hadress**
Please find the new versions of the H-ADRESS source files.
The previous session might have been deleted. Sorry. It was my fault. Previously the session number was #79, now #100!

In the following, I have listed Axel's comment:
(1) it needs to be correctly integrated into the standard make yes-package, make no-package system

- I have included the install.sh into the directory.

(2) it needs to be updated with respect to the current version of LAMMPS, e.g. the modified atom.h is not compatible with what is currently used. also addition of the new per-atom fields need to follow the best practice of other (user) packages.

- I have applied all the modification into the latest version of LAMMPS.

(3) the style names should be made consistent with the existing conventions (e.g. all lowercase for user visible styles), i would suggest: full/hars for the atom style and lj/cut/coul/hars/aa and lj/cut/hars/cg

- They are all changed accordingly.

(4) documentation should be moved to doc/src (.txt files only, the PR should not include .html files. they will be recreated anyway), examples to examples/USER/haddress

- They are moved.

(5) example files must be small and must not contain non-portable binary restart files. only data files may be included. data files should ideally be under 2MB

- It has been changed.

All the best,
<Maziar>

### CODE REVIEW

**Comment by akohlmey** [comment]
Sorry, but this is still not acceptable. There are two major issues:
- your package contains modified versions of standard source files. this is not acceptable. uninstalling your package will remove them completely and break compilation and or functionality. these modifications will have to be included in the original version and that has to be done in a way that does not collide with any other existing package. also, the modifications to atom.h are not following the best practice example from other packages, i.e. moving new class members to a separate section prefixed with a comment indicating which package these class members are used for. compare USER-EFF, USER-DPD and so on.
- your modifications are based on an old development check out. lots of things have changed since. for example the layout of the documentation tree is different. when contributing changes, they will always be merged into the development head revision, so it is best practice to upgrade to that state before filing a pull request

Two minor issues are:
- the user-hadress package has not been added to the suitable variables src/Makefile, so they are actually not tested for clean compilation on our typical set of compile settings with TravisCI
- The documentation contains html files, they are not needed at this point and i will have to remove them, as they are automatically generated during the publishing of a new patch. Mind you, if you update to the current development head, you can fully test the documentation generation, as we have now moved all required tools into the doc tree. It merely needs a python3 installation with virtualenv and will not run without.

**Comment by hadress** [comment]
Dear Axel,

I again followed your instruction to prepare the files accordingly.
Hope that the collaboration of both (high) temperature and (high) humidity here has not deflected my attention!

All the best,
<Maziar>

**Comment by akohlmey** [comment]
Some more comments:
- please don't push every commit to the remote repo. Complete your changes, test them and _then_ push to the remote repo. Every push triggers a full rebuild at TravisCI, but that is pointless unless you have fixed your installation/compilation issues. you can follow the link from the pull request page on github to the matching builds on TravisCI and there inspect the error messages. The builds on TravisCI are likely to find issues, that you may not have noticed, e.g. 64-bit integers or C++ code that is accepted by GCC, but not by Clang.
- your package doesn't seem to be needing any external libaries . Why mess with Makefile.package and Makefile.package.settings? This is bound to fail, if you don't know what you are doing. In fact, none of your included styles seem to depend on any existing code, so you should just leave out the Install.sh file completely. That one is only needed, if some files depend on other optional files being installed. It is easy to test for that, too: Take a clean checkout, install only your package and do a "make mpi" and "make serial". if it goes through, you don't need an Install.sh file.
- i see a modification to read_data.cpp, but i don't see the corresponding modification to write_data.cpp. also, shouldn't there be a corresponding modification to read/write_restart?

**Comment by akohlmey** [comment]
On Fri, Jun 24, 2016 at 10:18 AM, hadress <notifications@github.com> wrote:

> Dear Axel,
>
> I again followed your instruction to prepare the files accordingly.
> Hope that the collaboration of both (high) temperature and (high) humidity
> here has not deflected my attention!
>

​please see the the failures of the integration testing on travis ci. you
obviously haven't even tested your changes properly, as compilation fails
almost instantly. it is becoming extremely frustrating on my side to have
to point out even the most obvious necessary changes and corrections. we
aim to have a high-quality source code package, but your contribution is
still failing the most minimal requirement (clean compilation).

axel.



> All the best,
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/lammps/lammps/pull/100#issuecomment-228357977>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AARp459ep5zN3WkvX00fWvMgZFfVlRCYks5qO-cwgaJpZM4I52hY>
> .
>



-- 
Dr. Axel Kohlmeyer  akohlmey@gmail.com  http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste. Italy.

**Comment by hadress** [comment]
Sorry for the compilation error. I have thought that it was required to have Install.sh in the directory. I have deleted it and installed and uninstalled the packages several times through "make yes-user-hadress" and ... and it seems working on my PC. Additionally I have monitored the travis ci test and everything is O.K.
Yes, you are right about the independency of USER-HADRESS package.

Concerning the read_data.cpp, we need to read the information from the data file at the beginning. Those information will be written and read in restart files through the part of the code in atom_vec_full_hars. Up to this time, I have simulated several physical cases and I have not had any problem in restarting the simulations. 
Since the particle resolutions are fixed by their position in simulation box and representative atoms are fixed during the simulation runs (they are not dynamical properties), I by myself have not been in need of writing those atoms' properties. 

Please let me know if you have something else in your mind.

All the best,
<Maziar>

**Comment by akohlmey** [comment]
I've merged the code and made some adjustments, because the integration of the documentation was still not correct. There are still some open issues, but i'll address them separately in the issue tracker.

**Comment by hadress** [comment]
Thanks Axel!

I will look forward for your comment.

**Comment by akohlmey** [comment]
please see https://github.com/lammps/lammps/issues/106

**Pull request merged**
