### PR TITLE
Computation of forces/torques on rigid bodies moved to post_force

### PR DESCRIPTION
**Pull request by craabreu**
## Purpose

To move the computation of resultant forces and torques over rigid bodies from the routine *final_integrate* to the routine *post_force* in both fix rigid and fix rigid/small.

By separating these computations from the motion integration, they become available for new fixes which might possibly deal with rigid bodies and modify the forces on atoms, thus requiring recomputation of the resultant forces and torques.

In addition, it seems more logical to classify these computations as a post-force task, rather than a final-integration task.

## Author

Charlles Abreu
Federal University of Rio de Janeiro
Brazil

## Backward Compatibility

~~The modification is supposed to go unnoticed in the current LAMMPS implementation. It only creates new possibilities for future additions.~~

The modification will impose an additional constraint to the order fixes defined in the input script. Once the first fix rigid/* or rigid/small/* is defined, other fixes that include post-force tasks will no longer be allowed, unless their styles are rigid/* or rigid/small/* as well.

## Implementation Notes

**Testing**: With the original LAMMPS code stored at ~/Software/lammps and the modified code stored at ~/Projects/lammps, the following test was executed after compilation with `make yes-rigid && make mpi`:

```bash
cd ~/Projects/lammps/examples/rigid
for dir in Projects Software; do
  ~/$dir/lammps/src/lmp_mpi -in in.rigid > $dir.out
done
diff Projects.out Software.out 
```

The `diff` command accused differences in cpu times only. All numerical results were identical. A similar test was done for fix rigid/small.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [X] The source code follows the LAMMPS formatting guidelines

## Further Information

In our research group, we already take advantage of this modification in the development of a new fix that performs expanded-ensemble simulations for alchemical free-energy calculations.

### CODE REVIEW

**Comment by akohlmey** [comment]
I disagree with the claim, that this will be fully backward compatible. Moving the computation of per-body forces and torques makes the fix become subject to the order of when fixes are created when there are other fixes that change forces, e.g. fix setforce, fix addforce or fix aveforce. So at the very least, it has to be guaranteed, that this fix is the last fix to run during the post_force hook and that is not trivial to get right, since there may be multiple fix rigid instances.

**Comment by craabreu** [comment]
That's true, @akohlmey. My mistake. Thanks for the feedback.

I have noticed that `fix poems`, which already has a `post_force()` method, also suffers from the problem you mentioned.

My new proposal is the inclusion of code in the `init()` method of fixes `rigid`, `rigid/small`, and `poems`. An an error message will be thrown if one attempts to define a non-rigid fix that contains a `post_force()` method after any rigid fix has been defined.

I still have a concern, though. Having a `post_force()` does not necessarily mean that a fix will change forces. This makes the new solution too restrictive. Maybe a warning message would be enough, letting the user decide what to do. Or else a `force_change_flag` could be included in the mother class Fix.

**Comment by akohlmey** [comment]
Thanks. I will take a closer look and also compare to what is done in fix shake/rattle that should have similar restrictions, too.

**Comment by akohlmey** [comment]
@craabreu what is your opinion on making this change a run-time option? since this is mostly just moving a couple of function calls around, we could introduce a flag, that could be set via `fix_modify` and by default, the current behavior remains, and only if requested, the computation of body forces and torques is advanced to `Fix::post_force()`. That way, no error exit needs to be programmed. If your add-on functionality would require a fix id from the rigid fix, you could even do the equivalent to the `fix_modify` command from inside your code and then things would be almost completely transparent with full backward compatibility.

**Comment by craabreu** [comment]
Thanks, @akohlmey. This is a smart solution. And it's easy to implement. I only think that the error exit (or warning message) should remain, just in case the user chooses to activate the flag but forgets to check the fix order. I'll be updating the pull request soon.

**Comment by akohlmey** [comment]
i agree, there should be no error, just a warning. i would suggest the following command text:
```
fix_modify  <fix-id> bodyforces early

fix_modify  <fix-id> bodyforces late
```
with `late` being the default.

**Comment by akohlmey** [comment]
FYI, i've now implemented the proposed change for fix rigid and rigid/small and pushed it into your pull request branch. Please give it a try. This is still incomplete, since also the nose-hoover variants of the rigid fixes need to be adapted. Those only provide `final_integrate()` but inherit `post_force()`.
Documentation is also still missing, but that is trivial to add. I'd like to get your feedback first. Since perhaps more changes are needed.

**Comment by craabreu** [comment]
Thank you, @akohlmey. I have already done all this stuff, except the documentation part. I didn't expect that you would spend time on this, so I decided not to push partial stuff. Sorry for that.

**Comment by akohlmey** [comment]
don't worrry about me. i had to do something to distract me from less pleasant duties and it wasn't much effort. as you can see from my push, there is no problem with pushing incomplete changes for as long as that is indicated. in fact, we often encourage people to do this to give feedback early and thus be more effective. ...and we strongly encourage submitting pull requests early and incomplete for any changes to existing styles that are not part of a user package by the same author. we've seen that this helps shaping the contributions to be cleaner and saves a lot of effort integrating them. so this latter case does apply here. that said, don't hesitate to do a forced push and overwrite my changes. or keep a copy of my stuff somewhere for reference.
however, we **definitely** also need to have the rigid/nh versions of styles updated for this set of changes or else there may be compatibility issues.

**Comment by craabreu** [comment]
1. Base classes FixRigid and FixRigidSmall now have a `modify_param` method to handle the keyword `bodyforces`. This method will be inherited by all sub-classes except FixRigidNHSmall, which already has one of its own. This is solved by adding a call to `FixRigidSmall::modify_param` inside `FixRigidNHSmall::modify_param`, in case the passed keyword is not identified. This will be required if `modify_param` is added to other child classes in the future.

2. Each instance of FixRigid or FixRigidSmall will check for posterior fixes with `post_force` tasks, but only regarding its own position. This is necessary because `bodyforces` can possibly be set as `early` for some instances and `late` for others. Each instance will throw an individual warning message, if necessary.

3. Although not related to the intent of this pull request, I've also changed the check regarding the existence of multiple rigid-body fixes. Instead of multiple warning messages, now only one message will appear.

4. All these features were added to FixPOEMS as well.

**Comment by akohlmey** [comment]
@craabreu are you going to update `fix_rigid_nh.{cpp,h}` and `fix_rigid_nh_small.{cpp,h}`?
since `FixRigidNH inherits `FixRigid::post_force()` but overrides `FixRigid::final_integrate()` and `FixRigidNHSmall` has the same relation with `FixRigidSmall`, these need to be adapted for the changes in their parent classes. Or else the bodyforces and -torques may be computed twice and thus would override the computation if it is done "early".

**Comment by craabreu** [comment]
Done. I have also excluded `apply_langevin_thermostat()` from the block of early/late computation. It is now handled at `post_force()` only, as before. This change seems to be unnecessary, but I decided to make it for the sake of evaluation.

**Comment by akohlmey** [comment]
@craabreu thanks a lot. i found and fixed one bug where the `fix_modify` argument processing from `FixRigidNH` was not properly forwarded to `FixRigid` (unlike in the FixRigidSmall case).
While checking that out and recompiling, i realized, that the multi-thread versions in `USER-OMP` will need updating as well. i'll look into that now. after that, i think this is good to be merged.

**Comment by craabreu** [comment]
Thank you, @akohlmey. The new feature (if eventually merged) will be helpful for me and hopefully for other developers as well.

**Comment by sjplimp** [comment]
Hi - What do your new fix(es) do with rigid body forces and how do
they get access to them (for both big and small rigid bodies?).  Also,
it seems like there are many use cases when a user might apply
other fixes with a post_force(), legitimately (or now not, if the rigid body
forces are computed earlier), and the warnings will be somewhat confusing.
E.g. using a langevin fix on non rigid-body atoms.

**Comment by craabreu** [comment]
@sjplimp In our application, we define a class of pair styles that depend on a coupling parameter lambda and a new fix that includes stochastic changes of lambda. As we do not know beforehand if a proposed change will be accepted, we compute and store all forces which do not depend on lambda (other pair sub-styles, bonded terms, etc), then we add the lambda-dependent terms before reverse-communication and post-force tasks. If the change is eventually accepted, the next step starts with updating the forces with the new lambda. This does not require recomputation of all forces, but does require rev-comm and post-force. This will work for rigid-bodies (either big or small) only if forces and torques on them are summed up early, that is, as a post-force task. This is the current version of our code: https://github.com/atoms-ufrj/USER-ALCHEMICAL/blob/master/fix_softcore_ee.cpp
Regarding the warnings, they will only appear if `fix_modify` is deliberately called with option `bodyforces early`, which I presume will happen only when the user knows exactly what he/she is doing. @akohlmey suggested this behavior for backward compatibility, and I totally agreed.
Please let me know if you have other questions.

**Comment by akohlmey** [comment]
@craabreu FYI, steve and i are working on getting your code merged (finally!!) while i am visiting him in ABQ. For several reasons it was delayed and now there were additional complications due to other changes that were added to mainline LAMMPS since. since this is our fault, we are now working on resolving the remaining issues. Most of it is done, hence the recent activity, but It looks like we introduced some issue with running the force computation early (or are missing something), so there will be additional changes before it can be merged, once one of us has figured out, what is wrong. If by chance, you see what could be the issue, don't hesitate to report it here and/or update your PR.

**Pull request merged**
