### PR TITLE
Hippy fixes

### PR DESCRIPTION
**Pull request by bathmatt**
**Summary**
Further testing with MPIAP-Unified with the HIPPYNN potential exposed a few bugs in the initial push.  This reduces the number of bugs and now we can use this potential with LAMMPS.

**Related Issue(s)**

**Author(s)**
mattb@nvidia.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@lubbersnick

**Comment by lubbersnick** [comment]
I have a version that works in this PR: https://github.com/lanl/hippynn/pull/27.
That PR is still in progress, and I need to add test files in case others are wanting to reproduce.

Right now, the MLIAP non-kokkos and MLIAP-kokkos have divergent APIs, which leads to some awkward code to cover both cases. In particular, the data.eatoms is a write-only array in regular MLIAP and a read-only array in Kokkos. The former is what makes sense to me (we want pair styles to write energies, but not to read them). But perhaps the change in kokkos has a motivation? @bathmatt Can you let me know why that change? I think it would be best to synchronize the APIs.

**Comment by athomps** [comment]
@bathmatt This is great progress.  Following on @lubbersnick comment, now would be a good time to bring the Kokkos and regular MLIAP APIs into agreement, both working with the latest version of HIPPYNN e.g. https://github.com/lanl/hippynn/pull/27.

**Review by athomps — APPROVED** [review]
I approve.

**Comment by bathmatt** [comment]
I'll open one with the lanl folks to make things consistent and more
flexible. They're swamped right now and I'm on vacation so...

Thanks

**Pull request merged**
