### PR TITLE
A pull request for an optimized ILP(ilp/graphene/hbn) potential 

### PR DESCRIPTION
**Pull request by run-towards-the-future**
**Summary**

This pair style, ilp/graphene/hbn/opt contains our optimizations in SWLMFF. Since LMFF is not tidy enough to be integrated with LAMMPS, we currently can only include an optimized ILP(ilp/graphene/hbn) potential as a pull request.

**Related Issue(s)**

**Author(s)**

Optimization author 1: Ping Gao (National Supercomputing Center in Wuxi, China)
E-mail: qdgaoping@gmail.com
Optimization author 2: Xiaohui Duan (National Supercomputing Center in Wuxi, China)
E-mail: sunrise_duan@126.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

There is no changes in the pull request will break backward compatibility for inputs.

**Implementation Notes**

For the first committing, we add a new pair style, ilp/graphene/hbn/opt.
And this pair style updates to the OPT package.
For the second committing, we improve the performance of p
[SC21-LMFF.pdf](https://github.com/lammps/lammps/files/8541776/SC21-LMFF.pdf)
air style, ilp/graphene/hbn/opt.
And this improvement updates to the OPT package.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system

**Further Information, Files, and Links**

The optimizations have been included in our published paper, titled "LMFF: Efficient and Scalable Layered Materials Force Field on Heterogeneous Many-Core Processors". 
Url = {https://doi.org/10.1145/3458817.3476137},
Doi = {10.1145/3458817.3476137},

### CODE REVIEW

**Review by akohlmey — CHANGES_REQUESTED** [review]
@run-towards-the-future thanks for your contribution. Unfortunately, it will need some additional effort before a more thorough review will be done, and it can eventually be merged into the LAMMPS distribution.
1) It needs to be implemented as a derived class which derives from PairILPGrapheneHBN instead of Pair. That way only modified/optimized functions need to be provided and only additional data members are required in the optimized class. Please see other classes in the OPT and OPENMP package as examples. This should significantly reduce code redundancy and the resulting maintenance effort in case of bugfixes.
2) We have changed how we indicate polymorphism: only the base class function implementation is labeled virtual, all functions that override it in a derived class must be labeled with an override postfix. Again, please see other classes in OPT and OPENMP as examples.
3) only functions that are overridden from the base Pair class should be added as "public", everything else should be "protected".

I have already updated the integration into the GNU make based build system and the manual. So that is done for you, but it also means you should pull from your fork before you continue working.

**Comment by run-towards-the-future** [comment]
Thank you for your updating some files.   
Now, we have made the modification you mentioned above. Please help us check whether the current work meets the merging requirements. 
Thank you very much.

**Comment by run-towards-the-future** [comment]
> @run-towards-the-future thanks for your contribution. Unfortunately, it will need some additional effort before a more thorough review will be done, and it can eventually be merged into the LAMMPS distribution.
> 
> 1. It needs to be implemented as a derived class which derives from PairILPGrapheneHBN instead of Pair. That way only modified/optimized functions need to be provided and only additional data members are required in the optimized class. Please see other classes in the OPT and OPENMP package as examples. This should significantly reduce code redundancy and the resulting maintenance effort in case of bugfixes.
> 2. We have changed how we indicate polymorphism: only the base class function implementation is labeled virtual, all functions that override it in a derived class must be labeled with an override postfix. Again, please see other classes in OPT and OPENMP as examples.
> 3. only functions that are overridden from the base Pair class should be added as "public", everything else should be "protected".
> 
> I have already updated the integration into the GNU make based build system and the manual. So that is done for you, but it also means you should pull from your fork before you continue working.

Thank you for your updating some files.   
Now, we have made the modification you mentioned above. Please help us check whether the current work meets the merging requirements. 
Thank you very much.

**Comment by akohlmey** [comment]
> Now, we have made the modification you mentioned above. Please help us check whether the current work meets the merging requirements

No. What you submitted is not correctly implementing derived classes in C++. For example you left the constructor and destructor unchanged and that leads to all kinds of memory corruption and inconsistent behavior. Because of that unit tests are failing with error messages about double free and corrupted memory from the malloc library.

Please consult your favorite C++ textbooks.

**Comment by dxhisboy** [comment]
It seems after commit `ef51fb7`, the derivation from `PairILPGraphenehBN` is correct. Also, I find that there is no need of neighbor list for ghost atoms (I guess it is because of some historical reason), so I modified the code in `init_style` (commit `b55b9f5`).

Also, an additional comment:
Since the optimization has eliminated the usage of some data structures from `PairILPGraphenehBN`. That might be the initial reason to derive from `Pair`. Meanwhile, most of those data structures are pointers that allocated in `ILP_neigh` and initialized as `nullptr` in `PairILPGraphenehBN`. Thus those pointers does not hurt too much.

**Review by akohlmey — APPROVED** [review]

**Comment by akohlmey** [comment]
@dxhisboy @run-towards-the-future thanks for the updates. I made some more cosmetic changes, ran tests with valgrind, and benchmarked the interlayer examples compatible with this optimized pair style. I didn't see any remaining issues and a substantial speedup. When paired with OPENMP package compatible pair styles, there is a bit more speed possible (even with 1 thread) due to optimized code paths in OPENMP using `-suffix hybrid opt omp`.

**Comment by oywg11** [comment]
@run-towards-the-future @dxhisboy Thanks for the contribution! I compared the optimized ILP and the original one, they give the same results and the former gives a 2x speed up.

**Review by oywg11 — APPROVED** [review]

**Pull request merged**
