### PR TITLE
Mliap so3

### PR DESCRIPTION
**Pull request by macstein**
**Summary**

SO3 descriptor feature is implemented in MLIAP module
**Related Issue(s)**

**Author(s)**
@athomps @macstein @qzhu2017

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Review by athomps — COMMENTED** [review]
I suspect the change to mliap_model_python_couple.pyx reverses a previous bug fix.  Please test that all MLIAP examples still work and be careful not to push old versions of source files.

**Comment by akohlmey** [comment]
> I suspect the change to mliap_model_python_couple.pyx reverses a previous bug fix. Please test that all MLIAP examples still work and be careful not to push old versions of source files.

Not just there. There are multiple places where bugfixes or improvements in upstream are reverted. Also, the branch is littered with commented out debug code that must be removed, unneeded include statements and we prefer to *not* have "using namespace std" to avoid namespace clashes (many STL classes have names that are the same or very similar to class members or utility functions). I can provide specific review statements at the individual lines in the submission, if needed.

**Comment by macstein** [comment]
Then, I would like to create new branch "mliap_so3_ver2" from current "master" branch. Then I will update new sources in "src/MLIAP" folder without touching any other sources.  I will remove the debugging codes and "stl name space". And I will finally test all examples. 
Do you think I can avoid these problems with this way?

**Comment by athomps** [comment]
Yes, I think that will work.  Make sure to do your own testing of the MLIAP examples as well.

**Comment by macstein** [comment]
I believe that I am ready to submit better PR named "mliap_so3_ver2".  Can you discard current PR of "mliap_so3" ? Then, can I submit new PR? Or, please let me know if there is a way I can update "mliap_so3_ver2" on current "mliap_so3" PR.

**Comment by akohlmey** [comment]
> I believe that I am ready to submit better PR named "mliap_so3_ver2". Can you discard current PR of "mliap_so3" ? Then, can I submit new PR? Or, please let me know if there is a way I can update "mliap_so3_ver2" on current "mliap_so3" PR.

a) you can close a pull request you submitted yourself, b) having an open pull request doesn't stop you from submitting another

**Pull request closed without merging**
