### PR TITLE
cmake: bump kokkos to v3.1.01

### PR DESCRIPTION
**Pull request by junghans**
**Summary**

Pull in latest kokkos bug fixes

**Related Issues**

**Author(s)**

@junghans 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

yes

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by junghans** [comment]
I leave updating the bundled version to @stanmoore1

**Comment by junghans** [comment]
> I leave updating the bundled version to @stanmoore1

Done! Please have a look.

**Comment by stanmoore1** [comment]
@junghans thanks!

**Comment by junghans** [comment]
@akohlmey FYI, for future update we might want to use `git-subtree`.

**Pull request merged**
