### PR TITLE
Package Reorganization (step 1)

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This implements the first step of Issue #2525. USER-MISC is the only remaining user package. For details please see the discussion there.

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Partially. Style names are unchanged or in the few cases where they were changes, the old name remains available as alias, so that inputs will continue to function.

**Implementation Notes**

This will require updates to integration testing.
The following changes were made:
- packages were renamed as discussed in #2525 
- examples/USER has become examples/PACKAGES
- examples/USER/misc has become examples/USER-MISC
- the Package lists have been merged and sorted by their new name. References to user (or standard) packages removed.
- the "meam/c" pair style is now "meam", but "meam/c" remains an alias (as was previously "meam").
- the scripts to check the documentation for listing all packages and styles have been updated as needed

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

### CODE REVIEW

**Review by sjplimp — APPROVED** [review]

**Review by athomps — APPROVED** [review]
Whew! That's a lot of changes. I think ML-IAP is okay.

**Comment by athomps** [comment]
The change USER-REAXC -> REAXFF is particularly pleasing to see. ReaxFF is finally called by its proper name.

**Comment by akohlmey** [comment]
> Whew! That's a lot of changes.

Was only doable with a reasonable effort courtesy of "Unix plumbing" and the power of `find`, `grep` and `sed`. :tada:

**Comment by akohlmey** [comment]
> I think ML-IAP is okay.

It is not ideal but nobody has come up with a better alternative. I had been thinking about ML-MLIAP, but that is redundant, or we ML-META, but that may be - while accurate - more confusing than helpful, since "meta" is so loaded with all kinds of conflicting connotations. So I've stuck with ML-IAP. That has the benefit that we don't need to rename anything else that uses "mliap" since that still matches.

**Comment by oywg11** [comment]
@akohlmey Hi Axel, thanks for renaming and categorizing the packages, I think it's more clear now.
However, I found a small issue regarding the interlayer potential "pair_ilp_graphene_hbn" and "pair_kolmogorov_crespi_full" in the INTERLAYER package: the new version of potentials outputs zero energies when I do MD simulations. Please see the attachments for my test result. I went through the codes and found there is a modification of the structure but I didn't find the reason for this issue (the key part of the potential is untouched so I guess this issue is related to the change of the structure). I also checked that until version 30Nov20, the output is correct (see attachment for test result). 
Can you help me to resolve this issue? Many thanks!

[log.30Nov20.txt](https://github.com/lammps/lammps/files/6986721/log.30Nov20.txt)
[gr_hBN_Cstack_2L_noH.data.txt](https://github.com/lammps/lammps/files/6986704/gr_hBN_Cstack_2L_noH.data.txt)
[in.grhBN.txt](https://github.com/lammps/lammps/files/6986705/in.grhBN.txt)
[log.30Jul21.lmp.txt](https://github.com/lammps/lammps/files/6986706/log.30Jul21.lmp.txt)

**Pull request merged**
