### PR TITLE
Extend compute pair to handle multiple instances of a sub-style in pair style hybrid

### PR DESCRIPTION
**Pull request by mkanski**
## Purpose

I'd like to contribute a tweak for compute pair, which makes possible to use it with sub-styles specified multiple times in a pair style hybrid or hybrid/overlay command. Additionally, this PR adds a check for `evalue` which restricts it to `epair`, `ecoul` or `evdwl`. Currently, any value can be used and LAMMPS won't complain.

## Author(s)

Michal Kanski (Jagiellonian University)

## Backward Compatibility

It shouldn't break backward compatibility

## Implementation Notes

I introduced additional keyword "nsub" which allows a user to choose which instance of a sub-style will be used in the compute. The type of energy for the compute (epair/ecoul/evdwl) is now specified with help of another keyword called "evalue". No other features of LAMMPS are affected.

Instead of using "nsub" and "evalue" keywords, we just check whether the keyword following the pair style is numeric and then it is considered the sub-style number when using multiple styles of the same kind. The error, if an unknown keyword is added is retained.

A simple test script is attached. It checks if the sum of partial energies is equal to total potential energy.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

[test_script.txt](https://github.com/lammps/lammps/files/2451896/test_script.txt)

### CODE REVIEW

**Comment by akohlmey** [comment]
@mkanski thanks for your contribution. i've had a closer look and made some experiments. i've changed it a bit to be consistent with other parts of LAMMPS addressing multiple sub-styles and to retain backward compatibility.

**Comment by sjplimp** [comment]
@akohlmey @mkanski I like adding this functionality, but not so much the syntax
It would be more consistent with
other LAMMPS commands to now make these optional keyword/value pairs, e.g.
compute ... pair pstyle evalue key/value key/value ...
where the user can add zero of more key/value pairs, i.e.
evalue epair/evdwl/ecoul
nth 1/2/3/N
This allows for easily parsing new key/value pairs in the future.

**Comment by sjplimp** [comment]
sorry, my compute ... command syntax had an extra "evalue", now it should
change to one of the key/value options

**Comment by akohlmey** [comment]
@sjplimp i disagree. the "nth" keyword would make it **different** from other commands in LAMMPS that simply add the number after the pair style name. what you ask for is was what @mkanski had originally implemented (calling it "nsub"). and i changed the "evalue"  keyword/value setting, because it breaks backward compatibility. however i kept the error out for unsupported keywords (which in the current version would be ignored).

i don't see what would be gained with changing the syntax in a backward incompatible way. we can always do that later, if somebody adds more features to this compute and this would become necessary and would provide a benefit.

**Comment by sjplimp** [comment]
@akohlmey I mis-read the doc page.  I thought there were now 2 optional arguments and they could
be in either order or needed to be in a particular order.  If you're saying the N is required
if the pair style is one of multiple hybrids, that' ok (what did compute pair do
with that case previously?).  What I don't want to do is have multiple optional trailing
args without using the key/value syntax.  That makes the parsing more complex and
brittle, particulalry as new options are added. Also more confusing for the user.
Also, I can't recall , are there other commands which use the style N syntax for hybrid substyles besides pair_coeff and pair_modify pair?

**Comment by akohlmey** [comment]
@sjplimp compute pair did not handle the case of multiple sub-styles of the same name before. it would simply fail. yes, in my implementation the following number is required when there are multiple sub-styles of the same name. this is following the scheme as it is in `pair_coeff`. the "nth" or "nsub" keyword would not really be an optional flag. there is one other command i recall, that deals with this issue, and that is fix adapt. in that case the syntax is "<sub-style name>:<number>". i vaguely remember, that there was some technical reason why we didn't go with "<sub-style name> <number>", but i cannot remember which.

at some point in the future, we might want to revisit this and make the syntax consistent throughout and using the style like in fix adapt with the colon may be a better choice for everything (including `pair_coeff`). but at the moment, my preference is for sticking with the following number after a blank syntax.

**Comment by sjplimp** [comment]
yes, that logic is good - you can merge this PR as-is

**Pull request merged**
