### PR TITLE
Sticker bonds

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

Made a small change to fix bond/swap to enable it to support a 2nd kind of bond-swapping model, e.g. for vitrification of a dense polymer mixture.  Also enhanced the doc page to clarify the two use cases and more clearly how the bond swapping algorithm works.

**Related Issue(s)**

N/A

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey I want to get a collaborator to read this new doc page before we merge.

**Comment by sjplimp** [comment]
@akohlmey Collaborator confirmed OK, so ready to merge

**Review by akohlmey — APPROVED** [review]

**Comment by stanmoore1** [comment]
Not sure why `atom_kokkos.cpp` was modified in this PR?

**Comment by akohlmey** [comment]
> Not sure why `atom_kokkos.cpp` was modified in this PR?

those are only whitespace changes...

**Pull request merged**
