### PR TITLE
Updates for RHEO package, including new optional comm features

### PR DESCRIPTION
**Pull request by jtclemm**
**Summary**

1) Cleaning up various computes/fixes in the RHEO package and associated BPM files. 
2) Unified arguments for fix/compute/pair/bond/dump forward and reverse comm methods. All now accept an optional size argument. (I didn't see a reason why fixes had to operate differently)
3) Remove restriction that speed of sound is constant, add ideal gas EoS
4) Updating references
5) Adding type-correction to velocity shifting

**Related Issue(s)**

NA

**Author(s)**

Joel Clemmer (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

NA

**Implementation Notes**

NA

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

NA

### CODE REVIEW

**Comment by jtclemm** [comment]
Currently the *forward_comm()* and *reverse_comm()* protocols for fixes have an optional *size* argument that isn't present for compute, dump, pair, or bond methods. In the RHEO package, it is very handy to have a similar argument for computes. To keep everything uniform, I went ahead and added a similar argument for all class types.

However, no pair, dump, or bond styles would currently use this optional argument. So I can also just revert if preferred..

**Comment by jtclemm** [comment]
~Piggybacked typo fix from #4364~ Moved to #4370

**Review by sjplimp — APPROVED** [review]

**Comment by akohlmey** [comment]
@jtclemm can you please check, if there need to be updates to https://docs.lammps.org/Developer_comm_ops.html and similar files due to your changes? I currently cannot check myself.

**Comment by jtclemm** [comment]
> @jtclemm can you please check, if there need to be updates to https://docs.lammps.org/Developer_comm_ops.html and similar files due to your changes? I currently cannot check myself.

Good call, done.

**Comment by akohlmey** [comment]
@jtclemm FYI. This branch has a conflict with upstream and you need to pull and merge in the current develop branch and resolve the conflict before it can be merged.

**Comment by Jasmine969** [comment]
@jtclemm Hi Clemmer. Thanks for your effort on RHEO. Inlet/outlet boundary conditions are important in hydrodynamics, but have not been implemented in either SPH or RHEO. I am reading your paper (Palermo et al., 2024, Physics of Fluids) these days, in which you mentioned that
> Due to the complexity of these boundary conditions, this feature is not yet been generalized for inclusion in LAMMPS as of
the time ofwriting.

I wonder whether there are any proceedings about the inlet/outlet bc. I am really looking forward to using them in my simulation. Finally, so sorry to revive this post after months.

**Comment by jtclemm** [comment]
Hi, I'm glad the package is of interest. Unfortunately, I do not currently have a timeline for when the inlet/outlet will be available. I am still working on the fix, and do still plan on adding it to the package. However, I'm currently prioritizing improving the stability of RHEO, adding more compatibility with the SPH package, and finding/fixing potential bugs (e.g. #4545). So finishing up the inlet fix is a ways down on my to do list.

I'll be sure to let you know though when I include it in a PR.

**Comment by Jasmine969** [comment]
Thanks a lot. For the time being,  I use fix deposit and fix evaporate as a makeshift of the inlet and outlet bc. But they will lead to unphysical velocity and pressure. Therefore, I do expect a physical inlet/outlet bc like those in CFD. Looking forward to your updates!

**Pull request merged**
