### PR TITLE
Bond & angle styles gaussian

### PR DESCRIPTION
**Pull request by evoyiatzis**
**Summary**

A new bond_style & angle_style based on the expression of multicentered gaussian-based potentials (DOI: 10.1002/polb.20380)

**Related Issue(s)**

No related issue

**Author(s)**

E. Voyiatzis, Royal DSM email: evoyiatzis@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Maintains backward compatibility 

**Implementation Notes**

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
Thanks for the contribution. It would be most helpful, if you could include a little usage example and perhaps also a yaml file for the unit test facility: https://docs.lammps.org/Build_development.html#code-coverage-and-unit-testing
The code would be more readable, if you could avoid the use of `this->`.

**Comment by evoyiatzis** [comment]
Hi @akohlmey 
I have removed the  "this->" construct to make the code more readable and added a short line with a reference in the rst file as a small usage example. Although I (think I) have followed the steps described in the manual, I have not been able to create a yaml file. The steps are:

git clone -b unstable https://github.com/lammps/lammps.git second_lammps  
cd second_lammps  
mkdir build; cd build
cmake -D ENABLE_TESTING=on  -C ../cmake/presets/all_on.cmake -D PKG_USER-INTEL=no -D PKG_GPU=no -D PKG_KOKKOS=no -D PKG_MPIIO=no -D PKG_USER-ADIOS=no  -D PKG_USER-LB=no -D PKG_USER-SCAFACOS=no -D PKG_USER-NETCDF=no -D PKG_USER-QUIP=no -D PKG_USER-VTK=no -D PKG_USER-H5MD=no  ../cmake
cmake --build .

It appears that the following packages have been compiled (output of ./lmp -help)
ASPHERE BODY CLASS2 COLLOID COMPRESS CORESHELL DIPOLE GRANULAR KIM KSPACE
LATTE MANYBODY MC MESSAGE MISC MLIAP MOLECULE MSCG OPT PERI POEMS PYTHON QEQ
REPLICA RIGID SHOCK SNAP SPIN SRD USER-ATC USER-AWPMD USER-BOCS USER-CGDNA
USER-CGSDK USER-COLVARS USER-DIFFRACTION USER-DPD USER-DRUDE USER-EFF USER-FEP
USER-MANIFOLD USER-MEAMC USER-MESODPD USER-MESONT USER-MGPT USER-MISC
USER-MOFFF USER-MOLFILE USER-OMP USER-PHONON USER-PLUMED USER-PTM USER-QMMM
USER-QTB USER-REACTION USER-REAXC USER-SDPD USER-SMD USER-SMTBQ USER-SPH
USER-TALLY USER-UEF USER-YAFF VORONOI

While in the build directory, I type 
env TEST_ARGS=-s ctest -V -R BondStyle ../unittest/force-styles/tests/bond-harmonic.yaml
and I get the following message
UpdateCTestConfiguration  from :/home/envog/second_lammps/build/DartConfiguration.tcl
Parse Config file:/home/envog/second_lammps/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/envog/second_lammps/build/DartConfiguration.tcl
Parse Config file:/home/envog/second_lammps/build/DartConfiguration.tcl
Test project /home/envog/second_lammps/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
No tests were found!!!

I would appreciate your help

**Comment by akohlmey** [comment]
> While in the build directory, I type
> env TEST_ARGS=-s ctest -V -R BondStyle ../unittest/force-styles/tests/bond-harmonic.yaml

this is wrong. you don't give the yaml file as an argument. that is automatically selected from the name of the test. you can see all available tests with:

ctest -N

then you can narrow down the tests you want to use either with a regular expressions. for example:

ctest -R BondStyle:harmonic$

will run only the test for bond style harmonic (you need the "$" to terminate the regular expression or else it may match multiple tests). adding "-V" tells ctest to be more verbose and "env TEST_ARGS=-v" tells the underlying googletest library to be more verbose (requires -V to be effective). You can also select tests by their test number etc. as explained in the ctest docs.

The "-s" flag is to **reset** a test, which should only be applied if you change something or try to build a new test from an existing template. If you add a new YAML file to the tests folder, you must run `cmake .` to have the test detected and added. 

> I would appreciate your help

**Comment by evoyiatzis** [comment]
I am completely ignorant of ctest and its functionality. I guess I am still making some mistake(s) because when I type 
ctest -N 
in the command prompt, I get the following list of tests
Test project /home/envog/developing_lammps/build
  Test  #1: Tokenizer
  Test  #2: MemPool
  Test  #3: Utils
  Test  #4: FmtLib
  Test  #5: MathEigen
  Test  #6: AtomStyles
  Test  #7: PairUnitConvert
  Test  #8: PotentialFileReader
  Test  #9: EIMPotentialFileReader
  Test #10: FileOperations
  Test #11: DumpAtom
  Test #12: DumpAtomGZ
  Test #13: DumpCustomGZ
  Test #14: DumpCfgGZ
  Test #15: DumpXYZGZ
  Test #16: DumpLocalGZ
  Test #17: DumpCustom
  Test #18: DumpCfg
  Test #19: SimpleCommands
  Test #20: LatticeRegion
  Test #21: KimCommands
  Test #22: ResetIDs
  Test #23: LibraryOpen
  Test #24: LibraryCommands
  Test #25: LibraryProperties
  Test #26: LibraryConfig
  Test #27: LammpsClass
  Test #28: InputClass
  Test #29: FortranOpen
  Test #30: FortranCommands
  Test #31: PythonPackage
and there is no test for bonds/angles. If i use the command
ctest -R BondStyle:harmonic$
I get the reply 
Test project /home/envog/developing_lammps/build
No tests were found!!!
Any idea what I am messing up?

**Comment by akohlmey** [comment]
> I am completely ignorant of ctest and its functionality. I guess I am still making some mistake(s) because when I type
[...]
> Any idea what I am messing up?

Please check your CMake output. There should be some reference to the YAML library. If the suitable development package is not found, you may see the message: Skipping tests because libyaml is not found

**Comment by akohlmey** [comment]
FWIW, I have just hacked together a pull request that will download and compile a recent version of the yaml library, if the required development files cannot be found: #2476 

The dependency is mentioned in the docs, but most of the testing/development docs are new and - as you may have noticed - we are now slowly moving toward making the inclusion of tests in the unittest tree a requirement for contributions. That is, for contributions where there are a sufficient number of examples already implemented. We are still at less than 40% code coverage and are mostly covering the proverbial low hanging fruit, so this is going to be a "process" and experiences like with this PR will help pointing out where improvements are needed. So far the main goal was to increase coverage and avoid failures during integration testing.

**Comment by evoyiatzis** [comment]
> Please check your CMake output. There should be some reference to the YAML library. If the suitable development package is not found, you may see the message: Skipping tests because libyaml is not found

@akohlmey  You are correct: the libyaml was not installed (I had installed only the python bindings but not the actual library) and I was overlooking the message from CMake. Once I installed libyaml everything worked fine. Thanks

**Comment by evoyiatzis** [comment]
@akohlmey  You have given a nice description of how to add a unit test on #2099 . I found it very useful.
Maybe you could add this in the user manual even as a stub.

**Review by akohlmey — APPROVED** [review]
Updated it to current master and fixed a few minor issues in the documentation.

**Review by rbberger — APPROVED** [review]

**Pull request merged**
