### PR TITLE
EES wall potential

### PR DESCRIPTION
**Pull request by aershadinia**
This code is meant to calculate EES , potential between ellipsoidal particles and semi-infinite LJ wall. 
At first I tried to add it to a separate directory but now my code is under MISC directory. 
To find out more about the usage of this code you can take a look at its doc file. 

This code is brought to you by Abdoreza Ershadinia.

### CODE REVIEW

**Comment by akohlmey** [comment]
1) MISC != USER-MISC, your contribution should be included in the latter, not the former
2) to be consistent with the rest of LAMMPS, your examples should be in `examples/USER/misc/ees`
3) your documentation should mention under "Restrictions" that a) this command requires the USER-MISC package installed, and b) that it can only be applied to extended particles.

**Comment by akohlmey** [comment]
@aershadinia i've made some (mostly cosmetic) updates to the code, so that it is more in line with the rest of LAMMPS. i also changed the input examples, so they are more useful for regression testing and included reference outputs. please check it out whether this matches with your reference code.

i would like to suggest one more change: please merge the two doc files the two wall fixes. since a lot of the explanation is shared anyway and the docs for fix wall/region/ees mostly refer to fix wall/ees already.

**Comment by aershadinia** [comment]
I checked the examples. They work fine. I also changed some parameters like time step and run steps in order to show the interaction better. actually I made the simulation time longer to assure that particles hit hit the wall. 
About the doc files, In my opinion since they are basically two different fixes and they use different set of arguments, combining them into one file may cause some confusion. As you said and I am totally agree, the doc file for "fix wall/region/ess" refers to "fix wall/ees" but the purpose of dividing them was to show how one should use arguments.

**Comment by akohlmey** [comment]
LAMMPS already has too much clutter and redundancy in the manuals for the many, many commands, and this would be one piece more that can be easily avoided before it is added. There are plenty of precedents, where completely different implementations share the same documentation page because from the user perspective they do the same thing (e.g. the various fix rigid variants, multiple lennard jones pair styles etc.). You can easily achieve a visual "distance" between the two fixes, by adding an empty line to separate the examples and explain the different command lines in two different paragraphs. Please merge the two doc files. thanks.

**Comment by aershadinia** [comment]
Ok. I will do as you said.

**Comment by akohlmey** [comment]
made a few more changes to the docs and integrated it into the doc files properly. this is now marked ready for inclusion into LAMMPS

**Comment by aershadinia** [comment]
Thank you very much. What should I do next? Do in need to request for another pull?

**Comment by akohlmey** [comment]
There is nothing that you need to do at the moment. Updating the repository automatically updates the pull request.

**Pull request merged**
