### PR TITLE
Adding triclinic support to kspace_style pppm/tip4p

### PR DESCRIPTION
**Pull request by stanmoore1**
Adding triclinic support to kspace_style pppm/tip4p

### CODE REVIEW

**Comment by sjplimp** [comment]
I did the resolving on my box and pushed them back into GHub master - so this PR can
be deleted.

**Comment by akohlmey** [comment]
@sjplimp there must be something not done quite right with your resolution of merge conflicts workflow or else this should be closed automatically. in fact, none of the commits listed in this pull request show up in the commit history of "master". with a correctly performed merge and conflict resolution, they should be included, which makes me suspect, that you are working around git here rather than using it.

**Comment by stanmoore1** [comment]
I had a similar issue where I resolved a merge conflict and then lost the commit history in the lammps_USER-DPD fork. Still not sure what I did wrong.

**Comment by akohlmey** [comment]
here is my procedure for merging manually (i.e. not via the github web interface).
- go to my local LAMMPS repo
- `git checkout master; `git pull` : this updates my local checkout of master to the current version
- `git checkout -b merge-pull-666 master` : this creates a feature branch containing the current master for merging the pull request 
- look up the git repo and branch to pull from and do `git pull https://github.com/xxx/yyy.git zzz` : this attempts to merge and commit the changes from the given branch into master
- in case the previous step failed with a merge conflict, then all changes are processed with `git add`, but not yet `git commit` and the conflicting files are flagged as conflicts.
- at this point, i usually switch to using the graphical interface with `git gui`. each file with a conflict is marked and i can select the option `launch merge tool`, which launches another graphical tool (`meld`) with three panels containing, the version of the file in master on the left, the version in the branch on the right and the attempted merge in the middle. now i edit the file in the middle as needed and save it and quite the merge tool. rinse and repeat for all files with merge conflicts
- now i test compilation to see if all changes work. if not, more edits are needed, otherwise i add the edited conflicted files to the index again with `git add` and can conclude the pull with `git commit`.
- `git checkout master; git merge -m 'integrate pull request 666' merge-pull-666` : this transfers the merge branch to master
- `git push origin master` : this pushes the master branch to the github repo and should automatically close the pull request
- `git brand -d merge-pull-666` : this deletes the merge branch.

I've been doing this a **lot** with LAMMPS-ICMS and it has worked flawlessly all the time.

**Pull request closed without merging**
