### PR TITLE
Fix bug in fix_nh_kokkos

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Fix bug in fix_nh_kokkos as reported by Naga Vydyanathan on the mail list

**Author(s)**

Stan Moore (Sandia)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues.

### CODE REVIEW

**Comment by akohlmey** [comment]
@stanmoore1 
FYI, i usually won't look at pull requests for stuff that i am not actively working on unless you assign them to me, which means it is ready for merging. if you keep them assigned to yourself, it is supposed to signal, that you are not yet done with it. if you understand the workflow differently (since we keep tweaking it, it is not always easy to tell what applies to a given pull request...). so if you are waiting for me with any of the PRs that are still assigned to yourself, please let me know, or assign them to me.

i would like to get as much of the pending PRs merged by the middle of next week before starting to postpone changes that are not obviously bugfixes until after the upcoming stable release.

**Comment by stanmoore1** [comment]
@akohlmey sounds good, I assigned this PR to you for merging. I have a bunch of KOKKOS improvements I want to get merged in, will try to do that early next week.

**Comment by akohlmey** [comment]
> @akohlmey sounds good, I assigned this PR to you for merging. I have a bunch of KOKKOS improvements I want to get merged in, will try to do that early next week.

@stanmoore1 just for the sake of completeness. we have now two options to indicate unambiguously that you are still working on something: submit the pull request as a "draft pull request" (there is a drop down list arrow when submitting the pull request where you can switch from regular to draft), or apply the "work_in_progress" label. otherwise i have to to guess. and the label is helpful, if you clear the draft PR for review and then find out, there is still some issue (happens to me every now and then). see #1416 for an example of a draft PR. i will be collecting more small changes on that branch (and merge small, self-contained pull requests into it) until it is big enough or the next release is very close.

**Comment by stanmoore1** [comment]
@akohlmey yes, I was on the fence whether I should run this PR through the full gamut of Kokkos regression tests before merging. That is why I asked for your review but didn't assign it to you yet. I applied the WIP label to some of my pending PR already. Thanks

**Comment by akohlmey** [comment]
> @akohlmey yes, I was on the fence whether I should run this PR through the full gamut of Kokkos regression tests before merging. That is why I asked for your review but didn't assign it to you yet. I applied the WIP label to some of my pending PR already. Thanks

i don't think it is a big problem, if a little breakage leaks into master, for as long as there is time to fix it or revert it before a patch is made. since you have multiple pending KOKKOS related changes, it would be OK by me, if they do compile before they get merged, but don't need to be regression tested, but then do a full regression test after most or all of them are merged and before the next release. you can see, if a release is imminent, by the creation of a pull request to update the version. this is going to be the very last PR to be merged before a release. so if you have something that is merged to master and still untested or in the process of being tested or have some other doubt or concern, you could add a comment why this PR should be postponed and/or apply the WIP label. despite automation, we should strive to keep the manual effort on repetitive tasks small, and this seems to me a logical way to use the features of github to communicate to the entire project, if there are concerns.

 once @rbberger has recovered from his two weeks of all-day teaching HPC deployment, you should work with him, to have more thorough KOKKOS testing done here at Temple. we have the hardware ready. then those can be run automatically after every merge to master. that should help.
i just - with his help - added two tests to detect breakage with the Linux-2-Windows cross-compiler toolchain.

**Pull request merged**
