### PR TITLE
Add force style tests for Kokkos OpenMP

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

Adds tests for Kokkos pair styles with OpenMP when available. There are several failures that still need to be investigated.

**Related Issue(s)**

**Author(s)**

@rbberger (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by stanmoore1** [comment]
Looks good so far.

**Comment by rbberger** [comment]
@stanmoore1 @akohlmey went through the failing tests and found a few minor things. Also did a bit of refactoring to make the tests a bit more readable and produce better error messages.

These are the still failing tests, which need a closer look.
```
98% tests passed, 9 tests failed out of 491

Total Test time (real) = 105.60 sec

The following tests FAILED:
	 95 - MolPairStyle:coul_dsf (Failed)
	116 - MolPairStyle:hybrid-overlay (Failed)
	119 - MolPairStyle:hybrid_multiple (Failed)
	146 - MolPairStyle:lj_cut_coul_dsf (Failed)
	203 - MolPairStyle:table (Failed)
	211 - MolPairStyle:zbl (Failed)
	297 - ManybodyPairStyle:tersoff (Failed)
	298 - ManybodyPairStyle:tersoff_mod (Failed)
	304 - ManybodyPairStyle:tersoff_zbl (Failed)
```
Both hybrid-overlay and hybrid_multiple have errors of type: `EXPECT_FORCES: run_forces (newton on)`
The others are errors of type: `EXPECT_STRESS: nofdotr_stress`.

**Comment by stanmoore1** [comment]
@rbberger what does this still lack? Should I go through the failing tests?

**Comment by rbberger** [comment]
@stanmoore1 yes, the remaining failures still need to be reviewed.

**Comment by rbberger** [comment]
@stanmoore1 735d6926a1a52ef94ea778b2fbb8d222818d0974 fixes the failures for the kokkos tersoff styles. please take a closer look at that commit.

**Comment by rbberger** [comment]
```
99% tests passed, 5 tests failed out of 483

Total Test time (real) =  88.96 sec

The following tests FAILED:
	 83 - MolPairStyle:coul_dsf (Failed)
	104 - MolPairStyle:hybrid-overlay (Failed)
	107 - MolPairStyle:hybrid_multiple (Failed)
	192 - MolPairStyle:table (Failed)
	200 - MolPairStyle:zbl (Failed)
```

**Comment by akohlmey** [comment]
> ```
> 99% tests passed, 5 tests failed out of 483
> 
> Total Test time (real) =  88.96 sec
> 
> The following tests FAILED:
> 	 83 - MolPairStyle:coul_dsf (Failed)
> 	104 - MolPairStyle:hybrid-overlay (Failed)
> 	107 - MolPairStyle:hybrid_multiple (Failed)
> 	192 - MolPairStyle:table (Failed)
> 	200 - MolPairStyle:zbl (Failed)
> ```

If these 5 are the only tests that are currently failing, then we should just add a `skip_tests: kokkos` or equivalent tag to the YAML file and then work on resolving those. That way you won't need to maintain branch until somebody finds the time to sort these out.

**Comment by akohlmey** [comment]
@rbberger I will be compiling this branch on my desktop and review the failing tests and either adjust epsilon (in some cases there is some room) or disable the tests (for now). Should get this ready for merge in a few hours.

**Comment by akohlmey** [comment]
@stanmoore1 any objections to merge this?

**Comment by stanmoore1** [comment]
I think we should merge this.

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
