### PR TITLE
Update search.html in docs

### PR DESCRIPTION
**Pull request by rbberger**
DO NOT MERGE - This PR is for testing the alternative Jenkins GitHub PR plugin.

### CODE REVIEW

**Comment by rbberger** [comment]
ok to test

**Comment by rbberger** [comment]
test this please

**Comment by rbberger** [comment]
retest this please

**Comment by rbberger** [comment]
retest this please one more time

**Comment by rbberger** [comment]
retest this please, now with proper context

**Comment by akohlmey** [comment]
Is this one still needed?

**Pull request closed without merging**
