### PR TITLE
Correct handling of triclinic box support in pppm/tip4p and pppm/tip4p/omp

### PR DESCRIPTION
**Pull request by akohlmey**
Kspace style `pppm/tip4p` breaks when changing the box from orthogonal to triclinic, even without setting a tilt factor. I have tracked this down to the `PPPMTIP4P::find_M()` function (e.g. with setting the offset of point M to 0.0 the results are consistent with using a non-tip4p pair style and kspace style).
The problem lies in finding the closest image. While local atoms at this point are in lambda coordinates, ghost atoms are not, thus calling `Domain::closest_image()` fails. I've thus implemented a custom variant directly into `find_M()` which also eliminates the need for `find_M_triclinic()`. This change is now also ported to kspace style `pppm/tip4p/omp`.

To avoid memory corruption resulting from different memory layout for orthogonal versus triclinic boxes, a check is added, requiring to reissue a new `kspace_style` command after `change_box all triclinic`, if the style was already defined before.

### CODE REVIEW

**Comment by akohlmey** [comment]
@stanmoore1 did you have a chance to look at this? any comments? suggestions?

**Comment by stanmoore1** [comment]
@akohlmey do you know why we need to redefine the kspace style, i.e. why does that fix the problem?

**Comment by stanmoore1** [comment]
@akohlmey could the redefine be done programmatically instead of explicitly in the input deck? It's kind of a pain.

**Comment by akohlmey** [comment]
because we need to re-run all code that looks at triclinic, e.g. allocate() which allocates storage differently with triclinic on and off. so any time kspace_style is defined *before* the box is set to triclinic, we are wrong.

**Comment by akohlmey** [comment]
the memory corruption only shows when running with multiple MPI ranks.

**Comment by akohlmey** [comment]
overall, redefining kspace_style should only be required, when you switch from orthogonal to triclinic during a run, i.e. when the cached triclinic value in PPPM disagrees with the global flag. for well written inputs, that should not happen. ...or right after switching the box and i think under those circumstances, it is valid to expect to have to do something to update your kspace setting, as that is dependent on the box.

**Comment by stanmoore1** [comment]
Yes, I remember now that PPPM triclinic has a different data structure than orthogonal. I tested this and the bug fixed in #299 is still fixed with this PR as far as I can tell.

**Pull request merged**
