### PR TITLE
Optimize Kokkos PACE pair style for GPUs

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

- Fuse `barplm` and `ComputeYlm` inline into `ComputeAi` and `ComputeDerivative`, which reduces memory pressure
- Change the memory layout of some views to improve memory access patterns
- A couple other small optimizations

This PR gives ~1.7x speedup for 2000 Cu atoms on an NVIDIA V100 GPU.

**Related Issue(s)**

None

**Author(s)**

Stan Moore (SNL), with helpful suggestions from and discussions with Evan Weinberg (NVIDIA), @weinbe2 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Comment by stanmoore1** [comment]
@yury-lysogorskiy do you have an example for the extrapolation pair style?

**Comment by stanmoore1** [comment]
I confirmed correctness on GPUs with half list and full list. The tuning gives a marginal speedup when using a larger cutoff for LJ 500 atoms (5.0 sigma instead of 2.5 sigma).

**Comment by yury-lysogorskiy** [comment]
> @yury-lysogorskiy do you have an example for the extrapolation pair style?

@stanmoore1 , yes, please check this for example: https://github.com/yury-lysogorskiy/pace-tutorial/tree/main/AlLi-LAMMPS

**Comment by stanmoore1** [comment]
I confirmed correctness for the `product` and the `extrapolation` examples on a GPU. This PR is ready to merge from my POV.

**Review by yury-lysogorskiy — APPROVED** [review]
I confirm that both pace/kk and pace/extrapolation/kk  give identical results with older version.   On RTX 3090, 7k atom Al-Li potential with 1000 funcs/element I observe up to 30% performance improvement

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
