### PR TITLE
Fix init arguments and some join stuff for Kokkos 4

### PR DESCRIPTION
**Pull request by crtrott**
**Summary**

Update LAMMPS to work with upcoming Kokkos 4.0 release

**Author(s)**

Christian Trott crtrott@sandia.gov

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Should be backward compatible, including to pre Kokkos 4 releases of Kokkos. 

**Implementation Notes**

Did a bunch of compilation and run tests with bench and examples directory

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by crtrott** [comment]
Few comments: 

- Kokkos is now using non-volatile overloads of join/init in reductions. I added them in places missing, but LAMMPS developers should consider just removing the volatile overloads.
- I did a backward compatible (Pre Kokkos 3.7) ifdef path for initialization. One could get rid of that path if you don't intend to still compile with Kokkos 3.6 etc. 
- In the initialization path the numa option has been semi ignored for a long time. LAMMPS developers could consider getting rid of the numa option on the LAMMPS command line args. I just used it as a multipler on number of threads.

**Comment by akohlmey** [comment]
> * I did a backward compatible (Pre Kokkos 3.7) ifdef path for initialization. One could get rid of that path if you don't intend to still compile with Kokkos 3.6 etc.

At least with the CMake build system, the LAMMPS KOKKOS package is set up to require the same version (or later) for an external Kokkos library than what is bundled. Currently that is 3.7.0, so with a Kokkos 3.6.x installation CMake will already fail at the configuration step.

**Comment by akohlmey** [comment]
Support code for Kokkos prior to 3.7.0 is now removed and support for the "numa" or "n" option to the -kokkos flag.

**Comment by stanmoore1** [comment]
I merged this into #3532

**Pull request closed without merging**
