### PR TITLE
cmake: required v3.7 for some DOWNLOAD options

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by sjplimp** [comment]
@junghans can you add a similar error chcek/message when the GPU or KOKKOS packages
are requested, that says you need cmake 3.2 or later.  I will make the doc page then
say 2.8, but some features need a later cmake

**Comment by junghans** [comment]
Why does GPU need v3.2?

**Comment by sjplimp** [comment]
Don't know - that's what I was told, and hence what is in the doc pages.

**Comment by junghans** [comment]
GPU already has an error:
https://github.com/lammps/lammps/blob/master/cmake/CMakeLists.txt#L850
for =<CMake-3.1 though.

Kokkos handles that internally here:
https://github.com/lammps/lammps/blob/master/lib/kokkos/CMakeLists.txt#L10
already.

**Pull request merged**
