### PR TITLE
Add new bond style harmonic/restrain

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This implements a harmonic bond potential that does not have a single equilibrium distance per bond type, but uses the initial distance of the atoms. Thus it is more like a restraining potential, but unlike fix restrain, it uses explicit bonds.

**Related Issue(s)**

This implementation was motivated by a [discussion on the MatSci forum](https://matsci.org/t/segmentation-fault-while-reading-atoms-x0-value/47240)

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

Rather than storing the initial bond lengths, the initial atom positions are stored via an internal instance of fix property atom. This has the advantage of requiring minimum effort to implement and avoiding to write a new atom style.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp This is now back to where it is supposed to be. I have made some more tests and found a few more kinks that needed straightening out. I'm attaching a test input. If you run with `-v bond fixed`  it will use bond style harmonic, with `-v bond restrain` it will use bond style harmonic/restrain and with `-v bond hybrid` it will use both in a hybrid configuration. Since all bonds are of length 1 \AA (within the precision of the molecule) the initial energies, forces, and pressure should be very close for all 3 cases.

[in.spce.txt](https://github.com/lammps/lammps/files/10915555/in.spce.txt)
[spce.txt](https://github.com/lammps/lammps/files/10915556/spce.txt)

**Comment by akohlmey** [comment]
@sjplimp This is now waiting on you to update fix STORE/PERATOM as we had discussed elsewhere. I have thus changed the assignment. Please assign the PR it back to me when you are done and need me to complete it.

**Comment by sjplimp** [comment]
@akohlmey thanks - should get to this, this afternoon

**Review by athomps — APPROVED** [review]

**Comment by akohlmey** [comment]
@sjplimp fix STORE/PERATOM has been renamed to fix STORE/ATOM. I've updated the docs and added the notes we discussed. All tests pass on my machine.

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
