### PR TITLE
Dynamic check for CUDA and ROCm-aware OpenMPI support in KOKKOS package

### PR DESCRIPTION
**Pull request by vladgl**
**Summary**

This PR replaces the CUDA compile time check and adds a HIP runtime check for GPU-aware capability when compiling KOKKOS with CUDA and HIP backends. This feature for ROCm appeared in OpenMPI since version 5 [(see here)](https://docs.open-mpi.org/en/v5.0.x/man-openmpi/man3/MPIX_Query_rocm_support.3.html#mpix-query-rocm-support).

**Related Issue(s)**

**Author(s)**

Vladislav Galigerov @vladgl [vladgl3@yandex.ru](mailto:vladgl3@yandex.ru) (Higher School of Economics, Russia)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by vladgl** [comment]
@stanmoore1 Besides checking ROCm aware support, this PR may be partially related to #3140, perhaps we should extend it to a more general solution that includes CUDA?

**Comment by stanmoore1** [comment]
@vladgl thank you for this PR, and sorry for the delay, I will take a look.

**Comment by stanmoore1** [comment]
@vladgl thanks for this PR, the code looks good to me. I'm fine with either merging as-is, or extending this to CUDA. Do you have interest to work on that?

**Review by stanmoore1 — APPROVED** [review]

**Comment by vladgl** [comment]
@stanmoore1 Thanks for the reply! Yes, I'll try to do that soon, it seems like it shouldn't be much different from the HIP option.

**Comment by stanmoore1** [comment]
Great, thank you!

**Comment by vladgl** [comment]
@stanmoore1 It seems better to use [MPIX_ROCM_AWARE_SUPPORT](https://github.com/open-mpi/ompi/blob/67026ef03fffdd49decb02aca038b6e7f6c16756/ompi/mpiext/rocm/configure.m4#L24) instead of `OMPI_HAVE_MPI_EXT_ROCM`, i.e. to use the same format as with CUDA. Also, I have removed `if (have_gpu_aware == 1)` as it is redundant.

It is worth noting that MPICH has similar functions [MPIX_Query_cuda_support](https://www.mpich.org/static/docs/v4.1.x/www3/MPIX_Query_cuda_support.html) and [MPIX_Query_hip_support](https://www.mpich.org/static/docs/latest/www3/MPIX_Query_hip_support.html), but unfortunately it has no macro to check for the presence of these functions. To overcome this, we can use `check_cxx_source_compiles` in cmake build system, like [gromacs ](https://gitlab.com/gromacs/gromacs/-/blob/release-2023/cmake/gmxManageGpuAwareMpi.cmake) does.

Also, MVAPICH has [MPIX_Query_cuda_support](https://mvapich.cse.ohio-state.edu/userguide/gdr/#_compile_time_and_run_time_check_for_cuda_aware_support) with macro, but there is no such function for ROCm.

**Comment by vladgl** [comment]
@stanmoore1 At the moment, I would propose to include this pull request for openpmi. The search for a solution for other MPIs will take some effort.

**Comment by stanmoore1** [comment]
@vladgl thank you, I will review and get this merged.

**Comment by stanmoore1** [comment]
@vladgl @IanBogle do either of you have a build of OpenMPI 5.0 with ROCm that supports GPU-aware that could test this?

**Comment by stanmoore1** [comment]
I tested this with CUDA and OpenMPI 4.0, it seems to be working for CUDA.

**Comment by vladgl** [comment]
@stanmoore1 I just tried with OpenMPI 5.0 + ROCm with GPU aware, everything is fine, but I noticed that you have removed the "OMPI_HAVE_MPI_EXT_ROCM/OMPI_HAVE_MPI_EXT_CUDA" guards. I think they are important because someone might have OpenMPI without HIP or CUDA extensions, so they will get "MPIX_Query_rocm_support was not declared in this scope" error.

**Comment by stanmoore1** [comment]
@vladgl thanks I added the guards back in.

**Comment by stanmoore1** [comment]
This is working as far as I can tell, ready to merge from my POV.

**Pull request merged**
