### PR TITLE
Alternative implementation of ABC-FIRE

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This is an alternative implementation of the submission in pull request #3591 that folds the modifications to the algorithm into the `MinFire` class and enables it via a `min_modify` option.

**Related Issue(s)**

Closes #3591

**Author(s)**

See #3591 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This pull request also removes the obsolete minimization style fire/old. The information in the documentation about how to emulate the old fire minimizer with the current one via min_modify is retained.

**Implementation Notes**

There are some additional cleanups and minor refactoring for the MinFire class included that are supposed to make the code more readable (symbolic constants instead of numbers) and faster (templated function will create multiple variants at compile time with if statements already resolved by the compiler.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [ ] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] One or more example input decks are included

### CODE REVIEW

**Comment by akohlmey** [comment]
@jguenole while going over the code I was wondering whether it is now time to retire and remove fire/old. It has been almost three years. What do you think?

**Comment by jguenole** [comment]
@akohlmey Yes, it is indeed a good opportunity to remove that old implementation. I believe that anyone interested in testing an ancient script or verify old results related to fire/old, should recompile a version of LAMMPS of the age of the script/results.

**Comment by akohlmey** [comment]
> @akohlmey Yes, it is indeed a good opportunity to remove that old implementation.

Done.

**Comment by sebastianecheverrir** [comment]
@akohlmey As mentioned in #3591, attached an example for ABC-FIRE. It contains interstitial carbon atoms in an iron lattice. The interactions are given by a MEAM potential.
 
[abcfire_example.zip](https://github.com/lammps/lammps/files/10393417/abcfire_example.zip)

**Review by athomps — APPROVED** [review]
I approve

**Pull request merged**
