### PR TITLE
Kim property

### PR DESCRIPTION
**Pull request by yafshar**
**Summary**

A new kim_commands feature.

- New capability within LAMMPS for writing material properties computed in LAMMPS to standard KIM property instance format.
- Updating the kim_coammands document
- Updating the KIM package documents
- Addition of a KIM reference to the pair potentials document (pair_adp, and  pair_eam).

**Author(s)**

Yaser Afshar (U Minnesota)
Ellad Tadmor (U Minnesota)
Daniel S. Karls (U Minnesota)
Ryan Elliott (U Minnesota)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

There is no backward compatibility issue.

**Implementation Notes**

The new command requires that LAMMPS is built with the Python 3.6 or later package installed. It uses Python/C interface, and in case LAMMPS is not made with Python 3, calling this command will fail with a message indicating the problem.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@yafshar I think that we should aim to align the way how python is used in this command better with how it is used in the PYTHON package. For starters, you should initialize the python interpreter instance inside the LAMMPS class with `python->init()` like it is done with the styles in the PYTHON package. Then we should add a `load_module()` method to the `PythonInterface` adapter class (and its implementation) to have a consistent and generalized way of importing a python module into that global python interpreter instance. I have some more ideas of what could be generalized and abstracted, but I would prefer to discuss them first with @giacomofiorin and @rbberger who have figured out a lot of the details of how python is currently embedded into LAMMPS.

**Comment by yafshar** [comment]
> @yafshar I think that we should aim to align the way how python is used in this command better with how it is used in the PYTHON package. For starters, you should initialize the python interpreter instance inside the LAMMPS class with `python->init()` like it is done with the styles in the PYTHON package. Then we should add a `load_module()` method to the `PythonInterface` adapter class (and its implementation) to have a consistent and generalized way of importing a python module into that global python interpreter instance. I have some more ideas of what could be generalized and abstracted, but I would prefer to discuss them first with @giacomofiorin and @rbberger who have figured out a lot of the details of how python is currently embedded into LAMMPS.

@akohlmey I can easily fixe the first thing `python->init()`. I have written a wrapper before for importing python module and functions in c++. If I understand you correctly, you aim something general in LAMMPS, maybe a bit similar to what I have done here [PyGetAttribute, PyCallFunctionObject, PyCallFunctionName](https://github.com/yafshar/UMUQ/blob/develop/src/interface/python.hpp)

**Comment by rbberger** [comment]
@yafshar can you please add an example that uses this new command?

**Comment by rbberger** [comment]
@yafshar I've added a generic function to check the Python version. Your error message for missing Python support was redundant, because `Python::init` already does that.

**Comment by yafshar** [comment]
> @yafshar can you please add an example that uses this new command?

@rbberger below please find an example for you to see

```
 # Initialize interatomic potential (KIM model) and units
 atom_style atomic
 
 # Set the OpenKIM model that will be used
 kim_init LJ_Shifted_Bernardes_1958MedCutoff_Ar__MO_126566794224_004 metal
 
 # the equilibrium lattice constant for the fcc structure
 variable lattice_constant equal 5.248509056866169
 
 # Periodic boundary conditions along all three dimensions
 boundary p p p
 
 # Create an FCC lattice with the lattice spacing
 # using a single conventional (orthogonal) unit cell
 lattice fcc ${lattice_constant}
 region box block 0 1 0 1 0 1 units lattice
 create_box 1 box
 create_atoms 1 box
 mass 1 39.948
 
 # Specify the KIM interactions
 kim_interactions Ar
 
 # Compute energy
 run 0

 # Get cohesive energy
 variable natoms       equal "count(all)"
 variable ecohesive    equal "-pe/v_natoms"
 
 # Create a property instance
 kim_property create 1 cohesive-potential-energy-cubic-crystal
 
 # Set all the key-value pairs for this property instance
 kim_property modify 1 key short-name source-value 1 fcc                          &
                       key species source-value 1 Ar                              &
                       key a source-value ${lattice_constant}                     &
                             source-unit angstrom                                 &
                       key basis-atom-coordinates source-value 1 1:3 0.0 0.0 0.0  &
                                                  source-value 2 1:3 0.0 0.5 0.5  &
                                                  source-value 3 1:3 0.5 0.0 0.5  &
                                                  source-value 4 1:3 0.5 0.5 0.0  &
                       key space-group source-value Fm-3m                         &
                       key cohesive-potential-energy source-value ${ecohesive}    &
                                                     source-unit eV
 
 # Dump the results in a file
 kim_property dump "results.edn"
```

I would add the same example with some explanation and link in the `lammps/examples/kim`

**Comment by yafshar** [comment]
> @yafshar I've added a generic function to check the Python version. Your error message for missing Python support was redundant, because `Python::init` already does that.

@rbberger sounds great to me. Thanks

**Comment by rbberger** [comment]
> I would add the same example with some explanation and link in the `lammps/examples/kim`
@yafshar please do so. thanks

**Comment by yafshar** [comment]
> > I would add the same example with some explanation and link in the `lammps/examples/kim`
> 
> @yafshar please do so. thanks

@rbberger done.

**Comment by akohlmey** [comment]
@rbberger i am good with this now. Please assign to me (and approve) if you are also ok with merging.

**Pull request merged**
