### PR TITLE
Collected small fixes

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request collects multiple small fixes and improvements

**Related Issue(s)**

N/A

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues

**Implementation Notes**

The following individual changes are included:
- flag LAMMPS version as development version
- improve error messages for dump styles derived from dump style custom
- better detection of unsupported properties in dump style image
- include git descriptor in development and maintenance version output
- fix segfault when attempting to delete Atom class callback in base class after error in constructor of derived class
- address issues flagged by static code analysis
- fix syntax issue in CMake script that prevented testing the Fortran coupling simple example

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by stanmoore1** [comment]
Could we print out the git sha (if available) in the log file? I think that would be useful for many reasons, especially when we have months in between feature releases.

**Comment by stanmoore1** [comment]
And more convenient if you only have a log file and not the executable which can run `lmp -h`

**Comment by akohlmey** [comment]
> Could we print out the git sha (if available) in the log file? I think that would be useful for many reasons, especially when we have months in between feature releases.

The current situation is at the request of @sjplimp. I had the git hash included originally, IIRC. I am happy to revert.

**Comment by akohlmey** [comment]
@stanmoore1 what do you think of the change in commit a3de790a0da60c1ff13a39e0617bc75f45bdb9b1?

**Review by sjplimp — APPROVED** [review]

**Pull request merged**
