### PR TITLE
always compile in exceptions

### PR DESCRIPTION
**Pull request by junghans**
**Summary**

Always enable exceptions. I am not sure about performance and HPC implications.

**Related Issues**

See discussion in #2088.

**Author(s)**

@junghans 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Nope, the behaviour now is same as with `-DLAMMPS_EXCEPTIONS` before.

**Implementation Notes**

Just deleting code.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by junghans** [comment]
Not going to happen: https://github.com/lammps/lammps/issues/2088#issuecomment-629365703

**Comment by junghans** [comment]
After contemplating about it, I still think we should do this. This change would also help to make both builds systems more consistent.

**Comment by akohlmey** [comment]
> After contemplating about it, I still think we should do this. This change would also help to make both builds systems more consistent.

no, it doesn't. i've explained already what it would take to change my mind. i don't want to give people a false idea, that they can recover from failures. this is good the way it is: whoever wants this feature can have it and they have to know what they are doing, but nobody else is forced to use it.

**Comment by junghans** [comment]
Just to make sure I get this right. There are no performance penalties and this change only affects user building the their own app around `liblammps` as the lammps executable already calls `exit()` after it catches the exception.

**Comment by akohlmey** [comment]
> Just to make sure I get this right. There are no performance penalties and this change only affects user building the their own app around `liblammps` as the lammps executable already calls `exit()` after it catches the exception.

This is my last response to this whole affair as it irritates me immensely when people are not paying attention to my arguments.  So for the last time: you have to know what you get into when you are building an application that that uses LAMMPS as a library with exceptions enabled.  This would only be a meaningful choice, if the library is built without MPI support as MPI (currently to the best of my knowledge) has no mechanism to propagate exceptions across MPI ranks and to trigger a safe reset of the entire MPI subsystem. By making it a configurable item, people have to make a conscious choice, and that is intentional and desired.

And to repeat this one, too: if people that package LAMMPS make different choices for their binary packages, they are free to do so, but the consequences are on them. I don't want to deal with it.

**Comment by sgsaenger** [comment]
I hope @akohlmey will forgive me for  joining in on this :)

Exceptions are indeed also very useful when run in parallel, at least for a master-slave architecture where lammps does not run on the master process itself.
At least [MPICH claim](https://github.com/pmodels/mpich/blob/9710a9573b5d53efe9ce3da6c96517c6f9e85444/CHANGES#L115) to support executing `MPI_Abort` only across a given communicator since version 3.3.
With other implementations it's possible to [use threads and a bit of asynchronous MPI](https://github.com/sgsaenger/vipster/blob/967c74aff3700d8517d48eecbf2e6ea5d28c97ff/gui/qt/toolwidgets/lammpswidget_aux/run.lmp.cpp#L122-L135) to achieve (mostly) the same. (Successfully tested with OpenMPI 4.0.3.)

Notably, LAMMPS does not differ from any other library in this regard, handling exceptions in parallel always requires thought, so I'm not sure what is achieved from the current split, besides the need to document (or not) two different behaviors.
There's no protection against any non-LAMMPS exception thrown from within LAMMPS,
so in the case of an e.g. stdlib-exception the library user will have to do this anyway or risk stalling processes.

Maybe it would help to rename the exceptions to something more drastic, e.g. `LAMMPSTerminalError` to emphasize their nature and make this a bit more self-documenting?

**Comment by akohlmey** [comment]
> I hope @akohlmey will forgive me for joining in on this :)

only barely. this is getting far too "religious".

please keep in mind that I am wearing my maintainer hat here and that I am trying to be consistent with the preferences and policies that the other LAMMPS developers have established long before I started doing what I am currently doing in the development of LAMMPS.

1) we are talking about **default behavior** here. if you want something else you **can** have it.  that is why this feature is available as an option. why force **your** preferences down everybody else's throat? where is the harm to not have it as default behavior? what is it that you cannot do because having to enable a feature? for example, this applies to all functionality in packages, too, and nobody is complaining about that. or put differently, the fact that something can be done does not mean it has to be done. please be aware that arguments like "XXX does it" are irrelevant. default behavior is a choice, choices were made, and the code reflects this.

2) you are disregarding that LAMMPS aims to be compatible and properly functional by default on quite old environments. we just made a significant leap forward to require C++11, which now assumes that we aim to be compatible with what was current state in approximately 2012. Before that it, was approximately 2006. As a consequence of trying to stay compatible and consistent with past versions, all changes that affect **all** users will have to be considered with **extreme** paranoia. in its current form, LAMMPS is still mostly some form of "C with classes".  This is why using exceptions for errors was made optional. it was added to support a specific project and because there is potential for other uses. if it hadn't been possible to make it optional, it would not have been included at all.

**Comment by sgsaenger** [comment]
>   [...]  all changes that affect **all** users will have to be considered with **extreme** paranoia.

I would not expect less.
Still, i fail to see any drawbacks to this.
Please correct me if i'm getting any of this wrong:

1. Should not affect standalone execution at all.
2. Should be supported by all compilers since i-can't-even-find-out-when. At least years before C++11.
3. Ignoring the exceptions should terminate the application in line with the old behavior.
This is the point i'm the least sure about as my experience with MPI is too limited, but so far all dying MPI processes i've encountered always brought down the rest of the bunch with them.
4. Would make compiling against LAMMPS more convenient.
Currently exception-state is not easily available at compile-time and each project would have to write it's own code to determine it, if required.
5. Would make dynamic linking against LAMMPS more convenient.
Admittedly weak argument as at least the used MPI header and the float definitions can still introduce type mismatches to the API (or is it ABI at this stage?); i'm also not sure how stable the API itself is nor how important this is to the project.
6. Exclusively removes code complexity.

Yes, this is mostly a convenience change, if you feel this is not worth policy change so be it.
I'd be pretty happy though if this would be merged somewhere down the road :)

**Comment by akohlmey** [comment]
> > [...]  all changes that affect **all** users will have to be considered with **extreme** paranoia.
> 
> I would not expect less.
> Still, i fail to see any drawbacks to this.

Yet you are not addressing **my** questions.

> Please correct me if i'm getting any of this wrong:

[...]

> 3. Ignoring the exceptions should terminate the application in line with the old behavior.
>    This is the point i'm the least sure about as my experience with MPI is too limited, but so far all dying MPI processes i've encountered always brought down the rest of the bunch with them.

And this has been one of the main concerns that has been mentioned multiple times in the discussion about this issue. LAMMPS has two kinds of error conditions which are creating different exceptions and result in different behavior. In case we know the error is to be encountered by all MPI ranks, the MPI state is synchronized with an MPI_Barrier() and the error message is printed only by rank 0 and MPI is finalized the code stops via calling `exit()`. This is to make an effort so the user is not flooded with many copies of the same error message (remember that LAMMPS is designed to run across very many MPI ranks!) and make a best effort to flush all I/O buffers from the MPI library (which is capturing stdout/stderr from all ranks and forward it to rank 0).
Otherwise, the error printed on the rank the error occurred on, every effort is made to output the error message and then MPI is signaled to abort.

For GUI style applications or Python scripts that tend to use LAMMPS in a non-MPI (or MPI enabled but with a single rank) shared library, this is not a concern and throwing exceptions the preferred behavior, but that is not the primary use of LAMMPS and hence using exceptions is not the default behavior and has to be requested.

> 4. Would make compiling against LAMMPS more convenient.
>    Currently exception-state is not easily available at compile-time and each project would have to write it's own code to determine it, if required.

That is not correct. the (static) C++ function `Info::has_exceptions()` or correspondingly `lammps_config_has_exceptions()` in the C library interface can tell you the state.  Neither needs a LAMMPS instance to function. Other compile time properties can be detected as well particularly through the library interface. This is going to be expanded and better documented once the library interface refactor from PR #1970 is merged. A preview of the ongoing work is available at https://docs.lammps.org (look at the programming guide part). The goal is to have at least the library part completed for the next stable release in (late) summer 2020.

> 5. Would make dynamic linking against LAMMPS more convenient.
>    Admittedly weak argument as at least the used MPI header and the float definitions can still introduce type mismatches to the API (or is it ABI at this stage?); i'm also not sure how stable the API itself is nor how important this is to the project.

There is currently no effort made to keep the API, let alone the ABI stable. LAMMPS was not conceived to be installed as a systemwide library. This only became available after support of compilation with CMake was added. This support for installing LAMMPS was done in a rather ad hoc and rushed way without thinking things fully through. To make this work properly, some more changes need to be introduced to LAMMPS internally first. Please note that compilation with CMake is considered by some of the core LAMMPS developers more like a "gimmick" and the conventional make based build process is the only option they use and consider when programming. With that approach there is no system-wide installation and that any person using LAMMPS as a library would have to access it in its original location, and until very recently, the LAMMPS library would not even be constructed in the conventional build process unless explicitly requested.
In short, you are expecting consistent and convenient behavior from something that would need to be called "experimental" and is definitely not in a shape that it has the full endorsement and support from **all** core LAMMPS developers.

The C library interface has by its very nature fewer changes, though, and with the refactor in #1970 there should be an effort to make it more stable and consistent.

> 6. Exclusively removes code complexity.

Compared to the overall complexity in LAMMPS this is negligible and has not been in need for any maintenance in many years, as everything is well contained. I have spend *much* more time on this  discussion than I have spent on tracking issues or on maintaining that part of LAMMPS.
 
> Yes, this is mostly a convenience change, if you feel this is not worth policy change so be it.
> I'd be pretty happy though if this would be merged somewhere down the road :)

And still you have not addressed the issue that the current situation is not taking away anything. You can have the library with exceptions enabled already as it is. And you fail to point out where the harm is in leaving the current code in place. You are arguing as if with the default settings you cannot have exception handling. That is just not correct. The situation is rather the opposite: this pull request is **removing** a choice and that is why I am opposing it.

**Pull request closed without merging**
