### PR TITLE
add NWChem wrapper to client/server mode for AIMD

### PR DESCRIPTION
**Pull request by jboschen**
**Summary**

Add a Python wrapper on the NWChem quantum chemistry code so it can be used in client/server mode with LAMMPS. Simliar to VASP. Two example scripts are provided.

This is a replacement/continuation of https://github.com/lammps/lammps/pull/1696, opening this PR so that I can push commits to it.

**Related Issues**

N/A

**Author(s)**

Jeff Boschen (Iowa State U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp since this PR supersedes it, you should close #1696.

**Comment by sjplimp** [comment]
@jboschen I added my W min example.  Also archived output log files for both W and W.min.
We should do the same thing when the AO example is working.  I can add a min script for
that when dynamics seems good.

**Comment by sjplimp** [comment]
@akohlmey With the changes/added files from @jboschen I think this is now ready to merge.

**Comment by akohlmey** [comment]
> @akohlmey With the changes/added files from @jboschen I think this is now ready to merge.

I will need to resolve the merge conflicts with the documentation first, as the .txt files modified in this branch are gone and no updated .rst versions were created/included. I also spotted some spelling errors.

**Pull request merged**
