### PR TITLE
USER-UEF package for extensional flow

### PR DESCRIPTION
**Pull request by danicholson**
## Purpose

USER-UEF is a LAMMPS package for non-equilibrium molecular dynamics (NEMD) under extensional flow fields, including uniaxial and biaxial flow.

## Author(s)

David Nicholson, Massachusetts Institute of Technology

## Backward Compatibility

No issues are anticipated.

There is a small change to the argument parsing in `FixNH` added by @akohlmey so that `FixNH` can skip over arguments that are to be parsed in the derived class `FixNHUef`, following the example of FixNHSphere. This change has passed all regression tests on the temple jenkins server.

## Implementation Notes

The main addition is a integrator, FixNHUef, that derives from FixNH. It integrates the SLLOD equations of motion with a thermo-/baro-stat, and also implements the special boundary conditions required for extensional flow. Supporting functions for the boundary conditions can be found in uef_utils.{cpp,h}. Because of the upper-triangular representation of the simulation box, FixNHUef keeps track of two reference frames. Additional computes, ComputePressureUef and ComputeTempUef, were created to compute output in the reference frame of the applied flow field. A simple dump style, DumpCFGUef, was created in order to have an option for outputting coordinates in the reference frame of the flow field.

The results were checked against a literature example for a WCA fluid (see examples/USER/uef/nvt_uniaxial/)

## Post Submission Checklist

- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

The citations for the method used can be found in the doc files and README. 

One problem I had when writing this package is that I couldn't find a straightforward way to add additional keywords for a my derived class (FixNHUef), since the input is parsed in the constructor for the base class (FixNH). My solution was to write a standalone function in LAMMPS_NS (I call it "uef_arg_kludge") that will find the keywords and values specific to FixNHUef, push them to the back of arg, then decrease narg so that the FixNH constructor never sees them. I then parse these remaining keywords and values in the constructor for the derived class. Is this considered to be acceptable? Does anyone have a better solution? I could add some logic to the FixNH constructor to recognize the new keywords, but I was trying to avoid making changes to the LAMMPS core.

### CODE REVIEW

**Comment by akohlmey** [comment]
Thanks for your contribution to LAMMPS. This looks like it is very well done and will fit in cleanly.
I agree with your assessment of the problematic style of processing options in the FixNH class. There is at least one more nose-hoover based integrator style that is affected by this. There is a clean way to make the option handling extensible and i will look into it right away. it is probably best to wait until that change is merged into the master branch, then update your pull request before merging it.

**Comment by danicholson** [comment]
Thanks, that sounds good to me.

**Comment by akohlmey** [comment]
@danicholson i've just completed the changes to remove the option parsing hack and updated the pull request. these also include some cleanups to be closer to LAMMPS formatting and a little refactoring to avoid having to include the auxiliary class heading in the fix header. i also reran the examples and found acceptable agreement (divergence starts around 1000 steps) with the nvt example (BTW: the 1 processor log was empty), but significant deviation for the npt example (which diverges right from the beginning). perhaps i messed up something when refactoring the argument parsing. please check it out and let us know. thanks again for your contribution.

**Comment by danicholson** [comment]
@akohlmey Thank you very much for your changes. There was a small parsing issue in the FixNHUef constructor that I took care of. It was causing one of the keywords to be skipped over in the npt example, which is the likely reason for the divergence that you noticed. I made a few other formatting changes to (hopefully) bring the code closer to LAMMPS style, and also added a citation for the paper where I introduced this package into the documentation.

**Comment by akohlmey** [comment]
@danicholson thanks for checking it out. i suspected there was something wrong with the argument parsing, but i just didn't see it. there was one minor tweak missing for the docs. i think this is now ready for inclusion and i will assign the pull request to steve so he can merge it at the next opportunity.

**Pull request merged**
