### PR TITLE
added .travis.yml

### PR DESCRIPTION
**Pull request by junghans**
Get some free testing on github.com and travis-ci.org

### CODE REVIEW

**Comment by junghans** [comment]
And that is where more tests would be nice!

**Comment by junghans** [comment]
@akohlmey Can you merge this now? I will add more test cases via pull-request later.

**Comment by akohlmey** [comment]
On Fri, Aug 14, 2015 at 11:14 AM, Christoph Junghans <
notifications@github.com> wrote:

> @akohlmey <https://github.com/akohlmey> Can you merge this now? I will
> add more test cases via pull-request later.
>

​i have it merged into my personal repo already, but also made some
modifications including updates to the LAMMPS master makefile that will
allow to compile compatible packages for serial and compile a paralle
executable as well. i just need some more time to dig through the
documentation, make the changes and then test them before it push the repo
to the official LAMMPS-ICMS repo. i have a few more urgent items on my TODO
list for today, so i don't know yet, if i get to it today.

axel.​



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lammps/lammps/pull/5#issuecomment-131143325>.
>



-- 
Dr. Axel Kohlmeyer  akohlmey@gmail.com  http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste. Italy.

**Comment by akohlmey** [comment]
Just pushed the changes and expanded the build script to compile a serial and an MPI/OpenMP version. Also the serial version should use clang while the parallel version should use GCC for additional chances of triggering problems.

**Comment by akohlmey** [comment]
looks like i have it somewhat working now. just added some more compilation variants. still need to figure out some more stuff to run tests with different MPI + OpenMP settings. And then expand the build step to include more packages. GPU, USER-CUDA, and USER-INTEL need special hardware and compilers. some packages require external libraries. but for now, i would rather add more tests. we should keep them somewhat categorized. i am thinking to have category 01 only use stripped down inputs that are part of the LAMMPS distribution, category 02 could be inputs that are set up to test individual commands (almost like unit tests), category 03 would be tests for fixes and computes, category 04 tests that i used for testing USER-OMP (currently under test-user-omp), and so on.
some higher numbered category (say 80 and beyond), should be inputs that have to fail in a specific way and it would be an issue, if they do *not* fail.

we then also need some script/tool that compares the individual runs against some reference output.

**Pull request merged**
