### PR TITLE
Collected small fixes and updates

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request collects multiple small updates and fixes

**Related Issue(s)**

N/A

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

The following individual changes are included:
- unconditionally disable `if constexpr` in fmtlib for Intel compilers
- catch error exceptions in `command()` lambda functions in unittests
- fix bug introduced by PR #3896 where immediate variables were not treated like equal style variables when evaluating references to computes or fixes
- add check for failed unix socket creation to fix ipi
- add mode=pimd example for fix pimd/langevin, avoid per-bead repeated output, align output better with LAMMPS

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [x] One or more example input decks are included

### CODE REVIEW

**Comment by akohlmey** [comment]
@athomps I noticed some part of fmtlib that was not properly protected for C++17 compliance but instead depends on some internal compiler macro that may not be properly set by some compiler (including some Intel version on our CI servers that was warning about using a C++17 feature with C++11. Can you check out this branch against the Intel compiler failures you were seeing?

**Comment by stanmoore1** [comment]
> @athomps I noticed some part of fmtlib that was not properly protected for C++17 compliance but instead depends on some internal compiler macro that may not be properly set by some compiler (including some Intel version on our CI servers that was warning about using a C++17 feature with C++11. Can you check out this branch against the Intel compiler failures you were seeing?

@akohlmey I checked and unfortunately this doesn't fix the KOKKOS package + Intel compiler issue we discussed on Slack:
```
ERROR: Cannot open file data.1.00000000000001.tpm: No such file or directory (../read_data.cpp:367)
```

**Comment by akohlmey** [comment]
> @akohlmey I checked and unfortunately this doesn't fix the KOKKOS package + Intel compiler issue we discussed on Slack:
> 
> ```
> ERROR: Cannot open file data.1.00000000000001.tpm: No such file or directory (../read_data.cpp:367)
> ```

It won't work, since the check is true for C++17 and later. To disable this for your case, we'd have to disable this for all Intel compilers (or possibly do a check on the Intel compiler version, in case we find one that is not affected. I've modified the code accordingly in the latest commit, but I don't have much hope that this makes a difference. Since the issue you report would also happen with `sprintf()`, I suspect something more fundamental, e.g. some macro or define in fmtlib conflicting with some internal define or macros in the Intel compiler headers.

**Review by stanmoore1 — APPROVED** [review]
I approve

**Pull request merged**
