### PR TITLE
Doc adjust

### LINKED ISSUE #1141: bug with dihedral_style nharmonic
## Summary

Using the commands _dihedral_style nharmonic_ and _dihdedral_coeff 3 10.0 20.0 30.0_ is leading to lammps ERRORs.

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

On quick inspection I see the below line in function coeff within dihedral_nharmonic.cpp is raising the ERROR: "Expected integer parameter in input script or data file (../dihedral_nharmonic.cpp:279)
Last command: dihedral_coeff 3 10.0 20.0 30.0"

int n = force->inumeric(FLERR,arg[1]); 

The code expects argument 1 to be integer but the example (dihedral_coeff 3 10.0 20.0 30.0) provided in the documentation has float for arg[1]. I tried changing 10.0 to 2 just as a trial but i get another ERROR: All dihedral coeffs are not set.

## LAMMPS Version (Bug Report)

2 Aug 2018

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Fix all mis-matches between src file styles and doc pages.  Also check for missing doc
page entires on pages that catalog of list of styles. Includes a fix for a typo in the dihedral_style nharmonic docs. closes #1141

## Author(s)

Steve and Axel

## Backward Compatibility

Should be N/A.

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp here are several comments:
- `fix ave/spatial` and `fix ave/spatial/sphere` are aliases in `FixDeprecated` informing users, that these commands have been removed. This is intended behavior. In fact, I plan to do the same with all future cases of commands that are removed. This way people that try to use an old input file (e.g. from an old tutorial) will get a meaningful error message rather than the non-descript "unknown XXX style" which can easily sent them on a wild goose chase for the package that has this command.
- pair `lj/sf` and its USER-OMP equivalent was renamed for consistency, but since no functionality was changed, i consider the alias a reasonable choice between consistency and convenience. i intend to do the same when removing the MEAM package, as USER-MEAMC is 100% compatible, so old inputs can continue transparently. for REAX, on the other hand, the choice is different, since it is not command line compatible with USER-REAXC.
- python support for fixes and other style classes will have to see a major overhaul some time in the future @giacomofiorin and @rbberger have some plans and ideas. that would be the point to also clean up legacy features
- whether support for pair `eam/cd/old` is removed should be left to the author/maintainer. the `/old` version is just a wrapper around the same class as the new/current version.
- for USER-SMD you should also as the autor/maintainer to verify/update the examples, since there have been multiple renames of styles, not just the ones contained in this PR.
- pair disabled was a temporary measure, but i won't get to fix this, so it is best to remove the sources

**Comment by sjplimp** [comment]
@akohlmey why don't we do the following for this PR:
1) create a pair deprecated (like fix) and put lj/sf, lj/sf/omp in it
2) remove the python command (it is superceded by python/move correct?)
    if you want a command_deprectated.cpp for it, ok, but don't think it's necessary
3) just remove pair eam/cd/old - if it's identical and undocumented
    I don't see the point of keeping it
I don't think we need to be shy about renaming styles or removing 
dead names.  The deprecated files are a good place to give an
appopriate message. Could be "this command is gone", or 
"this command is renamed".  I can just skip the "deprecated"
files in my doc vs src checks.

**Comment by akohlmey** [comment]
@sjplimp eam/cd/old is different from eam/cd. it corresponds to a different, older publication. they differ in how the contribution to the local charge for the embedding energy is computed. eam/cd is faster. I think in this case it would be better to add a few lines to the documentation rather than removing it.

no, `python` is not superseded by `python/move`. OTOH, there is a lot of overlap between `fix python/move` and `fix python/invoke`. perhaps those should be merged and then called `fix python`. will need to discuss with @rbberger and @giacomofiorin who are behind improving/expanding python support in LAMMPS. This is a topic for after the next stable release, though.

in my personal opinion, it would be ok to keep (undocumented) aliases for backward compatibility for as long as there is no difference in functionality. i am particularly worried about ageing online tutorials (offsite), where LAMMPS beginners will be confronted with an "this command no longer exists, use XXX instead" error, when they are already confused and challenged by having to learn all the commands. perhaps we should document those aliases in the corresponding file only and keep them out of the table or contents and list of commands. The best example to highlight this would be REAX and MEAM. After removing the REAX package, pair_style reax is a prime candidate for PairDeprecated, while pair_style meam is a candidate for an alias in the header for meam/c.

**Comment by akohlmey** [comment]
@sjplimp i think this is now ready as far as i am concerned. i would prefer to keep aliases, for improved backward compatibility for as long as this is just a different name and no different functionality. and use "deprecated" styles only when functionality is removed or changed. however, i am not going to fight it, if you say, that you insist on removing `lj/sf` and `lj/sf/old`. i have added documentation and looked up the reference for `eam/cd/old`. also the details about binary packages for Linux have been corrected. if i receive an update from anton about more debian/ubuntu options in time, i'll add it here, but it can also go in later. i'd like to merge this rather sooner, so i won't have to merge in master again.

**Comment by evoyiatzis** [comment]
A short report of a typo in the documentation of "compute msd/chunk". In the provided example on how to output the results, there is the command "compute myChunk all com/msd cc1". I think it should be replaced by "compute myChunk all msd/chunk cc1".

**Comment by akohlmey** [comment]
@evoyiatzis thanks for the note about the typo. Should be fixed now in this branch.

**Comment by akohlmey** [comment]
@sjplimp since you created this pull request, i cannot request a review from you (which is a bit strange, i don't think we are the only project, where branches may be handed over to somebody else to continue processing it). but short of noticing any more documentation typos being reported, i don't plan any more changes and am now waiting for you to either approve my changes this far or request additional changes that i have chosen to not do so far. thanks.

**Pull request merged**
