### PR TITLE
Update atom_map_kokkos.cpp to fix overflow warning

### PR DESCRIPTION
**Pull request by alphataubio**
fix overflow compile warning while building KOKKOS package with -D LAMMPS_SIZES=bigbig:

/home/XXXX/lammps-2Aug2023/src/KOKKOS/atom_map_kokkos.cpp: In lambda function: /home/XXXX/lammps-2Aug2023/src/KOKKOS/atom_map_kokkos.cpp:218:21: warning: overflow in conversion from ‘long int’ to ‘int’ changes value from ‘9223372036854775807’ to ‘-1’ [-Woverflow]
  218 |     int i_closest = MAXTAGINT;
      |                     ^~~~~~~~~

**Summary**

**Related Issue(s)**

**Author(s)**

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [ ] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by alphataubio** [comment]
looking at failed build now, i will resubmit a different patch

**Comment by alphataubio** [comment]
i tried building with the following cmake options but i am unable to replicate the error in dev » pull_requests » ubuntu » unit_tests » cmake_mpi_openmp_smallsmall_shared.

cmake ../cmake -D BUILD_OMP=yes -D BUILD_SHARED_LIBS=yes -D LAMMPS_MACHINE=test-smallsmall -D LAMMPS_SIZES=smallsmall -D PKG_OPENMP=yes; cmake --build . -j 32

maybe because im on centos not ubuntu. sorry i dont have access to an ubuntu virtual machine.

**Comment by akohlmey** [comment]
> but i am unable to replicate the error in dev » pull_requests » ubuntu » unit_tests » cmake_mpi_openmp_smallsmall_shared.

Don't worry about this one. This is due to some race condition in the OpenMPI version used in the Ububtu 20.04LTS container that is used on the CI testing machine. We have not yet figured out a reliable way to reproduce it, because it happen very rarely, and thus have not implemented a proper solution. It keep popping up occasionally, but should be gone with the next run (or happen with a random different test).

**Comment by stanmoore1** [comment]
I think it should be:
`int i_closest = MAXSMALLINT;` instead of `MAXTAGINT`.

**Review by stanmoore1 — APPROVED** [review]
@alphataubio nice catch, I made a small tweak.

**Pull request merged**
