### PR TITLE
Dielectric package doc update and bugfix

### PR DESCRIPTION
**Pull request by ndtrung81**
**Summary**

This PR includes 1) bug fixes to the conversion factor for non-lj units in two polarize fixes (bem/icc and bem/gmres), and 2) update to the fix polarize doc page regarding charged interfaces.

**Related Issue(s)**

This is to address the issue reported by Shibo Pan on the MatSci forum: 

https://matsci.org/t/the-induced-charge-density-obtained-by-fix-polarize-is-always-4-times-less-than-numerical-results/47151?u=shibo_pan

**Author(s)**

Trung Nguyen (U Chicago)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Should maintain backward compatibility for reduced units (lj), corrected the missing scaling factor for units real, metal, si and nano.

**Implementation Notes**

The factor 4\pi was missing in non-lj units, making the electrical field magnitude smaller than supposed to be when the two polarize fixes are used. The updated code was tested by Shibo Pan, showing that the results are now consistent with analytical results for units real. Also, the default max number of iterations is raised from 20 to 50, to help ensure convergence in the solvers. It's recommended to check for convergence in their runs via writing out the RMS errors output from the fixes.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@ndtrung81 I am currently running the examples and trying to capture log files. How much slower may the "dof" method be than the others? On my desktop, the `nopbc` example input seem to get "stuck" while the `confined` input stops with this error:
```
if "${method} == gmres" then   "fix             3 interface polarize/bem/gmres 1 1.0e-4"   "fix_modify      3 itr_max 50 dielectrics ${ed} ${em} ${epsilon} ${area} NULL" elif "${method} == icc"  "fix             3 interface polarize/bem/icc 1 1.0e-4"   "fix_modify      3 itr_max 50 dielectrics ${ed} ${em} ${epsilon} ${area} NULL" elif "${method} == dof"   "fix             3 interface polarize/functional 1 0.0001"   "fix_modify      3 dielectrics ${ed} ${em} ${epsilon} ${area} NULL" else   "print 'Unsupported polarization solver' "
fix             3 interface polarize/functional 1 0.0001
fix_modify      3 dielectrics ${ed} ${em} ${epsilon} ${area} NULL
fix_modify      3 dielectrics -10 ${em} ${epsilon} ${area} NULL
fix_modify      3 dielectrics -10 15 ${epsilon} ${area} NULL
fix_modify      3 dielectrics -10 15 1 ${area} NULL
fix_modify      3 dielectrics -10 15 1 0.866 NULL
ERROR: Expected floating point parameter instead of 'NULL' in input script or data file (src/DIELECTRIC/fix_polarize_functional.cpp:510)
Last command: fix_modify      3 dielectrics ${ed} ${em} ${epsilon} ${area} NULL
```

**Comment by ndtrung81** [comment]
@akohlmey thanks for testing "dof", it was my mistake of blindly replacing `NULL` with `nullptr` without actually testing the fix. The "dof" method is indeed slower than the other two methods, especially with 2500 induced charges and a cutoff of 20 reduced units, and rarely used in my past studies. I now use a smaller system for the example `data.sphere` (642 induced charges).

**Comment by akohlmey** [comment]
@ndtrung81 please note that in order to signal that a pull request is ready for merge, it needs to be assigned to me. If it is assigned to somebody else, the assumption is that this person is still working on changes. This convention predates the option from GitHub to flag pull requests as drafts.

**Comment by ndtrung81** [comment]
@akohlmey thanks for the reminder, the PR is ready for review from my end.

**Review by athomps — APPROVED** [review]

**Pull request merged**
