### PR TITLE
Molecule template validity checks

### PR DESCRIPTION
**Pull request by jrgissing**
## Purpose

include sanity checks for molecule templates consistent with read_data

## Author(s)

Jacob Gissinger

## Backward Compatibility

yes

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [x] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@jrgissing FYI. please be aware, that i'll need to make some changes to this PR because molecule files can be read **before** the simulation box is defined, which in turn means, that the maximum number of all kinds of  types is not yet known and thus cannot be checked against. i'll be doing this in a separate branch where i will start from your changes. thus any additional pushes into this branch will likely be lost.

**Comment by jrgissing** [comment]
is it reasonable to instead require molecule templates to be read after the simulation box is defined, at least for most atom styles? notably, this should also fix the uncaught issue of changing newton settings after reading a molecule template

**Comment by akohlmey** [comment]
@jrgissing that is something you have to discuss with @sjplimp. i won't accept changes that alter established behavior until there is a good reason **and** when it cannot be addressed locally. it is straightforward to cache the state of the newton flags when the molecule file is read inside the molecule class and then do a check if they have been modified when the molecule template is used later.

**Comment by akohlmey** [comment]
@jrgissing the check for disallowing early molecule command invocation has been implemented differently (inside the molecule class constructor, where it seems more obvious and also more futureproof). Thus closing this request now.

**Comment by sjplimp** [comment]
just getting to this now - I think the earliest a molecule file would need to
be read is before the create_atoms command (if it is creating molecules),
but not before create_box.  So allowing it to be earlier than create_box
was probably unintentional.  Does making it be after create_box,
but allowed before create_atoms, solve any issues with when sanity
checks are performed?  I think the newton flag is frozen by that point.

**Comment by jrgissing** [comment]
yes, i believe requiring molecule commands to be after create_box allowed several of the same checks as appear in read_data

**Pull request closed without merging**
