### PR TITLE
Collected small fixes

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request collects multiple small changes and bug fixes

**Related Issue(s)**

addresses ellipsoid visualization issue discussed in: https://matsci.org/t/visualise-ellipsoid/49587

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues

**Implementation Notes**

- return quaternions as (1, 0, 0, 0) and shape as (1, 1, 1) for non-ellipsoid particles in compute property/atom
- update ASPHERE and ellipsoid examples for using compute property/atom
- update dump output in examples for ellipsoids using custom column names so OVITO will autodetect them
- bugfix for per-atom data access from fixes for fix ave/histo and fix ave/histo/weight (from Stan)
- fix bugs where Atom::tag values were stored in an `int` instead of a `tagint`.
- make use of blanks in conditions more consistent and balanced
- update list of known LAMMPS commands for syntax highlighting in the manual
- fix error message in compute property/atom where strings were inserted in the wrong order
- update URL for CasP website
- remove dead code and enforce some initializers

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey What is the first change in the list about quat and shape - don't see what file(s) that affects?

**Review by sjplimp — APPROVED** [review]

**Comment by akohlmey** [comment]
> @akohlmey What is the first change in the list about quat and shape - don't see what file(s) that affects?

You have to scroll down to the changes to the changes to compute property/atom: https://github.com/lammps/lammps/pull/3844/files#diff-fa8f324e49ec1158540dcda0fef139a551a41564ca0c76bf95403088672f41dfL1271

**Comment by sjplimp** [comment]
thanks - I didn't see the mention of compute property/atom in the 1st bullet

**Comment by akohlmey** [comment]
> thanks - I didn't see the mention of compute property/atom in the 1st bullet

You couldn't. I just added it (for posterity).

**Pull request merged**
