### PR TITLE
Bug fix for lj/class2/coul/long/gpu

### PR DESCRIPTION
**Pull request by LucienPan0903**
**Summary**

Bug fix for lj/class/coul/long/gpu

When calling PairLJCutCoulLongGPU::init_style(), the PairLJCutCoulLong::init_one(i,j) is called where (double*)cut_respa is uninitialized and a memory access error is threw out. A test case is placed in by running mpirun -n 1 lmp -sf gpu -pk gpu 1 -in SBA15.in
[https://github.com/LucienPan0903/lammps/tree/master/test](url)
**Related Issues**

None

**Author(s)**

Lucien Pan

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

yes

**Implementation Notes**

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by rbberger** [comment]
@LucienPan0903  As far as I can tell all we really need is cea5616, correct? Everything else is just debugging code that was then later removed again?

**Comment by LucienPan0903** [comment]
@rbberger Yes. The only code I added is an initialization of the pointer "cut_respa"  in the constructor.

**Comment by ndtrung81** [comment]
as already pointed out, only change by cea5616 is needed for this PR, which is good to me.

**Comment by akohlmey** [comment]
cherrypicked the relevant commit into PR #1817

**Pull request closed without merging**
