### PR TITLE
Add better Kokkos support for comm_style tiled

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Previously the Kokkos version of `comm_style tiled` did all MPI buffer pack/unpack in serial on the host CPU, which requires data transfer when running on GPUs. This PR adds full Kokkos support for `forward` and `reverse` comm. The `exchange` and `border` comm still need to be ported.

**Related Issue(s)**

None.

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

**Implementation Notes**

This is passing my tests on CPUs and 4 V100 GPUs.

### CODE REVIEW

**Comment by stanmoore1** [comment]
Whitespace issue is from upstream and is fixed here: https://github.com/lammps/lammps/pull/4090/commits/bd9f6993e3725462c8361bbff2dcf927a4144edc

**Review by sjplimp — APPROVED** [review]
nice work

**Comment by stanmoore1** [comment]
Running Kokkos regression testing on this PR now. Planning to add Kokkos support for `border` and `exchange` comm in a subsequent PR, along with a large refactor of the Kokkos `atom_vec` styles.

**Comment by akohlmey** [comment]
@stanmoore1 am getting these warnings with clang++:
```
/home/akohlmey/compile/lammps/src/KOKKOS/comm_kokkos.cpp:120:7: warning: variable 'check_forward' set but not used [-Wunused-but-set-variable]
  120 |   int check_forward = 0;
      |       ^
/home/akohlmey/compile/lammps/src/KOKKOS/comm_kokkos.cpp:121:7: warning: variable 'check_reverse' set but not used [-Wunused-but-set-variable]
  121 |   int check_reverse = 0;
      |       ^
2 warnings generated.
```

When looking closer at the code in this block, most has no effect and the function from line 120 to the end could be reduced to:
```
  if (!comm_f_only) {// not all Kokkos atom_vec styles have reverse pack/unpack routines yet
    reverse_comm_classic = true;
    lmp->kokkos->reverse_comm_classic = 1;
  }

  if (ghost_velocity && atomKK->avecKK->no_comm_vel_flag) { // not all Kokkos atom_vec styles have comm vel pack/unpack routines yet
    forward_comm_classic = true;
    lmp->kokkos->forward_comm_classic = 1;
  }
```

**Pull request merged**
