### PR TITLE
Correct compilation of GPU package when using HIP

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

A couple of things I've found while trying to compile with HIP. Still needs testing with actual hardware.*

* Fixes integer overflows when running `hip_get_devices`
* Missing change in `lal_charmm.cu` to keep it portable
* Added missing `cq()` getter in HIP `UCL_Program`
* Disabled new neighbor code for now until it is ported

*My own AMD card doesn't seem to be properly supported and hangs during code generation (Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]). With these changes, the gfx906 target compiles without errors.

**Related Issue(s)**

**Author(s)**

@rbberger (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Review by wmbrownIntel — APPROVED** [review]

**Review by sjplimp — APPROVED** [review]

**Comment by Vsevak** [comment]
I used our server with AMD Radeon VII and updated ROCm to v4.0.0. The CMake build works fine and hip_get_devices gives a correct output. But the very first call of the pair style GPU kernel throws a memory access fault. So the HIP backend would require further work... I will try to take time for this problem.
```
Initializing Device and compiling on process 0...Done.
Initializing Device 0 on core 0...Done.

Setting up Verlet run ...
  Unit style    : lj
  Current step  : 0
  Time step     : 0.005
Memory access fault by GPU node-4 (Agent handle: 0x31f17a0) on address 0x7fec2596c000. Reason: Page not present or supervisor privilege.
[jiht202overpc:53659] *** Process received signal ***
[jiht202overpc:53659] Signal: Aborted (6)
[jiht202overpc:53659] Signal code:  (-6)
[jiht202overpc:53659] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x128a0)[0x7ff1584768a0]
[jiht202overpc:53659] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7ff1564f8f47]
[jiht202overpc:53659] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7ff1564fa8b1]
[jiht202overpc:53659] [ 3] /opt/rocm-4.0.0/hip/lib/../../lib/libhsa-runtime64.so.1(+0x668df)[0x7ff1555888df]
[jiht202overpc:53659] [ 4] /opt/rocm-4.0.0/hip/lib/../../lib/libhsa-runtime64.so.1(+0x689eb)[0x7ff15558a9eb]
[jiht202overpc:53659] [ 5] /opt/rocm-4.0.0/hip/lib/../../lib/libhsa-runtime64.so.1(+0x16367)[0x7ff155538367]
[jiht202overpc:53659] [ 6] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7ff15846b6db]
[jiht202overpc:53659] [ 7] /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7ff1565dba3f]
[jiht202overpc:53659] *** End of error message ***
Aborted (core dumped)
```

**Comment by stanmoore1** [comment]
I've seen this before too with Kokkos, I think it is a known issue in the compiler. @arghdos may be able to comment further.

**Comment by akohlmey** [comment]
> I've seen this before too with Kokkos, I think it is a known issue in the compiler. @arghdos may be able to comment further.

A .0 version never causes much confidence, a .0.0 version even less so. ;-)

**Comment by akohlmey** [comment]
> I used our server with AMD Radeon VII and updated ROCm to v4.0.0. 

Thanks for looking into this. While you are at it, would you mind to also check out the OpenCL version?

**Comment by Vsevak** [comment]
> While you are at it, would you mind to also check out the OpenCL version?

Sure!
But Cmake build for OpenCL failed. Do you have any hints on what could be the reason?
```
...
[100%] Linking CXX static library liblammps.a
[100%] Built target lammps
Scanning dependencies of target lmp
[100%] Building CXX object CMakeFiles/lmp.dir/home/thevsevak/lammps/1_master_hip/src/main.cpp.o
make[2]: *** No rule to make target 'opencl_loader-build/libOpenCLd.a', needed by 'lmp'.  Stop.
CMakeFiles/Makefile2:485: recipe for target 'CMakeFiles/lmp.dir/all' failed
make[1]: *** [CMakeFiles/lmp.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

[build_log.txt](https://github.com/lammps/lammps/files/6038498/build_log.txt)

**Comment by akohlmey** [comment]
> > While you are at it, would you mind to also check out the OpenCL version?
> 
> Sure!
> But Cmake build for OpenCL failed. Do you have any hints on what could be the reason?

This is because by default we will now download, build, and link the OpenCL ICD loader from the Khronos reference sources.
There still seem to be bugs in the corresponding CMake script (I am still learning to do advanced CMake scripting).
You could try multiple things to try work around the (yet unknown) bug:
a) build a Release version or Release RelWithDebInfo version
b) don't override the OpenCL include and library path
c) disable building the ICD loader with `-DUSE_STATIC_OPENCL_LOADER=off`

Meanwhile I will look into sorting out the missed dependency issue.

**Comment by Vsevak** [comment]
> You could try multiple things to try work around the (yet unknown) bug:
> a) build a Release version or Release RelWithDebInfo version
> b) don't override the OpenCL include and library path
> c) disable building the ICD loader with -DUSE_STATIC_OPENCL_LOADER=off

I tried a) and b). OpenCL custom paths do not matter, but the build type does, so the build succeeded with default CMAKE_BUILD_TYPE.
And I didn't find any problems with OpenCL on Radeon VII in manual tests.

**Comment by akohlmey** [comment]
> I tried a) and b). OpenCL custom paths do not matter in my case, but the build type does, so the build succeeded with default CMAKE_BUILD_TYPE.

yup. thanks. it shall be fixed soon. I have reproduced this locally and implemented a fix.

> And I didn't find any problems with OpenCL on Radeon VII in manual tests.

excellent! thanks again.

**Pull request merged**
