### PR TITLE
Add method to copy Kokkos neighbor list to CPU list

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Add method to copy Kokkos neighbor list to CPU list. Gives speedup when running on GPUs and non-Kokkosized diagnostics request lists.

**Related Issues**

None.

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@akohlmey can we do full regression on this PR?

**Comment by akohlmey** [comment]
> @akohlmey can we do full regression on this PR?

full regression as some known failures for a while now. @rbberger volunteered to look into it (and then some). co-assigning him to this.

**Comment by stanmoore1** [comment]
I'm running this through full regression on my side.

**Comment by stanmoore1** [comment]
>I'm running this through full regression on my side.

Though I don't have USER-OMP tests set up. @rbberger any update on full regression on your side?

**Comment by stanmoore1** [comment]
All the tests passed on my end.

**Comment by stanmoore1** [comment]
@sjplimp can you review this PR?

**Comment by stanmoore1** [comment]
@rbberger did the relevant regression tests pass?

**Comment by akohlmey** [comment]
> @rbberger did the relevant regression tests pass?

yes. only the 6 expected failures from the RNG warm up that we still need resolving.

**Comment by akohlmey** [comment]
updated to current master to do one more round of test for compilation and running inputs.

**Pull request merged**
