### PR TITLE
Fix a bug when restarting with stored data in fix STORE/GLOBAL for global vectors or arrays

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

A couple of commands use the internal fix STORE/GLOBAL command to store a vector or array of global data.  E.g. the compute msd/chunk command does this to store the time=0 COM coords of each chunk.  When running a restarted calculation the global data is stored in the restart file.  So that in a restarted calculation, the MSD for each chunk would be continuous.

However, the restarting code in fix_store_global.cpp was not resetting the size of the global vector or array correctly, so that the global data was effectively lost.  In this case it meant the MSD was reset to zero at the beginning of the restarted run.

**Related Issue(s)**

No LAMMPS issues, but this issue was raised in the MatSci forum:
https://matsci.org/t/msd-computation-w-msd-chunk-and-restart/56657

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey I will post some info about this on the MatSci forum

**Comment by akohlmey** [comment]
@sjplimp you forgot to fix whitespace.

**Review by megmcca — APPROVED** [review]

**Comment by megmcca** [comment]
reviewed and approved but just caught @akohlmey's comment re: whitespace
copied the changes in `fix_store_global.cpp` and ran `make fix-whitespace`, nothing was flagged

**Comment by akohlmey** [comment]
> reviewed and approved but just caught @akohlmey's comment re: whitespace copied the changes in `fix_store_global.cpp` and ran `make fix-whitespace`, nothing was flagged

The issue is there since the checkstyle test flags it (whitespace issues do not fail the test, but just print a note) when you follow the link to the details https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Fcheckstyle/detail/checkstyle/10360/pipeline
You should see it, too.

Here is a protocol to efficiently do the check. This requires using the GitHub CLI from cli.github.com. After downloading and installing it you need to cd to your LAMMPS checkout and authenticate with: `gh auth login`. Then you can do: `gh pr list` and you see this is PR number 4270. This you can check out with: `gh co 4270`. Then you can co to src and do `make fix-whitespace`, add/commit the change and finally do `git push`. Since this branch allows members of the "lammps" github organization with write access to push to pull request branches, you can upload the fix right away. This even works when the branch is not in the lammps repo, but in somebody's fork. It only fails, if some fork is part of an organization with a commercial account that did not change the default setting to disallow such operations.

I just did this and there was a one line change.

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
