### PR TITLE
Grid adjust

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

Alters the way grid points are assigned to processors when a global grid is partitioned across procs.  A new Comm::partition_grid() method was added so other classes which define global grids can do this consistently.  For now, this is PPPM, PPPMDisp, MSM.  The previous method could assign grid points slightly outside a proc sub-domain to the proc which is slightly inefficient.  When global grids are coarser than the proc grid (in a dimension), the previous method was even more inefficient.

**Related Issue(s)**

N/A

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This change may lead to slight round-off changes in how grid-based quantities are computed.  E.g. long-range forces in PPPM.

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey @stanmoore1 I don't think this has any effect on accelerator packages that I could see.  It may break some regression tests, as indicated about re: round-off changes.

**Comment by sjplimp** [comment]
@stanmoore1 you should definitely test MSM and PPPM/disp with this change

**Comment by akohlmey** [comment]
@sjplimp I am seeing issues with the regression tests. For example, the attached input produces consistent results with 1, 2, or 4 MPI ranks, but different with 8.
[in.tpc.msm.txt](https://github.com/lammps/lammps/files/7017764/in.tpc.msm.txt)

**Comment by sjplimp** [comment]
@akohlmey I think Stan and I fixed this issue with MSM non-periodic.  Glad your tests caught it.

**Comment by akohlmey** [comment]
> @akohlmey I think Stan and I fixed this issue with MSM non-periodic. Glad your tests caught it.

@sjplimp did you already push this change? I cannot see it and check it out.

**Comment by sjplimp** [comment]
@akohlmey I just resynced, I think the latest changes to msm.cpp are there

**Review by stanmoore1 — APPROVED** [review]

**Pull request merged**
