### PR TITLE
Pair nm split

### PR DESCRIPTION
**Pull request by jddietz**
**Summary**
Style nm-split computes monomer-monomer interactions based on the generalized Lennard-Jones (LJ) potential by (Clarke). Here n is the parameter that controls the strength of the repulsive component of the interaction, m controls the strength of the attractive component. Note, nm/split is a modification to the already existing pair style nm/cut. Unlike nm/cut, style nm/split employs the standard LJ (n=12, m=6) above the 2^1/6σ (i.e. when forces are attractive). Applications and references to style nm-split can be found in (Hoy) where nm-split was used in conjunction with the fix bond/swap command to equilibrate long-chain Kremer-Grest bead-spring polymer melts.  Applications and references to style nm-split can be found in (Dietz, Hoy) where nm-split was used in conjunction with the fix bond/swap command to equilibrate long-chain Kremer-Grest bead-spring polymer melts. 

Style fene/nm is based on the standard FENE which consists of two components: 1) an attractive logarithmic term and 2) a repulsive Lennard-Jones (12-6) term. The “fene/nm” bond style goes hand-in-hand with the “nm/split” pair style: it replaces the usual LJ pair interactions in bond_fene.cpp with nm/splt interactions.  Used together, these allow one to combine DBH with a DPD-like procedure of starting out with soft-core repulsive interactions and gradually hardening until they achieve their final forms. 

References:
(Clarke) Clarke and Smith, J Chem Phys, 84, 2290 (1986).(Hoy) Hoy and Kröger, Phys. Rev. Lett. 124, 147801 (2020), (Dietz) Dietz and Hoy, Facile equilibration of well-entangled semiflexible bead-spring polymer melts, 2021 (publishing soon) 

**Related Issue(s)**

**Author(s)**
Robert S. Hoy (rshoy@usf.edu) and Joseph D. Dietz (jfoxd94@gmail.com or josephfox@usf.edu), University of South Florida

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**
Changes will not break backwards compatibility

**Implementation Notes**
Please see attached README files in addition to example scripts

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**
Coming Paper
J. D. Dietz and R. S.  Hoy, Facile equilibration of well-entangled semiflexible bead-spring polymer melts, 2021

[DBHequilscript-kbend0.0.gz](https://github.com/lammps/lammps/files/6504167/DBHequilscript-kbend0.0.gz)

[FRInitState.kbend0.0.Nch1000.N400.bond0.961.rho0.850.theta105.8.gz](https://github.com/lammps/lammps/files/6504171/FRInitState.kbend0.0.Nch1000.N400.bond0.961.rho0.850.theta105.8.gz)
[ README-equilibscripts.txt](https://github.com/lammps/lammps/files/6504173/README-equilibscripts.txt)
[FRInitState.kbend3.0.Nch1000.N400.bond0.961.rho0.850.theta132.6.gz](https://github.com/lammps/lammps/files/6504178/FRInitState.kbend3.0.Nch1000.N400.bond0.961.rho0.850.theta132.6.gz)
[DBHequilscript-kbend3.0.gz](https://github.com/lammps/lammps/files/6504179/DBHequilscript-kbend3.0.gz)

### CODE REVIEW

**Comment by akohlmey** [comment]
@jddietz Thanks for your submission. Unfortunately, there are several problems with your submission.
In general, please have a careful look at the instructions given at https://github.com/lammps/lammps/blob/master/.github/CONTRIBUTING.md#contributing-code and
https://lammps.sandia.gov/doc/Modify_contribute.html

Both new classes should **not** be implemented as standalone classes, but rather as derived classes from their corresponding counter parts, since that will allow a large amount of code sharing.

Also I noticed that the files were added in the wrong folder, that the documentation should not be in that folder as well, but integrated into the existing documentation for pair style nm/cut and bond style fene. Also there are further steps necessary to add links from the lists of commands that need to be included.

The description for pair style nm/split says "Unlike nm/cut, style nm/split employs the standard LJ (n=12, m=6) potential above the user-specified cutoff r_c" but that is not what is implemented. In fact a pairwise potential in LAMMPS **must** have a cutoff.
Instead the switch seems to be at the minimum of the 12-6 LJ provided one uses reduced units.

The pair nm/split has an incorrect "single()" function (it is unchanged from nm/cut) so either the use of the single function must be disabled or it needs to be implemented correctly.

All C++ files seem to be modified from older versions of their originals. We have since refactored and reformatted the originals, so the modified versions need to reflect that.

My recommendation is to start over with a new branch fresh from the latest upstream version of "master" and then define the derived classes (following the naming conventions) and then implement only what modifications need to be done and re-using as much existing code as possible from the parent classes.

**Comment by akohlmey** [comment]
@jddietz do you have any feedback for us on how you plan to proceed with this contribution?

**Comment by rshoy** [comment]
@akohlmey  Hi Axel!  Sorry for the delayed reply, I’ve been busy with other projects the past several days.  I see that Joe already corrected the descriptive text to clarify that the potential is 12/6 for r > 2^{1/6}σ   (i.e. not r > r_c as he’d written in the first version).  So, that addresses one of your comments.  

Regarding your other comments:

1) The original versions of the nm/split and fene/nm pair and bond styles were indeed modified from older versions of nm/cut and fene, but I'd thought the ones Joe submitted were modified versions of the current (10/29/20) nm/cut and fene.  You're saying that isn't the case?

2) About making them "derived" classes, I'm assuming you mean you want something along the lines of pair_nm_cut_coul_cut and bond_fene_expand, right?

3) Joe, please correct the single() function so it implements our modified (split) potential, and integrate our documentation into the existing documentation as Axel suggests.

4) Sure, we can start over with a new branch if you wish :)

Best,
Rob

**Comment by akohlmey** [comment]
> @akohlmey Hi Axel! Sorry for the delayed reply, I’ve been busy with other projects the past several days. I see that Joe already corrected the descriptive text to clarify that the potential is 12/6 for r > 2^{1/6}σ (i.e. not r > r_c as he’d written in the first version). So, that addresses one of your comments.

Not entirely. Last time I looked the implementation was only consistent with that description for sigma == 1.0.

> 
> Regarding your other comments:
> 
> 1. The original versions of the nm/split and fene/nm pair and bond styles were indeed modified from older versions of nm/cut and fene, but I'd thought the ones Joe submitted were modified versions of the current (10/29/20) nm/cut and fene.  You're saying that isn't the case?

"current" as far as development is concerned is the "master" branch and that has seen significant refactoring and updating since the last stable release and also formal changes to implement new conventions with respect to formatting and order of include statements. the latest change was to prepare for a change in the URL for the LAMMPS home page that was merged only yesterday.

> 2. About making them "derived" classes, I'm assuming you mean you want something along the lines of pair_nm_cut_coul_cut and bond_fene_expand, right?

No. I am thinking more along the lines of `pair_nm_cut.cpp/.h` and `pair_nm_cut_omp.cpp/.h` the latter only updates the constructor and the compute method. In your case, only compute() and single() seem to be different in the pair style (haven't looked in detail at the bond styles, they may need to be done differently, e.g. instead of overriding the complete function, you could just call the original and some additional code.

> 3. Joe, please correct the single() function so it implements our modified (split) potential, and integrate our documentation into the existing documentation as Axel suggests.

the documents I referenced and the section in the LAMMPS docs about building the manual provide many details of what can be  done to avoid issues. the resulting doc pages should cleanly translate to html and pdf and look proper when viewed locally.

> 4. Sure, we can start over with a new branch if you wish :)

yes, please do so. it would produce a much cleaner commit history.

> Best,
> Rob

**Comment by jddietz** [comment]
Sorry for the delay Axel. I had already gone through the process of rewriting the .cpp/.h files from the latest "pair_nm_cut.cpp/.h" (from the master branch).  I had done this in a new branch, but I hadn't submitted a pull request yet.

Thank you for clarifying the part about the "derived classes" . In my updates, I had created "pair_nm_cut_split.cpp/.h" as an extension of "pair_nm_cut.cpp/.h". I'll go through it again and make the changes.

**Comment by jddietz** [comment]
Hi Axel,

I apologize for not replying to your comment sooner. Next time, I'll be more courteous  and let you know that I need a little more time to draft a more well-informed response.

Sincerely,
Joe

**Comment by akohlmey** [comment]
Pull request will be resubmitted after the code has been updated.

**Pull request closed without merging**
