### PR TITLE
build a RBC Membrane model

### PR DESCRIPTION
**Pull request by ZhaoyanHuang**
**Summary**

build a RBC Membrane model with LAMMPS

**Related Issue(s)**

N/A

**Author(s)**

Hongyan Yuan, Mehdi Baghaee Karkaragh, ZhaoyanHuang, Southern University of Science and Technology

2205177599@qq.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

1.When compiling LAMMPS using the approach described by LAMMPS website that is specific to your machine, make sure to first run command “make yes-asphere” to include the asphere package.

2.In the examples/ASPHERE/rbc directory, open the file “create_rbc_withwater.m” using the Matlab program and run the provided code. Running this code will generate/output two files necessary for the model in your current working directory;
A. PSF ( Protein Structure File) “ rbc_D50AA9m12_N21702_W_water.psf ”
B. Read Data File “ read_data.rbc_ D50AA9m12_N21702_W_water_d0_water”
• The PSF file specifies the bonds present in the model and will only need to be loaded when visualizing the output of the LAMMPS simulation.
• The Read Data file will be used and called upon by the input file “in_rbc_membrane_w_water “run by LAMMPS

3.The input file used for the LAMMPS simulation is called “in_rbc_membrane_w_water” and contains the necessary parameters to run the RBC membrane model simulation. It uses the read data file “ read_data.rbc_ D50AA9m12_N21702_W_water_d0_water” as the initialconfiguration of the RBC membrane model.
To run the input file, place the LAMMPS executable, the read data file, the input file above into your specified working directory and issue following commands based on whether serial or parallel.

serial:
"./lmp_serial < in_rbc_membrane_W_water"

parallel：
"mpirun –np 8 ./lmp_serial < in_rbc_membrane_W_water"

4.To visualize the simulation trajectory, open VMD (Visual Molecular Dynamics) program and first load the dump file above and the load the PSF file “rbc_D50AA9m12_N21702_W_water.psf” produced from the Matlab code program above.

**Post Submission Checklist**

- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**
N/A

### CODE REVIEW

**Comment by akohlmey** [comment]
@ZhaoyanHuang thanks for your contribution. However, there are multiple issues. Please see https://docs.lammps.org/Modify_style.html for a guide with instructions on how to best comply with the conventions and requirements for contributions. Most importantly:
- *any* new feature (like your pair style) must be documented with a suitable .rst file in the doc/src folder
- all integration testing checks must be passed
- check out the requirements for citations embedded in the source code versus in the documentation.
- check out the programming style recommendations and requirements

Furthermore, your example looks more like a tutorial. The examples in the LAMMPS distribution are meant to be a minimal demonstration of how to employ features in a LAMMPS input file, neither a complete system preparation procedure and - most importantly - it should not depend on any tools outside of LAMMPS or those bundled with LAMMPS. This can be either expanded into a Howto document (but then it needs more background information and details) or it could be published on a separate tutorial website (a good way to advertise your research, too) and then just the URL needs to be provided in the documentation.

p.s.: we discourage the use of I/O redirection when running LAMMPS in parallel and thus recommend for examples and tutorials in particular to use the `-in` flag instead to set a good example for new LAMMPS users.

**Comment by akohlmey** [comment]
P.P.S: it is also advisable to avoid acronyms and "domain specific 'slang' terms" unless they are explained. For example, not everybody doing MD simulations knows what RBC stands for. It can stand for multiple things anyway: see e.g. https://en.wikipedia.org/wiki/RBC

**Comment by akohlmey** [comment]
@ZhaoyanHuang if you need help implementing the requested changes or need clarifications, please don't hesitate to ask.

**Comment by sjplimp** [comment]
@ZhaoyanHuang Thanks for submitting this new pair style and example.  In addition to Axel's suggestions, I have 2 organizational comments.

a) the Matlab script should go in a tools/rbc dir with its own README on how to run it - the README in the examples dir can point to that.  If the data file it produces is small enough it can be included in the examples dir - otherwise the examples README should just explain the user needs to run the tool first
b) I think your rbc examples dir should be under examples/PACKAGES, not examples/ASPHERE

Thanks

**Comment by akohlmey** [comment]
@ZhaoyanHuang without any feedback from you in any form, we cannot move forward with this. Thus I will close this pull request now. Please submit a new pull request when you have everything ready and make sure you update to the latest upstream version of LAMMPS.

**Pull request closed without merging**
