### PR TITLE
Bond/react: new examples and repackage

### PR DESCRIPTION
**Pull request by jrgissing**
**Summary**

Added two new examples for bond/react (simple epoxy, and polymerization of styrene). 
Also, repackaged bond/react into USER-REACTION
also, dihedral reaction constraint

**Related Issues**

none

**Author(s)**

Jacob Gissinger
info@disarmmd.org

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

repackages bond/react into USER-REACT

**Implementation Notes**

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] A package specific README file has been included or updated
- [x] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
I am not happy with the name of the package `USER-REACT` as it is very similar to `USER-REAXC` and thus users might confuse the two. How about `USER-BONDREACT`?
@sjplimp what is your opinion/suggestion?

Also, when adding a new package, there have to be changes made to the `src/Makefile`, `cmake/CmakeLists.txt` and some or all of `doc/src/Build_basics.rst`, `doc/src/Build_extras.rst`, `doc/src/Build_package.rst`, `doc/src/Packages_details.rst`, and `doc/src/Packages_user.rst`.

**Comment by sjplimp** [comment]
I like the name BONDREACT.  Jake?

**Comment by jrgissing** [comment]
I think the name BONDREACT will become overly restrictive in the near future, as other related fixes are added. The larger vision is for it to encompass a number of features beyond just simply creating bonds. I personally think USER-REACT is better and don't think the risk of confusion is a big worry, but could brainstorm other ideas

**Comment by akohlmey** [comment]
> I think the name BONDREACT will become overly restrictive in the near future, as other related fixes are added. The larger vision is for it to encompass a number of features beyond just simply creating bonds. I personally think USER-REACT is better and don't think the risk of confusion is a big worry, but could brainstorm other ideas

In my now 20+ years in dealing with open source scientific software i have learned to never underestimate the ability of people to misunderstand something. As LAMMPS is gaining popularity beyond programmers and people that do read documentation carefully, we should not assume too sophisticated users. To give an example: one major motivation for me to push toward having the REAX package removed from LAMMPS was the fact, that I got tired of having to explain on the lammps-users mailing list the difference between the USER-REAXC and the REAX package, and those names are more difference that USER-REAXC and USER-REACT.

So what other feature will be added? Is there some "common theme" that we could use for naming the new package?


so what other features

**Comment by stanmoore1** [comment]
> I am not happy with the name of the package USER-REACT as it is very similar to USER-REAXC and thus users might confuse the two. 

I'm going to second this. Surely there is some other name we can find.

**Comment by jrgissing** [comment]
things currently in the pipeline include a fix that makes it possible to create new molecules (or atoms) at precise locations in the vicinity of other nearby molecules (or atoms). this would include adding bonded interactions

another option is to base on the more general name for the protocol, i.e., USER-DISARMMD

**Comment by sjplimp** [comment]
How about USER-TOPO or TOPOLOGY for changes to
bond topology.  Or USER-MORPH?  Just ideas ...

**Comment by stanmoore1** [comment]
USER-REACTION, USER-CHEM

**Comment by jrgissing** [comment]
my top choices so far would be USER-TOPOLOGY or USER-REACTION

**Comment by akohlmey** [comment]
@jrgissing FYI, I just imported commit d897949ff87bb721a0d6ab86e40405418df5385b into PR #1853 so it will already be in the next patch and stable release.

**Comment by akohlmey** [comment]
@jrgissing this has merge conflicts in the documentation. Since we have completed the stable release, this is now a candidate to be merged (after successful review).

**Pull request merged**
