### PR TITLE
Fix CUDA-aware MPI issues with KOKKOS package

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**
This PR changes the CUDA-aware MPI checks from runtime to compile time, see https://www.open-mpi.org/faq/?category=runcuda. Also use "CUDA-aware MPI" instead of "GPU-direct". GPU-direct is a driver-level communication mode that requires CUDA-aware MPI but is different than CUDA-aware MPI. Also fixes an issue that prevented switching CUDA-aware off and adds more checks for MPICH, MVAPICH2, and Spectrum MPI.

**Author(s)**

Stan Moore (SNL), Alfredo Metere (International Computer Science Institute), helped by suggestions from Roy Musselman (IBM)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Changes the KOKKOS package `gpu/direct` keyword to `cuda/aware`.

### CODE REVIEW

**Comment by stanmoore1** [comment]
Actually the workaround doesn't work since Spectrum MPI also messes up the compile check. This PR does fix an issue that prevented switching CUDA-aware MPI off though.

**Comment by stanmoore1** [comment]
@metere1llnl can you take a look?

**Comment by stanmoore1** [comment]
I tested this on Lassen with Spectrum MPI and it works correctly as far as I can tell. These changes were also approved by @metere1llnl via email. @akohlmey, this PR is ready to merge.

**Comment by stanmoore1** [comment]
Actually more changes to come for an improved Spectrum MPI workaround.

**Comment by stanmoore1** [comment]
@metere1llnl good point, I updated based on your suggestion.

**Comment by metere1llnl** [comment]
Looks good to me now! :-)

**Comment by stanmoore1** [comment]
This finally works as I wanted

**Pull request merged**
