### PR TITLE
fixed bounds of loops in ML-IAP

### PR DESCRIPTION
**Pull request by bathmatt**
**Summary**

There was a bug with loop bounds not going over ghost particles
**Related Issue(s)**

**Author(s)**

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by bathmatt** [comment]
I am going to suggest @lubbersnick @bnebgen-LANL or one of the HippyNN team look at this and approve.

**Comment by lubbersnick** [comment]
@SakibMatin or @bnebgen-LANL could I ask one of you to test this version against ASE and report back?

**Comment by stanmoore1** [comment]
@bathmatt some Kokkos unit tests are giving a segmentation fault:
```The following tests FAILED:
	329 - ManybodyPairStyle:mliap_nn (SEGFAULT)
	330 - ManybodyPairStyle:mliap_snap_chem (SEGFAULT)
	331 - ManybodyPairStyle:mliap_snap_linear (SEGFAULT)
	332 - ManybodyPairStyle:mliap_snap_quadratic (SEGFAULT)
```

**Comment by bathmatt** [comment]
OK, I'll look on Thursday,

**Comment by sakibmatin** [comment]
I can test the ASE versions against this.

**Comment by bathmatt** [comment]
sorry, I fixed the typo, it was a cut error.  removed too much code, put it back

**Review by stanmoore1 — APPROVED** [review]
I approve, thanks @bathmatt!

**Pull request merged**
