### PR TITLE
Remove fix latte and LATTE package and examples and lib

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

Remove support for the fix latte command from LAMMPS.  This has been superseded by the MDI fixes,
namely fix mdi/qm and fix mdi/qmmm, which wrap several quantum packages, including LATTE.
See the examples/QUANTUM dir and the Howto_mdi.html doc page.  MDI supports running LAMMPS with
LATTE as a plugin library (similar to the way fix latte worked), as well as on a different set of MPI  processors.

**Related Issue(s)**

N/A

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey I think I found all the places in the docs and src where the LATTE package was referenced.  One exception is CMake.

**Comment by akohlmey** [comment]
> @akohlmey I think I found all the places in the docs and src where the LATTE package was referenced. One exception is CMake.

@sjplimp There were a bunch more things that needed updating: `src/Purge.list`, `src/.gitignore`, `doc/src/Commands_removed.rst` and a few minor issues.

CMake scripts have been updated, too. Let's see if any changes are needed for the full testing...

**Review by junghans — APPROVED** [review]
CMake part is just removing things.

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
