### PR TITLE
Collected small changes

### LINKED ISSUE #2170: [BUG] create_atoms rotate keyword manual/code disagreement
**Summary**

Documentation suggests that the angle after the rotate keyword in the create_atoms command must be in degrees, but it's coded in radians.

**LAMMPS Version and Platform**

12 Dec 2018 Ubuntu checked, but no related recent (for 6 years) changes to the functionality

**Expected Behavior**

As the manual suggests, the rotation angle should be in degrees:
[https://lammps.sandia.gov/doc/create_atoms.html](url)

> *rotate* values = theta Rx Ry Rz
>   theta = rotation angle for single molecule (**degrees**)
>   Rx,Ry,Rz = rotation vector for single molecule

**Actual Behavior**

The angle is interpreted in radians.

**Steps to Reproduce**

A minimal example is attached. It produces a dump with rotation around the x-axis.

**Further Information, Files, and Links**

Potentially problematic code:
**create_atoms.cpp**

> thetaone = force->numeric(FLERR,arg[iarg+1]);
> ...
> MathExtra::axisangle_to_quat(axisone,thetaone,quatone);

The function uses standard sine function, which expects radians. 

[input file create_atoms_problem.txt](https://github.com/lammps/lammps/files/4805762/create_atoms_problem.txt)
[molecule file tripod.txt](https://github.com/lammps/lammps/files/4805763/tripod.txt)

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request collects various small changes and updates

**Related Issues**

#2158 
fixes #2170 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

The following individual changes are included:
- Add support for checking `UNITS:` metadata tag in potential files to legacy potential file reader
- Set required units in potential file reader tests
- Add command line option to not capture stdout to potential file reader tests
- Add a folder and some tests for (simple) LAMMPS commands
- Add `[[ noreturn ]]` C++11 attributes to the functions in the Error class that do not return
- Plug memory leak in AtomVec classes
- Plug memory leaks in pair styles polymorphic, eam/cd
- Fix a substantial memory leak in kspace style MSM
- Make certain that allocated buffers in Comm::rendezvous_all2all() are not NULL
- Reintroduce CMake settings for code sanitizers
- Call MPI_Finalize() from test programs that use LAMMPS instances to avoid spurious memory leak reports by valgrind's memcheck tool
- Initial version of a tester program for testing basic atom style functions
- Document coding-style tools
- Document additional test programs

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] Suitable tests have been added to the unittest tree.

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey 
Re: the atom_vec.cpp change, this is for the case where the atom style is changed?
Should the destroy() calls in the destructor of the Atom class, thus be removed?
Re: changes in Comm:rvous() to add +1 to the allocations - why is this?

**Comment by akohlmey** [comment]
> @akohlmey
> Re: the atom_vec.cpp change, this is for the case where the atom style is changed?
yes. so every time atom style is not atomic.

> Should the destroy() calls in the destructor of the Atom class, thus be removed?

i am trying to adjust those kind of calls all over the code, so that they can be safely called multiple times. had to do that, too, to fix the leak in kspace style msm. when deleting arrays of pointers, you first need to free the data those pointers point to, but sometimes only those pointers may be updated.

> Re: changes in Comm:rvous() to add +1 to the allocations - why is this?

in some (small) test inputs,  `memory->smalloc()` was called with a size of 0 which returns a null pointer. however, passing a null pointer to memset() or MPI calls is illegal, even if the length is signaled to be 0. the GNU libc memset() does not segfault and MPICH and OpenMPI on Linux are fine with those, too. But i recall having issues with the MPI on IBM blue gene machines with that kind of code construct. By adding 1 those allocations are finite, a pointer is returned and the following calls will not segfault.

**Comment by akohlmey** [comment]
> @akohlmey
> Re: the atom_vec.cpp change, this is for the case where the atom style is changed?

BTW: this leads to the situation, that when switching from atom style charge to atomic, there still is data allocated for atom->q.
I noticed it when writing the tester tools for atom style classes.

**Comment by sjplimp** [comment]
@akohlmey 
Re: comm +1 changes - makes sense - please just add a comment in the rvous() method
to explain why the +1 was added
Re: avec changes - agree with putting the memory dealloc calls in the Avec destructor,
but why not thus remove them from the Atom destructor - one less place for the
user to add customization for new vecs/arrays.  Also there is no problem calling
mem->destroy() with a NULL ptr.  It should just exit.

**Comment by akohlmey** [comment]
> @akohlmey
> Re: comm +1 changes - makes sense - please just add a comment in the rvous() method
> to explain why the +1 was added

done

> Re: avec changes - agree with putting the memory dealloc calls in the Avec destructor,
> but why not thus remove them from the Atom destructor - one less place for the
> user to add customization for new vecs/arrays. Also there is no problem calling
> mem->destroy() with a NULL ptr. It should just exit.

ok. i removed them from atom.cpp and added deleting the "fixed" entries to the destructor in atom_vec.cpp
also renumbered the comments in atom.cpp

**Pull request merged**
