### PR TITLE
tweaks to Manual formatting

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Tweaks to high-level Manual formatting.

## Author(s)

Steve

## Backward Compatibility

N/A

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
@rbberger For the first page of the Manual, do you like the two-level TOC?  I kind
of like the bare-bones 1-level, i.e. ~12 sections only.  B/c the next level of Howto, Tools,
makes the TOC too long IMHO ...

**Comment by HaoZeke** [comment]
I suppose the usability of the manual in `pdf` format would be greatly reduced with only level one headings...

**Comment by rbberger** [comment]
@sjplimp I like what you did in Build*.txt. Looks tidy. I would keep the two-level TOC on the first page. It just shows that Tools and Howto could use some topic headers/categories.
@HaoZeke for the PDF the Sphinx TOC is ignored. htmldoc creates it's own TOC based on the HTML header levels. Different tool.

**Comment by sjplimp** [comment]
@rbberger For Tools and Howto does that mean I would have to create dummy pages
that just list Howto topics within a category?  I don't want to do that b/c categories
will be kind of artificial/ad-hoc.  There is such a spread of tools and howtos.  
Also, I'd just like the full list of tools or howto topics
to be viewed on single page of the lower-level doc page (e.g. Tools.html) so readers can see
them all.  So is there a way just to suppress the full list for those 2 headings on the
Manual.html page?  That's the page where I think it's too much detail.  Having the next level listed for the other sections on Manual.html is fine.

**Comment by rbberger** [comment]
@sjplimp I don't agree, can we leave it as is and get the release done like this?

**Comment by sjplimp** [comment]
@rbberger ok, we can leave Manual.html as-is for now.

**Pull request merged**
