### PR TITLE
workaround for double free issue when using USER-COLVARS with with lammps python wrapper and python package

### LINKED ISSUE #208: Incompatibility between PYTHON package and USER-COLVARS
For some reason installing the USER-COLVARS package breaks the Python interface of LAMMPS. The part that calls Python code from LAMMPS, not the other way around. This can be shown easily with the `examples/python/in.python` script.

I can also report that it only happens if the binary includes colvars. Since the script doesn't use colvars, my best guess is some static allocation, deallocation issue?

### This works without a problem:
```
virtualenv --python=$(which python2) pyenv
source pyenv/bin/activate
make -C src yes-python
make -C src serial
make -C src mode=shlib serial
cd python
python install.py
cd ../examples/python
../../src/lmp_serial -in in.python  # runs ok
```
### Steps to reproduce issue:
```
virtualenv --python=$(which python2) pyenv
source pyenv/bin/activate
make -C lib/colvars -f Makefile.g++ CXX=g++
make -C src yes-python
make -C src yes-USER-COLVARS
make -C src serial
make -C src mode=shlib serial
cd python
python install.py
cd ../examples/python
../../src/lmp_serial -in in.python  # runs, but dies nasty
```

```
*** Error in `../../src/lmp_serial': double free or corruption (fasttop): 0x0000000002659eb0 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x70c4b)[0x7f5fc7d0bc4b]
/usr/lib/libc.so.6(+0x76fe6)[0x7f5fc7d11fe6]
/usr/lib/libc.so.6(+0x777de)[0x7f5fc7d127de]
/usr/lib/libc.so.6(+0x35990)[0x7f5fc7cd0990]
/usr/lib/libc.so.6(+0x359ea)[0x7f5fc7cd09ea]
/usr/lib/libc.so.6(__libc_start_main+0xf8)[0x7f5fc7cbb298]
../../src/lmp_serial(_start+0x2a)[0x494a0a]
======= Memory map: ========
...
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by akohlmey**
this closes #208

### CODE REVIEW

**Comment by akohlmey** [comment]
@giacomofiorin i'll be recommending this for inclusion into upstream now. if you have any objections, holler. Note that we can always change this later and i am not pushing this into colvars for now. After all, this is a problem only exposed by the broken(?) way of how LAMMPS cannot access the symbols of the executable from the python wrapper.

**Comment by giacomofiorin** [comment]
Doing it now.

**Comment by akohlmey** [comment]
So what is the objection?

**Comment by giacomofiorin** [comment]
No objections.  Actually, I was about to change instead `cvm::line_marker` to an inline function, and remove a few more static members.  If your workaround fixes the double-free error for now, I can just hold off more changes until the next Colvars update.  So yes, please merge the PR.

**Comment by akohlmey** [comment]
Yes, it avoids the double free error, and also avoids the code duplication from inline functions. ;-)

**Pull request merged**
