### PR TITLE
Add Python 3 compatibility and expand Python interface availability

### PR DESCRIPTION
**Pull request by rbberger**
This PR moves the LAMMPS Python interface to top level classes. Any pointers-derived class can access the Python instance of the current LAMMPS object. Python functions previously declared using a `python` command may be executed from any part of the LAMMPS code if that feature is enabled.

This could be extended to allow further access to functions and data in the Python interpreter namespace. But we'd have to further discuss what kind of support is needed (accessors, wrapper functions which ensure the interpreter is initialized, etc).

In addition, these changes add Python 3 compatibility to the PYTHON package.

### CODE REVIEW

**Comment by akohlmey** [comment]
When i use the following example input:
```
lattice		fcc 0.8442
region		box block 0 10 0 10 0 10
create_box	1 box

variable        N equal 10
variable        PYPRINT python pyprint

python          pyprint input 2 SELF v_N return v_PYPRINT format pif here """
def pyprint(lmpptr,N):
     print("N=",N)
     print("ptr=",lmpptr)
     from lammps import lammps
     lmp=lammps(ptr=lmpptr)
     print("lmp=",lmp)
     return float(N)

"""
python          pyprint invoke
```
It is working fine in python 2 and i get the expected output:
```
LAMMPS (11 Apr 2017)
  using 1 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 1.6796 1.6796 1.6796
Created orthogonal box = (0 0 0) to (16.796 16.796 16.796)
  1 by 1 by 1 MPI processor grid
('N=', 10)
('ptr=', <PyCObject object at 0x7f488b9a74e0>)
('lmp=', <lammps.lammps object at 0x7f488b9a48d0>)
Total wall time: 0:00:00
```
With python3, however, it seems the SELF reference is not properly passed to python:
```
LAMMPS (11 Apr 2017)
  using 1 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 1.6796 1.6796 1.6796
Created orthogonal box = (0 0 0) to (16.796 16.796 16.796)
  1 by 1 by 1 MPI processor grid
N= 10
ptr= <capsule object NULL at 0x7f48beb72750>
ERROR on proc 0: Python function evaluation failed (../python_impl.cpp:315)
```
It looks like a NULL pointer is passed instead of the actual reference to the LAMMPS object, so the LAMMPS python module can use it instead of creating a new instance.

**Comment by rbberger** [comment]
The pointer is passed correctly. It works in Python 3.6. That NULL shouldn't have an effect. It is just a name for the encapsulated pointer. NULL is a [valid value](https://docs.python.org/3.1/c-api/capsule.html) as long as it's also used on the other end. That's what updated `lammps` class does.
```
LAMMPS (11 Apr 2017)
Lattice spacing in x,y,z = 1.6796 1.6796 1.6796
Created orthogonal box = (0 0 0) to (16.796 16.796 16.796)
  1 by 1 by 1 MPI processor grid
N= 10
ptr= <capsule object NULL at 0x7f26693d1c30>
lmp= <lammps.lammps object at 0x7f2669395d68>
Total wall time: 0:00:00
```
Did do reinstall the Python package after recompiling? Did you use mode=shexe or mode=shlib? Which Python 3 version are you using?

**Comment by akohlmey** [comment]
Yes, i reinstalled the python package (had to, because due to the renames, LAMMPS thought it was gone).
compilation was from scratch. `liblammps.so` was updated, even though it should technically not be needed: the compilation flags from `lib/python` should reexport symbols from the LAMMPS executable, and lammps.py will try to use those before trying to load `liblammps.so`.

the python version is 3.5.3

**Comment by akohlmey** [comment]
OK. i think i have found the issue. i did re-install the python ctypes wrapper, but i forgot to set PYTHON=python3, so it installed the new version only in the python 2.7 tree, and thus when i ran the python3 version, it didn't correctly cast the LAMMPS object pointer to a ctypes style pointer and that caused the failure. repeating the installation of the python wrapper with the correct flag, makes it work as expected. so no further change needed, unless i can figure out a way to make the master make file pick up the settings automatically.

**Comment by akohlmey** [comment]
@rbberger I've added some changes to the build system and also updated the `README` file in `lib/python` so that the default value for the `PYTHON` variable is now imported from `lib/python/Makefile.lammps` and thus installation of the python wrapper module should be automatically adapted depending on the choice of the python version to link to. Since we also support python3 transparently, the default file does no long er have to prefer python 2. We rather default to the default python.
p.s.: there is something fishy with the `testing-pr` task. it seems to get triggered on comments and not on pushes to the branch.

**Comment by akohlmey** [comment]
Here is my output of the test example for your reference:
```
$ ~/compile/lammps-icms/src/lmp_py2 -in in.check 2>&1 
LAMMPS (11 Apr 2017)
  using 1 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 1.6796 1.6796 1.6796
Created orthogonal box = (0 0 0) to (16.796 16.796 16.796)
  1 by 1 by 1 MPI processor grid
('N=', 10)
('ptr=', <PyCObject object at 0x7f6c48e044e0>)
('lmp=', <lammps.lammps object at 0x7f6c48e018d0>)
Total wall time: 0:00:00
$ ~/compile/lammps-icms/src/lmp_py3 -in in.check 2>&1 
LAMMPS (11 Apr 2017)
  using 1 OpenMP thread(s) per MPI task
Lattice spacing in x,y,z = 1.6796 1.6796 1.6796
Created orthogonal box = (0 0 0) to (16.796 16.796 16.796)
  1 by 1 by 1 MPI processor grid
N= 10
ptr= <capsule object NULL at 0x7fdb75559750>
lmp= <lammps.lammps object at 0x7fdb751ffb00>
Total wall time: 0:00:00
```

**Comment by akohlmey** [comment]
BTW: with the refactoring, one can "see" externally defined python functions and invoke them from LAMMPS. E.g. like this:
```python
from lammps import lammps

def testfunc(text):
    print("text=",text)

def pyprint(lmpptr,N):
     print("N=",N)
     print("ptr=",lmpptr)
     from lammps import lammps
     l=lammps(ptr=lmpptr)
     print("lmp=",l)
     return float(N)

lmp=lammps()
lmp.command('region box block -5 5 -5 5 -5 5')
lmp.command('create_box 1 box')
lmp.command('variable        N equal 10')
lmp.command('variable        hello string "Hello, World!"')
lmp.command('variable        PYPRINT python pyprint')
lmp.command('python          pyprint input 2 SELF v_N return v_PYPRINT format pif exists')
lmp.command('python          pyprint invoke')
lmp.command('python          testfunc input 1 v_hello format s exists')
lmp.command('python          testfunc invoke')
```

**Comment by giacomofiorin** [comment]
@rbberger The code looks overall as intended for me. I am still catching up with the backlog left after my travel last week, but I plan on testing the code with a sample call in the next few days. As for the PR itself, I am happy enough with the way it goes.

**Comment by akohlmey** [comment]
Sorry, but i don't agree with the last change. This `Python::request()` method does not make any sense in the naming conventions inside of LAMMPS. It would make **much** more sense to make `Python::init()` public and put the test for whether the `Python::impl` pointer is initialized into that method, too. I'll do the corresponding changes now and will push them.

**Comment by giacomofiorin** [comment]
@akohlmey Thanks for the simplification! I though that a private `init()` was a design choice with a specific reason in mind. My preference is for a public `init()`, of course.

**Comment by rbberger** [comment]
@akohlmey and @giacomofiorin: I suggest to keep this PR now as it is and allow Steve to merge it. The changes we discussed should be collected in an issue and tackled in a separate PR.

**Comment by rbberger** [comment]
@sjplimp the merge should now work again

**Pull request merged**
