### PR TITLE
new checksum for LATTE download

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

New LATTE download checksum from Christian Negre.

## Author(s)

Steve

## Backward Compatibility

Does CMake also need to be changed to track this?

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp  yes, the corresponding cmake entry needs to be updated as well. is there are new version number, too?
BTW: @cnegre in case there is no new version number (tag), please note, that changing the release without changing the version number is considered a bad thing. @rbberger recently showed me a youtube link with a talk on the worst offenses that software developers can do to make the life of (distribution) package maintainers hell. this was one of them. it listed some very well known software packages there, so this is not uncommon...

**Comment by akohlmey** [comment]
@sjplimp CMake support is updated and tested successfully against the updated MD5 sum.  i've added a small maintenance patch to src/Purge.list as well. ready for inclusion.

**Comment by junghans** [comment]
@cnegre and @akohlmey Do we understand why the checksum has changed?

**Comment by junghans** [comment]
Oh, I found that already https://github.com/lanl/LATTE/commit/61223bbc7d954534bc303920374878fa8bdae13a#commitcomment-29620795

**Comment by cnegre** [comment]
No idea

**Comment by cnegre** [comment]
Good to know. Thanks!

**Pull request merged**
