### PR TITLE
Consolidate clearing of eflags and vflags

### PR DESCRIPTION
**Pull request by martok**
Note: Purpose of the PR changed as per Comment #1

**Summary**

When applying flags at the start of a compute call, most pair styles only clear some of the flags. There is a function ev_unset that clears all flags, but that is rarely used.
The same pattern exists for fixes, impropers, angles, dihedrals, bonds and kspace styles.

This PR replaces the shared pattern with a central function that clears all flags.

**Author(s)**

Sebastian Hütter (OvGU)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No functional changes (hopefully!).
However, as a large number of files was changed that did not clear some flags, if at any point they were used erroneously, that might matter now.

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Regression test suite including accelerators passes

### CODE REVIEW

**Comment by akohlmey** [comment]
@martok pair->compute(0,0) is called quite frequently, e.g. during MD with fixed volume or minimization, when there is no thermo output or other access to energies. That not all pair styles call ev_unset() must be for historical reasons, i.e. the manual clearing of those flags must have been used until somebody, probably @sjplimp decided to consolidate it, but then did not apply it everywhere for reasons unknown. The difference, that I is that `eflag_either` is not zeroed, which doesn't seem to be used a lot.

So, if we are consolidating it now, we should be doing it now all the way. I am assigning @sjplimp to this PR so he can keep an eye on it and give further advice.

**Comment by martok** [comment]
Aye, `eflags_either` was the problem in this case.
I'll grep over the other pair styles make the same change, then.

**Comment by akohlmey** [comment]
@sjplimp can you make looking at this a priority? i'd like to have this change, if approved, included quickly.

**Comment by timattox** [comment]
Changes to USER-DPD look fine.  I hope to try them out in my test suite tomorrow.

**Comment by akohlmey** [comment]
@sjplimp your requested tweak is applied. please confirm, that this is what you asked for.

**Pull request merged**
