### PR TITLE
Move coord2bin() from npair.cpp to nbin.cpp. Reduces code duplication.

### PR DESCRIPTION
**Pull request by timattox**
This isn't "necessary", but reduces the duplication of code for easier
long term maintenance.  I'll also be using the longer form of coord2bin()
in USER-DPD's NBin class soon, so why not hoist it from NPair to NBin
where it seems to belong.

Details:
This also makes both forms of coord2bin() available in the NBin class.
The class NPair already had a pointer to the NBin instance (nb), so
just call the nb->coord2bin() method from any npair*.cpp file.
This commit updates npair* in USER-DPD and USER-OMP.  This commit
does NOT change USER-INTEL nor KOKKOS packages versions of npair.
The npair in the USER-INTEL package doesn't call coord2bin,
and npair in the KOKKOS package made the coord2bin methods inliner
functions, and had already made both variants of coord2bin
available to the NBin class.

### CODE REVIEW

**Comment by sjplimp** [comment]
Not so keen on this change.  It adds a level of indirection to the function
call inside the main neighbor build loop (i.e. it is called a lot).  If anything,
we should go the Kokkos route and make the coord2bin functions in-line
within NPair.

I don't mind a bit of code duplication, as those 2 methods are unlikely
to ever change.

**Comment by akohlmey** [comment]
@sjplimp FYI, for this kind situation, you should then unassign yourself and reassign the pull request to the submitter. i've just done that. this way, you won't see it in your TODO list unless it has been updated according to your wishes or additional arguments in favor of it provided, and then reassigned to you.

**Comment by akohlmey** [comment]
or if you categorically don't want to see it again, you can set the label `wontfix`, and click on `Close and comment` instead of `Comment`. The `wontfix` label would be the message to me (or the next GitHub wrangler) that you don't want to get this reassigned to you.

**Comment by timattox** [comment]
Thanks for the feedback.  I'll close this PR and later I'll revisit doing an inline version like Kokkos did for NPair.

**Pull request closed without merging**
