### PR TITLE
Meam spline multicomponent

### PR DESCRIPTION
**Pull request by DallasTrinkle**
This is the implementation of the multicomponent pair_meam_spline. It is compatible with the previous implementation (called "old style"), and includes a "new style" that can handle single or multicomponent MEAM splines. Documentation is updated to include the new version, and an example potential (TiO.meam.spline) is included.

### CODE REVIEW

**Comment by DallasTrinkle** [comment]
This version should be good to go; I had not tested the code with MPI. Found some parallel-only errors that are now fixed, and committed.

**Comment by akohlmey** [comment]
Thanks, but there is still work to do:
- there are inefficient constructs like `atom->x[i][0]` which require needless dereferences (and forced reloads, due to C/C++ pointer aliasing rules). they 
- the PR undoes some cleanups and coding style adjustments. more can be done, here is a summary:
  - no tabs
  - 2 spaces indentation per level
  - no trailing whitespace
  - system headers are included with `#include <header.h>`, not `#include "header.h"`
  - lines should be kept within 80 characters and wrapped, if needed
  - (internal) API names should not be whole sentences unless their use is strongly discouraged
- what about pair style `meam/spline/omp` which is derived from `meam/spline`?

**Comment by DallasTrinkle** [comment]
I believe I've addressed the issue; style cleanup, cleaned up the pointer derefencing similar to prior version of pair_meam_spline, added and tested version of OMP.

**Comment by akohlmey** [comment]
Nice work. I noticed a couple of issues with the potential file parser and fixed them. Also i added a 10-15% performance optimization, since the potential function lookup functions showed up in a quick profiling test.
I've pushed the changes to your branch, please check them out and see, if they broken anything.
I'll add a couple of minimal test inputs adapted from other existing input decks.
What is a little worrying is, that there seems to be some systematic discrepancy in energies between serial and MPI parallel runs (OpenMP seems to be fine). Quite possible, that those existed before (haven't had time to check). Also quite possible, that there is some side effect from recent neighbor list generation refactoring, that affects cases, where multiple neighbor list requests share binning or are constructed from the same master list. there are a couple of bugfixes for that in upstream, that may be worth checking out.

If you are happy with my changes and consider the code now good to go, let me know, then we'll merge it into master and check the parallel runs again. ... or i could merge in master and we can check directly.

just let me know.

thanks again for the help. this is how merging stuff into LAMMPS is fun. ;-)

**Comment by akohlmey** [comment]
yup, the original meam/spline implementation has the same inconsistencies with different number of MPI ranks. so this must be an issue unrelated to the multi-element support and thus i'll approve it for merging into the master branch and releasing it with the next patch.

**Comment by DallasTrinkle** [comment]
Thanks for your help with this; the changes look fine to me. I'm not sure what the issue is with MPI; I suspect it is an issue with the neighborlists. I've been doing relaxation tests, and I see no difference in the final energy with MPI vs. serial, but a different number of iterations to get to the minimum, and a small difference in lattice constant (10^-10 A) . I would like to get some more consistent testing of the energy derivatives using finite difference in MPI and serial to see if it's possible to nail down exactly where there's a problem.

Glad to see this will be available in the next release!

**Comment by akohlmey** [comment]
if you figure something out, please add a corresponding comment to issue #472.
often having somebody narrow down the cause without having a solution can be extremely helpful and simplify the process of implemented a bugfix.

**Pull request merged**
