### PR TITLE
Add python pair style for implementing simple pairwise additive potentials in python

### PR DESCRIPTION
**Pull request by akohlmey**
This PR implements a simple `python` pair style for simple pairwise additive potentials.
This works by using a a general framework in C++ that loops over all pairs similar to the lj/cut or morse pair styles and then calling python methods of a specific class in a provided python code to compute force and energy for each pair in python. 
Potential parameters must be stored in a symbolic way inside the python code and the pair_coeff statement works similar as for manybody potentials, providing the mapping of the numeric LAMMPS atom types to the symbolic atoms types inside the python code.
Furthermore, a `compute_force()` and `compute_energy()` function must be provided, that compute the force and energy of each pair, respectively and pass the result back to the C++ framework.

The python pair style also supports `Pair::single()`, so that one can use LAMMPS to conveniently build and use tabulated potentials and speed up the simulation with custom defined potentials massively.

### CODE REVIEW

**Comment by akohlmey** [comment]
@rbberger this is a minimal implementation of what i had in mind. About 20x slower. There should be some room for improvement, e.g. to turn the potential map into a flat list.

I'm leaving the branch open, so you can push into it as well. You can see from the example inputs, it is compatible with restarts, data files and hybrid pair styles.

**Comment by akohlmey** [comment]
@rbberger i am now leaning 99.9% towards your view about embedding python script in the executable.
For as long as the required chunk of redundant code is small as it currently is, we can just put it in each python file, simply quote it in the documentation, and say that all python potential files have to start with this. Same effect and we can more easily make file compatible to older versions of LAMMPS, in case the python base class API gets changed.

**Comment by akohlmey** [comment]
@rbberger I think with the documentation completed and a README file added to the example folder, this will be good enough for a first public release.

**Comment by rbberger** [comment]
@akohlmey looking good to me, assigning to Steve to maybe get into his merge window

**Comment by charlessievers** [comment]
@akohlmey and @rbberger I know I am late to the party, but this is super interesting. I just figured out what this package does and you both are way ahead of your time.

**Pull request merged**
