### PR TITLE
Colvars update 2017-03-10

### PR DESCRIPTION
**Pull request by giacomofiorin**
This PR includes aggregated commits from the Colvars repository, including primarily small bugfixes.

### CODE REVIEW

**Comment by giacomofiorin** [comment]
Axel, it doesn't look like I can assign this PR to people.

**Comment by akohlmey** [comment]
@giacomofiorin yeah, i guess you need to be invited to the "developers" group for that. let me know, if you want me to do this.

also, there seems to be the updated users guide PDF missing.

**Comment by giacomofiorin** [comment]
@akohlmey Thanks for noticing the missing PDF, I included it now.

I'm OK with being added to the developers group, although at the moment I wouldn't use any privileges other than setting parameters in my own PRs, and just for this may not be worth the trouble.

Moreover, I think that somebody who hasn't contributed before may want (and should be encouraged) to assign as reviewers the authors of the code that he/she is modifying, if applicable.

**Comment by akohlmey** [comment]
assignee != reviewer. can you try setting me as reviewer? we use the assignee designation to name who is responsible to merge or decide if it can be merged. so there can only be one assignee. for reviewing code, the reviewer designation should be used, that can can be multiple.

**Comment by giacomofiorin** [comment]
I can't set either the reviewers or the "assignee".  Sorry for the ambiguity, my point was that I see much more value in setting the reviewers as unprivileged user than in setting the assignee.

**Comment by akohlmey** [comment]
i agree. the reviewer option is fairly new, so it may be updated. i think for now we are good. if you want an invite as developer, let me know.

**Comment by giacomofiorin** [comment]
@akohlmey Can you invite me to the developers group?  It looks like there would be some PRs and issues that I'd want to be able to tag. Thank you!

**Pull request merged**
