### PR TITLE
HIP-backend for the GPU package

### PR DESCRIPTION
**Pull request by vvsteg**
**Summary**

This PR enhances LAMMPS with the capability for using the new HIP C++ runtime API for GPU-offloading of MD calculations as implemented in the GPU package that has been developed with support of CUDA and OpenCL backends using the unification layer of the _geryon_ library. This PR adds a new HIP-backend to this library. HIP is a part of the AMD ROCm open source GPU framework. This new HIP-backend can be used either with the hcc compiler for AMD GPUs, or with the nvcc compiler for Nvidia GPUs.

**Related Issues**

This PR is related to the issue #1368 and opens a new way of running LAMMPS on AMD GPUs that support ROCm without fixing the current version of the GPU package OpenCL-backend that is not fully compatible with the OpenCL 2.0 standard required for ROCm. The issue #1368 could be probably closed after merging.

**Author(s)**

Evgeny Kuznetsov (eokuznetsov@edu.hse.ru) and Vladimir Stegailov (v.stegailov@hse.ru, stegailov@gmail.com), International Laboratory for Supercomputer Atomistic Modelling and Multi-scale Analysis, Higher School of Economics, Moscow

**Licensing**

By submitting this pull request, we agree, that our contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

This PR should not break backward compatibility.

**Implementation Notes**

For porting to HIP framework, we use the CUDA-backend of the GPU acceleration capability of LAMMPS developed by Mike Brown et al. This acceleration library is based on the _geryon_ library that serves as a unification layer for CUDA and OpenCL backends.

A ROCm _hipify_ tool provides a fast method to translate CUDA runtime and driver API calls and types to their HIP analogs. Not all CUDA functions have corresponding HIP wrappers and those that have, sometimes are not fully implemented. In particular, this applies to CUDA driver API calls used in the _geryon_ library. Despite that _hipify_, empowered by the Clang C++ parser, allows translating the most part of CUDA code in a mistake-free manner.

Due to existing architecture differences, it has been essential to revise GPU kernels. This applies especially to inline assembly and warp operations. AMD and Nvidia GPUs have different warp sizes, 64 and 32 respectively, so it has been necessary to make sure all warp vote and shuffle functions, `__ballot` for example, use appropriate integer types and there are no "magic" constants like 32, 31, 5 and so on. `Printf` and `assert` calls from GPU kernels are still under development in ROCm, and it is worth noting that in the ROCm version 2.2 an assert call causes kernel execution abort regardless of the condition.

Another pitfall is using texture references and objects. In the ROCm version 2.2, AMD HSA imposes hard limits on texture dimensions (up to 4096 elements for 1D texture, for example), that makes them useless in practice. Moreover, textures are declared in kernel modules as external symbols, and they should be defined in the host scope. So, it becomes impossible to load and use binary kernel modules with texture declarations. A possible workaround to avoid significant code fixes, in this case, is to use device global pointer variables as pseudo-textures. Device pointers binding to texture references or objects turn into global variables assignments, and, like textures, global variables can be extracted by their names.

GPU sorting requires to install _hipcub_ (https://github.com/ROCmSoftwarePlatform/hipCUB). The HIP CUDA-backend additionally requires _cub_ (https://nvlabs.github.io/cub/).

Linking the MPI code with the `hipcc` compiler requires getting the corresponding linking options from a standard MPI-wrapper of the MPI stack deployed (e.g. OpenMPI or MPICH). These options should be included into the makefiles for `libgpu.a` and for `lmp_hip` binaries.

This PR has been tested using ROCm 2.2-2.6 and different standard LAMMPS input examples on Radeon RX 480 (gfx803), Radeon RX Vega (gfx900), Radeon VII (gfx906) and Titan V (sm_70) with OpenMPI and MPICH.

The PR code has been merged with the pull #1430.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [x] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

The following text is proposed for addition to lib/gpu/README

BUILDING FOR HIP FRAMEWORK

1. Install the latest ROCm framework (https://github.com/RadeonOpenCompute/ROCm).

2. GPU sorting requires installing hipcub (https://github.com/ROCmSoftwarePlatform/hipCUB). The HIP CUDA-backend additionally requires cub (https://nvlabs.github.io/cub). Download and extract the cub directory to lammps/lib/gpu/ or specify an appropriate path in lammps/lib/gpu/Makefile.hip.

3. In Makefile.hip it is possible to specify the target platform via export HIP_PLATFORM=hcc or HIP_PLATFORM=nvcc as well as the target architecture(s) (gfx803, gfx900, gfx906 etc.)

4. If your MPI implementation does not support mpicxx --showme command, it is required to specify the corresponding MPI compiler and linker flags in lammps/lib/gpu/Makefile.hip and in lammps/src/MAKE/OPTIONS/Makefile.hip.

5. Building the GPU library (libgpu.a): cd lammps/lib/gpu; make -f Makefile.hip -j8

6. Building the LAMMPS executable (lmp_hip): cd ../../src; make hip -j8

### CODE REVIEW

**Comment by akohlmey** [comment]
@vvsteg just discussed the status of this PR with @sjplimp while planning for the next two stable releases. We decided to take a closer look at this after the next stable release which is scheduled to happen in about a month. You may want to first update to the latest changes after that stable release or even submit a clean, new pull request. We will also have to work out something by that time where at least one of the LAMMPS core developers does have the hardware to compile and run/test this.

**Comment by vvsteg** [comment]
@akohlmey thank you for the notice. It makes sense since we have not yet tested this HIP-backend with the recent ROCm 3.0 that seems to have introduced some changes to the HIP compiler.

At the same time, I have been told by people from AMD that they have tested this HIP-backend successfully.

**Comment by sjplimp** [comment]
@vvstep Also, we have a conf call later this week AMD folks looking at LAMMPS.  So we plan to tell them about your work and see if we can connect them with you.

**Comment by sjplimp** [comment]
@vvsteg See my previous comment about AMD folks, I mistyped your username ...

**Comment by vvsteg** [comment]
@sjplimp The current problem with HIP-backend on AMD GPUs is the strange behaviour of the ROCm driver when one runs LAMMPS with more than 4 MPI processes per GPU. In these cases LAMMPS runs very slowly or hangs. As far as I know, this issue has not been resolved yet (please see https://github.com/RadeonOpenCompute/ROCm/issues/851).

**Comment by sjplimp** [comment]
@vvsteg We talked with the AMD folks this AM.  Sounds like they are already working with you on this PR, which is great.  We suggested that (a) you/they just test this on the bench dir scripts for a few problem sizes.  Then (b) we need to figure out how the user builds LAMMPS with either Cuda or HIP support for the GPU package backend.  Similar to what a KOKKOS package build requires for Cuda vs OpenMP.  That part, @stanmoore1 probably needs to test on our AMD testbed.  Maybe you have ideas on how to best do that.  Then (c) we can release.  I don't think performance or all other Cuda vs HIP issues need to be worked out now.  Those can be updated in future PRs
as the AMD hardware and software evolves.

**Comment by vvsteg** [comment]
@sjplimp I am sorry for a delayed feedback. Last week we have talked with the AMD folks as well. They showed some performance data for the standard scripts obtained with MI50. We have been granted access to a test platform with MI50 running under ROCm 3.0. And I can confirm that LAMMPS can be built without issues with OpenMPI using lib/gpu/Makefile.hip from this PR. The problems with running more than 4 MPI ranks per GPU have not been detected.

There have been some problems with building `libgpu.a` from HIP with `nvcc` (mentioned here https://github.com/RadeonOpenCompute/ROCm/issues/851). But this is not a critical issue since there is a separate CUDA-backend for Nvidia GPUs.

The HIP port of this PR is a bit old now. @Vsevak plans to merge it with the current master branch in a couple of days.

What other issues remain to be considered before the release?

**Comment by sjplimp** [comment]
@vvsteg @stsamoor Hi Vladimir - I defer to Stan Moore on this, whether he wants to do additional testing, either for building or running on AMD hardware he has access to.  If Stan and Trung approve the PR, I think it should be fine to merge.   There does need to be some additional documentation on how to use this on the Section 7.4 and 7.4.1 doc pages.

**Comment by sjplimp** [comment]
@stamoor Please see my previous comment to Vladimir.

**Comment by sjplimp** [comment]
@stanmoore1 Grrr - two mistypings.  Stan see my comment to @vvsteg above

**Comment by akohlmey** [comment]
This also needs support for building with CMake.

As already mentioned, given the nature of the changes and the number of files touched by it, I would prefer merging it *after* the upcoming stable release. At that point we will have completed the transition to .rst files for documentation, require C++11 for building LAMMPS and set the minimum requirement for CMake for version 3.10 instead of 2.8.12. This should simplify the process of integrating it into CMake and making the code usable and also give it sufficient time for feedback from users with AMD hardware to make all the little tweaks and adjustments that are always needed when adding a new back end to a large package.

**Comment by stanmoore1** [comment]
One main design issue is: do we want to have a single GPU package as is currently in this PR or separate out HIP vs CUDA?

**Comment by akohlmey** [comment]
> One main design issue is: do we want to have a single GPU package as is currently in this PR or separate out HIP vs CUDA?

There are already two(!) back ends (CUDA and OpenCL) in the GPU package and my understanding and reading of the code is, that this will add a third back end. So the decision between CUDA, OpenCL, and HIP is a compile time decision for compiling the library in lib/gpu and the GPU package as such would be unaffected.

**Comment by ndtrung81** [comment]
I support the merge of this PR because it's a pretty useful contribution to the GPU package.. As it ensures backward compability, I would keep it in the GPU package as is.

I don't have access to hardware to test it myself, so if @stanmoore1 sees the PR pass all the tests, I have no problem approving it right away.

**Comment by akohlmey** [comment]
superseded by #1863

**Pull request closed without merging**
