### PR TITLE
add NWChem wrapper to client/server mode for AIMD

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

Add a Python wrapper on the NWChem quantum chemistry code so it can be used in client/server mode with LAMMPS.  Simliar to VASP.  Two example scripts are provided.

**Related Issues**

N/A

**Author(s)**

Jeff Boschen (Iowa State U), submitted by Steve.

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted. Delete lines that don't apply_

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by sjplimp** [comment]
This still requires a couple iterations between @sjplimp and Jeff.

**Comment by jboschen** [comment]
Just pinging so my username is here.

**Comment by sjplimp** [comment]
@akohlmey @jboschen Jeff doesn't seem to have permission to push into this PR.  Is that something
you enable, or me?

**Comment by akohlmey** [comment]
> @akohlmey @jboschen Jeff doesn't seem to have permission to push into this PR. Is that something
> you enable, or me?

neither. you created a branch inside the LAMMPS repository. those are writable only by core developers and we don't want to change that.

pushing in other people's github branches only works for project developers into branches of submitted pull requests (unless the submitter disables that setting, which is enabled by default).

for branches inside the repo you can only do things the old fashioned way: @jboschen would have to submit a pull request for that particular branch and @sjplimp can then merge it (unlike 'master" this branch is not protected). or you have to reverse the roles and @jboschen would submit a new pull request to master, and @sjplimp can then push into it (if allowed).

**Pull request closed without merging**
