### PR TITLE
New generalized granular pair style

### PR DESCRIPTION
**Pull request by dsbolin**
This is a new granular pair style that expands options for granular contact models

This includes options for cohesion, rolling and twisting friction, and assignment of different coefficients to different atom types via pair_coeff command (new compared to existing pair gran/* styles).
**Author(s)**
Dan S. Bolintineanu, Ishan Srivastava, Jeremy B. Lechman

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under the GNU General Public License version 2.

_Please complete the following statement by adding "yes" or "no":_
My contribution may be re-licensed as LGPL (for use of LAMMPS as a library linked to proprietary software):

yes

**Backward Compatibility**

_Please state whether any changes in the pull request break backward compatibility for inputs, and - if yes - explain what has been changed and why_

N/A

**Implementation Notes**

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

Should not affect any other features in lammps

**Post Submission Checklist**

_Please check the fields below as they are completed **after** the pull request has been submitted_

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by akohlmey** [comment]
@dsbolin I think with my added changes, this is ready to be included. I've decided to remove the USER-OMP version of `fix wall/gran` rather than porting it to the updated code.
It would be nice if there were a few small/fast examples for this addition included, if only as a reference for testing future modifications. Those examples could be provided in a separate pull request.

**Comment by dsbolin** [comment]
@akohlmey Thanks for looking at this. I will add a few examples in a new pull request in the near future.

**Comment by sjplimp** [comment]
@akohlmey @dsbolin Looked thru the files, made only reformatting changes.  So everything
should still work, though @dsbolin it wouldn't hurt to re-run your examples.  3 Qs
1) @akohlmey do you want some of the constants at the top of pair_granular.cpp
to be refs to math_const.h
2) These pair styles do not invoke ev_init(), including the new pair_granulat.cpp, like the recent change.  Not sure if that will get merged for the other modified pair styles.
3) I'm unclear on why the variable nondefault_history_transfer appears in both pair_granular.h and pair_gran_hooke_history.h.  I think it should only be in the latter?
Otherwise good to go so far as I see.  Great work Dan!

**Comment by sjplimp** [comment]
@dsbolin Just realized there are no example scripts included.  Do you think
some should be added to the examples dir?  There is a pour sub-dir now.
It could be renamed to gran or granular, and new files with additional pair granular
options enabled could be added?  Note there is a granregion as well with your
examples.  A script with the new options could be added there also.

**Comment by akohlmey** [comment]
> @dsbolin Just realized there are no example scripts included. Do you think
> some should be added to the examples dir? There is a pour sub-dir now.
> It could be renamed to gran or granular, and new files with additional pair granular
> options enabled could be added? Note there is a granregion as well with your
> examples. A script with the new options could be added there also.

this was discussed already. a second pull request with examples is in preparation.

**Comment by akohlmey** [comment]
> @akohlmey @dsbolin Looked thru the files, made only reformatting changes. So everything
> should still work, though @dsbolin it wouldn't hurt to re-run your examples. 3 Qs
> 
> 1. @akohlmey do you want some of the constants at the top of pair_granular.cpp
>    to be refs to math_const.h

working on it now.

> 2. These pair styles do not invoke ev_init(), including the new pair_granulat.cpp, like the recent change.  Not sure if that will get merged for the other modified pair styles.

the pull request predates that change, so they will not show up here. however, pair granular needs to be updated and i am doing this right now.

> 3. I'm unclear on why the variable nondefault_history_transfer appears in both pair_granular.h and pair_gran_hooke_history.h.  I think it should only be in the latter?

i don't see it in pair_granular.h but in pair.h. it should be only in pair.h then, and also initialized there to avoid uninitialized access and thus random crashes. i see another possible uninitialized data (which may have gone unnoticed, since on linux data is initialized for the first time typically to 0 due to how its malloc() implementation works).

will make those changes and some more cosmetic cleanup.

>    Otherwise good to go so far as I see.  Great work Dan!

**Comment by akohlmey** [comment]
@sjplimp this PR should now be ready to be merged

**Pull request merged**
