### PR TITLE
User H-AdResS

### PR DESCRIPTION
**Pull request by hadress**
Branch featuring the Hamiltonian adaptive resolution simulation (H-AdResS) method. The new feature enables the simulation of a liquid composed by molecules whose resolution (atomistic or coarse-grained) depends on their location in space.

### CODE REVIEW

**Comment by junghans** [comment]
Please enable the build of USER-HADRESS in `.travis.yml`:
<https://github.com/MaziarHeidari/lammps/blob/USER-HADRESS/.travis.yml#L51>

**Comment by akohlmey** [comment]
Build will be included automatically, if the main makefile is updated. this is not the only issue with this PR. most are easy to fix and i can do them quickly myself, but i am certain some additional changes to the actual package code need to be made before the PR can be merged, e.g. some style name will need to be changed... More on this later, after i had some time to do a proper code review.

**Comment by akohlmey** [comment]
This package needs additional work before it can be merged. In particular:
- it needs to be correctly integrated into the standard make yes-package, make no-package system
- it needs to be updated with respect to the current version of LAMMPS, e.g. the modified atom.h is not compatible with what is currently used. also addition of the new per-atom fields need to follow the best practice of other (user) packages.
- the style names should be made consistent with the existing conventions (e.g. all lowercase for user visible styles), i would suggest: full/hars for the atom style and lj/cut/coul/hars/aa and lj/cut/hars/cg
- documentation should be moved to doc/src (.txt files only, the PR should not include .html files. they will be recreated anyway), examples to examples/USER/haddress
- example files must be small and must not contain non-portable binary restart files. only data files may be included. data files should ideally be under 2MB

**Comment by akohlmey** [comment]
Any comments or updates on this?

**Comment by raffopote** [comment]
Axel, thank you for your comments. We are currently working on implementing the modifications and will push the updated version soon. RP

**Comment by junghans** [comment]
Just FYI, you don't need to open a new pull request, you can simply push more commits to the same branch (in your case `USER-HADRESS`) and they will go into the same pull request.

**Comment by raffopote** [comment]
Dear Christoph,

Thanks a lot for the clarification!

Best,

R.


On Mon, Jun 20, 2016 at 6:25 PM, Christoph Junghans <
notifications@github.com> wrote:

> Just FYI, you don't need to open a new pull request, you can simply push
> more commits to the same branch (in your case USER-HADRESS) and they will
> go into the same pull request.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lammps/lammps/pull/79#issuecomment-227193691>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AS5X_5PVtBdLuSPoMBA9h3xtmJCSzTCRks5qNr72gaJpZM4IwGPU>
> .
>



-- 
"What power would Hell have if those imprisoned there were not able to
dream of Heaven?"

Sandman (Neil Gaiman)

**Pull request closed without merging**
