### PR TITLE
Collected small changes and fixes

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request collects multiple small changes and bugfixes

**Related Issue(s)**

Fixes 32-bit integer overflow issue reported in #3743 (but not the other issues)

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

The following individual changes are included:
- avoid 32-bit integer overflow when allocating neighbor list buffers in the INTEL package
- plug memory leak in FixNHIntel class in INTEL package
- avoid segfault in atom style edpd due to missing pointer initialization
- declare "sphere" and "cuboid" options in fix edpd/source and fix tdpd/source as deprecating pending future removal
- fix spelling and grammar issues in documentation
- modernize internal fix NEIGHBOR/HISTORY, use ubuf() to properly encode tagint data into communication buffer
- refactor granular submodel implementation to closer follow current coding conventions
- improve error messages for styles derived from the FixNH class
- simplify web browser compatibility explanation and provide a list of successfully tested web browser versions

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Review by sjplimp — APPROVED** [review]

**Comment by jtclemm** [comment]
Thank you for cleaning up all of the granular files. The only issue that comes to mind is that similar changes should be made to the documentation example. I can make those edits in just a minute.

**Review by jtclemm — APPROVED** [review]

**Comment by akohlmey** [comment]
> Thank you for cleaning up all of the granular files.

It is less of a cleaning up, more an alignment with the coding convention and particularly the consistent use of virtual and override keywords according to C++11 and later conventions.

@jtclemm If you have some time for that, we should probably stick our heads together and improve/extend the section in the manual on programming style and conventions: https://docs.lammps.org/Modify_style.html

You are in the unique position of having done some fairly intrusive work on LAMMPS and thus having a decent sense for how everything is pieced together, yet you are new enough to modifying LAMMPS core files so you are not tainted by "this how we always did it". For me, it is quite difficult to judge what needs to be mentioned, what needs to be explained and what is obvious. In some ways I have learned to trust my instincts for figuring out a compromise between what the latest styles and discussions suggest and what is practical and makes sense within the context of a code full of legacy components and compromises and the need to remain very portable. Some of the choices are just arbitrary (especially, when there is no performance or readability impact) and only made for consistency, yet over what *is* consistent there is not always 100% agreement.

Thus the more we can formulate "do this" or "don't do this" cases and motivate them, the easier we make it for people contributing to LAMMPS to write their contribution in a compatible style and thus make it easier to integrate them. And making it easier to integrate, yet keep the code consistent and maintainable is what this is (mostly) about.

**Comment by jtclemm** [comment]
> stick our heads together and improve/extend the section in the manual on programming style and conventions: https://docs.lammps.org/Modify_style.html

Sure, I'd be happy to brainstorm and should have time these next few weeks. I'll take a look at the page and jot down some notes.

**Comment by akohlmey** [comment]
> Sure, I'd be happy to brainstorm and should have time these next few weeks. I'll take a look at the page and jot down some notes.

Thanks. Please send me a note directly via email or slack when you feel up to it and I'll set up a Zoom session.
If there is anybody that wants to join this discussion, just drop me a note and I'll notify you.

**Comment by jtclemm** [comment]
> > Sure, I'd be happy to brainstorm and should have time these next few weeks. I'll take a look at the page and jot down some notes.
> 
> Thanks. Please send me a note directly via email or slack when you feel up to it and I'll set up a Zoom session. If there is anybody that wants to join this discussion, just drop me a note and I'll notify you.

Will do. I read through the modify style/contributions pages and have a few ideas for discussion. I also spotted a few minor typos/unclear phrasings I just pushed to this branch.

**Pull request merged**
