### PR TITLE
Add user manifold

### PR DESCRIPTION
**Pull request by Pakketeretet2**
Ok, here is a pull request from a feature branch to add the USER-MANIFOLD package.

### CODE REVIEW

**Comment by akohlmey** [comment]
Ok, so far. To make it a "real" user package, it needs to be integrated into the master makefile. the change below does that.
```
diff --git a/src/Makefile b/src/Makefile
index bd1b432..664c856 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -48,7 +48,7 @@ PACKAGE = asphere body class2 colloid compress coreshell dipole fld gpu \
 
 PACKUSER = user-atc user-awpmd user-cg-cmm user-colvars user-cuda \
           user-diffraction user-dpd user-drude user-eff user-fep user-h5md \
-          user-intel user-lb user-mgpt \
+          user-intel user-lb user-manifold user-mgpt \
           user-misc user-molfile user-omp user-phonon user-qmmm user-qtb \
           user-quip user-reaxc user-smd user-smtbq user-sph user-tally \
           user-vtk
```
However, the build after "make yes-user-manifold" fails with the following message:
```
In file included from ../fix_manifoldforce.cpp:25:0:
../manifold_factory.h:55:32: fatal error: manifold_spine_opt.h: No such file or directory
compilation terminated.
Makefile:110: recipe for target 'fix_manifoldforce.o' failed
make[1]: *** [fix_manifoldforce.o] Error 1
```

Next, multiple inheritance is often messy and not really needed. why not make your manifold base class derived from Pointers and pass in the LAMMPS pointer there already.

Also, we need to keep our namespaces and header files clean. The file manifold_factory.h includes <string> and <map> without using them immediately. such headers should be included in the implementation only, if at all possible. Same goes for the str_eql() function, which is added to the global namespace, but doesn't seem to be used. If such convenience functions are included, they should be part of a dedicated namespace or a class and it would be even better to make them static functions in the corresponding implementation files.

Similar things go for the sincos_lookup class. This class should be in its own namespace, but at the very least in the LAMMPS_NS namespace. The constants should not be in the header, as they are not needed there or anywhere outside the implementation. The MathConst namespace provides those and similar constants within LAMMPS. Furthermore, it appears that that specific class is not used anywhere, so it could be removed.

that are just a few things from a quick check. please try to update the pull request.

**Comment by Pakketeretet2** [comment]
I cleaned up a lot of stuff. The fixes are now in LAMMPS_NS, everything else is in LAMMPS_NS::user_manifold. I had some dangling includes left that were not in the repo but still in my working directory, so it compiled on my machine fine, sorry about that. These are now all removed. Multiple inheritence is gone, manifold now inherits Pointers.

**Comment by akohlmey** [comment]
still fails to compile for me. now it fails at the link stage with
```
fix_manifoldforce.o: In function `LAMMPS_NS::FixManifoldForce::FixManifoldForce(LAMMPS_NS::LAMMPS*, int, char**)':
/home/akohlmey/compile/lammps-icms/src/Obj_mpi/../fix_manifoldforce.cpp:67: undefined reference to `LAMMPS_NS::user_manifold::create_manifold(char const*, LAMMPS_NS::LAMMPS*, int, char**)'
fix_nve_manifold_rattle.o: In function `LAMMPS_NS::FixNVEManifoldRattle::FixNVEManifoldRattle(LAMMPS_NS::LAMMPS*, int&, char**, int)':
/home/akohlmey/compile/lammps-icms/src/Obj_mpi/../fix_nve_manifold_rattle.cpp:99: undefined reference to `LAMMPS_NS::user_manifold::create_manifold(char const*, LAMMPS_NS::LAMMPS*, int, char**)'
collect2: error: ld returned 1 exit status
Makefile:89: recipe for target '../lmp_mpi' failed
make[1]: *** [../lmp_mpi] Error 1
make[1]: Leaving directory '/home/akohlmey/compile/lammps-icms/src/Obj_mpi'
```

**Comment by Pakketeretet2** [comment]
I think I know why, I moved create_manifold to a separate cpp-file but forgot to add it, sorry...

**Comment by akohlmey** [comment]
I've done some more refactoring, dead code removal and cleanups. Please update your add-user-manifold branch with the following command and test it (you could call this a 'manual pull request').
```
git pull https://github.com/akohlmey/lammps.git merge-pull-35
```
This should be pretty close to what can be sent to steve. i still need to check the documentation, though, and add some references at the right places. most of that kind of integration, however, is usually done by steve anyway.

**Comment by Pakketeretet2** [comment]
Hi, this version seems to work fine. All examples run and give sensible results.

**Pull request merged**
