### PR TITLE
Humbird-Graves Tersoff-style potential

### PR DESCRIPTION
**Pull request by dhumbird**
**Summary**

This code implements the Tersoff-style potential for Si-F and Si-Cl presented by Humbird and Graves (J Chem Phys 2004). The substantial changes were made in 2018 and are work in progress. Last merged with upstream in June 2021.

**Related Issue(s)**

**Author(s)**

David Humbird, DWH Process Consulting, Centennial Colorado
dhumbird@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

The potential was originally verified against the Humbird publications and homebrew code.
This version also implements the generation and storage of a bicubic interpolation table from a file containing a small number of node points.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@dhumbird thanks for your submission. I had to switch the base because we renamed the development branch from "master" to "develop" some time ago.

How detailed and specific of a review do you want us to do on the pull request now since it is still marked as *draft*?

**Comment by dhumbird** [comment]
Hi Axel, I am corresponding with Steve on a separate thread. Joey Vella
from PPPL had requested him to look at this code that I hacked together
several years ago. Steve recommended I make a pull request and label it as
a work in progress for now. I will copy you on another email I am writing
now.

**Comment by stanmoore1** [comment]
@dhumbird do you have an update on the status of this PR? It has been sitting idle for a while.

**Comment by dhumbird** [comment]
This was something I wrote years ago, in my own fork. I made the merge request at the request of a researcher at PPPL with the understanding that he would fix it up for production. Obv that never happened, and he's no longer with the lab. We can close this.

**Pull request closed without merging**
