### PR TITLE
Update Kokkos library to v3.0

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

Update Kokkos library to v3.0 and remove deprecated code.

**Author(s)**

Stan Moore (SNL)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues.

### CODE REVIEW

**Comment by junghans** [comment]
This will also help with https://github.com/lammps/lammps/pull/1688#issuecomment-539051842

**Comment by stanmoore1** [comment]
This now compiles fine with Makefiles but needs help with CMake. I'm running it through Kokkos regression testing now.

**Comment by junghans** [comment]
Are there any modifications in our kokkos sources in comparison to the 2.9.99 tarball?

**Comment by stanmoore1** [comment]
@junghans the only difference is in `Makefile.kokkos`. See: https://github.com/kokkos/kokkos/compare/master...stanmoore1:lammps

**Comment by junghans** [comment]
Hmm, as this is a +/-100k lines change PR and only the makefile being different maybe we should use the normal install.py mechanism to get the source instead of bundling it with lammps.

**Comment by stanmoore1** [comment]
I'd be open to that but want to ask @sjplimp what he thinks. For stability we would need to point to the master version of Kokkos, not develop.

**Comment by akohlmey** [comment]
The CMake breakage is because Kokkos now enforces that defines are named `Kokkos_ENABLE_SOMETHING` instead of `KOKKOS_ENABLE_SOMETHING`. and there are additional warnings, that `-D Kokkos_ARCH=ARCH1,ARCH2` would have to become `-D Kokkos_ARCH_ARCH1=yes -D Kokkos_ARCH_ARCH2=yes`.

This is most certainly **not** something we want to merge **before** the stable release in a couple weeks or so.

**Comment by stanmoore1** [comment]
@akohlmey yeah that is what I expected.

**Comment by akohlmey** [comment]
> @akohlmey yeah that is what I expected.

...and of course the new settings and requirements would have to be documented in the manual.

**Comment by stanmoore1** [comment]
>...and of course the new settings and requirements would have to be documented in the manual.

I started on that, see 6d9900fe7f53ab3b013ffbfade6ee1247d2fe092

**Comment by akohlmey** [comment]
> > ...and of course the new settings and requirements would have to be documented in the manual.
> 
> I started on that, see [6d9900f](https://github.com/lammps/lammps/commit/6d9900fe7f53ab3b013ffbfade6ee1247d2fe092)

great!

this reminds me of another issue to consider. does this already include the "cmake rewrite" for Kokkos?
or would that be another change set?
If at all possible, I would prefer to arrange things in such a way, that we have to change how LAMMPS users access setting KOKKOS features only once.
This all looks like it will be best, that we leave KOKKOS support in the LAMMPS master branch untouched until we meet the next time in person. If need be, we could have temporarily an officially maintained kokkos feature branch in the github repository for the time being.

**Comment by stanmoore1** [comment]
Yes this PR includes all of the Kokkos CMake rewrite changes

**Comment by stanmoore1** [comment]
I had to take a patch from Kokkos develop to get UVM to compile with LAMMPS, see https://github.com/kokkos/kokkos/issues/2826. I want to follow the Kokkos master branch with LAMMPS, is there a way to install patches with `Install.py`?

**Comment by akohlmey** [comment]
> I had to take a patch from Kokkos develop to get UVM to compile with LAMMPS, see [kokkos/kokkos#2826](https://github.com/kokkos/kokkos/issues/2826). I want to follow the Kokkos master branch with LAMMPS, is there a way to install patches with `Install.py`?

`Install.py` is a python script, so you can do anything that you can script in python. We would have to figure out how to do the same in CMake. @junghans do you have any suggestions on that?

The question is: wouldn't it be easier to just apply the patch to the LAMMPS tree and then wait with the next Kokkos update until after the patch in question is merged there? We are already diverged with the recently contributed spellchecker changes, which are now causing lots of merge conflicts with this PR, too.

**Comment by stanmoore1** [comment]
>We are already diverged with the recently contributed spellchecker changes, which are now causing lots of merge conflicts with this PR, too.

I fixed the merge conflicts. 

>wouldn't it be easier to just apply the patch to the LAMMPS tree and then wait with the next Kokkos update until after the patch in question is merged there

Yes that is a good idea, I've done that in this PR.

@akohlmey @junghans What do we need to do to get this moving wrt CMake?

**Comment by akohlmey** [comment]
> @akohlmey @junghans What do we need to do to get this moving wrt CMake?

I would like to merge this for the next patch. @junghans is working on updating CMake support in LAMMPS, but since we want to be able to import the KOKKOS library as an external library, we basically have to make CMake support in LAMMPS adapt to it.

That means, this PR needs to be merged first and then into @junghans ' branch.

Before that, we need to discuss with @sjplimp how we handle configuration (since the current one will be refused by the updated KOKKOS cmake files) and specifically how we keep settings as similar as possible between conventional make and CMake. We should probably also construct some presets that are equivalent to the profiled Makefiles in the source tree.
I have already proposed to @sjplimp to have a conference call with @athomps, @rbberger, and you to go over a few items including this one.

**Comment by junghans** [comment]
> > I had to take a patch from Kokkos develop to get UVM to compile with LAMMPS, see [kokkos/kokkos#2826](https://github.com/kokkos/kokkos/issues/2826). I want to follow the Kokkos master branch with LAMMPS, is there a way to install patches with `Install.py`?
> 
> `Install.py` is a python script, so you can do anything that you can script in python. We would have to figure out how to do the same in CMake. @junghans do you have any suggestions on that?
Not sure why we need to patch anything, lammps brings its own kokkos source, so make it part of that. If somebody uses an external `kokkos` that is a different issue, but then they are on their own anyhow.

**Comment by stanmoore1** [comment]
@akohlmey that sounds good. I'm working on getting the Kokkos regression test suite to pass.

>Not sure why we need to patch anything, lammps brings its own kokkos source

@junghans We were considering your suggestion of deleting the copy of Kokkos out of LAMMPS and using `Install.py` instead

**Comment by junghans** [comment]
Ah, got it! CMake's external project has support for patches! Let me draft a CMake change for that!

**Comment by junghans** [comment]
@stanmoore1: I think I got the wrong patch, can you have a look?

**Comment by stanmoore1** [comment]
The Kokkos OpenMP regression tests are now passing. I'm getting a link error when building for Kokkos CUDA though.

**Comment by stanmoore1** [comment]
Nearly all the Kokkos CUDA regression tests are passing now. I compared performance on V100 GPU for LJ, EAM, and SNAP and there is no slowdown with Kokkos 3.0.

**Comment by akohlmey** [comment]
@stanmoore1 I would like to merge this today or tomorrow. then I can work on updating the CMake related documentation and we can adjust the integration tests. we can then merge whatever other KOKKOS related PRs are ready and then have 2-3 weeks to work on fixing things for the next patch.

**Comment by junghans** [comment]
@stanmoore1 do have a branch with all kokkos changes on it? So I can pull a patch vs. kokkos-3.0.00 and work on the cmake part.

**Comment by stanmoore1** [comment]
@akohlmey there are still a couple CUDA regression tests failing (but most are passing). I'm working on this today. Should we merge this now or wait until the tests pass?

**Comment by akohlmey** [comment]
> @akohlmey there are still a couple CUDA regression tests failing (but most are passing). I'm working on this today. Should we merge this now or wait until the tests pass?

Your call. Either way will work. I am expecting at least two weeks until the next patch release, possibly more, if we get some other "disruptive" changes merged, so there will be some time needed to sort out issues. The benefit of merging sooner would be, that we can also merge the cmake refactor sooner that @junghans is working on and then we save having to do any tweaks for the new KOKKOS Cmake requirements twice.

**Comment by junghans** [comment]
> > @akohlmey there are still a couple CUDA regression tests failing (but most are passing). I'm working on this today. Should we merge this now or wait until the tests pass?
> 
> Your call. Either way will work. I am expecting at least two weeks until the next patch release, possibly more, if we get some other "disruptive" changes merged, so there will be some time needed to sort out issues. The benefit of merging sooner would be, that we can also merge the cmake refactor sooner that @junghans is working on and then we save having to do any tweaks for the new KOKKOS Cmake requirements twice.

I am happy either way, there will be a conflict in `KOKKOS.cmake`, but it is going to be an easy one.

Are we still planning to ditch the bundled kokkos sources? And are we doing it in the PR?

**Comment by akohlmey** [comment]
> Are we still planning to ditch the bundled kokkos sources? And are we doing it in the PR?

not for the next patch release. this feels like one change too many to keep track of and sort out. this one is going to be disruptive as it is. so I suggest that we look into unbundling the KOKKOS library some time **after** the next patch release, i.e. in about a month or so.

**Comment by stanmoore1** [comment]
Yes I agree with @akohlmey

**Comment by junghans** [comment]
> Yes I agree with @akohlmey

Ok, I will work on the CMake part now.

**Comment by stanmoore1** [comment]
>Your call. Either way will work.

OK let's merge this in, and I'll submit another pull request soon.

**Comment by junghans** [comment]
@akohlmey the CMake part is totally hosed now.

**Comment by junghans** [comment]
See #1968.

**Pull request merged**
