### PR TITLE
patch niche rcb issue

### PR DESCRIPTION
**Pull request by Adrian-Diaz**
**Summary**

Addresses an issue with rcb that only occurs when all contents (<=8 dots) lie on the vertices of a partition. In this case zero width boxes could be created.

**Author(s)**

Adrian Diaz (University of Florida)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Clear of Conflict

**Implementation Notes**

Checks for zero width boxes at the end and resets the partition to the initial half box guess. Given the marginal imbalance and impact of this specific case no further adjustment is implemented.

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp am currently bouncing all communication related PRs to you for initial review. There are too many pending changes that may or may not be related to your PR #1556 it would be nice if we could merge that one soon and the re-review everything communication related afterwards.

**Comment by sjplimp** [comment]
@Adrian-Diaz please try the new version.  If it fixes your corner case, it should be ready to merge.
This one is simpler and also resets dotmark[] which is necessary.  Thanks

**Comment by Adrian-Diaz** [comment]
@sjplimp yea it works fine; thanks for the fix.

**Comment by akohlmey** [comment]
@sjplimp this looks ready, so please approve and hand it over to me.

**Pull request merged**
