### PR TITLE
Collected small changes and fixes

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request combines multiple small changes and fixes

**Related Issue(s)**

N/A

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

The following individual changes are included:
- fix broken src/ELECTRODE/Install.sh script.
- Make removal of include statements from Makefile.package.settings in Install.sh scripts accept leading whitespace

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by akohlmey** [comment]
@sjplimp @athomps @stanmoore1 has there been a final decision on whether we adopt the `xxx_command.{cpp,h}` convention for *all* explicit command style files (if only a subset, which?). The ML-POD pull request went back and forth a few times, and I didn't see a confirmation of a decision. So I am a bit confused now. 
If the answer is yes, should we apply this to other such commands, too? and if yes to that, this branch could be a place to do it. Or should you prefer a separate request?
Also, what would be to filename convention if there is a suffix? `xxx_command_suffix.h`? or `xxx_suffix_command.h`?

Here is the current list of files that would be affected:
```
balance.h
change_box.h
create_atoms.h
create_bonds.h
create_box.h
delete_atoms.h
delete_bonds.h
displace_atoms.h
info.h
minimize.h
read_data.h
read_dump.h
read_restart.h
replicate.h
rerun.h
reset_atoms_id.h
reset_atoms_image.h
reset_atoms_mol.h
run.h
set.h
velocity.h
write_coeff.h
write_data.h
write_dump.h
write_restart.h
COLVARS/group_ndx.h
COLVARS/ndx_group.h
KOKKOS/dynamical_matrix_kokkos.h
KOKKOS/third_order_kokkos.h
PHONON/dynamical_matrix.h
PHONON/third_order.h
PLUGIN/plugin.h
REPLICA/hyper.h
REPLICA/neb.h
REPLICA/prd.h
REPLICA/tad.h
REPLICA/temper_grem.h
REPLICA/temper.h
REPLICA/temper_npt.h
SPIN/neb_spin.h
```

**Comment by athomps** [comment]
I think the suffix `_command` should only be required when the command name coincides with another software object:

mdi
kim
fitpod

Nothing else on the list seems to qualify.

Aidan


From: Axel Kohlmeyer ***@***.***>
Reply-To: lammps/lammps ***@***.***>
Date: Friday, December 2, 2022 at 9:06 AM
To: lammps/lammps ***@***.***>
Cc: Aidan Thompson ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [lammps/lammps] Collected small changes and fixes (PR #3542)


@sjplimp<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsjplimp&data=05%7C01%7Cathomps%40sandia.gov%7C41260aeeb76647e22b1f08dad47f3beb%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638055940179193730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yLppXAef2kx1VlB9sGpJi12PGppUl7GxKiCcfxuc%2BFw%3D&reserved=0> @athomps<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fathomps&data=05%7C01%7Cathomps%40sandia.gov%7C41260aeeb76647e22b1f08dad47f3beb%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638055940179193730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B02ZPZWqT3zYmnN8F3iYDYkQA0iw8ebwaTdlJxUyBCQ%3D&reserved=0> @stanmoore1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstanmoore1&data=05%7C01%7Cathomps%40sandia.gov%7C41260aeeb76647e22b1f08dad47f3beb%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638055940179193730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4uZUSpyVdc%2F6xU1ykyCaio3aPYwuc98mJH9gr26CRNg%3D&reserved=0> has there been a final decision on whether we adopt the xxx_command.{cpp,h} convention for all explicit command style files (if only a subset, which?). The ML-POD pull request went back and forth a few times, and I didn't see a confirmation of a decision. So I am a bit confused now.
If the answer is yes, should we apply this to other such commands, too? and if yes to that, this branch could be a place to do it. Or should you prefer a separate request?
Also, what would be to filename convention if there is a suffix? xxx_command_suffix.h? or xxx_suffix_command.h?

Here is the current list of files that would be affected:

balance.h

change_box.h

create_atoms.h

create_bonds.h

create_box.h

delete_atoms.h

delete_bonds.h

displace_atoms.h

info.h

minimize.h

read_data.h

read_dump.h

read_restart.h

replicate.h

rerun.h

reset_atoms_id.h

reset_atoms_image.h

reset_atoms_mol.h

run.h

set.h

velocity.h

write_coeff.h

write_data.h

write_dump.h

write_restart.h

COLVARS/group_ndx.h

COLVARS/ndx_group.h

KOKKOS/dynamical_matrix_kokkos.h

KOKKOS/third_order_kokkos.h

PHONON/dynamical_matrix.h

PHONON/third_order.h

PLUGIN/plugin.h

REPLICA/hyper.h

REPLICA/neb.h

REPLICA/prd.h

REPLICA/tad.h

REPLICA/temper_grem.h

REPLICA/temper.h

REPLICA/temper_npt.h

SPIN/neb_spin.h

**Comment by akohlmey** [comment]
> I think the suffix `_command` should only be required when the command name coincides with another software object: mdi kim fitpod Nothing else on the list seems to qualify.

FYI, "fitpod" does not collide with anything, either. That is why I am so confused it was changed back to `fitpod.h`   from`fitpod_command.h`.

**Comment by sjplimp** [comment]
I am also opposed to changing the ~50 file names to something like run_command.cpp
If a user/developer wants to find all the commands, they can simply do this in the src dir:
% grep CommandStyle *.h */*.h
same for other styles

**Comment by athomps** [comment]
I think you meant "*not* changed back to `fitpod.h`".  For fitpod, the collision is not in the code, but in the human brain:


>>The reasoning was explained by [@exapde](https://github.com/exapde):
>>>I prefer fitpod_command.h/cpp' because we can immediately see fitpod is a Command Style. Similarly, we can see pair_pod.h/cpp' is a Pair Style right away without looking at the >contents of the files. The file name 'fitpod.h/cpp' is not specific enough, so we don't know if it is a style class or an auxiliary supporting class unless we look into their implementation.

**Comment by akohlmey** [comment]
> I think you meant "_not_ changed back to `fitpod.h`". For fitpod, the collision is not in the code, but in the human brain:

Sorry. But this is where I am getting confused. The same reason applies (or not) to the other commands.
having the file names fitpod.h/fitpod.cpp is just as good as, e.g. neb.h/neb.cpp or run.h/run.cpp and the reason for using fitpod_command.h/fitpod_command.cpp would also apply to the other files.

Please help me to resolve this contradiction.

**Comment by athomps** [comment]
This is not rigorous, so there no contradiction. The motivation described below makes sense to me for fitpod. I don't think it makes sense for neb or run.

>The file name 'fitpod.h/cpp' is not specific enough, so we don't know if it is a style class or an auxiliary supporting class >unless we look into their implementation.

But if it is too inconsistent, I am okay with `fitpod.cpp/h`

**Comment by akohlmey** [comment]
> This is not rigorous, so there no contradiction. The motivation described below makes sense to me for fitpod. I don't think it makes sense for neb or run.
> 
> > The file name 'fitpod.h/cpp' is not specific enough, so we don't know if it is a style class or an auxiliary supporting class >unless we look into their implementation.

But - as I said multiple times - *this* reasoning *does* apply to "run", "neb"  and many of the others I listed, too. Consider we have "fix neb" for example. Only when you look at neb.h do you see that this is for a command and not a support class for fix neb. How can this not be a contradiction?

**Comment by athomps** [comment]
> But - as I said multiple times - _this_ reasoning _does_ apply to "run", "neb" and many of the others I listed, too. Consider we have "fix neb" for example. Only when you look at neb.h do you see that this is for a command and not a support class for fix neb. How can this not be a contradiction?

Yes, I agree, NEB may also qualify.  I propose we consider adding `_command` for each command on a case by case basis, but only add the extra 8 characters If there is a need.

**Pull request closed without merging**
