### PR TITLE
Fix issues in ReaxFF QEq and ACKS2

### PR DESCRIPTION
**Pull request by stanmoore1**
**Summary**

The removal of ghost atoms in the fix QEq and ACKS2 neigh lists (5888ba05146f12a618ef2125a29ac385c3167f5c) introduced a potential out of bounds access in the neigh list `ilist` and also caused the BiCGStab solver to fail with bad numerics when using a full list with Kokkos.

**Related Issue(s)**

5888ba05146f12a618ef2125a29ac385c3167f5c

**Author(s)**

Stan Moore (SNL), reported by Ray Shan (Materials Design)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Yes

### CODE REVIEW

**Review by athomps — APPROVED** [review]
Very good. I approve.

**Comment by stanmoore1** [comment]
This passes all the tests I ran by hand. Full Kokkos regression testing is pending.

**Comment by stanmoore1** [comment]
@akohlmey weird that the unit tests had a segfault, I didn't see that in my testing.

**Comment by akohlmey** [comment]
> @akohlmey weird that the unit tests had a segfault, I didn't see that in my testing.

Not weird. The unittest procedure does the equivalent of multiple "clear" commands and "write/read_restart/data" and that is often not done in "normal" inputs. This regularly exposes when restarts don't store all relevant data or when data is not properly initialized when used the first time. Since Linux uses a malloc() that derives large memory blocks from using mmap(/dev/zero) with copy-on-write semantics, class members are initialized to 0 the first time around so many problems don't show, but after a "clear" memory is free()d and allocated and then will contain "random" data and then uninitialized variables can cause problems.

**Pull request merged**
