### PR TITLE
Avoid double free in some Kokkos pair styles destruction

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

During the destruction of some Kokkos Pair styles the Pair destructor tries to free non-null pointers. I got some of them, but I suspect there is more like these.

This is what happened with Kokkos and OpenMP during tests, which create LAMMPS instances one by one.
```
#0  0x00007ffff715fef5 in raise () from /usr/lib64/libc.so.6
#1  0x00007ffff7149862 in abort () from /usr/lib64/libc.so.6
#2  0x00007ffff71a1f38 in __libc_message () from /usr/lib64/libc.so.6
#3  0x00007ffff71a9bea in malloc_printerr () from /usr/lib64/libc.so.6
#4  0x00007ffff71aafbc in _int_free () from /usr/lib64/libc.so.6
#5  0x00007ffff71aeca8 in free () from /usr/lib64/libc.so.6
#6  0x000055555637be6b in LAMMPS_NS::Memory::sfree (this=0x55555a4481f0, ptr=0x55555a531b00) at /home/richard/GitHub/lammps/lammps/src/memory.cpp:118
#7  0x0000555556315ce1 in LAMMPS_NS::Memory::destroy<double> (this=0x55555a4481f0, array=@0x55555af139a8: 0x55555a531b00) at /home/richard/GitHub/lammps/lammps/src/memory.h:79
#8  0x000055555640c1e6 in LAMMPS_NS::Pair::~Pair (this=0x55555af138b0, __in_chrg=<optimized out>) at /home/richard/GitHub/lammps/lammps/src/pair.cpp:144
#9  0x0000555556e7e712 in LAMMPS_NS::PairCoulCut::~PairCoulCut (this=0x55555af138b0, __in_chrg=<optimized out>) at /home/richard/GitHub/lammps/lammps/src/pair_coul_cut.cpp:37
#10 0x0000555557bf5391 in LAMMPS_NS::PairCoulCutKokkos<Kokkos::OpenMP>::~PairCoulCutKokkos (this=0x55555af138b0, __in_chrg=<optimized out>) at /home/richard/GitHub/lammps/lammps/src/KOKKOS/pair_coul_cut_kokkos.cpp:51
#11 0x0000555557bf53d9 in LAMMPS_NS::PairCoulCutKokkos<Kokkos::OpenMP>::~PairCoulCutKokkos (this=0x55555af138b0, __in_chrg=<optimized out>) at /home/richard/GitHub/lammps/lammps/src/KOKKOS/pair_coul_cut_kokkos.cpp:51
#12 0x0000555556dc6e16 in LAMMPS_NS::Force::~Force (this=0x55555a46e1e0, __in_chrg=<optimized out>) at /home/richard/GitHub/lammps/lammps/src/force.cpp:145
#13 0x0000555556dc71b3 in LAMMPS_NS::Force::~Force (this=0x55555a46e1e0, __in_chrg=<optimized out>) at /home/richard/GitHub/lammps/lammps/src/force.cpp:165
#14 0x000055555632070e in LAMMPS_NS::LAMMPS::destroy (this=0x55555b2ae240) at /home/richard/GitHub/lammps/lammps/src/lammps.cpp:907
#15 0x000055555631e0bf in LAMMPS_NS::LAMMPS::~LAMMPS (this=0x55555b2ae240, __in_chrg=<optimized out>) at /home/richard/GitHub/lammps/lammps/src/lammps.cpp:704
```

**Related Issue(s)**

**Author(s)**

@rbberger (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by akohlmey** [comment]
@stanmoore1 can you please have a look at this PR as well?

**Comment by stanmoore1** [comment]
I think I have this working, running Kokkos regression tests now.

**Comment by stanmoore1** [comment]
@rbberger do you have unit tests you can perform on this PR?

**Comment by akohlmey** [comment]
> @rbberger do you have unit tests you can perform on this PR?

The standard unit tests are run automatically every time this PR is updated. Last run overview is here: https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Funit_tests/detail/unit_tests/2545/pipeline/34
and detailed results are here:
https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Fubuntu%2Funit_tests%2Fcmake_mpi_openmp_smallsmall_shared/detail/cmake_mpi_openmp_smallsmall_shared/2516/tests
https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Fubuntu%2Funit_tests%2Fcmake_mpi_openmp_smallbig_shared/detail/cmake_mpi_openmp_smallbig_shared/2516/tests
https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Fubuntu%2Funit_tests%2Fcmake_mpi_openmp_bigbig_shared/detail/cmake_mpi_openmp_bigbig_shared/2516/tests

I just enabled the extended library of tests with explicit inputs (not googletest based).
https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Fregression_tests/detail/regression_tests/222/pipeline
https://ci.lammps.org/blue/organizations/jenkins/dev%2Fpull_requests%2Frun_tests/detail/run_tests/233/pipeline

**Comment by stanmoore1** [comment]
Thanks @akohlmey. @rbberger was originally running the PairStyle tester with Kokkos, not sure that is in the code base yet?

**Comment by akohlmey** [comment]
> Thanks @akohlmey. @rbberger was originally running the PairStyle tester with Kokkos, not sure that is in the code base yet?

It isn't. We just very recently sorted out issues with getting (some) testing with the GPU package working without failures (on our test server(s)).

**Review by akohlmey — APPROVED** [review]

**Comment by stanmoore1** [comment]
@akohlmey this PR wasn't quite ready to merge, hence why it was still assigned to `stamoor`. I will submit a follow-on PR shortly.

**Comment by akohlmey** [comment]
Sorry about that. Friday was a bit hectic. I didn't want to delay the patch
release for another week. But it looks like doing another patch soon will
be a good idea, since I noticed some other issues that went under the
radar...

--
Dr. Axel Kohlmeyer ***@***.*** http://goo.gl/1wk0
College of Science & Technology, Temple University, Philadelphia PA, USA
International Centre for Theoretical Physics, Trieste, Italy

**Pull request merged**
