### PR TITLE
Collected small fixes and updates for LAMMPS and LAMMPS-GUI

### LINKED ISSUE #4246: [BUG] ValueTokenizer fails to read bigint on windows
**Summary**

>18: [ RUN      ] PotentialFileReaderTest.convenience_functions
18: D:\a\lammps\lammps\unittest\formats\test_potential_file_reader.cpp(289): error: Expected equality of these values:
18:   reader.next_bigint()
18:     Which is: 2147483647
18:   9223372036854775807i64
18:     Which is: 9223372036854775807
18: [  FAILED  ] PotentialFileReaderTest.convenience_functions (3 ms)

>[ RUN      ] TextFileReaderTest.convenience_functions
20: D:\a\lammps\lammps\unittest\formats\test_text_file_reader.cpp(190): error: Expected equality of these values:
20:   reader.next_bigint()
20:     Which is: 2147483647
20:   9223372036854775807i64
20:     Which is: 9223372036854775807
20: [  FAILED  ] TextFileReaderTest.convenience_functions (0 ms)

**LAMMPS Version and Platform**

see PR https://github.com/lammps/lammps/pull/4245

**Expected Behavior**

read 9223372036854775807

**Actual Behavior**

got 2147483647

**Steps to Reproduce**

```
TEST_F(PotentialFileReaderTest, convenience_functions)
{
    FILE *fp = fopen("potential_reader.file", "w");
    fmt::print(fp, "123\n");
    fmt::print(fp, "-123.45\n");
    fmt::print(fp, "{}\n", DBL_MIN);
    fmt::print(fp, "{}\n", DBL_MAX);
    fmt::print(fp, "{}\n", -DBL_MIN);
    fmt::print(fp, "{}\n", -DBL_MAX);
    fmt::print(fp, "{}\n", MAXSMALLINT);
    fmt::print(fp, "{}\n", MAXTAGINT);
    fmt::print(fp, "{}\n", MAXBIGINT);
    fmt::print(fp, "fooBAR\n");
    fclose(fp);

    BEGIN_HIDE_OUTPUT();
    command("units real");
    PotentialFileReader reader(lmp, "potential_reader.file", "test");
    END_HIDE_OUTPUT();

    ASSERT_DOUBLE_EQ( reader.next_double(), 123 );
    ASSERT_DOUBLE_EQ( reader.next_double(), -123.45 );
    ASSERT_DOUBLE_EQ( reader.next_double(), DBL_MIN );
    ASSERT_DOUBLE_EQ( reader.next_double(), DBL_MAX );
    ASSERT_DOUBLE_EQ( reader.next_double(), -DBL_MIN );
    ASSERT_DOUBLE_EQ( reader.next_double(), -DBL_MAX );
    ASSERT_EQ( reader.next_int(), MAXSMALLINT );
    ASSERT_EQ( reader.next_tagint(), MAXTAGINT );
    ASSERT_EQ( reader.next_bigint(), MAXBIGINT );
    ASSERT_STREQ( reader.next_string().c_str(), "fooBAR" );
    platform::unlink("potential_reader.file");
}
```

**Further Information, Files, and Links**

could be a problem with _atoi64 on windows ?

tokenizer.cpp
>bigint ValueTokenizer::next_bigint()
{
  std::string current = tokens.next();
  if (!utils::is_integer(current)) { throw InvalidIntegerException(current); }
  return ATOBIGINT(current.c_str());
}

lmpwindows.h:
>#undef ATOBIGINT
#define ATOBIGINT _atoi64

### LINKED ISSUE #4249: [BUG] `PyLammps.eval` throws `AttributeError` in ranks except rank 0 with mpi4py 4.0.0
**Summary**

When using mpi4py 4.0.0 (released two days ago) with pylammps, executing `PyLammps.eval` throws `AttributeError` in all ranks except rank 0.

I don't know whether it is a bug in mpi4py 4.0.0 or a breaking change that PyLammps needs to adopt.

**LAMMPS Version and Platform**

stable_2Aug2023_update3, Linux

**Expected Behavior**

With mpi4py 3.1.6, when doing `PyLammps.eval`, all ranks give the expected result (for example, `-4.77743273563228`).

**Actual Behavior**

With mpi4py 4.0.0, when doing `PyLammps.eval`, got
```
File "/usr/local/lib/python3.11/site-packages/lammps/pylammps.py", line 714, in eval
  value = self.lmp_print('"$(%s)"' % expr).strip()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```

`PyLammps.lmp_print` returns the expected value (e.g. `-4.77743273563228`) in rank 0 but `None` in other ranks.

**Steps to Reproduce**

Use docker to run `docker build --progress=plain .` using the following docker file and the test script.

`Dockerfile`:

```dockerfile
FROM python:3.11

ARG LAMMPS_VERSION=stable_2Aug2023_update3
ARG INSTALL_PREFIX=/lammps

RUN apt-get update && apt-get -y install cmake mpich

RUN curl -L -o lammps.tar.gz https://github.com/lammps/lammps/archive/refs/tags/${LAMMPS_VERSION}.tar.gz \
  && tar vxzf lammps.tar.gz \
  && rm lammps.tar.gz \
  && cd lammps-${LAMMPS_VERSION} \
  && mkdir build \
  && cd build \
  && cmake -C ../cmake/presets/all_off.cmake \
     -DLAMMPS_EXCEPTIONS=yes \
     -D BUILD_SHARED_LIBS=yes \
     -D LAMMPS_INSTALL_RPATH=ON \
     -D CMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
     ../cmake \
  && make -j4 \
  && make install \
  && make install-python \
  && cd ../../ \
  && rm -rf lammps-${LAMMPS_VERSION}

ENV LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:$LD_LIBRARY_PATH

RUN pip install 'mpi4py'  # or change to 'mpi4py<4'
ADD test_mpi.py /test_mpi.py
RUN curl -L -o in.melt https://raw.githubusercontent.com/lammps/lammps/master/examples/melt/in.melt
RUN mpirun -np 4 python /test_mpi.py
```

`test_mpi.py`:

```py
from mpi4py import MPI
from lammps import PyLammps

L = PyLammps()
L.file("in.melt")

print("Potential energy: ", L.eval("pe"))

MPI.Finalize()
```

**Further Information, Files, and Links**

https://github.com/mpi4py/mpi4py/releases/tag/4.0.0

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request combines multiple small bugfixes and updates that do not warrant a pull request of their own.

**Related Issue(s)**

Fixes the crash reported here https://github.com/lammpstutorials/lammpstutorials-article/pull/10#issuecomment-2249925159
Fixes #4246 
Includes #4247 
Closes #4249 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues. All tests pass.

**Implementation Notes**

The following individual changes are included:
- use "is" instead of "==" for comparison to None in Python
- fix crash in OpenMP version of ReaxFF that crashes in hbondchk due to not looping over ghost atoms
- correct error output for molecule files
- make native trajectory reader detect triclinic boxes reliably for various revisions of the trajectory file format
- add entry to open Simon Gravelle's LAMMPS tutorial from the About menu in LAMMPS-GUI
- add option to LAMMPS-GUI to export collected thermo data to YAML file form the chart viewer
- add option to LAMMPS-GUI to recenter snapshot image on COM of selected group
- fix error in pair style born/gauss docs
- fix out-of-bounds memory access in pair style dpd/coul/slater/gpu
- update force style tests for bonded interfactions to also test KOKKOS/OpenMP. Imported from PR #4190 
- update tests for ValueTokenizer
- update library interface tests enabling KOKKOS to handle the case of enabled GPU support (which *must* be used).
- update conversion of string to integer using stroll() (available since c++11) and strod() instead of atoi(), atol(), atoll(), and atof() with checks for partial conversion and overflow. See issue #4246 
- some changes in PyLammps to better handle running with MPI. Raise exception on eval() if not called from MPI rank 0. Some updates for the documentation
- includes KOKKOS related fixes from PR #4247 
- includes KOKKOS GFX1103 GPU support from PR #4248 

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by akohlmey** [comment]
@megmcca, @alphataubio, @stanmoore1 testing with KOKKOS/OpenMP needed to be skipped for dihedral styles hybrid, charmmfsw, and improper style class2, since those tests currently fail when running ctest.

**Comment by alphataubio** [comment]
> @megmcca, @alphataubio, @stanmoore1 testing with KOKKOS/OpenMP needed to be skipped for dihedral styles hybrid, charmmfsw, and class2, since those tests currently fail when running ctest.

the original test doesnt work because dihedral charmmfsw in not compatible with pair lj/charmmfsw/coul/charmmfsh on kokkos (i cant remember why now sorry), so dihedral-charmmfsw.yaml should be skipped for kokkos_omp that's correct. instead dihedral-charmmfsw-kokkos.yaml from PR 4190 with pair lj/charmmfsw/coul/long is the correct test.

remember you asked me to submit an additional test in PR 4190 ?

> On [unittest/force-styles/tests/dihedral-charmmfsw.yaml](https://github.com/lammps/lammps/pull/4190#discussion_r1633272420):
Please roll back these changes. The purpose of the test is to test the dihedral style and it does so with the minimum set of external dependencies. If you absolutely insist on testing the charmm dihedral style with a coul/long pair style, then please submit it as an additional test.

which is called dihedral-charmmfsw-kokkos.yaml.

conclusion: please import dihedral-charmmfsw-kokkos.yaml from PR 4190 and leave dihedral-charmmfsw.yaml kokkos_omp skipped.

**Comment by alphataubio** [comment]
@akohlmey UPDATE: i fixed bug in dihedral_charmmfsw_kokkos to make compatible with pair lj/charmmfsw/coul/charmmfsw so that both tests now pass with:

(1) pair lj/charmmfsw/coul/charmmfsw [dihedral-charmmfsw-coul_charmmfsw.yaml]
(2) pair lj/charmmfsw/coul/long [dihedral-charmmfsw-coul_long.yaml]
 
see commit https://github.com/lammps/lammps/pull/4190/commits/8751d073754d55cd35af9422d6b9d0266b942063 in PR 4190.

**Comment by akohlmey** [comment]
> UPDATE: i fixed bug in dihedral_charmmfsw_kokkos

Thanks a lot. I imported the bugfix. There is no need to have the test split into two tests, since the test checks the dihedral, not the pair style.

**Comment by akohlmey** [comment]
@Eddy-Barraud @ndtrung81 please check out the change I made in commit https://github.com/lammps/lammps/pull/4242/commits/5501f608f545506f6fbed5fdb055bd2fea3e304c
When compiling on a machine with AMD GPU using hipcc it complained about out of  bounds memory access and this change seemed to be the logical fix (it did turn off the warning).

**Review by sjplimp — APPROVED** [review]

**Comment by akohlmey** [comment]
@sjplimp check out the changes to the ValueTokenizer class in commit https://github.com/lammps/lammps/pull/4242/commits/9c937113fd074b47a7e22eb9eb23c0400b8a5927. They are still rather minimal, avoid he ATOXXX macros. *and* include checking for partial conversion or out-of-range values. Still need to update the Xnumeric() functions and a few other places accordingly. This is working on Windows, too. Also need to write more tests to check whether all the checks work.

**Pull request merged**
