### PR TITLE
Documentation Refactoring: Section Start

### PR DESCRIPTION
**Pull request by sjplimp**
## Purpose

Last set of changes for refactoring the doc pages.  This replaces Section_start.txt with
Install, Build, Run.  This still needs some polishing, specifically TODO comments and
Build_extras.txt.

## Author(s)

Steve

## Backward Compatibility

N/A.

## Implementation Notes

_Provide any relevant details about how the changes are implemented, how correctness was verified, how other features - if any - in LAMMPS are affected_

## Post Submission Checklist

_Please check the fields below as they are completed_
- [ ] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files, and URLs to external sites (e.g. DOIs or webpages)_

### CODE REVIEW

**Comment by akohlmey** [comment]
@rbberger i've merged in #1047 and also merged with master to resolve the conflicts due to the doc changes related to the KOKKOS tweaks in #1042 
It's all yours now, baby. ;-)

**Comment by rbberger** [comment]
@sjplimp I've completed my first pass on this. The remaining CMake TODOs are open questions at I don't have an answer to.

**Comment by akohlmey** [comment]
@sjplimp @rbberger did some additional polishing and rewording. Added some missing info on OpenMP and USER-QMMM. As for CMake building and other places, where we have to refer to the LAMMPS source folder, we should stick to the convention of `/path/to/lammps/` and then create a build folder called `build` in that folder, and thus refer to the `cmake` folder with `cmake ../cmake`. This has in my opinion the best chances to work for people and is also what i have seen most often being used (as default) for packages, that i have been compiling, that were using CMake. I've also changed the wording in a few places, to say that CMake creates the "build environment" instead of saying it produces a Makefile (that is just the default on Linux). There are probably some more places, that could be rewritten in a similar style.

**Comment by akohlmey** [comment]
sorted out a few more TODO items

**Comment by rbberger** [comment]
@sjplimp I've reduced the depth of the HowTo TOCs and fixed the FFT settings **again**. It won't work the other way.

**Comment by rbberger** [comment]
@sjplimp KOKKOS merged the change I proposed (see https://github.com/kokkos/kokkos/pull/1735), so for me it would be ok to mention that KOKKOS is supported with CMake, once we got that patch too. @stanmoore1 how to we get one in? Can you do a sync/snapshot of KOKKOS in a separate PR or should I just add this one line change here?

**Comment by stanmoore1** [comment]
@rbberger let's just patch the Kokkos version in LAMMPS, i.e. add the one line change here. Thanks

**Comment by sjplimp** [comment]
@rbberger @junghans The push I made could be the last update needed for this PR,
at least from me.
All the TODO flags are resolved.  Here are things to check:

a) I included the Kokkos CMake build info in Build_extras.txt.
If you decide to disable it for now, you could just add
a NOTE saying it is not yet available.

b) The Build_settings.txt section on CMake for FFT settings
requires upper-case for FFTW, MKL, KISS, etc.  I think it is
now the only CMake variable that does not allow lower-case.
It's fine if we leave it that way for the release, there
is a comment to that effect.  If Christoph can change it
in CMakeLists.txt before the stable, we can re-document it.

c) Build_cmake.txt says that CMake checks for invalid values.
If this is not true, we should add a NOTE that says it
will at some point, but not yet.  I assume this requires
some coding in CMakeLists.txt, but don't think it has
been done?

d) I changed the GPU package section of CMakeLists.txt
to reflect the doc page.  This introduced lower-case allowed,
and syntax consistent with the make build via Install.py,
e.g. mixed/double/single and arch = 30,50,60,70, etc.
You should check that I did it correctly, and that
it works as documented ??

**Comment by rbberger** [comment]
@sjplimp 
a.) fine with me, it’s a bumpy experience in some cases, but it’s good enough for me.
b.) for me this is now done. I won’t touch it. If you break it one more time, you need to fix it. 😄
c.) CMake warns you if you use an unknown setting, or has an error if you try to specify an invalid value for a specific data type. That is good enough. This is CMake’s job, not ours.
d.) I don’t like this at all. For two reasons: the GPU_ARCH was a value consistent with CUDA architecture values sm_30, sm_40, etc which have a meaning for CUDA programmers/users. And in the end, if we figure out how to do fat-binaries that will become a list of those values. So I would change this back. Also, the output for cmake is reporting sm_XY, which is confusing if you just set it to a number. So much for consistency.

**Comment by junghans** [comment]
@rbberger @sjplimp 
b.) Isn't is just adding `string(TOUPPER ${FFT} FFT)` ? Or do I miss something here? That would allow the user to input whatever crazy capitalization, e.g. `Kiss`, `KiSS`, `kisS`, `FFTw` or `fftw`.
c.) @rbberger, the only case which isn't covered are typos in the values, e.g. `LAMMPS_SIZES=sallsmall`.
d.) I agree with @rbberger here, when you [google `sm_60`](https://www.google.com/search?q=sm_60) you get a lot of use full Nvidia stuff, not so much for `60`.

Additional comment:
e.) We need to update some of the defaults, e.g. `BUILD_MPI` and `BUILD_OMP` in `cmake/README.md`.

**Comment by sjplimp** [comment]
@rbberger @junghans thanks for the feedback
b) I wasn't planning to change anything on this, just flagging that it should
be done at some point.  If not before the stable that's fine.
@junghans also for FFTW2 to support single-precision, the
lib needs to be -lsfftw instead of -lfftw.  I don't see any logic for
that in CMakeLists.txt.  If we want to not support FFTW2 or
not support single-prec with FFTW2, that's fine.  Again,
we just need to make the doc page consistent.
c) yes, it's typos in the values that I'd like to catch and flag,
again if not before the stable, that's fine.  We should just change
the doc page to clarify that
d) ok, I'll change 60 --> sm_60 and modify the make Install.,py
to be consistent.  I'm assuming the mixed/double/single is ok,
and allowing lower-case on other settings - I have no simple
way to test the CMakeLists.txt changes I made for that.
e) also I forgot to change the doc page from LAMMPS_JPEG --> WITH_JPEG,
will do that this AM

**Comment by rbberger** [comment]
b.) @junghans, adding new variables was paranoia on my end. You’re right, I think. At this stage I’ll do one more sweep and clean it up
c.) I still believe this is should be solved by cmake, but I can do something simple about it @sjplimp let me know when you’re ready
d.) thx
e.) yeah the README.md is now very outdated, need to go over it

**Comment by sjplimp** [comment]
@rbberger @junghans made the sm_60 vs 60 change
also changed Python.txt to Python_head.txt for the lower/upper case filename match
@rbberger I don't see where commands.txt is referenced in the doc pages or doc build.
Can we change the name of that file to e.g. commands_list.txt to avoid the
conflict with Commands.txt ??
If my earlier flagged issues (b,c) are resolved either in the doc pages or CMakeLists.txt
then I'm ready to merge

**Comment by sjplimp** [comment]
@rbberger I found where to change commands -> commands_list to avoid conflict with Commands.txt, pushed it

**Comment by rbberger** [comment]
c.) @junghans @sjplimp so I added validation for all options which use lists and removed the extra DEFINE variables. E.g.:
```cmake
set(LAMMPS_SIZES "smallbig" CACHE STRING "LAMMPS size limit")
set(LAMMPS_SIZES_VALUES smallbig bigbig smallsmall)
set_property(CACHE LAMMPS_SIZES PROPERTY STRINGS ${LAMMPS_SIZES_VALUES})
validate_option(LAMMPS_SIZES LAMMPS_SIZES_VALUES)
string(TOUPPER ${LAMMPS_SIZES} LAMMPS_SIZES)
```
Output:
```
cmake -D LAMMPS_SIZES=bla ../cmake
-- Running check for auto-generated files from make-based build system
CMake Error at CMakeLists.txt:37 (message):
  

  ########################################################################

  Invalid value 'bla' for option 'LAMMPS_SIZES'

  

  Possible values are:

  * smallbig

  * bigbig

  * smallsmall

  ########################################################################
```

**Comment by rbberger** [comment]
@sjplimp @junghans  I think we took care of everything, concerning b.) I would drop FFTW2 support. Take it as an opportunity to cut old ties. After putting that in the docs, that should be it.

**Comment by sjplimp** [comment]
@rbberger @junghans ok - dropped FFTW2 support for both CMake and make, updated
the doc pages accordingly - I'm ready to merge if you assign it back to me - thanks
to both of you for help with the polishing!

**Comment by rbberger** [comment]
@sjplimp Ok, go ahead.

**Comment by sjplimp** [comment]
@rbberger changed the docs to say no packages are now pre-installed in tarball

**Comment by junghans** [comment]
Nice job!

**Pull request merged**
