### PR TITLE
Modernize to C++11: use override

### LINKED ISSUE #2946: [Feature Request] Apply semi-automated code refactoring with clang-tidy
**Summary**

Now that we require a C++11 standard compiler to compile LAMMPS from some time, we should try to take more advantage of  C++11 language features. In part this has already been done, e.g. with PR #2358 where NULL was replaced by nullptr, but there are some other items where new language features can help improving the code by triggering compilation errors or warnings when applied. As the experience with PR #2358 has show, this refactoring can be tedious work, but the LLVM project has [a tool called clang-tidy](https://clang.llvm.org/extra/clang-tidy/) which can not only provide static code analysis but also in some cases [can refactor the code automatically](https://www.kdab.com/clang-tidy-part-1-modernize-source-code-using-c11c14/).
Thus the suggestion is to apply **some** of these modernizations in order to detect possible bugs and make it harder to introduce bugs in new code. Once we have settled on a set of items we can also add a check that will scan all pull requests to identify possible mismatches.

One of the most obvious modernization worth using is to add the `override` keyword for virtual methods. This can avoid issues that already happened multiple times in LAMMPS where arguments were added to a function in a base class, but with default values (to ensure backward compatibility). That would change the function signature and overridden versions in derived classes would suddenly become overloads with a different signature and thus no longer be called as intended and therefore causing unexpected and sometimes difficult to debug behavior.

**List of possible modernizations**

The the clang-tidy homepage has a [list of available checks](https://clang.llvm.org/extra/clang-tidy/checks/list.html) and indications whether it can update the code accordingly. The purpose of this feature request is to compile a list of changes that are meaningful and improve the code without changing it too much. Below is a list of links to currently available modernization features (features that don't apply to LAMMPS are not listed). The list is approximately ordered by significance. Some checks do not trigger any existing code, but could be used for checking new contributions.

* **Use always**
  - [x] [Use `override` keyword]()
  - [x] [Remove redundant void arguments](https://clang.llvm.org/extra/clang-tidy/checks/modernize-redundant-void-arg.html)
  - [x] [Use nullptr instead of NULL](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html)
  - [x] [Replace obsolete std::auto_ptr with std::unique_ptr](https://clang.llvm.org/extra/clang-tidy/checks/modernize-replace-auto-ptr.html)
  - [x] [Replace obsolecent std::random_shuffle](https://clang.llvm.org/extra/clang-tidy/checks/modernize-replace-random-shuffle.html)
  - [x] [Remove/replace deprecated C headers](https://clang.llvm.org/extra/clang-tidy/checks/modernize-deprecated-headers.html)
  - [x] [Label default constructors with `= default`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-default.html)
  - [x] [Label disabled constructors with `= delete`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-equals-delete.html)
* **Use on a case by case basis**
  - [x] [Modernize loops](https://clang.llvm.org/extra/clang-tidy/checks/modernize-loop-convert.html)
  - [x] [Replace 1 and 0 used to initialize `bool` variables with `true` and `false`](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-bool-literals.html)
  - [x] [Use pass by value in constructors where beneficial](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html)
  - [x] [Return braced a initializer instead of a typed one](https://clang.llvm.org/extra/clang-tidy/checks/modernize-return-braced-init-list.html)
  - [ ] [Make more use of the `auto` data type](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-auto.html)
  - [x] [Use emplace with containers](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-emplace.html)
  - [x] [Use noexcept](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-noexcept.html)

**Procedure**

The changes would have to be introduced one change per commit and with running compilation, regression and unit testing after every iteration followed by any required tweaks or bugfixes as additional commit(s). That way it should be possible to identify which specific modernization has been causing any issues later and then selectively revert it, if needed.

**Further changes**

While not available as an automatic transformation, we should also take advantage of the `delete` keyword to explicitly disallow the use of unwanted constructors in base classes. For example, most classes in LAMMPS cannot be correctly instantiated using the default constructor. Adding `delete` will make any such use a compile time error and also explicitly indicate to the reader of the source that this is not meant to be used.

### PR DESCRIPTION
**Pull request by rbberger**
**Summary**

This PR semi-automatically applies clang-tidy suggestions to make use of the C++11 `override` keyword.

The changes use `override` following the [C++ Core Guideline C.128](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-override), which is a collection of best practices.

It also removes the empty destructor of derived classes. (Option B in below discussion)

**Related Issue(s)**

Closes #2946

**Author(s)**

Richard Berger (Temple U)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

All automated tests pass.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by rbberger** [comment]
@akohlmey @stanmoore1 @sjplimp @athomps These are now sufficient examples to showcase what clang-tidy and the C++ Core Guidelines are suggesting in terms of using `override`. Please review, before I proceed with further changes.

**Review by athomps — APPROVED** [review]
I approve

**Comment by sjplimp** [comment]
Looks good to me

**Comment by stanmoore1** [comment]
@rbberger sometimes I get compiler warnings about a missing `override`, I still have to fix those by hand, right?

**Comment by rbberger** [comment]
@stanmoore1 just this the first bunch of updates for the KOKKOS parts up to this point. I'm using clang-tidy and do some manual changes. The thing is, I don't want to touch the `lib/kokkos` files, but if I run the tool it does so anyway. So I'm only committing what applies to src/KOKKOS.

This is what I use right now. note that the build folder is a CMake build folder which contains a `KokkosCore_config`
```
clang-tidy -checks=modernize-use-override -header-filter=.* KOKKOS/region*.cpp -fix -- -I$PWD -I$PWD/KOKKOS -I$PWD/../lib/kokkos/core/src -I$PWD/../lib/kokkos/containers/src -I$PWD/../build/lib/kokkos -std=c++14
```

**Comment by akohlmey** [comment]
@stanmoore1 this discussion reminds me, that I had promised you to give you the commands that I was using for the other transformations that I (semi-automatically) applied via clang-tidy. Here is the command line for all (better to add the options in stages).
```
clang-tidy -checks=-*,modernize-loop-convert,modernize-use-bool-literals,modernize-use-nullptr,modernize-use-noexcept,modernize-redundant-void-arg -fix -header-filter=.*,header-filter=library.h,header-filter=fmt/*.h
```

**Comment by rbberger** [comment]
@sjplimp @athomps @stanmoore1 @akohlmey Need a consensus on this:
Currently working on NPair classes, and this is happening a lot:
Example:
```c++
class NPairSkip : public NPair {
 public:
  NPairSkip(class LAMMPS *);
  ~NPairSkip() {}
  void build(class NeighList *);
};
```
turns into A:
```c++
class NPairSkip : public NPair {
 public:
  NPairSkip(class LAMMPS *);
  ~NPairSkip() override = default;
  void build(class NeighList *);
};
```
but B would be same:
```c++
class NPairSkip : public NPair {
 public:
  NPairSkip(class LAMMPS *);
  void build(class NeighList *);
};
```
What do we prefer? Stay explicit?

**Comment by akohlmey** [comment]
B

**Comment by athomps** [comment]
My opinion is I don't have an opinion. Both A and B seem reasonable.

**Comment by sjplimp** [comment]
Ditto to Aidan - either is fine.

**Comment by rbberger** [comment]
@lammps/core ok, this should be everything.

**Comment by akohlmey** [comment]
> @lammps/core ok, this should be everything.

I transferred the changes to the plugin examples (which are just copies of existing styles with a different class name) and am about to test and then push them.

At this point we should also document this in the programmer guide section in the manual. A brief mention of when to use "override" and "virtual" in [this section](https://docs.lammps.org/Modify_style.html#programming-conventions-varied) at the minimum. But considering that many people attempting to modify and extend LAMMPS are not overly experienced in C++ programming and may be lacking formal training (like me), I am also thinking to have a section added that explains how LAMMPS uses C++ and in particular polymorphism and what this means to the scope of class members (with some examples). This should include a list of "don't"s like calling virtual functions from constructors unless with explicit scope.

**Comment by rbberger** [comment]
@akohlmey added two paragraphs that recommend what to do.

**Comment by akohlmey** [comment]
> @akohlmey added two paragraphs that recommend what to do.

thanks. I'll draft a longer and more explanation of "how much C++" to use and how it works in a separate pull request.

**Comment by akohlmey** [comment]
@lammps/core please (re-)review. Because this PR touches so many files, it would be time critical to merge it soon. On the other hand, because of its impact, I would like to have multiple approvals from core developers.

**Comment by athomps** [comment]
I tried compiling this in make with everything turned on. After turning off a few packages that need external libraries, I hit this error:

` Generating lmpinstalledpkgs.h...
 Checking for module 'readline'
   No package 'readline' found
`
I am not sure how to proceed

**Comment by akohlmey** [comment]
> I tried compiling this in cmake with everything turned on. After turning off a few packages that need external libraries, I hit this error:
> 
> `Generating lmpinstalledpkgs.h... Checking for module 'readline' No package 'readline' found` I am not sure how to proceed. How can I tell where this dependency is coming from?

from BUILD_LAMMPS_SHELL=on

**Comment by akohlmey** [comment]
> How can I tell where this dependency is coming from?

`find cmake -type f -print | xargs grep -i readline`

**Review by athomps — APPROVED** [review]
This loThe shear number of changes is bringing my browser to its

**Comment by athomps** [comment]
I approved it, but I could not add comments, due to my browser choking on the shear number of changes.  I did notice a few warnings generated by reaxff/kk source files:

fix_reaxff_bonds_kokkos.h:43:8: warning: 'Output_ReaxFF_Bonds' overrides
fix_reaxff_bonds_kokkos.h:44:10: warning: 'memory_usage' overrides a member
fix_reaxff_bonds_kokkos.h:43:8: warning: 'Output_ReaxFF_Bonds' overrides a member 
fix_reaxff_species_kokkos.h:43:8: warning: 'FindMolecule' overrides a member

I also saw a warning in ML-PACE, but in the external code.

**Comment by rbberger** [comment]
@athomps looks like clang-tidy was choking on a few more Kokkos files. But this now answers the question of how we can detect missing `override` keywords :wink:

**Comment by akohlmey** [comment]
> I also saw a warning in ML-PACE, but in the external code.

Yeah, that one is full of code constructs that we discourage. There are some issues with almost all external libraries.  lib/atc, lib/awpmd and lib/poems are also showing their age and that they are not actively maintained.

**Comment by stanmoore1** [comment]
In general this looks OK to. How should we sort out the missing `override`?

**Comment by athomps** [comment]
> In general this looks OK to. How should we sort out the missing `override`?
The warning in ML-PACE is fine as is. Richard has fixed the other warnings.

**Review by stanmoore1 — APPROVED** [review]

**Review by akohlmey — APPROVED** [review]

**Comment by stanmoore1** [comment]
I'm seeing this warning:

```
../pair_sw_kokkos.h(121): warning: function "LAMMPS_NS::PairSW::threebody(LAMMPS_NS::PairSW::Param *, LAMMPS_NS::PairSW::Param *, LAMMPS_NS::PairSW::Param *, double, double, double *, double *, double *, double *, int, double &)" is hidden by "LAMMPS_NS::PairSWKokkos<DeviceType>::threebody [with DeviceType=LMPHostType]" -- virtual function override intended?
          detected during instantiation of class "LAMMPS_NS::PairSWKokkos<DeviceType> [with DeviceType=LMPHostType]" 
../pair_sw_kokkos.cpp(971): here
```

Will check for others.

**Comment by stanmoore1** [comment]
The previous SW warning is the only one I see, including all packages with Kokkos dependencies.

**Comment by akohlmey** [comment]
> I'm seeing this warning:
> 
> ```
> ../pair_sw_kokkos.h(121): warning: function "LAMMPS_NS::PairSW::threebody(LAMMPS_NS::PairSW::Param *, LAMMPS_NS::PairSW::Param *, LAMMPS_NS::PairSW::Param *, double, double, double *, double *, double *, double *, int, double &)" is hidden by "LAMMPS_NS::PairSWKokkos<DeviceType>::threebody [with DeviceType=LMPHostType]" -- virtual function override intended?
>           detected during instantiation of class "LAMMPS_NS::PairSWKokkos<DeviceType> [with DeviceType=LMPHostType]" 
> ../pair_sw_kokkos.cpp(971): here
> ```
> 
> Will check for others.

I think the clean solution here would be to rename the function (threebody_kk?).  Making it virtual is for sw and sw/mod where you use the compute function from sw even in sw/mod, but want to override only the threebody function.
The KOKKOS version has a (slightly) different signature (references, const property), too.

**Comment by akohlmey** [comment]
unfortunately, I just merged this PR, so please add changes to any of the other open KOKKOS related PRs, e.g. #3100  or #3035 after updating them to upstream.

**Comment by akohlmey** [comment]
@stanmoore1 apropos warning, I keep getting this for compiling fix_rx_kokkos.cpp for some time now:
```
In file included from /home/akohlmey/compile/lammps/lib/kokkos/core/src/Kokkos_Parallel.hpp:59,
                 from /home/akohlmey/compile/lammps/lib/kokkos/core/src/Kokkos_OpenMP.hpp:62,
                 from /home/akohlmey/compile/lammps/lib/kokkos/core/src/decl/Kokkos_Declare_OPENMP.hpp:49,
                 from /home/akohlmey/compile/lammps/build-test/lib/kokkos/KokkosCore_Config_DeclareBackend.hpp:47,
                 from /home/akohlmey/compile/lammps/lib/kokkos/core/src/Kokkos_Core.hpp:56,
                 from /home/akohlmey/compile/lammps/src/KOKKOS/kokkos_type.h:21,
                 from /home/akohlmey/compile/lammps/src/KOKKOS/neigh_list_kokkos.h:21,
                 from /home/akohlmey/compile/lammps/src/KOKKOS/neighbor_kokkos.h:19,
                 from /home/akohlmey/compile/lammps/src/KOKKOS/pair_kokkos.h:24,
                 from /home/akohlmey/compile/lammps/src/KOKKOS/pair_dpd_fdt_energy_kokkos.h:31,
                 from /home/akohlmey/compile/lammps/src/KOKKOS/fix_rx_kokkos.h:27,
                 from /home/akohlmey/compile/lammps/src/KOKKOS/fix_rx_kokkos.cpp:15:
/home/akohlmey/compile/lammps/lib/kokkos/core/src/impl/Kokkos_FunctorAdapter.hpp: In instantiation of ‘static void Kokkos::Impl::FunctorValueJoin<FunctorType, ArgTag, T&, Enable>::join(const FunctorType&, volatile void*, const volatile void*) [with FunctorType = LAMMPS_NS::FixRxKokkos<Kokkos::OpenMP>; ArgTag = LAMMPS_NS::Tag_FixRxKokkos_solveSystems<true>; T = LAMMPS_NS::s_CounterType; Enable = void]’:
/home/akohlmey/compile/lammps/lib/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:371:22:   required from ‘void Kokkos::Impl::ParallelReduce<FunctorType, Kokkos::RangePolicy<Traits ...>, ReducerType, Kokkos::OpenMP>::execute() const [with FunctorType = LAMMPS_NS::FixRxKokkos<Kokkos::OpenMP>; ReducerType = Kokkos::InvalidType; Traits = {Kokkos::OpenMP, LAMMPS_NS::Tag_FixRxKokkos_solveSystems<true>}]’
/home/akohlmey/compile/lammps/lib/kokkos/core/src/Kokkos_Parallel_Reduce.hpp:877:20:   required from ‘static void Kokkos::Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::execute(const string&, const PolicyType&, const FunctorType&, ReturnType&) [with PolicyType = Kokkos::RangePolicy<Kokkos::OpenMP, LAMMPS_NS::Tag_FixRxKokkos_solveSystems<true> >; FunctorType = LAMMPS_NS::FixRxKokkos<Kokkos::OpenMP>; ReturnType = LAMMPS_NS::s_CounterType; std::string = std::__cxx11::basic_string<char>]’
/home/akohlmey/compile/lammps/lib/kokkos/core/src/Kokkos_Parallel_Reduce.hpp:1020:76:   required from ‘typename std::enable_if<Kokkos::is_execution_policy<T>::value>::type Kokkos::parallel_reduce(const PolicyType&, const FunctorType&, ReturnType&) [with PolicyType = Kokkos::RangePolicy<Kokkos::OpenMP, LAMMPS_NS::Tag_FixRxKokkos_solveSystems<true> >; FunctorType = LAMMPS_NS::FixRxKokkos<Kokkos::OpenMP>; ReturnType = LAMMPS_NS::s_CounterType; typename std::enable_if<Kokkos::is_execution_policy<T>::value>::type = void]’
/home/akohlmey/compile/lammps/src/KOKKOS/fix_rx_kokkos.cpp:1657:28:   required from ‘void LAMMPS_NS::FixRxKokkos<DeviceType>::solve_reactions(int, bool) [with DeviceType = Kokkos::OpenMP]’
/home/akohlmey/compile/lammps/src/KOKKOS/fix_rx_kokkos.cpp:2287:16:   required from here
/home/akohlmey/compile/lammps/lib/kokkos/core/src/impl/Kokkos_FunctorAdapter.hpp:1586:5: warning: implicit dereference will not access object of type ‘volatile LAMMPS_NS::s_CounterType’ in statement
 1586 |     *((volatile T*)lhs) += *((const volatile T*)rhs);
      |     ^
/home/akohlmey/compile/lammps/lib/kokkos/core/src/impl/Kokkos_FunctorAdapter.hpp: In instantiation of ‘static void Kokkos::Impl::FunctorValueJoin<FunctorType, ArgTag, T&, Enable>::join(const FunctorType&, volatile void*, const volatile void*) [with FunctorType = LAMMPS_NS::FixRxKokkos<Kokkos::OpenMP>; ArgTag = LAMMPS_NS::Tag_FixRxKokkos_solveSystems<false>; T = LAMMPS_NS::s_CounterType; Enable = void]’:
/home/akohlmey/compile/lammps/lib/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:371:22:   required from ‘void Kokkos::Impl::ParallelReduce<FunctorType, Kokkos::RangePolicy<Traits ...>, ReducerType, Kokkos::OpenMP>::execute() const [with FunctorType = LAMMPS_NS::FixRxKokkos<Kokkos::OpenMP>; ReducerType = Kokkos::InvalidType; Traits = {Kokkos::OpenMP, LAMMPS_NS::Tag_FixRxKokkos_solveSystems<false>}]’
/home/akohlmey/compile/lammps/lib/kokkos/core/src/Kokkos_Parallel_Reduce.hpp:877:20:   required from ‘static void Kokkos::Impl::ParallelReduceAdaptor<PolicyType, FunctorType, ReturnType>::execute(const string&, const PolicyType&, const FunctorType&, ReturnType&) [with PolicyType = Kokkos::RangePolicy<Kokkos::OpenMP, LAMMPS_NS::Tag_FixRxKokkos_solveSystems<false> >; FunctorType = LAMMPS_NS::FixRxKokkos<Kokkos::OpenMP>; ReturnType = LAMMPS_NS::s_CounterType; std::string = std::__cxx11::basic_string<char>]’
/home/akohlmey/compile/lammps/lib/kokkos/core/src/Kokkos_Parallel_Reduce.hpp:1020:76:   required from ‘typename std::enable_if<Kokkos::is_execution_policy<T>::value>::type Kokkos::parallel_reduce(const PolicyType&, const FunctorType&, ReturnType&) [with PolicyType = Kokkos::RangePolicy<Kokkos::OpenMP, LAMMPS_NS::Tag_FixRxKokkos_solveSystems<false> >; FunctorType = LAMMPS_NS::FixRxKokkos<Kokkos::OpenMP>; ReturnType = LAMMPS_NS::s_CounterType; typename std::enable_if<Kokkos::is_execution_policy<T>::value>::type = void]’
/home/akohlmey/compile/lammps/src/KOKKOS/fix_rx_kokkos.cpp:1659:28:   required from ‘void LAMMPS_NS::FixRxKokkos<DeviceType>::solve_reactions(int, bool) [with DeviceType = Kokkos::OpenMP]’
/home/akohlmey/compile/lammps/src/KOKKOS/fix_rx_kokkos.cpp:2287:16:   required from here
/home/akohlmey/compile/lammps/lib/kokkos/core/src/impl/Kokkos_FunctorAdapter.hpp:1586:5: warning: implicit dereference will not access object of type ‘volatile LAMMPS_NS::s_CounterType’ in statement
```

**Comment by stanmoore1** [comment]
Will take a look

**Comment by stanmoore1** [comment]
@akohlmey that warning from `volatile` in `fix_rx_kokkos` should be fixed in https://github.com/lammps/lammps/pull/3100/commits/5d28d06a3c87c2b571beb5d797000b9619f17618.

**Pull request merged**
