### PR TITLE
add new pair potential for metal-organic interactions - pair style momb

### PR DESCRIPTION
**Pull request by tonnamb**
Hi,

Our lab created a new potential for metal-organic interactions.
We have been using it in our lab for 2-3 years, so it has matured and we would like to contribute it to the main repository.

Description of the potential can be found in:
http://pubs.acs.org/doi/abs/10.1021/jp412098n
Zhou, Ya, Wissam A. Saidi, and Kristen A. Fichthorn. "A force field for describing the polyvinylpyrrolidone-mediated solution-phase synthesis of shape-selective Ag nanoparticles." The Journal of Physical Chemistry C 118, no. 6 (2014): 3366-3374.

I wouldn't mind putting together a documentation for this potential.

Thanks!
Tonnam

### CODE REVIEW

**Comment by tonnamb** [comment]
Thanks for your feedbacks and comments Axel. I had made some progress, but have not finished writing out the documentations yet.

**Comment by akohlmey** [comment]
made a few more small changes that don't change code. sorry about the accidental additional commits. i've reverted them and moved them to the proper branch. my bad. not enough coffee, i guess.
overall, this looks ready for inclusion now. 

thanks again for your contribution.

**Comment by tonnamb** [comment]
No worries and thanks you for your small changes!
I'm planning to add some more details into the documentation and ask my advisor to look at the documentation before we merge this pull request.

**Comment by akohlmey** [comment]
OK. then i am unassigning steve (which is our signal to have it merged) and put myself back in charge until you tell me you the branch is ready. if you need some motivation for your adviser: we're about to release the next stable version, which would make your pair style visible to a larger audience immediately. the release candidate is scheduled for tomorrow at the latest. unless some showstopper level bug surfaces.

**Comment by tonnamb** [comment]
Hi @akohlmey,
My advisor looked through the documentation and we decided to change the pair_style name to 'momb' instead of 'zhou'. I have commit and push all changes to this branch, so it is ready for merge if you have no other change. Thanks!

**Comment by akohlmey** [comment]
ok. i've made a few more cosmetic and administrative changes. specifically, i added the reference paper to be printed into the cite.log file and consolidated the reference example to follow standard conventions closer. this should be ready to merge.
nicely done. thank you.

**Comment by tonnamb** [comment]
Thank you @akohlmey for your edits. They look good to me.

**Pull request merged**
