### PR TITLE
Add feature to transparently download external potential files when packages are enabled

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

Add a feature to both, the conventional and CMake based build processes that allows to unbundle (large) potential files from the git repo and source archives and download them on demand when the corresponding package is enabled. In addition to the filename, an MD5 hash is stored so that those files are downloaded only once if the hash matches. This way we will fetch the file that was current at any time, so switching to an older version of LAMMPS would fetch an older version of the potential, in case there is a difference.

**Related Issues**

#1839 

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues.

**Implementation Notes**

The information is stored in files "potentials.txt" in each package folder, which are parsed by either build system so the information is consistent across those. Also other parts of the code, e.g. input examples, could be handled in a similar fashion and the current scheme easily expanded.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by sjplimp** [comment]
@akohlmey A few Qs ...
a) the download happens the first time a user builds with the package installed?
b) nothing about the content of the potential file itself (e.g. header) is altered to work in this mode?
c) the potential file is added to the potentials dir?  what happens if one already exists, e.g. an older version of the same file?

Assuming b,c are ok, this seems like a good way to do this.  For (a) Is there a way to trigger this not on a build, but maybe by a specific "make" request, i.e. new target?  I imagine not everyone wants to grab the 100 MB nanotube potential, just b/c they build with USER-MISC.

**Comment by akohlmey** [comment]
> @akohlmey A few Qs ...
> a) the download happens the first time a user builds with the package installed?
it is downloaded during `make yes-<package>` or `cmake -D PKG_<PACKAGE>=yes`
so *before* actually compiling.

> b) nothing about the content of the potential file itself (e.g. header) is altered to work in this mode?

correct.

> c) the potential file is added to the potentials dir? what happens if one already exists, e.g. an older version of the same file?

it will be overwritten. also when you check out an older branch where the hash is different, it will synchronize to the current hash.

> Assuming b,c are ok, this seems like a good way to do this. For (a) Is there a way to trigger this not on a build, but maybe by a specific "make" request, i.e. new target?

that is conflicting with the philosophy of having this happening in a transparent fashion.
making that one more step just increases the chances that people make mistakes (and/or complain and/or forget).

> I imagine not everyone wants to grab the 100 MB nanotube potential, just b/c they build with USER-MISC.

that is true. it is not that bad, though. even on my rather slow internet link at home the delay is not as bad. but i agree that having this in USER-MISC, which has so many different things, is not a good idea with the download anymore. i would rather then move the pair style to a different folder, e.g. together with the fortran version of the same kind of potential, which we will need to set up the download of their potentials as well.

**Comment by sjplimp** [comment]
@akohlmey ok, I like the idea of having any pair style (or group or them) that uses this be in its own package - so the PR is good to go from my perspective

**Comment by akohlmey** [comment]
> @akohlmey ok, I like the idea of having any pair style (or group or them) that uses this be in its own package - so the PR is good to go from my perspective

@sjplimp i am already moving the pair style into the upcoming USER-MESONT package folders (and update src/Makefile, cmake/CMakeLists.txt and its doc file), but to minimize merge conflicts will finish the integration once we merge the (more general) fortran version of the same potential. Then I will also add some comment to the package description explaining that the potential files will be downloaded during installation of the package.

**Pull request merged**
