### PR TITLE
Step up cmake required version to support CMAKE_CXX_STANDARD

### PR DESCRIPTION
**Pull request by giacomofiorin**
**Summary**

`CMAKE_CXX_STANDARD` is not supported by CMake versions prior to 3.1. The C++11 test does not add the relevant compiler flag, and setting manually `-DCMAKE_CXX_STANDARD=11` raises a warning about the variable being unused.

It is still possible, though less portable, to enforce C++ standard via `CXXFLAGS`.

Error found on CentOS 7.7 with `cmake` 2.8.12 (RPM repository version).

**Author(s)**

@giacomofiorin 

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Fix.

**Implementation Notes**

Single-line change from `2.8.12` to `3.1.3`.

**Post Submission Checklist**

- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by junghans** [comment]
A higher CMake version would allow for some CMake beatification in general.

**Comment by akohlmey** [comment]
For the next stable release we are looking at RHEL/CentOS 7.x as a point of reference for minimum requirements to compile out of the box (its C++ compiler needs a flag to enable C++11 compatibility, it is not enabled by default). The previous stable releases were aimed to be compatible with RHEL/CentOS 6.x. For that we didn't look at CMake compatibility at all, but 2.8.12 seemed a reasonable minimal choice.

So to keep full out-of-the-box compatibility with RHEL/CentOS 7.x we should remain compatible with cmake 2.8.12; at least for the minimal base compilation. Add-on packages may require higher versions (as they may require higher minimum C++ standard compatibility). So at the moment we should probably revert any changes in the base CMake configuration script that are not compatible with version 2.8.12.

Or we should make an "executive decision" that we CMake compatibility requires a newer version and then we should set the minimum requirement to was is the lowest version among popular Linux distributions, e.g. RHEL/CentOS 8.x, Ubuntu 18LTS (or Ubuntu 16LTS?).

@sjplimp @rbberger any opinions on this?

**Comment by akohlmey** [comment]
@giacomofiorin this seems to contain changes from #1724, too.

**Comment by akohlmey** [comment]
@giacomofiorin I've gone and tested this on a clean CentOS 7 container, and if you follow the documentation, the CMake file is compliant with CMake version 2.8.12. The **documented** way to get around the pre-processor test is to set the variable `DISABLE_CXX11_REQUIREMENT` to true or to set the compiler flags to enable C++11 compatibility. I propose that we augment the documentation to make this more explicit as follows. The fact that a manual step is needed at this point for distributions like CentOS 7 is deliberate. We **want** to get the feedback (or blow back?). If we decide to require C++11 at the next stable release, we will change the preprocessor code to no longer allow to work around it and will also change the CMake script to turn on C++11 compatibility where supported. 

```
  diff --git a/doc/src/Build_settings.txt b/doc/src/Build_settings.txt
  index c40a91d78..a83ab4c52 100644
  --- a/doc/src/Build_settings.txt
  +++ b/doc/src/Build_settings.txt
  @@ -38,11 +38,16 @@ when calling CMake.
   
   [CMake variable]:
   
  --D DISABLE_CXX11_REQUIREMENT=yes
  +-D DISABLE_CXX11_REQUIREMENT=yes :pre
  +
  +You can set additional C++ compiler flags (beyond those selected by CMake)
  +through the CMAKE_CXX_FLAGS variable. Example for CentOS 7:
  +
  +-D CMAKE_CXX_FLAGS="-std=c++11" :pre
   
   [Makefile.machine setting]:
   
  -LMP_INC = -DLAMMPS_CXX98
  +LMP_INC = -DLAMMPS_CXX98 :pre
   
   :line


```

**Comment by sjplimp** [comment]
Fine by me.  No strong opinions.

**Comment by giacomofiorin** [comment]
@akohlmey I removed the spurious commits (sorry).

**Comment by akohlmey** [comment]
As points of reference: cmake3 (in version 3.14) is available for CentOS7 via EPEL, CentOS8 ships with CMake 3.11 and Ubuntu 18.04 has CMake 3.10. So if we want to cut ties with plain CentOS7 (w/o EPEL), then we should set the minimum CMake version required to 3.10.

But as mentioned before, at the current state of affairs, there is no need (yet) to make that change. Also automatic adding of `-std=c++11` for gcc versions that do support it, but have it not enabled by default could be easily added with CMake 2.8.12 compatible script code.

**Comment by giacomofiorin** [comment]
Thanks for the clarification.  It was actually not clear to me that the addition of `-std=c++11` is left to the user depending on the CMake version.

A couple of observations (since the change is meant to raise feedback).
1. The documentation explains that the build system checks if C++11 is "available or enabled". If it is required sometimes by the user to explicitly turn it on, maybe it should just be "enabled"?
2. A common scenario is using a more recent CMake than 2.8 because of other packages' requirements; those versions will silently turn on the C++11 compiler flag for e.g. GCC 4.8, but 2.8.12 won't.  This is confusing, given that the first line of `CMakeLists.txt` is the required version.

If you propose to extend the functionality of 2.8.12 via script to make it consistent with more recent versions, that sounds more reasonable than cutting off ties with base CentOS.  That would invalidate this PR, so please close it if the final decision is to keep supporting 2.8.12.

**Comment by junghans** [comment]
I added a bit of workaround for <CMake-3.1 in e26da83, however that will only work for some compilers not all, for full support we need to do something like: https://github.com/laristra/cinch/blob/master/cmake/cxx11.cmake

I feel, we should ultimately bump the CMake version to 3.10, maybe first having CMake-3.10 being a soft requirement and have users report back similar to #1659 and then make it hard after a while.

I remember that we downgraded from CMake-3.1 to CMake-2.8 due to that fact that some users found it confusing to type `cmake3` instead `cmake`.

**Comment by akohlmey** [comment]
for the time being, we get consistent behavior by simply commenting out the code that behaves differently on newer CMake versions, as done in commit https://github.com/lammps/lammps/pull/1721/commits/4aa47386ea209175f3fd53284d5ff1e4185c77a9

The way I think we should proceed is: first decide on whether we want to require C++11 after the next stable release (for that one the current test in `lmptype.h` would be removed again, and then afterwards the option to avoid it would be removed). What the minimum CMake versions should be we can decide after that in the next development cycle as well. Requiring CMake 3.x makes sense, if we can document how to get alternatives. Since there are many projects already depending on CMake 3.x, we can assume, that it would be available in all (well managed) supercomputing centers and for home users, it is already available (for CentOS 7 we should document that it is available through EPEL). At that point requiring version 3.10 seems the reasonable choice and then we can review how to improve and simplify and clean up CMake support in the next development cycle, too.

For that purpose, i have created a new issue pointing to this discussion, so this pull request can be closed and a new one submitted when the time is right.

**Pull request closed without merging**
