### PR TITLE
Pull request for USER-SELM 

### PR DESCRIPTION
**Pull request by atzberg**
**Summary**

This is a pull-request associated with the USER-SELM Package for Fluctuating Hydrodynamics simulations in LAMMPS.  This includes Stochastic Eulerian Lagrangian Methods (SELMs) for fluid-structure interactions subject to thermal fluctuations.  This pull-request relates to incorporating the codes into the latest version of LAMMPS.   This includes a collection of time-step integrators that couple particles to stochastic continuum fluid equations.  This also includes integration with shearing boundary conditions (Lees-Edwards) for rheological studies.

**Related Issue(s)**

The codes have been further developed and re-factored to use a library interface for integration directly in the LAMMPS distribution.  A previous version of the package was distributed as an external package.

**Author(s)**

Paul J. Atzberger
University of California Santa Barbara
http://atzberger.org
atzberg@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

N/A

**Implementation Notes**

Library interface developed for SELM methods.  Shear boundary conditions in hydrodynamics solver now are better integrated with LAMMPS domain shearing.  New examples are now included with the package.  The documentation files and README.rst have been updated and included with package information.

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

Additional information on the SELM project can be found at
http://mango-selm.org

### CODE REVIEW

**Comment by atzberg** [comment]
added missing file

**Review by atzberg — COMMENTED** [review]
added missing file

**Comment by akohlmey** [comment]
@atzberg before you continue working on this branch, please note that your pull request in its current form is unusable because it reverts many changes to the upstream version. This is possibly caused by importing files based on an older snapshot unconditionally.
What you have to do is to update the branch "master" in your fork from upstream to the current version, then create a new feature branch and then transfer **only** the changes pertinent to your package (usually that will be mostly new files plus a few changes to "infrastructure" files (e.g. src/.gitignore), the CMake/GNUmake build systems, and the documentation overview files and finally submit this feature branch as a pull request. You can check beforehand whether this is correct by looking at `git diff master..HEAD`.
If you know exactly on which (patch/stable) release your branch is based you may also extract a diff and apply that to the feature branch.
Since I can only speculate on the procedure that got you here, I cannot give you more specific instructions. But if you look at the [changes introduced by your pull request](https://github.com/lammps/lammps/pull/2806/files) you see that there many changes included that are unrelated to your contribution.

**Comment by atzberg** [comment]
OK, thanks for letting me know.  I'll do a fresh branch from current lammps.git:master HEAD and then put in selm changes in that branch.

**Comment by atzberg** [comment]
Created a new branch building on the more up-to-date version of lammps.

**Pull request closed without merging**
