### PR TITLE
Temper_NPT

### PR DESCRIPTION
**Pull request by amilumas**
New function that allows for parallel tempering (replica exchange) in MD in LAMMPS in the isothermal-isobaric ensemble (NPT).
This is similar to temper which works in the canonical (NVT) ensemble.
An example in.temper_npt is included that uses temper_npt.

## Purpose

The addition temper_npt allows for parallel tempering (replica exchange) MD simulations in LAMMPS to be in the NPT ensemble. It uses the npt acceptance criteria for NPT given in
Mori, Y .; Okamoto, Y . Generalized-Ensemble Algorithms for the Isobaric–Isothermal Ensemble. J. Phys. Soc. Japan 2010, 79, 74003.

It works in a similar way as temper which is for the canonical (NVT) ensemble, temper_npt requires pressure to be input as an argument. The temper_npt function follows a similar syntax as temper:

temper_npt N M temp fix-ID seed1 seed2 pressure index(optional)

Refer to documentation for temper, the only difference with temper_npt is that the pressure is specified as the 7th argument. The 8th argument is the same optional index argument used in temper.

## Author(s)

Contributing Authors: Amulya K. Pervaje and Cody K. Addington
Affiliation: North Carolina State University
Contact Email: amulyapervaje@gmail.com

## Implementation Notes

The new acceptance criteria for NPT uses the following information about the two replicas that are attempting to switch: the potential energies, the temperatures, and the volumes as well as the pressure set point.
The equations for the acceptance criteria are:
equations

The probability of replica exchange from replica X to replica X' is either 1 or exp(-Delta(REM)), whichever is lower. The Delta(REM) expression is given in the equation where Beta is 1/(kB*T) where kB is the Boltzmann constant, E is potential energy, P is the pressure that is set, and V is volume.

An example that uses this temper_npt is attached in.temper_npt which uses data file data.peptide.

### CODE REVIEW

**Comment by akohlmey** [comment]
Thank you for your submission to LAMMPS. 
I have a few requests for changes:
- the new command should be named `temper/npt` to be consistent with the conventions used elsewhere
- the contributed code should be added to the `USER-MISC` package and not `REPLICA` since it is a user contributed single file command. this should be referred to in the docs and also determines the location of the example (example/USER/misc/temper_npt)
- a _requirement_ for inclusion is that you provide documentation for the manual. You are free to implement this by modifying `doc/src/temper.txt` or providing a separate `doc/src/temper_npt.txt` file.
that should also include corresponding formula and references to relevant publications.

as a point of reference, you can look at the `temper/grem` command, that is a similar contribution.

i have not looked closely at the code, but if the changes to `temper` are as small as your description makes it sound, you may consider implementing it rather as a class that is derived from Temper and just overrides its code where required via polymorphism. if that requires some small changes to temper.h or temper.cpp (e.g. making some additional methods virtual), that can be easily arranged. however, as the implementor, you are in a better position, if this suggestion has sufficient merit. as a maintainer, i prefer keeping the amount of redundant code to the minimum, but only if this is not making things to complex.
in the case of `temper/grem`, for example, the savings were too small.

a good way to include a reference of your publication into LAMMPS is to use the `citeme` class.
please see, for instance, the file src/USER-MISC/pair_momb.cpp, for how to do this. this will add
the embedded BibTex style reference into the citeme.log file.

**Comment by akohlmey** [comment]
@amilumas, would please provide some (written) feedback on my comments and suggestions? thanks.

**Comment by amilumas** [comment]
I'm going to submit the required information soon. I'll do it in the end of
the week or early next week.

I'm going to follow your suggestion and submit it to the appropriate places
you have listed.. (USER-MISC)
for the code which I'll rename temper/npt instead of temper_npt to keep
with LAMMPS style.

I think it's best to keep this code separate from temper as they have very
different acceptance criteria and are used for different cases that may be
too subtle to implicitly assume.

I'm going to make a documentation for temper/npt. One question I had is
that the paper I cited in the original pull request was just the source for
the acceptance criteria. We did not write that paper. I just included that
reference for the acceptance criteria equation. We are in the process of
submitting a paper in which we used this new temper/npt functionality but
it has not yet been submitted.

Thanks,
Amulya

**Comment by akohlmey** [comment]
it does not matter whether you wrote a paper or not. if it is a core part of the algorithm you implemented, it should be cited, so that people looking up the docs (or the log.cite file) can read up on the theory behind the code.

**Comment by akohlmey** [comment]
BTW: you do not have to submit a new pull request. just commit the changes to the same branch and push it to github. the pull request will then be automatically updated.

**Comment by amilumas** [comment]
Okay, I'll make sure to cite in that way. I'll have my co-contributer look
over my materials and commit the changes.

Thanks

-Amulya

**Comment by akohlmey** [comment]
Thanks for the updates. I've made some additional adjustments and cleaned up a few things to be more in line with LAMMPS conventions and also to integrate the new commands fully into the manual and related files and lists. I think this is now ready to be included into the regular LAMMPS distribution.

**Pull request merged**
