### PR TITLE
add extract() function to few angle and bond styles 

### PR DESCRIPTION
**Pull request by evoyiatzis**
**Summary**

Add or expand extract() method to bond class2, angle class2/p6, angle cosine/buck/6d, bond morse, bond nonlinear, angle cross, angle amoeba, angle mesocnt, angle gaussian and bond gaussian

**Related Issue(s)**

No issues

**Author(s)**

E. Voyiatzis at NovaMechanics Ltd - email [evoyiatzis@gmail.com](mailto:evoyiatzis@gmail.com)

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

It will not break backward compatibility

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

### CODE REVIEW

**Comment by evoyiatzis** [comment]
Is there a yaml file for unit test of angle_style cosine/buck6d? I cannot find one in the unittest/force-styles/tests/ folder.

**Comment by akohlmey** [comment]
> Is there a yaml file for unit test of angle_style cosine/buck6d? I cannot find one in the unittest/force-styles/tests/ folder.

Not all styles have tests. Some cannot be tested this way, some require some work, some are simply not yet done.
WYSIWYG!

**Review by sjplimp — APPROVED** [review]

**Comment by evoyiatzis** [comment]
bond_style mesocnt inherits from bond harmonic so I guess it does not require an extract () method right?

**Comment by sjplimp** [comment]
@akohlmey Why does bond harmonic derive from bond mesocnt - that seems illogical on the face of it.

**Comment by evoyiatzis** [comment]
> @akohlmey Why does bond harmonic derive from bond mesocnt - that seems illogical on the face of it.

@akohlmey  @sjplimp 
My bad ! Indeed it is mesocnt that it is derived from harmonic

**Comment by sjplimp** [comment]
No, I mistyped - I saw that bond mesocnt derives from bond harmonic. 
However:
(a) Normally this would be a bond harmonic/mesocnt command, not bond mesocnt, to indicate the derivation.
(b) The doc page is incomplete - it doesn't say how the chiral indices n,m are used to alter the harmonic formula.
      I assume they alter K, but it should be explained.
(c) I think a better way to implement this would to use it with bond hybrid:
     Use standard bond harmonic for bond types that are "custom"
     Use bond harmonic/mesocnt for bond types that are "C", and drop the "C or custom" param

Steve

**Comment by akohlmey** [comment]
> @akohlmey Why does bond harmonic derive from bond mesocnt - that seems illogical on the face of it.

@sjplimp That is not what @evoyiatzis wrote. You switched it around. Apparently bond style mesocnt is a harmonic bond with a different way to enter its parameters.

@evoyiatzis You are correct. The mesocnt bond style uses all the functionality from bond style harmonic except for how to enter the parameters, so the extract function does not need to be re-implemented. It makes little sense in the context of such a model anyway. It would make more sense to export the unit conversion factor (eunit), but that is a local variable...

**Comment by sjplimp** [comment]
@akohlmey I did switch it around by accident.  What I meant by illogical is that the name of the mesocnt style is not harmonic/mesocnt - see (a) in my 2nd comment.

**Comment by akohlmey** [comment]
> @akohlmey I did switch it around by accident. What I meant by illogical is that the name of the mesocnt style is not harmonic/mesocnt - see (a) in my 2nd comment.

It is not going to be changed in this pull request. You need to contact the MESOCNT style author.
I personally, don't see much harm in this choice: it is in a package, it is only of use with other styles of that package, it has a unique behavior in the input, there is no value for any use beyond this package, so its inheritance is a minor concern.

**Pull request merged**
