### PR TITLE
Enable fix property/atom to create custom arrays

### PR DESCRIPTION
**Pull request by sjplimp**
**Summary**

Enhance fix property/atom to allow creation custom per-atom arrays, not just vectors,
with an i2_name, d2_name syntax.  In addition to custom vectors with an i_name, d_name syntax.
This includes additional data structures in atom.cpp/h.  And enabling other commands to work with 
either custom vectors or arrays: dump custom, compute property/atom, set, fix store/state, etc.
Also to allow the arrays to be extracted through the lib interface, via atom->extract().

**Related Issues**

**Author(s)**

Steve

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

Should be N/A.  Except that some error checking will be added to fix property/atom and fix store/state when restarting, which will change the restart file format if those commands are used.

**Implementation Notes**

**Post Submission Checklist**

- [ ] The feature or features in this pull request is complete
- [ ] Licensing information is complete
- [ ] Corresponding author information is complete
- [ ] The source code follows the LAMMPS formatting guidelines
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] The added/updated documentation is integrated and tested with the documentation build system
- [ ] The feature has been verified to work with the conventional build system
- [ ] The feature has been verified to work with the CMake based build system
- [ ] Suitable tests have been added to the unittest tree.
- [ ] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

### CODE REVIEW

**Comment by sjplimp** [comment]
There are a few styles in packages that use custom per-atom data which still need to be updated.
Also @stanmoore1 there is a Kokkos version of fix property/atom which will likely need to be upgraded to match the new CPU version.  Likewise additions to the custom per-atom data structs in atom.h if that is mirrored by Kokkos.  Also some error checking still needs to be added.

**Comment by sjplimp** [comment]
@stanmoore1 I think the Kokkos version of fix property/atom now needs to be updated to support custom per-atom arrays and not just vectors.

**Comment by stanmoore1** [comment]
@sjplimp I was going to work on the Kokkos changes for this but there are a bunch of merge conflicts. I think you understand the changes better than me, so maybe easier for you to fix the conflicts?

**Comment by stanmoore1** [comment]
@sjplimp I ported the changes to Kokkos and it compiles on my local box. I'm running full Kokkos regression testing now.

**Comment by stanmoore1** [comment]
> @sjplimp I ported the changes to Kokkos and it compiles on my local box. I'm running full Kokkos regression testing now.

Actually the regression tests can't compile since we renamed many of the packages, so we'll need to fix merge conflicts and merge in master before I can test.

**Comment by sjplimp** [comment]
working on fixing the conflicts - more work than I anticipated

**Comment by sjplimp** [comment]
working on fixing the conflicts - more work than i anticipated

**Comment by stanmoore1** [comment]
> working on fixing the conflicts - more work than I anticipated

Yeah they looked pretty nasty, let me (or perhaps @akohlmey) know if you need help

**Comment by stanmoore1** [comment]
@sjplimp FYI I think all the Kokkos changes are finished for this PR, but haven't yet been able full Kokkos regression tests until the merge conflicts are resolved.

**Comment by sjplimp** [comment]
@akohlmey got everything to compile after fully syncing with current master.  Look for OLDSTLYE in several src files - this is where I assume changes still may need to be made.

**Comment by sjplimp** [comment]
@akohlmey Also, I need to do some retesting that no new functionality got broken.

**Comment by stanmoore1** [comment]
I'm running this through Kokkos regression testing now.

**Comment by akohlmey** [comment]
> I'm running this through Kokkos regression testing now.

Don't bother. There are still known problems and pending updates from me.

**Comment by stanmoore1** [comment]
Alright, let me know when.

**Comment by akohlmey** [comment]
@sjplimp this is ready for you to continue. It looks like write_data and possibly also read_data are broken. I get a segfault in the corresponding unit test and I am not certain whether restarts were tested at the point where the unit test aborts.

**Comment by akohlmey** [comment]
@stanmoore1 this now passes the automatic and extended regression and unit tests and I have no more changes pending or known bugs. So "when" is now unless @sjplimp has some more changes or finds other bugs.

**Comment by stanmoore1** [comment]
I'm seeing some of the DPD-REACT regression tests segfault failing with Kokkos, need to debug.

**Comment by sjplimp** [comment]
@akohlmey ok, I thnk this is good to go.  I clarified the doc pages to make it simpler - exact match only
@stanmoore1 you may want to re-check that Kokkos versions of this still work

**Comment by stanmoore1** [comment]
I fixed the segfault with Kokkos. Running regression tests now.

**Comment by stanmoore1** [comment]
Regression tests passed, this PR is ready to merge from my point of view.

**Review by stanmoore1 — APPROVED** [review]

**Review by akohlmey — APPROVED** [review]

**Pull request merged**
