### PR TITLE
Collected small changes for the next patch release

### LINKED ISSUE #2208: LAMMPS docs only builds with enchant installed
**Summary**

Since https://github.com/lammps/lammps/commit/97b11ea746d283a4996c00df0bda8f784cfceb42 the LAMMPS docs can only be built with `enchant` installed. It is no longer optional, because the extension is installed in the venv and thus configured. I would revert to the previous behavior as it causes more problems than it solves or add a better check for detecting the C library.

**LAMMPS Version and Platform**

current master

**Expected Behavior**

Build documentation, e.g. HTML only output.

**Actual Behavior**

```
make html
....
Extension error:
Could not import extension sphinxcontrib.spelling (exception: The 'enchant' C library was not found and maybe needs to be installed.
See https://pyenchant.github.io/pyenchant/install.html
for details
)
```

**Steps to Reproduce**

**Further Information, Files, and Links**

### LINKED ISSUE #2213: [BUG] LAMMPS Exceptions throw lethal signals to python
v**Summary**

LAMMPS Exceptions is meant to not kill the calling code.
LAMMPS kills the calling code.

**LAMMPS Version and Platform**

The LAMMPS Versions are in the output.
The Platforms are listed in the io below

**Expected Behavior**

Red Hat 7.1
Traditional Make
```
$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lammps import lammps
>>> lmp = lammps()
LAMMPS (19 Mar 2020)
>>> lmp.command("units metal")
>>> lmp.command("units meta")
ERROR: Illegal units command (../update.cpp:292)
Last command: units meta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/anaconda3/lib/python3.7/site-packages/lammps.py", line 333, in command
    raise Exception(error_msg)
Exception: ERROR: Illegal units command (../update.cpp:292)
```

**Actual Behavior**

2019 MacBook OS 10.14.6
CMake build
```
$ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from lammps import lammps
>>> lmp = lammps()
LAMMPS (15 Jun 2020)
>>> lmp.command("units metal")
>>> lmp.command("units meta")
ERROR: Illegal units command (src/update.cpp:292)
Last command: units meta
[s1048312:97786] *** Process received signal ***
[s1048312:97786] Signal: Segmentation fault: 11 (11)
[s1048312:97786] Signal code: Address not mapped (1)
[s1048312:97786] Failing at address: 0x0
[s1048312:97786] [ 0] 0   libsystem_platform.dylib            0x00007fff7a31ab5d _sigtramp + 29
[s1048312:97786] [ 1] 0   ???                                 0x0000000000000007 0x0 + 7
[s1048312:97786] [ 2] 0   liblammps.dylib                     0x000000010d2302c8 lammps_get_last_error_message + 168
[s1048312:97786] [ 3] 0   libffi.6.dylib                      0x000000010c93d884 ffi_call_unix64 + 76
[s1048312:97786] [ 4] 0   ???                                 0x00007ffee37b6830 0x0 + 140732714936368
[s1048312:97786] *** End of error message ***
Segmentation fault: 11
```
or

Dell Desktop Machine Ubuntu 18.04.2
Traditional Make
```
$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lammps import lammps
>>> lmp = lammps()
LAMMPS (30 Jun 2020)
>>> lmp.command("units metal")
>>> lmp.command("units meta")
ERROR: Illegal units command (../update.cpp:292)
Last command: units meta
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[tnt4:19196] *** Process received signal ***
[tnt4:19196] Signal: Aborted (6)
[tnt4:19196] Signal code:  (-6)
[tnt4:19196] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f05fde7b890]
[tnt4:19196] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f05fdab6e97]
[tnt4:19196] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f05fdab8801]
[tnt4:19196] [ 3] /home/username/anaconda3/bin/../lib/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0xbc)[0x7f05f1e7384a]
[tnt4:19196] [ 4] /home/username/anaconda3/bin/../lib/libstdc++.so.6(+0xabf47)[0x7f05f1e71f47]
[tnt4:19196] [ 5] /home/username/anaconda3/bin/../lib/libstdc++.so.6(+0xabf7d)[0x7f05f1e71f7d]
[tnt4:19196] [ 6] /home/username/anaconda3/bin/../lib/libstdc++.so.6(__cxa_rethrow+0x0)[0x7f05f1e7215a]
[tnt4:19196] [ 7] /home/username/anaconda3/bin/../lib/libstdc++.so.6(_ZSt19__throw_logic_errorPKc+0x35)[0x7f05f1e6ef67]
[tnt4:19196] [ 8] /home/username/anaconda3/lib/python3.7/site-packages/liblammps.so(lammps_get_last_error_message+0xb5)[0x7f05f0dc07f5]
[tnt4:19196] [ 9] /home/username/anaconda3/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c)[0x7f05fc36aec0]
[tnt4:19196] [10] /home/username/anaconda3/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call+0x22d)[0x7f05fc36a87d]
[tnt4:19196] [11] /home/username/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce)[0x7f05fe0d8f7e]
[tnt4:19196] [12] /home/username/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(+0x139b4)[0x7f05fe0d99b4]
[tnt4:19196] [13] python(_PyObject_FastCallKeywords+0x49b)[0x55bc3d92ad2b]
[tnt4:19196] [14] python(_PyEval_EvalFrameDefault+0x537e)[0x55bc3d9867ae]
[tnt4:19196] [15] python(_PyFunction_FastCallKeywords+0xfb)[0x55bc3d92979b]
[tnt4:19196] [16] python(_PyEval_EvalFrameDefault+0x6a0)[0x55bc3d981ad0]
[tnt4:19196] [17] python(_PyEval_EvalCodeWithName+0x2f9)[0x55bc3d8c74f9]
[tnt4:19196] [18] python(PyEval_EvalCodeEx+0x44)[0x55bc3d8c83c4]
[tnt4:19196] [19] python(PyEval_EvalCode+0x1c)[0x55bc3d8c83ec]
[tnt4:19196] [20] python(+0x22f874)[0x55bc3d9e0874]
[tnt4:19196] [21] python(+0xf5da8)[0x55bc3d8a6da8]
[tnt4:19196] [22] python(PyRun_InteractiveLoopFlags+0xf3)[0x55bc3d8a6f5e]
[tnt4:19196] [23] python(+0xf5ffe)[0x55bc3d8a6ffe]
[tnt4:19196] [24] python(+0xf6a88)[0x55bc3d8a7a88]
[tnt4:19196] [25] python(_Py_UnixMain+0x3c)[0x55bc3d9ebf7c]
[tnt4:19196] [26] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f05fda99b97]
[tnt4:19196] [27] python(+0x1e0122)[0x55bc3d991122]
[tnt4:19196] *** End of error message ***
Aborted (core dumped)
```

**Steps to Reproduce**

```
$ python
>>> from lammps import lammps
>>> lmp = lammps()
>>> lmp.command("units meta")
```

**Further Information, Files, and Links**

I apologize for running the tests on three separate machines. If the solution is not clear, I will hunt down the problematic commit on Monday.

### PR DESCRIPTION
**Pull request by akohlmey**
**Summary**

This pull request contains assorted small changes that do not warrant a pull request of their own.

**Author(s)**

Axel Kohlmeyer, Temple U

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No known issues

**Implementation Notes**

The following individual changes are included:
- Fix bug in `slope()` function for too long vectors due to integer overflows
- Remove mentions of specific dump styles from the command overview
- Add reverse engineered documentation page for `compute smd/ulsph/effm`
- Force `LAMMPS_POTENTIALS` environment variable for unit tests accessing potential files
- Silence some compiler warnings in KOKKOS headers
- expand testing of functions in utils namespace
- make potential name in PotentialFileReader error messages consistent with pair style
- remove hard dependency on enchant library for doc builds. This fixes #2208 
- fix bug in compute gyration/shape/chunk, that did not update the number of local array rows
- flag an error when trying to apply the `ave()` variable function to an empty vector
- fix a bug in the library interface exception handling that was passing a NULL pointer instead of an empty string. This closes #2213
- fix bug in compute property/atom that would output shape parameters are radii instead of diameters as documented
- avoid segfault when using the `log` command without arguments.

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system

### CODE REVIEW

**Comment by stanmoore1** [comment]
@akohlmey can you add this change to clarify this error message:

```diff
diff --git a/src/pair_hybrid.cpp b/src/pair_hybrid.cpp
index b0def60..375ff8c 100644
--- a/src/pair_hybrid.cpp
+++ b/src/pair_hybrid.cpp
@@ -434,7 +434,7 @@ void PairHybrid::coeff(int narg, char **arg)
   if (!allocated) allocate();
 
   if (lmp->kokkos)
-    error->all(FLERR,"Cannot yet use pair hybrid with Kokkos");
+    error->all(FLERR,"Must use pair_style hybrid/kk with Kokkos");
 
   int ilo,ihi,jlo,jhi;
   force->bounds(FLERR,arg[0],atom->ntypes,ilo,ihi);
```

**Comment by akohlmey** [comment]
> @akohlmey can you add this change to clarify this error message:
> 

done in https://github.com/lammps/lammps/pull/2205/commits/f598ae7ebfd70e3657286fd9ea4afbe25e8ce11f
please note that hybrid/overlay didn't have that test/error, so i've added it.

**Comment by stanmoore1** [comment]
Thanks!

**Comment by akohlmey** [comment]
> Thanks!

Looking at the message from the mailing list and double checking the code, I think there is a logic error in this test as the `PairHybrid::coeff()` function is called by both the Kokkos and non-Kokkos variant of the pair style. I have moved the test to settings (so the check is done when the pair style is created and applies to both variants) and also tested for the name of the style so that  it now only fails if the name of the pair style begins with "hybrid" and ends with "/kk".

**Pull request merged**
