### PR TITLE
USER-DPD small updates

### PR DESCRIPTION
**Pull request by timattox**
## Purpose

Propagate some older changes into the USER-DPD code that were missed, one change on the Kokkos side, the rest for non-Kokkos.

## Author(s)

Tim Mattox (Engility Corporation)

## Backward Compatibility

Shouldn't have any issues here.

## Implementation Notes

Ran our internal 28 validation benchmarks for USER-DPD and found no regressions.

## Post Submission Checklist

_Please check the fields below as they are completed_
- [x] The feature or features in this pull request is complete
- [ ] Suitable new documentation files and/or updates to the existing docs are included
- [ ] One or more example input decks are included
- [ ] The source code follows the LAMMPS formatting guidelines

## Further Information, Files, and Links

N/A.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@timattox looks good. I assigned this to @sjplimp.

**Comment by akohlmey** [comment]
@stanmoore1 please wait before the jenkins runs have (successfully) completed before assigning a PR to @sjplimp. this way we have the confirmation, that the code at least compiles with several settings (e.g. LAMMPS_BIGBIG, LAMMPS_SMALLBIG, parallel/serial etc. thanks.

**Comment by stanmoore1** [comment]
@akohlmey will do.

**Comment by stanmoore1** [comment]
@akohlmey is it possible for @sjplimp to merge the PR if the jenkins runs haven't run yet? If so, wouldn't it be good to prevent that?

**Comment by stanmoore1** [comment]
I mean prevent it automatically, rather than by human interaction of not assigning to @sjplimp...

**Comment by akohlmey** [comment]
@stanmoore1 jenkins on our server runs through docker and that is currently not reliable enough. this is in part due to several other tasks that we are running on that server and in part due to how jenkins is set up in general. we are looking into improving that situation through moving some load to dedicated machines and generally separating the jenkins server from the execution machines.

in the current setup, steve uses a custom python script, where he will only "see" a PR when it is assigned to him. so it is part of the jobs of the "lieutenants" (i.e. us) to only assign a PR to him, when it is ready and checked.

i just discovered, however, that this scheme has one weakness: i needed to assign PR #688 to steve, because he said it needs some more changes to core files (and then he would need to assign it back to me). this conflicts with our scheme. so we may need a different approach, e.g. a label "ready_to_merge". with our current workflow, i have to count on steve reading through the comments.

another option would be to change the merge policy on github. this would refuse merges not only on merge conflicts, but also on failed tests and pending reviews. these are in part rather new features in the github webserver and API, so they were not considered when steve, richard and i worked out the procedure and figured out what steve needs to put in his python github checking tool. if i would activate them now, it will likely confuse steve without reason.

we should probably have a conference call on how to streamline/update the merge workflow in a few weeks when we all have a little more time. richard and i are in crunch mode until early november.

**Comment by stanmoore1** [comment]
@akohlmey sounds good, thanks for the explanation

**Pull request merged**
