### PR TITLE
Bond style special

### PR DESCRIPTION
**Pull request by danicholson**
**Summary**

This bond style provides an alternative mechanism to create special bonds by creating an actual bond that calls force->pair->single(). It can be used to create 1-5 (, 1-6, ..) interactions.

**Related Issues**

There have been a few discussions on 1-5 interactions over the years on the mailing list (e.g. 
https://lammps.sandia.gov/threads/msg78113.html)

**Author(s)**

David Nicholson
MIT
davidanich@gmail.com

**Licensing**

By submitting this pull request, I agree, that my contribution will be included in LAMMPS and redistributed under either the GNU General Public License version 2 (GPL v2) or the GNU Lesser General Public License version 2.1 (LGPL v2.1).

**Backward Compatibility**

No issues.

**Implementation Notes**

There are requirements on the special_bonds command, since this command will create new 1-2, 1-3 and 1-4 interactions. These are detailed in the documentation and error handling.

In this example, I add 1-5 interactions to a united atom C8 molecule. These 1-5 interactions are the weighted by 1, and thus should be equivalent to pairwise ones. The script using bond_style special (in.c8-special) yields the same total energy as the one using the pair potential (in.c8).

[bond_special_example.zip](https://github.com/lammps/lammps/files/4141445/bond_special_example.zip)

**Post Submission Checklist**

- [x] The feature or features in this pull request is complete
- [x] Licensing information is complete
- [x] Corresponding author information is complete
- [x] The source code follows the LAMMPS formatting guidelines
- [x] Suitable new documentation files and/or updates to the existing docs are included
- [x] The added/updated documentation is integrated and tested with the documentation build system
- [x] The feature has been verified to work with the conventional build system
- [x] The feature has been verified to work with the CMake based build system
- [x] A package specific README file has been included or updated
- [ ] One or more example input decks are included

**Further Information, Files, and Links**

n/a

### CODE REVIEW

**Comment by akohlmey** [comment]
@danicholson not sure if this can work the way people will expect it. Let us assume you have a linear chain of 6 atoms, so you have bond A-B, B-C, C-D, D-E, and E-F. If you now add an explicit bond A-E, this will make this pair an 1-2 pair, instead of an 1-5 pair, and more importantly, the 1-4 pair A-D will become an 1-3 pair as well as the 1-6 pair A-F. Now you have different scaling factors applied where you don't expect it.

**Comment by danicholson** [comment]
@akohlmey One way around this is to declare `special_bonds lj/coul 0 1 1` and then explicitly define each special bond of order 1-3 or greater using this style. Another way is to use `special_bonds 0 x x` and use `angle` and `dihedral` keywords for `special_bonds` to avoid creating additional 1-3 and 1-4 interactions. You could use the `zero` styles for the angles and dihedrals if you don't actually have these interactions.

Currently, the code requires that 1-2 interactions have 0 weight, 1-3 interactions have either weight = 1 or the angle keyword on, and that 1-4 interactions have either weight=1 or the dihedral keyword on. I think this makes sense, but maybe I'm missing something.

**Comment by sjplimp** [comment]
@danicholson In another effort we are working on a polarized potential (AMOEBA from Tinker) which includes 1-5 weightings in all its pairwise terms.  We will likely add an option to special_bonds to tell it to make a list of 1-5 neighs, similar to the 1-2,1-3,1-4 lists now stored be each atom. Also some of the neigh building methods will need to flag neighbors with the additional weight flag.  Then potentially any pair style could use it.  E.g. LJ or Coul.  Could do similar I suppose for 1-6, etc.

Will that new capability replace what you are proposing here?  Or complement it in some manner?

**Comment by danicholson** [comment]
@sjplimp In principle, I think this style is more flexible since it can be used ennumerate any set of special bonds and assign their weights. With that said, I think the functionality that people are looking for (myself included) is 1-5 interactions. 

I can think of one potential use case for this style that may not be easily handled by extending special bonds to 1-5 or 1-6. If you have a large molecule and want to include only bonded interactions and short-range steric hindrances (e.g. the pentane effect  in polyethylene), you could use this style for the short-range pairwise interactions and turn off the actual pair interactions. This could potentially be useful in creating equilibrated melts for polymer models that have dihedrals (as discussed in your article on equilibration: Auhl et al., JCP, 119, 24, 2003). This is not something I have worked on. Just a thought.

**Comment by sjplimp** [comment]
@danicholson This new bond style is a clever idea.  It took me a while to get my head around how it works.  So I didn't make any changes to the code, but I added some content to the doc page, to hopefully help users understand how it works and how to use it correctly.  Please see if you agree with the new doc page.  Also there is a Q there about using this with long-range Coulombics, which I think should be clarified.  When the doc page is done, this should be ready to release.  Thanks!

**Comment by sjplimp** [comment]
@danicholson Just checking to see if you've had a chance to read my doc page changes for your new bond style.
No deadline on my side - but we are doing some work to finish up some pending pull requests.  Thanks.

**Comment by danicholson** [comment]
@sjplimp Apologies, I missed your initial reply. I will review the changes and get back to you early this week.

**Comment by danicholson** [comment]
@sjplimp To update, the changes to the doc page look good to me. With respect to the last question on long-range Coulombics, I am not sure what the answer is at the moment. I am going to do some testing and get back to you.

**Comment by danicholson** [comment]
@sjplimp To (finally) answer your question, this style is not compatible with pair styles that use long-range Coulombics. I mentioned this on the doc page and altered the code to give an error if a kspace_style is defined. It would probably be better to check whether the pair style specific to the declared bond is incompatible, but I didn't figure out a simple way to do this.

**Comment by danicholson** [comment]
Thanks @sjplimp and @akohlmey. I was thinking specifically of cases where the special bond is applied to a pair of particles that do not interact via electrostatics. Initially, I was thinking that such a system might have a different pair style for the uncharged particles, but upon reconsideration, I think it would make more sense in almost every case to just use the same pair style for the whole system (with appropriate charges set to 0). I think that permitting special bonds for interactions with w_Coul = 0 could be a simple way to allow such a system. I will look into it more when I get a chance.

**Comment by akohlmey** [comment]
> Thanks @sjplimp and @akohlmey. I was thinking specifically of cases where the special bond is applied to a pair of particles that do not interact via electrostatics. Initially, I was thinking that such a system might have a different pair style for the uncharged particles, but upon reconsideration, I think it would make more sense in almost every case to just use the same pair style for the whole system (with appropriate charges set to 0). I think that permitting special bonds for interactions with w_Coul = 0 could be a simple way to allow such a system. I will look into it more when I get a chance.

@danicholson there are two "rules" that apply when using long-range electrostatics with a KSpace style:
1. When using a KSpace style, **all** coulomb must be of a compatible type. No cutoff coulomb is allowed at the same time
2. Pair::single() will include the erfc() damped coulomb interaction. For a "special" pair, however, you must compute the force/energy removed based on the full (undamped) coulomb, since the part missing due to the erfc() damping is included in the KSpace computation (which also includes interactions with other periodic images of the same atom(s)).

**Pull request merged**
