### PR TITLE
cmake: add link deps to pkg-config file

### PR DESCRIPTION
**Pull request by junghans**
Adding static link libraries to package config file.

### CODE REVIEW

**Comment by junghans** [comment]
@akohlmey please have a look if you like that approach.

**Comment by akohlmey** [comment]
> @akohlmey please have a look if you like that approach.

I will look into this some time next week. Currently I am focusing on refactoring the library interface and its documentation.

**Comment by akohlmey** [comment]
@junghans this looks ok to me. I don't consider it very important since I see the main use of static libraries when you want to include the LAMMPS sources into a large project and link with it statically.
For packaging and other systemwide installation, using the shared library has many advantages, and thus should be the preferred option. For the default settings with the legacy build, the static library has to be the default as this is the traditional behavior and creates a single standalone executable. And because of that the default for the CMake configuration has to be the same to have a consistent behavior (I just worked hard to make both compilation approaches more consistent).
So this reasoning has to be added to the documentation at some point (best after some of the other moving pieces have been included).

**Comment by akohlmey** [comment]
oh, and this needs to be updated to the latest master and the libraries have to be renamed, since the installed libraries are not `lib<somename>.a` but are now `liblammps_<somename>.a`.
(except for the client-server library).

**Comment by junghans** [comment]
> oh, and this needs to be updated to the latest master and the libraries have to be renamed, since the installed libraries are not `lib<somename>.a` but are now `liblammps_<somename>.a`.
> (except for the client-server library).

Should we just disable installing of static libraries and call it a day? And then remove the special code for handling that?

**Comment by akohlmey** [comment]
> > oh, and this needs to be updated to the latest master and the libraries have to be renamed, since the installed libraries are not `lib<somename>.a` but are now `liblammps_<somename>.a`.
> > (except for the client-server library).
> 
> Should we just disable installing of static libraries and call it a day? And then remove the special code for handling that?

... and wait until there is a convincing use case to consider re-introducing it. yes. We should then also remove the section from the `doc/src/Build_link.rst` file.

**Comment by junghans** [comment]
> > > oh, and this needs to be updated to the latest master and the libraries have to be renamed, since the installed libraries are not `lib<somename>.a` but are now `liblammps_<somename>.a`.
> > > (except for the client-server library).
> > 
> > 
> > Should we just disable installing of static libraries and call it a day? And then remove the special code for handling that?
> 
> ... and wait until there is a convincing use case to consider re-introducing it. yes. We should then also remove the section from the `doc/src/Build_link.rst` file.

Closed in favor of #2048.

**Pull request closed without merging**
